Add comment for v0 . 8 . 4 release
Update chagelog
Added image for instructions on setting up a BigBlueButton VM
LRQA - 18330 rename step 1
Add referenced image file
Added mavenCentral ( ) repo to ant build
Upgrade maven - javadoc - plugin to 2 . 3 . 1
Adding examples about the wiki
Fixed a bug in the body
CursorToBulkCursorAdapter . Close must call mCursor . Close instead of mCursor . Deactivate .
Fix README . Md file
Prepare release checkstyle - 6 . 8 . 1
Update version code
Update Flow to version 0 . 5 . 1
Add ' include ' to the index list in the script
Added a documentation to the wiki repo ( add behalf of Heather )
Ignore Vim swap files
Removed non - needed imports
Add config_use_strict_phone_number_comparation , which will be used by default applications .
Setting version to 1 . 0 . 124 - SNAPSHOT
Added Circle CI configuration
Delete com . 4 . Tools from grails - bit .
Remove useless import .
HHH - 8733 - General build cleanup - cli - 2 . 1 . 0
Delete strings . Xml
Add qr codes
Revert " Revert " LPS - 54998 SF
Adding space for sidebar image so that they are done with a image
Added IDE - specific files to .
Add logging file for new documentation .
Fixed a typo in README . Md
Remove unused screenshots
Prepare release v1 . 2
Bump engine . Io - client
Fix error in docking station on chunk unload , fixes # 2898
Prepare 3 . 0 . 0 .
Do not use the lastest tool on travis
Update killbill - payment - test .
Provides a more recent snapshot of the wiki
DO NOT MERGE - Updated ADB icon
Return the crash if there if it is open
Added HdrHistohram . Jar to base directory for convenient downloading
Renamed rnc file .
Don ' t append jars
Add serialVersionUID to NotSupportedException
Added STORM - 885 to CHANGELOG
Update to the latest support lib
Bumped version number to 1 . 4 . 1
Prepare release 0 . 8 . 4
Add service messages for CASSANDRA - Retina devices
Add link for # 1112
Remove redundant openjdk7 , non - existing openjdk8 from Travis - CI config
Def would create a local variable , but we want to access the field
Fixed bug in org . Mongodb . Kotlin . Js
Cleaning up more bind ( ) file
Fix problem with Gradle snippet
Fixed merge files for pr # 283 .
Setting version to 1 . 0 . 8 - SNAPSHOT
Update the version to 1 . 3 . 0
Add virtual destructor to contributors list
Added design gif
Revert " LPS - 46699 - CAS connection test results have the same style regardless of pass / fail
Update pom . Xml
Don ' t force apply on non - printable character
Releasing OrientDB 2 . 1 - rc6
Updated NOTICE file
Created tech - debt entries for all components and laboratory components .
Added travis . Properties
Added images for 3 . 2 . 0
Update linux - x86 natives
Removed tag flyway - 1 . 7
Fix test data
Add STORM - 1125 to CHANGELOG . Md
Fix a typo in the init script in the same test data
Fix a bug in init script
Fix check for non - index layout
LPS - 55725 Remove unnecessary new line
Changed version file to Dev Build to prevent confusion .
Fix for java 3 . 0 - dev an issue
Prepare for next development iteration
Add STORM - 1842 to changelog
Added Android SDK Platform with API level 16 to Travis build file
CAMEL - 1932 removed slf4j - simple dependency from camel - mina pom
Removing empty line .
Include a typo in test
Require Maven 3 . 0 .
Removed groovy build from library
Updated VERSION . Txt for 2 . 8 . 1 .
Reduce the stack used in the network checking
Add new module to enable repository
Add new words to the approve_regex
Removed unnecessary blank line
Fixed possible window in ping . Json
Fix tests for file 8
Add support for travis - ci
Update the sample APK .
Adding support submodule for Link to fix doc
Add a simple travis configuration
Added Tightdb JNI library for linux and README .
Do not show animator in tests
Update build tools for travis
Removing an empty line
Upgraded to ES 0 . 4 . 1
Updated proguard
Increment gradle build tools
Added tools . Jar again to keep Russel happy and the javac ant task working ; )
Add Compression . NONE
Add STORM - 118 to CHANGELOG
Updated Gradle plugin to 2 . 0 . 0
Add android jar file
Bump version from 1 . 7 . 8 - > 1 . 7 . 9
Removed debug output
Delete demo2 - badge .
Added fake font capability
Update libwebp
LPS - 65920 ( WEB ) Move xml files
MinecraftForge / FML @ 9520978b81d4cba5d8b0af0d5f155bd115023795 Use a temporary file for recompile ' s command line to combat command length to long issues .
Use both JDK7 and JDK8 in Travis
Set component configurations correctly for trident spouts
LPS - 32314 Add @ Override
Fix doc
Make gradlew to be an executable file .
Now removed connect - js submodule
Updated version code .
Change EditDistanceJoiner . Jar to newest version
Add SQL Console module to jOOQ - Copy authors . Txt
Setting default name for multi - project
Starting 0 . 5 . 3 - SNAPSHOT
Set max request focus for tearDown ( )
Fix build error in README
Smack 4 . 2 . 0 - alpha2
Remove empty lines
Removed unnecessary code from sample
Updated android natives
Updating Alloy to rev . 74817
Adding cpp property to com . Android . Io . Io . Js . Org . Android . Kotlin .
Updated version name / code
Fix Readme . Md
Don ' t run test as part of Java 7
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Add local . Properties to .
Proposed bug fix
Source jars are missing sources for classes written in Groovy
Removed Key Value Server from SVN repository .
Remove an unnecessary dependency in core module in manifest
Removing old ejb 3 . 0 . 0 jar
LPS - 67023 Add new module to the portal build
Deploy gh - pages
Added makeGLMModel call to python .
Fix the build .
Added activiti - archetype - api to debug module
Removed unnecessary import
Remove profiler arguments after start ( PY - 15771 )
Update demo
Add forgotten options in makefile
Setting version to 1 . 0 . 92
Revert " Caching dependencies to speed up PR builds "
Added support images for android . Properties
Add toString ( ) to kotlin .
Fix for bug where we don ' t generate anything properly as we don ' t exist
Added Travis . Properties file to enable Travis CI .
Delete outdated wiki snapshot ( replaced with Asciidoctor documentation )
Removed old NOTICE file
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . .
Removed tag roboguice - 1 . 1 . 1
Added STORM - 1572 to Changelog
Added STORM - 66 to Changelog
Added STORM - 351 to CHANGELOG
Add 2 . 2 . 0 zaphelp jar
Removed extra newline at the end of the file
Fix failing test # 70 .
Ignore gradle - build . Xml and .
Add words suggested by users
Regenerate gradle - wrapper . Jar using 1 . 10
Removed unnecessary test
Regenerate gradle - wrapper . Jar with 1 . 9 - rc - 4
Remove deprecated comment from comment
Removed ' var ' because it wasn ' t necessary
Removed old ejb 3 . 0 jar
Change gitignore file .
Revert " LPS - 56346 Backward compatibility to 1 . 6 . 1 "
Added tag 0 . 5 for changeset d04a8ef4ccb0
Restore execute permissions
Temporarily also include eglTerminate - bit on config , no longer no longer needed
Added version 2 . 2 . 3 snapshot
Changed version
Added relative path to the parent POM so that the user won ' t need to
Make new img ( no longer no classes )
Do not call WebTextView ( IDEA - 152896 )
Changed Target SDK to 21 ( Lollipop )
Revert " LPS - 60569 Update release 2 . 3 . 3 "
Prepare next release v0 . 91 . 1 - SNAPSHOT
Adding location method to singleton class template
Changed version number for v1 . 3 . 0
Fix bug in dataPath ( )
Add xhdpi launcher icon .
Added missing method to super . Close ( ) which will be used by default 2 . X ( IDEA - ) )
Don ' t run emulator and running in ci config
Add 1 . 8 . 4 to com . 7 . 1 error
Prepare version 22 . 0 . 0 - beta1 .
Set source encoding to UTF - 8
Fix merge conflict resolution
SONAR - 1065 Reformat and remove an language field in toString ( ) for shutdown ( PY - 15771 )
Fix typo which cause stack overflow if children ( ) was called
Updated studio
Added one more sample to fix ( I don ' t re )
Create grade files to appease NetBeans plugin
Add support lib to SeriesGuide project , too .
Added idea output directory to .
LPS - 50321 missing @ override
Removed unused semicolon in UrlMappingUtils
Added padding to in headless class so it does not make a static api
Remove debug statement
Fix FrameworksServicesTests . Apk to include libc + +
Updates smack jar files to the version which contains all patches from libsrc repo .
Bumped version to 0 . 8 . 3
Updated pom . Xml version to 3 . 0 . 3
Updating samples for v1 . 5 . 0
Moved test to NOPASS .
Add a README file so that we can be supported on testing
Added examples image for new documentation .
SONAR - 4970 Add a constant for dialogs list
Add android jar file
Added console # 254
Remove unnecessary dependency on Clang headers .
Removed unused import which is no longer used .
LPS - 52594 new sdk uses 1 . 0 . 0 ServiceBuilder
JAL - 35 Add image notes to non - proprietary licenses
Fix typo
Remove extra - maven - maven - maven tag in pom
Ignore blogs - demo 1 . 0 . 0 prep next
Move JS class back so it does not allow for failing tests
Added gitignore .
On behalf of Vincent Lucas , commits a fix to the calculation of the Last SR ( LSR ) timestamp for the Sender Report RTCP packet .
Add intelliJ files to gitignore
Add ' pre - null ' target to Ant build
Added documentation for the fill time .
Removed unused methods in sample index .
Revert " LPS - 50757 can we use the existing .
Removed old lib
Added favicon
Removed unused import from sample project
Removed profiler arguments after start ( PY - 15771 )
Remove scope ' provided ' from Groovy dependency because GMaven didn ' t like it
Add config_use_strict_phone_number_comparation , which will be used by default applications .
. 0 . 6 - SNAPSHOT
Stop compile error
Ignore * .
Switch version to 0 . 3 . 0
Updated help for 2 . 1 . 0 release
Add STORM - 1920 to CHANGELOG
Fixed PY - 6543 Django manage
Update the header of the function to add a blank line
Update windows natives
Prepare for next development iteration
Removed debug statement
Add ' var ' to ' shadowJar '
Fix problem with OTR images
Updated preview icon for Attach to Python store ( IDEA - 582 ) .
Don ` t hardcode the android sdk path in the build script before you push ( im looking at you Dave )
Updating Alloy to rev . 74817
Prepare version 20 - beta2 .
Upgraded maven - compiler - plugin version .
Updated icon for Py trip icon
Add maven plugin to gradle . Gradle .
Commit the height of the application code back to see if it will be used
Add Eclipse specific project files to ignore .
Remove logging on allow_failures , as it can be used in .
Created tech - debt entries for all components and laboratory components .
Added STORM - 205 to changelog .
Updated binary files for Android 4 . 3 + tests
Fix version number .
Added STORM - 1104 to Changelog
LPS - 61070 Add @ Override annotation for list of Application folder
Renamed class to fix capitalization issue
Fix a typo in help package .
Updated license file
Include install script for now
Fixed syntax for 1 . 8 . 7 awesomeness
Removing unused imports
Set source encoding to UTF - 8 version in javadoc
Remove unnecessary char from build . Gradle
Fill also include doLast ( ) instead of doFirst ( )
Added mockito support for v1 . 1 . 2
Add travis ci config
LRQA - 14606 Add test property for calendar - portlet
Remove unused files .
Updated reference to reference to match actual stops
Build fix ( ConvertLambdaToReferenceIntention )
Remove unused blank line
Removed unused import
Gh - 49 Build fix ( sears )
Prepare 2 . 2 . 0 release notes
IDEA - 117674 please rebuild and commit runnerw . Exe
Revert " Change revision property for 5 "
Add STORM - 1633 to CHANGELOG
Remove whitespacek
Fixed a problem with spaces
LRQA - 23204 Add new component for testing plugins
Don ' t run performance tests in travis
Delete outdated wiki API , replaced from java 3 . 0 .
Adding small doc file for v1 . 3 . 3
Removed the wrapper file
Add 222
Removing empty lines from git
Add 1 . 0 . 1 to build on android
Added performance test for Android 4 . 0 plus a comparison to 2 . 3
Added Travis config .
Add a redirect for / user module html
Return the view here .
Removed @ Override from interface method
Set default encoding to UTF - 8 ( fixes # 192 )
Add a toString method to avoid exception of supported events as well .
Fixes a bug which is done using the last commit of the detection which is not necessary
Pushed 2 . 8 . 1 again , fixed a small UI issue .
LPS - 55274 don ' t check this in
Fix build . Sh
Test travis CI .
Add STORM - 1079 to CHANGELOG . Md
Add examples image for new documentation .
Fixes a bug which could cause CPU starvation while receiving from MultiplexingDatagramSocket .
Removed TODO to CHANGELOG . Md
Remove extra line .
Corrected permission name for ' poweredBy '
Added SQLDialect
Add stacktrace for travis unit tests
Revert " Change User width , re - better does not have sense to affect dependencies .
Prepare release storm - hbase - 0 . 1 . 2
Revert " Revert " AudioFlinger does not remove any test that uses it is gone .
Update msn lib
Help topics for VCS configurables ( IDEADEV - 33672 )
Add Eclipse files to .
Upgraded parent declaration in all trunks to use version 1 of parent - central .
Removed logging errors
Add android jar file
Upgrade netflixoss Nebula plugin to 3 . 2 . 2
Ignore dependency - reduced - pom . Xml in .
Testing travis - ci
Added openjdk8 to the list of a openjdk6
Ignore Eclipse ' s .
Ignore " bin " directory ( created by Eclipse )
Delete outdated wiki snapshot
Removed old xerces jar
Remove some whitespace in bbb - conf
Prepare 0 . 6 release
Fix pom . Md
Added preview image
Mark offset gamma test as NOPASS , even though it ' s passing , as it affects other tests by updating the R GBM packge . "
Add image for instructions on setting up a BigBlueButton VM
Add demo icon for new wiki
Removed Key Value Server from SVN repository .
Update doc
Remove some whitespace in titan - runner
Update travis
Fixed # define conflicts with new private view
Make addPropertyDirect ( ) method in NeoApp . NeoAppRelationshipType . . . Otherwise
Add support for JNI library .
Provides a more recent snapshot of the wiki
Remove extra space in manual
Remove @ SuppressWarnings ( " # 1039 )
Add Arabic , displays to license list
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
LPS - 68937 ( WEB ) Move icon File
Fixing file to make it work in unit test
LRDOCS - 18330 rename step 1
Remove x bits from java files
Added missing jar file
Added parsing of Cython typedefs
LPS - 15662 Options icon in portlet title bar shows weird text
DO NOT MERGE - Ringtone bugfixes ( round 1 . )
Don ' t send inline dial option by default
Updated CHANGES . Txt for compatibility in README . Md
Fixed bbb - record - rest - index .
Gh - 49 Build comments
LPS - 43715 Ignore icon in the build
Temporarily also include eglTerminate - > eglInitialize hack for 8k
Added art image
Delete README . Md
Added jar file
Updates the size of the gifs and updated the icon from the Wiki .
Added image for instructions on setting up a BigBlueButton VM
Update travis . Yml
Remove @ nosideeffects from DataTransferItem . Prototype . GetAsString ( )
Add support submodule to help with testing support
Remove the unnecessary empty line in / usr / share / opentsdb / test / tsdb .
Add clojure . Ipr and clojure . Iws to .
Updating Alloy to f4bbdfc , 1 . 5 . 0
Reset drawable refresh button with orientation dialog after batching .
Removed @ Override from interface method
Added gitignore
LPS - 4668 - MB Emoticons need better z - index
Added files via upload
Removed an extra line at the end of the file
Don ' t index unsaved files ( ie , no context )
Revert " GRAILS - 4759 - updated ehcache to 1 . 6 . 1 "
Add CAP_BLOCK_SUSPEND to system server
Do not update accessibilityTitle in
Update sample jar to v3 . 0 . 1
Tweak proguard rule to attempt to solve XPrivacy
Remove redundant version number from sample project
Ignore kotlin - reduced - pom . Xml in .
LPS - 50748 move icon
Update applet zip
Add xxxhdpi images for intellij_info_aspect .
Added support lib for v1 . 1 . 2
Allow proguard config for unit tests .
Remove TBD from Question 1 . 1
Fix proguard
Replace wiki image
Added STORM - 499 to changelog
Add notes about JDI
Add launcher icon for new documentation .
Added library version
LPS - 65490 Compile for Android 1 . 6
Removed unused import from AndroidManifest . Sh
Fixed zeroClipboard . Min . Js
LPS - 62787 prep next , use latest
Updated build tools version to 0 . 7 . 0
Include some typo in bbb - conf
Removing useless logging .
Fixed broken test structure in terminal ( PY - 12782 ) .
Remove accidental AIDL methods .
Update travis to 1 . 8 . 0
Fixed a compile error .
Updated Changelog with STORM - 612
Update the list of the root project
Fixed the name of the NSMutableDictionary for the same task ( IDEADEV - 9314 )
Fixed unit test ( PY - 4087 , PY - 4088 , PY - 4089 )
Updating to Gremlin 0 . 8
Bump package . Json version to 0 . 4 . 4
Fixing an issue with isLocal ( which is no longer needed
Use the type of the sort style for start , as it can be used again .
Forgot a sentence .
LPS - 55480 Regen , ran " build - client " in portal - client
Don ' t generate icons for IntelliJ laf
Revert " LPS - 52740 Language properties "
Fixed bug in divider rather than copy up view .
Removed method that doesn ' t do anything
Update travis config
Fix a bug in svm . Cpp
Prepare for next development iteration
Remove android - android - plugin . Gradle from gradle . Properties
Built the latest snapshot
Removed version from pom . Xml
Fixed some problem with spaces .
Added maven - debug .
Add note about part of sample project
Git ignore gradle . Properties
Add version to gmaven - plugin
Don ' t accept " Schienenbein " ( - > Schienbein )
Fixed bug in org . Parboiled . Common . Reference
Adding hasFlash ( )
Incremented the version code of the sample project for GPlay upload .
Bump version from 1 . 7 . 10 to 1 . 0 . 10
Add new default material mapping for README ( # 32 )
Fixing syncDoc task to make it ' s specified
Enable break with spaces
Include a file that was failing in bbb - api
Remove unused import
Add NetBeans project files to gitignore
Add changes to README
Add stacktrace for travis runner
Moved META - INF / LICENSE .
Add getter image for index view
Fix finalization
Removed package statement as we ' ve stuff in groovy .
Add entry flag to README
Changed package name for older cygwin installations
Added image back
Remove an extra newline at the end of each test
Prepare 2 . 0 . 0
Make gradlew to be an executable file .
Add claims test for Android 4 . 0 . Zip file
Fixed broken test
Updated gradle wrapper to 2 . 1
Updated version for 0 . 5 . 0 release
Add CodeNarc rule exclusion
Changed test passing statuses ( munging / exec / pub - listener
Delete junk
Added upgrades . Txt to index of installation - deployment chapter
Add missing @ override to externs file html5 . Js .
Skip an typo in reference ( PY - 20458 )
Add images for instructions on setting up a BigBlueButton VM
Move unit test for unit tests .
Default native proto to correct port in Config
Fix missing import error ( PY - 19862 )
Rename file to match right location
Bumped version
Revert " force monospace font in qt preview "
Remove extra newline at the end of each test
Modify license file to test cruise ( IDEA - 152352 )
Remove obsolete script
Added missing @ override to externs file html5 . Js .
Updated knit icon
Added STORM - 1408 to Changelog
Remove - - debug option
LPS - 63740 Add javadoc file
Updated pom
Fix bug in help handling .
Remove unnecessary dependencies from Travis config
Push version to 222 .
Updated build . Properties for 0 . 3
Updated changelog for 0 . 9 . 0 release
Update xsoup to 0 . 2 . 1 # 75
Woops java type checks !
Update travis
Documented the changelog for the changelog "
Updated reference to library after rebase
Removed " b / > out from bin .
Removed extra @ Override from the init script .
Include syntax error in readme
Removing obsolete files
Prepare for next development iteration
Add Thumbs . Db to gitignore
Rename file to match class name
Updated splash screen for linux as well
Fixed tests in last commit
Updated version
Bump the version number to 2 . 0 . 3
Created tech - debt entries for all components and laboratory components .
Add NOTICE file
Added # hashCode ( ) to JID to be fully comparable .
Added native version of Sample project
Added missing change in README . Md
Added a super . Shutdown ( ) to newly added a images "
Added missing support
Fixed bug in iterate file .
Updated convert . Properties
Add tests to travis .
Set javadoc plugin for multi - project project
Update doc commit pointer
Removed old nfc jar
Added newline at end of file so it does not be used in the documentation .
Update native lib
LPS - 45448 update jar
Update crate - sql - plugin to fix bug
Fixed a bug in spaces ( PY - 20458 )
Fixed typo in org . Mongodb . Xml file
Prepare version 29 - beta2 .
Ignore * .
Fix gif url
Update gitignore to exclude the lib directory
Update 2 . 2 release
Added images for installing BigBlueButton VM
Prepared for next development iteration
WFLY - 6768 ServletResourceManager does not implement isResourceChangeListenerSupported correctly
Rename bash to contain folder
Added STORM - 792 to Changelog
Remove runit_NOPASS_Rdoc_prcomp .
Added bundler - y entries to .
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Added activiti . Util . Js + test to run only template
Add note of c / c / ext .
Fix possible NPE in lights ( PY - 17261 )
Remove trailing whitespace
LPS - 66316 ( WEB ) Move css file
Push a index of the statistics button so it will be used again
Added STORM - 820 to Changelog
Fixed test data .
Fix typo in fill DB .
Fixed checkstyle errors when opening it is a file before opening it .
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . Otherwise
Removed extra line at the end of the file
Updated TODO
DO NOT MERGE - Updated VPNServices stat_sys icons
Remove boost iostreams include from FilePath . Hpp
Ninja - correcting the the dependency for LOCAL_ONE in " switch " target "
Removed debugging messages in pom . Xml
LPS - 51179 - add test dir for portal - bundle
Add JDK 8 to Travis build .
Fix failing test , account for url - mappings - report
Fix typo in cxx_library example .
Override script to skip connectedCheck for now
Fixed bug when trying to rotate image when trying to rotate ( IDEA - 22515 ) .
Prepare release checkstyle - 6 . 15
Rename LICENSE to v1 . 0 . 0
Updating Alloy to rev . 74817
Updated jsr166e to version 0
LPS - 51081 Ignore extracted files
Only show scrollbars in the init class .
Removed unused asset
Fixing typo in bbb - conf for CASSANDRA - 5175
Removed print statement which was accidentally left in the file
Fix # 184 , refs # flaw ( # 1039 )
Added image for instructions on setting up a BigBlueButton VM
GRAILS - 8733 - General build cleanup - hibernate - testing
Don ' t use stlport .
Add todo for com . Mongodb . Com
LPS - 66316 ( WEB ) Move css file
Added STORM - 893 to Changelog
Add stacktrace for travis option
Remove unnecessary import .
Bumped version to 0 . 6 - SNAPSHOT
Updating Alloy to f4bbdfc , 1 . 5 . 0
Updated the zip file .
Remove unused import
Removing an extra line that was accidentally left in the file
Remove accidental postag from the init script .
Added missing submodule to readme
Accept android sdk licenses on travisci
Aligning version to the next version , with - SNAPSHOT
Updated travis . Yml
Updated eurosport cert so that SSL tests now works again
Removing empty JAR file
Don ' t delete jars that doesn ' t exist anymore .
Add javadoc support for gradle build since it compiles
Prepare next development version .
Created tech - debt entries for all components and laboratory components .
Updating Alloy to rev . 74817
Removed unused import .
Back svnkit 8179 since 8183 does not perform move correctly
Bumping versionCode 196 for 4 . 3 . 2 - SNAPSHOT .
Add examples image for README . Md
Fix leak of stackTrace in java / lang / Throwable .
Updating fabric directory from repo to public
Add GFM input for typescript
Update gif png
Added support for travis - ci
Don ' t include empty line for 60 seconds ( PY - 24429 )
Upgrading parent version .
Add missing import .
Add Travis configuration .
Ignore Intellij project files
Added activiti - archetype - unittest to the deploy profile as well
Fixed error when trying to rotate image when focus does not make a init .
Do not show leak in shutdown ( PY - 38918 )
Updated help for 2 . 1 . 0 release
Remove unused semicolon in UrlMappingUtils
Upgraded the version in the parent pom references in our example components to 3 .
Update to latest android build tools
Update the sample APK .
Add changelog to ignore list
Move to nebuladotNetflixoss 2 . 2 . 0
Add missing property to README
Revert " Restrict S3 deployment to actual tarball "
LPS - 33648 - Remove the constraining width from AutoComplete suggestions popup
Added forgotten package file
Remove extra newline at the end of each test
@ Deprecated does not have effect in Groovy
Fixed an issue with Packet Loss Concealment ( PY - 5417 ) .
Changed dependencies to milestone versions in preparation of tagging
Fixed a bug where the handler ' s not used by default .
Removes attempts to register the speex JavaEncoder and JavaDecorer classes , since they are exluded in the default libjitsi build , and trying to register them raises exceptions .
Update Studio
Removed unnecessary tag
Revert " Bumps commons - pool2 version to latest "
Changed target of Guava to UTF - 8
Add new class to the runner list in the samples
Fixed bug in org . Destroy . Impl . Js . Js
Adding NightlyBuildID . Java to .
Adding STORM - 1103 to CHANGELOG . Md
Add missing LOCAL_MIN_SDK_VERSION for Support Library demos
Removed unused spaces from manifest ( # 57 )
Rename setup_environment to install_frodo .
Fixed bug in org . Parboiled . Common . Reference
Removed Yaml and JSP tabs from " Other languages "
Jitsi videobridge - remove redundant bouncy castle jar file
Added Readme to v1 . 2 . 0
Built new snapshot
Fix Internal . InMilliseconds ( # 4191 )
Fix config
Prepared 0 . 8 . 0 release
Git add a newline at the end of the file , I can be supported rewritten
Added phonegap icon to demo2
Adding images for installing BigBlueButton VM
Updated banner to show 0 . 63 - Beta
Fixes java 1 . 5 compatibility .
Reverted changelog for STORM - 745
Delete README . Md
Add screenshots for installing BigBlueButton VM
Exclude checkstyle configuration in pom . Xml
Add words suggested by users
Remove background color from welcome fragment
Removing unused test
Add support for net . Hpp
Delete dimens . Xml
Ignore some bug in bbb - conf
Prepare release acra - 4 . 6 . 0
Add cloud - gce module
Add plugins to 0 . Txt for 2 . 1 . 1
Make spark . Response ' s body method public ( # 8 )
Bump curr . Release to 1 . 1 . 1
Add CLA so that OTP can be fully dpi for now .
Add STORM - 853 to changelog
Hmm , maybe * .
Removed old jars
Revert Studio to 2 . 0 . 2
Upgraded netty to 4 . 0 . 22
Remove mongo . Gradle
LPS - 43729 - Blogs subscribe links not contained in portlet string
Corrected the groovyBundleVersion in build . Properties for the new 1 . 8 . 0 - beta - 1 branch .
Fixes an empty string if there is not applied , when it is disabled
Removed unnecessary warning that doesn ' t be been called .
Dropped META - INF / MANIFEST .
NETTY - 371 OSGi Manifest requires Bundle - BuddyPolicy for
Update gradle build version to 2 . 1 . 2
Removes attempts to register the speex JavaEncoder and JavaDecorer classes , since they are exluded in the default libjitsi build , and trying to register them raises exceptions .
Prepare for next development iteration
Update preview image
Remove freemarker . Jar again
Don ' t update TextureView ' s surface if the Layer doesn ' t exist ?
Add link to stack overflow
Remove x bits from java files
We don ' t need these classes any longer
Ignore calevent - importer 1 . 0 . 0 prep next
Ignore emacs backup files .
Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode .
Update win32 - x86 native
Fixed Android Support library for Cropper .
Update crate - plugin to 0 . 8 . 0
Added missing params
Removed empty lines from bbb - client
Update sparc natives
Fix linebreaks in summary in README
Setting version to 1 . 0 . 12
Adding lib for MC 1 . 7
Added bouncycastle jar file
Remove unused AIDL methods .
Updated icons to better comply with Android Developer Guidelines .
Added forgotten method in AndroidManifest .
Fix typo
Allow plugins to use UTF - 8
Updated demo instructions in README
LRQA - 16988 Remove unused property
Added missing @ Required
Make gradlew to be an executable file .
Removed unused file
Changed version to 0 . 1 , since the 1 . 0 was just the in build name .
Revert " LPS - 48038 SF "
Started work on the ICQ / AIM protocol provider implementation
Set source encoding to UTF - 8
Removed roles from neo4j recipe , since they can not be part of a recipe
Updating Alloy to rev . 74817
Upgraded parent version .
Fix race condition in ZRTP state engine
Added @ since javadoc to the allowed option .
Added STORM - 1423 to Changelog
Smack 4 . 0 . 4 - SNAPSHOT
Updating Alloy to rev . 74817
Removed debug statement that was accidentally ignored by default
Add maven enconding property in build . Properties
Enable on_start notification always
Fix typo in pom . Xml
Added STORM - 1219 to Changelog
Add an empty line
Removed unused import from Java 7 since it ' s been abstract .
LPS - 66316 ( WEB ) Move css file
Add GuavaLib target to j2objc . Gyp .
Removing test that is no longer used
Remove old listwidget preview image
Don ' t need the upgrade plugin .
Added demo gif
Releasing OrientDB 2 . 1 - rc6
Added missing BenchmarkRunner config for svenson JSON databind
Update emitter version
Updated paper for language sweep and added code sample
Remove @ nosideeffects from DataTransferItem . Prototype . InitMessageEvent .
Prepare for next development iteration
Replace Task in diagram with FJTask .
Add GC thread to RSGL .
Add maven central to travis
Added exception to super . Shutdown ( ) putting the end of each method
Added tag 0 . 0 . 7 . 7 for changeset f415c01ff925
Remove " allowBackup " from Manifest
Renamed test file
Bump common ref for fix ( 1 . 5 . 0
Remove warning from EOF .
Fix project in library .
Add travis - ci config ( # 36 )
Fix pom . Md
Release pegasus 2 . 6 . 3 .
Adding missing method to super . Shutdown ( ) which we don ' t re it anyhow .
Revert since it breaks a unit test
Adding docs for 1 . 0 . 1 release
Added test & submodule so it can be called in ` zip ` file
Added missing def
Testing Travis Container Environment
Add blank line as end of server script
Update README . Md for version 0 . 1 . 3
Add preview image
Removed targetSDKVersion from AndroidManifest . Xml
Add new JSON file for github
Added readme for # 1112
Disable broken inspection by default
Remove unnecessary prop
Call invalidate ( ) in setCornerRadius ( ) , fixes # 87 .
Remove missing override entry
Add logo for instructions on setting up a BigBlueButton VM
Add verbose flag to com . 11 . 4 ( shanyu zhao via Thejas Nair )
Add small screenshots
Added LLVM bindings for PassManagerBuilder ( Mac OS X binaries ) .
Removing a trailing whitespace .
Created tech - debt entries for all components and laboratory components .
Add STORM - 1842 to changelog
Added OSSMETADATA for NetflixOSS tracking
In onKeyUp for DPAD_CENTER , show the IME for text state .
Release 2 . 1M5
Removed tag roboguice - 1 . 1 . 1
Skip tests for in - test tests
Add ICU as a java library into h2o - algos .
Ignore * .
Removed @ since tag that was not necessary
Add link to package index
Bump up pegasus version to 5 . 0 . 12
Added maven assembly to jmxtrans - all . Jar .
Modify install_fbthrift .
Fixed a small link name for README
Removed the unused stuff in the native project
Removing debug output .
Improve test for KT - 451 incorrect lines on Linux .
Update to latest android iconics
LPS - 57626 Migrate scss
Rename MENU . Md
Tip updated ( IDEA - 78127 )
Renaming 0 . 7 . 0 release .
Fix project in library .
Remove unnecessary dependencies from pom . Xml .
Add missing travis config
Added a META - INF / rules for Ubuntu
Update sparc jars
LRQA - 28693 Ivy needs mirrors - get
Changed dependency to BP 2 . 1 . 0 - SNAPSHOT
Removed broken import ( I accidentally do it )
Prepare for next development iteration
Push version to 17 - beta2 , 15031 .
Don ' t throw white profiles on account .
Remove unnecessary prop
Removed class that is no longer used
Update msn lib
Fixed NPE in Box . ExtendToEncompass , close # 1783
Remove double static check .
Removed unused methods
Add Joachim Semelman to the list of contributors list
Add - since flag for api level 19 to filter javadocs
Execute the typo in npm build
Fixed banner for landing page
Added STORM - 1473 to Changelog
Update travis config for travis
Fix a typo in documentation ( # 57 )
PY - 1065 Reformat and auto - import do not respect space - after - comma preference in multiline imports
Fixed some bug in manual ( PY - 15771 )
Add 2 . 4 . 1 to 1 . 3 . 0
Added Google to license .
Revert " Rollback avs to 2 . 3 . 3
Updated test for GROOVY - 3401 with a correct example showing that we can put a blankline before the colon
LPS - 69244 Move icon File
Added images for Play store ( new requirement )
Added STORM - 205 to changelog .
Made constructor public ( PY - 7983 )
Add STORM - 1450 to changelog
Fixed more subtle bug
Changed default item to false rather than changes
Updated mac natives to add new documentation
Remove extra comment that we ' can be done the wrong code
Added missing dependency .
Updated all icon to match same icon ( fixes # 144 )
Don ' t index unsaved files ( ie , no console )
Fix WorldEditPlayer . FindFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Added some icon to explain the Flexbox visually for Wiki .
Added version to checkstyle . Xml to prevent grails - specific tag so that doesn ' t need to
Fix PY - 2608 Icon links , have non - copyable
Add " cpp " target to the same package so that we don ' t now it
Updated the index to include AWS related info .
Updating Alloy to rev . 74817
Ignore portal - profile 1 . 0 . 0 prep next
Remove mavenLocal
Revert Studio to 2 . 0 . 2
Added virtual destructor to AsyncClient
Upgraded proguard to 5 . 2 . 1
Add - - flag to travis .
Updates file modes for some scripts .
Updated version to 0 . 2 . 1
Removed @ Overrides from the init script .
LPS - 55871 we should set _modifiedDate with modifiedDate
Setting version to 1 . 0 . 89
Remove stray comment
Turn off fixed rate scheduling in OpenGL
Updated false alarm in assets ( # 30 )
Do not call WebTextView . Js if it is not stuck .
LPS - 32257 Removed old jakarta - regexp config
Add classes to gitignore
Remove unneeded println .
Add SQL Console module to jOOQ - Copy authors . Txt
Removed tag roboguice - 1 . 1
Added support for AssertStatement
Upgrade gecko to 1 . 1 . 2
LPS - 35153 - Remove unnecessary CSS
CORE - 2136 Mysql must quote PARTITION as a content
Change Android build tools to 0 . 3 . 0
Changed dependencies to milestone versions in preparation of tagging
Add support link to template app .
Added images for instructions on setting up a BigBlueButton VM
Fixed bug in dumper ( PY - 4087 , PY - 4088 , PY - 4089 )
Added missing call to super . Close ( ) .
Fix memory issues
Add scenario margin back to com . Sun . Sun . Erb
Added maven - core - plugin .
MinecraftForge / FML @ 3231db9376766d619f942b6a526718daa3c68038 Sorta revert 908491d5e7ac26becdac938f38cc90d6b9d73ce1 but merge assets into the map , rather than force overwriting .
Update README . Md for version 0 . 1 . 3
Removed unused import
Removed print statement which was accidentally left in the file
LPS - 32314 Add @ Override
Set the height of the statistics button removed in shutdown ( PY - 15771 )
Update windows natives
Remove unnecessary performance line
Add extra - android - m2repository dependency in travis
Removing obsolete file
Learned some new structs from Blizzard ' s Hearthstone
Push version to 13 - beta4 , 11246 .
Fix typo in build . Xml
Add CASSANDRA - 10079 to changelog
Delete outdated wiki snapshot ( replaced with Asciidoctor documentation )
Ignore iml files
Update pom
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Removed unused com . Prototype . Zip file
Add config for unit tests
Added missing constant for Javadoc
Fix merge problem
Removed useless assignment .
Prepare for next development iteration
Bump common ref .
Remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed
Fixed broken test ( PY - 65 )
Add screenshots
Add an ensureOpen check to Publication . HasBeenConnected ( ) .
Updated reference for 1 . 1 . 3
Fixing license header in com . Phonegap . Api . PluginManager
Fix NullPointerException in A2DP methods in isKeyguardLocked ( )
Added relative path to the parent POM so that the user won ' t need to
LPS - 52594 new sdk uses 1 . 0 . 0 ServiceBuilder
Add an empty line needed for unit tests .
Should not be closing system dialogs when Recents is hidden .
Added files via upload
Setting version to 1 . 0 . 115
Includes the NOTICE file in the release
Delete ant - support - v4 . Jar .
Move test script
Prepare for next development iteration
Added slf4j - simple dependency for Eclipse
You don ' t need cunit in default
Revert eclipse project specific setting
Added a version to the end of the file 1 . 4 . 0 .
Updated reference to library after rebase
Bump the version of curr . Release to 1 . 7 . 0
Add SQL Console module to jOOQ - Copy authors . Txt
Fixed shell script name in README . Md
Rename README to README . Md to force latest sdocbook plugin
Adding a changelog for changes . Md
Fixed bug in org . Parboiled . Common . Reference
Fixed build tools version
Adding tools . Jar again to keep Russel happy and the javac ant task working ; )
Bump up revision number .
Remove @ Override from interface method impl
In onKeyUp for DPAD_CENTER , show the IME for text state .
Added bin to gitignore for eclipse
Prepare 0 . 4 . 0 release
Prepare next release v0 . 87 . 6 - SNAPSHOT
Ignore eclipse project files .
Revert Gradle version to 2 . 1 . 0
Gh - record Add " Make " portal - hostname " portal .
Removed portrait restriction in the SampleActivity declaration
Revert " LPS - 36642 rebuild ruby - gems "
Fix build
Add local . Properties to gitignore
Fixed problem with setText ( fixes # 47 )
Updated srcinc that works with spaces in the path
Updated splash
LPS - 65749 prep next , use latest
Fixed test for removing system ( PY - 4087 , PY - 4088 , PY - 4089 )
Fix a grammatical error in README
Prepare for next development iteration
Prepare release astyanax - 0 . 8 . 10 - SNAPSHOT
Fixing # 3134
Added ISchemableSpout interface
LPS - 67914 why do we need this ?
Prepare for next development iteration
Updated mockito to 1 . 8 . 0
Changed memory name for Android template
Change the problem in README .
Fixing broken dropdown asset
Signed disabler . Zip with testkeys
LPS - 52594 new sdk uses 1 . 0 . 0 ServiceBuilder
Fixed a bug with the init server to make it is not present .
Remove some debug code in ` runVerbose `
Fixed test compilation which may be used by different hard detection .
Don ' t highlight the exceptions on shutdown ( PY - 17261 )
Can ' t show empty sections in parallel "
SONAR - 17294 Add plugins api to travis module
Bump version to 3 . 0 . 0 - beta1
Fixed test data which was failing an empty code
Rename topics for GROOVY - 3401 with a correct package
Update location module
Removing test data .
Try it at a one - liner
Changed minSdkVersion to 8
Added logo for instructions on setting up a BigBlueButton VM
Set source compatibility in build . Gradle
Fix a typo in stress ( PY - 20458 )
Fixed a bug which is not necessary .
Removed print statement which was accidentally left in the top level .
Added relative path to the parent POM so that the user won ' t need to
Update changes
Add image for installing BigBlueButton VM
Added demo diagram for fundamental 6th practice2
Move tests to elasticsearch test framework
Updated libs
Update osx bullet natives
Add options to jetbrains . Dic ( don ' t need this
Added META - INF / plugin from src / bin folder
Updated documentation in 0 . 9 . 0 release
Testing Google Play because it is not used
Add netbeans folder to gitignore
Updated Symbolic Link to v1 . 3 . 0
Adding org . Java . Xml to HDFS - test page
LPS - 32314 Add @ Override
Remove unused jars
Upload 0 . 8 . 6 release .
Adding images for documentation .
Rogue line number for try / catch statement confuses IDE debuggers
Remove class that is no longer used .
Update Flow to version 0 . 3 . 1
Revert " LPS - 52740 SF "
Updated image of Vincent .
Mark offset gamma test as NOPASS , even though it ' s passing , as it affects other tests by updating the R GBM packge . "
Fixed test data
Reset build tools version for 2 . 3 . 0
Remove " notYetImplemented ( ) " from ControllerUnitTestMixinTests . TestAllowedMethods
Prepared for next development iteration
Added bin to gitignore
Adding empty line to try and test github webhook
Fix an memory leak .
Add the Gremreaper logo .
Fix ApplicationInfo copy ctor
Add 2 . 4 . 0 comment
Add config_use_strict_phone_number_comparation , which will be used by internal applications .
Remove an empty line in ` BuildRuleSuccess . Property ` .
Added groovy - api . Jar in the new ones .
Added activiti - archetype - unittest to the deploy profile as well
EGL14 . EglCreateWindowSurface should set producerControlledByApp
Fix case in CentOS script
Setting version to 1 . 0 . 108 - SNAPSHOT
Use okhttp 1 . 5 . 0 .
Add a release note in README . Md
Updated version to 1 . 2 . 1
Add ZIP bundling for debugging
Adding new image
Add some META - INF and services file specifying JimfsFileSystemProvider as a service provider .
Temporary disable install encoding on travis
Use the latest Android 2 . 0 . 1 "
LPS - 60633 ( WEB ) Move css file
Ignore translator - web 1 . 0 . 0 prep next
Update internal framework to API 21 ( lollipop )
Add STORM - STORM - STORM - STORM - STORM - 1243 to CHANGELOG
Do not show arbitrary string on HTML items
Make accidentally removed Util . Gwt . Xml ( PY - 9042 )
Removed unnecessary import in pom
Bump engine . Io - client
LPS - 45043 Remove unthrown exception .
Prepared 2 . 8 . 6 release .
Include an error which is done in the file which was set them in the client
Fixed a bug in the Tags methods that will be called in the static view .
Updated small screenshot size
Testing android - support - ci build
Add ' clustering ' to the DB list
Adding security - deny - uncovered test
LPS - 66316 ( WEB ) Move css file
Revert " LPS - 48038 SF "
Add examples image for Android 4 . Zip ( using 32 - 64 - bit )
Don ' t reverse the exceptions during shutdown ( PY - 125317 ) .
Help topic ( PY - 348 )
Freshen screen shots in help screens
Fix copy / paste error
Update location module
WCM - 627 prep next , use latest
Fixed spelling mistake in bbb - conf
Specify default user image for tests
Testing Circle CI
Include a bug in the end of the file before the lazy .
Added forgotten package file
Add org . Sonarqube .
Remove extra System . Out . Println from com . Mongodb . CommandResult . GetServerUsed
Lost mask_starfish .
Removing " allowBackup " from bin / bin / bin
Prepare version 23 - beta3 .
Bump maven lib version to 1 . 0 . 1 .
Updates build tools version to 2 . 1 . 2
Adding flow of exceptions at the com . Sun . Erb
Update msn lib
We don ' t need these classes any longer
Updated BP libs to latest version
Added fix test for Android 3 . 0 . 0 Release too
Updated Studio to work with submodule
Update crate - core to 1 . 0 . 1
Updating Alloy to 5887563 ; LPS - 31011
Updated images for landing page
Added images for installing BigBlueButton VM
Added demo gif
Remove trailling comma
Added upgrades . Pdf for v1 . 3 . 2
Revert " Caching dependencies to speed up other builds "
Revert gradle version to 2 . 1 . 3
Added upgrades . Txt to index of installation - deployment chapter
Fixing test .
Fixed the build for 0 . 6 . 1 branch
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Prepare version to 3 . 0 . 0 - beta1
Set back release properties
LPS - 63247 Add build . Xml
Fixed typo in cxx_library example .
Add groovy - boot - runner dependency
Update contributor list , add yaphet , bjlindeqiang , dingjun , Dollyn , feilaoda
Removed unused import from sample code
Testing out travis as ci
LPS - 67023 Add new module to the portal build
LPS - 63462 update jar
LPS - 64191 update jar
Added STORM - 1406 to changelog
Add default icons for Android 4 . 5 ( # 32 )
Updated CHANGES . Txt for YARN - 2503 .
Added newline to end of file adapter
Replace image for layout practice session 4
Update to latest android gradle build tools 2 . 0 . 0
Require Maven 3 . 0 . 1 problem
Add a @ Override to the supportsVariableLimit method
Add xml dependency to jetty - test
Add missing compounds
Learned some new structs from Blizzard ' s Hearthstone
Removed test for simulator .
Build # 5
Bump the version number to 2 . 1 . 1
Mention README and STORM - 1876 to README . Md
Fixed a bug with HttpMessage . Exit ( ) , not make it ' s not opened by default
Bumped version code
Fix travis config
LPS - 66144 Move css file
Fixed reference to ActorSerializer
Add chapter so that can run using another manifest "
FastArray doesn ' t overwrite toString ( ) method
Update the jar file .
LPS - 48539 Move TemplateResourceExternalizationTest to portal - service
Updated upload files for Spider .
Added activiti - archetype - unittest to the deploy profile as well
Don ' t draw terminal content out of the terminal panel component ( IDEA - 125317 ) .
Adding exceptions
Add android - android - plugin from grails - impl
No longer skip integration tests on Jenkins
Fixed issue with DimensionManager . ShouldLoadSpawn
LRQA - 28261 prep next , use latest
Delete outdated wiki snapshot
Fix typo in cxx_library example .
Changed components to use parent pom v 4 , producing source and javadoc jar packages
Fixed inline with Oleg ' s comments .
Fix version number
Fix travis
Fix spelling
Built the latest snapshot
Prepare for next development iteration
Added property for using 0 . Mongodb
Fix test for removing abc_max_actions_buttons .
Added a comment about the end of the script that is breaking the memory by the repository .
Added gradle . Properties to build . Properties
Update JIRA url
Enable toString ( ) method in PLWJGL , because it will find problems
Fixed test data which was accidentally left in the file root
Added missing super . Close ( ) so that it was not used in the last body .
Added android - support library , so the less unstable
Bump to version 0 . 4 . 2
Add placeholder for net ( String )
Added # hashCode ( ) to JID to be fully comparable .
Add notification default so it are needed in the host project
Run the same warning as you as it could running the problem in the same tests .
Removed extra newline at the end of the file
Remove unused import
Add image for installing BigBlueButton VM
Don ' t set RLIMIT on windoze , either .
Add bin to gitignore
Added link to readme
LPS - 61001 Move css file
Setting version to 1 . 0 . 79 - SNAPSHOT
Remove checked in svm . Cpp
Making spark . Response ' s body method public ( # 8 )
Updating XposedBridge . Png
Reverted pom to r2 since our build server can ' t handle r3
Add bin to gitignore
LPS - 66136 Move icon
Remove android - support - v4 .
Don ' t reference the enclosing type instance when it ' s not used ( memory optimisation )
Added forgotten module file
Updating Alloy to rev . 74817
Removed unnecessary redefinition of System . Out . Println
Update demo library
Updated version
Added files
Remove dependency with Java 8 .
Add Thumbs . Db to gitignore
LPS - 62570 win x64 3 . 3 . 6 lib
Made MongoException white ( PY - 7983 )
Added libsox - dev to apt - get install line in order to resolve all dependencies
CAMEL - 6872 Provide a doctype for the default list ID , so it ' s no longer used
Removed unused import from AnimatorSet .
Add link to Javadocs
DO NOT MERGE - Re - adding missing icon for fullscreen button .
Add travis ci
Bump common ref .
Update android tools to 2 . 1 . 1
Update to latest gradle plugin
Added mustache as a end of test file
Add image for launching on the BigBlueButton VM for linux
SONAR - 4252 update favicon
Remove useless code .
DO NOT MERGE - Updated textfield pressed state
Add new default material images
Adding Demo
Removing useless import .
Removed unused discard ( ) method
Ignore gradle files
Update travis
Updating Alloy to 5887563 ; LPS - 31011
Fixing build
Fix incorrect bug in CompilerExecutor . Java
IDEA - 151696 Add ' Liskov ' to the change list with the project
Added files via upload
LRQA - 26186 Add new property to track test targeting tests for Java 8
Updated demo
DO NOT MERGE Add go title to false alarm
Removed unnecessary return statement
Added newline to NoOutputException
Revert " Bump the version to 3 . 2 . 1 ( # 1127 )
MinecraftForge / FML @ c180d9b15735ce89a38c497acd65fa3fab595f77 Add a gradle file .
Added 1 . 3 . 0 base head note .
Decreasing default max connections per node to 10
Added gradle . Properties to git ignore file
Added inspection of running services
LPS - 54590 Add a line break to avoid access style definition
Add support for AssertStatement
Don ' t accept " Mitpreis " , add " xml ` to ' Quick use "
Updated convert . Properties
Updated the zip file .
Add Demo . Apk
Removed openid from grails - impl , , no longer work in java 1 . 0
Fixed the problem with spaces
Do not build gh - pages build .
Add missing property
Fix compilation error in bbb - conf
Added translation using Weblate ( Nepali )
Delete unused test .
Add org . Jetbrains . 4 zaphelp jar
Preparing WIP - Release v0 . 1 . 43 - alpha
Fixed bug in org . Destroy . Js . Js
Updating license file
Updated gradle plugin .
GRAILS - 80966 Debugger " Resume " button - right out to the " STOP " style .
Don ' t add " application " { param for manifest .
Ignore IntelliJ files
Update multiwords . Txt
Added new sample gif
Updated reference to library after rebase
Add JVM settings in gradle . Properties
Made the preview image .
Removed unused import from test configuration
Adding version for surefire - all to get rid of a dependencies
Removed ' var ' from ' client ' in ' gradle ' so it ' s there
Add zan - repo in distribution package
Make Tachyon - Perf a subproject of Tachyon
Add missing comment
Fix a typo
Setting version to 1 . 0 . 123 - SNAPSHOT
Added invalidateMaster method to control that behaviour from outside
Removed extra import at the end of the file
Added missing jar file
Remove reference to trigger build
Update travis config
Added a new version of app_konference .
Added mac gif for the README .
Fixed accidental suppressing of errors in unit tests
Fixed a bug in bbb - conf
Remove jslayoutjs annotation .
Add missing pkg statement to test
Fixed bug in iterate
Groovy Console - - Option to Auto - Save on Run - added missing action mapping entry
Remove deprecated constant
Add STORM - 1713 to CHANGELOG . Md
Bump to version 0 . 4 . 2
Revert " fix test "
Fixed compilation error in previous commit ( PY - 7983 )
Added file to .
Removed old lib
Added titan . Properties file for Play 7
Add shell script to org . Cpp . Js ( # 8 )
Removed useless import .
Push version to 13 . 1 , 11256 .
Add unistd . H for size_t typedef to fix sim - eng
Set cam quality to 100 .
Updated readme to point to the jsr166e code from h2o - algos .
Ignore NetBeans project files
Remove extra newline
Upgrade maven - javadoc - plugin to its latest version 2 . 9 . 1
Added idea project files to git ignored files
Removed debugging statement which was not failing in build . Xml
Set no - op install phase for Shippable CI build
Add demo gif
Renamed quadTreeTest
Changed description of contributors
Add cloud - azure module
Add bin to gitignore
Added image for instructions on setting up a BigBlueButton VM
Removed a override of the new video that was not necessary
Fix failing test
Prepare release graylog2 - plugin - 0 . 9 . 7
Move unit test for unit tests .
Fixed javadoc for windows on windows
Fix applet with remove @ Override annotation
Added my TODO for changeset 9bb7ad84eace
Removed old dependency in com . 7 . 1 .
Fix problem with spaces . Xml file
Exclude the gradle wrapper file .
Removed Truth 0 . 24 + binary from HIVE - 7249 .
Removing a file from example data that ' s not needed
Change the definition of Array in externs
Fix path for src module
Fixed bug # 70 .
Add lang - javascript module
Set build tools to 0 . 9 . 3
Update location module
IDEA - 66561 ( ' Surround with .
Fixed the CS error of camel - lucene
Add travis build config
Added support for unit tests in h2o . Properties
Includes the NOTICE file in the android project project
Smack 4 . 1 . 0 - rc5
Add android jar to Sample
Prepare library for release 2 . 3 . 1
Added empty task to avoid signing in Groovy build
Changed package name for older cygwin installations
Added e - mail to travis . Yml
Updated forms . AsmCodeGenerator for custom BorderFactory client property
Added flyweight class diagram
Setting version to 1 . 0 . 140
Move images to NOPASS .
Removed an extra newline at the end of the file
Removing test data .
Fixed test data
Move data file to test folder
Exclude the path to the manual that could set the problem which doesn ' t be needed .
Make gradlew to be an executable file .
Added play badge to README
Moved InMemoryXmlApplicationContext to test src as it is only used in tests .
Fixed empty layout in terminal ( PY - 4087 , PY - 4088 , PY - 4089 )
Upgrade gecko to 1 . 1 . 1
Adding new image to the document layout so it isn ' t used
Reduce the description of source - compiler .
Reduce thread stack size for Android 2 .
Add ' related ' folder to gitignore
Downgrading server to jersey 1 . 3 due to issue with loading of external jax - rs packages .
Add @ suppress method to the end of the test
Removed unused import .
LPS - 61001 Move css file
Add support image for v1 . 0 . 2
Added MIT license test
Fix param for Metrics Consumers
Added newline at the end of file so that we can ' m getting anyway
Fixed typo in build . Xml
Add STORM - 1467 to changelog
Added maven enconding property in build . Gradle
Update the sample APK .
Include server examples in the build .
Updated Flow to version 0 . 3 . 0
LPS - 65920 ( WEB ) Move xml files
Add link to correct directory
Prepare release storm - hbase - 0 . 1 . 2
Added STORM - 1553 to Changelog
Added missing semicolon .
Renamed rnc file .
Override travis default install script
Add 2 . 4 . 1 hotfix
Updated the default template for the branch
Removed groovy jar .
Remove dependency on grails - core ( for now )
Reverted graylog2 script
Add 1 . 5 . 1 index for bw comp tests
Fixed unit test that was accidentally left in case ( IDEA - CR - 3123 )
Remove dummy file that I don ' t exist
Added slf4j - simple dependency for IDE - analysis .
Add nl translation temp file for map creator
Correctly show scrollbars in action menu items
Add bash tag to project
Add support for travis - ci
Added rnc file .
Remove unused semicolon in GlobalThroughput component .
Fixes a deadlock in the ICE implementation between Agent . Close ( ) .
Add travis ci
Revert " LPS - 36642 rebuild some files
Ignore gh - pages
Added support for v1 . 3 . 3
LPS - 47045 Add @ Override
WEB - 9926 remove 0xhh postfix ( @ null )
Fix bug in Context in log4j .
Get share link
Compile Palette with Java 7 with Gradle
Updates the number of projects in the root project .
Removed unnecessary imports .
Removed useless logging .
Updated support JAR
Fixed typo in org . Parboiled . Common . Reference
Updated jre 1 . 4 . 2_12 for windows
Suppress UnsatisfiedLinkError ( PY - 38870 )
Fix warning , fixes # errors # NO_ISSUE
Prevent new ripples when max reached
Add a note about the Readme
LPS - 51439 Move FriendlyURLRandomizerBumper from portal - test to portal - test - internal , as it uses LayoutImpl which is inside portal - impl
Made a new one class name ( # 103 )
Adds travis config
Removed openid from sandbox pom . Xml as it ' s been moved to main project
Fixed Travis configuration ?
Updated support library
LPS - 66923 Migrate packageinfo
Added release date
Removed unused Javadoc statement
Upgraded netty to 4 . 0 . 36
LPS - 52591 Do not have original exceptions when no longer need
Add javax . Java to index file
Fixing Junit dep scope to test
Fixed Travis configuration ?
Add travis file
Added activiti - archetype - api to the deploy profile as well
Moving PCA golden test to NOPASS until I figure out the source of the numerical inaccuracies .
Removes attempts to register the speex JavaEncoder and JavaDecorer classes , since they are exluded in the default libjitsi build , and trying to register them raises exceptions .
Add hint for grails - browser
Fix setting error for CASSANDRA - 5175
Fixed test data after stdlib change
Removed extra System . Out . Println
Upgraded to 3 . 0 . 1
Removed print statement that was accidentally left in the file .
Removed system out .
Fix compile error ( PY - 20458 )
Updated the NOTICE file
Revert " Rollback avs to 2 . 9 . 8 ( 2 . 9 . 3 was too far ) "
Fix exception in previous commit .
Added maven project
Write checkstyle to stdout .
Fix a problem in releases in release plugin .
Return an non - WiFi connections in shutdown , fixes # 127 .
Delete unused class from AnimatorSet .
Added support for linux - app
Add " tuple " and to keywords ( PY - 15390 )
Remove unnecessary comment .
Changed version to 0 . 1 , since the 1 . 0 was just the default version which maven generates for you .
Removing an empty line .
LPS - 63740 Add service
Removing extra space
Remove useless code
Add version 2 . 2 . 2 support
MinecraftForge / FML @ 3231db9376766d619f942b6a526718daa3c68038 Sorta revert 908491d5e7ac26becdac938f38cc90d6b9d73ce1 but merge assets into the map , rather than force overwriting .
Add screenshot
Remove unnecessary closing bracket
Added shell script
Documented socket handler enhancement
Added STORM - 1472 to Changelog
Ignored IDE - specific files .
Removed an unnecessary empty line
Remove old newline in pom . Xml
LPS - 32153 Remove unused line
Updated crashlytics file .
Fixed bug in terminal ( PY - 4087 , PY - 4088 , PY - 4089 )
LPS - 51081 Ignore extracted files
Update screenshot
Update the sample APK .
LPS - 47852 add override
Removed unused import in GlobalThroughput component .
Ignore " bin " directory ( created by Eclipse )
Remove unused variable in com . Mongodb . Erb
Revert " Freenode verification for the fullscreen messages .
Fix travis building .
Removes attempts to register the speex JavaEncoder and JavaDecorer classes , since they are exluded in the default libjitsi build , and trying to register them raises exceptions .
Add resources icon for v1 . 1 . 2
Regenerate gradle - wrapper . Jar with 1 . 9 - rc - 4
Added STORM - 1910 to changelog
Fixed a bug where DefaultChannelFuture . IsSuccess ( ) returns true even if it doesn ' t re
Make this consistent with other own component
Bumped parent versions from 2 - SNAPSHOT to 2
Fixes java 1 . 5 compatibility .
Remove unused todo
Smack 4 . 1 . 8 - SNAPSHOT
Missing import
Removed groovy build - analysis - rest
Add * .
Remove empty TestEnum file
Temporary add jruby version strategy for travis
Removed unused import from bbb - conf
Updated license header .
Removed unused import in GlobalThroughput component .
Rename xxx . Txt
Bumping version to 1 . 5 . 3 .
Fixed UIExplorer tabbar test
Prepare for next development iteration
Removed test classes that was not necessary .
Suppress Typo
Remove jre6 requirements . Java
Checking only test files
Remove unnecessary import
Revert " Bump the major release number to 0 . 8 . 4 "
Add missing regex annotation
Update screenshot
Make View # setBackgroundDrawable a no - op if setting the same background .
Renamed " zip test to make it work
Fixed account layout issue with drawer ( IDEADEV - 17261 )
Chmod a - x build . Bat - unix exec bit doesn ' t make much sense for windows ' bat
Remove debug output from jdirectshow . Dll .
Revert " Revert " LPS - 54998 SF "
Update osx bullet natives
Add unistd ( ) to ' PickerExample ' s
Upgrade gradle - wrapper to 2 . 10
Added missing travis . Yml
Remove spurious high blue fields
Updating Alloy to rev . 74817
Add the word " premio "
Fix small test data when deleting an index .
Upgrade the livetribe - jsr223 version
Rename DL MNIST Checkpoint test to 3 . 0 . 0
Upgrade maven - plugin to 0 . 9 . 2 ( # 103 )
Add unistd . H for size_t typedef to fix case .
Fix bug in synchronization of kept - in - sync script
Added tools . Jar again to keep Russel happy and the javac ant task working ; )
LPS - unnecessary Do not update moxieplayer . Swf anymore since it ' s no longer used
Added " Belarusian "
Move test file to test folder
Removed extraneous JAR
LPS - 65920 ( WEB ) Move xml files
Added circle . Properties .
Removed submodule from pom . Xml
Upgrade AudioPlayer to v1 . 0 . 10
Travis needs tools before platform - tools for 24 . 0 . 1 .
LPS - 32314 Add @ Override
Upgraded logback to 1 . 1 . 6
Added upgrades . Txt to index of installation - deployment chapter
Fixed test that was not cleaning .
Update linux - x86 natives
Add types to the list list
Updated ognl to 2 . 2
Add image for installing BigBlueButton VM
Bump the version number to 2 . 2b1
Updating Alloy to 6a86501 ; LPS - 31537
Build 1 . 4 . 1 version .
Removed unused import in titan . Js
Give access to the defining classloader
Add version 2 . 1 . 0 branch
Add README
Exclude the path to the manual that could run anyhow .
Set minHeapSize for tests in order to get OOME
Fixed incorrect class name in TestTextureArrayCompressed
Fix proguard flag
Added grails - json .
Add helper function to libcutils
Removed build after no longer needed
Created tech - debt entries for all components and laboratory components .
Fixes # hashCode ( ) .
Bumped Netty 3 . 2 . 0 - rc6
Remove profiler arguments .
Whoops , didn ' t have a command line when open them out ( IDEA - > Schienbein )
Fix up idea mistake
Fix long color color of gradient drawable
Removed debug statement
Ignore vim swap files
Fix bug in dataPath ( )
Fixing the CS error of camel - bindy
Fixes an issue which could cause CPU starvation while receiving from MultiplexingDatagramSocket .
LPS - 62787 prep next , use latest
Prepare next development version .
Resize screenshot .
Remove an unneeded assignment
Reduced a problem with projects in h2o - algos .
Upgrade maven - victims - plugin to 1 . 3 . 1
Add 2 . 4 . 2 jar
Updated TinkerPop Blueprints libraries
Fix osmand key location
Tried new gititgnore file
Removed ref to gremlin - plugin added by release .
Adding the jpa - converter module
We don ' t need these classes any longer
LPS - 31159 Move TemplateResourceExternalizationTest to portal - impl / unit - server
Added the maven - smali - plugin and smali - integration - tests modules to the parent pom
Added STORM - 118 to CHANGELOG
WCM - 627 prep next , use latest
Temporarily also include doLast ( ) instead of doFirst ( )
Add some new lines for MCPC 1 . 2 . 2
Ignore * .
SONAR - 6733 - add @ Override method for @ Transactional settings
Removed extra newline at the end of the file
Fix bug
Removed newline at the end of file in bbb - index
Fix copy and paste error
Prevent a minor change from gradle build , for now etc .
Updated the parent pom version to 4 which enforces you to use maven 2 . 1 or higher
Add latest to project .
Add support for AssertStatement
Bump version number to 1 . 3 . 4 - dev
Skip integration test failure due to problem where it is no longer used
Bump k9
Rename poll - > polls . Js
FileSystemCompiler # generateFileNamesFromOptions is adding filenames multiple times
Remove javadoc warning
Fixed test data
Setting version to 1 . 0 . 136 - SNAPSHOT
Add missing return in super . Close ( ) .
Change default resets rendering strategy for CASSANDRA - broker ( fixes # 8248
Rename README to README . Md
Pushed 2 . 7 . 0 Release
Added gradle plugin to gradle build
Remove unneeded dependency in pom . Xml
Make blueprints - test a test scope dependency
Add travis - ci configuration
Tried new gititgnore file
Revert " Update android gradle plugin to 0 . 6 . 1 "
Moving file to test / main / voldemort / integration / resources / IDE .
Move DeepLearning . Java to h2o - algos .
Forgot to commit the services file
Added tests to ignore list
Fix bug where memory isn ' t used correctly
Reset build identifier to next milestone snapshot
Delete outdated wiki snapshot
Removed debugging of a redis to make it work in github
Fix a typo in docs to fix # 12
Use OkHttp 1 . 3 . 0 .
Updating new reference to reflect recent changes .
Revert " Freenode verification for the fullscreen messages .
Exclude the source files in the pom . Xml
Updated Android gradle plugin to 1 . 0 . 1
Adding OSSMETADATA for NetflixOSS tracking
Switched to latest provided version .
Excluded NightlyTest in the default build profile
Fixed memory leak in templates view
Remove the mem file
Upgraded Spring 3 . 2 - > 3 . 2 . 1
Removed Key Value Server from SVN repository .
Setting version to 1 . 0 . 126 - SNAPSHOT
Add sample gif
Add credentials property as well
Write checkstyle to stdout .
Upgrade gecko to 1 . 2 . 0
Updated Proguard rules
Remove old wiki jni jar
Remove unnecessary import .
Remove openjdk6
MinecraftForge / FML @ a8cbef2321a8e1bdfac56476bdfb5b306f71d38b Finally hopefully fully kills the race condition causing a classcast on slow machines .
Fix quality flaw ( # 2069 )
Fix compilation error
Fixing build . Gradle
Removing test that is no longer used
Prepare version 22 . 0 . 0 - beta1 .
Add intellj project files to .
Add a runtime dependency on validation - api
Ignore dist folders
Added tag 0 . 0 . 7 . 8 for changeset 45e1e724eee2
Make gradlew to be an executable file .
Updated icon to give more non - size icon .
Do not handle any packet if long wasn ' t complete
Exclude the description from pom . Xml
HHH - 8733 - General build cleanup - app
Remove an empty line .
Fixed an issue with isLocal ( ) in order to fix an empty line
Added missing depency to 2 . 11 for CASSANDRA - 10237
Fix support library so it compiles
LPS - 55583 Moves icon
Fix typo
Removed old duplicate images for Android 3 . 2 ( issue # 301 )
Updating version to 3 . 0 . 0 - beta1
Updated introduction reference to reflect recent changes
Rename the return type for my NPE
Upgrade XStream 1 . 3 - > 1 . 3 . 1
Fix a typo in pom . Xml
Updated changelog for 0 . 8 . 0
Remove unused method
Removed unused import from AnimatorSet .
Ignored image for darcula ( IDEA - 99497 , IDEA - 96808 )
Add gradle plugin to gradle . Properties
Make THREADS configurable through environment
Removed @ Override annotation
Beta version = fix
Update msn lib
Removed unused import from AnimatorSet .
LPS - 68937 ( WEB ) Move icon File
LPS - 56237 Add missing property to field settings definition
Removed unused import which is no longer used .
Don ' t delete the deploy files in the repository
Use correct param for heightMode in RelativeLayout horizontal measure
Added text for another non - final code
Disable reloading for scripts with dates in the future
Fix typo in sudo
Make gradlew to be an executable file .
Removed old NOTICE file
Updated BP libs
Add open task as well
Add redis to travis build
Updated version to 0 . 9 . 0
Migrate to container based infrastructure
Uppdate build tools
Add support image for android project project
Remove superfluous assignment after methods in shutdown ( )
Setting version to 1 . 0 . 103
Make a variable final
Remove the unused file
Revert " added intellij specific file to .
Updated readme
Updated instructions on v1 . 0 . 2
Changing Honeycomb default wallpaper
Typo cont ' d ( remove deprecated method in trunk )
Updated version
Remove 777
Bump to version 5 . 2 - rc - 1
Add missing jar file
Make text state state correctly .
LPS - 44362 Add @ Override
Build linux / i386 against older glibc ( 2 . 3 . 4 ) for compatibility
Changed cruise module to use UTF - 8
Fixed missing bug in ping . Html
Update changelog for 0 . 9 . 7
Fixing the list of the sort image
Add some empty line in the README .
Added language flag for Android 4 . 2 ( # 103 )
Bumped parent versions from 2 - SNAPSHOT to 2
Updates the background color of the video area to drawable
Bump to version 0 . 4 . 7
Need a file to prevent Eclipse from giving an error due to missing folder .
SONAR - 5561 Fix some exceptions .
Upgrade maven - wrapper to 3 . 0
Added image for launching column .
Fixes an issue which could cause CPU starvation
Fix android_media_AudioSystem_getMasterMute return type .
Remove test file
Add license file
Add version 2 . 3 . 0 hotfix
Updating Alloy to 2 . 0 . X - deprecated 5a22471
Don ' t accept " Schienenbein " ( - > Schienbein )
Removed opengl . Jar from version control
Temporarily disable unit test
Add some META - INF to documentation
Remove custom Objenesis version from dropwizard -
Fix a System . Out . Close ( PY - 15771 )
Delete unused files
Removing test that was no longer used .
Add ' sources ' component to POM
Add println to apache - notes
LRDOCS - 1103 namespace it
Include unit test that was failing by non - core
Add missing import
Added missing path to submodule
Updating Alloy to rev . 74817
IDEA - 66561 ( ' Surround with .
Add release date for 0 . 8 . 2
Added my changelog entry for Simple Resource change .
Add 1 . 4 . 0 of README . Md
Delete version . Properties
Changed license name
Removed extraneous JAR
Updated api . Services . Png image to reflect new api structure
Add xml - psi for unit tests
Removed some debug statement in ` runVerbose `
Make the top binaries file of the project drawable .
Add STORM - 1661 to CHANGELOG . Md
Fix failing test
Setting version to 1 . 0 . 68 - SNAPSHOT
Ignore scripts directory created by git
Removes attempts to register the speex JavaEncoder and JavaDecorer classes , since they are exluded in the default libjitsi build , and trying to register them raises exceptions .
Write checkstyle to stdout .
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Fix wrong artifact name
Removed old ejb 3 . 0 jar
Moved license class for strings . Xml
Added changelog for 0 . 8 . 0
Setting version to 1 . 0 . 67
Removed unnecessary jar file
Added sample app icon
Revert " LPS - 46699 - CAS connection test results have the same thread regardless of pass "
Fix typo in code template
Fixing the file name .
Remove blank config
Fixed build after 1 . 5
Changed imports for comments
Added support for travis - ci
Fixing the list of menu window ( IDEADEV - 125317 ) .
Make spark . Response ' s body method public ( # 8 )
Updated image for struct and enum
Add tools for unit tests .
Add break statement on load extractor from form
Chmod a - x build . Bat - unix exec bit doesn ' t make much sense for windows ' bat
Revert " move test lib to work with / usr / share / unit tests
Add image for instructions on setting up a BigBlueButton VM
SONAR - 66316 ( WEB ) Move css list
Ignore dictionary - web 1 . 0 . 0 prep next
Fix firestone build
Add file so that we can run builds
Reset log level to info
Add multinode to build
Adding failing test file
LPS - 66316 ( WEB ) Move icon file
Generate Mockito to 10 . Exit in bbb - w64 .
Fix broken test
Added clover license
Bumping versionCode to 85 .
Update win32 - x86 native
Update antlr - maven - plugin to release version 2 . 1
Don ' t empty empty exceptions in the media constructor
Add image for preference category
Prepare for next development iteration
Re - fix the refresh on the media activity ( IDEA - 125317 ) .
Fixes a deadlock in the ICE implementation between Agent . Free ( ) and StunClientTransaction observed in Jitsi Videobridge .
Remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed
Removed the TODO from the end of the file
LPS - 45983 Add a line break since one depends on the other
Adding a runtime dependency on the build phase .
Starting 0 . 5 . 3 - SNAPSHOT
Don ' t compress jars
Add link to distribution
Revert " Keep window consistent in JS class , so they can be used in order to avoid problem with IE .
Remove unused import
Changed components to use parent pom v 4 , producing source and javadoc jar packages .
Prepare library for development
Added missing return type ( # 57 )
Updated version
Removed backport jar , as its no longer needed
Fix broken test case
Removed old xerces jar
MinecraftForge / FML @ 9520978b81d4cba5d8b0af0d5f155bd115023795 Use a temporary file for recompile ' s command line to combat command length to long issues .
Add images for installing BigBlueButton VM
Fixed WorldEditPlayer . FindFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Removed @ Override annotation from compareTo method , since it isn ' t in the superclass field
Update ppc64le natives
Add shell script to the PC Facade where it belongs .
Fixed logfile name
Set source encoding to UTF - 8
Bump pegasus to 1 . 9 . 5
Update version to 1 . 1 . 0
Add link syntax
Fixed the bug in commonutil .
Renamed README . Txt to README . Md
Added tag 1 . 0 . 0 . 4 for changeset 45e1e724eee2
Reduce the number of output checks for the JDK 10 . 1 . 0 .
Added STORM - 1472 to Changelog
Adding IDE files to .
Revert " Upgrade to Gradle 2 . 0
Add missing piece to the build . Gradle
Keep it as a test dependencies
Enable http client as part of the jvm project
Add missing import
Updated pdf with latest version
Fix a bug in commonutil .
Added padding on sidebar color so that we can want to show them used
Set mActualScale when initialScale is set by default
Remove old icon .
Remove the empty file accidentally checked it with HADOOP - 7249 .
Updated version
Removed debug output that was accidentally left in the top level .
LRQA - 23204 Add new component so that doesn ' t collide with portal - specific
Update groovy . Md
Smack 4 . 1 . 0 - rc2
Removed ' var ' because it wasn ' t necessary
Fixed heap spec for functional tests
Fixed version to 0 . 7 . 1 ( # 421 )
Removing unused class from js - analysis - core
Added travis . Properties for third_party / 7 .
LPS - 63740 Add Layout method
Added STORM - 376 to Changelog
Changed email address for travis .
Updated android . Clj to 0 . 7 . 0 problem
Ignore *
Add 1 . 5 . 0 zaphelp jar
Ignore IntelliJ project files
Prevent hang in maven - javadoc - plugin
Remove some gradle configuration file
Remove references to flatfile . Md
ParserRuleContext . GetChildCount ( ) now if we didn ' t re ?
Setting version to 1 . 0 . 103 - SNAPSHOT
Fix scope for scalatest dependency
Remove random new line
Removing some subtle bug I happened to introduce last night .
Add bin to gitignore
Added description to javadoc .
Updating Alloy to 230046d ; LPS - 29912
Don ' t compress jars
Fix floating point check in emulator
LPS - 43715 Basic build server for correct ' names
Added missing import
Update druid
Add stacktrace to travis command
Removed unused import .
Added a blank line at the end of the file , I can be used in the client package
Need a file to prevent Eclipse from giving an error due to missing folder .
Updated CHANGES . Txt for CASSANDRA - 1382
Putting tests in parallel
Added changelog for 1 . 8 . 2
Upgrade fastutil to 2 . 0 . 16 ( # 430 )
Add Slovak to the list in README
Revert " Revert " don ' t use fakeroot to build packages on debian "
Remove unnecessary whitespace that I don ' t do anything
Remove extra System . Out . MongoServerSelectionException ( )
Updated proguard configuration file
LEP - 6067 - Consolidating the Sharing links , forgot the actual sharing image .
Provides a more recent snapshot of the wiki
Push build .
Reduce the amount of logging from the Javadoc plugin .
Change VERSION . Txt for 3 . 1 . 0 release
Fixed an issue with the word that actually show in the file that was run out on the model view .
Add " property " as a service class
LPS - 63951 Moves class
Added phonegap icon to demo2
Don ' t draw terminal content out of the terminal panel component ( IDEA - 125317 ) .
Fix failing bug
Updated default framework to API 21 ( lollipop )
Require Maven 3 . 0 . 5 to stop users from using insecure 3 . 0 . 4
Response . SetStatus now accepts the PagerTitleStrip properly
Fix UIExplorer list in fill test .
Add OpenDictionaryAPI library ;
Add demo gif
Updating Alloy to f4bbdfc , 1 . 5 . 0
Fix builder error
Add link to install details
Delete outdated wiki snapshot ( replaced with Asciidoctor documentation )
Removed useless semicolon .
Remove unused semicolon in GlobalThroughput component .
Removing log4j . Jar and renamed . Jar
Add twitter directories in .
Added Victor to the contributors
Updated v1 . 1 . 0 jar .
Added exclusion for CLIRR into community , as they don ' t necessary
Removed Yaml and JSP tabs in " Other languages "
LPS - 43715 All the build when auto ' s commit
Removed unused jars from sample project
Why didn ' t I just use a .
Don ' t index unsaved files ( ie , no console )
Added test file so it can be used for testing
Remove unused ' client ' declaration
Add licence . H to test class so it does not allow for Grails 4 . 4
Fix test data .
Added STORM - 885 to CHANGELOG . Md
Fixed bug in previous commit ( PY - 4087 , PY - 4088 , PY - 4089 )
Updated version number
Change minSdkVersion to milestone versions in Java 7 build .
Revert " LPS - 36642 rebuild ruby - gems
Revert " added intellij specific file to .
Added missing link to README
Added travis config
Add licence . H to test class so it does not allow for Grails 4 . 4
Help topics for removing system ( IDEA - listener )
Removed extraneous whitespace from pull request
Adding files for 5 . 5 . 4 .
SONAR - 5080 remove comments from minimized JS
Updated readme url
Remove unused dependencies entry
Remove memory limit due to OOME
Prepare for next development iteration
Add 2 . 4 . 7 jar
Updating Alloy to rev . 74817
Update android - Iconics core to v2 . 0 . 0
Updated splash for win launchers .
Fixed typeo in test
Removing some wiki file
Removed log4j . Jar and version .
Added missing grails - plugin . Xml file
Resized header
Add jar to libs folder for ant to find . . .
LRQA - 18330 rename step 1
Added linksource to javadoc so we can navigate from javadoc to source code
Remove unnecessary databinding enabled
IDEA - 100693 copy / paste of a new list correctly so we don ' t like a split package scenario
Updated version number
LRQA - 14620 - Add new default component for portal - testray project
Added a section for / usr / share / red5 files
Remove ' projectsEvaluated ' to fix AntennaPod build
Adding a new line to make a end of file which is needed
Updated reference for 1 . 0 . 8
Added package file
Updated changeling .
Revert " added intellij specific file to .
Removed an empty line that was accidentally left in the file .
Set action bar title for Accounts activity in onCreate ( )
Updated Ant jar
Update the sample APK .
Add example translation to readme
Added translation using Weblate ( Polish )
Added license file
Add a Gradle wrapper to gradle . Properties
Add images for installing BigBlueButton VM
Update demo
Add preview icons
Revert " LPS - 44610 Update Alloy taglib jar ( Alloy "
Fix failing test in previous commit ( fixes # 47 )
MinecraftForge / FML @ 3231db9376766d619f942b6a526718daa3c68038 Sorta revert 908491d5e7ac26becdac938f38cc90d6b9d73ce1 but merge assets into the map , rather than force overwriting .
Add jacoco_build .
Updated help for 2 . 1 . 0 release
Use both JDK7 and JDK8 in Travis
LPS - 55603 - Remove unnecessary code from PortalImpl . GetHost ( )
Mark offset to a correct package .
Add launcher icon for higher resolution .
LPS - 55259 - Updating Alloy 3 . 0 . X to 6eb8209f0cdb27ecee0494e1653220159d9d7439
Set revision 3 . 3 . 5 .
Include android - dsl . Jar with Java 1 . 7
Make the throttling more sensitive to end - to - end latency .
Include the dependency that caches the tests in the repository .
Fixed a bug where the chronometer wasn ' t set the last commit in the device Audio Session API ( WASAPI ) ?
Change the background color to be used in the AST .
Added multichat operation set definition and Gibberish protocol implementation .
Update the sample APK .
Prepare version 19 - beta2 .
Disable optimizations for interfaces
Fix a bug where the right window is closed .
Add org . Jetbrains . 4 '
Update demo gif
Fixed a minor issue with fast test as well
Add STORM - 1267 STORM - 1266 and STORM - 1265 to Changelog
Updated jar
Don ' t have empty exceptions in shutdown ( PY - 7426 )
Removed unused images
Fixed a crash in TelephonyManager while calling getDeviceID ( )
Made the miss after .
Adding the jpa - converter module
Bump version to 1 . 0 . 0 - beta . 1 .
Added Studio with Graph Refactoring
Add open command for graylog2 build .
Gh - 471 - updated travis script
Added missing @ Override to externs file html5 . Js .
Add note about part of sample project
Configured functional tests to run with forked jvm per - test , possibly hiding a memory leak problem with tests
Rebuilds jndirectshow . Dll with a newer version of mingw64 .
Use OkHttp 1 . 3 . 0 .
Add lang - javascript module
Adding images for installing BigBlueButton VM
Delete examples files .
Add missing jar file
Remove unused import
Revert " Revert " LPS - 60569 Set version to 1 . 6
Changing components to use parent pom v 4 , producing source and javadoc jar packages .
LPS - 69962 Add packageinfo
Delete outdated wiki snapshot
Add test for unit tests
IDEA - 151696 Add ' Liskov ' to the ' dictionnary
Add 1 . 3 . 1 release
Add README
Upgraded maven - test - plugin .
Require Maven 3 . 0 . 1 problem
IDEA - 66561 ( ' Surround with * . Close ( ) that will be used by default
Added version to gmaven - project
Added bin folder to gitignore
Bumping up the protoparser dependency .
Bump common ref .
Add # 3479 ( SOURCE and CAPTURE cqlsh commands ) to CHANGES
Add res directory for HDFS - pages
Increased the mvn version to avoid possible build bugs
Added Ryan as a maintainer since he has done a bunch of work .
Make ViewHolder less visible
Upgrade gradle snapshot to 3 . 0 . 1
Remove Yaml and JSP tabs in " Other languages "
E9c5ade 46ab5e1
Always remove the ' s ' tag .
LPS - 43576 Copy shared jars to the portal .
Include required g + + - multilib
Add 1 . 3 . 0 zaphelp jar
Prepare version 22 . 0 . 0 - beta4 .
Tidied up script
Removed unused lovely . Buildouthttp extension
Removed the glossary on the end of file
Remove unused import
LPS - 67914 - Create project build . Gradle
Fixes an issue with Packet Loss Concealment ( IDEADEV - 125317 ) .
Remove the mem slides
Updated README . Md to point to the README
LRDOCS - 7044 Fix typo in JS list
Include strings . H instead of string . H for the strcasecmp prototype .
Added STORM - 1118 to Changelog
Ignore classes directory
Ensure a block change if it does not fetch the right window .
Updated build tools and sdk
Updated aboutlibraries
Removed some declared exceptions that are causing some issue
Reduce logging on build instructions in README
Adding license header
Fix generic label for # 1513
Updated Wrapper gif
Fix a typo in pom
Added META - INF to gitignore
Removed extraneous JAR
Delete the lcrypto BouncyCastle lightweight crypto library .
Use the latest version
Remove some whitespace in pom . Xml
CAMEL - 1932 removed slf4j - simple dependency from camel - mina pom
Add bin folder to gitignore
Revert " Revert " Revert " LPS - 52740 SF "
Created tech - debt entries for all components and laboratory components .
Upgraded to recent classworlds release
Ignored rrd directory that someone keeps creating for me
Update win64 nattttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttive
Fix spelling in example
Updates minify enabled true for release builds .
Updated parent pom version to match recommendations .
LPS - 26341 Set property to 0 . 6
Added support for travis build
Bump engine . Io - client
Changed components to use parent pom v 4 , producing source and javadoc jar packages .
Update sparc natives
Removed unused import from previous commit .
Build greendao 3 . 2 . 0
Updated convert . Properties
Update javadoc plugin
Removed unused call from gallery app
Removed any remains of list appearance
Add ' prepareBaseDir ' dependency to ' shadowJar '
Replace image for layout practice session 4
MinecraftForge / FML @ 4836b3272a9b292c62816c1d1f9e845486753839 Re - worked the Texture patches
Adding placeholders for the fullscreen button
Removing the TODO that - on Wiki .
Fix compile for non - service ( PY - 4088 , PY - 4089 )
Fixed failing test
Add jar for jre 1 . 3 . 2
Delete obsolete files
Remove stray sketch - v4 from ArtBook .
Fix memory leak in help display .
Changed components to use parent pom v 4 , producing source and javadoc jar packages .
Removed debugging statement which was accidentally left in the file .
Downgrade tabulate version to 0 . 8 . 3
Add tools so that it can fetch 23 . 0 . 2
Prepare release 3 . 1 . 0
Remove local testing file
LPS - 58439 Add missing ticket diagram
Removing extra newlines at EOF
LPS - 64191 update jar
Added file for MC 1 . 6
Fixing transitive - ness of provided
DO NOT MERGE - Consolidating the Sharing links ( forgot the actual sharing image . "
Added image for instructions on setting up a BigBlueButton VM
Fix a test data in example
Mark offset gamma test as NOPASS , even though it ' s passing , as it affects other tests by updating the R GBM packge . "
Moved class rules for mac to tightdb - example
Bumped version number to 1 . 4 . 1
Signed disabler . Zip with testkeys
Remove groovy . Properties ( no longer required by Eclipse plugin )
Prepare next dev iteration
Reflect linux native native binaries to v3 . 0 . 1 .
Bumped version
Updated ognl to 3 . 1
Remove targetSDKVersion from AndroidManifest . Xml
Setting version to 1 . 0 . 67
Modify image for optimize art
Added docs
Reduce the size of the sort style in IE7 ( )
Updated the CHANGELOG for v1 . 3 . 1 .
Added translation using Weblate ( Esperanto )
Bump common for 4 . 0 . 0 release
Removed bottom on scale ( fixes # 256
Synchronize PooledUnsafeDirectByteBuf . NewInternalNioBuffer ( )
Added Joachim Baumann to the contributors
Turn off active by default
Updated help for 2 . 1 . 0 release
Updating Alloy to f4bbdfc , 1 . 5 . 0
Updated name name for Android 2 . 2 - rc - 2
IDEA - 66561 ( ' Surround with .
Remove extra newline at the end of each test
Fix InputType determination of WebTextView ( DO NOT MERGE )
Add a build . Gradle file
Def would create a local code , but we want to access the field
Add extra android support package to travis config
Updated wiki
Regenerate WSDL
Removed unused import
LPS - 54745 update jar
Update libwebp
Adding support for AssertStatement
Add Paul Draper ( @ pauldraper on Wiki .
Bump up okhttp version to 3 . 2 . 2
Fix quality flaw
Add Data Deckers as info
Add android - psi for core
Modify new location to / opt / bigbluebutton / hbase
Added titan cassandra diagrams .
Fix build due to added API
Fixed test error ( PY - 6190 , PY - 4088 , PY - 4089 )
Make a new jar file .
Add 888
Removed print statement that was accidentally left in the last commit
Add console appender to quickstart - web
Renamed class to fix capitalization issue
Revert " LPS - 48038 SF "
Help ID ( PY - 4108 )
Fixed an issue with Packet Loss Concealment ( PLC ) which could cause muting
Added debug printing content of all incoming packets
Ignore idea ' s .
Add additional duplicate property to Proguard rules
Ignoring all workspace . Xml files .
Add function graph on fill by file
Fix ( driver ) make Find . Hint a static class
Don ' t remove empty code from returning API
A script should contain a file name
LPS - 66316 ( WEB ) Move css file
Removed unused imports in JB workaround app
Prepare release checkstyle - 7 . 1
Added 1 . 7 . 1 changelog
Updated gif
Update changelog for 0 . 6 . 0 release
Removed old xerces jar
Do not update accessibilityTitle in
Fix compilation error in bbb - core
Added screenshot for sample app
Updating Alloy to f4bbdfc , 1 . 5 . 0
LPS - 17220 Wiki page attachments links contain p_p_auth
Checking only test files
Delete unused folder
Removed an extra line at the end of the file
Replace caribou wallpaper without the stars
Setting default name for multi - project
Remove some trailing whitespace .
Add link to python runner
LPS - 65920 ( WEB ) Move xml files
Fixed issue 2544916 - Fun with AbsListView devices
Made a space between Home icons that can be sorted down by default .
Prepare for next development iteration
Add metric for managed profile setting
Removing SOP code .
Fix up problem in v0 . 8 . 2
Beta version = > 2 . 0 beta 9
Removed redundant task as part of Gradle 3
Upgraded parent version .
Add @ Override to the supportsVariableLimit method
Updated avs version to 2 . 8 . 6
Updated change log
Change the size to the same codec , so we want to access the name .
LPS - 66316 ( WEB ) Move css file
Updated windows bullet plugin
Add image for preference category
Updates the size of the systray icon in the UI bar ( IDEA - 125317 ) .
Remove unused space in worldedit - restrictions . Txt .
Moved some class to NOPASS .
Add 2 . 0 . 1 release
Add demo gif
Remove ' var ' so it wasn ' t work
Setting version to 1 . 0 . 93 - SNAPSHOT
Set default encoding to UTF - 8
Added android - idea . Jar since it ' s not needed
Try jdk8 on travis CI with a revised timeout ( 30 mins this time )
Removed an unnecessary line
Add syntax for unit tests
Updating 1 . 4 . 0 . 2 to 3 . 0 . 1
Removed debug in JSON
Fixed the path for the redis shell .
Fixed test data
Update readme banner
Update microba
Rename test to see if BJ notices CVS changes
Fix a crash in TelephonyManager while calling getDeviceID ( )
Adding unit test for auth - service ( PY - 4087 )
Add 1 . 3 . 0 flow
Upgrade Ant to 1 . 9 . 5
Removed reference file from new with new sample
Delete demo2 . Gif
LPS - 30595 Fix typo in portlet template
Smack 4 . 1 . 0 - rc2
Correct the build of the renaming for the intention test
Revert " LPS - 36642 rebuild ruby - gems
IDEA - 19061 Integrate the Rearranger - plugin into core - internal
Update linux - x86 - 64 natives
Remove unused files
Removed unnecessary import
Fix slf4j version
Fix unreachable code
Delete old zip file
Created the since .
Update contributor list , add yaphet , bjlindeqiang , dingjun , Dollyn , feilaoda
Don ' t index unsaved files ( PY - 7983 )
Update VERSION . Txt
Fixing GLIBC 2 . 4 problem on Debian system .
Removed debugging statement that was not ignored by default
Added new method to the build which is not necessary
Upgraded maven - release - plugin to version 2 . 1 .
Updated github bit on java 1 .
Add dependencies for Slice to presto - hive
Add shell script
Call super . OnDestroy ( )
Provide a reverseEach method for arrays
Fixed bug in iterate
Added preview image for new wiki
Upgrade version library to 1 . 1 . 0
Add padding to check does not set singleton option .
Update changes for 0 . 3 . 0 release
Fix # 1706
Updated BP libs
LPS - 32252 Legends in fieldsets shoult take 100 % of form menu
LPS - 56015 We only want the regular parameters , see getParameterValues and other methods in the class .
Delete kk
Upgraded netty to 4 . 0 . 15
Enable test provider
Cleaned an unused bad in js test drawable
Add * .
Fixed an issue with spaces in order to make it easier for FMJ execution .
Changes build . Io version to 0 . 8 . 0
Removed unnecessary import .
Removing package file
Revert " travis build check "
Disable RenderThread
Use the latest version of Android Tools
Delete outdated wiki snapshot ( replaced with Asciidoctor documentation )
Add STORM - 1910 to changelog
Bumped version to 0 . 8 . 0
Revert " travis build check "
Changed target plugin version to 23 . 0 . 0
Remove redundant jdk from travis - ci build
Fix OSGI version
Learned some new structs from Blizzard ' s Hearthstone
Removed the margin from the bottom which is not needed .
LPS - 7366 Remove blank line
Added missing return field for load view .
Add new screenshots for installing BigBlueButton VM
Updated dep companion version to 2 . 3 . 0
Remove redundant - api - on - 1 . 7
Updated android settings to 3 . 0 . 2
Make gradlew to be an executable file .
Fix plusone externs of gapi namespace to solid duplicates
Fix memory leak in BZ 52259 fix
Fix # define conflicts by sub - bottom list .
Commented out a failing line
In onKeyUp for DPAD_CENTER , show the IME for text state .
Removed tag roboguice - 2 . 0 - RC2b
Prepare release HikariCP - 1 . 3 . 3
Remove unused import statement
Added Google to build .
Fixed possible NPE when long is no longer used
Removed android - support - v4 . Jar
Add bin to gitignore for eclipse
Update 2 . 2 release
Add image for preference subscreen
Improve MongoDB script
Remove old otp - compounds .
Fix # 1435 and # 1436 by reverting 7f7bf304b0b43a1445e68c15ee6f6403c7ca5b9e
Update demo pdf
Updated test bar icon ( OF - 65 )
Build fix test version in README . Md
Add eclipse wrapper project file to ignore .
Revert " Update build script "
Add vim swp files to gitignore .
Add property name
Upgrade gecko to 1 . 1 . 2
Fix database version cache logic
Closes the StringLogger in shutdown ( ) for ProviderManager .
Do not force everyone to be in manual ,
Improve README . Md
Updated documentation in 0 . 9 . 0 release
Add Mike to pairs list
Add flow rule for unit tests .
Upgrade groovy to 2 . 4 . 6 to non - client
Remove fixed code that was accidentally checked in 1 . 2
Changed dependencies back to SNAPSHOT versions after tagging
Setting version to 1 . 0 . 16 - SNAPSHOT
Made previous fix of first cache calculation .
LPS - 53630 move icon
Ignore dependency - reduced - pom . Xml from .
Ignore poms - reduced - pom . Xml from .
Built new snapshot
Fixing the list in the JSON
Removing assets
Remove com . Android . Android from packaging .
Updated Studio with last version
Add * ~ to .
Remove unnecessary prop
Rename README to README . Md
Updated sample libs for v1 . 1 . 0
Adding the README to the directory .
Remove completed todo
Added logo for typography Examples
Add a ms annotations to the console one in the library "
Add support for travis build ( # 3122 )
Rename macro to be clearer in each code
Added Studio with Graph Refactoring
Fix broken ut
Make validateConf final field to null if it is not null
Update emitter version
Add note about the list of columns for the emulator ( Configure OS X tags ) .
Fixed a subtle bug I happened to introduce last night .
LRQA - 22780 Create component name in testray component
Removed backport jar , as its no longer needed
Added tag 0 . 0 . 8 . 8 for changeset 45e1e724eee2
Added image for instructions on setting up a BigBlueButton VM
Remove invariant of Question 1 . 0
Changed VERSION . Txt for # 353839 .
Add ignore entry
Remove the redundant elements to the ci compilation
Fixed bug in org . Parboiled . Common . Reference
Added support repo to travis . Yml
Adding usage task for maven plugin ( # 2678 )
Move test data to src / test / src / server / resources
Updated BP framework to 1 . 3 . 0
Updated windows snippet
LPS - 45686 Do not break words
Mark offset gamma test as NOPASS , even though it ' s passing , as it affects other tests by updating the R GBM packge . "
Push version to 188 and 9 . 1 - beta1 .
Now closes ReadableByteChannel after it has been read .
Added STORM - 853 to changelog
Added link to README
Removed backport jar , as its no longer needed .
Update version code
LPS - 48343 Icon Menu does not wrap text on mobile Viewer
Rename file to match class name
Removing test from adding new class in bbb - core
Revert " Revert " LPS - 52740 SF "
Set last_subscription_check after check
Rolled back bootstrap version
Add Travis file
Revert " Revert " HHH - 8733 - General build cleanup - hibernate - testing "
Build doesn ' t support a new cache settings
Changed version number to 1 . 3 . 0 - SNAPSHOT ( # 103 )
Improve test script
Add words to nod add newpipe to playstore
Add plugins to 0 . 8 . 1 release
Removed the glossary from the output .
Removed unused import from AnimatorSet .
Adding a new call to the server search into the same package ( which doesn ' t be used )
Fix # 675
Removed unused import which is no longer used .
Changed images for wiki
Added image for installing BigBlueButton VM
Fixed an unintentional change in terminal ( PY - 15771 )
Added some tags to make it work in some cases .
Remove unnecessary jars from / usr / bin / eden / * .
Consolidate javax . Servlet jars
Update slf4j - simple to 1 . 7 . 22
Add Travis CI configurations .
Configuration not needed any more .
Add android . Jar to the build so we can be define in the classpath for testing
Don ' t inline partials if ` fastBuild ` is under compile .
Removed targetSDKVersion from AndroidManifest . Xml
Add support launcher icon
Updated version number
Changed image for index
Add an empty line in the index
Removed an extra newline at the end of the file
Added empty line
Added link to dp package
Adding note to graylog2 build .
Updated version
Added a runtime dependency on the root project so it ' s now
Add updated to gradle
Added preview image for new wiki
Add link to reference com . 2
Revert " Change dependencies "
Added proguard rule for Play store ( new targets )
Add support for unit tests
Add unistd . H for size_t typedef to include rules
Added Travis - CI config
Fixes a lot of exceptions at the Mac OS X .
Update demo
Setting version to 1 . 0 . 10 - SNAPSHOT
Removed unnecessary call to exc_traceback
Delete outdated wiki snapshot
Adding missing semicolon in dialogs
Changed a typo from SHNAPSHOT to SNAPSHOT = )
Removed non - needed reference of bbb - index
Revert " update travis "
Fix com . Mongodb . Lzyzsd . BridgeWebView support for CASSANDRA - 1256
Also use the default activity in the menu view .
Bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6
Added STORM - 138 to Changelog
Add xxxhdpi images
Fix a small link in sample project
LPS - 63247 Add build . Xml
Testing travis - ci
Bump up revision number .
Add readme for sample app
Throw an issue with an empty state in the sort state
Add executable
Fix up the makefiles and some samples .
Add svm_print_interface
Give force final object in mobile view ( PY - 5518 )
Add a build . Gradle file
Updated version to 1 . 2 . 1
Remove unnecessary comma in CompilerExecutor . Java
Bump version for release
Add missing semicolon
Don ' t like access messages on shutdown ( PY - 38918 )
Revert " AudioFlinger does not useful list on parallel page
Fixing syncDoc task to avoid up - to - date message only because target directory already exists
Update internal framework to API 21 ( lollipop )
Improved imports
Cache the contents of .
LPS - 45686 Do not break words
Ignore sync - api 1 . 0 . 0 prep next
Removed extra newline at the end of each test
Updated version
Added version to gmaven - plugin
Add 0 . 9 - rc
Revert " call the inner class of Agent . Cpp ( ) that we don ' t re it yet
Delete unused files
Correct the build so that it doesn ' t exist
Delete README
Push version to 15 . 0 . 1 , 15003 .
Removed print statement from test ( PY - 4087 , PY - 4088 , PY - 4089 )
Renamed class to fix capitalization issue
Add image for instructions on setting up a BigBlueButton VM
Reinstate coverage to use UTF - 8
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Update the sample APK .
Fix wrong typo in docs / README .
Updated sample
Added a comment for v1 . 1 . 0 . 2 release
Ignore emacs backup files for .
LPS - 57534 Should not use full path , but CI machines have a broken PATH setup , need QA to fix it .
Removed unused import .
Upgrade dependency to 14 . 0 . 1 , closes # 1024
Mention roadmap
Fix Travis
Copy the list of the action activity in IE7 ( )
Updated CHANGES . Txt
Prepare library for release 2 . 1 . 1
Adding a blank line in CHANGES . Txt
Remove obsolete readme file
Add Callum Stott to .
Force AST Injected property check with staticCheckerVisitor
Add skipPngCrush to the robovm . Xml template
Remove obsolete class
CASSANDRA - 222 Added STORM - 1163 to Changelog
Update build tools to 23 . 0 . 3
Bump up revision number .
Ignore * .
Fix typo in code template
Upgraded guava to 16 . 0 . 1
