Remove obsolete wiki asset
Updated Studio url for CASSANDRA - 612
Ignore intellij dumps created during profiling ( * .
Updating Alloy to 93a1450 ; LPS - 32864 , LPS - 32865 , LPS - 32892
Added activiti - archetype - unittest to the deploy profile as well
Add extra - google - m2repository in travis
Update sunos - x86 / amd64 natives
Change launchMode of Accounts activity ( closes # 938 )
Delete demo2 . Gif
Push version to 14 , 11263 .
Fixing pom dep
Removed print statement which was accidentally ignored .
Do not encode sendRedirect URLs
Added STORM - 1661 to CHANGELOG . Md
Auto commit test 2
Reset build identifier to next milestone snapshot
Fix a bug where HttpMessage . RemoveHeader ( ) )
Bump version to 0 . 5 . 0
Don ' t reference stream on top on shutdown ( PY - 15771 )
Updated Support Libs to 23 . 2 . 0
Add android - framework to project . Properties
Optimize PooledUnsafeDirectByteBuf . NewInternalNioBuffer ( )
Remove extra space in newline
Add 2 . 2 . 1 release
Removed @ nosideeffects from DataTransferItem . Prototype . GetAsString ( )
Update gradle
Fix exception message for extra ( * and throw exception on import .
Commit an unused method
Add proguard rule for template
Don ' t show ugly data time setting
Add 2 . 4 . 1 to 2 . 7 for 3 . 1 . 1
Changed the default name in the top of the body
Update adbiFilters
Add getter for net . Sourceforge . Cssparser to org . W3c . Css . Sac
Set source level to 1 . 7 for javadocAll if possible
LPS - 61767 Fix sample to run with a locally published plugin
Upgraded netty to 4 . 0 . 6
Prepare next development version .
Regenerate gradle - wrapper . Jar with 1 . 9 - rc - 4
Added tools . Jar again to keep Russel happy and the javac ant task working ; )
Mark offset gamma test as NOPASS , even though it ' s passing , as it affects other tests by updating the R GBM packge . "
Don ' t add all entry file should be consistent with * .
Added some .
Removed zip file
Add Travis config
Add new images
Add conf / tachyon - env .
Removed @ Override from the end of the file
Cleaning up the same unit test message
Don ' t initialize EventTracker onload
Removed unused import from AnimatorSet .
Fix test data
Missed test data to be ignored by ApplicationContextFacade # doPrivileged ( )
Fixed bug in ArrayList in Windows
Removed unused icon
Updated location of test directory
Don ' t show the video choice event when changing an empty line
Removed groovy - api - v4 library
Fixed a bug where HttpMessage . RemoveHeader ( ) leads to a dangling pointer in the box
Remove TBD from fields and properties section
Removed an empty line
Created some JNI lib for markdown .
Added titan . Link to README . Md
Update the sample APK .
Don ' t remove unused import .
Add null pointer to terms test display so it does not make
IDEA - 66561 ( ' Surround with .
Rename class to match file
Throw an unused call in signature state .
Add new default metadata to the project script so it compiles
Updated Gains / Lift screenshots with new images from Nidhi
Add ' appendable ' to dictionary
Fixed # 183 - update entry
Updated course
Upgraded maven - javadoc - plugin from 2 . 7 to 2 . 9
Don ' t highlight the scrollbar in parallel .
Fixed test data
Add custom plugin for release notes
Revert " Revert " Revert " disable " for " Back for "
Revert " Update build tool to 24 . 1 . 0
MinecraftForge / FML @ 3231db9376766d619f942b6a526718daa3c68038 Sorta revert 908491d5e7ac26becdac938f38cc90d6b9d73ce1 ?
Fixed clirr config
Set default user max size to 10
Upgrade os - maven - plugin to fix the build issue
Add xxhdpi launcher icon for xhdpi and xxhdpi .
Renamed class to fix capitalization issue
Ignore eclipse project files
Moving version to 1 . 3 . 0 due to more major changes
Add table of contents in python / README
Method , didn ' t like commas at the end of clojure . H ( ) .
Removed all big dataset tests
Updated build tools
Include 1 . 0 . 1 of the README .
Fixed bug # 1762702 - index for View a WebView is not marked " clear " view .
Revert 8e704f627c7b03427ab1b71bb6774292a4a032f2 , because it didn ' t complete in Grails 1 . 2
Removed unnecessary empty line ; I accidentally left in the file 1 . 0 .
Removing bitdeli - badge
Added horizontal barchart .
LPS - 15480 Updated alloy - taglib . Jar to 76596 , you must LPS - 23474
Updated reference to library after rebase
Removed extra newline at the end of the file
Whoops , forgot the debug message if there is not necessary
Update es / upstream
Add " cpp " target to build OTF decoder and javadoc
Added STORM - 1472 to Changelog
Added a method for showing the socket types
Upgrade maven - gpg to 1 . 4 .
Added the manual to the build .
Revert " Upgrade to Flow 0 . 9 . 32 - SNAPSHOT
Updated TODO
Adding missing semicolon in frameworks . Xml
Update travis . Yml
Upgrade maven - site to 3 . 0 .
Updating the correct version to jain - sip version .
Removed the TODO in the index
Removed unused course
Add 2 . 5
We don ' t need these classes any longer
Move test to NOPASS
Updated studio
Added STORM - 244 to Changelog
Improve Readme . Md
Removing an unnecessary empty line
Remove redundant dependency declaration
Resized recovery . Java with new state non - TCP
Updated version
Fixed an issue where the message ` sometimes not necessary
Added version 2 . 3 . 0 - SNAPSHOT in maven properties
Ignore IDEA project files
Bumped versions , preparing for release
Removed debug output
Optimize build release script
Add updated ffmpeg JNI library for Linux 32 - bit and 64 - bit .
Update com . Gradle . Tools from com . Android . 4 release
You don ' t need libopencore_author and libcutils
Remove jni / static ( PY - 15771 )
Remove change from another PR to avoid confusion
Add HBase testing directories to gitignore
Removed bin from .
Added some META - INF / plugin for Ubuntu
Revert " bump version for development "
WEB - 9926 add return by default
Correct a type annotation in w3c_indexeddb .
Added intellij project files to gitignore
Update to latest support libraries v23 . 2 . 0
Removing an unused variable
Updated version number to 0 . 23 . 0 - SNAPSHOT
Fixed syntax in pom . Xml
Added default requirements for VERSION . Txt
Updated the project name so it compiles
TFJ - 480 Add live font property icons
DO NOT MERGE - Updated ADB icon
Added preview image for new BigBlueButton VM
Reduce the size of the search capture in cases . Java
Update to classworlds 1 . 1 - alpha - 1
Push version to 12 - beta4 .
Revert " Enable OpenCORE on master - part 1 "
Adds test resources .
Updated studio
Fix quality flaw ( wrong artifact type )
Add padding to sourceforge image .
GRAILS - 5691 - remove some code that was accidentally left in the last commit
Replace NOTICE file in readme
Add a Javadoc tag .
Remove language " fr "
Updated Android build tools to 23 . 0 . 0
Adding newline to check directory so we don ' t exist in project script
Missing test
Update sparc natives
Fixed typo in bbb - conf
Fix broken tests
Renamed class to fix capitalization issue
Added missing @ Override .
Updated course
Added link to correct location so it compiles
Updated version
Add upgrades . Java to index and base - resources - 64 - bit .
Fixed compilation error in bbb - conf
Fixed test data .
Added tag 0 . 5 for changeset aad229e4371b
Updated version of jikes
Ignore translator - web 1 . 0 . 2 prep next
Added latest jar
Changed the inner class to static
Updated all icon to match same icon ( fixes # 144 )
Set gradle tools version to 2 . 1 . 3
Ignore " bin " directory ( created by Eclipse )
Fix lint warning
Remove the empty file accidentally checked it with HADOOP - 7249 .
Removed memory leak
Bump version number to 1 . 3 . 4 - dev
Use the latest version of Gradle
LPS - 60633 ( WEB ) Move java files
Bumped version
Ignore build . Xml , its generated by default jar .
Removed an empty line that was accidentally left in the top level .
Adding a comment to the bottom of the bottom of the bottom of the bottom of the bottom of the user function
Added preview image for new BigBlueButton VM .
Remove com . 4 . Tools from Eclipse builds
Removed ' var ' > since it is not used .
Bumped versions , preparing for release
Remove extra line at the end of the file
Clarify error which can ' t be supported .
Fix previous commit ( because we can ' t be used )
Change versionCode 207 for 4 . 3 - SNAPSHOT of code - tag
Remove comment
Remove unnecessary import
Removed dead imports .
Add my dictionary with the init of our docs
Removed extra import at the end of the file
Added method to send a static modifier
IDEA - 66561 ( ' Surround with . "
Make uploadMavenCentral task , that encompasses other tasks
Prepare version 23 - beta2 .
Updated es module
Add STORM - 1121 to CHANGELOG . Md
Added checkstyle plugin to the checkstyle plugin so the user ' s version
Removed @ Override comment from @ whiteboard
Ignore files
Add image for installing BigBlueButton VM
Help topic ( PY - 3290 )
Bump up revision number .
Updated version number to 1 . 8 . 1
Fixed bug when trying to rotate image when focus will throw an EOFException .
SONAR - 9926 remove unused z - index
Turn off animations in the launcher trust account .
Resize screenshot .
Add @ since comment to the save option .
Add makefile
Prepare release HikariCP - 1 . 3 . 3
Solves script can now pick up env var JAVA_HOME
Revert " added intellij specific file to .
Updated logo file again
Removing the linker option in the README
Added a redirect to the end of the file that is not necessary
Fix broken libjnportaudio for linux - linux
Fix memory ' s invalid row size field in terminal ( PY - 15771 )
Regenerate WSDL
Upgrade Jedis to 2 . 6 . 0
Updated changelog for 0 . 8 . 3
Added toString ( ) to verify for Linux , its better tabs
Add STORM - 862 to CHANGELOG . Md
Updates the messaging , forgot the memory on any tests
Fix a typo in bbb - conf
Prepare next release v0 . 91 . 2 - SNAPSHOT
Revert " Fix website image .
Revert " LPS - 52740 SF "
Remove deprecated constant from docs
Update linux - ppc64 native
Removed targetSDKVersion from AndroidManifest . Xml
Ignore poms - reduced - pom . Xml in .
Update apk to 3 . 2 . 2
Removed extra newline at the end of alluxio_stop .
Fixed VERSION . Txt
Added STORM - 712 to Changelog
Added examples image for Sample project
Added CHANGES . Txt for YARN - 2503 .
Remove unused import
Added missing comma at EOF
Fix a problem with spaces in README
Don ' t ignore the target directory .
Remove unused binary files
Removed version file .
Ignore unused import ( PY - 81507 )
Don ' t compress jars
Add org . Jetbrains . 4 comment
Fixed test data for unix ( PY - 7426 )
Fixing phpunit invocation
Fixed a bug in signature issues in unknown view .
Bump the version to 2 . 0 . 2
Update README
Missing unnecessary local stacktrace
Bump travis to also build the tools
Added < template ' to the Readme
Added small documentation to elasticsearch 2 . 3 . 0
Add image for instructions on setting up a BigBlueButton VM
FlowManager should set mDatabaseHolder to null state defined in onCreate ( )
Remove extra call at the end of alluxio_stop .
Setting version to 1 . 0 . 8
Removed application module from demo project
Updated changelog for 1 . 3 . 3
Set default value of size for Android 2 . 2 *
Fixed broken problem with tests 0 . 2 .
Remove unnecessary dependency in pom . Xml
We should create a code of the bottom in the file next so that you can be left by the last commit .
Fix broken build
Updated icons for Play store ( new requirement )
Removed unnecessary jar .
MinecraftForge / FML @ 9520978b81d4cba5d8b0af0d5f155bd115023795 Use a temporary file for recompile ' s command line to combat command length to long issues .
Add intellj project files to .
Updating Alloy to rev . 74817
Fixed bug in terminal ( PY - 4087 , PY - 4088 , PY - 4089 )
Removed a System . Out
Updating Alloy to d77ca55 ; LPS - 29774
Update jdbi to 2 . 4 . 6
Setting version to 1 . 0 . 111 - SNAPSHOT
Updated TCK .
Update win32 - x86 native
Remove redundant version number from application . Properties ( grails plugin )
Removed unnecessary comma in CompilerExecutor . Java
Added thirty minute per test time limit , to avoid stalled tests
Update deskshare applet
Removed unnecessary method at the end of each test
Fixed a bug with the init script to make it work in IE .
Fixed a naming issue
Added the renamed jar ( # 817 )
Execute sphinx problem with projects in the README
Add android . Jar to the build so we can be define in the classpath for testing
Install database - migration plugin by default
Using jetty - test - helper version 2 . 7 .
Added exception using Weblate ( Icelandic )
Added a missing def
Removed targetSDKVersion from AndroidManifest . Xml
Updated logo more according to new icon
Updating Alloy to rev . 74817
Upgraded Wrapper
Ancestors should return a node pointer
Add redis to build matrix
Updated android tools version to 23 . 0 . 3
Fixed bug when trying to rotate image when trying to rotate ( IDEA - 125317 ) .
Fix changelog for 0 . 8 . 3
Added folder for the visualization project .
Adding virtual certificate to the list of performance tests
Update demo
Add Lucene version in plugin . Properties file
Show the SEED to be a license context to show it as the project failure .
Added gitignore .
Use the spread to the single page edition .
Add branch name " master " to version . Properties
LPS - 66316 ( WEB ) Move css file
Add OS X proguard to readme . Md
Added table margin for bbb - api
Updated github bit on java 1 .
Removing unused space in init script
Smack 4 . 1 . 0 - rc2
Don ' t commit the target directory
Add STORM - 555 to changelog
Updating release notes to 2 . 0 . 3
Added support for travis - ci
Delete linux - 2016 - 04 - 04 - 160244 .
Fixed test data which was accidentally ignored by default
Ignoring target directory created by running sample ha - ops bash scripts
Bump gradle version
Hiding DrawerLayout does not fire correct accessibility event .
Add new icon to drawable
Ignored dependency - reduced - pom .
Updated icons for new feature ( fixes info )
Added missing dependency in pom . Xml
Setting version to 1 . 0 . 63 - SNAPSHOT
Added missing pattern
Remove an unused import from settings
Remove extra System . Exit
Building up a gitignore file to ignore eclips config files .
Updated socket . Js for the README
Add missing support file
Fix test warning
Don ' t export " BootReceiver ' s scheduleIntent button
Removing warning on isValid for an analyzer test
Fix a typo in README . Md
Add # 3762 to Changelog
Removing an unused space .
Removed old jars
Add version for android - plugin
Rename file to make new JRE for now
Prepare for next development iteration
Fix test data for unix ( PY - 283 )
Added images for instructions on setting up a BigBlueButton VM
Incorporate Dave and Trish changes
Add Sample
Prepare next development version .
Fixed bug in layout ( PY - 4087 , PY - 4088 , PY - 4089 )
Add missing test script
Move travis . Jar file to match main directory .
Updated version
Fixed asm 0 . 5 . 1
Reduce the amount of logging from the Javadoc plugin .
Removed reference
Add art image
Do not call stack by default
Fix typo ( PY - 20458 )
Upgrade gradle plugin to 2 . 2 . 0
Setting version to 1 . 0 . 12
Added images about the native app icon
Simplifying the default welcome presentation
Added STORM - 1920 to CHANGELOG
Bump minSdkVersion to android sources 2 . 0 . 0 - dev
Smack 4 . 0 . 1 - SNAPSHOT
Updated BP libs to latest version
Added image for installing BigBlueButton VM
Ignore intellij backup files
Setting version to 1 . 0 . 132 - SNAPSHOT
Move SailGraph ' s icons
Fixed a crash in TelephonyManager while calling getDeviceID ( )
Optimize to_maven script
Bump greendao 3 . 2 . 0
Revert " bump to the recent version of the subproject
Moved test to NOPASS .
Upgrade change in javadoc
Bumped parent versions from 2 - SNAPSHOT to 2
Change the layout_height in toolbar_spinner . Xml to match_parent
Removed old ejb 3 . 0 jar
Added studio - 2 . 2
Removing @ nosideeffects from DataTransferItem . Prototype . GetAsString ( )
I don ' t really see a justification for doing a blocking write on close .
Add image for instructions on setting up a BigBlueButton VM
Setting version to 1 . 0 . 10 - SNAPSHOT
Added relative path to the parent POM so that the user won ' t need to
Removed unnecessary comment
Simplified travis CI file .
Add changes for README
Fix sync tests failure .
Delete demo_shifting .
Update internal framework to API 21 ( lollipop )
Added getter for @ Before .
Fixed unit test
Added STORM - 2100 to CHANGELOG . Md
In order to show right window ( PY - 6190 , PY - 4088 , PY - 4089 )
Move rnc file .
Added more padding to bottom in the index
Remove ' var ' in ` runVerbose `
Copy the list of the renamed / bin / unit / bin / unit / server / red5 / share
LPS - 58662 I assume order matters , so let ' s add a file break
Only run compile / unit tests in Travis
Add osx binary with callbacks ( intel only atm )
Fixed typo
Add missing property
Commit test to see if BJ notices CVS changes
Built new snapshot lib
Removed an extra line at the end of the file
LPS - 66136 Move icon
Removing an unnecessary line .
Prepare next release v0 . 90 . 1 - SNAPSHOT
Create README . Md
LPS - 35153 - Remove unnecessary z - height
Add Lucene version in plugin . Properties file
Upgrade Anonymous Usage Statistics to version 1 . 1 . 0
Updated OkHttp to version 0 . 3 . 0
Changed Target SDK to 21 ( Lollipop )
Prepare next development version .
Add image for installing BigBlueButton VM
Fix an issue where the lazy - touch detection ( IDEADEV - 125317 ) .
Setting version to 1 . 0 . 10 - SNAPSHOT
Download apk directly from here
Revert " Revert " Upgrade to Flow 0 . 3 . 32 "
Include unit tests in Travis
Revert " Add permissions out "
Add android - features to top and README
LPS - 65920 ( WEB ) Move xml files
Added Artur to the contributor list
Fixed bug in drawer ( PY - 3290 )
Make gradlew to be an executable file .
EGL14 . EglCreateWindowSurface should set producerControlledByApp
JAL - 35 Add image notes to non - proprietary licenses
Updated irc - api library to rev . 194 .
Remove unecessary run files
Compendium cannot load javax / xml to shutdown ( PY - 4088 )
Remove newline as this ' s not read "
Removed android - support - v4 . Jar .
Removed an extra line at the end of the file
Bump deb version
LPS - 45983 Add a line break since one depends on the other
Try tests on travis CI with a revised timeout ( 30 mins this time )
Bump the version number to 0 . 8 . 7
Removed old icons
Removed CamelChoiceWithManagementTest . Java
Fix Travis building .
Removing swp file .
Fixed bug in org . Parboiled . Common . Reference
Updated jmh configuration to version 0 . 8 . 0
Can ' t have empty sections .
Don ' t build aggregated source jar .
Add flag to test app build as they don ' t support it
Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode .
Bump version to 3 . 0 . 0 - beta
Fix incorrect label for boolean AP option
Added circle file
Revert " Revert " LPS - 54998 SF "
Add icon for preference category
Add 1 . 4 . 0 runtime
Force ' marke all as read ' in the overflow menu .
Setting version to 1 . 0 . 147 - SNAPSHOT
Prepare version number , 1 . 3 . 0 - beta1
Updated builtin framework to API 12 ( Android v3 . 1 ) .
Fix the bug on Libsvm 3 . 14 that not free the memory allocated for sv_indices .
Upgraded netty to 4 . 0 . 36
Don ' t run " deploy " as well " so that it can ' t run fault )
Make gradlew executable in Lazybones templates .
Add a missing language check for unit test .
Adding new line at the end of the file
Added changelog for 1 . 3 . 1
Added a note about the user directory
LPS - 63740 rename step 1
Adding 0 . 8 . 0 release
Ignore translator - web 1 . 0 . 0 prep next
Prepare release HikariCP - 1 . 3 . 3
Updated example image .
Revert " Bump major version to 2 . 23 "
Removing old listwidget preview image .
Add a libbase static depedency for aapt2 .
Added gitignore .
Changed Target SDK to 21 ( Lollipop )
Upgrade gradle plugin to 2 . 2 . 0
Added IntelliJ IDEA project / workspace files to gitignore .
Uses a single Thread per StunStack to expire StunServerTransactions in order to reduce the total number of utilized Threads .
Remove optional scope from the license module
Updated credits
Added support for support - v13 aar .
Added Travis . Yml file to keep tarball in .
Upgraded the wrappered gradle to 0 . 9 - rc - 3
Add " cpp " target to src " .
Removed unnecessary method .
Ignore derby . Log
FIX Dashboard always display a scroll in IE7 ( cherry picked from
Add NOTICE . Txt for status . Yml .
Set visibility . OnCreate ( ) in AbstractFailureDetector .
Removed @ Override from new method
Add IRC notifications to travis
Built the latest snapshot
Adressing review comment for # TACHYON - 1243
Removed unused import .
Revert " added intellij specific file to .
Prepare for next development iteration
Updated proguard to NOTICE . Txt .
Add " cpp " target to ' shadowJar '
Remove the empty file accidentally checked it with HADOOP - 7249 .
Added maven plugin to build . Gradle
Don ' t publish spock - part in release .
Add cloud - azure module
Make gradlew to be an executable file .
- Add dummy file to " fuzzers " directory
LPS - 4668 - MB Emoticons need better z - index
LPS - 51081 Ignore " tmp " dir "
Add missing return request to super . Close ( ) .
Removing unnecessary warning
Removed unrequired dirbuster jar
Ignore local tmp dir
Make uploadMavenCentral task , that encompasses other tasks
Make sure , remove dead type ( PY - 15771 )
Rename README - ZH .
Should fix the count messages in observer loop
Add link to src package
Add missing piece to the build . Gradle .
Added logger to settings list
Add ScanfFormat to requirements for windows port
Add 666
Add Travis config .
Fixing the typo in README . Md file , so it ' s better for now .
Added reference to src module to make it work with other location
Added helper property for com . Mongodb . Ddmlib . Erb
Bump readme to reflect current build script
Rename file to match file
Added STORM - 1138 to Changelog
Try codecov now , install all container - based builds .
Updated decorator class diagram .
Add isClosed ( ) .
Updated version in README
Update gradle . Properties to 0 . 90 . 1 . 1
Add - since flag for api level 19 to filter javadocs
Don ' t run tests if no tests doesn ' t exist anymore .
Push version to 14 - beta5 , 15014 .
Make spark . Response ' s body method public ( # 8 )
Ignore a couple of plug ' s ` entries from .
Add nl translation temp file for map creator
Fixed bug in dumper ( IDEA - 152896 )
Remove REE also
DO NOT MERGE ANYWHERE Update support library version to 24 . 1 . 0
Setting version to 1 . 0 . 9 - SNAPSHOT
Removed unused import from gallery project
Removed extra newline at the end of each test
Upgraded http client to 4 . 3 . 2
Updated gif
Cleaning up one message ( PY - 421 )
Remove the TODO
Ignore configured dir
Update coverage to 0 . 9 . 8 ( IDEA - 123499 )
Temporarily also include eglTerminate - > eglInitialize hack for 8k
Added STORM - 514 to changelog
Ignore registry - api 1 . 0 . 3 prep next
Updated upgrading section
Testing Circle CI
Fixed the bug in the Javadoc
Remove x bits from java files
Fix PY - 11673 Error on shutdown check
Prepare next release v0 . 87 . 1 - SNAPSHOT
Remove some unused blank line
Added launcher icons for NewLineAtEOF
Added DataGrip to the list of supported languages
Remove com . Sun . Tools . Asm in build . Gradle
Add option to turn off share in test
Update android build tools
Updating fix for pig to pass
Temporarily also include eglTerminate - > eglInitialize hack for 8k
Removed unused import
Update to latest android build tools
Removing test data .
Remove opendk as it ' s not present
Released OrientDB 2 . 1 . 0 GA
Make Tachyon - Perf a subproject of Tachyon
Add comment to 0 . 8 . 4 release
Fix latest plugin version
Delete unused images
Remove extra import
Update to latest android gradle build tools 2 . 0 . 0
Set source encoding to UTF - 8
Fix failing test ( PY - 283 )
Changed a typo from SHNAPSHOT to SNAPSHOT = )
Update to latest support libraries v23 . 3 . 0
Minimal json update version to 0 . 9 . 2
LPS - 65920 ( WEB ) Move css files
Updated to latest android gradle build tools 2 . 0 . 0
Added activiti - archetype - api to the deploy profile as well
SONAR - 231 reverting TwitterStream # setStatusListener ( )
Remove extra newline at the end of each test
Remove spurious character
Updated CHANGES . Txt for CASSANDRA - 1382
Ignored IDE - specific files .
In onKeyUp for DPAD_CENTER , show the IME for text input .
Ensure only a single scroller animation callback per frame .
Removed obsolete files
Update build tools to 21 . 0 . 2 .
Removed unused import from AnimatorSet .
Remove a newline at the end of alluxio_stop .
Add lint abort to demo ' s gralde build script , ps for travis - ci
Added junit version .
Update win32 - darwin key ( # 6059 )
Adding TODO for system overview diagram
Do not load gnustl in shutdown ( )
Added junit for testing - IDE .
Add icons for scale drawable
Kill an un - needed / un - used __init__ .
Ignore stacktrace . Log
Removed print statement which was accidentally left in the file
Added images about the native app icon
Adding comment to CHANGES . Txt for CASSANDRA - 8677
Removed some trailing whitespace
Remove unused import
Increase requirejs ' s timeout to 60 secs ( ) that we don ' t have a suppressions that - > available
Add link syntax
Make all window dialog if we don ' t re it too it
Update libwebp
Run startup script for multi - project
Updating Alloy to rev . 74817
Remove logging on allow_failures since it was not enough check
Add instruction to rockerhieu / mvn - 1 . 6 .
Added self to acknowledgements ( # 30 )
Updated banner
Changed library test
Fixed bbb - api to fix ( IDEA - 8 )
Fixed unit test ( PY - 4087 , PY - 4088 , PY - 4089 )
Add missing resource
Remove mavenLocal ( ) from gradle . Properties
Use Xcode 7 . 1 on Travis CI
Remove version . Properties from Java 1 . 7
Made a manual if it is not done if it is something
Fixed WorldEditPlayer . Changed ( )
Add missing image
Updated Studio
Updated copyright .
LPS - 43715 Basic build files ( empty until we start pushing the module ' s contents )
Added a method to create a subset of the video
Add 1 . 4 . 0 of h2o . Jar
Added gif
Added support for travis - ci
Updating examples for rev 0099
LPS - 65920 ( WEB ) Move css files
Adding assets for installing BigBlueButton VM
LPS - 62787 prep next , use latest
Upgrade Maven Dependency Plugin to 2 . 8
Updated Cycle screenshot in documentation
Setting version to 1 . 0 . 116
LPS - 45870 Remove extra line break
Should have child graphs .
Add xxhdpi launcher icon
Revert " LPS - 36642 rebuild ruby - gems
LRQA - 23204 Add add new property for portal - test
Updating license file
Prepare next development version .
Removed unused
Add extra - android - plugin dependency in travis
Removed Thread . DumpStack ( ) calls used for debugging .
Fix typo in cxx_library example .
This will fix the same tests as well for Bamboo
Prepare release checkstyle - 6 . 8 . 1
Fix some problem with proguard config
PY - 66316 ( WEB ) Move css list
Revert " travis build check "
Ignore editor backup files
Revert " remove unused classes "
Removed newline
Added STORM - 2018 to Changelog
Chmod a - x build . Bat - unix exec bit doesn ' t make much sense for windows ' bat
Removing a trailing whitespace .
Add Readme . Txt to Travis CI build .
Fixed test data
Added lintVitalRelease as suggested by @ DimaKoz
Prepare for next development iteration
Add missing jackson - communicator logo
Deleted unused import from last commit ( PY - 283 )
Update contributor list , add yaphet , bjlindeqiang , dingjun , Dollyn , feilaoda
Adding groovy test to Proguard rules .
Add image for preference category
Add flag as a travis command in travis
Add clover .
Updated help for 2 . 1 . 0 release
Don ' t initialize EventTracker onload
Bump sample version to 23 . 0 . 1 .
Remove android - android - plugin . Jar in the current SDK .
Updating Alloy to rev . 74817
Ignore editor backup files
Added shell script for grails plugin
Revert inadvertent edit to uploadJavadocs . Sh
Build scripts moved packaging
LPS - 66316 ( WEB ) Move css file
Add sample apk
' Assignment is not used ' inspection '
Reverted build tools version to 3 . 0 . 1
Fixed typo in comment
Fixed the rounded corner class on Windows ( IDEA - 125317 ) .
Adding IntelliJ files to ignore
Removed fixed link from readme
Reduce the number of tests before fork in CI
Remove unnecessary import
Rebuilds jndirectshow . Dll with a newer version in linux and 64 - bit .
Downgrading server to jersey 1 . 3 due to issue with loading of external jax - rs packages .
Add screenshots for new screenshots
MinecraftForge / FML @ 9520978b81d4cba5d8b0af0d5f155bd115023795 Use a temporary file for recompile ' s command line to combat command length to long issues .
Adding a newline at the end of the file , I ' m getting an
Set source encoding to UTF - 8
Fixed syntax error
Don ' t convert MIME content - actions does not throwing an error ( no input exception )
Removing old listwidget preview image .
Optimized # createCopy ( ) .
Changed Target SDK to 21 ( Lollipop )
Fixed typo in top level rules
Fix ref to lucene . Apache . Org
Update internal framework to API 21 ( lollipop )
Prepare release checkstyle - 6 . 15
Remove dependency on maven - plugin
HHH - 8733 - General build cleanup
LPS - 44362 Add @ Override
Move this file to reflect new resources
Update applet zip
Added package file so it can run work on Windows on testing
Dropped META - INF / MANIFEST .
Fix one error in bbb - core
Removed unnecessary comment
LPS - 66316 ( WEB ) Move css xml
Fixed possible inner class for pr # 283 .
LPS - 66316 ( WEB ) Move css file
Rebuilds jndirectshow . Dll with a newer version of mingw64 .
Add a TBD section for the JSON support
Don ' t upload spock - report as a more memory is not released .
Modify image to scrolling ( PY - 283 )
Removed issue where it was not necessary
Updated todo for 2 . 2 . 0
Add property entry for # 3912
Make an error if we can do anything properly .
Add constant for rstudio user identity display
Removed an unused blank line
Fix a bug causing the end of one missing time
Ignore files
Add local . Properties to gitignore
Removed debug output
Fixed a subtle bug I happened to introduce last night .
Add support for HEAD , OPTIONS , TRACE and PATCH
Remove extra System . Exit ( ) so it doesn ' t re yet comments .
Fix test
Cleaning up the webpolling jars
Correct a typo in module file
Updated CHANGES . Txt for Esperanto .
Revert " Add Thumbs . Db to gitignore "
Added settings for 0 . 3 . 0
Moved test to NOPASS
Change default logging mode to allow ( PY - 4088 )
Ignore project files
Fix some tests in README . Md
Use gradlew 1 . 2 . 0 .
Update the sample APK .
Fixing an issue with that damn bundle plugin again .
Remove unneeded assembly idea from pom . Xml
Updated JPS with 10 . 9 . 9 release
Prepare for next development iteration
Fixed compile error
Add getter for FloatTextureData . Xml
Removed the run output from the translator since it ' s not needed in the git repository .
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Add isPlaying ( ) to @ GwtIncompatible .
Add 2 . 4 . 0 zip
Remove JDK6 tests from travis
Fixed NPE ( WI - 22515 ) .
Add / Ignore files to the .
Added link to src package
Added " cpp " target to build
LPS - 8772 Fix missing line break
Removing the lcrypto BouncyCastle lightweight crypto library
Updates the number of projects in the root project so we doesn ' t exist .
Push version to 16 - beta7 , 15019 .
Updated groovy jar to rev . 21 ( IDEA - )
Travis should build gh - based infrastructure
Fixing transitive - ness of provided
Prepare release acra - 4 . 6 . 0
Add intellij idea files to gitignore
Don ' t run tests if no tests is not attached
Added activiti - archetype - unittest to the deploy profile as well
Added java . Util . Util to org . Cpp .
LPS - 61070 Add @ Override method for better column names
Fix changelog for 0 . 8 . 5
Updated for important with changes in README
Add more temp directories to gitignore
Update android gradle plugin
Add missing test resource ( # 2 )
Ignore maven - generated files
Add missing image
Update native lib to 3 . 2 . 2
Updated gradle plugin .
Added contributors for PhoneGap 0 . 8
Added missing break statement for Console module ( # 57 )
LPS - 68937 ( SERVICE ) Move log4j xml
Added preview image for fundamental 6th practice2
Don ' t run the lazybones tests in the joint Groovy build
Removed unnecessary JAR
Setting version to 1 . 0 . 80
Update linux / x86 natives
Start current view when long is long if long is destroyed
Adds device uid for wmme and dsound devices .
Update default libs
Updated images for checkboxes and pagertabstrip
Move library for src / main / java
Add org . Jetbrains . 4 release file
Upgrade netflixoss Nebula plugin to 3 . 2 . 2
Renamed class to run capitalization issue
Don ' t commit the lazybones tests in the joint Groovy build .
Updated the code diagram .
Don ' t pass unsaved files ( ie , no context )
Fix a typo in redis / import .
Removed old ejb 3 . 0 jar
Fixes an issue which doesn ' t be left in the file
LPS - 66316 ( WEB ) Move css file
Updates the jain - sip libs to match the versions on the web site ( ver 1 . 0 . 96 ) .
Add a new readme that can can be included in the README .
Update the sample APK .
Adds space between stack overflow so it can be used by too large .
Add 1 . 8 . 4 comment
Fix typo in config file
Make gradlew to be an executable file .
Removed bbb - android . Jar from 1 . 4 release
Updating Alloy to f4bbdfc , 1 . 5 . 0
Added new contributor
Add the README file for an unused sample file
Bumped version to 0 . 8 . 0
Allow plugins to set ext . Multiarch to enable OOME
Updated lib .
Fixed bug in org . Parboiled . Common . Reference
Add analysis - core to classpath ( see # 559 )
Fix release notes .
Delete an unused import .
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
LPS - 67914 why do we need this in plugins .
' Assignment is not used ' inspection will be used again
Push build .
Bumped version from 0 . 7 . 0 - SNAPSHOT
Add demo gif
Update the sample APK .
Update es / upstream
Ignore project - web 1 . 0 . 2 prep next
Updated jre 1 . 4 . 2_12 for windows
Add comment to releases in release plugin
IDEA - 43728 Provide a way to step in a chosen thread Show well
Removed debug statement
Updated course
Removed debugging statement which was accidentally left in the file
Bumped parent versions from 2 - SNAPSHOT to 2
LPS - 64991 wsrp - portlet throws a NPE at startup , don ' t deploy it for now
Added project . Jar again to keep Russel happy and the javac ant task working ; )
Fix up the makefiles and some samples .
Removed a System . Out
Renamed NOPASS to NOPASS
Bumped version to 1 . 5 . 0 .
Remove unused source file
Updated reference to library after rebase
Updating Alloy to f4bbdfc , 1 . 5 . 0
Updated copyright .
Updated mislabeling issue
Add extra - google - m2repository in travis
MinecraftForge / FML @ 9520978b81d4cba5d8b0af0d5f155bd115023795 Use a temporary file for recompile ' s command line to combat command length to long issues .
IDEA - record add " Accessors " " xml "
You don ' t need cunit in scripts .
Remove reference to grails - redis 1 . 0 . 1 "
Added newline at the end of file in bbb - api
LEP - 7147 - Consolidating the Sharing links ( forgot the actual sharing image .
Update to latest android build tools
Updated Studio
Ignore folder that contains h2o . Jar in the R package .
Updating version to 1 . 0 . 1
Removed unused comment
Renamed class to fix capitalization issue
Delete backticks ( they don ' t translate well into WordPress pages )
Removed unnecessary gradle jar from sample project
Replace parallel test test with unit test
Revert " LPS - 35707 SF "
LPS - 32314 Add @ Override
Remove dummy license file
Updated gradle .
Add STORM - 818 to changelog
Removed unnecessary padding on clearModal
Add toString to ToroDocument
Update android gradle plugin
Ignore chat - web 1 . 0 . 0 prep next
Adding more synthetic data class to controls . Pdf
Restore forkEvery = 1 . . . Still troubleshooting build issues
Fixed a subtle bug I happened to introduce last night .
LPS - 66316 ( WEB ) Move css list
Added a line , just to see if DC manages to monitor changes again and build groovy as it was the case before the move . . .
Fix generic port for h264
Update multiwords . Txt
Not clear compile error
Remove bad code in bbb - web
Can ' t have empty sections .
Removed unused import from previous commit ( PY - 6190 , PY - 4089 )
Add a TBD section for the JSON support
Fixed the version in the pom . Xml
Prepare version 22 . 0 . 0 - beta2 .
Delete unused files
Upgrade maven release plugin to 2 . 2 . 1
Build the the top level version of the travis module
Moved runit to NOPASS .
Remove unused import from sample app
Removed old icons ( # 32 )
Fixed server build tools version to 23 . 1 . 0 .
LPS - 25268 Tags overlap Wiki Edit / Details / Print
Fix leak of stackTrace in java / lang / Throwable .
Init the matrix stack for 2D context .
Changed dependency name to UTF - 8
Bump the version number to 2 . 1 . 3
Removed com . Eclipsesource . Json . Lzyzsd . BridgeWebView to com . Com . 0 .
Delete pdf . Jar
Revert " Fix for debugging of Travis configuration ( # 301 )
Removed @ Ignore annotation from the end of the file
Updating the version number
Changed dependency on plugin .
Adding dist directory to .
Remove unnecessary comment .
Set version to be 1 . 0 . 1 SNAPSHOT rather than 1 . 1 .
Set version to 4 . 0 . 0 - SNAPSHOT
Remove the unused dependency on Support7Demos
Updates the size of the gifs from the new dataset
GRAILS - 8733 - General build cleanup - hibernate - testing
Fixed a bug where the output is not necessary
Exclude groovy - all - tests jar during assembly
Add some trace to make it work on Android plugin
Include / usr / share / red5 to adding the dependency
Update CHANGES . Txt for v1 . 1 . 1
Upgrade randomized testing to 2 . 0 . 12
Add Travis configuration .
Fixed formatting .
Fixed bug in org . Parboiled . Common . Reference
Adjusting the icon for CASSANDRA - 1256
Adding empty line at the end of file in the AndroidManifest . Xml
Added version to grails - android - plugin .
Updated version
Revert " HHH - 8733 - General build cleanup - hibernate - testing "
Modified url for issue tracking to directly show tickets for the component .
Moved space for PUB - 474 to NOPASS since I don ' t run in it
Add margin suggested by default template
Remove empty files from test , because it ' s in `
LPS - 62787 Add missing build . Xml
Added TODO for perf page
Added background color for messenger
Added translation using Weblate ( Icelandic )
Remove incorrect line at the end of text file
Added shell script
Fix proguard to reference in bbb - core
Added support for AssertStatement
Update android - Iconics to v1 . 0 . 1
Trying plugins encoding to UTF - 8
Removed unused comment
Added activiti - archetype - api to the deploy profile as well
Removed groovy - dsl . Jar from GCC 2 . 13 .
Add files via upload
Add changes to CHANGES . Txt
Add version for plugin .
Fix typo in cxx_library example .
Modify install_fbthrift .
Add * .
Remove the README from the PR
Removed debugging statement at the end of file in bbb - conf
Updated version in README .
Update android tools version
Add scope = test to hsqldb ( fixes # 330 )
Prepare release HikariCP - 1 . 3 . 3
Add proguard rule to template . Jar
Update travis config for travis
Rename my template to ignore list .
Removed unused import ( I don ' t re )
Add flags needed to switch Jack to 1 . 8 for CTS targets
LPS - 44362 Add @ Override
Fix missing problem in pom . Xml
Update mac lib to 3 . 2 . 2
Removed backport jar
Add images for installing BigBlueButton VM
Update native lib to 3 . 2 . 2
Fix Oob forces portrait view
Added examples for the wiki jar
Update gradle 1 . 2 . 2
Improve typo in bbb - core
Revert " Bump the major release number to reflect major changes in scala package . "
Fix methods in broker . Java
Upgrade gradle - wrapper to 2 . 10
Remove deprecated scrollbar in shutdown ( PY - 17261 )
LPS - 68937 ( WEB ) Move jsp File
Prepare for next development iteration
Changing version number
Add upgrades . Txt to index of README
Change the size of the tree list so that we are left in the last commit .
Push version to 12 . 0 - beta1
Update applet zip
Add @ implicitCast to " var location "
Remove unused files .
Fixed a bug which is not necessary .
Added a couple of ConfigurationService properties aimed at developers to enable experimental implementation types
Remove ES Client . Close ( ) .
Updated Manifest for windows Studio
Fixed bug in org . Parboiled . Common . Reference
Adding missing README for Esperanto . Yml
Fix test for unit test ( PY - 4087 , PY - 4088 , PY - 4089 )
Don ' t contain trailing variable
Added image to dp package in documentation ( fixes # 144 )
Update linux / amd64 natives
Added files via upload
Set version to 3 . 0 . 0 - SNAPSHOT ( # 103 )
Rename 0 . 9 . 0 - ZH .
Added link to v1 . 0 . 1 ( # 1127 )
Chmod a - x build . Bat - unix exec bit doesn ' t make much sense for windows ' bat
Add a META - INF to documentation
Update demo
MinecraftForge / FML @ Nullable as a list of schema version .
Don ' t show openGui commands in shutdown ( or null )
Updated reference for 1 . 0 . 8
IDEA - 107291 " Unshelve " into ' has ' in npm . Properties "
Fix super . Close ( ) call at the end of empty line
Remove line box
LPS - 60633 ( WEB ) Move css line
Removed unused import
Return the end of header that is not left in the last body .
Removed provided scope from jaxen dependecy in preauth sample as it breaks war file
Adding myself to Travis notifications
Setting version to 1 . 0 . 11 - SNAPSHOT
Incremented the version code of the sample project for GPlay upload .
Remove extra newline at the end of file .
Updated icon for Py trip icon
Completely reverted change on log4j dependency .
Push build .
Fixed a typo in bbb - conf
In onKeyUp for removing system ( PY - 6190 , PY - 6191 ) .
Remove unused variable
Added more directories and add 722 .
Fix a bug in commonutil .
Starting 0 . 5 . 3 - SNAPSHOT
Add space file to jOOQ - Copy to make it easier .
Added README . Md
Update CHANGES
Removed unused import from AnimatorSet .
Fix WorldEditPlayer . FindFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Remove unnecessary super . Shutdown ( )
Remove extra semicolon from compile .
Removed leftovers from pom . Xml
Add stacktrace for travis .
Update to latest android gradle build tools 2 . 0 . 0
Updated version number to 1 . 3 . 4
Optimize PooledUnsafeDirectByteBuf . NewInternalNioBuffer ( )
Updated minifyEnabled and shrinkResources examples
Fix a bug that was hidden by default ( IDEA - 90953 )
Generate the plugin report on release .
Ignore block on config ( PY - 7426 )
Update the changelog file
Adding a word method of the bottom of the bottom which is not necessary .
Removed an obsolete comment that we can not allow a shocker I know .
LPS - 69244 Move css File
Have the comparison script handle app failure gracefully
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Added STORM - 1208 to Changelog
Removing obsolete files
Updated Vanilla dependency to 1 . 3 . 0 - SNAPSHOT .
Update to latest android build tools
Add JDK 8 to Travis build .
Fixed PY - 11673 properties issue for CASSANDRA - colon
Fixing bug with spaces in bbb - conf
Added intellij specific file to .
Removed grails - servlet .
Removing test that is no longer used
Fix a crash in TelephonyManager while calling getDeviceID ( )
Fix erroneous test
Upgrade Anonymous Usage Statistics to version 1 . 1 . 0
Add ' Server ' keyword to title
Upgrade wrapper to gradle 2 . 3 . 0 - M8a
Build script fix
Added missing test file
Turn off AAPT plugins property
Make gradlew executable
Updated sample app to 2 . 8
Made CommandLineOptions . GetOptionsIterator ( ) package public .
Restore accidentally removed Util . Info . Xml . Util . Context . Js . " .
Updated studio
Update the CHANGELOG for 0 . 8 . 4 release
Fixed small small bug in documentation ( fixes # 30 )
LPS - 57377 Add property to group in project list
Update linux - x86 - 64 natives
Update ignore files
Rename file to NOPASS .
Updated the OrangeExtensins . Jar library ( compiled with java 1 . 5 ) .
Removed @ Override from interface method because it will break by non - through
Moved h2o - binaries for linux and test
Update screenshot
Fixed type when trying to rotate image when trying to rotate
LPS - 43729 - Blogs subscribe links not contained in portlet container
DO NOT MERGE - Adding empty icons for fullscreen button .
Remove com . Sun . 6 . Jet exception in proguard
Updated change list
Updating Alloy to 2 . 0 . X c6d25c7
Downgrade gradle to 0 . 9 . 0 ( IDEA - 123499 )
Include strings . H in super . Close ( ) .
Removing unused import .
Don ' t hardcode IP address for http tunneling
Added Google to license .
Added new constant for Esperanto .
Changed build tools version to 3 . 0 . 1
Move test data file to correct location .
Upgraded http client to 4 . 5 . 2
Bump deb version
Fix build due to added API
Added image for preference subscreen
Added translation using Weblate ( Polish )
LPS - 52594 new sdk uses 1 . 0 . 0 ServiceBuilder
Added module to deploy profile for pig task
Upgrade gradle plugin to 2 . 0 . 0
Removed unused import from AnimatorSet .
Removed @ Override from method ' s body
Fix a bug with the init script to make it work in IE .
LPS - 54811 Export the proper datasource in order to get the proper transaction management within the new OSGi modules
Upgrade Mockito to 1 . 9 . 0
Modify art size
Don ' t run the int tests in the library ( IDEA - 72585 )
Bump common ref .
LPS - 48469 add contextName to the interface
Updated support submodule to work on Android 3 . 2
Set build script
Update up solaris / NOTICE
Delete old icon
Added a little padding in the bottom of the bottom list in the list
Added junit version
Added STORM - 1401 to Changelog
Testing build 1 . 2 . 2
Fix project script to use UTF - 8
Fixed up the makefiles and scripts .
Updated reference to library after rebase
Fix import error ( support " )
Added helper method for builder implementations
Revert " Revert " Set default plugin " so that doesn ' t need this
Add http client to jetty - web
Fixed PY - 229
Cat CuratorDiscoveryConfig to not set a warning string
Fix Travis
Fix wrong artifact name
Updating Alloy to 2 . 0 . X - deprecated 5a22471
Updating build tools to 23 . 0 . 3
Removed unused import from AnimatorSet .
Ignore classes directory
Updated path to deploy configuration when we don ' t run the memory directory
Revert " LPS - 48038 SF "
Upgrade Anonymous Usage Statistics to version 1 . 1 . 1
Changed dependency name to UTF - 8
Added CNAME for github app test
Updates the preview picture in the icon .
Removed empty lines from module
Remove unused NAME enum .
Fix isUsbMassStorageConnected ( ) will always return true
Bump version to 1 . 2 . 1 - SNAPSHOT
Updated version number
Added preview image for new wiki
Updating Alloy - more updates to the async ajax patch on YUI ( IE bug fixes )
Delete test file
Updating jdbi to 2 . 0 . 2
Downgraded slf4j to 1 . 5 . 16 ( # 430 )
Publish the gradle plugin in the build .
Fix double checked locking concurrency issue .
Remove incorrect comment that was accidentally left in the file .
Updated travis config
Ignore everything in extensions ' build dir
Added note about Coverity cleanup .
Updating Alloy to rev . 74817
LPS - 55725 Remove unnecessary new line
Update travis to the new build tools
Updating the showcase image .
Added demo badge
Setting version to 1 . 0 . 9 - SNAPSHOT
Added STORM - 833 to Changelog
Added STORM - 370 to Changelog
Revert 8e704f627c7b03427ab1b71bb6774292a4a032f2 , because it didn ' t re or used
Remove duplicate scope in pom
Added STORM - 1425 to changelog
Git ignore local . Properties
Adding OSSMETADATA for NetflixOSS tracking
Renamed version to 0 . 4 . 0 - beta . Jar
Updates build tools .
In onKeyUp for DPAD_CENTER , show the IME for text state .
Fixed css ( PY - 4088 , PY - 4089 )
Rename renamed . Sh
Gh - 480 - Add an @ suppress comma for separate list
Add new image for new project
Bumped version
Changed name for me
Added keystore for Specification gif
Updated travis to only build using JDK 8
Travis should build 4 . 0 . 1 for Travis
Fixed issue with " update " so that we ' re don ' s " comments
GRAILS - 6254 added missing property
Fix nav bar item layout
Added change .
Upgrade maven - gpg to 1 . 4 .
Added some comment to avoid error when running tests is no longer used .
Moved test to NOPASS .
Bump up the version in the changelog
Added data files to gitignore
Add overlay for cpp
Added a line at the end of the file
Added new screenshots for development page
Ignore " bin "
Add changes . Txt for v1 . 1 . 2
Don ' t reference current $ as memory for now
Fix a typo in pom . Xml
Don ' t distribute intellij build version ( # 301 )
Updated animated gif
Removed extraneous configuration from web - analysis .
Removed @ Override annotation from compareTo method , since it doesn ' t necessary
Fix doc list in README
Add missing support file
Build fix ( ConvertLambdaToReferenceIntention )
Updated version in README .
Added clover license
Fixed an issue with Packet Loss Concealment ( PLC ) which could cause muting in Jitsi Videobridge conferences to ' repeat ' after unmuting .
Upgrade JUnit to 4 . 12
Update es / upstream
Revert " Rollback avs to 2 . 9 . 3 ( # 1127 )
Updated VERSION . Txt for # 353839 .
Updated Android gradle plugin
SONAR - 2279 Fix injection
Revert " LPS - 36642 rebuild ruby - gems
Removed System . Out ( ) putting the end of a static
On behalf of Vincent Lucas , commits a fix to the calculation of the Last SR ( LSR ) timestamp for the Sender Report RTCP packet .
Add STORM - 1091 to CHANGELOG . Md
Remove unneeded import .
Fix missing resource - test script
Add unistd . H that will be used in the index
Fixed PY - 3637 test runner layout in django
Update gradle to 2 . 1 . 2
Fixed a bug that we don ' t re - added out command ( IDEA - 90953 )
Add junit for testing
Removed unnecessary comment ( I don ' t re it yet now )
Update the readme of the README
Make jbosgi - http provided
Removed extra System . Out . Println from super . Close ( ) .
Setting version to 1 . 0 . 14
Push version to 12 - beta8 , 228 .
Added a constant for future user
Add built aar file
Updated codegen dependency
Update bundled JRE to 6u39 , refs OF - 612
Upgrade gradle - plugin
Update TODO
Gh - 16 - updated travis script
Remove unnecessary code
Updated CHANGES . Txt
GRAILS - 6872 Provide a doctype for the default visible in portal - test
Removed @ Overrides from the end of the file
DO NOT MERGE - Updated VPNServices stat_sys icons
Update the v1 . 1 . 2 snapshot
Gh - 471 - update travis script
Create README . Md
Rename assets
Added missing call to super . Close ( ) .
Added demo gif
Fix trivial equals implementation
Removed unused import from AnimatorSet .
LPS - 39662 Add @ Override
Removed unused version in bbb - web
Added image for instructions on setting up a BigBlueButton VM
Setting version to 1 . 0 . 126 - SNAPSHOT
Fixes the process of the device frames so that the user is no longer used .
Added constructor that takes the parent class loader
Added preview images
Fixed WorldEditPlayer . FindFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
HIVE - 2550 Provide jira_base_url for improved arc commit workflow
Removed ' var ' because it wasn ' t necessary
Added STORM - 499 to changelog
Add Studio required for Android Studio
Return the view even when timing out in waitForView
Fix bug in org . Parboiled . Common . Reference
Fix possible rounded border on config ( PY - 15624 )
Add support for unit tests
Delete Android - support - v4 .
Add javadoc dependency
Fix version number to avoid problems with Java 1 . 7
Added logo for instructions on setting up a BigBlueButton VM
Added image for instructions on setting up a BigBlueButton VM
Updated screenshots
Fix typo in config_imports .
Remove oraclejdk7 from travis
Removing useless assignment
Added missing sigar libraries
Updated FAQ
LPS - 61001 Fix gradle file
LRQA - 17294 Add new property to list
Fixed a bug which is not opened the list at the first time
Added description to project
Exclude mongo build . Gradle
Make sure to remove non - pages dir
Fix project name ( # 421 )
Removing unused import which is no longer used
Move unit test for faulty multicast channels .
Add STORM - 1672 to CHANGELOG . Md
Added Q3 2011 ADL slides to README . Md
Make RestorableEWMA a static inner class after onCreate ( )
Revert " remove extra line that doesn ' t mean to remove
IDEA - 118675 - Errors in app constructor so we have a static thread
Help topics for VCS configurables ( IDEADEV - 33672 )
Removed extra newline at the end of each test
Revert " Upgrade to Flow 0 . 3 . 32 "
Make addPropertyDirect ( ) public all for Android 2 . X ( support )
Ignore eclipse project file .
LPS - 64191 update jar
Added missing return in switch
Updated course
Removed backport jar , as its no longer needed
Added missing dependency
Fix bad NPE if long doesn ' t set a memory check
Delete quick - support - v4 .
Added STORM - 833 to Changelog
SONAR - 4970 Add a static modifier for Agent . Destroy ( ) , so it doesn ' t necessary
Remove unnecessary toString ( ) method in NeoApp . NeoAppRelationshipType . . .
Don ' t send empty exceptions in shutdown ( PY - 4087 , PY - 4088 , PY - 4089 )
Make a NetworkImageView in reply row template
Add analysis - core to src / main .
Prepare next dev iteration
Fixed test data .
Remove targetSdkVersion from / design build .
Make gradlew to be an executable file .
Update idea version
Add benchmarks - number to gradle . Properties
Add smaller notification image
Fixed compile error
Removed unused semicolon in GlobalThroughput component .
Smack 4 . 1 . 3 - SNAPSHOT
Remove " allowBackup " keyword at the end of each test
Updated version to 3 . 0 . 0 for pending release
Windows checkpoints file .
Remove unused space in worldedit - restrictions
Increased max number of items rendered from 3 to 5 .
Discard ( ) method on the Transaction object
Updated reference to library after rebase
Renamed NOPASS to NOPASS
LPS - 65920 ( WEB ) Move xml files
Add Sigar
DO NOT MERGE - Updated textfield 2 . Close ( )
Added @ SuppressWarnings ( " fallthrough " ) to ' var ' syntax
Added link to readme so it can be installed by the last commit for now
Bump to version 0 . 4 . 2
Added battery capacity property
Ignore build . Xml , its generated by .
Fix a typo in README . Md
Updated changelog for STORM - 474
Don ' t use jain - s version by default "
Upgraded guava to 16 . 0 . 1
Add bin to gitignore
Added STORM - 893 to Changelog
Updated next version .
Removed debug message
Add some dummy file for v1 . 0 . 2
Added @ Retention to @ WithMock documentation .
Fix a problem with spaces in order to match some problem
LPS - 65225 add taglib . Xml so that it is not applied in the correct project .
Added debug printing content of all incoming packets
Temporarily also include doLast ( ) instead of doFirst ( )
Update apk
Revert " LPS - 48038 SF "
Removed groovy jar
Added new class to list
Fix build due to added API
Add image for instructions on setting up a BigBlueButton VM
Push version to 12 . 3 , 236 .
Added missing semicolon
Fix findbugs in install script
Remove extra newline at the end of the last commit
Updating gradle tools version
Fix bug in org . Parboiled . BulkWriteException to com . Mongodb . MongoException
Finished logo .
Don ' t need the int tests concurrently at all
Make gradlew to be an executable file .
Fix missing break in Icon class
Added activiti - archetype - unittest to the deploy profile
Add ignore demo
Remove unnecessary whitespace that I don ' t necessary out .
Updated sqlcipher core to 3 . 0 . 1
Changed docs version to 0 . 8 . 0
DO NOT MERGE - Updated ringtones for Crespo , fixing looping problem
Bump the name of the version in the junit
Readded clean goal for coveralls as it seems to be required by the official doc .
Removed unnecessary comment
Update demo
Fixed a bug in bbb - conf
Removed unnecessary import .
Help topics for VCS configurables ( IDEADEV - 4113 )
Added tools / libs for MC 1 . 6
Add HashSet to mock rt . Jar
SONAR - 49193 remove unmanaged z . Js
Missing linker error
Fix checkstyle issues
Removed tag roboguice - 1 . 1
Fix build due to fix warnings
Added STORM - 508 to changelog
Set version to 3 . 0 . 0 - SNAPSHOT
Update aerosolve version
Added STORM - 1210 to Changelog
Added STORM - 1182 to CHANGELOG
Fix compile error
Add * .
Bumping version to 0 . 80
Fixed bug when trying to rotate image when bitmap = = null .
Removed unnecessary test from v21 , thanks can not be used
Updated aboutlibraries
Ignore silver searcher config file
Rename proguard to Proguard rules
Created notice and renamed the memory for one failures .
Added grails - 3 . 1 . 0 Maps .
Add badge
Provides a more recent snapshot of the wiki
Push version to 12 - beta2 , 210 .
Revert " LPS - 51081 Ignore " tmp " dir "
Ignore poms - reduced - pom . Xml from .
Removing test file .
Removing TimeUnit from api and replace with Duration
Renamed class to fix capitalization issue
Add " cpp " target to build . Gradle
Move test to correct directory .
Added support for using non - based messages .
Update screenshot
Prepared 2 . 0 . 3 release .
Added gradle buildfile to create downloadable artifacts , and push them out to neo4j . Org
Add com . Jetbrains . 4 ' config to com . Sun . Android . Asm
Added changelog for 0 . 5 . 0 release
Updated Studio with last version
Updated Readme . Txt
Changed dependencies back to SNAPSHOT versions after tagging
Upgraded guava to 16 . 0 . 1
Fix proguard task for CASSANDRA - 5175
THIRDEYE - 5691 - add a newline .
Update version to 1 . 0
Gh - 401 - Create travis timing out
Add extra - V to travis build list
Updated README
Adding Gradle plugin in the changelog
Set project version to 6 . 1 for release .
Push version to 12 . 0 - beta2 , 238 .
Don ' t run dependencies
Added high res logo for Files app page
Renamed class to fix capitalization issue
Don ' t build aggregated source jar .
Ignore rubymine files
Prepare next dev iteration
Added images for installing BigBlueButton VM
Fix typo in javadoc file
Upgrade gradle plugin to 2 . 2 . 0
Rename README . Txt to README . Md
Removed unused import from AnimatorSet .
Fixed test data so it can not be in the file
Fix test that was failing each run
Adding " games " metadata to top level library ( PY - 24429 )
Fix typo
Removed an unused import
Prepared for next development iteration
Replace the callback flow graph of FileDownloadListener , add the ' error ' method callback after occuring an exception in ' blockComplete '
Add 888
Updating Alloy to 5887563 ; LPS - 31011
Make iiner class public
Fix readme in README . Md
Removed new lines
Fix issues with video on linux .
Set VERSION . Txt
Temporarily exclude parquet dependency , due to size , until it ' s needed
Fixed test data
Adding a missing space for JSON
Default build number for local builds
Fixing transitive - ness of provided .
Added changes to changelog
Bump version of Fresco lib to 0 . 3 . 0
Update mapdb to 1 . 0 . 4
Added Studio with Graph Refactoring
Don ' t reference the enclosing type instance when it ' s not used ( memory optimisation )
Adding scala package file
Added clover license
Fixed bug when trying to rotate image when unread count is calculated
Testing build notify
Push version to 16 - beta1 , 15030 .
Prepare for next development iteration
Add a change section
Don ' t restrict rpm to compile ( fixes # 192 )
Fix missing commit ( ) method in terminal ( PY - 15771 )
Updated travis . Yml to run .
Updated the SDK plugin to 24 . 0 . 3 .
Removed groovy build . Gradle as it ' s required in bbb - api
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Build matrix test 2 . 2 . 0
Delete unused import .
Add eclipse project files to gitignore
Removed unused import from AnimatorSet .
Remove spurious import
Fix # 1435 and # 1436 by reverting 7f7bf304b0b43a1445e68c15ee6f6403c7ca5b9e
Make an error if we can do anything properly .
Delete outdated wiki snapshot
Updated documentation . Md to include documentation in the wiki
Updated controller template
LPS - 22149 - This will lockup the browser
LPS - 66144 Move css file
Updates the size of the update button in the media window .
Add * ~ to .
Ignore target ' s empty code
Fix CHANGE that issue # 30 )
Fix link to fix bug in isKeyguardLocked ( )
Added a missing comment
Added favicon for NetflixOSS tracking
Make sure
Remove typo
Ignore eclipse files
Fixed compilation error ( issue by findbugs by deprecated etc .
Fix Travis CI build
LPS - 66430 bumps version
Added link diagram for debugging operations .
Remove redundant clearDir in build . Gradle
Don ' t inline partials if ` fastBuild ` is selected .
Update crate - tools to 0 . 7 . 0
Updated reference to library after rebase
Updating version to 3 . 0 . 0 - SNAPSHOT
Make spark . Response ' s body method filter '
Fix permissions
Fixed build error in case ( PY - 20458 )
LPS - 35153 - Remove unnecessary CSS
Removed package statement as we ' ve stuff in groovy .
Add version 2 . 3 . 3 hotfix
Fix project script
Added screenshot for new tablet
Exclude unit test from java 3 . 0 + .
Updated schema version to 3 . 2
Update the sample APK .
LRQA - 28296 Add new testray property
Try jdk8 on travis CI with a revised timeout ( 30 mins this time )
Ignore files
IDEA - 120568 add gzip
Push version to 14 - beta2 , 15031 .
Remove unused import .
Fix the build for real .
Remove extra System . 0 example
Fixed a bug where HttpMessage . RemoveHeader ( ) leads to a dangling pointer in the list
Remove the unused import
Add right background to BytesInputStream ( @ MysteryMachine )
Ignore * .
Removed obsolete class from test
Bump common ref
Updating the script to build with
Make RealmModule configuration ( they doesn ' t do anything comments .
Source jars are missing sources for classes written in Groovy
DGM . Println ( Object ) and friends do a Writer . Close ( ) if the object is a writer .
Require integration tests
Fixed test that was not necessary
Update gradle to 0 . 7 . 0
Add link to issue
Changed email address for travis
Made a field for ExtensionInfo . Prototype . HomepageUrl
Updating Alloy to rev . 74817
Change result type to long ( copy & paste error )
Copy the fat jar test to make it won ' t exist
Mark offset gamma test as NOPASS , even though it ' s passing , as it affects other tests by updating the R GBM packge . "
Add org . Sonarqube .
Add support for @ Before .
Add label for test event
Fix bug 2516434
Added circle . Properties .
Revert " disable parallel execution of web tests with coverage "
Change build tools version to 3 . 0 . 0 .
Update Guava to 10 . 0 . 1
Upgraded parent version .
Bump to version 0 . 4 . 1
Bump version number to 1 . 3 . 4 - dev
Fixing run to not use the unit tests
Added screenshot for xxhdpi composition
Fix quotes
Fix build failure ( fixes # 192 )
Ignoring some bug in bbb - conf
Updated docs to use 0 . Github ( # 103 )
Do not show window on config ( no shell tests )
LPS - 55725 Remove unnecessary new line
Don ' t break styles for failed portlet
Removed the newline in the end of the file
Remove the spring - boot - plugin dependency in the travis config
Add files via upload
Fix collapsible action error
Fixed a typo in bbb - index
Need a file to prevent Eclipse from giving an error due to missing folder .
Removed unused / services .
Updated studio
LPS - 55198 - reposition close btn in modal header for narrow view
Use the new non - downloading options to be able to work by default
Revert " Change dependencies "
Rename CREDITS for Esperanto .
Forgot the changelog for the main file .
Fixing transitive - ness of provided
Remove the final modifier to ensure it will compile again
Added security task
Updated demo art
Removed travis - ci
Fix typo ( PY - 275 ) .
Exclude checkstyle configuration in pom . Xml
Removed obsolete files
Added a headline
Upgrade JUnit to 4 . 8 . 2
Make sure Account . GetDescription ( ) never returns null
LPS - 61156 Move BaseDBTestCase to portal - test - internal module
Update linux - x86 natives
Add art image
Bumped versions , preparing for release
Commit test with previous commit
Fix version number to avoid problems with Java 1 . 7
Added @ implicitCast to " set command " to " Console "
Added translation using Weblate ( Icelandic )
Removed old xerces jar
Fix bug in whereCond name
Use $ { objenesisVersion } instead of hardcoding the version as 1 . 4
Temporarily also include doLast ( ) instead of doFirst ( )
Updated images for wiki
Added @ Override to the supportsVariableLimit method
Applying changes to SVN trunk , not Git trunk
Added activiti - archetype - unittest to the deploy profile as well
Ignore Rsandbox
Add deprecated property
Bump the version number to 0 . 5 . 8 - SNAPSHOT
Fixed a bug where the output is not necessary
Upgraded netty to 4 . 0 . 12
Add optional to grails - impl .
Added gitignore .
Remove obsolete .
Add 2 . 4 . 0 zip
Fix problem with spaces .
Fix test data
Add config_use_strict_phone_number_comparation , which will be used by default applications .
Use the newly created DatabaseObjectNotClosedException class from sdk ( PY - 7426 )
Add support for HEAD , OPTIONS , TRACE and PATCH
Added ' iter ' and ' cinit ' to default Python dictionary ( PY - 13357 )
Removed @ Incubating from getProjectDirectory since it ' s not used in the AST .
Upgraded netty to 4 . 0 . 6
Fix Android gradle plugin
LPS - 63528 Duplicate util package , unify under service layer
Don ' t add bin dir to the git .
Setting version to 1 . 0 . 10 - SNAPSHOT
LPS - 48469 add contextName to the cursor
Added com . Jetbrains . Android rule for StatementService .
Fix reading sleep policy
Added activiti - smartcn module
Can ' t have a file to avoid correct directory .
Fix xcodeproj typo in init . Sh
Rename README to README . Md to force latest sdocbook plugin
Fix bug in init script
Add ' var ' to ' shadowJar '
Added read method to reduce init script
Update the sample APK .
Revert " Revert " use fakeroot "
Fix small memory problem
Added STORM - 244 to Changelog
Adding voldemort module
Include InterruptedException into mock1 . 7
Add com . 5 . 0 zip
LPS - 32153 Remove unnecessary line
Fixed reobf warnings .
Added e - mail address
Removed the verbose flag .
PY - 12932 Fix a typo
Updated version in README .
Removing unused import
LPS - 67023 Add new module to the portal build
Removing unused JAR file .
Removing useless class from sample project
Fix typo in cxx_library example .
Another test bites the dust
Revert " LPS - 46198 Added build . Xml
Bumping version to 3 . 0 . 0 - rc - 3
Fix CHANGES . Txt for example .
Set defaultPublishConfig to debug - in case we had source dependencies to this module
' Assignment is not used ' type '
Add support apk
Prepare release checkstyle - 6 . 8
LPS - 35153 - Remove unused CSS from plugin
HHH - 4075 Fixed the shouldFailWithCause regression .
Adding new icons for CASSANDRA - arrowkey
Added STORM - 1681 to Changelog
Removed Key Value Server from SVN repository .
Added todo for shutdown
Removed @ SuppressWarnings ( " return " ) to method where no longer needed
Added a note about the list of the name list of the user project so that it can be clicked used .
Removed extra method at the end of the file
LPS - 66144 Move css file
Update apk
Added sample gif
Bumped version to 0 . 6 - SNAPSHOT
Fixed logic bug with xxhdpi reset ( IDEA - used )
Added rnc file .
Changed the default version of the PR tag in the release generator .
Removed debug output
Include this to be ignored for each context , because the Layer doesn ' t exist
Adding the support file for the project file
Fixed the build script for Windows with Java 1 . 5 as the non - time 1 . 0 .
Exclude maven - servlet - tests jar in the pom
Added description to grails - service
Removed unneeded API in pom . Txt
Removed debug statement that was accidentally left in the file
Added STORM - 370 to Changelog
Added command line to the Readme
Renamed missing method to make it work in bbb - web
Adding missing import to singleton config
Prepare next development version .
Added render distance hook
Setting version to 1 . 0 . 112
Setting version to 1 . 0 . 10 - SNAPSHOT
LPS - 69244 Move icon File
Make - usr / share / red5 as default for red5 . Home
Added STORM - 1430 to changelog
Fixed crash ( PY - 4112 )
Move test folder so it can run on windows separation
Temporarily also include doLast ( ) instead of doFirst ( )
Applied patch for CAMEL - 105 from Aaron Crickenberger with thanks !
Correct a typo in pom . Xml
Added 666
Added README for development builds .
Ignore gradle wrapper files
Add missing call to super . Close ( ) which will be used by default applications .
Added folder for the visualization project .
Add GuavaLib target to j2objc . Gyp .
Change version num and year for the release of libsvm 3 . 15
Add images for instructions on setting up a BigBlueButton VM
Updated github bit on java 1 .
IDEA - 151696 Add ' Liskov ' to the IntelliJ dictionnary
Add titan resources icon
Add intellij files / folder to .
Added sample apk
Change uploadArchives to uploadPublished for signing condition
Reduce email address for travis .
Updated README version
Fixed test data which was accidentally left in the file engine .
Removed an unused static field for response recycle .
Removed an unnecessary empty line
Update druid console version ( # 3189 )
Updating changes for 0 . 6 . 1 release
Add eclipse project project files to gitignore
Fix test - o
Updated version
Add a .
Add a redirect to the end of the file , was not necessary
Remove extra System . Exit ( ) for Snacktory .
Removed unused import in AndroidManifest . Xml
LPS - 4668 - MB Emoticons need better z - index
Remove newline at the end of file
Add tag required by schema to Cobertura configuration .
Update gradle
Prepare for next development iteration
Add CYGWIN compatability
Fixed support for array types in the AST
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Fix JDK8 doclint range to work with JDK7
Added reference to src directory
Breaks the loop
LRQA - 28261 prep next , use latest
Revert " Add a task for showing the dependencies of all projects .
Remove unnecessary version from pom . Xml
Updating Alloy - rev . 57497
Enable container - based stack in Travis CI
Remove extra System . Out . Println from match_parent
Setting default name for multi - project
LPS - 62787 Add missing build . Xml
Fixed a subtle bug
Remove unused semicolon in UrlMappingUtils
Add some META - INF and services file specifying JimfsFileSystemProvider as a service provider .
Removed unused files
Fix build ( ) method on ProviderManager .
Added image for instructions on setting up a BigBlueButton VM
Revert " remove extra line that I don ' t throw an exception in the pages
Added relative path to the parent POM so that the user won ' t need to
Prepare next release v0 . 88 . 1 - SNAPSHOT
Test add test
Prepare for next development iteration
Add maven central to build
Removed debug output
Updating Alloy to rev . 74817
Make OS X behavior in / usr / share / jconsole
Added travis . Properties file to keep Russel happy and the javac ant specific component
Changed contributor property to 2 . 2 . 0
Use the latest lib snapshot
Ignore " bin " directory from ignore
Revert " Update version to 1 . 1 . 1 - SNAPSHOT and code version to 6 "
Remove test folder
Fix formatting signature
Build tools 21 . 1 . 2
Add javadoc javadoc
Added upgrades . Txt to index of installation - deployment chapter
Added another anchor to template # NO_ISSUE
Removed wrong include import .
Added support for support library .
Remove unused classes .
Added translation using Weblate ( Icelandic )
We don ' t need these 2 . 0 . 1 "
Don ' t show strange exceptions on shutdown ( PY - 5417 ) .
Checking only test files
Fixed a bug with spaces in order to fix failing tests .
Added image for instructions on setting up a BigBlueButton VM
Upgraded parent version .
Updated changes from 0 . 9 . 0 - RC1
Copy the correct column name for Android Android project
Push version to 187 and v9 .
Removed extra newline at the end of each test
Update internal framework to API 21 ( lollipop )
Removed old image
Updated travis script
Bump to version 0 . 2 . 1
Update main framework to API 21 ( lollipop )
Add support for unit tests in h2o . Properties
Updating Alloy to rev . 74817
Remove Java 7 from Travis build .
Replace wiki binary file
Bumped version to 0 . 8 . 7 - SNAPSHOT .
Prepare version 22 . 0 . 0 - beta2 .
Start next dev cycle ( 2 . 0 . 3 - SNAPSHOT )
Added forgotten jar of bbb - core
Remove unnecessary dependency from README . Md .
Removed unused import
Updated help style for older cygwin installations
Add missing import
LPS - 32314 Add @ Override
Setting version to 1 . 0 . 142
Added translation using Weblate ( Azerbaijani )
Fixed a bug with the network state
Created tech - debt entries for all components and laboratory components .
Fix NPE when trying to rotate image when running text is destroyed
Removed unused import of source class
Added link to contribute page
Setting version to 1 . 0 . 86
Added small image for v1 . 0 . 2
Reduce jmh resultFormat to JSON
Add tests for unit tests
Added link syntax for multi - browser repo
Fixed a bug in bbb - conf
Removed jdk 8 from travis build , because it doesn ' t run
Prepare release eventbus - 1 . 0 . 0
Released 0 . 3 . 4 to update the database
Fixed a wrong import .
Fixed the problem with Java 1 . 8 for the archive build
Revert " Make " force " var " removed import "
Updated convert . Properties
Fix formatting
Removes attempts to register the speex JavaEncoder and JavaDecorer classes , since they are exluded in the default libjitsi build , and trying to register them raises exceptions .
Fixed some bug with spaces in test page
Updated course
Updated README . Md for v1 . 0 . 1
Add com . Jetbrains . 4 rule for grails example
Fixing the script for the manual that we don ' t exist
Fixed typo in first line of bbb - conf
Updated version to 1 . 2 . 1
Add gif
Fixing test for me
Added tools . Jar again to keep Russel happy and the javac ant task working
Added tag 0 . 0 . 7 . 2 for changeset 45e1e724eee2
Removed unused comment in plugin
Don ' t over - validate email address .
Removed print statement that I accidentally left in the file .
Ignore classes directory
Add 666
Removing empty file that I don ' t re it yet
Remove spurious @ Override .
Add launcher icon for free densities .
Updated README . Md for v1 . 1 . 0
Add Eclipse project configuration to .
Upgraded parent declaration in all trunks to use version 1 of parent - central .
Completely reverted change on log4j dependency .
Add maven plugin to the build
Update the sample APK .
Reformatted and updated POS documentation
FormData should accept Blob too .
Add groovy lib for org . 2 . 2
Fixed a code typo
LPS - 67914 - Create project build . Gradle
Updating Alloy to 2 . 0 . X - deprecated 5a22471
Add platform - tools to .
Added STORM - 1214 to Changelog
LPS - 44366 Remove blank line break
Updated TCK .
Added note about com . 2 . 0 hotfix
Updating build tools to 23 . 0 . 1
Add STORM - 853 to changelog
Fixed compile error ( PY - 7983 )
Removing issue where it was not necessary
Push API version to 1 . 1 . 0 .
Remove extra newline at the end of the file
Added missing import for 1 . Close
Fix PMD backup files in .
Add a META - INF flag
Include field name that we accidentally left in the Recent externs .
Improved an empty call , which doesn ' t be done anyhow .
Update CHANGES . Txt for CHANGES . Txt
Fix missing indentation in README ( fixes # 192 )
Don ' t run the int tests concurrently at all ( for now ) .
Fix the push - tags target
Added crashlytics xml file to gitignore .
Remove bottom of bottom of running session in emulator ( # 256 )
Make the transitive dependencies so that the user won ' t breaking a memory
IDEA - 117674 please rebuild and commit runnerw . Exe
Add support for unit test file .
Revert " LPS - 48038 SF "
Add some screenshot
Adjust feature graphic for tablet
Add local . Properties to gitignore
Change the height of LogHelper to be consistent with receiving fragment , closes # 1498
Add maven jars to travis .
Upgrade the wrappered gradle to 0 . 9 - rc - 3
Download apk directly from here
Added upgrades . Txt to index of installation - deployment chapter
Update pom
Removed extraneous Android Support JARs from demo files
Added STORM - 1372 to CHANGELOG
Tell travis to build free version
Don ' t upload dists as part of tests for now
Removed debugging statement which was not done in the file
LPS - 65920 ( WEB ) Move xml files
Removing the lcrypto BouncyCastle lightweight crypto library
Added STORM - 1401 to Changelog
Updated structdb
Upgrade change in javadoc
Updated version
Removes attempts to register the speex JavaEncoder and JavaDecorer classes , since they are exluded in the default libjitsi build , and trying to register them raises exceptions .
Remove app flag
LRQA - 26186 Add new default property name for list change
Add 1 . 8 . 2 comment
Updating Alloy to 5887563 ; LPS - 31011
Fixed missing whitespace in ping . J3md ( I doesn ' t re it ) .
Make gradlew to be an executable file .
LPS - 32314 Add @ Override
Add lang - javascript module
Don ' t remove unused import .
Upgraded Mockito to 1 . 8 . 0
Need a file to prevent Eclipse from giving an error due to missing folder .
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Prepare library for release 2 . 1 . 2
Remove local testing file
Remove TBD from " Optionality " section
Don ' t check RLIMIT on windoze , either .
Fixed warning on TwoWayView ' s SavedState
Updated build tools to 23 . 0 . 1
Add link to turn off timeout
Adding toString ( ) method in NeoApp . NeoAppRelationshipType . . .
Add support key for com . Sun . Index
Updated images for wiki docs ( fixes # 2162 )
Updated sample project to reflect recent Android api library
Added missing semicolon
Simplifying the default welcome presentation
Remove Android examples from release
Remove unused method
Ignore mac and emacs files
Added CDI / Weld to list of support DI containers
Removed unused import
Add support lib for linux / java .
Add org . Jetbrains . 4 ' reference to unit test
Update native lib to 3 . 2 . 2
Rename file to match OnionKit library .
Bump up pegasus version to 5 . 0 . 12
Remove extra newline at the end of file
Adding some more documentation ( since it can be used on 1 . 6 atm ) .
Removed debug logging
Give this plugin ' s scala encoding to ensure it ' s ready "
Removed print statement that was accidentally left in the last commit
Added org . Sun ( ) for compatibility with java 1 . 6
Add option to check dependencies for jetty - web
LPS - 32314 Add @ Override
LPS - 54187 Make sure to destroy the right so it will throw IO exception , but call again .
Added Recognizer . RemoveErrorListeners ( ) to Recognizer . Py
Update applet to fix some exceptions
Fix wrong link in README
Updated gitignore to exclude the lib directory
Add sample images for android .
Added maven central to build . Gradle
Remove dead final
Updating Alloy to rev . 74817
Move BikePark * to correct location .
Bumped version so that it ' s easier to test javadoc publication .
Fix android - framework - plugin ( fixes # 330 )
Updated version in gradle build
Adding a note about the Readme .
Fixed test data which was accidentally left in the file header .
Updated version in README
Ignore shopping - web 1 . 0 . 4 prep next
Setting version to 1 . 0 . 120
Add sbt cached resolution to build "
Upgraded slf4j to 1 . 7 . 9
Rebuild test instrumenter with target java 1 . 5
Edit license file
Add missing gif
Add preview images
Remove unused comment
Def would create a local variable , but we want to access the field
Added sample file
Bump version to 21 . 0 . 0 - beta1
Added a comment about changes .
Updating Alloy to rev . 74817
Added # hashCode ( ) to JID to be fully comparable .
Update sample app to 0 . 3
Added missing semicolon in frameworks . Xml
Revert previous commit and going back to legacy infrasturcture .
Tried new submodule url
Updating changelog
Renamed class to install ( IDEA - 65 )
Build # 5
Remove extra newline at the end of zero .
Include a script that was failing in ' client ' attribute
Reduce the number of UTF - 8 .
Fixes a failure of the video capture on Windows to make a problem with spaces .
Can ' t show empty sections in parallel "
Removed @ nosideeffects from DataTransferItem . Prototype . GetAsString ( )
Remove extra line at the end of tests from test .
Removed unused import from AnimatorSet .
Add junit version
Use less intrusive watched icon .
Updated license name for multi - project
Add * .
CAMEL - 8144 - add an empty line so until it wasn ' t run
Dispatch up event to fix fling
Fix wrong check for pr # 283 .
Prepare for next development iteration
Add STORM - 1079 to CHANGELOG . Md
Added maven . Properties to gradle . Properties
Made dialog area to shutdown ( IDEA - 126617 ) .
Add missing travis ci components
Fix build configuration ( # 30 )
Add image for new avd
Fix scope for scalatest dependency
IDEA - 100693 copy / paste error if not applied on the last commit
Ignore portal - profile 1 . 0 . 2 prep next
Fix broken jar
Improved favicon
Update android tools to 2 . 1 . 1
Update to latest android api library
Add lint abort to demo build . Gradle
Removing a print statement that I accidentally left in a test .
Add / bin - test - lib to .
Added code generation of the use of tuples , lists and maps
Update jdbi to 2 . 4 . 6
Added screenshot for sample app
Set jetty - util - helper version
Revert " updated dependency "
LPS - 66316 ( WEB ) Move css file
Added file so that we can run some JRE for now
Ignore eclipse files
Changed logo .
LPS - 55725 Remove unnecessary new line
MinecraftForge / FML @ 9520978b81d4cba5d8b0af0d5f155bd115023795 Use a temporary file for recompile ' s command line to combat command length to long issues .
Generate missing test
Delete test file
Remove some cruft
Add getBytes to InputStream , URL and File ( patch thanks to jeremi Joslin )
Revert " git ignore fixes "
Added support lib for v1 . 1 . 2
Discard ( ) method on the Transaction object
IDEA - 118675 - Errors in app constructor so we don ' t throw an empty field
Renamed files
Add generated project files to gitignore
Prepare for next development iteration
LPS - 65920 ( WEB ) Move java xml
Updating Alloy to f4bbdfc , 1 . 5 . 0
Removed Eclipse wrapper files from .
Commit the automatic trailing newline in JSch config file
Push version to 11250 .
Added @ SuppressWarnings ( ) to return by default
Fixed compile error
Update GLIBC 2 . 4 . X symbol
Don ' t distribute slf4j - app
Commit test to see if BJ notices CVS changes
Added test that cannot be used in case at the log4j
Add NetBeans files to .
Added documentation for instructions on setting up a BigBlueButton VM
Fixed the build of the root tag in the end of the one ( PY - 15823 ) .
Adding comment about lifecycle mapping in pom
Removed an unnecessary empty line at regression ( IDEADEV - 14205 addendum ) ( Chaoyu Tang via Ashutosh Chauhan )
Remove excess + from release notes
Ignore dependency - reduced - pom . Xml from .
Changed new property name
Added activiti - archetype - unittest to the deploy profile as well
Delete groovy - 2016 - 04 - 23 - 205955 .
Fix a typo in docs to fix # 57
Add Spring
Update to version 0 . 3 . 0
Upgrade gradle plugin to 2 . 3 . 0
Move test folder so it can be used by the same package .
LPS - 15720 Add terminated to bad column name
Adding a previously created test to git
Removed typo in comment ; fix # 164
Built the latest snapshot
Fix log in previous commit
Fixing the glyph for U + 3A34 in DroidSansFallbackFull . Ttf .
Remove newline at the end of xml file
Skip tests in compiling alluxio for hadoop
Adding h2o - x86 binary so it can be in the repository
Add README
Adds STORM - 934 to CHANGELOG . Md
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Bump pegasus to 1 . 10 . 6
Upgrade Mockito to 3 . 2 . 0
Ignore project . Properties
LPS - 63528 ( WEB ) Move icon files
Remove Travis
Update gradle to 2 . 1 . 2
Removing unnecessary test
Make spark . Response ' s body method public ( # 8 )
Set group and property in top level .
Removed debug code
Rename app submodule
LPS - 8865 Add @ Override
Bump common ref .
Fixed android backend . . .
Add support for Travis CI .
Upload 1 . 3 . 0 version .
Add extra . Properties to .
Make sure that its timestamp in the file
Updating number 20 version 2 . 0 . 2
Removed extra line at the end of the file
Add STORM - 2045 to CHANGELOG
Fix bug 43706 .
Update macosx bullet
Adding mavenLocal ( ) for local resolution
Add missing break .
Prepare for next development iteration
Add inspection check for CASSANDRA - 1256
Don ' t have " var " out " definition in com . Sun . 6 . MongoServerSelectionException class
GRAILS - 4440 fix Apple ' s L & F detection when running Jdk6 +
Add en - GB and tr to the list of supported languages
Fixed a bug in AuthenticatingConnection on checking for isClosed ( ) .
Fix failing test
Updating Alloy - rev . 57497
Don ' t clear wrapping in menu items
Adding lang3 jars
Fixed a bug with spaces in bbb - 10
Change # 9 properties
Don ' t keep the default specialized implementation for Git ' s layout
Revert " LPS - 46699 - CAS connection test results has the DTLS project 8 .
Fix failing test ( PY - 283 )
Updated copyright date
Add docs - all dependency for plugin .
Ignore local . Properties file ( # 4066 )
Restore accidentally removed Util . Shutdown ( ) .
Add STORM - 1661 to CHANGELOG . Md
Upgraded parent declaration in all trunks to use version 1 of parent - central .
Add getter for exceptionTranslator # 617
Removed tag roboguice - 2 . 0 - RC2b
Make new active error in CHANGES . Txt
LPS - 53578 don ' t save borders
Footer doesn ' t overwrite toString ( ) method from comments .
Delete outdated wiki repository .
Added new files to libRSSupport
Add reference to demo app
Update linux - arm native
Removed reference to 0 . 8 . 1 in the new sample
Updated CHANGES . Txt for CHANGELOG . Md
Add missing jars from pom . Xml
Fixed compile error ( PY - 7426 )
MAHOUT - 1775 FileNotFoundException caused by aborting the process of Mac OS X 10 . 6 . Org "
Can ' t access static field from nested closures
Changed version to 0 . 1 , since the 1 . 0 was just the default version in skeleton
Added STORM - 1473 to Changelog
Bump version for 0 . 9 . 3 release
Remove x bits from java files
Remove the unused dependency in core
Updated sqlcipher . Jar to 3 . 5 . 1
Updated README version
Add extra - google - m2repository in travis
Fix typo
LRQA - 12823 - Add test property to use Solr in Poshi
Add a proguard to distribution
Fixed broken merge bug
Added English ( UK ) , closes 2 . 5 . 0 ( CASSANDRA - 301 )
Add support for MC 1 . 7
Update version number for doc stamp
Push version to 12 . 0 - beta2 , 238 .
Remove unused image
Added platform - framework to .
Added the maven - smali - plugin and smali - integration - tests modules to the parent pom
Bump version number to 3 . 0 . 1
Added link to README
Add scala - pc
Fixed test data .
Bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6
Remove extra newline at the end of each test
Correct a test case in bbb - api
Use OkHttp 1 . 3 . 0 .
LPS - 53630 move icon
LPS - 58662 I assume order matters , so let ' s no " list
Added missing comment ( support info )
Updating Alloy to f8730a6 ; LPS - 30266
Remove unnecessary code
Added favicon . Ico
Copy the index of an white time out in shutdown ( PY - 15771 )
Remove unneeded license file
LPS - 64991 wsrp - portlet throws a NPE at startup , don ' t deploy it for now
Fix codenarc link
Removed unused import from AnimatorSet .
Source jars are missing sources for classes written in Groovy
Remove the empty file accidentally checked it with HADOOP - 7249 .
Update Android plugin to 2 . 1 . 2
Removed targetSDKVersion from AndroidManifest . Xml
Added Steve as a contributor
LPS - 66316 ( WEB ) Move css
Removed bbb - dsl . Java .
Revert " Update the gradle wrapper to root "
Remove dependency on groovy - api for now
Fix memory leak
Fixed bug in org . Parboiled . BulkWriteException to com . Mongodb . MongoException
Added openjdk6 to Travis configuration
Reverted accidental DataSourceStatus enum change
Set default autoJoin = true for now .
Added generic padding to the right state
Added options to avoid groovy tests in bbb - ui
Fix a wrong import .
Fixed typo in config file
Raise CircleCI test timeout
Improve constructor of layout ( PY - 4087 , PY - 4088 , PY - 4089 )
Modified url for issue tracking to directly show tickets for the component .
Update docs
Added the version of the branch to the up .
Update todo
Tidy up aopalliance dependency
Build new pre release b4
Update wrapper dependency to 21 . 1 . 0 .
Removed unused stacktrace from sample runner ( # 1039 )
Removed the empty line at the end of the file
Changed id to CLI friendly format .
Updated version
Added dependency to avoid ignored files .
Upgrade JUnit to 1 . 8 . 2
Remove obsolete import
Adding org . Android . Xml to true .
Fixed # 184
SONAR - 63925 Fix wrong dir
Removing useless import .
Revert " added intellij specific file to .
Changed default item to reflect random new property
Removed Dead requirements for VERSION . Txt
Set source encoding to UTF - 8
Update gradle version
Added missing readme to readme
Added new logo to v1 . 2 . 0
Made CommandLineOptions . State to MetaqMessageSessionFactoryBean . Java
Removed android - support - v4 . Jar .
LPS - 56621 I assume order matters ?
Updated Android plugin to 2 . 1 . 1
Bump the version in README .
Ignore files
Add STORM - 1079 to CHANGELOG . Md
Added Richard to the team - welcome aboard !
Updating to Gremlin 0 . 8
Bump to version 1 . 4 . 2
Make View # setBackgroundDrawable null
Add dummy test file
Added a property to avoid the exception stack trace when running the console
Updated copyright date in LICENSE .
Add application tag to AndroidManifest . Xml
Updated icon to give more non - size icon .
Revert " LPS - 50757 can we use the existing .
Moved AstBrowserProperties from src / main to src / resources .
Prepared version 1 . 8 . 0
Remove extra whitelisted branches .
Revert " git ignore fixes "
Added STORM - 132 to Changelog
Fixing the BND and jar packaging by manually overriding the exports
Added manifest from build . Xml
Added shell script for tic 574
Update applet jar with changes to minimize connect timeout
Bump common bit on sample
Fix copy & paste error in isKeyguardLocked ( )
Update freemarker to 2 . 2 . 0
Try a little more heap memory for tests in Bamboo
Removed a debug line in the body
Revert " Revert " Set " need " to 1 . 6 "
Fixed an issue with the init script at the same value .
Add test resource
Finished collection / list separation
Fix test data for docStub intention
Improved super . OnDestroyView ( ) to super . Close ( ) .
Fixed bug that meant test always hung until the y pane in the corresponding interface .
Remove the TODO
Upgraded parent declaration in all trunks to use version 1 of parent - central .
Added local . Properties to gitignore
Remove executable flag for source files
Fix a typo in bbb - index
Fixes a forked provided to UTF - 8 .
Added translation using Weblate ( Polish )
Bump version to 0 . 2 - rc - 1
Use the latest platform - tools on travis
Updated reference to ownCloud library
Update NEWS typo
LPS - 32038 Removed old jakarta - 2 . 0 . 0pr7 . Jar
Enable break statement
Try state change
Revert " Changed rule " so it wasn ' t being included in site "
Add null pointer to terms test display so it does not make
Upgraded parent version .
Fix a small test
Ignore emacs backup files
Remove @ Override from interface method
Temporarily also include eglTerminate - > eglInitialize hack for 8k
Add missing import to libclang diagnostic function
Updated CHANGES . Txt for beta . Properties
Fixed test data which was accidentally ignored by default
Fixed travis build tools version
Upgrade gecko to 1 . 1 . 2
Fix build .
Updated travis . Yml to run with Java6 as well
Updated library reference
Change the size of the media activity in the browser list .
Changed id to CLI friendly format .
Updated gradle version
Do not call attempts to null if it is not null .
Added note about default bug in bbb - conf
Updated documentation in README
Gh - 66 Fix plugins name
Simplifying the default welcome presentation
Ignore the .
Added a protected method to retrieve the indent printer for reuse in subclasses of MarkupBuilder
Fix issues with add testing change
Added list of CONTRIBUTORS file
Fix a typo in svm . Cpp
Removed @ Incubating from getProjectDirectory since this is not ignored
Ignore IntelliJ files
Added travis - ci
Permit cc - > objc again .
Update applet to fix some exceptions
Update the sample APK .
Remove comment
Fix bug in previous commit
Added app_konference - 10 . 04 - 32 .
Fix opacity on models .
Push version to 192 and 9 . 3
Use the Cache for ~ / .
Configured functional tests to run with forked jvm per - test , possibly hiding a memory leak problem with tests
Adding a few legend to the contributors file .
Mark offset gamma test as NOPASS , even though it ' s passing , as it affects other tests by updating the R GBM packge . "
Prevent @ SuppressWarnings ( " ) " javadoc " @ import )
Adding the background of the bottom of the init .
Add STORM - 1079 to CHANGELOG . Md
Remove an obsolete comment .
Fixed a bug in ControllerActivityCounter
Modify docker
Add toString ( ) to kotlin . Sh
Fixed test data .
Add simple version in pom
Try tests in travis CI with a revised timeout ( 30 mins this time )
Add ' client ' support to Manifest
Updated studio
Remove the TODO
Fix dep issues
Added upgrades . Txt to index of installation - deployment chapter
Updated location module to API 21 ( lollipop )
Allow the injected translation
Cleaning up test
Improve banner
Don ' t add bin dir to .
Update travis . Yml
Fixed an issue with spaces in unit test
Ignore files
Updated support library to 23
Added STORM - 1523 to Changlog
Added translation using Weblate ( Turkish )
Bump version to 1 . 5 . 0
Added grails - support .
Close the list of the gifs that will be done in the last commit .
Removed default run configuration ( # 57 )
Don ' t index unsaved files ( ie , no console )
LPS - 45869 Fix warning
LPS - 65920 ( WEB ) Move css files
Added translation using Weblate ( Icelandic )
Update to latest android gradle build tools 2 . 0 . 0
Prepare next development version .
Remove unnecessary semicolon
Update natives
Bump common ref .
Setting version to 1 . 0 . 111 - SNAPSHOT
Set getDiffableValue ( ) method even if it is no longer used , but we can ' s used before running by default
Add STORM - 625 to changelog
Updated proguard config to correct stacktraces ( OF - 65 )
We don ' t need this if there is not left in ' client ' keyword .
HIVE - 2608 didn ' t removed udtf_not_supported2 .
LPS - 62787 prep next , use latest
Push version to 15 . 0 . 1 , bumped to 3 . 0 . 1
Added jme3 - lwjgl3 / build / to the gitignore file . . . .
Turn ' t show K9mail - item buttons so we don ' t catch a warning around place .
Don ' t show sidebar bar for window ( PY - 5935 )
Added screenshots for installing ubuntu from v1 . 1
Add matplotlib
Copy the fields of LogHelper to be consistent with initialization order .
Upgrade maven - maven - plugin to 1 . 1 . 1 ( # 3397 )
Updated favicon
Remove duplicate dependency
LPS - 68937 ( SERVICE ) Move support xml
Added idea output directory to .
Added example entry
Add TODO for CMakeLists . Txt
Updated EnOcean lib to work with more EEP .
Delete unnecessary line in pom . Xml .
Updated version
Ignore maven target folder and eclipse project files ( .
Reverted version to 23 . 1 . 0 .
Fixed bug when trying to rotate image when auto it is not .
Bump socket . Io
Uses a single Thread per StunStack to expire StunServerTransactions in order to reduce the total number of utilized Threads .
Updated gradle plugin version
Accept " testIteratingWithList " test
Change minSdkVersion to 6 . Sh as we don ' t exist in AndroidManifest . Xml
LPS - 21453 Ignore auth token check for blogs trackback urls
Upgrade sonar - victims - plugin to 2 . 3
Added missing params in docs
Renamed quadTreeTest
Removing old JAR
Ignore IntelliJ IDEA files
Fixing the CS error of camel - > 2 . 2 . 0 compatibility
IDEA - 8733 - General build cleanup - hibernate - testing
Updating latest library to 3 . 0 . 1
Add missing padding to geometry3d
Updating Alloy to rev . 74817
Update to latest android gradle build tools 2 . 0 . 0
Remove junit dependency
Added a new function so that we have a new package
LPS - 50321 missing method
Remove unused files
Do not use CC if there is not used correctly
Added STORM - 1842 to changelog
Fixed test data
Added STORM - 1473 to Changelog
Add some TBD section for docs TOC .
Revert " Upgrade to version 2 . 1 . 2 "
LRQA - 12823 - Add test property to use Solr in Poshi
SONAR - 4923 Add missing @ Override method for @ whiteboard
Setting version to 1 . 0 . 104 - SNAPSHOT
Remove redundant dependecy on core - tests for windows
Update linux - ppc64 native
Removed extra newline at the end of the file
Include original head by the lib
Add analysis - icu module
Ignore grails - pugin - 0 . 0 . 3 .
Update favicon
Delete truth jar which was unintentionally added
Add maven plugin to build . Gradle
Make spark . Response ' s body
Upgraded netty to 4 . 0 . 6
Remove an unused blank line
Added image for instructions on setting up a BigBlueButton VM
Updating Alloy to rev . 74817
Added new screenshot
Camel shell commands adapter for Spring Boot Remote shell .
Update jars
Deleting @ SuppressWarnings ( " return " ) to method with intentional fallthrough
Adding windows builds of new native dlls
Update changes for 1 . 3 . 1
Remove unnecessary semicolon in StringUtils
SONAR - 5718 Fix infinite scrolling in FF
Changed order to be used by default
Removing old logo from sample project
Prepare next development version .
Update android natives
Added android . Back to grails . Jar .
Add STORM - 1079 to CHANGELOG . Md
Bump json version to 4 . 3 . 0
Fixed the changelog for 0 . 5 . 0 release
Updates the chat chat scaled NOPASS .
Updated drawable icon to be 1px tall .
Fixing cache on non - connections
Smack 4 . 1 . 0 - rc2
Add NetBeans files to .
Do not accept shell server , even if it ' s no longer used .
Add preview image
SONAR - 5718 Fix infinite scrolling ( ? )
Revert " @ javax . Java to check directory ( see # 36 )
Run " gradle test " instead of the default " gradle check " to speed up execution and because check fails
Add option for net
Added openjdk6 to Travis
GROOVY - 816 - import breaks example
Removing generic image
Fixed problem with exceptions which doesn ' t be scaled anyway
IDEA - 80966 Debugger " Resume " button - right next to the new ones .
Update changes . Txt
Removing appinfo . Jar
Set default encoding to null
Add device - topology .
Remove the empty file accidentally checked it with HADOOP - 7249 .
Turn off signing for sub - project
Add link to python runner
Added forgotten package file
Fixed sample . Sh typo
Removing an extra line .
Fix wrong artifact name
Added preview image
Removed old ejb 3 . 0 jar
Removing some documentation from source files
Setting version to 1 . 0 . 87
