Delete ic_launcher .
Updated FML
Ignore target , because that is generated code
Updating Alloy to fc7699d ; LPS - 32276
specify source encoding
Add stacktrace for travis .
Fix incorrect solaris / x86 native library
Change launchMode of Accounts activity
Delete demo2 . gif
Push version to 11244 .
fixing Junit dep scope to test
um , this was overwriting all other plugins .
Always invalidate TextView on checkForRelayout
Added STORM - 1272 to Changelog
Auto commit test 2
Reset build identifier to next milestone snapshot
Fix NPE when provider returns null cursor .
Make ideavim compatible with InteliiJ IDEA 10 . 0 . 2
Remove temporary test
Updated support libs to 23 . 3 . 0 .
Pull script for window
Remove empty line .
Fix checkstyle
Create README . md
Make sure .
update gradle
Fix checkstyle violation - extra import .
Fix single test
Add default constructor to Proguard rules
Rename method
update libwebp
Update build branches
update adbiFilters
Fix data driven testing example in documentation
Set source level to 1 . 7 for javadocAll if possible
LPS - 30240 Move IntraBandPortalCacheManagerTest from portal - service to portal - impl , because the dependence to MemoryPortalCacheManager
upgraded netty to 4 . 0 . 31
Prepare next development version .
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4
Create README . md
make pyunit NOPASS until hadoop namenodes created .
Adding an empty line to test the import script
updated jline
Add art assets
Added a gitignore
add NOTICE file
add conf / tachyon - env .
IDEA - 77239 Cannot checkout project from github
Thymeleaf support words
fix this $ 0 groovyc problem
Add finish ( ) after timeout of Reqeust Arc operations .
fix test data
Removed extraneous comments
fixed PY - 3637 test runner progress in django
Removed image , never used .
Move file to correct dir
Add versions to fbobjc .
don ' t include grails - core in POM
Changed defaults when creating new room .
Remove TBD from fields and properties section
added getCollection ( Class ) to interface
add free marker and junit in supplementaryLibs
Create README . md
Bump SpongeCommon reference .
HHH - 7578 Sybase does not support " unique not null "
added id to textview
remove useless println
rename class to match file
Help id corrected .
We don ' t need libopencore_author and libcutils in libmedia_jni
Updated Gains / Lift screenshots with new images from Nidhi
Thymeleaf support words
update changes . txt
fixed test message for lesson 2 task 5
Removed another version from the pom
don ' t return null network .
Don ' t show suggestions
Fix Copyright Year
adding influencer , influencers
bumped up gradle to 2 . 4
Updating samples
fixed clirr config
add source and target compatibility to 1 . 6
Upgrade os - maven - plugin to fix the build issue
Adding missing Notifications icon
Remove unused notification icons .
ignore local tmp dir
fixed version
add table of contents in python / README
The / green command should now only affect dirt on the top layer .
Added tests to index
Add missing piece to the build . gradle .
Add version back into compile notes
Appease the checkstyle overlords .
remove component ' s events when dealloc is called . "
Fix broken test name that prevents test from running .
removing bitdeli - badge
Create test
LPS - 64182 update jar
Updated reference to ownCloud library with reduced logs in operations in shares
Fix focus issues with dialpad in the call dialog .
fixing missing types in capture method
update es / usptream to include fetchSourceSubPhase change
switch off unsupported sparse extensions for our hg version ( 2 . 6 . 2 )
add STORM - 1503 to changelog
Fix check style
Upgrade maven - gpg to 1 . 4 .
Added the manual to the build .
Updated wrapper version .
Updated todo
Add permission model - - Adding a newline at the end of FsPermission . java
Updated Travis CI for newest dependencies
update emitter version
moving to latest release of jain sip
Normalize line endings
Remove redundant modifier
update snapshot branch
Removing accidentally added file
Move test to NOPASS
updated studio
Added STORM - 765 to Changelog
Add version back into compile notes
add function with zero arguments
Add eclipse plugin .
update cacheword to latest head
updated version
Fix RTL layout in Recent Apps , landscape mode
Do not use unreleased checkstyle rules
follow / unfollow API
Updated Vanilla dependency to 1 . 3 . 0 - SNAPSHOT .
do not lock files
optimize build release script
Fixing GLIBC 2 . 4 problem on Debian system .
add RippleBackground
Fix an example of Tree model JSON output
improve TextInput docs
avoid conflict with prev PR
add HBase testing directories to gitignore
remove test file
testing push mails
Revert " bump version for development "
Don ' t allow onBackPressed to be called while AstridActivity is finishing .
Correct a type annotation in w3c_indexeddb .
Ignore IntelliJ output directory .
update to latest android support libraries v23 . 2 . 1
Remove unused function arg
Updated version number to 0 . 23 . 0 - SNAPSHOT
Added javadoc
Updating changelog for 0 . 6 . 0 release .
Added new rounding methods to Float and Double that take a precision being the number of decimal places to round to ( update contributor info in pom )
Reverts removal of @ JsonIgnore on Event . type field
Add a new contributor
added the Gremreaper logo .
Switch the visibility of LazilyInitializedInfo . clone to protected since it ' s only used by JSDocInfo .
update to classworlds 1 . 1 - alpha - 1
Push version to 190 .
Revert " Enable OpenCORE on master - part 1 "
Update the alias in the server side trust store to match the name used for the certificate .
updated studio
Updated mockito to 1 . 8 . 0
Fix NPE on isValid for an expired session when activity check is enabled .
removed System . exit ( 0 ) from RunTests
Added person .
Add logging for unknown state .
remove language " fr "
Update Android build tools ( # 908 )
added scripts to create heron - tools self extracting binary
Fixed closing socket in debuger .
update sparc natives
Fixed asciidoc issue
Switch basic auth back on in web - secure
Rename Histogram to DHistogram in an effort to avoid a class name collision
Added curContext . blendFunc to fake - dom .
fixed test message for lesson 2 task 5
add and initialize README . md
updated version
Compiled w / jdk 1 . 4 . 2
LPS - 67383 Add package . json
Increment of invalid packets counter needs to be concurrent because it is used by both sender and receiver threads .
Added tag 1 . 0 - RC1 for changeset 4daa5ed3ef0e
updated version of jikes
ignore translator - web 1 . 0 . 2 prep next
added latest jar
changed the inner class to static
Updated ic_sysbar menu asset
Move the version to a separate file
ignore class files in root ( which are generated by " gradle test " )
Set bg and fg colour in site . css
Removing accidentally added file
remove underline on focused link
Bump the version number to 1 . 2 . 8 - dev
update gradle android tools
LPS - 55531 Move FileSystemStoreRootDirException to portal - service
bumped version
add bin / and gen / to ignore list
Expose FloatingActionsMenu . isExpanded ( ) state
add incorrect compounds
adding logo
The CI build no longer runs * all * compatiblity tests .
Prevents unnecessary exception from GA failure .
Upgrade version .
Fixed test
Removed a System . out
Ignore OSX and IDE files
Removing support library vector drawables as 23 . 1 doesn ' t support it yet
Fixed version in the notes
Delete help button from postfix completion configurable
Removing println from OperationMerge
Delete helloworld . meta
Vertical drag supported overriding clampViewPositionVertical method .
reset utterance counter upon stop ( )
default focused control is OK button
Make uploadMavenCentral task , that encompasses other tasks
Prepare version 23 - beta3 .
updated es module
added STORM - 1053 to Changelog
Bumped version
Disable one of the ` ExternalJavacIntegrationTest ` test cases .
ignore files
add provider properties action
Saving Blacklist and Hold for Moderation lists when dismissing dialog
Bump the version
prepare for next development iteration
save storage format version after successful cleanup
add getter for GenericVertex max index
Nexus S now reports the proper frame - rate
resize screenshot .
Set beta_features to True .
Add makefile
prepare for next development iteration
Solves script can now pick up env var JAVA_HOME
added intellij specific file to .
Removed last trace of Wildfire . . . . .
Deploy the upgrade info as an artifact .
change default markdown rendering to not use hard wrap
Reflect linux native binaries to latest changes .
Fixed VM memory leak in AudioSystem JNI interface
Regenerate portal - client .
Bumping project configuration requirement to Android 2 . 2
set version for release
Added explicit HystrixPlugins . reset ( ) to HystrixTimerThread init of each test
Added STORM - 1561 ot Changelog
prevent thread leaks due to deallocator prestarting threads
Added gitignore .
Prepare next release v1 . 0 . 2 - SNAPSHOT
Missing mavenCentral ( ) repository
Fix start - mac .
Remove build . sh debugging flag .
update linux - ppc64 native
Add 2 terms to spelling . txt
adding IDE related files to .
build linux / i386 against older glibc ( 2 . 3 . 4 ) for compatibility
do not lock files
Fixed the problem with maven publication .
Added STORM - 787 to changelog
added titan and captheorem image for documentation .
Missing CHANGES . txt for YARN - 2503 .
remove unused import
restored projectName property to support backwards compatibility with plugins etc .
Enlarge default size for the main window .
Ignoring TDB files .
Fix cqlsh DESCRIBE column order
Removed DS_Store files
IDEA - 126585 " Evaluate Code Fragment " dialog uses some strange proportional font in editor
don ' t compress jars
Remove the superfluous ProGuard rule for the database package
add overlay for cpp subproject
Fixing phpunit invocation
Removed debug logging added with r1061929 .
Bump the version to 2 . 0
documented changes so far
LPS - 47461 Add entry - action style
Updated doc for 1 . 8 . 0
Add Ken to the AUTHORS file .
adding branch in .
Adds ' More ' custom action icon for Android Wear devices
Make sure background drawables are correct when View is attached
start drag of text selection on initial press
setting version to 1 . 0 . 135 - SNAPSHOT
Removing wiki repo submodule
Bump readme version
Fixed bug in proguard . cfg
do not run tests in parallel
Update the ptbtokenizer test to reflect the non - americanization
removed extraneous whitespace from pull request
Fix broken build
changed image transparency
Move H2OApp into a package
MinecraftForge / FML @ 0b84b6aa297bdf6ab9f010e340f286442cb242dc Expose the state of the loader
Add Eclipse ' s bin / folder to .
Updating Alloy to 8cb02f9 ; LPS - 23021
Fixed a bug where the notifications could overlap when reset
Removed a System . out
Updating Alloy to ccc1dec ; LPS - 30040
Updated RecyclerView support lib to V22
setting version to 1 . 0 . 146
Updated TCK .
update w32 native
Remove redundant version number from application . properties ( grails plugin )
allow private constraints to be retrieved as a read only property
Added thirty minute per test time limit , to avoid stalled tests
update deskshare applet
Remove unused variable
Fixed a bug with the init script to make it work in IE .
Fixed a naming issue
Adding whack to messenger to allow for cleaner dom implementation of basic xmpp handling .
add lint abort to demo ' s gralde build script , ps for travis - ci
Add product flavor to reduce build time on debugging
install database - migration plugin by default
Using jetty - test - helper version 2 . 7 .
Should fix black laser beams .
added a missing def
If no security filter is added then display all resources
Replaced archive icon .
Updating Alloy to 8cb02f9 ; LPS - 23021
Upgraded wrapper
fixed tag state identification problem
Disable the JDK 6 and 7 builds on this branch - - no point loading up
Bump common ref .
don ' t index unsaved files ( ie , no context )
Added reference to distribution .
Added folder for the visualization project .
add Compression . NONE
update apk
Using 1 . 1 . 0 of gradle plugin
add more margin to bottom .
Added gitignore .
update ui
Add branch name " master " to version . properties
LPS - 66316 ( WEB ) Move css file
Added a download link to the not - so - obvious releases tab
Removed margin from ' add button ' .
Updated github page logo
don ' t tweak left margin for ssh button panel
Bump jxmpp to 0 . 5 . 0 - alpha7
Add ABS as dependency to library ( fix # 559 )
add STORM - 555 to changelog
Prepare library for release 2 . 1 . 4
Added gitignore .
Remove doc / shared again
Fix - - filter documentation
ignoring target directory created by running sample ha - ops bash scripts
Update shiped ForgeGradle for 1 . 7
Hiding DrawerLayout does not fire correct accessibility event .
fixing the name of the sort icon for hdpi
ignored dependency - reduced - pom .
add more contrast
Fix OSGI version
setting version to 1 . 0 . 128
missing import
missing import
Fix task leak in coordinator
add google classic style loadmore
update Bootstrap ' s entry in the NOTICE file
adding ommitted file
Fix log version string .
Set NODE_ENV and use node - env - inline plugin
Revert sound change ( # 63 )
Add logging of Bintray user for CI
Fix changelog by adding a new empty section
Implement PrestoConnection . getTransactionIsolation
upgraded some JAR files in the project
Add CHANGELOG . md
Adds travis - ci configuration
prepare release curator - x - zkclient - bridge - 3 . 0 . 0
Fix missing line after import codenarc
Add files via upload
Add a statically linked , 32 - bits x86 protoc ( v2 . 5 . 0 ) for Linux .
added few known transitive verbs .
Prepare next development version .
Fixed deserialization problem in DatePicker .
KT - 1036 JetFile - > PsiJavaFile cast problem - one more test for changed diagnostic behaviour
logging stuff 1 .
updated version
fixed asm jar version
add new subproject to pom file
Removed reference
Add sample preview
use 500 as max output lines on all platforms
replaced print with logging
Upgrade gradle plugin to 2 . 2 . 0
setting version to 1 . 0 . 77 - SNAPSHOT
added icon to reset magnification in desktop sharing
Updated default presentation for BigBlueButton 0 . 81
Added STORM - 1270 and STORM - 1274 to Changelog
Using the latest buildtools version here too
Smack 4 . 0 . 2 - SNAPSHOT
Updated graphdb libs
add image for listview and custom listitem
Adding more temp files to gitignore
setting version to 1 . 0 . 132 - SNAPSHOT
Change Sorbian ISO 639 - 2 from wen to hsb
Fix unbounded expansion of cumulative buffer in SslHandler
optimize to_maven script
Bump up RC version in curr . release
try new about format
Requires AUC in R in jenkins
shut up linter
experimenting the OSGi stuff , parent 7 - SNAPSHOT deployed on Nexus
Fix AppleBundle # getBuildSteps ( ) so it returns a non - null value .
removing appinfo . jar
alternately patched avro jar
fix ( driver ) make Find . Hint a static class
I don ' t really see a justification for doing a blocking write on close .
Add image for backstack visualization
setting version to 1 . 0 . 5
Declare orientdb - core dependency to be of jar type
Remove unnecessary spaces from docs / manual / dynamicform .
Fixed typo in .
add docs to keep up to date
Fix sync tests failure .
removed apk
don ' t compress jars
Bluez doesn ' t handle disconnect while connecting well .
fixed PY - 6543 Django manage . py commands not working
add YARN - 4367 to 2 . 8 . 0 .
Don ' t re - throw exception in onThrowable
Temporarily disables the MSN test suite so that we could have a new build .
The emojicon size was not consistently taking effect when it was set after the text was set .
Do not include svg - s in the default resource pack
optimize release builder
LPS - 12050 PortletClassLoaderUtil should release reference to PortletClassLoader after PortalClassLoaderServletContextListener context destory
Only run compile / unit tests in Travis
update macosx bullet natives
Added zero - arity body to comp function returning identity fn
fixed reference to ActorSerializer
Added zero - arity body to comp function returning identity fn
Built the latest snapshot
improved handling for Droid Incredible 2
LPS - 52093 moves icon
add reply . writeNoException ( ) for quick response
Prepare next release v0 . 90 . 2 - SNAPSHOT
Create zmnhnd . xml
LPS - 2900 - Firefox ( and other browsers ) will only show the scrollbar when needed
Add Lucene version in plugin . properties file
Use truth snapshot until truth > . 24 is released
Bump readme version
updated ehcache dependency to 1 . 1
Prepare next development stage
add image for transition drawable
Fix uninitialized variables in Caches . cpp
setting version to 1 . 0 . 126
Download built apk files here
touched changed log so Travis CI tries again .
Include a call to ` ulimit - a ` when building in Travis CI
Updated support section
Set self . camera to nil when stopping session
LPS - 67914 Do not commit private . lar
Added Artur to the contributor list
ordering tests
add execution permission to " input " script
Set node size to 10 in NodePencil .
JAL - 35 Add image notes to non - proprietary licenses
Updated irc - api library to rev . 194 .
Fix nit in pom . xml
catch Throwable on startup rather than Exception
Set isInEditMode ( ) to true # 9
Removed android - support - v4 . jar .
Ignore outstanding delayed shutdown on restart
bump deb version
LPS - 45983 Add a line break since one depends on the other
Add postgresql in the allow_failures block from travis config ( see # 382 )
Updating release version to 0 . 96 in build . properties
remove fiel
remove empty file
fixed travis build problem
Remove unused file
Deprecating ExternalResources .
upgraded junit
Add a redirect for / index . html on the site .
Don ' t build aggregated source jar .
Add ICU as a java library for docs .
Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode .
Bump version to 3 . 0 . 0 - beta . 1
Remove duplicated definition of alarm_active .
add 1 . 8 changelogs
Revert " Revert " LPS - 54998 SF "
add icon
Bump Idea compiler process heap to 1 . 5GB
Force ' marke all as read ' in the overflow menu .
setting version to 1 . 0 . 148 - SNAPSHOT
Updating gradle tools version
update video library to gstreamer - java 1 . 6 and jna 3 . 5 . 2
Fix the bug on Libsvm 3 . 14 that not free the memory allocated for sv_indices .
upgraded netty to 4 . 0 . 35
Adjust maven assembly so that the tarballs are not released to our artifactory on release .
add execution permission to " input " script
Fix error in variable name in README
add exec header . sh
updated AUTHORS . md to include Vingles
Add maven central repo to readme
LPS - 4808 - Migrating Browser Selectors / extensions to Alloy
Updated FAQ
ignore translator - web 1 . 0 . 0 prep next
prepare for next development iteration
updated example image .
Revert " Bump major version to 2 . 23 "
Delete obsolete icon
Add a libbase static depedency for aapt2 .
Added gitignore .
adding another exception test
Upgrade gradle plugin to 2 . 2 . 0
Ignore OSX and IDE files
Logs a couple of debug messages to warn about potential programming errors .
Missing mavenCentral ( ) repository
updated credits
Added lib dir in cassandra - 0 . 7
Push ci
Updated wrapper version .
Add maven central repo to readme
Remove " Set up library later " from dialog
ignore pom . xml . versionsBackup
FIX Dashboard always display a scroll in IE7 ( cherry picked from
Eradicate whitelisting
fixed key type .
Remove spurious @ Override .
add IRC notifications to travis
Built the latest snapshot
adressing review comment for # TACHYON - 1243
Fixed bug in dumper ( compile - server ) .
Git hygiene
prepare release acra - 4 . 5 . 0RC3
Updated hector link in README . txt to match Readme . markdown
fixed typo in config file .
Removing accidentally added file
fixed IDEA build configuration
improved logger
add cloud - azure module
add execution permission to " input " script
Added source folders
LPS - 10193 Cast group_ .
follow / unfollow API
Fix errors found by the new check .
Remove fflush from hdr_percentile_print .
Delete Thumbs . db
ignore intelliJ files
Make uploadMavenCentral task , that encompasses other tasks
Removed leftover name field
Give proper extension for markdown .
Fix typo in log message .
Added MANIFEST . in needed for building PyPI package .
build make buildlog include tests run and fail stacktraces
immediately update todo tree ( IDEADEV - 20186 )
Get me out the stupid readme file .
Add 222
update classpath for javadocing
Indicate temporary status of YouTrack in README .
Added Makefile for R .
Added " elastics " client for javascript
Add a README section for open items to remind me to check & test XML
Replace local copy of TimerMixin with module from npm .
Added STORM - 1408 to Changelog
Adding codecov support to travis
added favicon
add getRegion to PolygonSprite
Updated version in README
updated version in README
add API reference docs filtering for level 20
add a few more tests to pyunit smoke test list
Push version to 13 - beta6 , 11249 .
make full message view whitespace - aware so we can do cool ascii - art
Remove ' performanceTest ' entries from .
Create webapp / llap directory for MiniLlapCluster
save watches per configuration type - fixed tests
omitting rbx - 19mode from travis build for now , because hoe is acting up .
DO NOT MERGE ANYWHERE Update support library version to 24 . 1 . 0
setting version to 1 . 0 . 104
Flip EMERGENCY_ASSISTANCE_ENABLED to true
Fixed TextInput . blur ( )
upgraded json path to 2 . 0 . 0
Renamed rnc file .
include tests in package - plugin
Remove extra traling space
ignore configured dir
update coverage to jdk 9 compatible asm
temporarily set InconsistentArrays as a warning
Added STORM - 500 to Changelog .
ignore registry - api 1 . 0 . 1 prep next
Updated upgrading section
Remove post tag in circle file to attempt build fix
added TODO
Adding execution permission to the shell script files
Don ' t update TextureView ' s surface if the Layer doesn ' t exist
Prepare next release v0 . 87 . 2 - SNAPSHOT
Fix an example of Tree model JSON output
fixed wrong model name
update changes . txt
comment out snapshot plugin for release
SONAR - 3429 In rule descriptions , " < p > " should have vertical spacing
Update android build tools
mention 5950 in NEWS
removing assembly
Remove another unused method .
update to latest android build tools
Remove failed test to troubleshoot
add jdk8 to build matrix
Releasing OrientDB 2 . 1 - rc6
Reduce the amount of logging from the Javadoc plugin .
Ignore OSX and IDE files
Fix latest plugin version
Added Makefile for R .
Fixed import error
update to latest android gradle build tools 2 . 0 . 0
Upgrade ZkClient to 0 . 8
Added makeGLMModel call to python .
changed a typo from SHNAPSHOT to SNAPSHOT = )
update to latest support libraries v23 . 3 . 0
minimal json update version to 0 . 9 . 2
Revert " LPS - 66282 Increase app server startup timeout to 15 minutes to match ant "
Upgrade Support Library to 24 . 1 . 1
add osm module to parent pom
catch more exceptions during tearDown ( )
Fix fileHasAnnotations for Repo
remove spurious character
updated CHANGES . txt
Remove temporary file npm . tar . gz from Git
Add missing specialized implementation for Counted / count on StringSeq .
Ensure only a single scroller animation callback per frame .
update latin names
Update build tools to 21 . 0 . 2 .
Remove unneeded method .
Remove a debug line
Add lintOptions in build . gradle
upgraded to recent classworlds release
add 32 - bit linux version of launch4j
adding TODO for system overview diagram
Fix master build
forgotten jars
Fixed test
Removed README stub
Add text editor temporary files to .
Fix issue with state reset
modify mute / unmute buttons and icons
make sure we only sign when uploadArchives is run
Ignore patterns
Set isInEditMode ( ) to true # 9
Grails Controller tests generator modified
add heap dump on OOM , see # 304
Removed a redundant call to setDefaultButton
update libwebp
Remove outdated ( and wholly unnecessary in this case ) README for wordcount examples
Updating Alloy to 8cb02f9 ; LPS - 23021
Strict compile warnings
Use the main WorldEdit version for Sponge
Add self as contributor
replace the callback flow graph of FileDownloadListener , add the ' error ' method callback after occuring an exception in ' blockComplete '
Added akka application packaging cache to the ignored files .
fix the misleading model_key name
override canNavigateToSource for the future compatibility
add iris test file
Add debug to version name
Add sudo false to use container - based infrastructure .
updated my e - mail address
Fix double counting of written characters .
Fix uninitialized variables in Caches . cpp
Updated refs
set openpgp - api - lib to a version that actually works
Updated copyright .
LPS - 52760 forgot this
Ignore mac hidden files for ant auto - complete
Adds Gson and GsonConverter for Retrofit
Added Example apk
add weex . jks wee . txt
updating examples for rev 0099
LPS - 59594 Fix run format - source checks outside the portal
add favicon
LPS - 66860 prep next , use latest
Explicitly specify jspc version
Use new Alluxio logo
setting version to 1 . 0 . 115
LPS - 42723 Remove blank line
Should have child graphs .
add function graphic
Bumping commit of submodule
Run the tests in parallel .
added date stamp
Prepare next development version .
Fix flexible rails , Closes # 944
Add redis to .
Removed Thread . dumpStack ( ) calls used for debugging .
FileList implements IArrayLike < ! File >
gradle should output the stacktrace for test failures
prepare for next development iteration
build make buildlog include tests run and fail stacktraces
add function with zero arguments
Revert " travis build check "
Ignore editor backup files
unbreak accessiblewebview
ignore " bin " directory ( created by Eclipse )
Added STORM - 1190 to Changelog
add execution permission to " input " script
include outbound socket exceptions at debug level
Improve environments .
Added copyright year entry to configuration file
Added lintVitalRelease as suggested by @ DimaKoz
prepare release checkstyle - 7 . 1 . 2
Adds Retrofit library
LPS - 68970 rename file
Add feilaoda as contributor
ignore target
Add a 192x192 xxxhdpi icon ( scaled down from 512x512 )
Don ' t upload codecov results if jacoco wasn ' t run , as it generates an email warning now
ignore idea files
extended help files for WebSockets
LPS - 27200 Jetty needs JNDI
update version of build tools
Use the new Android 2 . 0 - style SDK value for this field so it compiles
Updating Alloy to 8cb02f9 ; LPS - 23021
Ignore editor backup files
add new module to platformImplementationModules
Removed old Javadocs .
Build scripts moved packaging
LPS - 27654 - Adding Translation in Web Content in Control Panel on IE8 Breaks
Add sample apk
Started new demo .
Releasing v8 . 0 . 5
fixed typo in comment
Fix reboot loop due to NPE .
Adding IntelliJ files to ignore
Get me out the stupid readme file .
do not run tests in parallel
use minSdk 11 for Sample
Add updated ffmpeg JNI library for Linux 32 - bit and 64 - bit .
Upgraded slf4j - api from 1 . 6 . 1 to 1 . 7 . 2
add image for listview and custom listitem
MinecraftForge / FML @ 0b84b6aa297bdf6ab9f010e340f286442cb242dc Expose the state of the loader
comment out snapshot plugin for release
Set default encoding to UTF - 8 ( fixes # 192 )
Fix descriptor leak after accepting connections
Made empty constructor for ModMetadata public
Remove unused icon .
Fixed isDrawing .
Changed Target SDK to 21 ( Lollipop )
Restored formatting interfaces to provide same functionality as v0 . 95 .
Fix ref to lucene . apache . org
set IDEA JDK from build script
prepare release checkstyle - 6 . 13
Don ' t run performance tests in parallel .
Adding myself to Travis notifications
LPS - 33648 - Remove the constraining width from AutoComplete suggestions popup
Drop unused widget preview images .
update applet zip
Added an object file and a elf file to the test data
Remove unused file .
Build ' client ' target with - Wno - sign - compare .
FileList implements IArrayLike < ! File >
LPS - 57173 Wake all thread waiting on the manager
help ID ( PY - 4107 )
LPS - 61001 Move java file
Updates smack jar files to the version which contains all patches from libsrc repo .
Build tarball only
Require Maven 3 . 0 . 5 to stop users from using insecure 3 . 0 . 4
Include message history in stacktraces from error handler , making it easier to know where the problem was .
fire file statuses changed event after adding ignored files ( IDEADEV - 16670 )
Modify changelog
Remove extra empty lines
Remove LOAD_OS_APP message from standard context hub messages
add constant for rstudio user identity display
wake - up sleeping reader when stop is called
optimize p . redraw ( )
Added IDEA files to the .
Add intellj project files to .
Skip auth setup if AllowAllAuthenticator is used
Fixed a subtle bug I happened to introduce last night .
remove patch verb , not supported by HttpUrlConnection
Remove text capitalization in widget titles , closes # 1498
fix the build
Updating copyright on about . jpg to run to 2008
fixing line endings for .
updated CHANGES . txt for Breton .
Adds * .
Ignore target directories
Fix wrong file name
fixing a memory leak when creating a new node and not adding it to the tree .
Ignore VIM swp files .
add jcenter to repositories to get actionbarsherlock . aar
Use Android Gradle Plug - in v2 . 2 . 0 - alpha6
Bump SpongeCommon reference .
Fixing an issue with that damn bundle plugin again .
when building the simulator on linux , link ( only ) with libdl , as opposed to also making libdl a build target .
Updates the global shortcut library for Mac OS X with a version compiled on 10 . 6
prepare for next development iteration
Fixed IndexOutOfBoundsException in EpisodesFragment
Fixed colspan .
Make Bazel compile ( a previous change added a graph - > jsr305 dependency that was not reflected in the BUILD file )
Upgrade gradle
Fix NPE on isValid for an expired session when activity check is enabled .
updated sbt idea plugin to 1 . 5 . 2
Add oraclejdk8 for travis
Fix potential NPE in WebView
added new config files to gitignore
upload demo gifs
Remove reference to querydsl - root
LPS - 10836 remove local address after do local method for Unitcast situation
Remove unused file
Starting a new 1 . 0 Release
Push version to 13 . 1 , 11256 .
temporary reverted changes in javac2
+ x for wait_for_emulator
Fixing transitive - ness of provided
prepare release acra - 4 . 3 . 1
Ignore IDEA project / workspace files
save watches per configuration type - fixed tests
Remove ntlm module from pom
cleaning up 1 . 8 . 6 warnings
LPS - 43729 - Blogs subscribe links not contained in portlet container
Updated CHANGELOG . txt .
add info about " Android - AppMsg - Gradle - Sample " in README . md
ignore bin directory
Use Gradle Android 0 . 6 .
Add missing test resource ( # 2 )
ignore top level dsl - support dir
Updated refs
update osx / darwin native
Update gradle build tools
Added STORM - 1168 to Changelog
Removed an accidental line break to retain the standard code formatting .
LPS - 65017 Move resource - actions
Changed break extension to have 2 buttons for breaking on request and / or response
LPS - 57004 Batch tests should print gc logs
Refactored quartz plugin .
setting version to 1 . 0 . 141 - SNAPSHOT
update cacheword to latest head ( notification fixes )
Only clear the caret when in caret selection mode .
Adds device uid for wmme and dsound devices .
Fix check box alignments
make images shorter
Adds smackx - debug to our smacklib to make debugging easier when necessary
Fixing the build .
Upgrade netflixoss Nebula plugin to 3 . 2 . 2
Refactored item_avenger to item_character
Make Tachyon - Perf a subproject of Tachyon
inherit meta from parent dir
Don ' t automatically show the batch buttons when entering multiselect mode
Make text in table wrappable
delete old file
Fix focus issues with dialpad in the call dialog .
LPS - 51081 Move stuff out
Allows use of IPv6 addresses without brackets ( Resolves
Recommend jcenter repo .
Bump SpongeCommon reference .
moved wait_for_emulator to android examples
update CHANGES
Also release Android sources to npm
add execution permission to " input " script
Commented the missing function viewUpdate ( ) and added a navigator . notification . alert ( " Ready " ) ;
Updating Alloy to 813ca0d ; LPS - 26904
added mcumings to contributor
ignore files
Bump " demo " to 1 . 1
explicitly declaring the Locale of JavaDoc task as en_US
Updated libs .
Updating Tomcat ' s copy of BCEL as far as r1748500 ( more to come )
Added gitignore .
Fix release notes .
Add missing villager sounds .
Updating the script to build with
LPS - 55100 Ignore lib for versions . xml
Add COCOA_TREE to list of possible tree types .
Push build .
bumped version from 0 . 3 - SNAPSHOT to 0 . 4 - SNAPSHOT
upload demo gifs
Bump SpongeCommon reference .
update es / usptream to include fetchSourceSubPhase change
LRQA - 27231 prep next , use latest
Changing the MSI installers banner
Disable Example until new plugins are pushed
add getCount method to BytesInputStream ( @ MysteryMachine )
optimize p . redraw ( )
fixed test message for lesson 2 task 5
Add isClosed in DruidDataSource
bumped parent version from 2 - SNAPSHOT to 2
LPS - 64744 don ' t make this a a subrepo
Add appcompat v7 support library .
Add missing LOCAL_MIN_SDK_VERSION for Support Library demos
Removed a System . out
cm changes broke this
Bumped version to 1 . 5 . 0 .
Delete default README
Updated reference to ownCloud library with reduced logs in operations in shares
Updating Alloy to 813ca0d ; LPS - 26904
Updated copyright .
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Use the Cache for ~ / .
MinecraftForge / FML @ 0b84b6aa297bdf6ab9f010e340f286442cb242dc Expose the state of the loader
include tests in package - plugin
missing test for KT - 451 incorrect character liternals assertion error
Add sources . jar as part of the build artifacts .
don ' t build consoleio on win64
LPS - 40933 Puts device preview on top of dockbar and other elements
use latest build gradle tools version
updated Studio
Ignore folder that contains h2o . jar in the R package .
updating version to 1 . 0 . 1
Make APNS . java final
Deleted some unused resources
Added comment .
added new configChang handling for certdisplay
set IDEA JDK from build script
Don ' t reset the JVM for manual tests .
LPS - 36595 Do not display Manage Site Membership in Control Panel when the Site membership policy doesn ' t allow manual membership
Add the Servlet 3 . 0 xsd ' s
add scenario name to test stub
add STORM - 790 to changelog
remove repeat annotation
Reset languageMode to languageIn at the beginning of processNewScript ( )
Fixed classpath reference in buildscript dependencies
ignore chat - web 1 . 0 . 0 prep next
Corrected Javadoc on MapReduceOutput
restore forkEvery = 1 . . . still troubleshooting build issues
Invalidate structure when adapter is changed
do not return invalid files
Added a line , just to see if DC manages to monitor changes again and build groovy as it was the case before the move . . .
LPS - 53413 Set 20 plugin groups
update multiwords . txt
Always invalidate TextView on checkForRelayout
Removed unnecessary import .
undo previous trivial change , still testing svn
French tagger now calls dontTagLowercaseWithUppercase ( ) .
Remove fflush from hdr_percentile_print .
updated hbase jar
Prepare version 20 . 1 . 0 - beta1 .
Removed unused incompilable input file
Use latest release plugin .
replace the openjdk6 to oraclejdk8
moved runit to NOPASS .
FredrichO - fixed spacing on the bottom of the number of columns in the media gallery settings layout .
Added nmsblock classes for MCPC 1 . 6 . x .
Reverted build tools version to fix CircleCI
LPS - 8736 - Allow configuration popup styling to be targeted specifically
Fix leak of stackTrace in java / lang / Throwable .
Fix build .
fixed IDEA build configuration
update sbt 0 . 13 . 11 - > 0 . 13 . 12
Added log and release to cvsignore
Sample fixes .
cleared cache in travis
Return the record state locked
updating the version number
Create Jar artifact with test code
Ignore IDEA ' s ` .
added id to textview
Updated version before the release
Setting release version to 4 . 0 . 0 .
Increase CircleCI timeout to 30 min
Adding Read icon , updating Dashboard / Reload icons
Publish ` gradle - process - services ` module
Move Benchmark release to 1 . 3
exclude groovy - all - tests jar during assembly
Add configuration changes to Notification Settings
Build fix ( take 2 )
update morfologik - stemming to 1 . 5 . 3
upgrade randomized testing to 2 . 0 . 12
Add ` repositories { mavenCentral ( ) } ` to Gradle instructions for completeness
PY - 1065 Reformat and auto - import do not respect space - after - comma preference in multiline imports
add offset
modify mute / unmute buttons and icons
Delete unused strings resource file
Fix doc link for optimize documentation
updated version
Remove trailing line
Modified url for issue tracking to directly show tickets for the component .
Moving PCA golden test to NOPASS until I figure out the source of the numerical inaccuracies .
Added failing test for JSON output
Remove unused file .
LPS - 61001 add image_uploader to build process
add words
The / green command should now only affect dirt on the top layer .
Added translation using Weblate ( Azerbaijani )
Fix back popping the back stack too much .
Handle logging levels via log4j . xml
Set LOCAL_MIN_SDK_VERSION .
prepare release 0 . 17 . 2
update Android - Iconics to v1 . 0 . 1
Add org . sonarqube .
LPS - 37519 hide only control panel link icons
Add ignores for idea and eclipse project settings
add " perflib " from tools - base module to build
moving logo to wiki
described changes to French Grammar rules in CHANGES . txt
Added Changelog
Add issue template .
Modify install_mongodb .
ignore files
Fixed a minor typo at the top ( Cloudera CHD3 - > Cloudera CDH3 )
Changed a + = of a null string back to the appropriate = sign .
Updated README for 0 . 6 . 7 . 2
update buildToolsVersion
Added junit version .
prepare for next development iteration
added few known transitive verbs .
Update build branches
Fixed typo
Added missing graph . shutdown ( ) to newly added test case
Add flags needed to switch Jack to 1 . 8 for CTS targets
LPS - 42308 Set visible does not always work in Liferay Pagination
Zeppelin Server doesn ' t catch all exceptions when launching interpreter . sh
update win32 native
delete old jar
Add screenshots
update w32 jar and universal jar ( defer toolkit load )
simplify code
added linux binary
LPS - 52826 sdk missing gradle wrapper
added known aliast for monostate pattern
change the default release scope to be patch
Fix mCoveredFadeColor setter
Upgrade wrapper to 2 . 10
need store refresh status thread to be daemon
LPS - 15720 Add terminated to bad column names list
prepare for next development iteration
Remove sorting on post formats to fix # 284 .
Create README . md
Set isInEditMode ( ) to true # 9
Push version to 14 . 0 . 2 , 11265 .
update applet zip
if null , check version .
Remove unused file .
Make every language have its own preview page by default ( no need to specify useSharedPreview ( ) for each )
changes the incoming message alert to a less intrusive sound
Remove ES Client . close ( ) .
Get me out the stupid readme file .
add function with zero arguments
Ignore list created
Turn debug on for test diagnosis
LPS - 18560 Source formatting missed the break
I had named these with RF instead of matching all the existing * _rf_ * .
update native win32 - x86
Added files via upload
Added get point method to Line3D . java
rename README . txt to README . md
Updated changelog for 0 . 8 . 3
add execution permission to " input " script
Create README . md
update demo
Make ViewHolder less visible , static .
remove silly throws decl
Updated reference for 1 . 0 . 8
adding word " LibreOffice "
added deprecated annotation to deprecated methods .
Add moon point
LPS - 27654 - Adding Translation in Web Content in Control Panel on IE8 Breaks
Fix issues with app crash
Take fake bold font property into account .
Make log4j an optional dependency
Adding myself to Travis notifications
setting version to 1 . 0 . 9 - SNAPSHOT
Updated the sample APK
Skip a test that does not apply to JRuby .
push new builder top on texture
Completely reverted change on log4j dependency .
Testing visiblity of a commit message
Add Eclipse files to .
Include message history in stacktraces from error handler , making it easier to know where the problem was .
Fixed TextInput . blur ( )
Added log and release to cvsignore
Added serialVersionUID to MongoInterruptedException
starting 0 . 6 . 1 - SNAPSHOT
Add Readme file
Ignore temp files
Updated travis
avoid fallthrough in ONMOUSEDOWN
Fix AppleBundle # getBuildSteps ( ) so it returns a non - null value .
Fix BufferedTokenStream . reset ( ) putting the stream in an invalid state when called before lazyInit
Make argument of NullType constructor nullable
Add source encoding to the maven compiler plugin .
fixed typo in travis . yml
update to latest android gradle build tools 2 . 0 . 0
updated version
add function with zero arguments
Disable JS tests when enabling the profile dbTests
Fix missing return value in android_location_GpsLocationProvider_init
Reduce the amount of logging from the Javadoc plugin .
change wl12xx hotspot ssid to spike
updated CHANGES
Fix nullptr exception .
add incorrect compounds
LPS - 66848 Add missing Gitignore
Have the comparison script handle app failure gracefully
Upgrade gradle
Added STORM - 848 to changelog
Remove a spurious symlink
Upgrade netty - build to 12
update to latest android gradle build tools 2 . 0 . 0
Update travis config
set IDEA JDK from build script
Removed un - used p . paused ( ) .
added intellij specific file to .
updating history
Remove newline in TicTacToe example
help ID ( PY - 4110 )
add date
Changed packaging to jar since there are problems with bundle ( classes being in other
Add ' Server ' keyword to title
knock version back to 1 . 6
build script fix
delete test file
Have a bottom actionbar in the Search activity to be consistent .
Log type of unexpected quorum packet in observer loop
update sample app
Add Foundation import to the native IntegralToString header .
Fixed accidentely removed call to " java " from bin / robovm .
updated studio
Fix changelog by adding a new empty section
Fixing small memory leak when evaluating xpath queries .
Missing key
update linux amd64 natives
Updated gitignore ?
Make notest .
Updated the OrangeExtensins . jar library ( compiled with java 1 . 5 ) .
Removed unnecessary return statement
add codestyle jar file
updated change branch image
Make method private
LPS - 54970 removed unnecessary return
Updated notification icon for Android 2 .
force foreground of execution line to be white
Updated change list
Updating Alloy to 2 . 0 . x ad77288
Upgrade Ant to 1 . 9 . 6
Make convertToTranslucent a public method in Activity
Remove unused assignment .
use applet compatible with java 1 . 5
Added Google to license .
Add a repository block to library only section . . .
Downgrade jdk version .
rename jsoup
upgraded http client to 4 . 5 . 2
bump deb version
Fix build due to added API
Add image for gravity
Added translation using Weblate ( Polish )
SEMVER update ant . bnd
remove extra unneeded elements
Reverted build tools version to fix CircleCI
Rename migration to avoid timestamp conflict
Fix extra text appearing after ellipsis
Don ' t wrap inline code blocks .
LPS - 54811 Export the proper datasource in order to get the proper transaction management within the new OSGi modules
Set oss parent to 9
Add relative link to contributing file .
Fix indirect misuse of $ ( my - dir ) .
Bump common ref
LPS - 46809 Add a line break since we ' re about to manipulate the var
updated the screenshot
Fix # 205
mention 5950 in NEWS
Removed unused file
increased text size
add sample apk
Added STORM - 1074 to the CHANGELOG .
moving RestSpecAndBasicUnitTest to test / unit / voldemort / server / rest
wipe change notes from plugin . xml
Add 0 . 138 release notes
Updated reference to ownCloud library with reduced logs in operations in shares
Appease the checkstyle overlords .
added helper method for builder implementations
Remove AppState from Known Issues page
Added " elastics " client for javascript
Have RCTBridge . loading return RCTBatchedBridge . loading
cat health api didn ' t disable headers
Fixed Travis
Upgrade jsr305 2 . 0 . 3 to 3 . 0 . 0
Updating Alloy to 2 . 0 . x - deprecated 5a22471
Updating build tools to 23 . 0 . 1
HHH - 7578 Sybase does not support " unique not null "
Added intellij generated files
Don ' t run performance tests in parallel .
Reduce default stack size for CASSANDRA - 1256
Updating junit version to 4 . 11 - using FixMethodOrder for method ordering
Aligned pom . xml with the other components .
Adds settings icon
Updates the merge calls button .
Eradicate whitelisting
Add case for Decimal128 to BsonBinaryReader # skipValue
Fix isUsbMassStorageConnected ( ) will always return true
Upgrading the Guava version
updated to tz version 2006d
Adding hero image .
LPS - 8084 - Adding certain characters to live search throws javascript error
Delete README
Marking 9 . 3 . 8 as clirr comparison
LPS - 52032 released 1 . 0 . 2 , so prep for 1 . 0 . 3 snapshot
add jcenter to repositories to get actionbarsherlock . aar
Fix double checked locking concurrency issue .
Make argument of NullType constructor nullable
Updated travis
Ignore target directory
Updated Slovak translation
Updating Alloy to 8cb02f9 ; LPS - 23021
LPS - 25788 top links are broken in IE7
update travis to the new build tools
updating banner images
Add demo gif
setting version to 1 . 0 . 12
Added STORM - 1279 to Changelog
Added STORM - 449 to Changelog
replace Future < T > with T in EJB implementation
Changed components to use parent pom v 4 , producing source and javadoc jar packages .
Added STORM - 1104 to Changelog
added idea ignore config
adding OSSMETADATA for NetflixOSS tracking
updated label to 0 . 81 - beta - 2
Updates build tools and compile version
Fixed a bug where the notifications could overlap when reset
allow testing element icons ( author section removed )
Add DroidSansArmenian font file
Added onSequenceStep ( ) ( # 103 )
Added Sprint 2 comps
Bump up revision number .
Changed name for me
Added screenshot
Only CI build the master branch
Only build the master branch with Travis .
don ' t index unsaved files ( ie , no context )
Ignore IntelliJ IDEA files
Add ESC mapping for Pixel C keyboard
Cleaning unused files .
update buildnumber - maven - plugin to 1 . 3
add missing test
Requires AUC in R in jenkins
reset version for development
added tmp to ignored dirs
add overlay for cpp subproject
Remove unnecessary code from the test
rename UsersController # delete to destroy # NO_ISSUE
Ignore Sublime Project Files
Add images for the lifcycle of a controller context
Don ' t trace debugger internals in Python 3 .
rename unit - tests execution to default - test
ignore * ~ from hg
updated animated gif
remove todo
Set OTR session in ChatView . onBind .
Modify changelog
Fix - Add travis - ci support
Remove semicolon
Bump readme version
Add clover license
Fix copy & paste error in isKeyguardLocked ( )
Upgrade JUnit to 4 . 12
update es / usptream to include fetchSourceSubPhase change
Removed unneeded ant call in build ( )
set version for release
Removed number to avoid problems
Adjusted the logout icon for better fit in button
Bumping commit of submodule
Remove vim command
Reverts revision 83 because it causes receive streams to stop ticking .
add STORM - 1848 to changelog
Fix typo .
Fixed a layout issue with the empty view in list comments
fix the build
add devtools api
update com . android . tools . build to 0 . 4 .
Have the final setVisibility cause a requestLayout .
add jamm - 0 . 2 . 5 .
Add battery capacity property
update Bootstrap ' s entry in the NOTICE file
Completely reverted change on log4j dependency .
Move Recents task to back when hiding view .
setting version to 1 . 0 . 11 - SNAPSHOT
Push version to 234 .
Instruction3rmi should use Format3rmi , not Format3rms
add jamm - 0 . 2 . 5 .
updated codegen dependency
update bundled JRE to 6u39 , refs OF - 612
update build . gradle
update TODO
Add mongodb service for travis config
Remove fixed pipeline technique from lighting shader
add # 3794 to NEWS
Websockets now need this method .
Increasing uninterrupted sleep quantum in SQLiteDatabase to increase transaction size .
add globus
Use new lib
Speed up Travis by running on non - sudo containers
Speed up consistent hash ring
Moving third - party STUN implementation from Openfire main project to plugin .
Removed a redundant call to setDefaultButton
Add demo . gif
Fix trivial equals implementation
Fix JavaDoc .
LPS - 34188 Add missing list close tag in the export layouts form
Added " elastics " client for javascript
Updated GBM and GLM booklets on github
setting version to 1 . 0 . 113
Made CuboidRegion ( world , . . . ) constructor clamp to world .
added constructor that takes the parent class loader
Added files via upload
fixed javadoc for zipalign path getter
HIVE - 2550 Provide jira_base_url for improved arc commit workflow
corrected a typo from @ Maxwell1987
Added STORM - 849 to Changelog
updated studio
Replace registerForEvent ( ) with equivalent call that makes registerForEvent ( ) unused .
modified a bit of test data
Shrink notification area to contents
Fix an example of Tree model JSON output
Remove support library from the StackBlur library
remove overridden function implementation .
Fix Java unmappable character warning on Windows .
added faunus diagram .
added titan + rexster image
updated plan to remove existing functionality
Fix the fix in r1530423
Try a different travis config
Deprecated com . mongodb . MongoServerSelectionException class
added missing sigar libraries
Updated FAQ
LPS - 54165 your changes reminded me of a bug that the SN migration team added
Add project default gradle . properties , to avoid build failures from missing properties
fixed the busy sound as it was rendering quite poorly with portaudio
Added description to project
Reactivated the rxjava - core tests
changed versioncode number
Add a a trailing comma .
Log exception if it prevented to start the Git process
removed OBE comment
add STORM - 1848 to changelog
Add image for hierarchy viewer
Fix a ViewPager bug repopulating after a data set change that removed
fix conflicting native library error message
handle empty preview appearance correctly .
Accessibility events fired from AdapterView underpopulated .
Add missing method
Increased version
Try and handle " death on startup " a bit cleaner
Added idea output directory to .
LRQA - 24374 Add a new ' portal . release ' property to mark all portal tests to be ran in the release job
Included string . h to use memset in stress . cpp
fixed test message for lesson 2 task 5
Delete truth jar which I forgot to delete when removing Ant support .
FIX application zip should contain a top level dir
Remove redundant fileTree dependency
Delete duplicate application . properties
Updated Changelog for STORM - 315
Added support for using a transaction to perform batch tasks .
Set mSeekNotificationSent as false for RTSP seeking .
Reload results immediately after the sort has changed
Excel import sometimes drops last row of data .
Added link to contribute page
Prepare for next dev iteration
Remove test I opted to host elsewhere
Added ` Groovy ` solutions for chapter 5
add execution permission to " input " script
update idea version
Added OC Jelly Bean workaround app as a visible module in the project
Fix data driven testing example in documentation
Fix Preview initialization .
remove key lookup for account screen ( not a good place )
Smack 4 . 1 . 3 - SNAPSHOT
Add NEAR QueryOperator
updated version to 3 . 0 . 0 for pending release
set transparency 20 %
rename IntelliLang configurable to " Language Injection "
Increased max number of items rendered from 3 to 5 .
Suspend must freeze the time
Updated reference to ownCloud library with reduced logs in operations in shares
cm changes broke this
fixed compilation error
add Alireza as contributor
Removed PMetadata from opengl
adding words suggested by users
Add flow directive to index . android . js
Reverted pom to r2 since our build server can ' t handle r3
add support for chunk setup options in data chunks
ignore build . xml , its generated by .
Fix build
Updated Changelog for STORM - 315
Added checkstyle to core and cache module
upgraded guava to 14 . 0
Ignore Jetbrains IDEA files in git
Added STORM - 1418 to Changelog
Prepare next version ( 0 . 3 )
reset current scheme panel after import if current scheme was updated
Add build status icon
Added support for using a transaction to perform batch tasks .
added few known transitive verbs .
Hopefully fix the build .
Added debug printing content of all incoming packets
Deploying more artifacts .
Download apk directly from here
include tests in package - plugin
Delete build . gradle
Check for APK tamper in HomeActivity . onResume ( ) , fix # 309
Fix build due to added API
Add image for action bar action items
Upgrade AudioPlayer to v1 . 0 . 8
add directoryMappingChanged ( ) callback
replace non - portable use of echo - n with printf
Fix exception in wrapped documents
Use 0 . 6 of the gradle plugin .
Delete obsolete import
finished collection / list separation
Added security dependency on webapp . mod
add execution permission to " input " script
Fix missing break in Icon class
Added NOTICE file
Add Clover instrumentation .
fixed a small bug
Committed new mountains . zip file
Updated version in docs to use 1 . 5 . 0
Remove vim command
Bump readme version
Readded clean goal for coveralls as it seems to be required by the official doc .
Add isClosed in DruidDataSource
update apk
Do not process grammars following an error during parsing ( fixes # 507 )
Allow access to the type " ComponentVillage "
Always call handleException rather than cb
remove freemarker . jar and junit . jar
Fixed bullet points in README
Fix type warnings
missing import
Fix checkstyle issues
Removed tag roboguice - 1 . 1 . 1
add spreay dependency to core subproject
add STORM - 1499 to CHANGELOG . md
setting version to 1 . 0 . 6
update aerosolve version
Added STORM - 1396 to Changelog
Added STORM - 1127 to Changelog
Fixed data type in setStreamVersion
Added the mysql connector jar to .
Updating release version to 0 . 96 in build . properties
Prevent receiver leak in TrustAgentWrapper
Fix Preview initialization .
update aboutlibraries
added keystore to gitignore
Nexus S now reports the proper frame - rate
Add Mike to the AUTHORS file .
adding android - framework . jar fixes # 34
add badge
update wiki - snapshot
Push version to 12 - beta2 , 210 .
Ignore docs . tar in GIT
Add Eclipse specific project files to ignore .
Add definition file for Travis CI
Removing TimeUnit from api and replace with Duration
renamed class to fix capitalization issue
Added test for
Fixed case of SideBitFlag
pass env ' s CFLAGS through to sub - builds
update screenshot
bumped development version
added gradle buildfile to create downloadable artifacts , and push them out to neo4j . org
Fixing the build .
missing changelog description
Updated Studio with last version
updating history .
Changed dependencies to milestone versions in preparation of tagging
upgraded guava to 17 . 0
Fix typo in beans { } example
Added Commander / SourceSafe to the list of checked plugins
Update the version to . 96
reduce logging , use ' quiet '
Removed JDK7 and OpenJDK
add wget to yum dependencies
update CHANGES
Set project version to 6 . 1 for release .
Push version to 12 . 4 , 244 .
Adding maxmemory setting for javadoc generation
Fixes default config settings .
Added Travis
Only show warnings and errors from maven - javadoc - plugin
ignore mac finder droppings
Prepare next dev iteration
debug dor darcula nad retina
Fixed camel - test dependency scope .
Update build tools .
Renamed README . txt to README . md
Updated unit test for CacheConfig class .
include ' < cxxabi . h > ' ( needed for non - OS X platforms )
Fix test that was not cleaning meta class registry after test
Fixed test for changes to ' model ' report output .
Add comment .
Improved CSS to only add space for breadcrumbs below the * first * title on each page .
prepared for next development iteration
add progress cycle
Remove unused field .
Updating Alloy to 4610c77 ; LPS - 31413
Remove deprecated constant
Use the path for the maven - built jar now that we are recommending using maven to build above
Fix apicheck break .
Fix linux capture preview .
set VERSION . txt
Exclude log4j in kafka dependency as well
Fixed test data
adding exception
Bumped version to 0 . 35
turn off active by default on tests
add changes note about changed launch scripts
update sample app
prepare release swagger - project - 1 . 01
Restored security tab
Fix 64 bit long pointer size for media scanning
Add definition file for Travis CI
repackaging guava
Fix indent for unordered lists as well
testing build notify
Push version to 15 . 0 . 6 , 15008 .
prepare release checkstyle - 6 . 11
Fix release notes
Don ' t run the lazybones tests in the joint Groovy build .
Added getter for FloatTextureData . buffer
Fix travis building .
fix build error
Delete build . gradle
Revert " Bumping gradle to hopefully fix buffer overflow on Travis "
Remove warning that should rarely matter
Removed DoubleCheckedLocking from checkstyle . xml .
ignore maven target folder and eclipse project files ( .
Closes completely the master password dialog when finished instead of just hiding it .
remove spurious import
Fix extra text appearing after ellipsis
Remove LOAD_OS_APP message from standard context hub messages
Delete screenshot_one .
acknowledge bashisms
updated controller template
LPS - 22149 - This will lockup the browser
LPS - 65920 ( WEB ) Move css files
Don ' t include original exception class name in CQL message
Added upload dir to gitignore
fixed ignore
Fix release notes
Fix bug introduced in Change I856118d8 .
accept " screenshot "
Add a default xlarge wallpaper .
Fixed IndexOutOfBoundsException in EpisodesFragment
remove typo
patch the gitignore by hand .
Give a useful error message when the neo4j shell script gets no command
update travis to play 2 . 2 . 2 - RC1
LPS - 66848 Add missing Gitignore
Add missing closing parenthesis in configuration example
Add optional tags to frameworks / base ext .
fixed # 32
Use the latest version of Android Tools
Updated reference to ownCloud library with reduced logs in operations in shares
Updated build configuration to version 3 . 2 . 0 - SNAPSHOT
make full message view whitespace - aware so we can do cool ascii - art
Make gradle wrappers executable
Fixed the name of the bintray task in the travis file .
LPS - 26209 Remove the row id when closing the row
removed package statement as we ' ve stuff in groovy .
Use the latest lib snapshot
Fix an example of Tree model JSON output
Add image of install details
updated version number
Updated schema version to 3 . 2
Bump SpongeCommon reference .
Excluded a couple of tests from java 9 test suite .
try jdk8 on travis CI with a revised timeout ( 30 mins this time )
git ignore gradle . properties
Add lib / html / sax / push_parser .
Push version to 14 - beta1 , 11258 .
Remove unused import .
More missing " public "
Fix the build
Don ' t invalidate the options menu from the message list as we open a
Reinstate view example for screenshot tests
add a disconnect from ANativeWindow
ignore * .
Delete img
Bump SpongeCommon ref .
Updating the script to build with
Have a bottom actionbar in the Search activity to be consistent .
STORM - 751 Move javadoc aggregate to site phase .
DGM . println ( Object ) and friends do a Writer . close ( ) if the object is a writer .
Use the Cache for ~ / .
Add WaveTable symbol to w3c_audio .
Change version back .
updated the CHANGELOG
Added self to Travis notification list
Removed spurious break .
Updating Alloy to 8cb02f9 ; LPS - 23021
change result type to long ( copy & paste error )
add xml - psi into core - analysis . jar ( required by java )
Make GBM weight test NOPASS again .
Set memory for compiler as otherwise it sometimes fails here
Make SwitchPreference switch more Material
Fix i18n - unsafe API in AaptStep
Set activity state correctly when ending activity .
Flow should ignore website .
Revert " disable parallel execution of web tests with coverage "
knock version back to 1 . 6
update equalsverifier to 2 . 1 . 4 ( # 3410 )
Upgraded parent version .
Upgrade Anonymous Usage Statistics to version 1 . 1 . 0
updated version number to 1 . 01
Ignore OSX and IDE files
Add Screenshot for documenting repo branch in gfx
Fix quotes
Fix test resource number .
Add gitignore to github repo .
update readme for new version
Redraw search autocomplete dropdown after config change .
LPS - 25605 Fix jspc
Don ' t show strange exceptions on shutdown ( PY - 5417 ) .
added appveyor build definition
remove check for Java 6 or above before applying bintray . gradle
Add art assets
Fix layout
Ignore api key file
learning git
Fix an serializable bug .
updated studio
LPS - 47753 - Documents and Media Icon view overlaps border and document name
typo , removed sys accidently a couple days back
Revert " Change the scope "
added oupls images for documentation .
Added person .
Fixing transitive - ness of provided
remove the final modifier to ensure it will compile again
updating version . txt
update demo
Removed " travis_wait "
Remove unused import
Upgrade JUnit to 4 . 12
Remove old unused test resources
Change the 0_fully signal icon to the new style
Upgrade JUnit to 4 . 8 . 2
Remove unreachable code
LPS - 50400 Move AsyncBrokerTest to portal - impl , no change
update linux - x86 natives
add antlr - 3 . 1 . 3 ( should have been in r761805
Bumped minSdkVersion
Forgot to include an import
Fix Java unmappable character warning on Windows .
add Asturian
add csiro . au as TLD since is not listed on Mozilla PSL
missing force refresh icon
Fix bug that meant test always hung until the background process count reached zero .
Removed another version from the pom
Only show warnings and errors from maven - javadoc - plugin
Add different resolutions for ic_action_watched .
Fix AppleBundle # getBuildSteps ( ) so it returns a non - null value .
Added Christopher Deckers as author
Remove log4j . properties from test - jar .
Ignored SDK directory
Bug 289540 added javadoc into distro
Bump the version
Fix WTF when creating a lazily initialized connection
upgraded netty to 4 . 0 . 33
We don ' t need libopencore_author and libcutils in libmedia_jni
Added gitignore .
Remove useless .
adding junit in preparation from testing
Fix documentation for Method . is_static
Fix filename typo
Adding constant to PokeGO
Indexer don ' t use the value specified with - m
Add option to export weights and biases to REST API / Flow .
Fixed a crash in TelephonyManager while calling getDeviceID ( )
removed unused variable
upgraded netty to 4 . 0 . 6
update aboutlibraries
LPS - 63528 Duplicate util package , unify under service layer
removed empty line .
setting version to 1 . 0 . 78
LPS - 46809 Add a line break since we ' re about to manipulate the var
Added local . build . properties to the build so the user can have properties that are not in a file handled by Subversion .
Fix reading sleep policy
Pull oy for release
Missed file during previous commit .
Remove unused import alluxio . util . OSUtils to pass checkstyle
rename for letter case
eliminate signed / unsigned comparison warning
revert change preventing NULL SSID in a WifiConfiguration
Remove unnecessary initialization
Bump SpongeCommon reference .
don ' t use fakeroot to build packages on debian
Remove unknown app module
Added STORM - 1279 to Changelog
Adding riak module
include InterruptedException into mock1 . 7
Added back gtest . zip
LPS - 40933 Puts device preview on top of dockbar and other elements
Fixed a bug in bbb - conf
added e - mail address
removing assembly
convert bytes to hex for BytesType . getString ( )
Updated version in README .
Fix build - remove obsolete import of Animatable
LPS - 68289 Activate HibernateUnexpectedRowCountAspect on CI .
Delete outdated wiki snapshot ( replaced with Asciidoctor documentation )
IDEA - 146469 IDEA with bundled JDK on OS X has incorrect Info . plist settings that prevent dynamic switching between graphics cards
Fix data driven testing example in documentation
another test bites the dust
LPS - 62718 add build . xml
bump to version 5 . 4 - rc - 2
Fixed wrong android version name in README . md
update tests to android - 19
add console appender to quickstart - web
adding rootbeer1_paper . pdf ( HPCC - 2012 conference paper )
prepare for next development iteration
In JSF tag attributes must generally be deferred value expressions , but IDEA does not flag as error immediate evaluation expressions .
Don ' t leak scanners when fetching suggestions from HBase .
set maximum height for mention menu ;
Added STORM - 1476 to CHANGELOG . md
Removed Key Value Server from SVN repository .
add TODO for BIP
remove ugly focus highlight border
Updated the CHANGELOG
Added missing break in case
Move BeanDeclaration to correct package
Add 1 . 3 apk and qrcode
Add screenshot
set correct version
Update stack diagram .
Ignored all dependency - reduced - pom . xml .
may as well make this by default
Move the wcursor increment after the assert
Hide enum constructor further .
remove fiel
make project name distinct from src / grails / build .
Fix sourceDirectory , restoring compiled serializers to guava - gwt jar .
Adding top level .
Updated comment .
Add lint config
Added STORM - 449 to Changelog
Add maven central repo to readme
Modifies prefab to reflect new BreatherComponent name
Fix progress dialogs to top of browser window
Prepare next development version .
Added render distance hook
setting version to 1 . 0 . 100 - SNAPSHOT
setting version to 1 . 0 . 98
LPS - 54533 moves icon
Ignore OSX and IDE files
Added STORM - 797 to Changelog
Actually close the comment
moved pyunit to NOPASS .
LPS - 19211 Missed build . properties
for IDEA - level ignored folders - keep / show in viewer only folder
Remove log4j . properties from test - jar .
add demo . gif
Updated README with recent new Extensions .
Remove Gradle wrapper files from .
Removed unnecessary indirect call in NioSocketChannel . isConnected ( )
Added folder for the visualization project .
bump version for move to Apache incubator
change version num and year for the release of libsvm 3 . 15
Forgot to include images in last commit
Updated github page logo
add " retarget " to english
Adding missing Notifications icon
Add intellij files / folder to .
Delete demo . apk
change uploadArchives to uploadPublished for signing condition
Deploy snapshots of 1 . 1 branch with Travis CI
Updated version in README .
Removed unused import
Remove webpage after dismissing the view .
Removed stupid typo that I accidentally committed .
update druid console version ( # 3189 )
removed blankline
Added settings to .
fixed wrong import .
updated version
Ignore temporary generated site .
Fix spelling mistake .
Remove fall through for KEYCODE_VOICE_ASSIST
fix mac build issue
LPS - 51912 remove redundant ` continue ` keyword
Remove TBD from fields and properties section
Add checkstyle plugin to lifecycle mapping exception to get things work without warnings on Kepler .
Increment gradle build tools
prepare for next development iteration
add flipviewpager
Making sure that there is no notification when focus changes from something to nothing .
enable unit test on jdk6 and 7 , and use mvn clean package instead of mvn test - B
Fix JDK8 doclint range to work with JDK7
Adds Retrofit library
Breaks the loop
LRQA - 29149 prep next , use latest
fixed IDEA build configuration
update assertj to test scope
Updating Alloy to 813ca0d ; LPS - 26904
drop jdk6 from build matrix , we require java 7
Make MetricsRegistry # getMetrics ( ) return an unmodifiable map
Setting default name for multi - project
LPS - 62787 Add missing build . xml
Removed un - used p . paused ( ) .
help topics for VCS configurables ( IDEADEV - 33672 )
Adding top level .
Added support for using a transaction to perform batch tasks .
Fix power provider
Adding image folder for Flow documentation graphics
Call WebView # freeMemory before collecting memory information
Added relative path to the parent POM so that the user won ' t need to
Prepare next release v0 . 88 . 2 - SNAPSHOT
adding gitignore file
prepare for next development iteration
Fix license header .
GRAILS - 5691 - remove some code that was accidentally left in the last commit
Updating Alloy to 8cb02f9 ; LPS - 23021
add seaborn to requirements . txt
add gitignore
Use two threads on TravisCI
Use the latest lib snapshot
Added intellij files to .
Update gradle . properties file with a new VERSION_NAME and VERSION_CODE for the next development iteration
remove empty file
Fix generic method signature
build tools 21 . 1 . 2
set javadocs to use UTF - 8
remove the unused manifest file
add Alireza as contributor
Fix broken test .
add jamm - 0 . 2 . 5 .
Fix variable visibility issue
Added translation using Weblate ( Azerbaijani )
Added diffutils library
Return this instead of null in TimeoutStream # resume
To run test
Bump the default max of the connection pool to 8 .
Adds dialog image
Upgrade parent pom version .
reset version for development
Ignore Vim / Vi backup & swap files
Push version to 11 , 206 .
Fixed a compilation error ( returning from a void method ) .
update internal framework to API 21 ( lollipop )
removed unused texture
Use both JDK7 and JDK8 in Travis
Missing mavenCentral ( ) repository
Update expected user guide sample output
Add travis - ci configuration .
Updating Alloy to 8cb02f9 ; LPS - 23021
Remove Java 7 from Travis build .
Delete PACKAGES . gz
Bumped version to 0 . 8 . 7 - SNAPSHOT .
Prepare version 22 . 0 . 0 - beta3 .
start next dev cycle ( 2 . 0 . 2 - SNAPSHOT )
Add some gitignores
Include ` private - cli ` on npm export
Remove unused import in BufferUtils
Updated usage of the fest - assert - core jar
Add GCMParameterSpec to preloaded - classes
LPS - 19601 No feedback to the user when signing in using Facebook
setting version to 1 . 0 . 151 - SNAPSHOT
Added translation using Weblate ( Kabyle )
removed empty line .
Created tech - debt entries for all components and laboratory components .
Fix landscape layout of LockScreen on devices with a keyboard
don ' t show misleading help message
Added Fenwick Tree ( Binary Indexed Tree ) to the Readme
setting version to 1 . 0 . 126 - SNAPSHOT
Added Example apk
Remove memory limit due to OOME
Add missing JSON highlighting to example .
added new plugins codes
Fix lint
Add oraclejdk8 to the build matrix for Guava on Travis CI .
prepare for next development iteration
Updated version
Granular navigation uses mContentDescription instead of getCpontentDescription ( ) s
Setting build group and version
Missed required - type - id for a junit
updated csproj file
Fix mCoveredFadeColor setter
Log information to determine why the CoreAudio library does not load correctly from the build .
Modifies prefab to reflect new BreatherComponent name
fixed test message for lesson 2 task 5
add release notes
change pyunit to PASS PUBDEV - 2199
Removed unused method
fixed typo in first line of bbb - conf
prepare release HdrHistogram - 1 . 0 . 9
Add screenshot
Run the tests in parallel .
add multithreaded example
Added tag 0 . 0 . 7 . 2 for changeset 5de91e5a0e95
Add lint config
don ' t over - validate email address .
Avoid splitting overloaded methods
Added tmp / to .
Remove Y
Normalize line endings
Remove spurious @ Override .
modified symbol for darcula ( IDEA - 99497 , IDEA - 96808 )
missing return in svg ' s getCoords
Ignore temporary generated site .
bumped parent - pom - > 7 - rc
Completely reverted change on log4j dependency .
Set minSdkVersion + targetSdkVersion via build . gradle
Bump SpongeCommon reference .
updated breton POS dictionary from Apertium svn r53329 .
Add support for ALTER TABLE MODIFY in CUBRID
Added volley . jar to the project
Fixed a code typo
LPS - 67839 Create project build . gradle
Changed Target SDK to 21 ( Lollipop )
Remove android - 22 from buildscript
Added STORM - 1476 to CHANGELOG . md
Source formatter had trailing blank line
Updated TCK .
Moved log4j . properties to test folder to avoid including it in jar
Speed up Travis by running on non - sudo containers
Added STORM - 1449 to Chagelog
Added makeGLMModel call to python .
Added IPC manager ( support info )
Push API version to 1 . 1 . 0 , enable snapshot .
Restored @ since javadoc tag of Convertible
add close method to EchoedRow
Add maven central repo to readme
remove duplicate image
Add DSLContext . fetchFromCSV ( boolean ) to allow for fetching header - less CSV data
printing all threads stack trace , is making the console out put very large and not giving much info
and update CHANGES . txt for CASSANDRA - 11051
Fix JAR count after adding task - cache - http .
Don ' t run the int tests concurrently at all ( for now ) .
fix the push - tags target
add libs / to gitignore and remove old dependency directories
Enabled fast scrolling for season and episode lists .
make sure Maven prints the complete stacktrace to the command line in case of test failures
IDEA - 117674 please rebuild and commit runnerw . exe
Adding a ' .
remove unused logger
Add missing closing parenthesis in configuration example
Add 9 - inch screenshots
Ignore IDEA project files
Fixed issue where unread messages wouldn ' t alert properly .
Add Travis - CI support
upgrade the wrappered gradle to 0 . 9 - rc - 3
Download built apk files here
Renaming FrameDebugExtension to FrameCaptureExtension to better reflect usage
Fix ci link
upgraded some JAR files in the project
Added STORM - 893 to Changelog
tell travis to build free version
Remove javadoc option that fails with java 7
Remove a debug line
Add portlet properties
removing OSX file
Added STORM - 2018 to Changelog
Updated structdb
shut up linter
Updated version
Log information to determine why the CoreAudio library does not load correctly from the build .
Updated screenshots image
increased the default permgen
Only CI build the master branch
Updating Alloy to 4610c77 ; LPS - 31413
Fixed focus javascript error .
add execution permission to " input " script
LPS - 43918 Add SuppressWarnig
Adding couchbase module
reenable daylight saving test , now that we use joda - time 2
Fixed the camel - scala compile error
learning git
Test can take more than 10 minutes , use travis_wait command to allow them take up to 20 minutes .
Prepare library for development
Remove local testing file
remove TBD from " Optionality " section
Avoid early returns
Fix typo for setting selection drawable
add maven support
Fix preloaded classes for the emulator .
Remove stray ' - ' after splitting of increment and decrement methods
Add tab localization
updated images for checkboxes and pagertabstrip
Updated comment .
remove unused import statement
Updated default presentation for BigBlueButton 0 . 81
Remove Android examples from release
Added debug level pool statistics logging
add intellij * .
added CDI / Weld to list of support DI containers
Fix osmo login issue
renamed bouncy castle library and upgraded it to rev141 and jdk1 . 5
Disable mocking " promise " in Jest tests
update osx / darwin native
Rename README to README . md
Releasing v8 . 0 . 5
Fixed formatting of data structure test code
adding words suggested by users
Actually fix dupe drop
Automatically sign artifacts when releasing .
Fix returning wrong field
temporarily disable 1 . 3 rule for idea_rt
Changed target file name
LPS - 54970 removed unnecessary return
LPS - 10836 remove local address after do local method for Unitcast situation
Added Recognizer . removeErrorListeners ( ) to Recognizer . py
update applet to fix some exceptions
Add CHANGELOG . md
the dist and docs target now work with the github repo
Add 1 . 9 . 4 adapter .
always add snapshot repo as long as we are using Groovy 2 . 0 snapshot
Added WebGLUnsignedByteArray to jslint .
Updating Alloy to 8cb02f9 ; LPS - 23021
Move BikePark * to correct location .
Increment version by Travis CI build 145
Add READ SD CARD permission
Upgrade gradle - plugin
Add maven central repo to readme
Fix test failures for CASSANDRA - 5175
Updated version in README
ignore pom . xml . versionsBackup
setting version to 1 . 0 . 111 - SNAPSHOT
add sbt cached resolution to build "
upgraded slf4j to 1 . 7 . 16
rebuild test instrumenter with target java 1 . 5
update doc
add empty header placeholder
add irc icon 64x64
Animate movies grid view .
Relax flow jest - cli regex
Added a gitignore
Push version to 15016 .
tweak readme
Updating Alloy to 8cb02f9 ; LPS - 23021
Updated code .
Bump versionCode to 85 .
trying out shippable
Removing openjdk8 from the Travis config as this isn ' t supported
tried new submodule url
updating changelog
initial git ignore file
build # 7
Adds more code on dispatching audio level events .
Remove title , gets set dynamically
Configuration not needed any more .
Adds stream capture and render via CoreAudio for MacOSX .
Added the shutdown command to the service provider
Add getter method for line length field .
Input Whitespace ( is used in many UTs ) now compilable
shiftreduce parser in corenlp requires pos
Add version 2 . 3 . 4 to upgrade from versions
Also update ticked icon .
Fix POM
Ignore * .
adding word " LibreOffice "
dispatch up event to fix fling
Make ViewHolder less visible and static .
prepare for next development iteration
add STORM - 1079 to CHANGELOG . md
Added tag 0 . 2 for changeset aa491af82d9a
Invalidate ActionMode content rect on scroll .
Add missing travis ci components
disable AMQP by default in graylog2 . conf example # NO_ISSUE
add screenshots
Revert test
Updates
ignore portal - profile 1 . 0 . 3 prep next
make the common library
improved favicon
build make buildlog include tests run and fail stacktraces
Fixed pom . xml tag
Add lintOptions in build . gradle
remove repeat lefover . . .
add / bin - test - lib to .
added code generation of the use of tuples , lists and maps
Reseting a project . properties file
Add transition screenshots
Upgrade asset pipeline to 3 . 2 . 0
Revert " updated dependency "
LPS - 65012 Move export - import - service resources to the correct dir
Git hygiene
Ignore eclipse files
Resized header
LPS - 55548 Add property to field type settings definition
MinecraftForge / FML @ 0b84b6aa297bdf6ab9f010e340f286442cb242dc Expose the state of the loader
Reverts removal of @ JsonIgnore on Event . type field
remove bin directory
Added * jar and out into ignore list .
Add getBytes to InputStream , URL and File ( patch thanks to jeremi Joslin )
change the gitignore
adding this in so its there for easy building
Removed unused return type in ExecutorServiceProxy .
add help topic ( IDEADEV - 24855 )
Change put command .
ignore classes directory
prepare for next development iteration
fix more apostrophes
Updating Alloy to 813ca0d ; LPS - 26904
ignore * ~ from hg
Remove another unused method .
Push version to 11250 .
fixed possible problem with closed DB
Fixed MySQL datetime test case
Updated studio with Security + Backup UI
removed wrong doc
Add a LOG_TAG for android . graphics . Graphics JNI .
Remove travis configuration file
Ignore the local eap repo .
add logo
fix usages may break code if conflicts were ignored
adding comment about compiler argument
add words suggested by users
Remove old InetAddress DNS cache from preloaded - classes .
Added integration test outputs to .
Updated Slovak translation
add new line at the end of file in the pom . xml
Removed " terrain . png "
added few known transitive verbs .
Add Spring
Updated dependency version to latest release
Update delve version
changing demo runit statuses
LRQA - 16038 Fix value of property to get correct team name to testray
add * ~ to .
Made names consistent in configuration examples
Built the latest snapshot
Update to latest getglue - java snapshot , now supports checkin comments .
Replace AndroidEmoji . ttf for UI optimization
Set beta_features to True .
skip tests in compiling alluxio for hadoop
Commits the binary for the JNI Speex encoder , decoder and resampler on Mac OS X and thus enables them .
Recommend jcenter repo .
Add STORM - 1427 to Changelog
update default gradle version configuration
bump to 1 . 7 . 6 and minor CHANGELOG cleanup
Aligned pom . xml with the other components .
Adds the .
LPS - 69997 Add taglib mapping
add all jdk
update gradle
add h2o_hosts
Fix build after checkThread fix merge to master
Set memory limit for CircleCI
add function with zero arguments
remove old screenshots they are not representativ anymore
Display improvements
Bump common ref .
fixed android backend . . .
Adding empty script to " pack . sh " GhostDriver ( a reminder . . . )
Upload 1 . 4 . 1 version .
Added ignores for Eclipse files
Simplified shell launcher and fixed white space handling
Upgrade retrofit2 to beta4
Set log level to trace for package action . support . broadcast in the RecoveryPercolatorTests # testSinglePercolator_recovery test .
add STORM - 1126 to changelog
Fix uninitialized rect structure for retrieving rect cropping information from decoder
add new hdpi and xxhdpi resources for penandink icon
Adding mavenLocal ( ) for local resolution
include ' < cxxabi . h > ' ( needed for non - OS X platforms )
prepare for next development iteration
Changed background color of external player to transparent
lower gig requirements to 1 , test works fine .
Changed wrong id .
Started work on the ICQ / AIM protocol provider implementation
we could be leaking file descriptors here
LPS - 47461 Add entry - action style
Updating Alloy to 813ca0d ; LPS - 26904
make auto focus for all consoles with history
adding lang3 jars
fixed a bug in the - - salt function
Fix # 2739
Added ' metaclass ' to default Python dictionary ( PY - 13357 )
Adds a jitsi - defaults .
Added makeGLMModel call to python .
Do not commit target directory
remove PIDFILE at stop time
Tried new gititgnore file
Move the wcursor increment after the assert
added Kasper to list of developers
Upgraded parent version .
Add DSLContext . fetchFromCSV ( boolean ) to allow for fetching header - less CSV data
Removed tag roboguice - 2 . 0 - RC2b
Preparing for release X . Y . Z
add support for chunk setup options in data chunks
emit didFocus after routeStack reset
remove fiel
Added new files to libRSSupport
added rendered version of logo
update linux - arm native
Fixed a bug
Updated CHANGES
Fix OSGI version
Fix data driven testing example in documentation
Rebuild static openssl libraries from NDK r9c
can ' t access static field from nested closures
Bumped JadConfig to version 0 . 3 , fixes SERVER - 59
Add STORM - 244 to Changelog .
Bump readme version
Make gradle wrappers executable
Don ' t link librt on Mac
LPS - 32257 Removed conflicting nekohtml classes
Updated README for 0 . 6 . 7 . 2
update travis . yml
Add maven central repo to readme
HHH - 9717 - Build script improvements - applied new standalone XJC and AnimalSniffer plugins
Add - lpam when linking pam_google_authenticator module to fix undefined symbol problem
Fixed issue where ChunkPriderEvent . InitNoiseField used the wrong sizeY value .
prepare release 0 . 16 . 0
Create README . md
update version number for doc stamp
Push version to 14 - beta4 , 11261 .
fixed wrong import .
Upgrade Aalto - xml to 1 . 0
Restored upload of distribution
Revert unnecessary build / version changes
removed onion routing from readme
rename file so its title has a space in it
Allow the support library to work directly on Gingerbread .
bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6
DO NOT MERGE Take fake bold font property into account .
disable partial nashorn support while merging in recent bug fixes
Upgraded surefire maven plugin to 2 . 6
LPS - 55591 Move icon
LPS - 39388 Remove weird comment
Delete obsolete import
Updating Alloy to a8113a6 ; LPS - 30593
Add support for interceptorsgd
add style images
Remove unused setter from HttpConfiguration .
Ignore bin and gen
LPS - 64744 don ' t make this a a subrepo
Added GIF
Fixed default focused element for credentials dialog opening ( password is focused if username is disabled )
STORM - 751 Move javadoc aggregate to site phase .
Removing accidentally added file
update com . android . tools . build to 0 . 4 .
run travis ci whit ' gradlew check '
added Steve as a contributor
LPS - 31159 Move TemplateResourceExternalizationTest to portal - impl / unit - test
Updated read me
set IntelliJ IDEA languageLevel to 1 . 6 for Grails 2 . 4 .
Add an " all " target to compile everything and run test cases , pmd , findbugs etc
Fix footer in FireFox
ApplicationStarterBase can process external command line
Added OpenJDK 6 to the Travis config
Reverted accidental DataSourceStatus enum change
Remove ' displayName ' prop from ' PickerExample ' component
add grailsCentral ( ) repo to sample application so dependency resolve
Fix typo
include " ruby / util .
Fixed typo in doc
Fix CircleCI configuration
Overload Methods Declaration Order Check compilable UT input
Modified url for issue tracking to directly show tickets for the component .
update dict
Added the PR number for the snapshot interface in the changelog
update todo
Fixed pom . xml issue with distributed sub - project
build new pre release b4
Bump common and forge build dependency .
fix bug
Remove redundant call to createSdpOffer ( )
Fixes # 167 by replacing the undefined ' mavenUser ' and ' mavenPassword ' with placeholders
updated version
Fix memory leak ( also delete the best model ) .
disable uploadArchives for streaming and hadoop 1 . 0
Add back validate into BootstrapModal globals
restore grails . factories file
add function with zero arguments
removed unused annotations from java . g
Saving Blacklist and Hold for Moderation lists when dismissing dialog
Ignore eclipse files
Replace refresh with cluster . health check
fixed BackgroundAttribute bug .
Bump up assertj version
update gradle
make note of # 4452 and # 4452
This update fixes pty on windows .
Delete dangling comment about long - dead code .
Removed android - support - v4 . jar .
LPS - 40679 Fix SF
Remove redundant fileTree dependency
Set VERSION to 5 . 3 . 0 - dev ( via coho )
ignore logs
add STORM - 1008 to CHANGELOG . md
added Richard to the team - welcome aboard !
updating to Gremlin 0 . 8
Upgraded maven - javadoc - plugin from 2 . 7 to 2 . 9
Fix indent
Ignore bin and gen
Added a property to avoid the exception stack trace when running the console
Updated copyright date in LICENSE .
Intellij doesn ' t like trailing newlines ; removed from neo4j . xml .
fixed big refresh image for tablets
LPS - 65225 update hash
Moved AstBrowserProperties from src / main to src / resources .
Prepared version 1 . 8 . 0
Add caching of Maven artifacts to Travis CI build
made the mistake of opening anything in finder
Added STORM - 1204 to Changelog
temporarily disable 1 . 3 rule for idea_rt
make dummy change and assert CC is updating correctly
Added failing test for JSON output
update applet jar with changes to minimize connect timeout
update common ref
remove change from another PR to avoid confusion
Added CNAME for github docs to accept project - voldemort .
try a little more heap memory for tests in Bamboo
Fixed cancel button in landscape account activity
Use new sanitizer option .
CORE - 1506 updateSQL generates invalid SQL for oracle
add new similarity word2vec test
finished collection / list separation
Fix UIExplorer drawer list
Fix a bug in ControllerActivityCounter
Removed leftover name field
Remove random "
bumped parent versions from 2 - SNAPSHOT to 2
Ignore IDEA directory
add execution permission to " input " script
Change Chunk < T > to be a static inner class
Renamed maven assembly to jmxtrans - all . jar .
removed left space from chat view balloon
Bumping the version code again .
use the latest platform - tools on travis
Updated reference to library after adding support to set user agent
LRQA - 16067 Add list of product names into test . properties
LPS - 46537 Add plugins SDK
rename " Console Folding " to " Console "
try screen refresh
remove unused property
added id to textview
Upgrade parent pom version .
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
git ignore eclipse stuff
Add lineDashOffset to externs for CanvasRenderingContext2D .
enable EGL_IMG_context_priority for the omap4 platform
add tags for wakelock and other API names
JETTY - 1308 327109 ( re ) fixed AJP handling of empty packets
Replicate text and sounds settings for managed profile .
Fixed travis build tools version
Upgrade gecko to 1 . 1 . 3
fixed test data for docStub intention
Remove oraclejdk7 from travis .
Updated library reference
ensure key provider returns unique key for each item
Changed id to CLI friendly format .
Updated IntelliJ version
Fix an unintentional change in method signature and avoid an API change .
Ignore reports directory .
Add link to Javadocs
Marking 9 . 3 . 8 as clirr comparison
Updated default presentation for BigBlueButton 0 . 81
Ignore the gradle - app .
Added a protected method to retrieve the indent printer for reuse in subclasses of MarkupBuilder
Updated contributing section
Updated French translation
Add missing closing parenthesis in configuration example
Add a Javadoc pointer from DiscreteDomain to DiscreteDomains .
Hide gh - pages
use oracle ' s official jdk
Fixed method layout in ActivityApp
update applet to fix some exceptions
Bump SpongeCommon reference .
add Eclipse support
Add @ since comment for method Part . getSubmittedFileName ( ) that was added in Servlet 3 . 1 .
Added app_konference - 10 . 04 - 32 .
updated CHANGES
Push version to 12 - beta2 , 210 .
Use the Cache for ~ / .
configured functional tests to run with forked jvm per - test , possibly hiding a memory leak problem with tests
adding vvikas
passed 4 times on small machines , once on my local machine
add A tag ' s cursor css
add todo
Added STORM - 827 to Changelog
Remove test I opted to host elsewhere
Fixed lost text in notifications for failed uploads
modify docker
Make Option extend HTMLOptionElement instead of Element
Remove redundant constructor .
comment out snapshot plugin for release
use a container and caches
Don ' t appy recording marks twice to audio
updated studio
Correct a typo
Add scope = test to hsqldb ( fixes # 330 )
added support for GvTags
Fix previous fix .
handle new nack packet in timeline
Remove failed test to troubleshoot
improve banner
Ignore Eclipse files
updated sdk
Fix typo in angular - 1 . 5 externs
Add text editor temporary files to .
Added support - annotations
Added STORM - 1837 to Changelog
update latin names
Prepare release 3 . 0 . 5
logging stuff 1 .
Prevent random crashes on SGX architecture
add ConnectionState interceptor ,
Fix crash when doing conferencing over Wi - Fi
LPS - 47045 Add @ Override
LPS - 63528 ( WEB ) Move icon files
Don ' t fetch all indexer errors to get total count
fixing build
Added STORM - 132 to Changelog
remove component ' s events when dealloc is called . "
update windows natives
Bump common ref .
setting version to 1 . 0 . 118
added few known transitive verbs .
add STORM - 1937 to CHANGELOG
Corrected typo in year in license
Don ' t capitalize headings .
tries a rescue of my git repository after a network loss
LPS - 65749 prep next , use latest
Push version to 16 - beta4 , 15013 .
Added jme3 - lwjgl3 / build / to the gitignore file . . . .
Remove a problematic empty update optimization .
use more subtle shade for inline toolbar button text
Add art assets
added mysql - python
Fix descriptor leak after accepting connections
Upgraded maven - compiler - plugin version .
Updated logos with new ones - part of # 630 rebranding
LPS - 61440 remove dynamicImport
Removed rogue text from build file .
ignore intellij project / workspace files
Fix changelog by adding a new empty section
Add fast color matrix
Updated EnOcean lib to work with more EEP .
fixed 5 millisecond delay on recompiled .
updated version
Ignore IntelliJ metadata
add sitetools
Fix recent regression in DrawableContainer .
bump socket . io for tests
Logs a couple of debug messages to warn about potential programming errors .
Increment gradle build tools
rename example guide
Removed application tag from library , unnecessary
LEP - 5045 Bug - Allow guest to see attached images
Upgrade Apache Commons Collections to v3 . 2 . 2
Add pointer to h2o - 3 repo .
updated JettyWebfilterTest . java to JettyWebFilterTest . java
cleanup remove unused file
Ignore IntelliJ IDEA files
Added message .
Add a task that resolves all configurations .
build nekodtd using java 6 instead of java 7 and commit the new binaries .
Porting fix to allow for a forward / include to call getAttributeNames on the Request in a sandbox
Updating Alloy to 8cb02f9 ; LPS - 23021
update com . android . tools . build to 0 . 4 .
Remove hardcoded version of commons - cli
Added reference to distribution .
Fix up Settings dependencies when Enabled is off , fix # 208
Add PBAP service start .
Use higher z - index for modal backdrop
added changes for 1 . 2 RC3
fixed test data
add STORM - 1646 to CHANGELOG
Include shrink - index .
Bumped version to 1 . 6
LRQA - 12823 - Add test property to use Solr in Poshi
fixed PY - 2608 Test runner does not draw test hierarchy
setting version to 1 . 0 . 103
Remove unnecessary permission from gallery app
update linux - ppc64 native
add context accessor for subclasses
Moving third - party STUN implementation from Openfire main project to plugin .
add analysis - icu module
ignore grails - plugin - domain - class / bin
Commit ugly icon
Not using any more
add apply eclipse to enable cleanEclipse eclipse targets
Fix potential segfault in RS watchdog .
upgraded netty to 4 . 0 . 7
Changed CommandLineRunner to public , as I believe that was the intention according to
Adding icon for attic and modified firstfloor icon to exclude the attic .
Updating Alloy to 8cb02f9 ; LPS - 23021
Add a white background layer .
Includes the NOTICE file in the release
update jars
placed the completed ( ) call under the right braces
adding windows builds of new native dlls
updated CHANGES
FIX Dashboard always display a scroll in IE7 ( cherry picked from
Added debug assertions
Suppressed deprecation warning in the group test
Remove spurious density - specific default wallpaper .
Prepare next development version .
Refactored quartz plugin .
Added new files to libRSSupport
add STORM - 1674 to changelog
Bump maven lib version to 1 . 0 . 1 .
Removed unnecessary file
modified image
Added more height to the shadow drawable , so it can be scaled properly to lower dpi screens .
Avoid NPE when trying to do access logging on cookies for an unmapped request .
Smack 4 . 1 . 0 - beta3 - SNAPSHOT
updating gitignore
Remove an unnecessary empty line
Add travis config
reduce staggering in help display
Add CHANGELOG . md
add jdk
remove unused config
Removing Java 6 from the travis build config since 7 + is needed for findbugs 3 . 0 .
GROOVY - 816 - import breaks example
Fix changelog by adding a new empty section
invoke later to show error message
implementing before on node set
add HADOOP - 9417 to CHANGES . txt
removing appinfo . jar
Allow change in whether to shuffle training data after checkpoint restart .
Create menu_nl .
Removing accidentally added file
Fixing deprecated gradle property
Added Travis
Added Travis
Modify changelog
Added multichat operation set definition and Gibberish protocol implementation .
Fix plugin id name
Added files via upload
removing appinfo . jar
remove old screenshots they are not representativ anymore
setting version to 1 . 0 . 151 - SNAPSHOT
