Remove unused image .
Updated FML , Renamed it ' s readme for the Wiki
Ignore local classpath
Ignore Update ' modules / apps / collaboration / blogs / .
Updating Alloy to 4a5c75c ; LPS - 34421 , LPS - 30784
Fix transitive dependencies in pom . Xml
Updated changelog
Remove opendk as it ' s not present
Fix incorrect solaris / x86 native library
Update changelog
Add getter for perf package .
Delete demo2 . Gif
Push version to 11244 .
Fix scope for DW example tests .
Ignore Update ' modules / apps / foundation / portal - remote / .
Don ' t delete system / hive as well in antlr . Jar .
Use PApplet . Java ( ) instead of index ( ) for present .
Add STORM - 2041 to CHANGELOG
Fix broken build
Reset build identifier to next milestone snapshot
Fix copy & paste error in isKeyguardLocked ( )
Cut the candidate branch , bumped curr . Release to 0 . 70 .
Fixed # 860
Update support library to 23 . 2 . 1
Add script for issue template
Remove some trailing whitespace
Remove unused import .
Adding minimal doc
Fix copy / paste error
Ignore Update ' modules / apps / marketplace / .
Updates build tools version to 2 . 1 . 2
Updated documentation to point to the Polymer pass .
Remove unused import
Fixed typo in README . Md
Added alternative method to create super
Update android natives
Supporting script ' s startup .
Update adbiFilters
Fix syntax error in readme
Ignore Update ' modules / apps / web - experience / journal / .
Set source level to 1 . 7 for javadocAll if possible
Ignore Update ' modules / apps / collaboration / flags / .
LPS - 61156 Move BaseDBTestCase to portal - test - internal
Upgraded netty to 4 . 0 . 31
Prepare next development version .
Regenerate gradle - wrapper . Jar with 1 . 9 - rc - 4
Removed new files for HDFS - client .
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Add release rules
Update readme
Add animated app file
Ignore that pesky id_file in camel - hl7
Added a redirect for the deployment ( # 1041 )
Added IntelliJ IDEA specific extentions to be ignored .
Updated ChangeLog
GRAILS - 11151 remove StatementCache from jdbcInterceptors property from default
CPP - 5210 Add " Accessors " to jetbrains . Txt
Revert " retire android_native_window_t "
Fixed a bug in ScanSettings constructor ( # 8 )
Ignore Update ' modules / apps / foundation / contacts / .
Fix test data
Removing @ Nullable from AppCompatActivity # getData ( )
Run failing tests ( PY - 19862 )
Remove unused files .
Move PointSetTest to the same location as PointSet .
Fix single NPE in angular - 1 . 5 + again
Don ' t debug grails - core dependency on travis - ci
Don ' t show sidebar menu by default
Remove TBD from fields and properties section
Remove warning ( ) from error ( ) .
Adding junit jar file ( IDEADEV - 40066 )
Commit incr - debug services
Bump common for 4 . 2 . 2 ref
Ignore Update ' modules / apps / collaboration / message - boards / .
HHH - 6495 Adding a comment ( move space must be needed in case sensitive from project ( ) .
Fixed missing ' var ' in header . Css
Ignore Update ' modules / apps / marketplace / .
Fixed a bug in the TODO ( ) method to work properly
Rename class to match file
Disable NPE when stop is used ( PY - 15823 ) .
Fix broken test name
Updated Gains / Lift screenshots with new images from Nidhi
CPP - 5210 Add " Accessors " to jetbrains dictionary
Update CHANGES . Txt
Fixed EDU - 158 Problems with tasks
Added missing version to checkstyle plugin
Remove unused local variable from comment that we ' re methods that we can be used by well .
Fixed the text icon from the view / list .
Update changelog
Updated proguard name
Accept " automata "
Update gradle gradle plugin to 0 . 4 . 1
Ignore Update ' modules / apps / foundation / map / .
Updated FML as LICENSE to reflect problems with non - reserved rules
Fixed clirr config
Bump up Netty version to 4 . 0 . 1
Upgrade os - maven - plugin to fix the build issue
Add StoreMeta which is an empty style for now
Removed unused strings . Png asset from HIVE - 522 .
Added * .
Updated version
Add table of contents in python / README
Fixed issue when stop all on progress returned ( IDEA - 81507 )
Added option to index script
Add OC - Total - Length to UploadRemoteFileOperation
Updated read me
Set the FilterCriteria . OnRecallSelection ( ) method to return the same state
Remove old semicolon
Remove unused import .
Removing bitdeli - badge
Adding missing test file
LPS - 63462 update jar
Ignore Update ' modules / apps / collaboration / microblogs / .
Updated reference to oc - library
Fixed a bug in svm . Cpp .
Missing apt_deps .
Updated es upstream to fix flaky DeallocatorsTest
Corrected plugin ids for groovy plugin instead of java 8 ( PY - 20263 )
Added STORM - 1348 to Changelog
Update changelog
Fix transition not properly removing targets types .
AS7 - 5700 removed version from maven - maven - plugin - plugin
Added the manual to the build .
Upgrade the wrappered gradle to 0 . 9 - rc - 3
Ignore Update ' modules / apps / foundation / portal - search / .
Updated todo
Ignore Update ' modules / apps / web - experience / asset / .
Removed unnecessary return statement in LineageFileOutStream
Update travis . Yml
Increased cassandra version to 1 . 1 . 3
Eliminated dependencies on pthread , glib rec mutex synchronization .
Fixed typo in com . Mongodb . MongoServerSelectionException class .
Removed unnecessary semicolon in StringUtils
Ignore Update ' modules / apps / collaboration / notifications / .
Fix snapshot version
We don ' t need these classes any longer
Move test to NOPASS
Updated studio
Ignore Update ' modules / apps / foundation / web - proxy / .
Starting 0 . 5 . 5 - SNAPSHOT
Added STORM - 850 to Changelog
Improve Readme wrt # 547 )
Remove debug statement
GRAILS - 10102 - test - plugin - test module changes
Reduced default memory size to work .
Updated version
Added toString ( ) to kotlin . Css
Fixed bug with the version of the subproject
Add vim swp files to gitignore .
Changed version to 0 . 1 , since the 1 . 0 was just the default version which maven generates for you .
Remove unused import ( # 1342 )
Optimize build release script
Add updated ffmpeg JNI library for Linux 32 - bit and 64 - bit .
Add 2 . 4 . 2 to build configuration with processor ( IDEADEV - 20263 )
Added Bitdeli badge
Ignore Update ' modules / apps / foundation / frontend - js / .
Remove calls to RCTBundleURLProvider setDefaults
Remove change from another PR to avoid confusion
Add HBase testing directories to gitignore
Die unused jre .
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Fixed a typo in the README .
Bump version to 1 . 1 . 0 - SNAPSHOT
Fixed a bug where GCalControlSet were not working .
Ignore Update ' modules / apps / web - experience / asset / .
Correct a type annotation in w3c_indexeddb .
Git ignore eclipse stuff
Add link to support README .
Ignore Update ' modules / apps / collaboration / document - library / .
Update to latest android support libraries v23 . 3 . 0
Fixed a bug in svm . Cpp .
Bump up the version number to 1 . 2 . 0
Updated version number to 0 . 23 . 0 - SNAPSHOT
Fixed typo in reference to match copy ( PY - 15907 )
Updated changelog
Revert heap name to use UTF - 8
Removing @ Override flag from compareTo method , since it isn ' t needed
Remove temp dependency from readme
Added image for Play store ( new requirement )
Ignore Update ' modules / apps / foundation / portal / .
Ignore Update ' modules / apps / screens / .
Fixes # 591 Synchronise the untrack statement method to ensure that Statements are independently thread - safe .
Update to classworlds 1 . 1 - alpha - 1
Fix REAMDE . Md for v1 . 0 . 1
Push version to 206 .
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Revert " Enable OpenCORE on master - part 1 "
Updating R link to the wiki directory .
Updated studio
Ignore Update ' modules / apps / foundation / frontend - js / .
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Ignore Update ' modules / apps / foundation / roles / .
Changed dependency to milestone versions in pom . Xml
Handle jumpToCurrentState ( ) in VectorDrawable
Disable cat . Recovery / 10_basic .
Updated README . Md for 0 . 4 . 1 release
Removed old background color for python interface
Remove language " fr "
Ignore Update ' modules / apps / web - experience / export - import / .
Update Android build tools ( # 908 )
Don ' t run eglTerminate - > UTF - 8 , so we can know something twice .
Fixed closing socket in debuger .
Update sparc natives
Fix typo
Switch basic auth back on in web - secure
Moved @ Transaction and @ NotTransactional to Core dependencies
Add curContext . BlendFunc to fake - dom .
Fixed EDU - 158 Problems with tasks
Added professional image for wiki
Set version 4 . 5 . 2 - SNAPSHOT
Updated Ant jar
LPS - 48075 update stuff in docroot based plugins
Remove trailing System . Out . Println from FakeBase64
Updating changelog
Added tag 0 . 5 for changeset aa491af82d9a
Updated version of jikes
Ignore translator - web 1 . 0 . 3 prep next
Update native jar to 3 . 2 . 2
Changed the inner class to static
Fixed bug in previous commit ( # 833 )
Ignore Update ' modules / apps / foundation / portal - lock / .
Publish 0 . 6 . 2 to fix build errors problem
Ignore class files in root ( which are generated by " gradle test " )
Modified todo not making new else in HTML view
Remove the empty file accidentally checked it with HADOOP - 7249 .
Remove underline on focused link
Bump the version number to 1 . 2 . 2 - dev
Update gradle to v2 . 0 . 0 - alpha1 to enable instant run ; )
LPS - 60633 Move FlagRequest to service module
Bumped version
Updated gitignore to ignore hprof files .
Fix an issue with the message that doesn ' t do anything 1 . 5 .
Don ' t accept " Leereichen " , probably a typo of " Leerzeichen "
Add image for simplecursoradapter
Tweak transitive dependencies from javadoc files ( see part of packages ) .
Changed constructor to true for now ( PY - 5417 ) .
LPS - 56692 update BundleVersion to 2 . 0 . 0 since prep for 2 . 0 . 1 prep next
Remove old semicolon in graylog2 . Sh
Don ' t show the inner class scope
Fix auto - text print in overflow view ( closes # 100 )
Sample should use doLast ( ) instead of doFirst ( )
Updated release readme
IDEA - 43728 Provide a way to step in a chosen thread while others remain suspended - remove dupliacted SUSPEND_ALL contexts
Remove TODO from OperationMerge
Fix library in library build . Gradle .
Removed unused property from AnimatorSet .
Revert default scroller .
Do not close the inner class instance when it ' s been read .
Make uploadMavenCentral task , that encompasses other tasks
Updated changelog
Prepare version 24 - beta2 .
Ignore Update ' modules / apps / foundation / portal / .
Updated es module
Add STORM - 1032 to CHANGELOG . Md
ACT - 401 Added cxf module to the checkmule profile
Remove warning that doesn ' t complete it instead of windows .
Ignore jar .
Added image for multi task visualization
Saving Blacklist and Hold for Moderation lists when dismissing dialog
Updated changelog
Ignore Update ' modules / apps / web - experience / iframe / .
Bump up version number .
Update version to 1 . 5 . 1
Make subcaption font for enumeration - seq
Don ' t force refresh with style messages for now
Nexus S now reports the proper frame - rate
Update README . Md for version 0 . 1 . 3
Replaced huge screenshot
Re - correcting the a constant for LOCAL_ONE in v2 . 5 .
Add makefile
Prepare release HikariCP - 1 . 3 . 0
Solves script can now pick up env var JAVA_HOME
Added gradle . Properties to .
Starting 0 . 5 . 5 - SNAPSHOT
Updated logo more according to new icon
Added cycle to the deploy profile
Fixed bug in ByteBufferSend that lead to missing super .
Fix broken libjnportaudio . So for Linux 32 - bit .
Fix VM memory leak in AudioSystem JNI interface
Regenerate portal - client .
Ignore Update ' modules / apps / foundation / web - proxy / .
Bumping project configuration requirement to Android 2 . 2
Revert version for 0 . 9 . 1
Make the cumulation field in unittest to its own exception types .
Added STORM - 1954 to CHANGELOG . Md
Fix merge warning
Ignore Update ' modules / apps / static / osgi / .
Ignore Update ' modules / apps / collaboration / blogs / .
Ignore Update ' modules / apps / web - experience / export - import / .
Change the prefetcher ' s low exceptions to available for Windows ( PY - 6618 )
Prepare next release v1 . 0 . 2 - SNAPSHOT
Updated README . Md image to reflect new version list in README . Md
Added - - porcelain flag .
Add actor - bots - Add entries in bbb - conf
Update linux - ppc64 native
Add " tuple " and " tuples " ( fixes # 394 )
Added jOOQ - related dir to ignore .
Update w32 jar and universal jar ( defer toolkit load )
Fixed typo in typo in bbb - conf
Removed cofh from checked files
Adding STORM - 1979 to CHANGELOG . Md
Added a new high dpi icon , and an updated version of the medium dpi version .
Added CHANGES . Txt for YARN - 2503 .
Remove unused import
Added types to create a subset of the end of FsPermission . Java
Add package name
Ignore Update ' modules / apps / web - experience / asset / .
Now ignores realm which there is an generated directories .
Added google logo
Removed old readme from support . Properties
IDEA - 126585 " Evaluate Code Fragment " dialog should be highlighted one ( IDEADEV - 17986 )
Don ' t compress jars
Adding missing proguard rule for proguard
Don ' t build consoleio on win64
Fixing phpunit invocation
Remove superfluous whitespace in CompilerExecutor . Java
Bump the version number to 2 . 1 . 3
Updated README . Md to ver 1 . 0 . 1
LPS - 25268 Tags overlap Wiki Edit / Details / Print
Ignore Update ' modules / apps / collaboration / recent - documents / .
Update build tools version to 23 . 1 . 0
Add a couple of AUTHORS in readme . Md
Adding branch in .
Add image for the pep8 - dpi icon
Granular navigation 4099023 - Phantom clicks on some websites
Remove checkThread ( ) method from findAddress
Setting version to 1 . 0 . 8
Remove dummy libsurfaceflinger_client
Updated readme version
Restore Dexguard obfuscation , re # 301
Ignore Update ' modules / apps / collaboration / mentions / .
Ignore Update ' modules / apps / web - experience / portlet - configuration / .
Ignore Update ' modules / apps / collaboration / ratings / .
Fixed transitive dep issue
Actually reset the number of frames that could never invoked in the minimum camera but not applied for children .
Suppress pre - needed index ( IDEADEV - 12901 )
Ignore Update ' modules / apps / foundation / petra / .
Fix broken build
Updated formula typo in the logo
Move DeepLearning . Java to h2o - algos .
MinecraftForge / FML @ d00feb58c762b0bbc506d79faf1ce40bc96732e9 Remove debug code that was causing console spam in Forge .
Adding Eclipse - related files to gitignore .
Updating Alloy to rev . 81636
Removed unnecessary indirect call in NioSocketChannel . IsConnected ( )
Removed a System . Out
Updating Alloy to ccc1dec ; LPS - 30040
Remove lint option to avoid grails - level - v23 . 0 .
Setting version to 1 . 0 . 111 - SNAPSHOT
Updated TCK .
Update native lib to 3 . 2 . 2
Remove redundant version number from application . Properties ( grails plugin )
Ignore Update ' modules / apps / foundation / portal - template / .
Rename one class in last commit
Added thirty minute per test time limit , to avoid stalled tests
Update deskshare applet
Fixed a subtle bug in ParticleSystem . Reset ( ) ( CASSANDRA - 9042 )
Ignore Update ' modules / apps / web - experience / journal / .
Fixed a bug with the init script to make it work in IE .
Fixed a naming issue
Add adapter for android .
Fix Java 7 in build . Gradle
Fix problem with installing the build .
Install database - migration plugin by default
Using jetty - test - helper version 2 . 7 .
DO NOT MERGE Add missing ap threshold
Added a missing def
Fixed error message when building the system ' s list that we can be done by default .
Added GPL - licensed application icon
Updating Alloy to rev . 81636
Upgraded Wrapper
Fixed tag state identification problem
Ignore Update ' modules / apps / collaboration / invitation / .
Ignore Update ' modules / apps / web - experience / site - navigation / .
Prepare 0 . 8 . 8 release
Use git protocol instead of https for submodule references - - avoids Windows msysgit flakiness .
Don ' t log failed strings ( PY - 65 )
Adding # 215 Update readme to README . Md
Added folder for the visualization project .
Add console appender to quickstart - web
Update demo
Ignore Update ' modules / apps / sync / .
Ignore Update ' modules / apps / collaboration / wiki / .
Use okhttp 1 . 5 . 0 .
Added more margin to the new location .
Ignore Update ' modules / apps / foundation / portal - scheduler / .
Added gitignore .
Ignore Update ' modules / apps / marketplace / .
Update the screenshot of the gauss decay in function_score
Add branch name " master " to version . Properties
LPS - 66316 ( WEB ) Move css file
Fixed readme in README .
Ignore Update ' modules / apps / foundation / portal - search / .
SONAR - 5173 Change the filter of the color to align value
Ignore Update ' modules / apps / adaptive - media / .
Added logo
Use smaller font size for outline
Ignore Update ' modules / apps / foundation / frontend - editor / .
Smack 4 . 2 . 0 - rc1
Add ABS as dependency to library ( fix # 559 )
Add STORM - 555 to changelog
Updated version number for release notes
Add gitignore file
Removed obsolete lib submodule
Delete unused import .
Ignoring target directory created by running sample ha - ops bash scripts
Update shiped ForgeGradle for 1 . 7
Hiding DrawerLayout does not fire correct accessibility event .
Removed an empty file from the realm control
Ignored dependency - reduced - pom .
Update icons for layout ( IDEA - 125223 )
Ignore Update ' modules / apps / foundation / my - account / .
Changed pom of concurrent threads for build to pass on Bamboo
Setting version to 1 . 0 . 64 - SNAPSHOT
Removed debug println from createGraphics .
Fix javadoc warning
Ignore Update ' modules / apps / foundation / monitoring / .
Remove unused return statement in ExecutorServiceProxy .
Ignore IntelliJ backup files
Add StringTemplate to the NOTICE file
Added missing script to git
Fix the JSDoc for angular . Collections .
Increase the number of threads so that we can ' t reset twice ( PY - 15907 )
Fixed a bug in svm . Cpp .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Updated changelog
Fix a problem in the client .
Updated changelog
Remove unused semicolon .
Removing unneeded jar file
Add change log .
Updated ChangeLog
Delete travis . Jar
Updated version number to 0 . 23 . 0 - SNAPSHOT
Removing @ SuppressWarnings ( ) from BasicCacheTest
Add missing image for v1 . 2 . 2
Updated JavaApplicationStub , which runs both on Leopard and Tiger .
Remove false alarms that were used supported )
Prepare next development version .
Fix crash in previous commit ( # 8 )
Added tests for the pep8 - dpi function
Removed old libs
Updated version
Fixed asm jar version
Removing liquibase - osgi from parent project pom
Removed reference
Add preview image
Don ' t accept " Leereichen " , probably a typo of " Leerzeichen "
Handle accessor for the future pom .
Update README . Md
Upgrade gradle plugin to 2 . 2 . 0
Ignore Update ' modules / apps / marketplace / .
Setting version to 1 . 0 . 149
Add StoreMeta which is an empty error in the new dpi icon .
Simplifying the default welcome presentation
Added STORM - 1053 to Changelog
Ignore Update ' modules / apps / web - experience / layout / .
Add actor - webkit - devel dependency
Smack 4 . 0 . 2 - SNAPSHOT
Updated Blueprints libs
Removed unused class file
Ignore Vim / Vi backup & swap files
Setting version to 1 . 0 . 69
Rename file
Fix unbounded expansion warning
Ignore Update ' modules / apps / collaboration / notifications / .
Ignore Update ' modules / apps / collaboration / bookmarks / .
Optimize to_maven script
Bumped version to 0 . 57 .
Fixed var to be compatible with OS X
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Shut up linter
Upgraded the version in the parent pom references in our example components to 3 .
Remove unused import .
Remove old image
Removed Truth 0 . 24 + binary from third_party .
Make the dest log .
I don ' t really see a justification for doing a blocking write on close .
Add image for multi task constructor
Setting version to 1 . 0 . 116
Added changelog
Declare orientdb - core dependency to be of jar type
Updated changelog
Remove invalid lines
Only use iphonesdk8 . 3 .
Remove spurious regular expressions , fix some rules
Fix sync tests failure .
Delete demo - 0 . 5 . 0 .
Ignore Update ' modules / apps / foundation / configuration - admin / .
Build trove4j to be compatible with 1 . 5
Bluez doesn ' t handle disconnect while connecting well .
Fixed PY - 6543 Django manage . Py commands not working
Ignore Update ' modules / apps / foundation / petra / .
Add HADOOP - 9417 to CHANGES . Txt
GRAILS - 5691 - remove unused code
Temporaly remove yahoo tests
Adding a call to super . Close ( ) at the end of the buttons
Remove mongo . Jar
Don ' t maximize viewer ' s window by default
LPS - 44526 New User does not have administration permissions in New Site when made Site membership
Only run compile / unit tests in Travis
Add osx binary with callbacks ( intel only atm )
Fixed support for enumeration - seq
Ignore Update ' modules / apps / collaboration / bookmarks / .
Ignore Update ' modules / apps / foundation / portal - store / .
Fixed PY - 7294 Invalid warning to avoid anybody of transactions in default page .
Ignore Update ' modules / apps / collaboration / document - library / .
Ignore Update ' modules / apps / foundation / portal - template / .
Revert " Revert " Ask on demand in optimizeImports . . .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Use the latest lib snapshot
Suppress bad warnings
LPS - 52368 move icon
Remove sorting on post formats to fix # 284 .
Ignore Update ' modules / apps / foundation / frontend - css / .
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Prepare next release v0 . 87 . 1 - SNAPSHOT
Create zmnhnd . Xml
LPS - 2900 - Firefox ( and other browsers ) will only show the scrollbar when needed
Add Lucene version in plugin . Properties file
Use truth snapshot until truth > . 24 is released
Bump version
Removed grailsCentral ( ) from BuildConfig . Java
Bumped version to 0 . 8 . 0 - SNAPSHOT
Add image for multi task visualization
Fix doc for enumeration - seq
Setting version to 1 . 0 . 75 - SNAPSHOT
Download apk directly from here
Bump pegasus version to 5 . 0 . 5
Add java 6 to Travis build
Fixed typo in README
Ignore Update ' modules / apps / sync / .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Remove unused code instance in comments . Md
Ignore Update ' modules / apps / web - experience / journal / .
LPS - 58931 Don ' t render this
Added Artur to the contributor list
GRAILS - 11151 remove StatementCache from jdbcInterceptors property file .
Set correct permissions on the script .
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Ignore Update ' modules / apps / foundation / plugins - admin / .
Ignore Update ' modules / apps / foundation / configuration - admin / .
Set node size to 10 in NodePencil .
JAL - 35 Add image notes to non - proprietary licenses
Updated irc - api library to rev . 194 .
Ignore Update ' modules / apps / web - experience / asset / .
Remove redundant inclusion of module . Xml
Remove unused imports from AnimatorSet .
Ignore Update ' modules / apps / marketplace / .
Ignore Update ' modules / apps / web - experience / trash / .
Removed unused import from AnimatorSet .
Removed android - support - v4 . Jar .
Ignore Update ' modules / apps / collaboration / directory / .
Add accessor for buckets scanned in ScanData
Bump deb version
LPS - 45983 Add a line break since one depends on the other
Remove allow_failure jruby - 16 . 0 . 0 . 0
Switched version to 0 . 80
Ignore Update ' modules / apps / collaboration / notifications / .
Removing the accidentally committed screen dump .
Removed CamelChoiceWithManagementTest . Java
Fix travis . Yml .
Removing the accidentally committed image data
Fixed partial delete of previous log ( # 642 )
Ignore Update ' modules / apps / web - experience / export - import / .
Fixed pom . Xml issue with distributed sub - project
Remove @ Nullable from PreDexMerge . GetSecondaryDexDirectories
Don ' t build aggregated source jar .
Add " nodpi " to DpiTest Android . Mk
Ignore Update ' modules / apps / foundation / portal - security / .
Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode .
Bump version to 3 . 0 . 0 - beta . 1
SONAR - 4746 Remove comments when using it
Add gif to readme
Ignore Update ' modules / apps / foundation / frontend - js / .
Ignore Update ' modules / apps / collaboration / wiki / .
Revert " Revert " LPS - 54998 SF "
Add image for multi task action button button
Updated changelog
Don ' t run ` task ' s ` private ` files ( IDEA - compat )
Never show expunge on actionbar .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Setting version to 1 . 0 . 142
Ignore Update ' modules / apps / collaboration / message - boards / .
Fixed CHANGES
Don ' t include symbols in the jre 1 . 7 .
Fix the bug on Libsvm 3 . 14 that not free the memory allocated for sv_indices .
Ignore Update ' modules / apps / web - experience / site - navigation / .
Ignore Update ' modules / apps / collaboration / item - selector / .
Upgraded netty to 4 . 0 . 6
Gh - 31 - Removed increase phase argument
Remove the execute permission from source files
Add Jake Wharton to contributors .
Improve superclass to fix .
Updated AUTHORS . Md to include Vingles
Fix link name
LPS - 42723 Remove blank line
Updated FAQ
Ignore translator - web 1 . 0 . 0 prep next
Prepare release HikariCP - 1 . 3 . 3
Updated example image .
Revert " Bump major version to 2 . 23 "
Delete the ancient logo .
Add a libbase static depedency for aapt2 .
Added gitignore .
Fixing missing import
Upgrade gradle plugin to 2 . 2 . 0
Added all * specific files to .
Updates the ice4j library to r240 in order to fix an issue which could leave an initiated Jingle call connecting forever .
Add README to h2o_hadoop .
Updated credits
Added both versions of jflex
Ignore Update ' modules / apps / foundation / configuration - admin / .
Ignore Update ' modules / apps / web - experience / journal / .
Created tech - debt entries for all components and laboratory components .
Upgrade the wrappered gradle to 0 . 9 - rc - 3
Add a comment that this time requires compile . Properties
Fixed issue where history is no longer being added as well
Ignore Update ' modules / apps / collaboration / .
FIX Dashboard always display a scroll in IE7 ( cherry picked from
Add missing Cydia Substrate doc
Fix the gif to the Item
Remove sorting on text input so it doesn ' t set
Fix chmod .
Use the latest lib snapshot
Ignore Update ' modules / apps / foundation / contacts / .
Adressing review comment
Update history list with history
Git ignore Rplots . Jar .
Ignore Update ' modules / apps / collaboration / item - selector / .
Ignore Update ' modules / apps / web - experience / layout / .
Prepare for next development iteration
Fix typo in assets .
Removed some space at the end of alluxio_stop
Remove the empty file accidentally checked it with HADOOP - 7249 .
Fix dependency that didn ' t run the build script
Fixing VERSION . Txt
Adding cloud - azure module
Set correct permissions on the script .
- Add dummy file to " fuzzers " directory
Update changelog
LPS - 30588 Add toUnescapedModel to RepositoryModel
Revert " ignore gitignore .
Removed @ PrivateApi annotation ; not needed since PacketTransceiver is in the impl test , and therefor should not be accessed by the outside world
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
SONAR - 5561 Fix error in manifest in AndroidManifest . Java
Removing generic jar from the facebook dependency
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Adding Eclipse IDEA specific extentions to be ignored .
Ignore Update ' modules / apps / collaboration / bookmarks / .
Make uploadMavenCentral task , that encompasses other tasks
SONAR - 3862 Fix a bug in Firefox
Rename README - pt to README - pt .
HHH - 4088 - Session API does not throw an exception , but don ' t do anything it
Ignore Update ' modules / apps / web - experience / journal / .
Added cassandra - android - app .
Remove unused VM task from jar file
Fix missing import
Fixed readme
Remove Y
Deploy sites with the jar for tests .
Changed email address for 1 . 8 . 3 release
Create readme - ZH .
Fixed import error
Fixed typo in readme
Ignore Update ' modules / apps / foundation / portal - security / .
Remove the background from the RelativeLayout , allowing doesn ' t do anything or not set
Added STORM - 1596 ot Changelog
Remove jruby - 2 . 0 from allowed failures
Updated changelog
Improved favicon
Removed @ Nullable from AppCompatActivity # getData ( )
Updated version in README
Prepare release 0 . 19 . 2
Add API reference docs filtering for level 20
Add exe attribute for keywords . Txt
Push version to 14 - beta4 , 11261 .
Do not show separator specific of stream names .
Ignore Update ' modules / apps / collaboration / blogs / .
Remove ' performanceTest ' files from .
Create webapp / llap directory for MiniLlapCluster
Don ' t force refresh if data is taken from cache
Ignore Update ' modules / apps / web - experience / journal / .
Changed email address for travis .
Update Gradle release to 0 . 3 . 1
Setting version to 1 . 0 . 10 - SNAPSHOT
DO NOT MERGE - Small documentation fix for AudioManager . Java
Fixed bug in J2eeConfig . Xml as it was using the stream as it .
Upgraded http client to 4 . 3 . 6
Don ' t use 54321 in the jre 1 . 7 .
Added back + requirements to 5
Fix typo in changelog
Ignore configured dir
Update coverage to jdk 9 compatible asm
Temporarily set InconsistentArrays as a warning
Added STORM - 370 to Changelog
Ignore registry - api 1 . 1 . 0 prep next
Updated upgrading section
Raise CircleCI commit heap to latest java
Added missing params name
Remove executable bit .
Fix copy / paste error
Prepare next release v0 . 88 . 2 - SNAPSHOT
Add image on readme
Added Lenovo ThinkPad Tablet
Ignore Update ' modules / apps / foundation / hello - world / .
Fixed typo in changelog entry
Skip it ' s dependency name out to 1 . 6 . 1
Fix spelling mistake
Bump to version 1 . 5 . 1
Added Kasper to list of developers "
Temporarily disable performance tests
Updated changelog
Ignore Update ' modules / apps / foundation / frontend - js / .
SONAR - 6372 Remove unused import .
Update to latest android build tools
Remove impute . Flow from index . Yml .
Remove jdk 8 from travis build , because it always hangs / takes to long
Releasing OrientDB 2 . 1 - rc6
Changed build . Gradle to liquibase - core
Adding osx dsstore file to be ignored
Added intelliJ hidden files to gitignore
Fix latest plugin version
Removing the accidentally removed image
Fixed incorrect import in ping . Json
Upgrade gradle to version 2 . 1 . 0 to benefit from instant run .
Use the archive path so that it can be compatible with Gradle 3 . . .
Updated changelog
Fix bad height in p . Set ( )
Changed a typo from SHNAPSHOT to SNAPSHOT = )
Updated changelog
Ignore Update ' modules / apps / collaboration / item - selector / .
Bump build to 1 . 7 . 0
Incrementing minimal - json version due to serialisation bug in 0 . 9 . 2
LPS - 61440 remove jodd . Io
Update min sdk to 11 . 1 . 1
Remove unecessary < extension > element from maven - bundle - plugin
Catch more exceptions when restoring selection ( IDEADEV - 38870 )
Remove an unused code in the annotation that is not necessary
Remove spurious character
Mention changes to German rules
Ignore coverage report after web test failures
CLJ - 1329 - remove unused enum in PersistentVector . Cons ( )
Ensure only a single scroller animation callback per frame .
Remove unused files ( irrelevant )
Update build tools to 21 . 0 . 2 .
Removed unused import .
Deprecate return statement on boolean AP option
Add lint abort to demo ' s gralde build script , ps for travis - ci
Updated to classworlds 1 . 1 - alpha - 1
Updates the opus binaries for Windows to make an experimental 1 . 1 .
Adding TODO for system overview diagram
Combine BlockWorker and BlockDataManager .
Add files via upload
Added project example to libclang diagnostic function
Kill an un - needed / un - used __init__ .
Ignore Update ' modules / apps / foundation / portal - template / .
Adding * .
Fix bug 4099023 - Phantom clicks on some websites
Add video icon for Windows template
Increased max heap size when running tests
Add NOTICE file to AsciiDoc
Fix crash when trying to make sure when user is opened .
Fixed missing sys import
Add heap dump on OOM , see # 304
Removed unnecessary return statement
Update libwebp
Ignore Update ' modules / apps / marketplace / .
Fixed broken test data
Updating Alloy to rev . 81636
Make and level of Gradle jar for coveralls
Fix up change number .
Add ColeMurray to contributors
Change the size of the gifs
Ignore Update ' modules / apps / web - experience / xsl - content / .
Removed import .
Remove debug output which was accidentally be used .
Fixed missing padding in ElasticSearchIndex , fixes # 284 .
Add missing resource
Deploy org . Jetbrains . 4 .
Ignore Update ' modules / apps / foundation / frontend - js / .
Use Xcode 7 . 1 on Travis CI
Ignore Update ' modules / apps / collaboration / document - library / .
Bump up revision number .
Fix double counting of written modifier to avoid NPE
Fix bad id in ping . Json
Add file folder
Revert " Revert " AudioFlinger does not need LOCAL_STATIC_LIBRARIES in packages "
Ignore Update ' modules / apps / foundation / portal - security / .
Ignore Update ' modules / apps / web - experience / export - import / .
Updated copyright .
LPS - 43715 Basic build files ( empty until we start pushing the module ' s contents )
Remove newline at the end of manifest .
Added missing SPDY npn - boot . Jar file to Openfire lib / samples
Adding web version .
Added new migration config file
Removing duplicated arraycopy ( for arrayCopy )
LPS - 51081 Exclude custom build script , as it ' s needed "
Added a new high dpi icon , and an updated version of the medium dpi version .
LPS - 66860 prep next , use latest
Upgrade Maven Dependency Plugin to 2 . 8
Updates the chat room contacts background menu ( IDEA - ) .
Setting version to 1 . 0 . 68 - SNAPSHOT
LPS - 57377 Add property name for trunk "
Updated changelog
Maybe use markdown . . . Duh .
Add icons
We don ' t need Ivy 7 in tests . Xml
Fix NPE
Fix a compile - info option to fix bug
Prepare next development version .
Fixed bug with opcodes that use the video
Remove jdk 8 from travis build , because it always hangs / takes to long
Removed Thread . DumpStack ( ) calls used for debugging .
Ignore Update ' modules / apps / foundation / portal - settings / .
Fix a typo in ISurfaceTexture IPC code .
Don ' t use 54321 in the main package
Prepare release checkstyle - 6 . 14 . 1
Remove all line at the end of the file
Fixed bug in JedisCluster del command .
Revert " travis build check "
Updated README
Ignore editor backup files
SONAR - 5080 remove the last commit instance in order of building the anywhere
Fixed typo in org . 9 . CommandResult . GetServerUsed
Added STORM - 1058 to Changelog
Chmod a - x build . Bat - unix exec bit doesn ' t make much sense for windows ' bat
Remove unused variable in method
I trust Maven completely .
Removed extraneous import
Added lintVitalRelease as suggested by @ DimaKoz
Prepare for next development iteration
Add ptr - demo - 2 . 0 . 4 .
AS7 - 2310 rename jboss - admin .
Update contributor list , add yaphet , bjlindeqiang , dingjun , Dollyn , feilaoda
Add runner script for python workspace .
Add image for multi task constructor
Don ' t upload codecov results on travis
Add gitignore
Removed issue labels from the issues ' summary that were in the " Release 2 . 1 . 0 " help page .
Ignore Update ' modules / apps / foundation / hello - world / .
We now changed t set out twice . Xml ( ) at the end of the file
Update to latest support libraries v23 . 3 . 0
Revert " update to latest android - core - plugin "
Ignore Update ' modules / apps / collaboration / mentions / .
Updating Alloy to rev . 81636
Ignore IntelliJ backup files
Include PY - 6643
Ignore Update ' modules / apps / foundation / my - account / .
Ignore Update ' modules / apps / ip - geocoder / .
Removed old Javadocs .
Build scripts moved packaging
LEP - 4510 - Themes should contain styling for commonly used elements
Ignore Update ' modules / apps / collaboration / announcements / .
Add sample apk
Removed empty line method
Fixing license warning
Fixed typo in comment
Updated TODO .
Adding IntelliJ files to ignore
Fixed invalid link to the copy / robovm . G . "
Reduce fork count for tests
Remove unused import from TWLayoutManager
Rebuilds the Linux binaries of the PortAudio support from its latest source / r7982 .
Downgrading server to jersey 1 . 3 due to issue with loading of external jax - rs packages .
Add missing image for v1 . 2 . 2
MinecraftForge / FML @ d00feb58c762b0bbc506d79faf1ce40bc96732e9 Remove debug code that was causing console spam in Forge .
Corrected bitwiseNegate in operators documentation ( closes # 144 ) .
Ignore Update ' modules / apps / web - experience / layout / .
Prepare release checkstyle - 6 . 14 . 1
Fix unexpected rotation change when re - enabling auto - rotate .
Fix an issue where disabled if we ' re already found ( IDEA - 157793 )
Delete demo2 . Jpg .
Maybe I undo this in the Note model
Changed build . Properties to 7 . 1 . 1
Set limits . ToString ( ) and InvalidPathException for Uploads
Fix ref to lucene . Apache . Org
Ignore Update ' modules / apps / foundation / contacts / .
Fixed my bug in svm . Cpp
Prepare release checkstyle - 6 . 13
Fix typo in parallel config
Updated changelog for 2 . 1 . 0 - stable .
Ignore Update ' modules / apps / collaboration / document - library / .
LPS - 33648 - Remove the constraining width from AutoComplete suggestions popup
Remove the TMDB API Jar from the realm
Updated changelog
Update applet zip
Added some image to the new dpi icon .
Removed redundant directory src / tests from bbb - client
Add " Testing " target ' target to DataView .
Remove @ nosideeffects from DataTransferItem . Prototype . GetAsString ( )
LPS - 57173 Wake all blacklist property for Oracle 1 . 1 or SNAPSHOT
Help ID ( PY - 4116 )
Ignore Update ' modules / apps / collaboration / directory / .
LPS - 60633 ( SERVICE ) move service file
Ignore Update ' modules / apps / collaboration / quick - note / .
Improves the hotplug response times on Windows which may be noticeably prolonged due to thread scheduling in cases of Windows Multimedia reporting lack of a device driver .
Ignore Update ' modules / apps / sync / .
Changed build . Gradle ref to build . Xml
Don ' t require old maven
Fixed a bug where HttpMessage . RemoveHeader ( ) even if we are done with a message
Don ' t show empty by default event on non - ARC
Updated changelog
Added logo to README
Fix # include for the images that was I noticed doesn ' t get it instead of install .
Add constant for rstudio user identity display
Dialog should start the SSL engine ( IDEADEV - 6618 )
Fixed a typo .
Added all Eclipse files to .
Ignore Update ' modules / apps / collaboration / document - library / .
Updated gitignore to ignore hprof files
GROOVY - 2195 ' s patch created a regression , so I ' m reverting the previous change
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fixed a subtle bug I happened to introduce last night .
Remove patch verb , not supported by HttpUrlConnection
Do not show separator by default
Fixing breakage with previous API
Updated src / java / com . 2 . 4 .
Fixing line endings for .
Updated CHANGES . Txt for Esperanto .
Follow / unfollow API
Add change .
Move PointSetTest to the same package as PointSet .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Avoid compiler button out on default menu
Ignore VIM swp files for git
Move maven project to test
Ignore Update ' modules / apps / foundation / portal - settings / .
Use Android Gradle Plug - in v2 . 3 . 0 - alpha6
Bump common for 4 . 2 . 2 ref
Fixing an issue with that damn bundle plugin again .
Added libutils dependency for libandroidfw host build .
Updates the background color to be consistent with appended Messages ( LSR ) .
Prepare for next development iteration
Ignore Update ' modules / apps / web - experience / product - navigation / .
Removing useless semicolon .
Fixed text error in p . Java ( # 63 )
Fix compilation in js script
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Implement cursor to the getCoyoteResponse ( ) method
Ignore Update ' modules / apps / collaboration / announcements / .
Upgraded commons - plugin from 2 . 0 - jsr - 03 .
Add JDK 8 to Travis build .
Ignore Update ' modules / apps / foundation / users - admin / .
Remove checkThread that is null .
Add IDEA project files to .
Ignore Update ' modules / apps / foundation / login / .
Ignore Update ' modules / apps / foundation / users - admin / .
Add icon for free documentation .
Added link to keep latest repository .
LPS - 57119 Only strip fully qualified classname when it ' s NOT a literal string
Delete test file
MAHOUT - 1775 FileNotFoundException caused by aborting the process of downloading Wikipedia dataset
Push version to 13 . 1 , 244 .
Expanded the ZAP help sections corresponding to Authentication and Users .
Trying should fix the container - based builders .
Fixing transitive - ness of provided
Prepare release acra - 4 . 6 . 2
Ignore pact - tests files
Save watches per configuration on Android 2 . 2 ( PY - 8347 )
Removed log4j . Properties from test - pom . Xml
Cleaning up 1 . 8 . 6 warnings
LPS - 24280 add comment
Updated CHANGELOG . Txt .
Fixed invalid code
Ignore IDEA project files
Update Android plugin to 1 . 1 . 0
Add missing test resource ( # 2 )
Don ' t track ant - debug .
Add file folder
Update native lib to 3 . 2 . 2
Update gradle to 2 . 0 . 0 - rc4
Aded STORM - 760 to Changelog
Replace the margin of the end of copyright where they don ' t do anything
Ignore Update ' modules / apps / collaboration / ratings / .
LPS - 61556 Move css files
Add image for simplecursoradapter
LPS - 55275 Exclude unused war
Ignore Update ' modules / apps / foundation / monitoring / .
Updated ChangeLog
Removed old lib
Setting version to 1 . 0 . 92
Updated cacheword for 3 . 0 . 5
Fix NPE when trying to be TOUCH_DONE_MODE when calling doDoubleTap .
Ignore Update ' modules / apps / collaboration / ratings / .
Adds device uid for wmme and dsound devices .
Fixed a typo in the drawer .
Ignore Update ' modules / apps / foundation / portal - store / .
Changes the hangup sound to a more subtle one ( b / 3116268 )
Add OpenDictionaryAPI library case
SONAR - 45870 Remove comment that doesn ' t exist because it does not exist
Update upto gradle plugin 0 . 2 . 2
Move pyunit to NOPASS since I figure out the language of the numerical inaccuracies .
Make sure that this doesn ' t fail on violations
Add an option to selecting the path of cmdline files via versionspecificmoddir .
Don ' t reference the enclosing type instance when it ' s not used ( memory optimisation )
Can ' t have empty words on navigation languages
Remove commons - 2 . 5 . 5 to jar due to standalone 2 . 5 . 2
Handle toString ( ) method from shutdown ( ) method
LPS - 51081 Move stuff out
Updates the jain - sip libs to match the versions on the web site ( ver 1 . 0 . 96 ) .
Changed heading name
Bump common for 4 . 2 . 2 ref
Move rebalance scripts to bin directory .
Add release date
ZEPPELIN - Updated allowed tests in .
Set correct permissions on the script .
Remove unused import .
Updating Alloy to e79a782 ; LPS - 13554
Add new contributor
Adding empty migration file
Updated pldroid - player - 1 . 1 . 5 .
Remove unused config in build
Updated libs .
Delete unused protected in method class
Adding gitignore .
Prepare 0 . 7 . 0 release
Fixed a typo in the server . Xml ( not ) for the BUILD file )
Tell Travis to stop emailing us .
LPS - 45755 - Add ' portal - acceptance ' component
Make the dest dir
Push build .
Updated version to 0 . 4 . 5
Add header file
Bump common for 4 . 2 . 2 ref
Updated es upstream to fix flaky DeallocatorsTest
LRQA - 28621 prep next , use latest
Updates the SC logo in the model Audio Session API ( WASAPI ) backend .
Ignore Update ' modules / apps / web - experience / export - import / .
Fix AS project naming .
Remove unsed check for simulator
Changed the size of ijar_test
Fixed EDU - 158 Problems with tasks
Correct the typo in typo in bbb - web .
Bumped parent versions from 2 - SNAPSHOT to 2
Ignore Update ' modules / apps / web - experience / trash / .
LRQA - 64991 Remove mail portlet from build as it fails inconsistently on jboss / wildfly
Ignore Update ' modules / apps / web - experience / rss / .
Removed extraneous JAR from spring - core - 2 . 0 . 2 .
Fix up the makefiles and some samples .
Removed a System . Out
Rename Filter to FilterActivity to prevent name collision
Released 1 . 5 . 1 - SNAPSHOT .
Removed the accidentally checked file in the app project
Updated reference to oc - library
Updating Alloy to e79a782 ; LPS - 13554
Updated copyright .
Updated changelog
Remove myself from Travis configuration .
MinecraftForge / FML @ d00feb58c762b0bbc506d79faf1ce40bc96732e9 Remove debug code that was causing console spam in Forge .
Don ' t include arrays in emulator ( fixes # Thejas Nair )
Update the MSI installers .
Remove debug logging .
Make FileStack by default
LPS - 46869 On a smartphone , excess white space appears in Site Administration for Site Memberships and Site Teams portlets
Update to latest android build tools
Updated Studio
Ignore new .
Updating version to 1 . 0 . 1
Remove unused import logs .
Removed empty class file .
Updated changelog
Fixes a minor bug in ParticleSystem . Reset ( ) , see # 642 )
Removed com . Sun . Impl . Arrays import
Add - - Just to the build . Gradle file
Don ' t need performance errors
LPS - 43188 - Save original IORequest object in case we need to access it
Fixing transitive - errors in distribution
Removed some empty line
Ignore Update ' modules / apps / foundation / portal - lock / .
Ignore Update ' modules / apps / marketplace / .
Added STORM - 833 to Changelog
Removed @ Repeat ( 100 ) from BasicCacheTest
Fix AutoCraftingTable not respecting the doRemove flag .
Fixed classpath reference in buildscript dependencies
Ignore chat - web 1 . 0 . 0 prep next
Corrected " rb " in hdr_histogram_format_example . C . Service ( ) .
Restore forkEvery = 1 . . . Still troubleshooting build issues
Make finish ( ) with Resources . AsByteSource to make new exception message
CAMEL - 7209 Fixed the unit test message in order so that it does not do what ' s
Added a line , just to see if DC manages to monitor changes again and build groovy as it was the case before the move . . .
Fixed class name for smart enter test
Update multiwords . Txt
Fix bug in block ( )
When marking a message as well
Remove warning that doesn ' t like it instead of java .
Don ' t accept " Leereichen " , probably a typo of " Leerzeichen "
Fix typo in spec for Windows types as well .
Update archaius2 to 1 . 7 . 5
Prepare version 20 - beta3 .
Removed unused resources .
Remove maven release plugin version declaration to make eclipse happy
Remove openjdk6 from Travis CI config
Ignore Update ' modules / apps / web - experience / staging / .
Moved runit to NOPASS .
Remove sleep 3600 .
Removed test file from test ( thanks to exist .
Prepare release 0 . 8 . 2
Ignore Update ' modules / apps / collaboration / message - boards / .
LPS - 25268 Tags overlap Wiki Edit / Details / Print
Bump version number
Fix leak of stackTrace in java / lang / Throwable .
Fix NPE in moveSharedElementsToOverlay
Revert name name name to 7 . 1 . 1
Bump version code to 2 . 5 . 0
Add # 5125 to CHANGES
Removed empty apk
Remove unused import
Add accessor for buckets scanned in ScanData
Updated the version number from v1 . 3 . 2 to v1 . 4 . 0
Don ' t run jars anymore .
Remove ' buildSrc / ' folder from .
Removed warning that doesn ' t like anything
Bumped version .
Setting release version to 4 . 0 . 0 .
Ignore Circle CI .
Remove one from one from java
Don ' t add task instead of build
Do not set manual id for now
Exclude groovy - all - tests jar during assembly
Ignore Update ' modules / apps / web - experience / asset / .
Remove screenorientation on UCropActivity ( # 8 )
Build fix fix for Android 2 . 6
Updated CHANGES file to indicate 9 . 1 . 1
Upgrade randomized testing to 2 . 0 . 12
Add ` repositories { mavenCentral ( ) } ` to Gradle instructions for completeness
Fixed test data for duplocator test
Remove unnecessary viewType assignment in LayoutParams
Added professional image for parallel gateway process
Remove spurious line in the theme list
Fix doc link to indicate installed issue .
Updated changelog
Ignore Update ' modules / apps / web - experience / asset / .
Updated version
Remove the xwalk_core_library ' s ' vs . Release '
Modified url for issue tracking to directly show tickets for the component .
Ignore Update ' modules / apps / foundation / portal - lock / .
Move DeepLearning . Java to h2o - algos .
Fix copy / paste error in isKeyguardLocked ( )
Remove unused files .
LPS - 62733 add build . Xml
Add words
Removed unnecessary constructor comment
Added translation using Weblate ( Uzbek )
Fix copy / paste error
MAHOUT - 1775 FileNotFoundException caused by aborting the process of downloading Wikipedia dataset
Fix indirect misuse of Android . Sh
Updated changelog
Removed net_bt_stack group '
Update to latest android iconics - core
Fix pom . Xml by default - compiler .
LPS - 52390 remove unnecessary z - index .
Ignore Update ' modules / apps / foundation / users - admin / .
Run the same package as it instead of the build projects .
Add " perflib " from tools - base module to build
Remove the file file that should be created by default
Bump version number
Mention changes to German rules
Add changelog for 1 . 3 . 1
Fixed build .
Ignore Update ' modules / apps / foundation / expando / .
Modify install_fbthrift .
Ignore output from Latex
Modify Makefile
Add extra link at the README list
Ignore Update ' modules / apps / marketplace / .
Removed some system tag .
Updated README for 0 . 6 . 7 . 2
Add tools version .
Ignore Update ' modules / apps / web - experience / product - navigation / .
Fix test failure for gh - core .
Prepare release HikariCP - 1 . 3 . 9
" Updating samples to reflect recent changes in JDBC artifacts .
Ignore Update ' modules / apps / web - experience / staging / .
Include JDK 8 for Travis .
Remove spurious comment for now .
Remove unused import in BufferUtils
Add flags needed to switch Jack to 1 . 8 for CTS targets
LEP - 5049 Rolling back , see comments on JIRA
Increasing uninterrupted sleep flag to need its process
Update win64 nattttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttive
Removed old file
Ignore Update ' modules / apps / web - experience / export - import / .
Add image for multi - runner README
Update linux - amd64 to 3 . 0 . 4 ( native )
Reverted the repetition rate of the off - the - rote prompt
Add header image
Ignore Update ' modules / apps / foundation / portal - cache / .
Update packer ng jar to 1 . 0 . 2
Added DataGrip to the list of supported languages
Change the default release scope to be patch
Fix mCoveredFadeColor setter for AndroidNeverlinkAspect .
Ignore Update ' modules / apps / foundation / portal - store / .
Upgrade gradle - wrapper to 2 . 10
Ignore Update ' modules / apps / foundation / portal - settings / .
Removed numThread ( PY - 22220 )
LPS - 15720 Add terminated to bad column names
Prepare for next development iteration
Removed new import .
Ignore Update ' modules / apps / collaboration / wiki / .
Added a Composite Configuration Diagram to use in the Wiki .
Always refresh pane value is open ( IDEADEV - 22794 )
Push version to 14 . 0 . 2 , 11267 .
Update applet zip
Don ' t show empty Python code button by default
Remove unused files .
Removed @ Repeat ( 100 ) from BasicCacheTest
Changes the incoming message alert to a less intrusive sound
Remove ES Client . Close ( ) .
Add mention of visibility rule
Undo the unused code
Ignore Update ' modules / apps / foundation / web - proxy / .
Added missing eclipse config file
Fixed test data according to missing test list in unit tests
LPS - 54984 Fix warning
Move ChildBrowser . Java again
Update win64 nattttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttive
Added files via upload
Revert " Revert " Provide " testIteratingWithList " test "
Rename LICENSE to LICENSE - 2 . 0 .
Update readme to reflect LayerDrawable support in README
Chmod a - x build . Bat - unix exec bit doesn ' t make much sense for windows ' bat
Added pr 53 to changelog
Add missing documentation
Update demo
Do not configure Undertow listeners as reversed with the reverse proxy
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Make ObjectId Serializable JAVA - 109
Updated reference for 1 . 0 . 8
Add FORCE index for notificationQ
Ignore Update ' modules / apps / web - experience / site / .
Add MIT TODO . Md to added TODO .
Ignore Update ' modules / apps / foundation / frontend - js / .
Fix difficulty for Visitor # 213
LPS - 54552 avoid duplication of breadcrumb now that it is a portlet
Ignore Update ' modules / apps / foundation / frontend - js / .
Fix loosing default profile
DO NOT MERGE - Small documentation fix
ZEPPELIN - 1308 the version of threads so that we can need to pass "
Adding myself to Travis notifications
Setting version to 1 . 0 . 6
Incremented the version code of the sample project for GPlay upload .
Remove boost iostreams include from FilePath . Hpp
Updated icon
Completely reverted change on log4j dependency .
Fixed build . Properties
Rename the generated stuff to the correct package failure .
Fixed a bug where HttpMessage . RemoveHeader ( ) even if we don ' t like twice ( IDEADEV - 38870 )
Fix typo in SASL name in graylog2 example
Remove Thumbs . Db from gitignore
Removed unused enum value in ` BuildRuleSuccess . Property ` .
Starting 0 . 6 . 1 - SNAPSHOT
Add class diagram for free version .
FIX # 937 requires typo in AUTHORS . Md .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Adding files via upload
Add slack notifications to travis .
Remove @ PrivateApi annotation ; not needed since PacketTransceiver is in the impl package , and therefor should not be accessed by the outside world
OpenGL GLSurfaceView apps don ' t draw an exception if we don ' t do an the headless class .
Ignore Update ' modules / apps / foundation / portal - remote / .
Fixed BufferedTokenStream . Reset ( ) returns true call in the grid view
Fix an problem with backsided objects .
Skip integration tests in pom . Xml
Ignore Update ' modules / apps / collaboration / item - selector / .
Updated travis . Yml in Travis
Update to latest android gradle build tools 2 . 0 . 0
Ignore Update ' modules / apps / web - experience / product - navigation / .
Revert " Revert " Bumping version to 0 . 2 . 2 - SNAPSHOT 1 . 0 . 2 jar
Ignore Update ' modules / apps / foundation / portal - search / .
Fixed typo in comment fix
Fix extra dependency in manifest .
Add missing return type in ViewOverlay . Clear ( ) .
Add source encoding to pom . Xml
Changed default param name for CASSANDRA - 3718 .
Ignore Update ' modules / apps / collaboration / message - boards / .
Add changes of CHANGES . Txt for CASSANDRA - 10000
Fixed missing return statement which was not needed when it is disabled
Add a probable typo in getBitmapWithFilterApplied
LPS - 56179 Create a new ResouceBundle for item - selector - web
Have the comparison script handle app failure gracefully
Use Gradle 2 . 11 .
Add STORM - 1964 to changelog
Remove old jar files
Upgrade netty - build to 12
Update to latest android build tools
Added Oracle JDK 8 to .
Mark getConnection ( ) that takes a end of time .
Remove spurious comment in svm . Cpp
Revert " added intellij specific file to .
Updating history
Ignore Update ' modules / apps / collaboration / blogs / .
Make BlockSuppressalStatus constructor public
Help ID ( PY - 4116 )
Fix # 109
Revert minSdk back to the parent pom
Add ' Server ' keyword to title
Reordering the build repositories in the hope that this fixes the jenkins build .
Build script fix
Add test data for linux
Remove TODO from pom . Xml
Ignore Update ' modules / apps / web - experience / rss / .
Added missing sigar imports
Bump version to 0 . 6 . 1 .
Ignore Update ' modules / apps / collaboration / document - library / .
Add missing @ Override annotation ( # )
Added ' Testing Applications ' and dictionary in voldermort - web .
Updated studio
Ignore Update ' modules / apps / foundation / contacts / .
Update changelog for 0 . 9 . 2 .
Fixed type signature for abs ( ) as they don ' t reset too e .
LPS - 23695 Missing language key in User Statistics
Update linux - x86 - 64 natives
Remove ' subprojects / * / ide ' entry from .
Move this to PASS .
Updated the OrangeExtensins . Jar library ( compiled with java 1 . 5 ) .
Don ' t reference the enclosing type instance when it ' s not used ( memory optimisation )
Add jar file
Updated documentation on git rather than better ( * )
Fix warning
LPS - 57119 Only strip fully qualified classname when it ' s NOT a literal string
Updated icons for chat item ( IDEA - 125223 ) .
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Remove unnecessary empty line .
Updated change list
Updating Alloy to 2 . 0 . X c6d25c7
Reordering the build repositories to start the pom .
Fix copy & paste error in isKeyguardLocked ( )
Removing @ Overrides from method that implements interface if it is used .
Don ' t hardcode IP address for http tunneling
Ignore Update ' modules / apps / foundation / portal - store / .
Added Google to license .
Added symbolic link to title
Add support version for travis .
Debug test_RF_mnist8m_s3n - > mnist8m_RF_bench
Upgraded http client to 4 . 5 . 2
Bump deb version
Make an internal class package private ( cherry - pick to master to unblock all )
Add image for multi task visualization
Added translation using Weblate ( Polish )
LPS - 63462 update jar
SONAR - 4636 Bind handling of branding resources to a later phase of the build
Ignore Update ' modules / apps / collaboration / bookmarks / .
Changed build tools to 2 . 0 . 2 .
Move worldedit . Properties to defaults folder so it extracts properly
Delete unused enum value in ` BuildRuleSuccess . Property ` ( closes # 47 )
Fixed typo in benchmark .
LPS - 54811 Export the proper datasource in order to get the proper transaction management within the new OSGi modules
Prepare release otto - 1 . 1 . 0
Remove old semicolon
Removed android . 26 . Properties from pom . Xml .
Bump common for 4 . 2 . 2 ref
LPS - 46809 Add a line break since we ' re about to manipulate the var
Update gif
Update README . Md to show version 0 . 3 . 3 .
Update NEWS
Ignore Update ' modules / apps / foundation / frontend - editor / .
HIVE - Re - Don ' t need this
Ignore Update ' modules / apps / foundation / users - admin / .
Change width of drawer to 320dp
Upgraded SVNKit to 1 . 0 . 1
Added STORM - 794 to Changelog
Ignore Update ' modules / apps / foundation / xstream / .
Moved the Swing Model test to swing project
Added jars to build . Gradle
Add link to 0 . 8 . 4 release index
Updated reference to oc - library
Remove useless semicolon in StringUtils
Added helper method for builder implementations
Fixed typo in documentation index
Fix typo
Make RCTRootView propage motions
Allow leading spaces in unassigned shards lines
Revert " Caching dependencies to speed up PR builds "
Ignore Update ' modules / apps / sync / .
Make Tachyon - Perf a new dependency in POM
Updating Alloy to 5ab6d2d ; LPS - 36519
Ignore Update ' modules / apps / marketplace / .
Ignore Update ' modules / apps / web - experience / staging / .
Updating build tools to 23 . 0 . 1
Fixed bug where splitframe does not return one by default
Ignore gen ' s grunt - buildpackage
Don ' t run performance tests in parallel .
Include stdio . H in 1 . 7 .
Upgraded Mockito to 1 . 9 . 0 .
Fixing the build in pom
Added description for Grails 1 . 6 .
Changed icon to indicate view icon
Removed test file
Added case of Decimal128 to BsonBinaryReader # skipValue
Fix isUsbMassStorageConnected ( ) will always return true
Ignore Update ' modules / apps / foundation / portal - settings / .
Prepare for next development iteration
Bump release number to 1 . 2 . 1
Add image for simplecursoradapter
Updating Alloy - more updates to the async ajax patch on YUI ( IE bug fixes )
Removing the secret key .
Ignore Update ' modules / apps / web - experience / rss / .
Added jetty test to UTF - 8
LRQA - 20520 prep next , use latest
Update support version
Fix double checked locking concurrency issue .
Fix NPE in PackageParser
Changed travis config to test builds in Travis CI
Updated gitignore to ignore hprof files
Updated changelog
Updating Alloy to rev . 81636
LPS - 27739 Site admins without Control Panel access cannot manage page or site data
Change build tools version to 23 . 0 . 0
Updated changelog
Updated banner to show 0 . 63 - Beta
Update gif previews
Setting version to 1 . 0 . 79 - SNAPSHOT
Ignore Update ' modules / apps / foundation / login / .
Added STORM - 1182 to Changelog
Added STORM - 437 to Changelog
Replace Future < T > with T in EJB implementation
Bump version
Fix camel - test dependency
Ignore Update ' modules / apps / collaboration / wiki / .
Add STORM - 2054 to Changelog
Ignore intelliJ files
Adding OSSMETADATA for NetflixOSS tracking
Updated label to 0 . 81 - beta - 2
Updates build tools and compile version
Fixed a bug where the notification scroller is disabled .
Dialog should start the SSL engine ( IDEADEV - 38870 )
Add image for multi - client
Ignore Update ' modules / apps / web - experience / staging / .
Fixed wrong code in readme
Add text icon for free app .
Switch master to 4 . 1 . 0 . BUILD - SNAPSHOT
Changed name for me
Ignore Update ' modules / apps / foundation / portal / .
Create TestUtils
Only use jdk8 in travis
Allow failures of jruby - 20mode for now .
GRAILS - 5691 - remove some code that was accidentally started in the text
Fix build . Js with fixed bug
Ignore Update ' modules / apps / collaboration / message - boards / .
Fix typo in setLength
Added launcher icons for ldpi and xxhdpi densities
Upgraded maven - javadoc - plugin from 2 . 7 to 2 . 9
Added PyDocstringTest to all tests suite
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Set version for 0 . 9 . 5 release
Added tmp to ignored dirs
Ignore Update ' modules / apps / foundation / frontend - js / .
Add overlay for cpp subproject
Add copy to create a subset of the orginal dataset
Removed margin public from py from py config
Ignore fetched JVMLS files
Add image for action bar action button
Fixed copy and paste error in debugger
Reduce noise by maven - javadoc - plugin
Update gitignore to ignore 0 . 8 . 2
Ignore Update ' modules / apps / foundation / my - account / .
Updated animated gif
Add todo comment
Remove callbacks in onDetachedFromWindow , fixes b / 7465673
Added a . For 0 . 8 . 0 Release the .
Add config for Travis CI
Fixed # 76 decrease default location into default
Ignore Update ' modules / apps / sync / .
Updating readme in prep for 0 . 6 release
Add clover license
Removing default hack to fix value ( PY - 15907 )
Upgrade JUnit to 4 . 12
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Updated es upstream to fix flaky DeallocatorsTest
Ignore Update ' modules / apps / collaboration / bookmarks / .
Removed org . Jetbrains . Jet exception in proguard build
Set version for 2 . 7 . 2
Ignore Update ' modules / apps / web - experience / export - import / .
Setting build number to 4 . 0 . 1
Updates the chat room contacts parameters when they don ' t have been read .
Ignore Update ' modules / apps / collaboration / ratings / .
Ignore Update ' modules / apps / web - experience / layout / .
We don ' t need Ivy 7 in tests . Xml
Ignore Update ' modules / apps / collaboration / mentions / .
Do not encode sendRedirect URLs
On behalf of Vincent Lucas , commits a fix to the calculation of the Last SR ( LSR ) timestamp for the Sender Report RTCP packet .
Added STORM - 370 to Changelog
Don ' t show K9mail - errors as move / copy .
Don ' t maximize viewer ' s parsing by default
Fixing Node # each semantics so we don ' t do anything
Fix typo in installDeps
Ignore Update ' modules / apps / web - experience / asset / .
Update gradle to 2 . 1 . 2
Fixed a bug .
Add ptr - demo - plugin .
Don ' t allow onBackPressed to be called when AstridActivity is clicked
Add dashboard_widget_default_cache_time option .
Ignore Update ' modules / apps / sync / .
Ignore Update ' modules / apps / web - experience / asset / .
ACT - 401 Added cxf module to the checkmule profile
Fixed a bug in canAddToLastInputMethod ( )
Ignore Update ' modules / apps / collaboration / bookmarks / .
Setting version to 1 . 0 . 103
Bump version to 0 . 7 . 0 - SNAPSHOT
Remove unneeded inclusion of rs_math .
Added missing SPDY npn - boot . Jar file to Openfire lib / dist
Updated codegen dependency
Ignore Update ' modules / apps / foundation / portal - security / .
Update RPM bundled JRE to java 7u40 , refs # OF - 513
Update build . Gradle
Update TODO
Ignore Update ' modules / apps / collaboration / blogs / .
Add osx w / allowed failure on Travis
Remove debug statement
Mention 5950 in documentation .
Ignore Update ' modules / apps / foundation / frontend - css / .
HHH - 4088 - Session . GetSession should always return sessions from 10 . . .
Oops , forgot a bad fields as some exception before running in sync
Ignore local - debug files
Fix builder icon
Use the latest lib snapshot
Bump version
Revert " Caching dependencies to speed up PR builds "
Added * .
Move DeepLearning . Java to ActivityCompatApi23 . Log ( # 582 ) .
Removed a redundant call to setDefaultButton
Ignore Update ' modules / apps / foundation / portal - search / .
Added files via upload
Fix trivial equals implementation
Suppress onAttach deprecation warning in ReaderPhotoViewerFragment
LPS - 47791 - Select All checkbox not displaying ( occurs in WC and DM )
Ignore Update ' modules / apps / sync / .
Ignore Update ' modules / apps / web - experience / site / .
Ignore Update ' modules / apps / web - experience / portlet - configuration / .
Fix syntax error in documentation list
Add missing image for v1 . 5 . 2
Ignore Update ' modules / apps / foundation / portal - remote / .
Setting version to 1 . 0 . 148 - SNAPSHOT
Fixed CCE ( EA - 38206 )
Added constructor that takes the parent class loader
Removed unused pattern .
Fixed javadoc for zipalign path getter for initSql .
HIVE - 2550 Provide jira_base_url for improved arc commit workflow
Fix an issue where HttpMessage . RemoveHeader ( ) leads to a dangling pointer
Ignore Update ' modules / apps / collaboration / blogs / .
Add STORM - 1112 to CHANGELOG . Md
Added a Composite Configuration Diagram to use in the Wiki .
Replace registerForEvent ( ) with equivalent call that makes registerForEvent
Updated changelog
Ignore Update ' modules / apps / collaboration / directory / .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Updated changelog
Ignore Update ' modules / apps / marketplace / .
GRAILS - 5691 - remove some code that was accidentally left in a warning
Removed bottom padding for Nullable ( # 1039 )
Ignore Update ' modules / apps / foundation / frontend - theme / .
Removed mention in readme
Removed android library file
Add TODO to jetbrains . Dic
Ignore Update ' modules / apps / collaboration / blogs / .
Make sure that there doesn ' t run twice .
Added preview image
Added a sample image image .
Added gstreamer dependency
Fix typo in typo in bbb - conf
Remove sudo
Updated changelog
ParserRuleContext . GetChildCount ( ) cannot CASSANDRA - 4088 , PY - 12782 )
Added missing sigar libraries
Updated FAQ
Ignore Update ' modules / apps / collaboration / wiki / .
Ignore Update ' modules / apps / foundation / portal - remote / .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
LPS - 68862 - Add new property to ignore list
Ignore Update ' modules / apps / collaboration / bookmarks / .
Moving STUN sources from Openfire main project to bin .
Fixed incorrect variable method for now ( PY - 12901 )
Added description to project
Don ' t upload tests generated by default .
Update gradle version
Remove an unused enum value in ` BuildRuleSuccess . Property ` .
GRAILS - 5691 - remove some code that was accidentally left if it is open ( IDEA - 157793 )
Move this test to standalone , as it ' s useless in core ( no languages available there )
Add STORM - 1453 to changelog
Added class diagram for free version .
Fix bug 5244365 - Don ' t populate a ViewPager in onAttachedToWindow
Fix a bug where HttpMessage . RemoveHeader ( ) leads to a dangling pointer in the
Don ' t force refresh if data is taken from cache
Ignore Update ' modules / apps / web - experience / nested - portlets / .
Make mSessionCallback null in TvView . UnbindTvInput
Not reinitializing the backing arrays in OperatorZipIterable
Add javadoc plugin .
Fixed error .
Ignore editor backup files
LRQA - 25866 Add properties to designate tests as CE or EE only
Make spark . Response ' s body so that we don ' t do it , but we ' re null .
Fixed EDU - 158 Problems with tasks
Removed backport jar , as its no longer needed
Fix build . Json
Fixed spelling mistake
Don ' t need pthread
Ignore Update ' modules / apps / foundation / portal / .
Add STORM - 1112 to CHANGELOG . Md
Remove debug statement so I can don ' t do anything yet .
Fix small bug where DefaultChannelFuture . IsSuccess ( ) instead of the status activity instead of current .
Ignore Update ' modules / apps / foundation / map / .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
SONAR - 5080 remove comments in minimized JS
Ignore Update ' modules / apps / foundation / portal - search / .
Updated changelog
Make spark . Response ' s body method public ( # 8 )
Updated changelog
Update main . Md doc
Prepare next dev iteration
Remove unused imports
Update the name of the date .
Ignore Update ' modules / apps / screens / .
Set correct permissions on the script .
Add build . Properties again
Added project name to
Ignore Update ' modules / apps / foundation / configuration - admin / .
Fixed typo in index
Fixed issue string
Remove warning on non - existent method
Smack 4 . 1 . 2 - SNAPSHOT
Fixed typo in ' var '
Updated version to 1 . 0 . 0 for pending release
Updated image for 1 . 5 . 2
Don ' t force all if data is taken from cache
Increased max number of items rendered from 3 to 5 .
Remove extra newlines at EOF
Ignore Update ' modules / apps / foundation / portal - settings / .
Updated reference to oc - library
Rename Filter to FilterActivity to prevent name collision
DO NOT MERGE - Updated textfield ( PY - MERGE )
Fix Ryan & screenshot in CONTRIBUTORS . Md
Ignore Update ' modules / apps / collaboration / item - selector / .
Don ' t force refresh if data is closed
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Add " tuple " and " tuples " ( fixes # 394 )
Add build tools to README
Upgrade Anonymous Usage Statistics to version 1 . 1 . 0
Add STYLE enum for functions
Added eclipse generated files to .
Fix compile error in previous commit ( fixes # 330 )
Ignore Update ' modules / apps / foundation / portal - instances / .
Add STORM - 1535 to changelog
Don ' t filter some header files on portlets
Upgraded http client to 4 . 5 . 23
Updated gitignore .
Added STORM - 370 to Changelog
Prepare next version ( 0 . 3 )
IDEA - 126585 " Evaluate Code Fragment " every each thread
Fix go link in README . Md
Added needed support to exclude certain databases from support for allowGeneratedIdInsert .
Ignore Update ' modules / apps / collaboration / flags / .
Fix syntax error in wercker . Pack .
Made tests , fork isn ' t run it .
Added debug printing content of all incoming packets
Deploying more artifacts .
Update apk
Publish license ( PY - 65 )
Removed support library from the StackBlur library
Ignore Update ' modules / apps / web - experience / asset / .
Fixed a typo in the server that was necessary so that we can use the getSourceName ( ) in AndroidManifest series plot
Make an internal class package private ( cherry - pick to master to unblock all )
Added image for multi task visualization project .
Remove dependency and build from build build .
Don ' t force refresh if data is closed ( IDEA - 157793 )
Removes empty line at the end of install .
Fix import in wrapped documents
Prepare release 0 . 17 . 2
Removed the newline in the end of the file
Finished collection / list separation
Don ' t publish versions ( prevents modules instead of case )
Set correct permissions on the script .
Fix missing break in Icon class
Fixed lost language annotation for Linux and he
Update the changelog file name .
Remove empty line of EOF .
Updated changelog
Update CircleJumpDrawable . Gif
Add 2 . 4 . 0 release notes from release list
Fixed error in previous commit ( # 642 )
Updating readme to match version 0 . 9 . 3
Readded clean goal for coveralls as it seems to be required by the official doc .
Removed unused import from import ; fixes # 211 )
Update apk
Ignore Update ' modules / apps / collaboration / blogs / .
Do not process grammars following an error is closed
Fix missing closing bracket
Fixing the same method parameter
Removed Truth 0 . 24 + binary from third_party .
Ignore Update ' modules / apps / foundation / portal - security / .
Add DataGrip to the list of supported languages
Add default constructor to graylog2 . Sh
Do not delete svg - partial
Fix checkstyle issues
Ignore Update ' modules / apps / foundation / expando / .
Removed tag roboguice - 1 . 1 . 1
Removed item as part of usage ( )
Ignore Update ' modules / apps / foundation / my - account / .
Setting version to 1 . 0 . 118
Update aerosolve version
Add STORM - 1453 to changelog
Add STORM - 1406 to changelog
Fixed data error in setStreamVersion
Remove ' performanceTest ' entries from .
Bumping up curr . Release to 0 . 70 .
Updated changelog
Ignore Update ' modules / apps / foundation / login / .
Fix an unintentional change in signature of Reqeust Arc operations .
Remove System . Out . Println ( Object )
Upgrade Support Library to 21 . 1 . 2
Added the gradle target to ignore .
Nexus S now reports the proper frame - rate
Add a missing contributor list to Makefile .
Added new migration file with the new attribute data header
Add badge
Provides a more recent snapshot of the wiki
Push version to 11 , 206 .
Add * .
Remove ' performanceTest ' entries from .
Add missing library for uploading binaries to googlecode .
Removing TimeUnit from api and replace with Duration
Moved assertThat ( ) back into hamcrest - integration ( really this time ) .
Removed the testdata file in the docs .
Move Runits for GLRM set loss function by individual column to passing thanks to Michal ' s fix
Tidied up more 10 for libunix . Hpp
Updated screenshots
Bumped version to 1 . 0 . 0
Updated changelog
Added gradle buildfile to create downloadable artifacts , and push them out to neo4j . Org
Changed id to also use the video - data .
Updated changelog
Ignore Update ' modules / apps / collaboration / blogs / .
Updated Studio with last version
Updating history .
Changed dependencies back to SNAPSHOT versions after tagging
Upgraded guava to 14 . 0 . 1
Fix oreientation bug
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Fixed a typo .
Update version to 1 . 0 . 1
Reduce logging , use ' quiet '
Only use jdk8 in travis
Add wget for yum warning
Add changes entry for unnest
Set version to 6 . 0 - SNAPSHOT .
Ignore Update ' modules / apps / foundation / hello - soy / .
Push version to 13 - beta4 , 11246 .
Don ' t restrict rpm to compile integration tests
Ignore Update ' modules / apps / foundation / portal - instances / .
Add MainFrameWebView to android . Xml
Updated changelog
Added a test case of the new dpi icon
Changed packaging to jar since there are problems with bundle ( classes being in other
Many users may add the .
Prepare next dev iteration
Updated changelog
Add image for Android listitem
Fixed camel - test dependency scope .
Update gradle to v2 . 0 . 0 - alpha1 to enable instant run ; )
Rename README . Txt to README . Md
Removed @ Repeat ( 100 ) from BasicCacheTest
Removed dead code statement
Remove debug output warning
Added " cpp " " options " in ' backspace ' command ( PY - 7609 )
Fixed a bug where HttpMessage . RemoveHeader ( ) leads to a book for each model
Corrected typo in TODO
Prepared for next development iteration
Replace the callback flow graph of FileDownloadListener , add the ' error ' method callback after occuring an exception in ' blockComplete '
Ignore Update ' modules / apps / foundation / hello - world / .
Remove unused field of Event . Shutdown ( ) .
Updating Alloy to 5887563 ; LPS - 31011
Do not show merge cache from sub - bottom menu
Fixed typo in README
Fix a bug in svm . Cpp
Fix issues with video on linux .
Adding 7 . 0 . 1 - SNAPSHOT section to VERSION . Txt
Don ' t require java 7 in pom
Fixed test data
Ignore Update ' modules / apps / collaboration / notifications / .
Ignore Update ' modules / apps / foundation / portal - lock / .
Add exception output
Ignore Update ' modules / apps / foundation / roles / .
Ignore Update ' modules / apps / web - experience / journal / .
Updated IntelliJ version
Turn off active by default on tests ( # 1843 )
Prepare 1 . 0 . 4 release
Updated sample version
Fix building with integ tests .
Updated studio with Security + Backup UI
Fix 64 bit long pointer size for media scanning
Added professional image for parallel gateway process
Added clover license
Commits the background color on the sort background rather than work
Testing build notify
Prepare version 27 - beta1 .
Prepare for next development iteration
Fix release notes for v1 . 5 . 0
Don ' t run the lazybones tests in the joint Groovy build .
Updated changes . Txt for 0 . 8 . 1 .
SONAR - 8427 Behave BDD support for resume from long
Fix travis . Yml .
Update CHANGES . Txt
Ignore Update ' modules / apps / web - experience / export - import / .
Changed manifest to src and correct authors
Revert " Bumping gradle to hopefully fix buffer overflow on Travis "
You don ' t need performance object .
Ignore Update ' modules / apps / collaboration / blogs / .
Add constant to requirements . Txt
Added node_modules to gitignore
GRAILS - 6047 , GRAILS - 6089 - improve handling of calls to local closures in Bootstrap
Remove spurious import
Remove errant AutoCloseable .
Fix # include for the images that was I noticed doesn ' t get it instead of install .
Removing old images that can not necessary with a new code extension
Removed ' Master ' from names .
Updated controller sh
LPS - 39310 Don ' t leak jsessionid by default
LPS - 65920 ( WEB ) Move css files
Ignore Update ' modules / apps / collaboration / flags / .
Revert " Fix zombies after they are removed from timer cache as well .
Remove MainClass . Jar from lib .
Ignore Update ' modules / apps / web - experience / site / .
Fix small grammatical error in readme
Inherit meta from parent dir
Fix release notes for v1 . 5 . 0
Ignore Update ' modules / apps / collaboration / flags / .
Fix bug in XML list block ( # 421 )
Accept " Renamed " " " " " " " " " " link " # 394 )
Add StoreMeta which is an empty icon
Remove useless System . Out . Println
Remove typo
Add Clover instrumentation .
Remove TODO from javadoc . Xml
Add flowdock notification to Travis build .
LPS - 66848 Add missing Gitignore
Fix spacing for networkingPrivate . WiMAXStateProperties extern .
Added missing target dependencies
Add tab localization ( # 6954 )
Ignore Update ' modules / apps / foundation / frontend - css / .
Updated Android sdk to 21 . 2 . 2
Updated reference to oc - library
Updated build configuration to version 3 . 2 . 0 - SNAPSHOT
Fixed small typo in TCPServer .
Fix permissions
Ignore Update ' modules / apps / collaboration / blogs / .
Fixed a bug where the end of window .
LPS - 47791 - Select All checkbox not displaying ( occurs from WC and DM )
Removed package statement as we ' ve stuff in groovy .
Use the latest lib snapshot
Fixed syntax error in README . Md
Ignore Update ' modules / apps / marketplace / .
Add image
Don ' t hardcode the index for my version that we don ' t belong in up 3 . 2
Ignore Update ' modules / apps / web - experience / journal / .
Updated schema version to 3 . 2
Bump common for 4 . 2 . 2 ref
CAMEL - 7209 Fixed a unit test
Try jdk8 on travis CI with a revised timeout ( 30 mins this time )
Added ignore rule
Updated changelog
Add lib / html / sax / push_parser .
Push version to 12 - beta8 , 228 .
Ignore Update ' modules / apps / collaboration / document - library / .
Ignore Update ' modules / apps / foundation / frontend - js / .
Remove unused import .
Removing unnecessary closing angle comment .
Remove unnecessary imported package
Remove @ Override flag from compareTo method , since it isn ' t in the superclass .
Fix UIExplorer crash
Removed scalar_intersect from getting constructor ( # 63 )
Ignore * .
Remove the accidentally created file width ( too # 6954 )
Bump SpongeCommon ref .
Don ' t build gh - pages branch .
SONAR - 5845 Fix separator name for CircleCI ( PY - 6618 )
ACT - 401 Added cxf module to the checkmule profile
DGM . Println ( Object ) and friends do a Writer . Close ( ) if the object is a writer .
Stopping unnecessary character
Fix AutoCraftingTable not respecting the doRemove flag
Change version back .
MAHOUT - 1775 FileNotFoundException caused by aborting the process
Remove obsolete comment from travis .
Fixed issue where disabled is disabled .
Updated ChangeLog
Updating Alloy to rev . 81636
Change result type to long ( copy & paste error )
Ignore Update ' modules / apps / web - experience / rss / .
Don ' t include help files on linux .
Ignore Update ' modules / apps / collaboration / image - uploader / .
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Set MaxDirectMemorySize for tests .
Remove extraneous semicolon in wizard .
Remove TODO from OperationMerge
Ignore Update ' modules / apps / web - experience / layout / .
Set activity type ( caused by 3 . . .
Ignore Update ' modules / apps / foundation / portal - security / .
Flow should ignore website .
Ignore Update ' modules / apps / collaboration / announcements / .
Revert " disable parallel execution of web tests with coverage "
Upgrade Support Library to 24 . 2 . 1
Ignore Update ' modules / apps / collaboration / document - library / .
Upgraded Mockito to 1 . 9 . 0 .
Upgraded parent version .
Upgrade Anonymous Usage Statistics to version 1 . 1 . 0
Ignore Update ' modules / apps / collaboration / document - library / .
Bump version to 1 . 2 . 4
Remove mention of contributor
Add image for issue tracking
Fix quotes
Ignore Update ' modules / apps / web - experience / layout / .
Remove unused import in quarry arm script .
Ignore Update ' modules / apps / collaboration / document - library / .
Added professional image to include otp . Jar
Fix link to issue 0 . 9 . 2 .
Make ViewHolder less visible , fixes # 301
LPS - 45983 Add a line break since it ' s not needed
Kill CheckOutputThread on stoptrace ( PY - 12782 )
Add getContextPath .
Set uploadArchives encoding to utf - 8
Add art assets
Fix context menu
Don ' t use 54321 in the rest package
Create gradle files to appease NetBeans plugin
Fixed too high margin
Updated studio
LPS - 55198 - reposition close btn in modal header for narrow
Don ' t use the arguments to fseek ( works via Ashutosh Chauhan )
Revert " Change the scope "
Updated png . Png
Remove extra space
Fixing transitive - ness of provided
Remove the final modifier to ensure it will compile again
Set VERSION file
Updated paper for remote logo
Removed the " quiet " flag so that travis doesn ' t time out
Fixed finbugs issue ( PY - 3290 )
Prepare release jfinal - 1 . 5
Removed unnecessary jar file
Update the www - hdpi emergency icon
Ignore Update ' modules / apps / foundation / login / .
Ignore Update ' modules / apps / foundation / portal - lock / .
Upgrade JUnit to 4 . 8 . 2
Remove unreachable code
LPS - 55531 Move FileSystemStoreRootDirException to portal - service
Ignore Update ' modules / apps / collaboration / document - library / .
Update linux - x86 natives
Add jar
Bumped up the version to 0 . 4 . 4
Accidentally put an empty class to the ignored class .
Add STORM - 1771 to changelog
Make sure that there doesn ' t run twice .
Ignore Update ' modules / apps / foundation / portal - template / .
Ignore Update ' modules / apps / collaboration / invitation / .
Fixed small bug in p . Bash ( # 642 )
Add csiro . Au as TLD since is not listed in Mozilla docs
Remove unused files
Fixed a bug where HttpMessage . RemoveHeader ( ) leads to a dangling leak
Add explanation on adding dependencies of maven - release - plugin
SONAR - 4636 Bind handling of branding resources to a later phase of the build
Add missing image for windows
Fix AppleBundle # getBuildSteps ( ) so it returns a non - initialized list
Applying changes to SVN trunk , not Git trunk
Ignore Update ' modules / apps / collaboration / wiki / .
Add source module to pom . Xml
Add STORM - 1646 to CHANGELOG
Remove release
Bump pegasus version to 1 . 8 . 5
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fix mcp mapping .
Upgraded netty to 4 . 0 . 31
Add LGPL desgination to hunspell
Disable stdio . H in tools / android - 1 . 1 .
Added gitignore .
Remove useless .
Added packaging and refactored libraries around
Fix documentation for Method . Is_static
Ignore Update ' modules / apps / foundation / petra / .
Moved test from src to test tree
Add StoreMeta which is an empty style for the client
Removed some comment on the javadoc
Removed unused import in ExecutorServiceProxy .
Ignore Update ' modules / apps / foundation / portal - configuration / .
Can ' t export a movie - create API , but ' t be opened in the global window .
Removed todo returned that we ' re longer merge in case .
Upgraded netty to 4 . 0 . 6
Update aboutlibraries
LPS - 63528 Duplicate util package , unify under service layer
Add * .
Ignore Update ' modules / apps / web - experience / journal / .
Setting version to 1 . 0 . 77 - SNAPSHOT
LPS - 46809 Add a line break since we ' re about to manipulate the var
Fix for GRAILS - 8586 " gradlew install this changes .
Fix reading sleep policy
Add maven - net - ext to jphp - runtime POM
Turn off baseline aligment .
Ignore Update ' modules / apps / foundation / web - proxy / .
Remove spurious blank line
Moved index . Html to GoogleChartsExample folder
Fixed error in previous commit
Add the hide for the inner class method for the lazy - 1 . 1 .
Don ' t initialize JMF
Bump common for 4 . 2 . 2 ref
Revert " Revert " don ' t use fakeroot to build packages on debian "
Fix merge of manifest
Add STORM - 818 to changelog
Ignore Update ' modules / apps / foundation / monitoring / .
Ignore Update ' modules / apps / web - experience / asset / .
Adding riak module
Include InterruptedException into mock1 . 7
Added adapter for android .
Ignore Update ' modules / apps / collaboration / mentions / .
LPS - 46869 On a smartphone , excess white space appears in Site Administration for Site Memberships and Site Teams portlets
Fix a bug in svm . Cpp .
Added e - mail address
Removing assembly
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . Otherwise
Updated version in README .
Removed @ Repeat ( 100 ) from BasicCacheTest
LPS - 65492 Ignore SF for now
We don ' t need binary files on # 2410 .
Revert " add " Console " " to " bin " "
Fix copy / paste error
Ignore Update ' modules / apps / collaboration / image - uploader / .
Another test bites the dust
LPS - 63247 Add build . Xml
Ignore Update ' modules / apps / foundation / frontend - theme / .
Bumping version number and code for 2 . 6 . 2
Add link about forge version location in README . Md
Ignore Update ' modules / apps / foundation / plugins - admin / .
Fixed wrong separator path in README . Txt
Adds TODO for 416 truncated LIST command .
Added packaging and refactored libraries
Prepare release checkstyle - 6 . 16
Removing @ PrivateApi annotation ; not needed since PacketTransceiver is in the impl package , and therefor should not be accessed by the outside world
Don ' t show super . RequestFocus ( ) to subclass .
Added new theme of the header ( ) to updating updated .
Add STORM - 1455 to CHANGELOG . Md
Include server examples in the build .
Remove unused code warning
Ignore Update ' modules / apps / collaboration / ratings / .
Fixed issue in previous change
Include shrink - index .
Ignore Update ' modules / apps / web - experience / trash / .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Ignore Update ' modules / apps / foundation / frontend - js / .
Fixed a bug where HttpMessage . IsSuccess ( ) putting the same stack is used .
LPS - 60633 ( SERVICE ) Move service class
Update introduction course to 3 . 0 . 1
Add animated gif
Changed version to 0 . 1 , since the 1 . 0 was just the release version .
Replaced white key for 4 . 3 . 4
Fixed broken script name
Removed unused comment - > 1 . 6 .
Fixed some issue with create docs
Remove silly throws decl
Updated changelog
Removed old readme for HIVE - 522 .
Changed package name .
Added checkstyle to the dependencies that we can ' t find the suppressions artifacts .
Add a META - INF / pack .
Ignore Update ' modules / apps / collaboration / bookmarks / .
Revert version of file .
Ignore old semicolon in docs
Added STORM - 417 to changelog
Fixed typo in benchmark .
Call super . Shutdown ( ) reported by ProviderManager .
Delete the scored frame and changing from nodes
Prepare next development version .
Added render distance hook
Setting version to 1 . 0 . 148
Setting version to 1 . 0 . 58 - SNAPSHOT
LPS - 51748 Move icon
Fixed a typo in our build script .
Ignore Update ' modules / apps / web - experience / product - navigation / .
Added STORM - 1053 to Changelog
Ignore Update ' modules / apps / sync / .
Fix typo in code activity since it will be ignored by default .
Ignore Update ' modules / apps / foundation / portal - search / .
Move Runit for PUB - 474 to NOPASS until I figure out the source of the numerical inaccuracies .
LRQA - 47293 Exclude the DependencyVisitor file from the new javadoc module
Don ' t prompt refresh if data is closed by default
Ignore Update ' modules / apps / web - experience / layout / .
Don ' t restrict rpm to only INFO cases .
Added res directory
Updated README with new snippet
Remove ' performanceTest ' entries from .
Updated ChangeLog
Delete the scored frame , which will be used by default
Added folder for the visualization project .
Fix ci compilation .
Change version num and year for the release of libsvm 3 . 15
Add missing image for v1 . 5 . 2 .
Added logo
Add todo to jetbrains . Dic
Added image for multi task visualization project .
Add intellij files / folder to .
Delete demo . Apk
Change uploadArchives to uploadPublished for signing condition
Ignore Update ' modules / apps / foundation / frontend - js / .
Remove memory limit ( # 41 )
Updated changelog
Updated README for 0 . 6 . 7 . 2
Remove extraneous @ Override in HazelcastClientProxy .
Removed spurious System . Out . Println
Fixed a bug in svm . Cpp
Ignore Update ' modules / apps / collaboration / blogs / .
Update druid console version ( # 3189 )
Ignore Update ' modules / apps / collaboration / wiki / .
Prepare 1 . 1 . 2 release
Ignore project . Properties files
Remove unused variable from lerp example
Updated version
Remove temporary directory from .
Fix spelling code
Missing overwritten method in FieldSpec ( # 256 )
Fixed false positive in " A Unicode character "
LPS - 51810 Shorten call pointer
Remove outOfRange suppression
Adding org . Jetbrains . Kotlin as part of pom . Xml
Update gradle
Prepare for next development iteration
Add e / SourceSafe to the list of some files
Ignore Update ' modules / apps / collaboration / notifications / .
Updated changelog
Remove unused setter from HttpConfiguration .
Enable unit test on jdk6 and 7 , and use mvn clean package instead of mvn test - B
Removed javadoc attribute in pom . Xml
Ignore Update ' modules / apps / web - experience / asset / .
Added a Composite Configuration Diagram to use in the Wiki .
Breaks the loop
LRQA - 28979 prep next , use latest
Ignore Update ' modules / apps / collaboration / announcements / .
Make finish ( ) when creating a build ( fixes ) .
Remove optional generation of the dependency
Updating Alloy - rev . 58165
Add osx w / allowed failures on Travis
Fixed a subtle bug I happened to introduce last night .
Setting default name for multi - project
LPS - 62787 Add missing build . Xml
Ignore Update ' modules / apps / foundation / portal - remote / .
Fixed a bug in svm . Cpp
Remove @ Repeat ( 100 ) from BasicCacheTest
Add the META - INF / pack .
Fixed a bug where HttpMessage . RemoveHeader ( ) leads to a dangling pointer in the model
Fix power provider for event list
Ignore Update ' modules / apps / web - experience / layout / .
Add image for fixed documentation .
Do not encode sendRedirect URLs
Added relative path to the parent POM so that the user won ' t need to
Prepare next release v0 . 88 . 2 - SNAPSHOT
Add empty migration file
Prepare for next development iteration
Remove unnecessary internal class from build . Gradle
Removed @ Repeat ( 100 ) from BasicCacheTest
Updating Alloy to rev . 81636
Added example to installation documentation
Added gitignore .
Updated 3 . 0
Use the latest lib snapshot
Added * .
Update gradle . Properties file with a new VERSION_NAME and VERSION_CODE for the next development iteration
Removed the accidentally checked in repository
Fixed missing closing bracket
Updated travis . Yml buildTools version to 7 . 0 . 1
Ignore Update ' modules / apps / web - experience / journal / .
Set the group name to build . Gradle
Removing accidentally added logo
Ignore Update ' modules / apps / collaboration / ratings / .
Removed mention of GROOVY - 6226
Remove debug logging that was accidentally removed in tests .
Add 2 . 4 . 0 library for bw comp tests
Ignore Update ' modules / apps / foundation / portal - security / .
Don ' t create the headless class as it isn ' t have change that we ' re null as well .
Added translation using Weblate ( Icelandic )
Correct the typo in the changelog .
Add missing SPDY npn - boot . Jar file to Openfire lib / dist
Fix the dock - insertion Dream entry codepath .
Ignore Update ' modules / apps / marketplace / .
To run test
Make sure that we don ' t set the hostname call from default .
Add image for multi task action button button
Updated parent version .
Set release version for release
Ignore Update ' modules / apps / foundation / portal - security / .
Add unistd . H for size_t typedef to fix sim - eng
Updated changelog
Push version to 11 , 206 .
Ignore Update ' modules / apps / web - experience / portlet - configuration / .
Make array that we don ' t have better path in order of the path
Upgrade maven version to 1 . 0 . 4
Update internal framework to API 24 ( Nougat Final Preview )
Removed unused image .
Updated changelog
Use gradlew executable on travis
Bump up release number to 1 . 0 . 6
Ignore Update ' modules / apps / web - experience / site / .
Fixed typo in javadoc config
Add support for TravisCI - ci config .
Updating Alloy to rev . 81636
Remove opendk as it ' s not present
Ignore Update ' modules / apps / collaboration / microblogs / .
Removed old pattern relationship image
Bumped version to 0 . 8 . 7 - SNAPSHOT .
Prepare version 20 - beta3 .
Start next dev cycle ( 2 . 0 . 2 - SNAPSHOT )
Created notorious enterprise / WEB - INF / __pycache__ to .
Remove debuggable = true from build . Gradle
Removed unused method from AnimatorSet .
Add foo . Jar to fix broken build
Update README . Md
Revert " LPS - 45166 SF "
Setting version to 1 . 0 . 7
Added translation using Weblate ( Kabyle )
Fixed copy / paste error
Created tech - debt entries for all components and laboratory components .
Add getChildCount ( ) to PShape reference
Don ' t force refresh if data is taken from cache
Added Fenwick Tree ( Binary Indexed Tree ) to the Readme
Setting version to 1 . 0 . 10
Add header gif
Remove memory limit from travis
Fix path typo in com . Mongodb . CommandResult . GetServerUsed
Ignore Update ' modules / apps / sync / .
Added entry for " Remote Code Execution - CVE - 2012 - 1823 "
Fixed react import case ( failed on case sensitive file )
Remove jdk 8 from travis build , because it always hangs / takes to long
Prepare release storm - hbase - 0 . 1 . 2
Updated version
Add STEM_1 , STEM_2 and STEM_3 key as wakeup keys .
Fixing some problem in pom . Xml
Remove unnecessary import message .
Update changelog
Add additional key for fullscreen on iOS7
Add symmetric sslAvailable = false
Improves the hotplug response times on Windows which may be noticeably prolonged due to thread scheduling in cases of Windows Multimedia reporting lack of a device driver .
KAFKA - 4088 - Session . GetSession should always return sessions from Mac .
Fixed EDU - 158 Problems with tasks
Added a README
Updated ChangeLog
Move rebalance image to NOPASS .
Fix stupid bug in svm . Cpp
Fixed typo in first line of bbb - conf
Ignore Update ' modules / apps / web - experience / site / .
Udpated version to 2 . 0 . 2 - SNAPSHOT
Add screenshot
Fix jars of jars that we don ' t run fails with case etc .
Remove unused file
Added tag 0 . 0 . 7 . 2 for changeset 5de91e5a0e95
Fix permalink to StatusBarIOS . SetStyle in the NavigatorIOSColorExample
Don ' t over - validate email address .
Removed unnecessary return statement
Ignore * .
Add 111
Normalize line endings
Remove spurious @ Override .
Add icon
Ignore Update ' modules / apps / foundation / petra / .
Fixed a typo in the comment .
Ignore Update ' modules / apps / foundation / expando / .
Ignore dependency - reduced - pom . Xml
Bumped parent - pom - > 7 - rc5
Ignore Update ' modules / apps / foundation / portal - settings / .
Completely reverted change on log4j dependency .
Upgrade Support Library to 24 . 1 . 1
Bump common for 4 . 2 . 2 ref
Updated breton POS dictionary from Apertium svn r53329 .
Ignore Update ' modules / apps / foundation / petra / .
Added makeGLMModel call for FakeContext
Add Apache Commons Lang 2 . 6 , for use with Apache Velocity 1 . 7
Fixed a code typo
Ignore Update ' modules / apps / collaboration / wiki / .
LPS - 67469 LRDOCS - 2841 remove build . Gradle since that project is now empty "
Revert " Revert " HHH - 8733 - General build cleanup - hibernate - testing "
Testing travis - ci
Adding STORM - 625 to changelog .
Ignore Update ' modules / apps / web - experience / layout / .
Source formatter had trailing blank line
Updated TCK .
Moved timeout to avoid failing compilation
Add Gitter webhook as a secure Travis project
Add STORM - 1452 to changelog
Fix accidental import width .
Added IPC exception .
Push API version to 1 . 0 . 0 .
Changed method name to not initialized a a session annotation
Removed unused property from AnimatorSet .
Fix typo ( # 57 )
Make stress executable
Improve lexer input package in timeline
Ignore Update ' modules / apps / collaboration / mentions / .
Removing @ Repeat ( 100 ) from BasicCacheTest
Edit CHANGES . Txt for CASSANDRA - 11051
Fix JAR count after adding task - cache - http .
Add missing property name .
Fix the push - tags target
Add Eclipse wrapper project file to gitignore .
Add config_use_strict_phone_number_comparation , which will be used by stream .
Ignore Update ' modules / apps / foundation / license - manager / .
Make sure jandex is using problem in pom ( # 1843 )
IDEA - 117674 please rebuild and commit runnerw . Exe
Adding a Composite Configuration Diagram to use in the Wiki .
Remove some whitespace
Added assertions by default
Adjust feature graphic for tablet
Adding IntelliJ files to .
Ignore Update ' modules / apps / web - experience / site / .
Fixed issue where unread count is found ( IDEADEV - 22794 )
Move Travis CI config to src / test directory
Upgrade the wrappered gradle to 0 . 9 - rc - 3
Ignore Update ' modules / apps / web - experience / asset / .
Download apk directly from here
Moved DelegatingAuthenticationEntryPointTest - context . Xml to test / resources
Fix CHANGES . Txt for releases
Remove unused files ( irrelevant )
Ignore Update ' modules / apps / sync / .
Updated changelog
Ignore Update ' modules / apps / marketplace / .
Added STORM - 1423 to Changelog
7 0 . 6 . 0 release notes from 2 . 0 . 0
Fix typo in pom . Xml
Remove unused code from keywords . Java
LPS - 63247 Add build . Xml
Updated changelog
Remove unused pattern relationship image
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Ignore Update ' modules / apps / web - experience / staging / .
Added STORM - 625 to changelog .
Updated structdb with structs from AngryBots for 4 . 2
Shut up linter
Bump version to 3 . 0 . 0 - beta . 1
Improves the hotplug response times on Windows which may be noticeably prolonged due to thread scheduling in cases of Windows Multimedia reporting lack of a device driver .
Ignore Update ' modules / apps / foundation / frontend - js / .
Updated splash screen for Windows
Increased the default permgen once
Added wand - item so that OTP can be supported by multiple indexes .
Ignore Update ' modules / apps / web - experience / asset / .
Ignore Update ' modules / apps / foundation / portal - instances / .
Updating Alloy to 5887563 ; LPS - 31011
Fixed an serializable bug .
Ignore Update ' modules / apps / web - experience / journal / .
Set correct permissions on the script .
LPS - 58662 I assume order matters , so let ' s add a line break
Adding the jpa - converter module
Remove @ Nullable from getVirtualFile method
Revert " Revert " Bumping up version to 2 . 6 . 1 "
Create gradle files to appease NetBeans plugin
Add openjdk6 to Travis configuration
Prepare library for development
Remove local testing file
Ignore Update ' modules / apps / web - experience / portlet - configuration / .
Remove TBD from " Optionality " section
LPS - 42723 Remove blank line
Removed unused imports
Ignore Update ' modules / apps / web - experience / journal / .
Add maven support
Added SystemServiceRegistry to preloaded - classes
Ignore Update ' modules / apps / web - experience / staging / .
Remove an obsolete comment
Add Hopper to Chute as discussed
Ignore Update ' modules / apps / web - experience / staging / .
Updates the chat room contacts icons .
Prepare release notes .
Correct the typo in the noun
Simplifying the default welcome presentation
Remove version after pom . Xml
Removing @ Nullable from PreDexMerge . GetSecondaryDexDirectories
Correct the gitignore in gitignore
Added link to snapshots after 0 . 9 release notes
Update voiceRouter with currentStatus = STATUS_UNKNOWN ; while makeUturnWhenPossible is active
Added professional image for parallel gateway process
Include podspec in npm distribution .
Update native lib to 3 . 2 . 2
Rename testMultinode . Sh to testMultiNode . Sh
Bump pegasus to 1 . 9 . 5
Ignore Update ' modules / apps / foundation / portal - instances / .
Removed broken import
Ignore Update ' modules / apps / foundation / portal - remote / .
Don ' t accept " Schienenbein "
Implement cursor to the getCoyoteResponse ( ) method from the exception if it is enabled
No longer 3 . 0 . 1 or above
Removed unnecessary @ Override statement
Add grailsCentral ( ) from BuildConfig . Io as it doesn ' t work in Grails 1 . 2 .
Disable CLIRR rule to UTF - 8 .
LPS - 57119 Only strip fully qualified classname when it ' s NOT a literal string
LPS - 55603 - Remove unnecessary code from PortalImpl . GetHost ( )
Added Recognizer . RemoveErrorListeners ( ) to Recognizer . Py
Update applet to fix some exceptions
Adding change log
Revert " Updated gitignore for me "
Add apache logs folder
Don ' t include transitive dependencies for all projects ( fixes # 192 )
Add mention of contributor to Makefile
Updating Alloy to rev . 81636
Move ChildBrowser . Java to the right directory
Bumped version so that it ' s easier to test javadoc publication .
Adding system + to the main constructor
Update gradle build
Corrected typo in Constructors section
Disable dan ' s reference to avoid boost implementation
Updated version in README
Ignore Update ' modules / apps / collaboration / directory - .
Setting version to 1 . 0 . 113
Add sbt cached resolution to build "
Upgraded slf4j to 1 . 7 . 20
Rebuild test instrumenter with target java 1 . 5
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Corrected title call
Remove unused asset drawable
Add StoreMeta which is an empty components for the medium dpi version .
Fixed a bug where GCalControlSet might not be centered
Remove @ nosideeffects from DataTransferItem . Prototype . GetAsString ( )
Ignore Update ' modules / apps / foundation / web - proxy / .
Added Gradle gitignore
Push version to 12 . 1 , 236 .
Updated CHANGES . Txt for # 353839 .
Updating Alloy to rev . 81636
Added # hashCode ( ) to JID to be fully comparable .
Ignore Update ' modules / apps / foundation / portal / .
Use Java 7 .
Add test for interceptorsgd
Added Oracle JDK 8 to .
Tried new submodule url
Updating changelog
Add a script to generate a random file , that should be used later on the client check
Build number 10
Removing unused imports from AnimatorSet .
Suppress incorrect import in comment
Make it is no longer sign when building all by the compilation .
Adds experimental support for acoustic echo cancellation ( AEC ) on Windows when using Windows Audio Session API ( WASAPI )
CAMEL - 5583 - Add LZFDataFormat to jaxp . Index .
Keep review comments ( # 6059 )
Remove @ Override from GrailsDomainClassMappingContext . GetIdentityMapping ( ClassMapping )
Fix a small bug in upcoming changes ( # 1039 )
Add version 2 . 3 . 4 to upgrade from versions
Use less intrusive watched icon .
Use Java 8 .
Ignore grails - test - suite - uber / bin /
Added a few more ideas .
Dispatch up event to fix fling
Ignore Update ' modules / apps / marketplace / .
Don ' t show the animation buttons , leave an empty line .
Prepare for next development iteration
Updated changelog
Updated changelog
Add STORM - 1079 to CHANGELOG . Md
Ignore Update ' modules / apps / collaboration / directory / .
Added tag .
Use PApplet . Java ( ) instead of System . Exit .
Add missing travis ci components
Missing mysql - section .
Add nbase - arc - app icon
Remove dummy jar file
Ignore Update ' modules / apps / foundation / frontend - js / .
Removed @ PrivateApi annotation ; not needed since PacketTransceiver is in the impl package , and therefor should not be accessed by the outside world
Ignore portal - profile 1 . 0 . 0 prep next
Make org . Jetbrains . 4 as part of build . Gradle
Improved favicon
Fixed the build issue .
Added booleanTest . Json to pom . Xml
Add net . GetProxiesByKey ( ) and jna for 4 . 2
Remove warning ( ) from BasicCacheTest
Added IDEA files to .
Added code generation of the use of tuples , lists and maps
Reseting a TBD . Properties file
Ignore Update ' modules / apps / foundation / frontend - theme / .
Added files via upload
Upgrade mysql driver to 1 . 3 . 1
Revert " update dependency "
LPS - 65012 Move export - import - service resources to the correct dir
Added a dummy .
Ignore eclipse files
Build 1 . 5 . 2
LPS - 36595 LPS - 37303 Undo SF in c034e424db7a18a4de11f2ec3c2bde00c4ee9b56 , because I think is the controlled exception in the dialog field
MinecraftForge / FML @ d00feb58c762b0bbc506d79faf1ce40bc96732e9 Remove debug code that was causing console spam in Forge .
Removing unnecessary return statement in LineageFileOutStream
Remove unused test file
Ignore icon .
Add getBytes to InputStream , URL and File ( patch thanks to jeremi Joslin )
Ignore Vim swap files
Updated changelog
Add missing SPDY npn - boot . Jar file to Openfire lib / dist
Removed @ PrivateApi annotation generation
Remove @ Experimental annotation now that this ( = v2 )
Change put command .
Revert " Ignore * .
Prepare for next development iteration
Update Readme .
Fix up typo in bbb - example
Updating Alloy to e79a782 ; LPS - 13554
Added classes to .
Don ' t show the value of the call provided into the last commit
Push version to 226 .
Fixed broken unit test
Improve inspection by default
Ignore Update ' modules / apps / sync / .
Fixed formula typo in bbb - hdpi
Added booleanTest . Json to pom . Xml
Fix an issue issue for 1 . 6 . 1 .
Fix an issue .
Updated changelog
Add lib / to .
Add good icon for free version .
IDEA - 100693 copy / paste of a whole space as well as system is closed ( IDEA - 157793 )
Ignore Update ' modules / apps / foundation / portal - search / .
Adding comment about compiler argument
Add " tuple " and " tuples " ( fixes # 394 )
Ignore Update ' modules / apps / foundation / license - manager / .
Ignore Update ' modules / apps / foundation / portal - security / .
SONAR - 3862 Fix a small bug in subtasks and freeswitch
Ignore emacs backup files .
Updated API reference
Added the manual to the build .
Removed empty pattern relationship image
Fixed typo in section id
Ignore Update ' modules / apps / foundation / frontend - css / .
Add Spring
Add website to readme
Ignore Update ' modules / apps / foundation / portal - security / .
Update build tools
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
LPS - 36294 - Missing language key from portal
Add * .
Fixed typo in com . Mongodb . MongoServerSelectionException class
Use the latest lib snapshot
Update to latest getglue - java snapshot , now supports checkin comments .
Fixed the glyph for U + 3A34 in DroidSansFallbackFull . Ttf .
Fix the resolved color for the intention ( ) .
Skip tests in compiling alluxio for hadoop
Add adapter for mdpi - runner .
Ignore Update ' modules / apps / foundation / frontend - css / .
Fix readme
Ignore Update ' modules / apps / collaboration / wiki / .
Added STORM - 1423 to Changelog
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Bump pegasus to 1 . 9 . 5
Set source encoding to UTF - 8
Ignoring gitignore
LPS - 67839 Create project build . Gradle
Add flowdock notification to Travis build .
Update gradle to 2 . 1 . 2
Don ' t load twice ? Anymore
Remove checkThread ( ) from findAddress
Applying changes to false alarm in CI build
Updated README . Md for v1 . 1 . 2 .
Added ignored_columns .
Delete demo_shifting .
LPS - 55079 Set min - height for pre in editor style
Bump common ref for loadWorld fix .
Ignore Update ' modules / apps / web - experience / journal / .
Updated banner to 0 . 9 . 4 . 0
Ignore Update ' modules / apps / marketplace / .
Ignore Update ' modules / apps / web - experience / asset / .
Ignore Update ' modules / apps / web - experience / staging / .
Add missing image for 1 . 5 . 2
Add Apache Commons Pool2 to Bazel .
Ignore Update ' modules / apps / web - experience / staging / .
Added eclipse project files to .
Fix a bug in ScanSettings constructor
Update crate - client to 0 . 6
Ignore Update ' modules / apps / collaboration / wiki / .
Remove unnecessary warning .
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Add STORM - 1937 to CHANGELOG
Prevent exception in View
Add icons
Adding mavenLocal ( ) for local resolution
Removed rotate ( PY - 4116 )
Prepare for next development iteration
Added Application class .
Revert " disable 3041579 stream for the makefile in the init file
TFJ - 586 define CursorSupport # START for the better coding experience
Added professional configuration for binary jars
Ignore Update ' modules / apps / web - experience / export - import / .
Fixed a bug where HttpMessage . RemoveHeader ( ) leads to a dangling leak
LPS - 45246 Don ' t capitalize the content title
Updating Alloy - rev . 58165
Ignore Update ' modules / apps / foundation / license - manager / .
Ignore Update ' modules / apps / foundation / portal / .
Help ID for received consoles with auto methods ( PY - 5990 ) .
Adding lang3 jars
Changed release name to j2objc - beta4 - 7
Fix git
Added ' iter ' and ' cinit ' to default Python dictionary ( PY - 7609 )
Updated test_jruby .
Ignore Update ' modules / apps / marketplace / .
Fix bad height in p . Set ( )
Updated FML ' s dictionary in AUTHORS file .
Revert " update CHANGES . Yml ( # 57 )
Update gitignore
Ignore Update ' modules / apps / collaboration / blogs / .
Add a toString ( ) method
Added Kasper to list of developers
Upgraded parent version .
Ignore Update ' modules / apps / foundation / portal - security / .
Ignore Update ' modules / apps / foundation / users - admin / .
Added missing parser for signature
Removed tag roboguice - 1 . 1 . 0
Fixed # 2951 by the README .
Update todo comments
Changed transitioner background color to ' transparent '
Remove unused image .
Added new files to libRSSupport
Added image for Android 1 . 7 .
Update linux - arm native
Don ' t inline HTML call for my new array .
Fixed typo in changelog
Do not 9 commit ( # 103 )
Fixed error # 257 , # 258 , # 260 )
Fix broken workspace error
Can ' t access static field from nested closures
Revert " force using hadoop - scala dependencies
Add STORM - 1466 to changelog
Updating readme in prep for 0 . 3 release
Remove executable bit .
Make android - web - web - runner script that should be supported by default .
Revert " LPS - 36642 rebuild ruby - gems "
Updated version in README .
Revert " Caching dependencies to speed up PR builds "
Fix readme in README . Md
Ignore Update ' modules / apps / foundation / portal - scripting / .
Fixed tests in build . Yml .
Include a typo in the config .
Fixed a bug .
Fixed a typo in the changelog .
Create README . Md
Update version number for doc stamp
Push version to 12 - beta9 , 230 .
Removed unused import
Removed old jars from Eclipse example
Adding the singleton module
Remove minSdkVersion and targetSdkVersion from 0 . 9 . 0 release
Set orbot / tor support into experimental status
Rename README to README . Md to force its parcing
Removed unnecessary return statement in LineageFileOutStream
Bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6
Revert " Invalidating a TE should not cause an condition on the speech synthesis .
Removed an unused import .
Upgraded maven - site - plugin to 2 . 1 . 1 .
LPS - 54250 moves icon
LPS - 30638 Executing portlet struts action should not a portlet keys
Fixed error in previous commit .
Ignore Update ' modules / apps / web - experience / export - import / .
Updating Alloy to c3a133e ; LPS - 30635
Hack Jetty / Websocket Session
Added high res launcher icons for xhdpi and xxhdpi .
Closes the StringLogger in shutdown ( ) for HA graph db
Added files via upload
LRQA - 64991 Remove mail portlet from build as it fails inconsistently on jboss / wildfly
Ignore Update ' modules / apps / foundation / portal - template / .
Ignore Update ' modules / apps / web - experience / layout / .
Removed mention of GROOVY - 6226 ( Configure some to info )
Do not force everyone into the own exception ( IDEADEV - 38870 )
ACT - 401 Added cxf module to the checkmule profile
Remove the empty file accidentally checked it with HADOOP - 7249 .
Update Android plugin to 2 . 1 . 2
Revert " added " util " test " to android - all
Ignore Update ' modules / apps / marketplace / .
Added Steve as a contributor
LPS - 50400 Move AsyncBrokerTest to portal - impl , no change
Fixed typo in README . Md
Set compile files to utf - 8
Removed unused config from createGraphics .
Fix footer in FireFox
Ignore Update ' modules / apps / foundation / server / .
Do not close dialog ( IDEADEV - 38870 )
Add redis to travis build
Reverted accidental DataSourceStatus enum change
Fixed flow warnings so that it can be set "
Removed empty line version 1 . 0 . 1 from Grails library , since they ' s open .
Fix link in readme
Build script 2 . 1 . 6
Fixed typo
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fix CircleCI configuration
Suppress unchecked warning
Modified url for issue tracking to directly show tickets for the component .
Update dict
Update CHANGELOG . Md for 2 . 7 . 1
Update todo
Fix typo in pom . Xml
Build new pre release b6
Restored uploadArchives and target for Java 7 . . .
Remove ' var ' button output .
Removed unused imports
Change number of package .
Updated version
Updated README
Ignore Update ' modules / apps / web - experience / site / .
Remove unused import ( # 1342 )
Ignore Update ' modules / apps / web - experience / site - navigation / .
Removed some unnecessory code
Removed warning that doesn ' t do anything it for Grails
Adding missing migration file
Fixed z - index
Added whiteboardAccess to config . Xml
Ignore Update ' modules / apps / web - experience / export - import / .
Remove unused import in BufferUtils
Adding IDE related files to .
Fix bad number in cluster test
Removed @ Repeat ( 100 )
Ignore Update ' modules / apps / collaboration / message - boards / .
Removed unused line .
Update gradle version
Fixed license warnings
Added Patrick Galley to credits
Remove the TAB key
Removed android - support - v4 . Jar .
LPS - 42815 - Error message style does not wrap on IE8 Breaks
Adding slf4j - api dependency to org . W3c .
Set VERSION to 5 . 3 . 0 - dev ( via coho )
Ignore files
Add STORM - 1203 to changelog
Added Richard to the team - welcome aboard !
Ignore Update ' modules / apps / collaboration / wiki / .
Updating to Gremlin 0 . 8
Upgraded maven - javadoc - plugin from 2 . 7 to 2 . 9
Fixed title
Added missing eclipse config file
Added a property to avoid the exception stack trace when running the console
Updated copyright date in LICENSE .
GRAILS - 7366 Remove blank line
Updated icon
LPS - 61420 Add property name to the module
Moved AstBrowserProperties from src / main to src / resources .
Prepared version 1 . 8 . 0
Updated changelog .
Made the mistake of opening anything in finder
Added STORM - 730 to Changelog
HHH - 11007 - Add Envers as a package name for Android 1 . 6 .
Added package template
Added missing migration file .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Update applet jar with changes to minimize connect timeout
Make 0 . 4 . 5 to the code error that updating to 1 . . .
Ignore Update ' modules / apps / foundation / portal - security / .
Fix lint errors in unused buffer ;
Ignore Update ' modules / apps / foundation / petra / .
Fixed typo in 1 . 7 . 1 hotfix
Try a little more heap memory for tests in Bamboo
Added bottom padding for customizations .
Remove some ' client ' .
SONAR - 3626 Fix test name
Updated version to 1 . 1 . 0
Add test resource
Finished collection / list separation
Remove warning that doesn ' t do anything correctly .
Fix copy and paste error in isKeyguardLocked ( )
Ignore Update ' modules / apps / collaboration / document - library / .
Removed unused import comment .
Updated changelog
Updated changelog
Fix typo in changelog
Upgraded parent declaration in all trunks to use version 1 of parent - central .
Ignore * .
Remove executable flag for source files
Remove unnecessary call = see # 1533 )
Write checkstyle to stdout .
Changed title in header ( # 523 )
Bump version to 1 . 2 . 5
Use the latest platform - tools on travis
Fix a minor typo of the library
Ignore Update ' modules / apps / collaboration / bookmarks / .
Fix Makefile .
Updated gradle jar to 1 . 9 . 2
Do not request focus for About command statement ( IDEADEV - 38870 )
Try screen refresh state
Ignore Update ' modules / apps / sync / .
IDEA - 11626 Debugger cannot inspect Swift object variables compiled with Xcode 6 . 3 ( 6D520o )
Fixed missing ' var ' in header . Css
Ignore Update ' modules / apps / foundation / frontend - css / .
Updated parent version .
Skip visitEnd in InliningInstructionAdapter
Ignore top level src dir
Remove @ nosideeffects from DataTransferItem . Prototype . GetAsString ( )
Ignore Update ' modules / apps / collaboration / document - library / .
Disable EGL_IMG_context_priority for the query build script
Ignore Update ' modules / apps / collaboration / blogs / .
Removed @ Nullable from PreDexMerge . GetSecondaryDexDirectories
Yeah , I just did ( # 57 )
Back up / restore the " Avoid poor connections " on change .
Update travis config
Updated changelog
Ignore Update ' modules / apps / foundation / login / .
Upgrade gecko to 1 . 1 . 2
Ignore Update ' modules / apps / collaboration / comment / .
Fixed test data for EnumAutoGeneratedMethods case
Remove openjdk6 from Travis CI config
Updated reference to ownCloud library with reduced logs in operations in shares
Fixed typo in file names .
Changed id to CLI friendly format .
Updated IntelliJ version
Don ' t expand the SearchView if already expanded .
Fixed typo for 1 . 4 . 2 .
Modify readme . Md
Fix JUnit issues
Simplifying the default welcome presentation
Ignore Eclipse directory
Added a protected method to retrieve the indent printer for reuse in subclasses of MarkupBuilder
Add Bitdeli badge
Updated changelog
Add flow image for NewLineAtEOF .
Remove unused import .
Do not push ideaj files to master
Temporary disable install script to run on JDK7 .
Fixed issue 404
Update applet to fix some exceptions
Bump common for 4 . 2 . 2 ref
Remove gradle wrapper dependency
Fix typo
Updated app_konference - 10 . 04 - 32 .
Added new contributor rule to updating up . Txt
Push version to 186 and 9 - beta5 .
CB - 11727 - travis ci setup is still using 0 . 2 . 32 node
Configured functional tests to run with forked jvm per - test , possibly hiding a memory leak problem with tests
Make self to contributors
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
The defaultdict import .
Added line at end of file
Added STORM - 266 to Changelog
Remove test arguments
When marking a more message as well .
Modify docker
Add WaveTable symbol for w3c_audio .
Updated changelog
SONAR - 5561 Fix issue on CAMEL - 105
Disable tests in build . Xml
Remove feature / ppa from travis build file .
Removed unnecessary line from import . Xml
Updated studio
Fix typo in changelog
Don ' t pull test and provided dependency of the manual phase
Added javax . Servlet jar to git
Fixed bug in edit unload ( PY - 16878 )
Revert com . Mongodb . MongoServerSelectionException class
Fix warning # 1401
Improve banner
Ignore Update ' modules / apps / foundation / frontend - theme / .
Ignore Update ' modules / apps / collaboration / blogs / .
Added / gen dir to the .
Updated travis config
Ignore Update ' modules / apps / web - experience / staging / .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fixing the JSDoc for angular . Bind .
Ignore Update ' modules / apps / collaboration / document - library / .
Remove bin from .
Ignore Update ' modules / apps / collaboration / microblogs / .
Update FastAdapter to latest v1 . 5 . 5
Add STORM - 2078 to CHANGELOG
Delete strings . Xml
Upgraded slf4j to 1 . 7 . 6
Remove old lib folder
DO NOT MERGE Take fake bold font property into account .
Disable query cache by default
Fix mobile sites when creating a lazily initialized connection .
Ignore / login script
LPS - 63528 ( WEB ) Move icon files
Revert " wc accepts files as this , Closes # 322
Updated travis . Yml buildTools version to 23 . 0 . 0
Added STORM - 132 to Changelog
Remove component call
Ignore Update ' modules / apps / web - experience / site / .
Update linux natives
Bump common ref for loadWorld fix .
Setting version to 1 . 0 . 66 - SNAPSHOT
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Revert " Revert " Make clearing the cache characters .
Ignore Update ' modules / apps / web - experience / journal / .
Add STORM - 1573 to CHANGELOG . Md
Fixed typo in year in graylog2 . Conf
Fixing some type issues
Ignore Update ' modules / apps / marketplace / .
Remove generic - length file
LPS - 65749 prep next , use latest
Push version to 16 - beta3 , 15013 .
Added jme3 - lwjgl3 / build / to the gitignore file . . . .
Remove submodule / hadoop - library
Don ' t allow K9mail - errors to avoid sure error message in cases .
Ignore Update ' modules / apps / foundation / portal - security / .
Set back = parse type ( IDEADEV - linking )
Adding images for instructions
Add MySQL - python
Fix copy / paste error on case ( )
Added maven plugin dependency to failsafe - maven - plugin - plugin
Adds device uid for wmme and dsound devices .
Ignore Update ' modules / apps / foundation / frontend - theme / .
LPS - 28261 prep next , use latest
Fixed typo
Added intellij specific files to .
Fix changes in README . Md
Add support for testing gc
Updated EnOcean lib to work with more EEP .
Don ' t include 54321 in the config data
Updated version
Added bin / drlvm / robovm - vts .
Fix version name
Ignore Update ' modules / apps / static / osgi / .
Fix bug # 5017432 NPE when mixing the spans with an regression .
Bump socket . Io for tests
Ignore Update ' modules / apps / web - experience / nested - portlets / .
Updated changelog
Updates the ice4j library to r240 in order to fix an issue which could leave an initiated Jingle call connecting forever .
Update gradle to v2 . 0 . 0 - rc4
Adding release notes
Removed application tag from library
LPS - 64979 Add IBM packages to framework ' s plugins name
Upgrade XStream 1 . 3 - > 1 . 3 . 0
Ignore Update ' modules / apps / web - experience / site / .
Add logo to nod add newpipe to playstore
Moving unit test name to test folder as well
Delete old readme
Ignore bin directory
Fixed description in Question 1 . 5
Manually exclude a description of spaces .
Adding soot with 1 . 5 . 1 .
Porting fix to allow for a forward / include to call getAttributeNames on the Request in a sandbox
Updating Alloy to rev . 81636
Ignore Update ' modules / apps / foundation / login / .
Update build number
Remove hardcoded version of commons - cli
Update README ' s README
Don ' t include the dubuggable flag in the joint Groovy project .
Enabled state size in notification list ( IDEADEV - 9512 )
Fix highlight result checkbox position on old FF
Ignore Update ' modules / apps / foundation / frontend - editor / .
Fixed the problem with the correct package ( # 103 )
Fixed test data
Add STORM - 2079 to CHANGELOG
Fix doc link
Upgrade Ant to 1 . 6 . 6
LRQA - 18792 Add property name for Microblogs portlet in testray
Only define _GNU_SOURCE if it wasn ' t defined
Setting version to 1 . 0 . 59 - SNAPSHOT
Fix master of manifest in AndroidManifest . Xml
Update linux - ppc64 native
GRAILS - 11151 remove StatementCache from jdbcInterceptors property in list
Move the Swing Model test to swing project as well
Add cloud - azure module
Add bin to gitignore
Add smaller sized icon
Delete old file due to test folder
Update build . Gradle
Updated changelog
Explicitly set halide_library . H to crash .
Upgraded netty to 4 . 0 . 25
Ignore Update ' modules / apps / collaboration / ratings / .
Add BAD_PACKAGE_PROPERTY_ACCESS DiagnosticType to the VISIBILITY DiagnosticGroup ( which transitively adds it to ACCESS_CONTROLS )
Add image for issue dialogs
Updating Alloy to rev . 81636
DO NOT MERGE - Quick fix icon
Exclude checkstyle for functional tests
Update jars
Placed the FilterCriteria . OnRecallSelection ( ) to return the already assigned parameter
Building linux native runtime with older version of glibc
Update changes for CASSANDRA - 2041
FIX Dashboard always display a scroll stack state
Made connecting index
Ignore Update ' modules / apps / foundation / portal - template / .
GRAILS - 5691 - remove some code that was accidentally left in case .
Update changelog
Ignore Update ' modules / apps / web - experience / site / .
Removed no - length file in prep for 1 . 5 beta
Prepare next development version .
Ignore Update ' modules / apps / foundation / portal - search / .
Upgraded SVNKit to 1 . 2 . 0 for ReleasePlugin . Jar
Removed $ Revision client for settings .
Add STORM - 2086 to CHANGELOG
Automated rollback of changelist 117753253 .
Fix POSIX - compliance issue in OpenGrok
Updated favicon . Png image
Updated xxhdpi mipmap icon to 144x144
Fix StackOverflow when calling getLayoutInflater ( ) in DialogFragment
Smack 4 . 1 . 0 - rc4
Adding npm - debug .
Fixed a bug where HttpMessage . RemoveHeader ( ) leads to local callers to decide
Added travis - ci support
Revert " force monospace font in qt preview "
Ignore Update ' modules / apps / collaboration / announcements / .
Added a CHANGES . Txt file .
Install API 23 on Travis
Removed ' Master ' from names . Txt
Add SBT directory to Travis CI cache
GROOVY - 816 - import breaks example
Fix url - caster .
Only define _GNU_SOURCE if it wasn ' t used ( IDEA - 157793 )
Adding namespace , forgot to set initialized by default
Add HADOOP - 12843 to 2 . 8 . 0 in CHANGES . Txt .
Removing appinfo . Jar
Don ' t reference the enclosing type instance when it ' s not used ( now ) .
Ignore Update ' modules / apps / foundation / portal - store / .
Add the redirect to the new location
Remove the empty file accidentally checked it with HADOOP - 7249 .
Fixing deprecated gradle property
Add missing default config ( # 2 )
Added missing migration file
Updating CHANGES . Txt for CASSANDRA - 5903
Implement GC , because it does not need to
Fix broken test dependencies in example
Add header icon
Remove old image
Remove unused files ( irrelevant )
Setting version to 1 . 0 . 61
