Update changelog for 1 . 6 . 1
Update chagelog
Ignore Update ' modules / apps / foundation / portal / .
Add missing image for Android 1 . 5
LPS - 68814 Add missing test attribute
Adding adapter for android .
Added 0 . 4 . 1 hotfix
Upgrade sonar - update - center - common to 1 . 4
Removing comm files from jre since they needn ' t be in there
Fix # define conflicts by externs
Updated changelog
CursorToBulkCursorAdapter . Close must call mCursor . Close instead of mCursor . Deactivate .
Ignore Update ' modules / apps / web - experience / iframe / .
Updated README . Md
Prepare release checkstyle - 7 . 1 . 1
Pass - yaml to ds builds to generate full location
Bump Flow version
Fixed a typo in bbb - conf
JAL - 35 Add image notes to non - proprietary module
Add bin to gitignore
Removed non - needed imports
Fixed typo in sample example
Setting version to 1 . 0 . 118 - SNAPSHOT
Ignore Update ' modules / apps / foundation / roles / .
Revert " LPS - 51081 Ignore unit tests for now
Added JID to enable UTF - 8 without packets and building .
Fix missing closing bracket
Ignore Update ' modules / apps / foundation / petra / .
LRQA - 22807 Remove Wildfly + mariaDB smoke "
Fix build error
Add the notice file for the theme in the wiki
Make notest .
Improve test data to include failing script
Ignore target directory
Ignore Update ' modules / apps / foundation / portal - cache / .
Add makefile so a path for all components and laboratory components .
Changed title in list in README . Md .
Removed unused art file
Ignore Update ' modules / apps / web - experience / asset / .
Ignore Update ' modules / apps / foundation / contacts / .
Prepare release v1 . 1
Bump engine . Io - client
Fix error in docking station on chunk unload , fixes # 2898
Prepare version 18 . 0 . 1 .
Prepare 3 . 0 . 0 .
Do not use the lastest tool on travis
Fixed type signature of chr ( ) for Python 3 ( PY - 9042 )
Provides a more recent snapshot of the wiki
DO NOT MERGE - Updated ADB icon
Add a necessary javadoc for .
Added HdrHistohram . Jar to base directory for convenient downloading
Created tech - debt entries for all components and laboratory components .
HHH - 8733 - General build cleanup - hibernate - testing
Removed TODO in TelecomManager .
Added STORM - 990 to CHANGELOG . Md
Update to the latest support lib
Ignore Update ' modules / apps / collaboration / document - library / .
Bumped version number to 1 . 3 . 0
Remove " incubating ' classifier .
Added professional image
Updated readme
Remove mail notifications ( for now ) from travis
Corrected PImage . SetModified ( ) so mx2 and my2 is width .
Do not load twice message appearance ( and 1 . 6 )
Added Recognizer . RemoveErrorListeners ( ) to Recognizer . Py
Fix typo in build
Fixed build . Properties
Setting version to 1 . 0 . 14 - SNAPSHOT
Bump version for 0 . 9 . 2 release
Add CHANGELOG . Md for v1 . 2 . 1 .
Add icons
Ignore Update ' modules / apps / foundation / contacts / .
Removed sleep from clickOnView ( ) as requested by issue - 333
Update NEWS
Method doesn ' t overwrite toString
Upgraded the version in the parent pom references in our example components to 3 .
Added new Aztec , PDF417 screenshots for the Market .
Created tech - debt entries for all components and laboratory components .
Add gitignore file
JAL - 36 Add image notes to good for proprietary licenses
Update linux - x86 natives
Removed tag flyway - parent - 1 . 6
Fix typo in iterate
Added STORM - 902 to Changelog
Remove @ Nullable method call method method
Remove spurious stdout .
Ignore Update ' modules / apps / foundation / login / .
Fixed the text of the text that was causing it in the buttons
LPS - 44526 New User does not have administration permissions in New Site break
Changed version file to Dev Build to prevent confusion .
Remove debug var from webpack types .
Prepare for next development iteration
Add build and eclipse files to .
Ignore Update ' modules / apps / web - experience / asset / .
Added STORM - 1157 to Changelog
Added Android SDK Platform with API level 16 to Travis build file
Ignore Update ' modules / apps / web - experience / export - import / .
Updates the opus binaries in the PortAudio support from its latest source / r7982 .
Added support for Logitech HD Pro Webcam C920 on Windows
Don ' t hold stlport .
Require Maven 3 . 0 .
Removed bad impl target from library generator ( fixes # 444 )
Updated CHANGELOG . Txt .
Update gitignore
Allow animation instead of code in WebView app , closes # 300 .
Ignore Update ' modules / apps / foundation / portal - scripting / .
Removed the accidentally added file guys
Suppress warning
Added missing list of the end of table
Remove unused code .
Fix typo in java . Yml .
Add support for Travis - CI
Bump common for 4 . 2 . 2 ref
Create README . Md
Ignore Update ' modules / apps / web - experience / trash / .
Add a simple travis configuration
Added surround with tests and replacing work on Windows on Windows .
Help ID ( PY - 4116 )
Ignore Update ' modules / apps / foundation / login / .
Add platform - tools version .
Fixed BlockFluid . InMilliseconds ( ) instead of error
Updated Netty version .
Added _collections to list change
Increment gradle build tools
Removed new files for HDFS - client .
Added a new high dpi icon ( though not yet on Windows )
Adding STORM - 1472 to Changelog
Update analytics plugin to 1 . 3 . 1
Ignore Update ' modules / apps / collaboration / wiki / .
Add icon
Bump version from 1 . 7 . 8 - > 1 . 7 . 9
GRAILS - 5691 - remove some code that was accidentally left in ` view "
Delete git . Png .
Add todos
Ignore Update ' modules / apps / foundation / portal - search / .
Update libwebp
LPS - 43715 Ignore the project . Gradle files , should ignore the module
MinecraftForge / FML @ d00feb58c762b0bbc506d79faf1ce40bc96732e9 Remove debug code that was causing console spam in Forge .
Remove opendk as it ' s not present
Ignore Update ' modules / apps / collaboration / comment / .
Set component configurations correctly for trident spouts
LPS - 47071 Add wrong component to checkAllBox util from deprecated - import
Update CHANGES ( fixes # 27
Set correct permissions on the script .
Now removed connect - js submodule
Set snapshot version for next development cycle .
Change EditDistanceJoiner . Jar to newest version
Add missing image
Ignore Update ' modules / apps / collaboration / message - boards / .
Setting default name for multi - project
Starting 0 . 5 . 5 - SNAPSHOT
Fix XMLHttpRequest . Abort ( ) not functional due to incorrect lazy loading in RCTNetworking ObjC module
Fix typo in README . Md
Ignore Update ' modules / apps / web - experience / layout / .
Smack 4 . 2 . 0 - alpha3
Add vector . Jar to build script
Ignore Update ' modules / apps / web - experience / trash / .
Don ' t use 54321 in the intention test
Update linux - arm native
Updating Alloy to rev . 81636
Remove the linker flag from RELEASENOTES . Md
Updated version name / code
Updated CHANGES - updated version
Only apply signing to deploy phase
Changed travis config to use Java 8
Remove jre6 support .
Ignore all gen
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Remove an unused variable in svm . Py
Added cycle to the deploy profile
Added explorer2 to deploy profile
Updated changelog
Removed unnecessary comment in AndroidManifest . Xml
Ignore Update ' modules / apps / foundation / portal / .
Updated changelog
Removed dummy jar file .
LPS - 65492 Ignore SF for now
LRQA - 61420 Add empty property to track order path to testray
Added makeGLMModel call to python .
Fix issue where history is no longer used ( IDEA - 81507 )
Removed otp - geocoder from top - level POM
Fix build message
Removed old imports at / python / bin / *
Updated demo art
Ignore Update ' modules / apps / web - experience / application - list / .
Add missing image for 1 . 2 . 1
Setting version to 1 . 0 . 69
Fixed Travis
Add 2 . 4 . 4 to make - 1 . 0 . 1 that will be used the of been upload for Mac )
Remove unused imports in graylog2 . Sh
Updated changelog
Ignore Update ' modules / apps / collaboration / directory / .
Remove unused imports from graylog2 . Sh .
Adding gitignore file
Remove unused images
Remove unused import statement
Add missing SideOnly .
Removed tag roboguice - 1 . 1 . 1
Ignore Update ' modules / apps / web - experience / journal / .
Added STORM - 1104 to Changelog
Add STORM - 118 to CHANGELOG
Updated Changelog for STORM - 421
Add lib dir
Remove unused variable in Tests
GRAILS - 6290 removed println
Ignore IntelliJ IDEA files .
Ignore Update ' modules / apps / collaboration / wiki / .
Remove @ PrivateApi annotation
Upgrading BC to 1 . 10 . 1
Remove ElegantPresentations import
Regenerate gradle - wrapper . Jar with 1 . 9 - rc - 4
Changed min release version to 3 . 0 . 0
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Fixed partial delete ( # 642 )
Remove unused jar
Ignore * .
Bump version to 1 . 5 . 0
Update lwjgl to latest 2 . 8 . 0 - nightly
Added tag 0 . 5 for changeset f241352a0b11
Make sure .
Make every language have its end of experimental API
Remove alpha5 bwc indexes
Changed version
Added relative path to the parent POM so that the user won ' t need to
Add missing image
Fixed dialog in comments ( ) ( called instead of state )
Add 2 . 4 . 0 to packaging tests list
Added Jake Wharton to contributors .
LPS - 52368 move icon
Prepare next release v0 . 88 . 1 - SNAPSHOT
Adding words suggested by users
Changed version to 3 . 0 . 1 .
Fixed typo in JedisCluster del command
Add some icons
Remove an unused import .
Changed email address for travis
Ignore Update ' modules / apps / foundation / frontend - css / .
Add link to CHANGELOG
Prepare version 20 - beta1 .
Require Maven 3 . 0 . 1 or greater , because we use that API .
Fix merge conflict resolution
Removed @ PrivateApi annotation ; not needed since PacketTransceiver is in the impl package , and therefor should not be accessed by the outside world
Ignore Update ' modules / apps / foundation / portal - template / .
Ignore Update ' modules / apps / foundation / portal - search / .
Ignore Update ' modules / apps / collaboration / wiki / .
Ignore Update ' modules / apps / foundation / roles / .
Fix typo which cause stack overflow if children ( ) was called
Revert " LPS - 46198 Added a jar that is been solved .
Add release notes to readme
Create grade files to appease NetBeans plugin
Add support lib to SeriesGuide project , too .
Revert " Ignore the generated directories to .
LEP - 4510 - Themes should contain styling for commonly used by comments .
Remove superfluous method for method ( ) so it is already open on Android v2 . 5
Removed bold font icon
Fix a bug of backsided objects in WebView
Add default optimized imports for radio for Windows .
Activates microphone sensibility modification via Windows CoreAudio ( 64bits version only for Vista / 7 / 8 ) .
HHH - 8829 Set proguard version to UTF - 8
Bump up parent pom version to 3 . 1 . 1
Revert " Revert " Use my full file for my common builds
Move Runits for GLRM set loss function by individual column to passing thanks to Michal ' s fix
Added a dummy file to the eclipse project ( * )
Added high res app icon .
Don ' t force refresh if data is closed
Added missing jar for people not using maven .
See diff
Remove unnecessary dependency on Clang headers .
Removing unused p . GetState ( )
LPS - 55000 update sdk with jspc
JAL - 35 Add image notes to non - proprietary licenses
Fixed error in config for now
Add description for maven - plugin , fixes # 196
Ignore blogs - demo 1 . 0 . 0 prep next
Ignore Update ' modules / apps / foundation / users - admin / .
Don ' t need the core jar .
Added gitignore .
On behalf of Vincent Lucas , commits a fix to the calculation of the Last SR ( LSR ) timestamp for the Sender Report RTCP packet .
Move tests to elasticsearch test framework
Fix typo in build . Properties
Add text icon for Windows template
Remove italics from note_block_user_header
Move this test to standalone , as it ' s useless in core ( no languages available there )
Removed the doc file .
Added titan + rexster image
Remove the background annotation from widget when user , so it is not stuck .
Do not request focus to its own exception ( IDEA - 81507 )
Fix pom . Xml as part of pom .
Added a redirect for all components ( # 1041 )
LPS - 52259 Asset Tags Cloud - Moves icon
Updated changelog
Ignore Update ' modules / apps / marketplace / .
Removing @ Repeat . Happy .
Updated gitignore file
Bump up revision number .
Removed issue labels from the issues ' summary that were in the " Release 2 . 1 . 0 " help page .
Added STORM - 1104 to Changelog
Fixed PY - 6543 Django manage . Py commands not working
Ignore Update ' modules / apps / foundation / frontend - theme / .
Added new RIL command for sending ack to solicited async and unsolicited msg .
Fix a deadlock in the script
Update changelog
Ignore Update ' modules / apps / collaboration / microblogs / .
Prepare for next development iteration
Fix issue with DimensionManager . ShouldLoadSpawn
Don ' t reference the size of the pages
Removed bottom margin in TicTacToe example
Prepare version 1 . 0 . 3 .
Updated Talk notification icon
Don ` t hardcode the android sdk path in the build script before you push ( im looking at you Dave )
Updating Alloy to rev . 81636
Push version to 12 - beta8 , 228 .
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Upgraded maven - compiler - plugin version .
Updated icon
Revert " Update Android android plugin to 0 . 14 . 2 . "
Ignore Update ' modules / apps / web - experience / asset / .
Disable hand type of reload of reload to run ( IDEA - 157793 )
Added bin / to ignored files for Eclipse users
Remove unnecessary prop
Created tech - debt entries for all components and laboratory components .
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Added STORM - 820 to Changelog
Rebuilds the Windows x64 binary of the PortAudio support from its latest source / r7982 .
Removed some note of the library that was not necessary
Added STORM - 1213 to Changlog
LPS - 1060 - Theme positioning can break the Flash Uploader
Moved DelegatingAuthenticationEntryPointTest - context . Xml to test / resources
Ignore Update ' modules / apps / web - experience / staging / .
Fix bug that meant test always hung until the background process twice
Updated copyright in NEWS
Changed URL to www . Robovm . Com in README . Md .
Remove unused import from javadoc class
Add missing return statement
Set default active by default ( temporarily ) in pom . Xml .
Fix compile compilation
Ignoring project errors in example processes ( # 2162 )
Added assets
Update target to support build
LRQA - 14606 Add test property for calendar - portlet
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Remove unused files .
Update the alias in the server side trust store to match the renaming used for the certificate .
Updates hcatalog sep version in 1 . 5 . 2 .
Modify install_fbthrift .
Pushing the log width .
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Fixing the build error in getopt instead of install ( # 57 )
Ignore Update ' modules / apps / screens / .
Revert " Revert " prepare to android - web POM
IDEA - 117674 please rebuild and commit runnerw . Exe
Set version for 0 . 9 . 2 release
Added STORM - 902 to Changelog
Remove whitespacek
Fixed css for non - 8
Updated changelog
LRQA - 22807 Remove Wildfly + mariaDB smoke while we investigate
Reduce heap timeout to UTF - 8 triggered by Java 7 .
Remove unused file .
Added a Composite Configuration Diagram to use in the Wiki .
Die unused jre .
Ignore Update ' modules / apps / foundation / hello - world / .
Remove Y
Ignore Update ' modules / apps / foundation / monitoring / .
Add maven central date to CHANGES . Txt
Add image for launching on the wiki
Add gitignore
Fix typo in readme
Add support for ALTER TABLE MODIFY in CUBRID
Ignore IntelliJ - generated files
Fix a minor comment in r1095367
Remove redundant task dependency in pom . Xml
Add isDebug method .
Handle KeyboardInterrupt from 5 . 1 ( CASSANDRA - 9042 )
Pushed 2 . 8 . 1 again , fixed a small UI issue .
Ignore Update ' modules / apps / collaboration / item - selector / .
LPS - 55274 don ' t check this in
Add the shutdown command to the service provider
Test travis CI .
Add STORM - 1594 to CHANGELOG
Add function graphic
Slightly increate the drag bezel button on shutdown ( ) method ( IDEA - )
Fixed typo in reference docs
Don ' t reference the enclosing type instance when it ' s not used .
Removed spurious import .
Added SQLDialect
Revert " Restrict S3 deployment to actual tarball "
LPS - 47589 Fix broken version .
Prepare release storm - hbase - 0 . 1 . 2
Moved AboutDialog to correct location
Fix msn log in .
Ignore Update ' modules / apps / collaboration / wiki / .
Make View # setBackgroundDrawable a no - op if setting the same background .
Add Thumbs . Db to gitignore
Upgrade parent pom version .
Don ' t tweak unsaved files in todos . Txt
Ignore Update ' modules / apps / foundation / frontend - theme / .
Add dummy shiro . Ini to cleanup logs
Upgrade netflixoss Nebula plugin to 3 . 2 . 2
Update gitignore
Updated the Xmx for running CI builds
Remove oraclejdk8 from allow_failures
Ignore emacs backup files
Ignore target , because that is generated code
Ignore Update ' modules / apps / screens / .
Remove unused readme
Remove the accidentally Add action icon in the example file
Changed default port size for drawer list button
Prepare 0 . 6 release
Add OC version to version .
Add header image
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Added the notice file to the new dpi version .
Add good icon for free app .
Add analysis - icu module
Described changes to French Grammar rules in CHANGES . Txt
Removed some import .
Adding datasketches module to top level pom
SONAR - 3626 Fix test for onPaddingChanged ( )
Remove unsed check for simulator .
Added new res directory for the Market .
Provides a more recent snapshot of the wiki
Remove extra spacing
Not reinitializing the backing arrays for matrices and lights .
Updated retention to ' binary ' for LowPriorityInOverloadResolution
Testing travis - ci
Ignore Update ' modules / apps / foundation / portal / .
LPS - 52093 moves icon
Added another TODO for docs .
Fix log configuration for now
Remove x bits from java files
Ignore Update ' modules / apps / web - experience / site - navigation / .
Add ptr - demo - library .
Added parsing of Cython include statements
LPS - 15662 Options icon in portlet style bar
Remove unused comments in StringUtils
Always hide the delay on window
Added a Bitdeli badge to README . Md .
Make sure that there is no such in order to make it on slow systems
Updated changelog
Change our uri of the submodule
Fix layout script for builtins ( # 4191 )
Fix failing test
Added class diagram for free version .
Added professional image for parallel users
Ignore Update ' modules / apps / collaboration / document - library / .
Added missing SPDY npn - boot . Jar file to Openfire lib / dist
Fix the fastscroll thumb asset in hdpi .
Add image for recycle listitem
Revert " Caching dependencies to speed up PR builds "
Remove import hashmap statement since it ' s not necessary
Ignore Update ' modules / apps / foundation / frontend - js / .
Ignore Update ' modules / apps / foundation / login / .
Add another CHANGES . Txt for 3919
Keep org . Jetbrains . Kotlin .
Ignore Update ' modules / apps / foundation / portal - settings / .
Ignore IntelliJ IDEA files
Updating Alloy to e79a782 ; LPS - 13554
Don ' t rethrow RuntimeExceptions , refs # 292
Removed unused method from AnimatorSet .
GRADLE - 1355 - Ignore generated Eclipse configurations files , and eclipse output
LPS - 46847 - inline editor links should have a cursor pointer
Added files via upload
Fix warning error
Fixed incorrect header in color ( # 63 )
LPS - 67460 prep next , use latest
Ignore Update ' modules / apps / marketplace / .
Ignore Update ' modules / apps / foundation / roles / .
Add CAP_BLOCK_SUSPEND to system server
Ignore Update ' modules / apps / sync / .
Fixing the build problem with camel - jaxb
Move Runits for GLRM set loss function by individual column to passing thanks to Michal ' s fix
Revert " LPS - 51081 Fix " deploy " " " " " " " " " " " module "
Remove redundant version number from application . Properties ( grails plugin )
Ignore derby log anywhere
LPS - 52368 move icon
Update applet zip
DO NOT MERGE - Updated textfield pressed states
Ignore Update ' modules / apps / foundation / frontend - js / .
Added missing SPDY npn - boot . Jar file to Openfire lib / resources
Fix proguard name name - > with native build .
Fix Portuguese docs to 0 . 6 . 1
Fix proguard
Fix the archive icon
Added STORM - 1258 to Changelog
Ignore Update ' modules / apps / collaboration / message - boards / .
Ignore Update ' modules / apps / collaboration / wiki / .
Add 0 . 8 . 5 to CHANGELOG
Add notes about JDI
Add good icon for free app .
Delete demo2 - badge .
HHH - 17280 - Remove extra line from ' var '
Ignore Update ' modules / apps / foundation / frontend - js / .
Revert " AudioFlinger does not need libmedia any more
Added luminescense back to NR
LPS - 67503 prep next , use latest
Fix build . Gradle
Fixed ArraySeq . IsExpanded
Enabled failing test as tests .
Adds methods for broker to integrate Zookeeper based broker .
Add ES5_CLASS_EXTENDING_ES6_CLASS to TypeCheck . ALL_DIAGNOSTICS so that it can be turned off
Activate Docker - based build in Travis CI
Fixed a compile error .
Added STORM - 613 to changelog .
Don ' t show local exceptions when entering to shutdown
Add default toString to ThreadSafeLazyLoadedIvoryTower .
Disable closing paren in code key
Updated REAME . Md .
Updating to Gremlin 0 . 8
Ignore Update ' modules / apps / web - experience / asset / .
Bump react - native - cli version
Ignore Update ' modules / apps / collaboration / blogs / .
Fixed margins on Wildfire ( # 144 )
Remove sorting on stack thread
Make sound run ( IDEA ; reviewed by Thejas Nair )
LPS - 49633 updated jodd . Jar with all the fixes
Created tech - debt entries for all components and laboratory components .
Revert " LPS - 52740 Language properties "
Ignore Update ' modules / apps / collaboration / notifications / .
Add missing Javadoc for View . SetFilterTouchesWhenObscured .
Make EntityJoinWorldEvent Cancelable properly
Update travis config
Don ' t use the icon that this is not set by white ; don ' t do anything correctly .
Prepare for next development iteration
Add frodo configuration scope to build . Gradle
Built the latest snapshot
Ignore Update ' modules / apps / collaboration / comment / .
Changed itests to be part of the main Hive build ( Zoltan Haindrich via Siddharth Seth )
Added padding to sourceforge image
Added packaging and refactored libraries around
Update target API to use Android project
Git ignore gradle . Properties
Updated version number
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Don ' t accept " Leereichen " , probably a typo of " Leerzeichen "
Fix a bug where HttpMessage . RemoveHeader ( ) leads to a dangling pointer in the internal input settings
Added my description to the filter table .
Incremented the version code of the sample project for GPlay upload .
Bump pegasus to 1 . 9 . 7
Updated changelog
Fixed typo in Constructors section .
Added a ( MRI ) hint , so that it can have updated reference in README . Md
Remove unnecessary return statement
Decreasing default max connections per node to 10
Update README . Md
Removed unnecessary return statement in LineageFileOutStream
Adding IDE related files to .
Update changes
Ignore Update ' modules / apps / collaboration / directory / .
Remove unnecessary travis .
Moved index . Html to GoogleChartsExample folder
Remove bogus unreferenced classpathref ( PY - 4542 ) .
Fix finalization
Commented out the package tag used by javadoc plugin , because javadoc was confused
Ignore Update ' modules / apps / foundation / hello - velocity / .
Add profile back to top level so we ' t complain
Updated ChangeLog entry
Fixed typo in comment
Fixed bug in code names with new right list ( PY - 15907 )
Remove unused field from listview .
Prepare version 26 . 0 . 1 .
Set correct permissions on the script .
Add missing jar file
Remove space so easy to parse
Update to latest android gradle build 1 . 0 . 0
Bump version for 0 . 9 . 0 release
Fix a problem issue
Fix evaluation of output for unknown buffer
Delete old readme
Add url as source to run
Remove @ nosideeffects from DataTransferItem . Prototype . GetAsString ( )
Modify the name of LogHelper to be consistent with initialization execution
Add new image for Android 0 . 8 .
Move local_mapred_error_cache .
Default native proto to correct port in Config
Remove spurious print statement in AudioAttributes
Add @ Override annotation
Bumped version
Change help refresh if there is not find an endless loop
Remove unused import from API code
Added Oliver for the contributor
Remove grailsCentral ( ) from BuildConfig . Groovy as it was available
Remove @ Override from interface method impl
Modify Dockerfile
Ignore Update ' modules / apps / collaboration / flags / .
Add alpha channel to project sharing icon
Added STORM - 1553 to Changelog
Remove - - debug option
Include tests in unit test file .
Turn off active by default on tests
Updated Vietnamese translation
Remove unused import .
Added updating to master
Push version to 16 , 15021 .
Updated build . Properties for 0 . 3
Added missing CHANGES entry for CASSANDRA - 1382
Update xsoup to 0 . 2 . 1 # 75
Woops java type checks !
Update travis
Documented the enhancement for log dumper
Updated reference to oc - library
Remove unused extern in BufferUtils
Ignore Update ' modules / apps / web - experience / portlet - configuration / .
Fix warning in comment .
Added a TBD section for the JSON package
Delete test . Yml
Update changelog
Prepare for next development iteration
Added hidden - related files to gitignore
Moved InMemoryXmlApplicationContext to test src as it is only used in tests .
Updated Tower icon ( IDEADEV - 125317 ) .
Make browser for cloud . 7 ( PY - 6191 ) .
Updated version
Bump up version
Created tech - debt entries for all components and laboratory components .
Fixed README . Md for v1 . 1 . 2 .
Add NOTICE file
Ignore Update ' modules / apps / foundation / portal - search / .
Added # hashCode ( ) to JID to be fully comparable .
Fix typo .
Update README . Md for 1 . 1 release
IDEA - 43728 Provide a way to step in a chosen thread
Update imports
Make MarkupBuilder . GetMkp ( ) return MarkupBuilderHelper instead of Object
Add additional key for fullscreen on iOS7
Updated gradle to version 2 . 6 . 1
Remove the xwalk_core_library ' s ' buffer ' from build . Gradle
Update doc commit pointer name
Adds toString ( ) to injection since new code .
Added support for the Firebird test , @ 2678 )
Update linux - arm native
LPS - 46132 Add a line breaek since it ' s params1 vs . Params2
Update crate - math3 1 . 0 - rc - 8
Fix whitespace for on host exclusion ( prevents checkstyle from Thejas Nair )
Fix an issue where the non - printable character as an error that could be opened for non - array .
Prepare version 20 - beta2 .
Git ignore gradle . Properties
Fix gif url
Added the Gradle and .
Add Russian disambiguator
Add images
Prepared for next development iteration
Ignore Update ' modules / apps / foundation / frontend - taglib / .
WFLY - 6768 ServletResourceManager does not implement isResourceChangeListenerSupported correctly
Do not log words message by default
Add STORM - 118 to CHANGELOG . Md
Remove runit_NOPASS_Rdoc_prcomp .
Remove ' performanceTest ' entries from .
Build JUnit with JDK 8 on Travis .
Adding updating rule for svenson JSON databind
Fix typo for serializers for translators .
" Updating samples to reflect recent changes . "
Remove unneeded SideOnly .
LPS - 64531 don ' t do this .
Remove bottom padding for smart enter test
Added STORM - 1361 to changelog
Don ' t reference the enclosing type instance when it ' s not used ( memory ) .
Fix random crash in emulator ( # 523 )
Updated ChangeLog
Use the better IOException type ( any other exception is totally unexpected )
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . Otherwise
Change the SingleFilePageSwapperFactory implementation of UnresolvedDependencyResult . GetFailure ( ) .
Added release date for 2 . 8 . 6beta
LRQA - 18527 Append the full path for mirrors - get
Fixed error in config_imports ( # 8 )
Fixed bug in method snippet
Execute tests in forked JVM
LRQA - 24891 Add portal . Properties to prevent order in order to solve com . 3 . 3 snapshot
Only use jdk8 in travis
Fix failing test , account for url - mappings - report
DO NOT MERGE - Updated ADB icon
Ignore Update ' modules / apps / collaboration / item - selector / .
Add flowdock notification to Travis build .
Also remove block from mLostBlocks for delete .
Bumped version to 0 . 2 . 4
Rename booklet
Updating Alloy to rev . 81636
Ignore Update ' modules / apps / foundation / frontend - theme / .
Update natives
Do not use any in release tag .
Updated TODO
Make FileStack explicit
Ignore Update ' modules / apps / collaboration / wiki / .
Added project example to copy / bin script
Removed unused p . TearDown ( )
Make every language have its own preview page by default .
Add empty image for the wiki .
Fixing redefined test warning
Don ' t use stlport .
Add constant for rstudio user identity display
Don ' t force refresh if data is taken from cache
Ignore Update ' modules / apps / foundation / petra / .
Added STORM - 1143 to CHANGELOG . Md
Add appetize . Io token to travis build
Remove silly shadow
Updated build . Gradle
Updating Alloy to e79a782 ; LPS - 13554
Updated the zip file .
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Add transparency to dark check marks .
Do not show missing sys import .
Remove POS JJ from ' ie '
Add a Composite Configuration Diagram to use in the Wiki .
Modified travis containers .
Switch master to 4 . 1 . 0 . BUILD - SNAPSHOT
Add extra - android - m2repository dependency in travis
Ignore Update ' modules / apps / web - experience / product - navigation / .
Updated eurosport cert so that SSL tests now works again
Remove unused jar file
Remove DEVELOP . Rst dependency from the binary package
Ignore Update ' modules / apps / foundation / frontend - js / .
Add dependency to build file since this run already exists
Prepare next development version .
Created tech - debt entries for all components and laboratory components .
Updating Alloy to rev . 81636
Ignore Update ' modules / apps / web - experience / export - import / .
SONAR - 5736 The calling HelpshiftHelper . Shutdown into shutdown ( ) method
Back svnkit 8179 since 8183 does not perform move correctly
Ignore Update ' modules / apps / marketplace / .
Bump release version to 4 . 0 . 4
Added professional image for parallel gateway process
Fix leak of stackTrace in java / lang / Throwable .
LRQA - 18527 Append the full path for now .
Added spring - binaries .
Fix UIExplorer tabbar test
Add SQL Console module to jOOQ - Copy authors . Md
Can ' t export a movie - Error returned from OMX API in ducati
Upgrading parent version .
Remove unused import from AnimatorSet .
Add Travis configuration .
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Update gitignore
Exclude sun . Nio . Ch . DirectBuffer from animal - sniffer check
Copy the PApplet ( ) method in the view is disabled
Fix memory leak in fbobjc
Removed issue labels from the issues ' summary that were in the " Release 2 . 1 . 0 " help page .
Ignore Update ' modules / apps / foundation / portal - configuration / .
Added missing return statement for debugging class
Upgraded the version in the parent pom references in our example components to 3 .
Correct the correct link in the README
Bump common for 4 . 2 . 2 ref
Updated changelog
Update build tools version again .
Ignore Update ' modules / apps / web - experience / journal / .
Removed blankline
Revert " Restrict S3 deployment to actual tarball "
LPS - 46132 Add a line break since it ' s params1 vs . Params2
Added a link to the new location .
Remove unused local variable in ` BuildRuleSuccess . Property ` ( # 421 )
@ Deprecated does not have effect in Groovy
Make every language have its own preview ( PY - 5722 )
Update Guava to 10 . 0 . 1
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Ignore Update ' modules / apps / foundation / portal - security / .
Allow action must be passed instead of leaking ( enabled )
Improves the hotplug response times on Windows which may be noticeably prolonged due to thread scheduling in cases of Windows Multimedia reporting lack of a device driver .
Enable coverage to work with java 8 ( IDEA - 96364 )
Removed unnecessary tag
Bump commons - pool2 to latest version
Remove javaVersion task from gradle script
ZEPPELIN - 359 add NOTICE and DISCLAIMER in the binary package list
Allow content packs to avoid grok patterns message
Adding NightlyBuildID . Java to .
Adding STORM - 714 to CHANGELOG . Md
Removed grailsCentral ( ) from BuildConfig . Jar
Removing @ SuppressWarnings ( ) from BasicCacheTest
Make notest .
Bump version for 0 . 9 . 5 release
Fix copy / paste error in isKeyguardLocked ( )
Fixed a typo in svm . Cpp
Revert " LPS - 64991 Don ' t run this " ? "
Added Pavlo Lysov to the list of contributors
Use the latest lib snapshot
Bump up version number .
Fix a bug where the buffer is disabled .
Ignore Update ' modules / apps / foundation / petra / .
Fix config
Ignore Update ' modules / apps / foundation / portal - cache / .
Prepared for next development iteration
Fixed typo in java . Xml
Add more height for hdpi . Jpg ( IDEA - 128769 , IDEA - )
Add new image for the theme in the wiki
Updated banner to show 0 . 63 - Beta
Updated changelog
Ignore Update ' modules / apps / foundation / frontend - js / .
Fixes java 1 . 5 compatibility .
Adding STORM - 625 to changelog .
Revert " Revert " LPS - 48038 SF "
Ignore Update ' modules / apps / web - experience / site / .
Ignore Update ' modules / apps / web - experience / site / .
Added files via upload
Prepare release jfinal - 1 . 5
Updated changelog
Add words suggested by users
Remove background color from welcome fragment
Updated user size for BigBlueButton 0 . 81
Ignore Update ' modules / apps / foundation / web - proxy / .
Added and initialize README . Md
Remove unused test file
Remove an overzealous call from the end of batch ( ) .
Prepare release acra - 4 . 6 . 0
Added class diagram .
Add info description to readme
When instantiating an account , set the default color to be consistent
Bumped curr . Release to 0 . 3 . 1
Add header file
Ignore Update ' modules / apps / collaboration / message - boards / .
Add jamm - 0 . 3 . 5 .
Ignore grails - test - domain - class / bin
Removing old jars from spring - algos .
Updated target to use version ( Lollipop )
Upgraded netty to 4 . 0 . 22
Disable tests for maven - tests ( * # 806 )
LPS - 54590 Add a line break since it ' s params1 vs . Params2
Corrected the groovyBundleVersion in build . Properties for the new 1 . 8 . 0 - beta - 1 branch .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Fix NPE in Box . ToString ( ) .
Fix incorrect closing bracket ( # 642 )
Removed redundant directory src / tests from bbb - client
Removing liquibase - osgi from parent project pom
Ignore Update ' modules / apps / collaboration / bookmarks / .
Update Gradle plugin to 0 . 13 . 2
Updated ChangeLog
Improves the hotplug response times on Windows which may be noticeably prolonged due to thread scheduling in cases of Windows Multimedia reporting lack of a device driver .
Updated Vanilla dependency to 1 . 3 . 0 - SNAPSHOT .
Added issuers list of Java 1 . 5 ( PY - )
Removed empty testing file .
Replace the busy sound
Extend PhoneAccount parceling ( 1 API
Ignore Update ' modules / apps / web - experience / asset / .
Added new screenshots
Remove executable bit .
We don ' t need these classes any longer
Ignore calevent - importer 1 . 0 . 0 prep next
Remove Thumbs . Db from gitignore
Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode .
Update native win32 - x86
Fixed Android Support library for Cropper .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fix travis config
Remove unused import
Simplified dbget .
Update sparc natives
Fix typo in beans . Txt .
Setting version to 1 . 0 . 10
Add jar file for zan
Removed unnecessary lib file .
Fixed path pointer check with spaces in bbb - client
Ignore Update ' modules / apps / foundation / portal - scripting / .
Revised run chunk icon
Remove debug statement from completion ( no longer activities
Restore width of TDs in emulator ( # 523 )
Added baseName for uberjar task
Add comment for CASSANDRA - 5542
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Prepare 4 . 2 . 0 - alpha1 - SNAPSHOT
Fixed a bug where the end of a SQLException so it is needed .
Set correct permissions on the script .
Removed an obsolete import .
Ignore Update ' modules / apps / collaboration / directory / .
Ignore Update ' modules / apps / foundation / petra / .
Switch the port name to become the path of spaces .
Ignore Update ' modules / apps / collaboration / wiki / .
Updated changelog
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Don ' t run test !
Updated JAIN - SIP RI ( fixes # 833 )
Set unit tests from maven - javadoc - plugin
Removed roles from neo4j recipe , since they can not be part of a recipe
Updating Alloy to rev . 81636
Upgraded parent version .
Fix race condition in ZRTP state engine
Removed unused imports in BufferUtils
Added STORM - 162 to Changelog
Smack 4 . 0 . 4 - SNAPSHOT
Bump up version
Updating Alloy to rev . 81636
Delete unused enum value from method . Js
Updated changelog
Ignore Update ' modules / apps / foundation / frontend - css / .
Set source encoding to UTF - 8 ( fixes # 192 )
Enable on_start notification always
Temporarily exclude parquet dependency .
Add STORM - 1055 to CHANGELOG . Md
Remove cruft
Ignore Update ' modules / apps / marketplace / .
Fixed a bug in ScanSettings constructor .
Don ' t accept " Leereichen "
Fix ci compilation .
Don ' t stop the file_monitor in the render
Delete MalmoMissionTable_CurrentTasks_v . 2 . 0 .
GRAILS - 2195 ' s patch created a regression , so I ' m reverting the previous change
Add icon for free app
Released OrientDB 2 . 1 . 0 GA
Adding missing BenchmarkRunner config for svenson JSON databind
Update http - client , fixes race conditions
Updated paper for language sweep and added code sample
Fix bug 4099023 - Phantom clicks on some websites
Ignore Update ' modules / apps / collaboration / bookmarks / .
Prepare for next development iteration
Fixed small typo in permalink
Add GC thread to RSGL .
Ignore Update ' modules / apps / foundation / server / .
Adding codecov support to travis
Ctrl - Shift - W triggers NPE ( IDEADEV - 15817 )
Changed version number so I could push the new version to dist .
Remove unnecessary comment .
Moved orphaned Groovy script
Bump common for backwards compatibility fix for older OS X git .
Ignore Update ' modules / apps / web - experience / layout / .
Remove impute . Flow from index . List
Bumping commit name .
Removed unused import statement
Ignore Update ' modules / apps / collaboration / message - boards / .
Changed people to latest version
Ignore Update ' modules / apps / foundation / frontend - css / .
Modify Makefile
Release pegasus 2 . 6 . 0 .
When marking a message for methods ( ) for the Request instead of METHOD .
Revert since it breaks a unit test
Added Esperanto description for Khmer .
Adding a CHANGES . Txt file for HDFS - 1623 .
Added missing def
Revert " Caching dependencies to speed up PR builds "
Gh - 29 Add comment about trailing class
Update README . Md for version 0 . 1 . 3
Add icon for all avd
Fix for GRAILS - 6503 " WAR does not update "
Add GCMParameterSpec to preloaded - classes
Fixed typo
Disable broken inspection by default
Remove unnecessary prop
Fix a ViewPager that could be defined in onAttachedToWindow .
Ignore Update ' modules / apps / web - experience / journal / .
Removed - api flag in build . Gradle
Ignore Update ' modules / apps / web - experience / asset / .
Add support for android . Jar ( thanks to exist )
Added org . Android . Jar to dbcompile classpath
Remove old screenshots for HIVE - 522 .
Added LLVM bindings for PassManagerBuilder ( Mac OS X binaries ) .
Remove numThread and maxConnections from reference . Java
Created tech - debt entries for all components and laboratory components .
Update readme
Added image icon
CLJ - 1329 - remove unused local variable in ` BuildRuleSuccess . Property ( )
Release 2 . 1RC2
LPS - 69013 prep next , use latest
Removed duplicate proguardAchives configuration
Add ICU as a java library for docs .
Ignore IntelliJ backup files
Remove debug output at unit test
Fix typo .
Bump pegasus to 1 . 9 . 7
Renamed maven assembly to jmxtrans - all . Jar .
Modify install_fbthrift .
Add iOS entrance for english version
Remove the accidentally committed doc dump .
Make every language have its own preview page by default .
Add case to identify a classnode as well
Ignore Update ' modules / apps / foundation / hello - soy / .
Ignore Update ' modules / apps / web - experience / portlet - configuration / .
Using the latest buildtools version here too
Ignore Update ' modules / apps / collaboration / message - boards / .
Ignore Update ' modules / apps / web - experience / layout / .
LPS - 55480 Regen , ran " build - client " in portal - client
Rename README - pt to README - pt .
Tip updated ( IDEA - 78127 )
Excludes scala dependencies from zipkin - cassandra - core
Bumping commit name .
Ignore Update ' modules / apps / foundation / portal / .
Fix OSGI source path for now
Ignore Update ' modules / apps / foundation / portal - settings / .
Updated features to 2015 . Md in README . Md .
Added new migration file in the Demo .
Ignore Update ' modules / apps / web - experience / export - import / .
Update sparc jars
LRQA - 28693 Ivy needs mirrors - get
Upgrade Apache Commons Collections to v3 . 0 . 0
Fix spaces in config_imports .
Prepare for next development iteration
Ignore Update ' modules / apps / foundation / expando / .
Push version to 12 - beta8 , 228 .
Removed unnecessary return
Fixed link in CHANGELOG . Txt
Ignore Update ' modules / apps / web - experience / product - navigation / .
@ Deprecated does not have effect messages for now
Fix msn log in .
Fixed NPE in Box . ExtendToEncompass , close # 1783
Remove double up unregistering mPackageBroadcastReceiver
Update voiceRouter with currentStatus = STATUS_UNKNOWN ; while makeUturnWhenPossible is active
Add a CHANGES . Txt file for HDFS - 1623 .
Add API reference docs filtering for level 20
Add splitIndex Javadoc option to the root project
Cleaned up favicon
Added STORM - 1473 to Changelog
Accept Google ' s Android SDK licenses
Changed the size of ijar_test
PY - 1065 Reformat and auto - import do not respect space - after - comma preference in multiline imports
Remove unused lines
Update the CHANGELOG for SI - 1851 bugfix
Updated LICENSE to 2014 .
Updates build tools version to 2 . 1 . 0
Updated changelog
Updated test for GROOVY - 3401 with a correct example showing that we can put a blankline before the colon
LPS - 57626 Migrate icon
Add assets for Android .
Added STORM - 1160 to Changelog
Only define _GNU_SOURCE if it wasn ' t used ( IDEA - 157793 )
Add STORM - 1361 to changelog
Ignore Update ' modules / apps / web - experience / journal / .
Revised missing icon from paul
SONAR - 3862 Fix small rendering bug in PennTreeReader . Java
Updates the chat room guest icon .
Modify Makefile
Revert " Revert " Ask on demand at the write of outstanding body option , closes # 1807 .
Fixed a bug in reply . Reset ( 0 ) for now
Fixed bug in previous commit ( # 833 )
Changed description of org . Jetbrains . BulkWriteException to com . Mongodb . MongoException
Remove errant AutoCloseable .
Added more height for the shadow drawable , so it can be scaled properly to lower dpi screens .
Adding JUnitLib target to lib folder ( IDEADEV - 5935 )
Remove numThread ( PY - 24855 )
Fixed bug in ByteBufferSend that lead to incorrect value for isClosed ( ) .
Updated the index in the preview list .
Ignore Update ' modules / apps / foundation / portal - security / .
Updating Alloy to rev . 81636
Git ignore Rplots . Pdf .
Ignore portal - profile 1 . 0 . 0 prep next
Remove mavenLocal
Prepare 0 . 7 . 0 release notes in release
Add parsing information to kotlin . Xml .
Upgraded proguard to 5 . 2 . 1
Rewording 1 . 0 . 5 release of 3 . 0 . 0
Make gradlew executable in Lazybones templates .
Bump version
Ignore Update ' modules / apps / foundation / portal - configuration / .
Remove sleep 3600 .
Revert " LPS - 45166 SF
Setting version to 1 . 0 . 147 - SNAPSHOT
Add MIT License
Turn off fixed rate scheduling in OpenGL
Making the gemmlowp token more descriptive
Remove unnecessary semicolon
LPS - 68937 ( WEB ) Move OSGi icons
Ignore IDEA project files
HHH - 7147 - Don ' t set RLIMIT on windoze , either .
Add a redirect to the new location .
Removed tag roboguice - 1 . 1 . 1
Added support for AssertStatement
Use older version of yammer to be compatible with skeleton
LPS - 27654 - Adding Translation from Web Content from Control Panel "
Disposing popup over node
Updated Support Libs to 23 . 2 . 2
Changed dependencies to milestone versions in preparation of tagging
Add blueprints - framework - 2 . 2 . 0 - java5 . Jar
Add image for action bar icon
Fix syntax error in titan and ntp 2 . 6 .
Removed debug statement from com . Mongodb . CommandResult . GetServerUsed
Ignore Update ' modules / apps / collaboration / directory / .
Remove inout from settings
Fix typo in readme file
Add missing SPDY npn - boot . Jar file to Openfire lib / dist
MinecraftForge / FML @ 3231db9376766d619f942b6a526718daa3c68038 Sorta revert 908491d5e7ac26becdac938f38cc90d6b9d73ce1 but merge assets into the map , rather than force overwriting .
Update README . Md for version 0 . 1 . 3
Removed an unused import .
Removed unnecessary return statement in LineageFileOutStream
LPS - 57119 Only strip fully qualified classname when it ' s NOT a literal string
Remove unused setter from com . Sun . Impl . Impl . "
Update mac bullet binary and natives jar file
Fix previous commit
Only use jdk8 in travis
Renamed the name name to reflect the correct name
Ignore Update ' modules / apps / web - experience / site / .
Learned some new structs from Blizzard ' s Hearthstone
Ignore Update ' modules / apps / web - experience / product - navigation / .
Ignore Update ' modules / apps / foundation / portal - configuration / .
Push version to 11253 .
Adding TODO to build . Xml
Fixed new CHANGES for 2 . 3 . 3
Removing old pattern relationship image
Ignore iml files
Update pom . Xml
Use Gradle 2 . 6 .
Added config_use_strict_phone_number_comparation , which will be used by kitkat
Add missing jar file
Fixed issue when using two threads is too .
Remove unneeded println
Removed unused import from AnimatorSet .
Updated version number to 0 . 23 . 0 - SNAPSHOT
Ignore Update ' modules / apps / foundation / hello - soy / .
Bump common for backwards compatibility fix for older plugins using setLocation and such on Entity .
Remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed
Fixed a bug in the mouse .
Rename file image
Add an ensureOpen check to Publication . HasBeenConnected ( ) .
Use the Tomcat logo rather than the ASF logo as the logo shown throughout the install .
Ignore Update ' modules / apps / web - experience / journal / .
Fixing license header in com . Phonegap . Api . PluginManager
Remove unnecessary code .
Make JSR305 annotations provided
LPS - 55000 update sdk with jspc
Fixed missing closing annotation error ( support info )
Should not be closing system dialogs when Recents is hidden .
Update demo gif
Setting version to 1 . 0 . 90 - SNAPSHOT
Includes the NOTICE file in the release
Die extra bin .
Move DeepLearning . Java to h2o - algos .
Prepare for next development iteration
Don ' t require empty artifacts for clean
Remove pre - add flag
Revert eclipse project specific setting
Don ' t add the TODO .
Updated reference to oc - library
Prepare for next development iteration
Add notice
Added proguard rule
Moved index . Html to GoogleChartsExample folder
Removed changelog
Fixed import error ( PY - 16878 )
Change build tools to 23 . 0 . 3 .
Created tech - debt entries for all components and laboratory components .
Ignore Update ' modules / apps / screens / .
Bump up revision number .
Changed default cache size to crash .
Return an empty PluginList instead of null in looper when loading ( ) that we don ' t do anything .
Add local . Properties to gitignore
Prepare 0 . 4 . 0 release
Prepare next release v0 . 87 . 4 - SNAPSHOT
Ignore Vim swap files
Fix bad merge of tools version .
Fix typo in build . Cfg
Fixing the build error on debian
Update bundled JRE to 6u39 , refs OF - 612
Fix build
Ignore IntelliJ IDEA files
Add toString ( ) method from NETWORK_TYPE_IWLAN
Updated builtin framework to API 24 ( IDEA - 154513 )
Fix # 1173
WCM - 626 prep next , use latest
Removed unnecessary local variable in ` BuildRuleSuccess . Property `
Fix a grammatical error in README
Prepare for next development iteration
Prepare release astyanax - 1 . 0 . 0 - SNAPSHOT
LPS - 51937 remove bad SF
Added ISchemableSpout interface
Removed unused import from demo . Yml
Prepare for next development iteration
Ignore Update ' modules / apps / web - experience / layout / .
Removed version of pom . Xml
Fix syntax error in readme . Md .
Add missing installation link to docs config
Fixing broken dropdown asset
Signed disabler . Zip with testkeys
LPS - 55000 update sdk with jspc
Remove unused import statement
Ignore Update ' modules / apps / collaboration / flags / .
Fix test data for now as unit tests
Remove repeat annotation from PropertyNode # setClosureSharedVariable
Don ' t use bold words on global view , because they don ' t do anything
CAMEL - 5583 - Add LZFDataFormat to jaxp . Index .
Bump version number
Ignore Update ' modules / apps / collaboration / wiki / .
Ignore Update ' modules / apps / foundation / login / .
Install setup . Sh change
Release the version 1 . 1 . 1
Removed unnecessary semicolon .
Do not delete access information in messages due to checking method ( IDEADEV - 5417 ) .
Ignore Update ' modules / apps / foundation / contacts / .
Ignore Update ' modules / apps / collaboration / image - uploader / .
Update location module
Remove impute . Flow from index . Yml
Try it at a one - liner
Changed minSdkVersion to 8
Add header image
Ignore Update ' modules / apps / collaboration / announcements / .
Ignore Update ' modules / apps / foundation / portal / .
Ignore Update ' modules / apps / sync / .
Added check for gradle .
Ignore Update ' modules / apps / web - experience / asset / .
Ignore Update ' modules / apps / foundation / portal - security / .
Fixed missing closing bracket
Ignore Update ' modules / apps / web - experience / asset / .
Fix finalization
Allow action bar size to 3 .
Ignore Update ' modules / apps / web - experience / product - navigation / .
Added relative path to the parent POM so that the user won ' t need to
Updated changes
Add app image for v1 . 5 . 0
Bump version number
Added mention of visibility in README
Add icon for free documentation
Move tests to elasticsearch test framework
Ignore Update ' modules / apps / collaboration / blogs / .
Updated TinkerPop libs to 2 . 2 . 0 - SNAPSHOT
DO NOT MERGE - Updated TestNG jars
Removed value in distribution
Ignore Update ' modules / apps / collaboration / wiki / .
Add empty migration file .
Ignore Update ' modules / apps / web - experience / staging / .
Added some license option to README . Md
Update NEWS readme
Ignore ds_store files
Fixed # 215 Update readme for CASSANDRA - 5542
Adding a test script to easily run a check of the manual
LPS - 45573 add error break since I assume order matters
Moving test to no pass as there is already LBFGH
Ignore Update ' modules / apps / foundation / portal - search / .
Ignore Update ' modules / apps / web - experience / application - list / .
Create README . Md
Ignore Update ' modules / apps / web - experience / iframe / .
Changed the name to the additional pages for the pages .
Rogue line number for try / catch statement confuses IDE debuggers
Revert " clear zombies after they are removed from timer list "
Revert " Upgrade to Flow 0 . 4 . 5 "
Removed import from data types ( IDEA - array )
Adjusted FireFox permissions image to give more prominence to the microphone
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Remove invalid style from NOTICE
Ignore Update ' modules / apps / collaboration / image - uploader / .
Revert " Revert " Use the build - remove empty line
Remove a wrong char " 7 "
Updated changelog
Ignore Update ' modules / apps / web - experience / asset / .
Prepared for next development iteration
Add local . Properties to gitignore
Removed unnecessary comment from plugin .
Fixed accidental edit issue
Ignore Update ' modules / apps / web - experience / nested - portlets / .
Added new screenshots for installing the theme list
Fix ApplicationInfo copy ctor
Add a task that resolves all configurations .
Fix partial delete comment .
Update changelog
Add missing semi - colon .
Ignore Update ' modules / apps / collaboration / bookmarks / .
Update solaris - sip . Jar of Android 1 . 6 . 1
Source jars are missing sources for classes written in Groovy
EGL14 . EglCreateWindowSurface should set producerControlledByApp
Fix missing memory name for case ( ) .
Setting version to 1 . 0 . 118 - SNAPSHOT
Fix dependency in commons - core dependency .
Adding link to readme
Prepare for next development iteration
Add diagrams for the theme in the wiki
LPS - 54250 moves icon
Add missing migration file
Add memory dependencies
Changed Target SDK to 21 ( Lollipop )
LPS - 45564 Add missing @ Override
Ignore the client / shade / dependency - reduced - pom .
Ignore Update ' modules / apps / collaboration / item - selector / .
Build trove4j to be compatible with 1 . 5
Update changelog
Revert " Fix toString ( ) method in NeoApp . NeoAppRelationshipType . . . Otherwise
ZEPPELIN - 852 fixed the fields float outside the box .
Do not encode sendRedirect URLs
Bump engine . Io - client
Remove unused import
Add a changelog for CHANGELOG . Md
Fix a minor typo in r1095367
Removing extra comment in worldedit - restrictions ( ) .
Updated small screenshot size
Ignore Update ' modules / apps / foundation / users - admin / .
Compile tools 2 . 2 . 2
Fixed a bug in commonutil .
Remove com . Eclipsesource . Properties from pom . Xml
LPS - 47291 Move the test to portal - service because otherwise it ' s not accessible from DLValidationUtil
LPS - 56179 Create a new ResouceBundle for item and existing . Properties
Add missing image resource
Handle KeyboardInterrupt in using 3 . 1
Help topic ( PY - 348 )
Freshen screen shots in help screens
Updated ChangeLog
Remove useless assignment in LayoutParams
Update location module
LPS - 65749 prep next , use latest
Don ' t include 54321 in the workspace script
Bump make memory for groovyDoc to fix failing execution
Bump version number to 1 . 0 . 0 - SNAPSHOT
Fixed double - benchmark version
Removed @ Ignore from a comment that was not necessary used on the new line )
Add a redirect to the new location .
Ignore Update ' modules / apps / collaboration / microblogs / .
Added cloud - topology .
Removed unnecessary semicolon .
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Changed the size of the DTLS - droid is disabled reported by Damian Minkov .
Fix Boost install script to match problem with bluetooth
Prepare version 23 - beta5 .
Bump maven lib version to 1 . 0 . 1 .
Update gradle to 2 . 1 . 2
SONAR - 5561 Fix wrong upgrade in rest - test
Fix msn log in .
Ignore Update ' modules / apps / foundation / frontend - theme / .
We don ' t need these classes any longer
Updated Blueprints libs
Add version for v1 . 3 . 0
Update Kotlin . Yml to include updates of pycharm EDU2 . 0
Fix POM_ARTIFACT_ID and POM_NAME for the bom module
Updating Alloy to 5887563 ; LPS - 31011
Modify the assignments of the netwok icons to states
Updating readme to reflect bug 1 . 3 . 0
Add image for the pep8 - dpi icon
Ignore Update ' modules / apps / foundation / server / .
Added files via upload
Ignore Update ' modules / apps / web - experience / iframe / .
Add DestroysInstance to Binding . Unbind ( )
Add image
Drop OpenJDK6 from Travis CI suite
Updated Gradle plugin .
Move Runits for GLRM set loss function by individual column to passing thanks to Michal ' s fix
Fix performance test .
Fix jacoco plugin description in pom . Xml
Don ' t build feature in Travis CI ( # 542 )
Push version to 12 . 0 - beta2 , 238 .
Set back release properties
Ignore Update ' modules / apps / web - experience / asset / .
Ignore Gradle related file .
Ignore Update ' modules / apps / collaboration / flags / .
Remove useless whitespace
Removing j2objc - framework dependency
Update contributor list , add yaphet , bjlindeqiang , dingjun , Dollyn , feilaoda
Updated changelog
Don ' t force refresh if data is taken from cache
Testing out travis as ci
LPS - 65492 Ignore SF for now
LEP - 7666 Move com . Liferay . Portal . Wsrp to com . Liferay . Wsrp to LPS - 16075
LPS - 63462 update jar
Ignore Update ' modules / apps / web - experience / journal / .
Add STORM - 714 to CHANGELOG . Md
Revert " Revert " LPS - 61793 Move icon
Ignore Update ' modules / apps / foundation / portal - settings / .
Add HADOOP - 12843 to 2 . 8 . 1 that was just 20 .
Remove @ Override from interface method impl
Replace image for layout practice 5 1 . 2
Upgrade delve version .
Require Maven 3 . 0 . 2 or greater , because we use that API .
Fixed a bug where HttpMessage . RemoveHeader ( ) leads to a dangling leak .
Remove transitive dependencies that were needed anyhow .
Fix typo .
Learned some new structs from Blizzard ' s Hearthstone
Fixed " setup " shortcut for ' backspace ' command ( OC - 5012 )
Build number 10
Revert Gradle version to 1 . 7 to bypass OSS build issue with Gradle 1 . 3 .
Formatting readme markdown
Run the end of experimental the default ( PY - 2101 ) .
Bump version to 1 . 5 . 0
Remove JDK6 tests as it won ' t be supported from 3 . 0 onwards
LPS - 63528 ( WEB ) Move icon files
Fixed reference to ActorSerializer
Added circle . Yml
FastArray doesn ' t overwrite toString ( ) method
Added a few piechart screenshot .
LPS - 52768 moves icon
Ignore Update ' modules / apps / foundation / contacts / .
Rename README . Txt to README . Md
Fix typo in pom . Xml
Don ' t draw terminal content out of the terminal panel component ( IDEA - 125317 ) .
Adding exceptions
Adding the renaming of threads so that doesn ' t do what we don ' t run at integration tests .
No longer skip integration tests on Jenkins
Ignore Update ' modules / apps / foundation / portal / .
Fixed a bug where GCalControlSet might not be initialized correctly
LRQA - 28229 prep next , use latest
Removing unused pattern relationship image
Allow restricting of Android again for Android
Upgrade XStream 1 . 3 - > 1 . 3 . 1
Fixes # 140 Removed line dialog .
Set pageLoadNotTriggered in onLoadFinished as well
Add tools for travis
Fix Issue # 140 as a crash
Built the latest snapshot
Prepare release otto - 1 . 3 . 0
Removed old translation of README . Md
Remove unused import statement
Add new module jar to suite
Added auto - reconnect flag to CHANGES . Txt
Update JIRA url
Removing an unused variable in ` BuildRuleSuccess . Property ` ( closes # 47 )
Remove bogus unreferenced classpathref ( cut and paste error )
Make interface as well that true again .
Updated android library jar to latest ADK .
Upgrade Anonymous Usage Statistics to version 1 . 1 . 0
Removed author tag
Added # hashCode ( ) to JID to be fully comparable .
Ignore Update ' modules / apps / web - experience / staging / .
Add support for MC 1 . 7 . 6 .
Tidied up ( # 8 )
Remove @ Nullable from PreDexMerge . GetSecondaryDexDirectories
Ignore Update ' modules / apps / collaboration / document - library / .
Add chinese translation
Add image for multi task visualization project
Don ' t set RLIMIT on windoze , either .
Ignore Update ' modules / apps / foundation / portal - lock / .
Updated gitignore .
Added another page link to README
Move AndroidManifest . Xml to source directory because it extracts properly
Ignore Update ' modules / apps / web - experience / asset / .
Setting version to 1 . 0 . 90 - SNAPSHOT
Fix crash in storm_env .
GRAILS - 11151 remove StatementCache from Event . Xml ( ) .
Bump version
Update the www - hdpi tutorial icon .
Fix pom version
Add commons / build
LPS - 19648 Add icon for web - impl
Fixed file name of travis script
Still return a package occurs by default .
Add StoreMeta which is a file in the sample
Updating Alloy to rev . 81636
GRAILS - 5691 - remove some code that was accidentally left in the last commit
Add " MMS " to common all so it compiles "
Updated version
Adds build_tmp to .
Ignore that pesky id_file in camel - hl7
Correct the gitignore of .
Ignore Update ' modules / apps / foundation / map / .
LPS - 62570 win x64 3 . 3 . 6 lib
Ignore Update ' modules / apps / foundation / contacts / .
Ignore Update ' modules / apps / web - experience / asset / .
Remove unused viewType assignment in LayoutParams
Added libsox - dev to apt - get install line in order to resolve all dependencies
Ignore Update ' modules / apps / web - experience / layout / .
GRAILS - 6254 added missing import in worldedit . Shutdown ( # 57 )
Remove extra line between out to 1 . 5 ( # ) )
Add SQL Console module to jOOQ - Copy authors . Txt
Revert icon to old one
Add Travis configuration file
Ignore Update ' modules / apps / collaboration / message - boards / .
Bump common ref for loadWorld fix .
Upgraded jackson to 1 . 7 . 4 as well
Update to latest gradle plugin
Changed IndexPrimaryShardNotAllocatedException from 409 ( RestStatus . CONFLICT ) to 500 ( RestStatus . INTERNAL_SERVER_ERROR )
Fix broken .
Rebuilds jmsoutlookaddrbook . Dll using tdm - gcc instead of mingw - w64 .
Add chromeMediaSource to MediaTrackConstraint extern .
Fix bug 2502522 - Accessibility events contain text of invisible views .
Add new default material images
Remove debug code
Ignore Update ' modules / apps / foundation / portal / .
Fix deadlock in NetworkIdentity . HashCode ( ) .
Fix typo in HTTP2 settings generation
Update gitignore
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Specify platform - tools version for travis .
Updating Alloy to 5887563 ; LPS - 31011
Fixing documentation
Fixed import .
CPP - 5210 Add " Accessors " to jetbrains . Txt
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Add sample
OC - 11626 Debugger cannot inspect Swift object variables compiled with Xcode 6 . 3 ( 6D520o )
Update todo
IDEA - 82647 Don ' t wrap HTML files from strings . Close ( ) that was be used on non - world
Help help menu ( IDEADEV - 38121 )
Ignore Update ' modules / apps / foundation / frontend - theme / .
Removed TODO . Txt .
Fix apicheck break .
Ignore Update ' modules / apps / collaboration / document - library / .
MinecraftForge / FML @ 94821fac98e64d9b8ad7434ed23a621850a8e11c Add a config file that lets you add additional soft dependencies at runtime - injectedDependencies . Json
Bump version to 0 . 4 . 4
Decreasing default max connections per node to 10
Add local . Properties to gitignore
Add lintVitalRelease as suggested by @ DimaKoz
Ignore Update ' modules / apps / web - experience / site / .
Revert " LPS - 45166 SF "
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Add adapter for mdpi - pack .
Ignore Update ' modules / apps / foundation / users - admin / .
Applied Stefan ' s patch
Don ' t show empty artifacts for non - ARC
Updated the zip file .
Update art
Fix bad height in variable name
DO NOT MERGE - Delete the line
Reordering the build repositories in the hope that this fixes the jenkins build .
Fixed PY - 7294 Invalid warning to avoid anybody of transactions in default page .
Remove debug logging
Fixed # 3134
Remove @ Override from end of javadoc files
Using jetty - api - helper version
Preparing WIP - Release v0 . 1 . 43 - alpha
Ignore Update ' modules / apps / foundation / roles / .
Update changelog
Removed unnecessary return statement in LineageFileOutStream
Ignore Update ' modules / apps / web - experience / product - navigation / .
Corrected license error in license list
Updated Gradle plugin .
GRAILS - 6047 , GRAILS - 6089 - improve handling of calls to local closures in Bootstrap
Fix typo in shell script .
Added Eclipse project target to ignore list
Update multiwords . Txt
Delete PreviewGif . Gif
Updated reference to oc - library
Ignore Update ' modules / apps / foundation / roles / .
Add JVM version in gradle . Properties
Ignore Update ' modules / apps / web - experience / site / .
Ignore Update ' modules / apps / foundation / petra / .
LPS - 15924 - Create a couple of " related " button "
Fixed syntax error in readme
Remove nouse module
Remove screenorientation on UCropActivity , it doesn ' t exist
Added missing migration config
Updated changelog .
Set source encoding from UTF - 8 ( fixes # 192 )
Make uploadMavenCentral task as it will be consistent with bbb - record
Ignore Update ' modules / apps / collaboration / blogs / .
Mention 5950 in NEWS
Setting version to 1 . 0 . 77 - SNAPSHOT
Added invalidateMaster method to control that behaviour from outside
GRAILS - 5691 - remove some code that was accidentally left because it is closed
Add support file to continous integration
Make bower non - interactive .
Updated changelog
Ignore Update ' modules / apps / foundation / frontend - editor / .
Update travis config
Added a new version of app_konference .
Added files via upload
Fixed accidental suppressing of errors in unit tests
Remove warning that was accidentally set .
Remove jslayoutjs annotation .
Revert " added localbox . Java to the topdomains of the config file , i think it ' s better for testing
Ignore Update ' modules / apps / collaboration / flags / .
Delete the scored frame , but not the appended vec
Ignore Update ' modules / apps / foundation / portal - lock / .
Groovy Console - - Option to Auto - Save on Run - added missing action mapping entry
Remove deprecated annotation
Ignore Update ' modules / apps / web - experience / product - navigation / .
Add STORM - 1713 to CHANGELOG . Md
Upgrade Anonymous Usage Statistics to version 1 . 1 . 0
Supplement the README
Moved demo pyunits to NOPASS since it is NOPASS .
Fix missing closing bracket
Add back underFSStorage into gitignore , which is the default ufs dir for local users
Remove svm - toy / .
Revert " Fix URL to jetbrains . Dic ( IDEA - 65 )
Changed doc reference to Elasticsearch Reference .
Fixed a bug where DefaultChannelFuture . IsSuccess ( ) returns true even if the future is not done yet
Push version to 224 .
Removed unused import
Set cam quality to 100 .
Updated read me
Add logs / and data / to .
Bump version
Fix smoke test name
Add explanation on adding dependencies of maven - release - plugin
Add Eclipse - related files to gitignore .
Remove useless import in quarry arm .
Set no - op install phase for Shippable CI build
Ignore Update ' modules / apps / foundation / portal - cache / .
Add files via upload
Add StoreMeta which is an file on the device
Update LICENSE . Txt
Add cloud - azure module
Revert " git ignore fixes "
Add image for free documentation .
Fixed frameRate .
Updated changelog
Fix compile error in 1 . 6 . 2 .
Released OrientDB 2 . 1 . 0 GA
Move local_mapred_error_cache .
Ignore Update ' modules / apps / collaboration / recent - documents / .
Call unlinkToDeath ( ) in CASSANDRA - 109
Set animation instead of tabs in the view ( )
Update natives
Added John " tug " Wilson in the @ author annotation in the javadoc
Override bootstrap ' s th styles .
Updated Vietnamese translation
Fix typo in build . Gradle
Removed unnecessary jar file
Removing a file from example data that ' s not needed
Made PersistentStructMap non - final
Fix warning
Add Missing semicolon in graylog2 . Index
Add analysis - kuromoji module
Add microbench to build . Gradle
LRQA - 17294 Remove unused import
Add comment in log view
Fix WorldEditPlayer . Count ( ) from createApplication ( )
Removed unused components from NOTICE file
Add support for travis - ci
Add padding on adapters
Prepared 2 . 0 . 5 release
Add missing SPDY npn - boot . Jar file to Openfire lib / dist
Prepare library for release 2 . 2 . 1
Fixed error with signing .
Fixed typo in comment
Added e - mail to travis . Yml
Updated forms . AsmCodeGenerator for custom BorderFactory client property
Add good icon for Android 1 . 5 beta documentation
Setting version to 1 . 0 . 148 - SNAPSHOT
Move this test to standalone , as it ' s useless in core ( no languages available there )
Fix an unintentional change in method information and changing # 284 .
Remove impute . Flow from index . Yml
Fixed the header icon .
Move worldedit . Html to migration folder so it extracts properly
Fix Makefile for docs .
Set correct permissions on the script .
Add openjdk6
Move ChildBrowser . Java to the right directory
Kill finish ( ) on Accounts activity when auto jumping to the same state , because it isn ' t used
Upgrade maven - surefire - plugin .
Remove unused import
Set source encoding limit in pom . Xml
GRAILS - 4075 Fixed the shouldFailWithCause regression .
Updated ChangeLog
Add back underFSStorage into gitignore , which is the default ufs dir for local fs
Downgrading server to jersey 1 . 3 due to issue with loading of external jax - rs packages .
Ignore Update ' modules / apps / foundation / petra / .
Add back CordovaWebView . GetUrl ( ) as part of test to run in unit tests
Add flow directive to index . Yml .
Updated changelog
LPS - 48288 Set resourcePermissionMap to _resourcePermissions
Ignore annotations , because that is generated code
Add ptr - demo - debug .
Changed location of section for better look ` n ` feel
Fix param for Metrics Consumers
Remove @ Repeat ( 100 ) from BasicCacheTest
Revert " Update manifest name
Add STORM - 1467 to changelog
Remove unecessary < extension > element from maven - bundle - plugin
Ignore Update ' modules / apps / web - experience / site / .
Bump common for 4 . 2 . 2 ref
Include server examples in the build .
Revert " add CHANGES . Txt for CASSANDRA - 11051
LPS - 60633 ( WEB ) Move css files
Add travis file for Travis CI
Updated IOUtils 2 . 3 . 2 - > 1 . 6 . 2
Update changelog for STORM - 492 .
Added interface to SurfaceTexture
Fix the build . Properties file
Enable unit test on jdk6 and 7 , and use mvn clean package instead of mvn test - B
Remove alpha5 bwc indexes
Fixed nav bar color in material .
Removed obsolete studio .
Add resize to the support library makefile .
Add warning about data separators always fix
Adding a META - INF / services file
Fixed readme typo
Fix bug in LayoutPanel refresh ( if we can be accessed by the outside world
Fix broken KL file .
Ignore Update ' modules / apps / foundation / frontend - editor / .
Fixed test classpath for spring - core
Create webapp / llap directory for MiniLlapCluster
Bump release to 1 . 7 . 0
Fix bug in View ( PY - 18546 )
Removed CHANGELOG . Txt
Add Travis configuration file
Added a new high dpi icon , and an updated version of the medium dpi version
Fixed error in previous commit ( fixes # 47 )
Added the click length " to owner list .
Add osx w / allowed failures on jdk8
Update native submodule to include flaky tests
Revert " ignore " bin " directory .
Add Mariano Semelman to the list of contributors in README . Md
LPS - 44342 Make an error that doesn ' t allow the scrollbar in the Recent Downloads portlet
Remove unused variable in method
Fix missing config for performance tests
Get share link
Fix up docs & issue with 1 . 6
Build LayoutLib tests with Java 7
Added missing property
CAMEL - 5583 - add LZFDataFormat to jaxp . Sh
Updated support JAR
Fix a bug that we don ' t do anything .
Removing comm files from jre since they needn ' t be in there
Suppress UnsatisfiedLinkError ( debug info )
Remove a comment that was not opened in the " i " thread page .
Ignore Update ' modules / apps / foundation / portal - scheduler / .
Ignore Update ' modules / apps / web - experience / journal / .
Prevent new ripples when max reached
Fixed typo
LPS - 48539 Move TransactionalTestRule to portal - test - internal module
GRAILS - 10448 - fix failing tests
Set release date
Added order to enable UTF - 8
Added DBCP to Supported Modules in README
Ignore Update ' modules / apps / web - experience / layout / .
Fix YAML so it parses
Updated support library
Ignore Update ' modules / apps / web - experience / asset /
Updated changelog
Committing a bug where DefaultChannelFuture . IsSuccess ( ) returns true defined
Upgraded netty 4 . 1 . 2
Ignore Update ' modules / apps / foundation / xstream / .
Ignore Update ' modules / apps / foundation / portal - template / .
LPS - 48473 - Remove ' isEditorPresent ' property from Liferay . Properties
Create README . Md
Fixing Junit dep scope to test
Fixed Travis configuration ?
Add javax . Inject jar
Don ' t run performance tests in parallel .
Updated GBM weights runit test to NOPASS
Improves the hotplug response times on Windows which may be noticeably prolonged due to thread scheduling in cases of Windows Multimedia reporting lack of a device driver .
Ignore Update ' modules / apps / foundation / portal - search / .
Added title about dates . Md
Fix multi tab < re while in wrong usage
Make every language have its own preview page by default ( no need to specify useSharedPreview ( ) for each )
Improve manifest from git .
Set release version to 1 . 1 . 0
Remove extra newline at the end of the file
Ignore Update ' modules / apps / collaboration / message - boards / .
Removed system out .
Add config_use_strict_phone_number_comparation , which will be used by default )
Removed unecessary include files .
Revert " Rollback avs to 2 . 9 . 8 ( 2 . 9 . 3 was too far ) "
Added missing VIBRATE permission
Remove web
Configured surefire to use UTF - 8 so that Aslak can write & read his
Fix typo in build . Gradle
Fix constructor for networkingPrivate . GetServer ( ) .
Fix previous commit messages .
Add javax 1 . X to third_party 2 . 2 . 2
Set pageLoadNotTriggered in onLoadFinished as well
Ignore Update ' modules / apps / foundation / portal - settings / .
Remove unused return statement
Moved ( copied ) components and ported to kernel / index / shell 1 . 0 - SNAPSHOT .
Also show empty preview by default , because it will be clicked )
LPS - 67049 Move unit test to correct module
Fixed test script for optimize imports
Remove unused variable
Remove old jar from lib / webapp / WEB - INF / lib
MinecraftForge / FML @ 54e06e841d1c8df24fc30e1ec3a51def67f58858 Move Resource refreshing until affter postInit .
Add screenshot
Remove @ Nullable from PreDexMerge . GetSecondaryDexDirectories
GRAILS - 11151 remove StatementCache from jdbcInterceptors property in default DataSource properties .
Documented socket handler enhancement
Build X module by default .
Added target to .
Fixed a bug in commonutil .
Don ' t set the application title in the library
Made GNU / paste by default
Update gitignore
Fixed a minor bug in ParticleSystem . Reset ( ) reported by the future support .
Do not use any in release tag .
Ignore Update ' modules / apps / foundation / users - admin / .
Update screenshot
Bump common for 4 . 2 . 2 ref
LPS - 42815 - Error message style does not wrap on overflow fast
Fix InputType determination of WebTextView ( DO NOT MERGE )
Add clojure . Ipr and clojure . Iws to .
Remove the background annotation from the buttons that , will be done by default .
Ignore Update ' modules / apps / sync / .
Updated ugly icon
Fix travis building .
Improves the hotplug response times on Windows which may be noticeably prolonged due to thread scheduling in cases of Windows Multimedia reporting lack of a device driver .
Add good icon to replace normal icon from v1 . 1 . 0 .
Regenerate gradle - wrapper . Jar with 1 . 9 - rc - 4
Add STORM - 1055 to CHANGELOG . Md
Servlets do not throw exception messages in a ViewPager
Rename * .
Bumped parent versions from 2 - SNAPSHOT to 2
Ignore Update ' modules / apps / web - experience / staging / .
Update bsd64 native
Ignore Update ' modules / apps / collaboration / image - uploader / .
Ignore Update ' modules / apps / collaboration / announcements / .
Remove underline on GROOVY - array ( fixes # 211 )
Smack 4 . 1 . 7 - SNAPSHOT
Quoted evaluation in file in bbb - conf
Don ' t require any tests
Updated ignore list
Move ChildBrowser . Java to the right directory
Remove obsolete comment from allow_failures
Fix a bug where the chronometer wasn ' t accidentally using the message .
Corrected typo in year in license
Don ' t highlight anything in / list
Added cython to py requirements . 0
Bump VERSION to 1 . 6 . 2 .
Add virtual destructor and demonstrated . Js .
Prepare for next development iteration
Ignore Update ' modules / apps / foundation / portal / .
Don ' t include the . Org . H for the JDK 8 .
Ignore Update ' modules / apps / collaboration / recent - documents / .
Looping visibility
Remove empty file from the project list
Disabling test directory as slave not able to access hdfs
Ignore Update ' modules / apps / collaboration / notifications / .
Call getPositionForView ( clear info on Vista / x / Throwable )
Bump version to 1 . 5 . 3
Fix broken test .
Update screenshot
Implement jumpToCurrentState ( ) in VectorDrawable
Added jar files to appease NetBeans build
Do not show separator on stream list last child
Ignore Update ' modules / apps / foundation / frontend - js / .
Ignore Update ' modules / apps / foundation / portal - security / .
Chmod a - x build . Bat - unix exec bit doesn ' t make much sense for windows ' bat
Remove debug output from jdirectshow . Dll .
SONAR - 5736 The calling HelpshiftHelper . Init class from windoze , either .
Update osx bullet natives
Fixed a typo in bbb - conf
Revert Gradle version to 1 . 6 to bypass OSS build issue with Gradle 1 . 11 .
Ignore Update ' modules / apps / marketplace / .
Added missing jar file
Make EntityJoinWorldEvent Cancelable properly
Updating Alloy to rev . 81636
Bump version
Don ' t show stlport .
Don ' t use 54321 in the Microsoft Outlook Address Book of watchdog .
Changed dependencies back to SNAPSHOT versions after tagging
Fixed typo in FlaggedClientConfig file name .
Try removing container - based config
Ignore Update ' modules / apps / foundation / frontend - theme / .
Fix build on Windows
Remove unused imports
Added missing jars from DirBuster integration
LPS - 47449 - Missing language key for portal - impl
Added back in author / revision info
Moved ChildBrowser . Java to the right directory
Removing the commons - codec .
Updated changelog .
Ignore Update ' modules / apps / web - experience / iframe / .
LPS - 69997 Add lang mapping
Updated elasticsearch upstream to fix some windows
Removed Key Value Server from SVN repository .
Updated pd to 1 . 7 . 0
Travis needs tools before platform - tools for 24 . 0 . 1 .
Don ' t force refresh if data is taken from cache
Upgraded logback to 1 . 1 . 5
Added missing migration file
Removed unused imports
Rebuilds the Mac OS X binary of the PortAudio support from its latest source / r7982 .
Remove temporary test comment
Updated doc for GROOVY - 2774
Add image for multi task visualization
Bump the version number to 2 . 2b3
Edited audio - test . Mp3 to web - bit .
Fix build - removing repo .
Ignore Update ' modules / apps / marketplace / .
Fixed broken import
Give access to the defining classloader
Fixed syntax error in readme
Add link to documentation list of CONTRIBUTORS . Md
Ignore Update ' modules / apps / collaboration / microblogs / .
Added checkstyle number that was email with Maven 3 . 1 .
Fix hystrix - contrib submodule path
Ignore Update ' modules / apps / foundation / petra / .
Fixed missing import
Fix DexGuard project for event .
Fix CHANGES . Txt as it ' s not in library bug .
Add the Servlet 3 . 0 xsd ' s
Updated changelog
Ignore Update ' modules / apps / collaboration / document - library / .
Remove unneeded " static " keyword from Number3D class
Ignore Update ' modules / apps / foundation / license - manager / .
Created tech - debt entries for all components and laboratory components .
Regenerate racingbike icon in 48x48 px like it ( IDEA - )
Prepare release imageloader - parent - 1 . 5 . 9
Fix crash in movie studio
Update the old screenshots in bbb - web
Use more forks and less iterations / test
Make sure Account . GetDescription ( ) never returns null
Fixed build message for # TACHYON - 1243
Add Deep Water jar to .
Fixed typo in JedisCluster del command
GrailsBootstrap was setting the pluginSettings property for the plugin
Fix README in README . Md
Possibly fix # 94
LPS - 65749 prep next , use latest
Prepare next development version .
Replaced huge screenshot
Remove an unneeded assignment
Update build tool
Increased cassandra version to 1 . 1 . 2
Add blueprints - core - 2 . 2 . 0 - java5 . Jar
Updated TinkerPop libs to 2 . 2 . 0 - SNAPSHOT
Ignore Update ' modules / apps / foundation / login / .
Fix osmand key location
Ignore Vim swap files
Make Tachyon - Perf a subproject of Tachyon
Fix typo in pom . Xml
We don ' t need these classes any longer
LPS - 50855 Move CSS files to their proper locations
Adding spring - boot - plugin to the deploy profile
Added STORM - 1423 to Changelog
LRQA - 26247 prep next , use latest
Use the build messages from the build
Add missing Cydia Substrate library
Ignore Update ' modules / apps / foundation / portal - configuration / .
Tried new gititgnore file
Fixed import error ( PY - 16878 )
Removed unused import .
Remove unnecessary break in Tests
Remove @ Nullable from PreDexMerge . GetSecondaryDexDirectories
Fix setName use - after - free
Fix build . Gradle
Updated the parent pom version to 4 which enforces you to use maven 2 . 1 or higher
Added an empty high dpi icon work if it is start .
Added missing SPDY npn - boot . Jar file to Openfire lib / dist
Bump the version number to 1 . 2 . 8 - dev
CAMEL - 6047 , remove unnecessary method from shutdown ( PY - 6618 )
Use older version of yammer to be compatible with skeleton
Ignore Update ' modules / apps / foundation / frontend - css / .
Rename Filter to FilterActivity to prevent name collision
Ignore Update ' modules / apps / foundation / frontend - theme / .
FileSystemCompiler # generateFileNamesFromOptions is adding filenames multiple times
Remove javadoc warning
Removed unused import
Setting version to 1 . 0 . 98
GRAILS - 6733 - add a comment that we don ' t do anything if we don ' t do anything correctly .
Ignore Update ' modules / apps / web - experience / site / .
Fix bug 3425610 Adjust Lock sound level
Rename README . Txt to README . Md
Updated CHANGELOG
Add Jungtaek Lim to be sponsor of storm - example
Removed Java 6 from javadoc build .
Remove " notYetImplemented ( ) " from ControllerUnitTestMixinTests . TestAllowedMethods
Make blueprints - test a test scope dependency
LRQA - 17294 Remove unused import
Ignored IDE - specific files .
Gradle should match project . Properties after d816483a7cd4d98b5b136139ccaacd322e0ab5b6
Move flavor strings to donottranslate file .
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Forgot to commit the services file
Added intellij specific files to .
Don ' t require self ( s instead of r454 ) .
Ignore Update ' modules / apps / collaboration / document - library / .
Reset build identifier to next milestone snapshot
Remove unused files ( HIVE - 516 )
Updated ChangeLog
Fixed unit test name value .
Modified todo ( fixes # 211 )
Bump dependency on neo4j - browser .
Remove the memory leak from org . 9 . 1 .
Updated ugly icon
Adding ycsb . Jar to dbcompile classpath
Add kotlin - maven - plugin version
Created tech - debt entries for all components and laboratory components .
Set the source encoding to UTF - 8 to remove a maven warning when building
Excluded NightlyTest in the default build profile
Remove @ PrivateApi annotation class from listview .
Remove commons - cli config
Fix bad xml version in pom . Xml
Add datasketches module to top level pom
Updated README . Md to show version 0 . 4 . 1 .
Setting version to 1 . 0 . 142 - SNAPSHOT
Add gif
Remove jdk 8 from travis build .
Ignore Update ' modules / apps / web - experience / layout / .
Write checkstyle to stdout .
Set minSdkVersion to 8 for 2 . 2 . 1
Updated changelog
Updated changelog
Added some license option to README . Md
Move JPAPathBuilderValidator to src / main / java
Fix memory leak when having complete .
Add java8 to travis .
MinecraftForge / FML @ dc02d56195606d3ba2f1c5036fc8c0ddb67c843f Fix derp with ModType annotation
Fixed accidental edit warning .
Moved whiteboardAccess to config . Xml template
Disable doclint on JDK8 .
Ignore Update ' modules / apps / collaboration / wiki / .
Removing @ Nullable from PreDexMerge . GetSecondaryDexDirectories
Push version to 15 . 0 . 6 , 15008 .
Remove ' subprojects / * / ide ' entry from .
Add a runtime dependency on validation - api
Ignore dist folders
Ignore Update ' modules / apps / web - experience / export - import / .
Added tag 0 . 0 . 7 . 6 for changeset 45e1e724eee2
Ignore Update ' modules / apps / foundation / frontend - theme / .
Set correct permissions on the script .
Ignore Update ' modules / apps / web - experience / trash / .
Updated icon
Turn off publish failure
Exclude weld - core from java 6 .
Make TemplateResource public for running integration tests
Removing @ Override flag from compareTo method , since it isn ' t used
Delete the memory leak ( returning from a void method )
Ignore Update ' modules / apps / collaboration / blogs / .
R / m duplicate entry in the changelog
Update weexcore so . Properties ( 2 . 6 . 2 )
LPS - 61556 Move icons files
Fix change
Revert " added an " properties " to " bin ' settings .
Updating version to 3 . 0 . 0 !
Fixed copyright dates .
Remove @ Nullable from subclass ( ) method
Upgrade Ivy 2 . 2 . 0 RC to final
Ignore Update ' modules / apps / foundation / expando / .
Ignore Update ' modules / apps / web - experience / export - import / .
Fix lost sharedManfiest configuration in build . Gradle
Add STORM - 2041 to CHANGELOG . Md
Remove unnecessary return statement in LineageFileOutStream
SONAR - 5736 The select list actions does not fetch more than one message
Fix winpty executables .
Ignore Update ' modules / apps / web - experience / iframe / .
Added jcenter to repositories to get actionbarsherlock . Aar
Make THREADS configurable through environment
Don ' t emit empty exceptions in notebooks
Bump version for 0 . 3 . 2 release
Fix msn log in .
Fix a typo causing the end of constructor .
Ignore Update ' modules / apps / foundation / portal - lock / .
LPS - 69244 Move icon File
Ignore Update ' modules / apps / web - experience / asset / .
LPS - 34662 Add @ Override to suppress comments that doesn ' t allow comments in entry
Removed @ PrivateApi annotation ; not needed since PacketTransceiver is in the impl package , and therefor should not be accessed by the outside world
Don ' t create a line in my dictionary ( IDEADEV - 65 )
Use correct param for heightMode in RelativeLayout horizontal measure
Updated changelog
Disable reloading for scripts with dates in the future
Gh - 480 - Add unneeded caching on Travis CI
Set correct permissions on the script .
Remove extraneous jar file
Updated BP libs
Remove release 0 . 5 . 5
Add flowdock notification to Travis build .
Revert " ignore " bin " directory "
Add mongodb to travis CI
Gradle build tools version 1 . 0 . 1
Ignore Update ' modules / apps / sync / .
Add icon for Grails 1 . 5 . 0 .
Missing dead code .
Ignore Update ' modules / apps / foundation / frontend - js / .
Setting version to 1 . 0 . 15
Someone doesn ' t create a new line
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Revert back change
LPS - 51081 Ignore @ Thumbs . Db to .
Add 581 to CHANGES . Txt
Add another upcoming change in documentation index
Updating default wallpaper
Ignore Update ' modules / apps / collaboration / document - library / .
Ignore Update ' modules / apps / foundation / frontend - taglib / .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Typo cont ' d ( remove deprecated method in trunk )
Set version for maven - rules
Ignore Update ' modules / apps / web - experience / journal / .
Remove 666
Bumping versionCode 207 for 4 . 5 . 1 release
Added missing SPDY npn - boot . Properties file to Openfire lib / dist
Removed margin of p . Shutdown ( ) .
Revert " LPS - 44526 New User does not create a permissions in portal
Build linux / i386 against older glibc ( 2 . 3 . 4 ) for compatibility
Fixed typo in build . Yml
Updated the year from the translator .
Bump pegasus to 1 . 9 . 7
Fix build - update scripts in fbobjc
Ignore Update ' modules / apps / foundation / portal - instances / .
Added a Composite Configuration Diagram to be used . . . .
Added a Composite Configuration Diagram to use in the Wiki .
Bumped parent versions from 2 - SNAPSHOT to 2
Update changelog for 1 . 5 . 1
Fix an issue where the end of the stream .
Prepare release acra - 4 . 6 . 2
Create gradle files to appease NetBeans plugin
Prevent NPE when stop by the first video
Change ribbon version to 2 . 0 - RC9 .
Add good icon for free app
Fixed the fastscroll thumb import name
Fix android_media_AudioSystem_getMasterMute return type .
Correct the typo in the flow
Added missing resources for CASSANDRA - 3563
Skip tests for Java 7 ( # 330 )
Revert " Android package name requires at least two segments "
Don ' t accept " Leereichen " , probably a typo of " Leerzeichen "
Removed old lib
Remove sudo
Create README . Md
Switch version number to 3 . 0 . 1
Do not start queued actions for TV device
Ignore Update ' modules / apps / foundation / portal - settings / .
Remove the accidentally checked file in prep for 1 . 2
Moved Runits for GLRM set loss function by individual column to passing thanks to Michal ' s fix
Move test module to exports file
Add 1 . 4 . 5 to point of developers
Ignore Update ' modules / apps / collaboration / message - boards / .
Remove comment
Adding org . Jetbrains . Android as part of install . Properties
Remove bottom margin from header list
Added missing image
Updating Alloy to rev . 81636
Updated readme in README
Fixed typo in README .
Updated changelog .
Added a Bitdeli badge to README .
Revert " LPS - 56041 shouldn ' t need this
Changed license name
Removing the commons - codec .
Updated api . Services . Png image to reflect new api structure
Remove unneeded cast in linker task
SONAR - 5905 Fix bug in Firefox
Remove AppState from Known Issues drawable
Added Kasper to list of developers
Ignore Update ' modules / apps / collaboration / bookmarks / .
Fix failing test
Setting version to 1 . 0 . 149
Revert " Git should ignore the TestNG output directory "
Improves the hotplug response times on Windows which may be noticeably prolonged due to thread scheduling in cases of Windows Multimedia reporting lack of a device driver .
Write checkstyle to stdout .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Ignore Update ' modules / apps / collaboration / notifications / .
Update travis config file
Removed unnecessary version from pom . Xml
Ignore Update ' modules / apps / web - experience / layout / .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Update changelog
Delete old file due to test folder
Moved runit to NOPASS .
Updated CHANGELOG with weakling feature .
Setting version to 1 . 0 . 103
Ignore Update ' modules / apps / foundation / frontend - css / .
Remove the secret key .
Added new pic in the list of the sample
Fix NPE # 12 . Java . Js ( # 421 )
Fix a bug with backsided objects .
Meteor / AWSCloudFormation added to validation list
Fixed typo in comment
Added exclusion declaration to the deploy classpath
Add flag for GROOVY - INF to improve location
Add Travis configuration file
Kill finish ( ) on Accounts activity ( # 144 )
Do not encode sendRedirect URLs ( PY - 15907 )
Use user related icon for CASSANDRA - arrowkey and 64 - bit ( IDEADEV - 38918 )
Disable memory install test for ' spec ' command
Add break statement on load extractor from form
Ignore Update ' modules / apps / foundation / portal - search / .
Chmod a - x build . Bat - unix exec bit doesn ' t make much sense for windows ' bat
Fix typo in NativeComponentsAndroid . Md
Add image for multi task visualization
Ignore Update ' modules / apps / marketplace / .
LPS - 10616 Add missing import annotation
Ignore dictionary - web 1 . 0 . 2 prep next
Remove extraneous space in worldedit - side
Add Travis configuration file
Remove extra - arg from CHANGES . Txt
Add Joachim Baumann to the contributors list
Add class diagram for template to make a rebase
LEP - 5922 - refactoring , see comments on ticket used
Fix regression in NOTICE . Gradle
Fixed test data
Added clover license
Bump version to 0 . 1 . 5
Update native win32 - x86
Releasing OrientDB 2 . 1 - > 1 . 2 . 1
Updated changelog
Fixed a subtle bug in ParticleSystem . Reset ( ) ( IDEA - )
Add image for issue
Prepare for next development iteration
Fix RegTestParams subsidy decrease index explicitly
Remove useless semicolon comment .
Remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed
Removing @ Override statement that was accidentally try in case if well
LPS - 51912 remove unnecessary line break
Ignore Update ' modules / apps / sync / .
Add checkstyle required by schema to Cobertura configuration ( fixes # 192 )
Starting 0 . 5 . 4 - SNAPSHOT
Ignore Update ' modules / apps / screens / .
Don ' t compress jars
Added CHANGES . Txt to CHANGES . Txt
Removing dead code
Remove unused method from CompilerConfig
Changed components to use parent pom v 4 , producing source and javadoc jar packages .
Prepare library for release 2 . 1 . 2
Removed newline at the end of files
Updated version
Removed support library from the StackBlur library
Revert " Keep an empty line in the console
Remove old link from AndroidManifest . Xml
MinecraftForge / FML @ d00feb58c762b0bbc506d79faf1ce40bc96732e9 Remove debug code that was causing console spam in Forge .
Added image for multi task visualization project .
Check null input view
Ignore Update ' modules / apps / collaboration / microblogs / .
Fix copy / paste error
Update ppc64le natives
Ignore Update ' modules / apps / web - experience / export - import / .
Ignore Update ' modules / apps / collaboration / image - uploader / .
Add local docs to the spec list
Ignore Update ' modules / apps / collaboration / flags / .
Fixed logfile name
Prepare release jfinal - 1 . 7 . 2
Updated changelog
Bump pegasus to 1 . 9 . 7
Updated version
Add heap dump on OOM , see # 304
Ignore Update ' modules / apps / web - experience / staging / .
Fix typo in JedisCluster del command
Move jute file into toplevel src directory
Added tag 0 . 0 . 7 . 4 for changeset 5de91e5a0e95
Added John Wagenleitner to the contributors list
Added STORM - 1472 to Changelog
Ignore Update ' modules / apps / foundation / my - account / .
Add e - mail url
Fix sample - sql - plugin version .
Keep it as a test dependencies
Missing entry for CASSANDRA - 5542
Add a new logo ( ) .
Updated pdf with latest version
Restore accidentally removed call
Revert " Revert " Ask on demand in WebView
Fixed typo .
Remove unused files ( irrelevant )
Remove the empty file accidentally checked it with HADOOP - 7249 .
Updated version
Fixed missing closing bracket ( # 6059 )
Don ' t try a top level so that it doesn ' t collide with
Add scala link to documentation
Smack 4 . 1 . 0 - rc4
Removed empty line in titan . Sh
Fixed heap spec for functional tests
Ignore Update ' modules / apps / foundation / configuration - admin / .
Ignore Update ' modules / apps / foundation / plugins - admin / .
Updated changelog
Updated Blueprints
Removed httpclient - 4 . 0 . 0pr7 .
Add missing gradle . Properties file
Ignore Update ' modules / apps / foundation / frontend - js / .
LPS - 26283 Add a line break since it ' s no longer used
Added STORM - 375 to Changelog
Added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Updated submodules to latest
Ignore OS X .
Ignore Update ' modules / apps / foundation / portal - search / .
Ignore Update ' modules / apps / web - experience / layout / .
Add ColeMurray to contributors list
Remove ' subprojects / * / ide ' entry from .
Make Tachyon - Perf a subproject in pom
Revert " Revert " Revert " Use a new ' s ' cause does not prepare . 1 .
Ignore Update ' modules / apps / foundation / frontend - editor / .
Removed old doc submodule
Adds a toString method to prevent init tool to reuse when used is submitted .
Setting version to 1 . 0 . 135 - SNAPSHOT
Updated changelog
Ignore Update ' modules / apps / web - experience / export - import / .
Change FML should use the file instead of install .
Remove unused variable in ` BuildRuleSuccess . Property `
Copy the inverse of the modelview in resetMatrix ( ) .
Ignore IntelliJ ' s .
Fixed README . Md again
Added homebrew go strings .
Don ' t compress jars
Try jdk8 in travis
Ignore Update ' modules / apps / foundation / roles / .
LPS - 13277 But we don ' t need this ?
Added sleep to create a subset of the end of execution header
Update druid
Update travis command
Ignore Update ' modules / apps / foundation / frontend - js / .
CLJ - 4088 - Session . GetSession should always return sessions from parent
Ignore Update ' modules / apps / collaboration / bookmarks / .
Remove dup shebang .
Create gradle files to appease NetBeans plugin
Mention changes to German rules
Revert " Revert " disable the command line with an empty location
Updating changelog
Upgraded to ElasticSearch v0 . 20 . 4
Remove extra traling line
Added syntax line
Added TODO
Remove unnecessary constructor from HttpConfiguration .
Ignore Update ' modules / apps / foundation / portal - search / .
Fixed proguard id for proguard list since they can ' re !
Ignore Update ' modules / apps / collaboration / document - library / .
Updating Alloy updated diagram .
Ignore Update ' modules / apps / static / osgi / .
Provides a more recent snapshot of the wiki
Push build .
Ignore Update ' modules / apps / collaboration / microblogs / .
Fix typo in pom . Xml
Fix a more error # 10 . Github . " . Sac
Remove Tween externs .
Remove description of create more usr / share fixes
Ignore Update ' modules / apps / foundation / map / .
LPS - 30588 Add toUnescapedModel to RepositoryModel
Add more height for hdpi . Jpg ( IDEA - 128769 , IDEA - )
Always send ESC for backspace
Ignore Update ' modules / apps / foundation / portal - scheduler / .
Remove unused variable in alarm_active .
Updated icons from Vincent .
Ignore Update ' modules / apps / foundation / hello - world / .
Require Maven 3 . 0 . 5 to stop users from using insecure 3 . 0 . 4
Also set the size of glm lists ( ) method in # 297
Don ' t show sidebar menu by default .
Ignore Update ' modules / apps / foundation / contacts / .
Add missing jar for people not using maven .
Add gitkeep in demo
Updating Alloy to e79a782 ; LPS - 13554
Fix checking for multilabel
Remove old wiki gif
Bump version to r08 - SNAPSHOT
Removing the accidentally committed image case ( too TOOLS - 72585 )
Remove unused constructor from AnimatorSet .
Fixed test problem
Delete old jar code
Revert " Add Thumbs . Db to gitignore "
Just to get correct commit
Add Apache Commons Pool2 to Bazel .
Add Matthew to pairs file
Remove the newline with the end of the file supported languages but not accidentally made it if it is also used ( IDEA - 157793 )
Disable cloud - core dependency on core project ( IDEA - compat )
Missing doc - library .
Why didn ' t I just use a .
Fix mobile sites when creating a lazily initialized connection .
Add StoreMeta which is an code of the boy .
Prevent NPE when trying to be TOUCH_DONE_MODE when calling doDoubleTap .
Add @ implicitCast to " clear definition " to be consistent with " checkout .
Fix typo in cxx_library .
Added STORM - 1245 to changeling .
Ignore Update ' modules / apps / foundation / login / .
Remove @ Override flag from compareTo method , since it hasn ' t needed
Rename project docs to latest version 0 . 4 . 3 .
Updated build tools to 23 . 0 . 4
Revert " Revert " Use an empty build . " ) so that it ' s better for all builds
Ignore libs directory in the repo .
Ignore Update ' modules / apps / web - experience / export - import / .
Ignore Update ' modules / apps / collaboration / microblogs / .
Updated changelog for development .
Don ' t publish consoleio
Ignore Update ' modules / apps / collaboration / wiki / .
Add @ implicitCast to " clear definition " to be consistent with " checkout .
Ignore Update ' modules / apps / collaboration / blogs / .
Changed concurrency on startup ( fixes # 211 )
Removed extraneous whitespace from pull request
Added comment to typo in typo . Txt
Bump local threads
Updated release notes for v1 . 1 . 0
Update configuration . Yml
Add lintVitalRelease to avoid breaking memory
Changed dependencies back to SNAPSHOT versions after tagging
Add missing jar
Updating Alloy to rev . 81636
Update android - Iconics core to v2 . 1 . 0
Replace demo7 . Gif
Fixed typeo in test
Delete more manifset files .
Ignore Update ' modules / apps / foundation / frontend - js / .
Remove support library from the StackBlur library
Add new image for the theme in the wiki
Resized header
Add jar to libs folder for ant to find . . .
LPS - 61156 Move BaseDBTestCase to portal - test - plugin
Added linksource to javadoc so we can navigate from javadoc to source code
Set minSdkVersion to 8 in build . Gradle
Fixed test error in previous commit ( # 642 )
Updated version number
LRQA - 22807 Remove Wildfly + mariaDB module
Added the Growl - android .
Ignore Update ' modules / apps / web - experience / export - import / .
Added run command and target to run script
Enable log output on trests
Ignore Update ' modules / apps / foundation / frontend - js / .
Updated reference for 1 . 0 . 8
Add notorious enterprise / backup / data to .
Add STORM - 245 to Changelog
Add STORM - 1496 to gitignore
Set default implementation network to be suppressed .
Do not show merge by default ( no longer z - >
Updated idea jar to latest ( 2 . 6 . 4 )
Bump common for 4 . 2 . 2 ref
Added e - mail notification
Ignore Update ' modules / apps / web - experience / journal / .
Ignore Update ' modules / apps / foundation / frontend - editor / .
Ignore Update ' modules / apps / collaboration / wiki / .
Added translation using Weblate ( Nepali )
Ignore Update ' modules / apps / foundation / portal - store / .
Add recently added utils . R to to Collate field for the DESCRIPTION file template of the R package .
Remove uneeded dependency
Add image for multi - runner README
Change the size of the gifs .
Mute breakpoint icon loading button button
Revert " LPS - 44610 Update Alloy taglib jar ( Alloy "
LRQA - 618 Add possibility to keep only filter panel size
MinecraftForge / FML @ 5785a9c9e8d76b91a03ed1f9791aeee1cb7ea00b Fix up multiple injections of cmdline files via versionspecificmoddir .
Add jacoco_build .
Removed issue labels from the issues ' summary that were in the " Release 2 . 1 . 0 " help page .
Fix Travis again .
LPS - 17957 Can ' t save Asset Publisher configuration
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Ignore Update ' modules / apps / collaboration / document - library / .
Added professional image
LPS - 23806 Kaleo Designer is not selecting the connector when clicks on the connector shape ; Updating Alloy to 7db41fa30ff8e886e328d6bccf17e07dd26fb1a1
Ignore Update ' modules / apps / foundation / portal - remote / .
Ignore Update ' modules / apps / foundation / portal - search / .
Set revision 3 . 3 . 5 .
Ignore Update ' modules / apps / collaboration / microblogs / .
We don ' t need libopencore_author and libcutils in antlr .
Ignore Update ' modules / apps / web - experience / product - navigation / .
Make this library changes to avoid race condition .
Add sponge maven repository to build . Properties
SONAR - 5736 The select list component does not fetch more than one page type .
Updated changelog
Also remove obsolete line between at least it as a first source as well .
Added multichat operation set definition and Gibberish protocol implementation .
Bump common for 4 . 2 . 2 ref
Ignore Update ' modules / apps / foundation / frontend - css / .
Prepare version 19 - beta2 .
Disable optimizations for interfaces
Fix a bug disappearing installerPackageName info of packages after reboot .
Added another iOS brace in bbb - conf
Updated demo art
Fixed a typo in the theme list .
Add STORM - 1110 to CHANGELOG . Md
Updated jar
Ignore Update ' modules / apps / collaboration / directory / .
Fixed tests in previous commit ( fixes # 47 )
Ignore Update ' modules / apps / foundation / portal - security / .
Fix builder icon
Added CONTRIBUTORS . Txt
Rename no - length file to pushAndRun
Removed log4j . Properties from test - build . Xml
Bump version to 1 . 0 . 0 - beta . 1 .
Updated studio with Security + Backup UI
Add missing migration file
Gh - 471 - updated travis script
Remove old semicolon in wizard
Prepare 0 . 9 . 3 release
Added excludeDependencies to pom . Xml
Adds support for Logitech HD Pro Webcam C920 on Windows .
Update joda - time to 2 . 0 . 1 ( # 430 )
Add datasketches module to top level pom file
Add missing image for multi - client
Removed obsolete files in test / webapp / bin / windows / windows / WEB - INF
Added missing migration file
Fix node leak in HTML5 frame ( PY - 18546 )
Don ' t use the application title instead of the code
Updated mockito to 1 . 8 . 0
LPS - 69962 Add packageinfo
Ignore Update ' modules / apps / foundation / petra / .
Removed the Basque store icons
Ignore Update ' modules / apps / marketplace / .
Fix the build error
Accept ' indices ' and ' formulae '
Add travis status badge to README .
Added temp files
Use Android version number in build . Xml
Removed accidental license option in build . Gradle
Do not show refresh messages on error ( PY - 29885 )
Updated gradle target to 1 . 3 . 6
Added new temp files to gitignore
Removed version number from pom . Xml
Ignore Update ' modules / apps / foundation / portal - search / .
Bump common ref for loadWorld fix .
Add # 3479 ( SOURCE and CAPTURE cqlsh commands ) to CHANGES
Added a redirect to the new location
Increased the mvn version to avoid possible build bugs
Added Ryan as a maintainer since he has done a bunch of work .
Fixed compilation error
Ignore Update ' modules / apps / foundation / configuration - admin / .
Ignore Update ' modules / apps / collaboration / bookmarks / .
Adding JavaUtilLog notifications to VERSION . Txt
Fixed # 1049
E9c5ade 46ab5e1
Removed unnecessary indirect inner class instance in ExecutorServiceProxy .
LPS - 43576 Copy shared jars to the portal .
Fix travis env .
Added a Composite Configuration Diagram to use in the Wiki .
Ignore Update ' modules / apps / web - experience / staging / .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Prepare version 22 . 0 . 0 - beta4 .
Ignore Update ' modules / apps / foundation / contacts / .
Tidied up script
Fixing the global error that doesn ' t do anything if it is still used .
Removed @ PrivateApi annotation ; not needed since PacketTransceiver is in the impl package , and therefor should not be accessed by the outside world
Added missing super . Shutdown ( ) so that the notification is closed
Ignore Update ' modules / apps / foundation / portal - remote / .
Ignore Update ' modules / apps / collaboration / bookmarks / .
LPS - 67914 - Delete unneeded build . Gradle
IDEA - 126585 " Evaluate Code Fragment " should have " focused " "
Remove unused placeholder in JB workaround app
Add self to contributors list ( # 301 )
LPS - 42961 Fix incorrect logic , trying to be needed
Add getter for authoritiesPopulator .
Add STORM - 1468 , STORM - 1199 to changelog
Ignore IDEA project files
Remove empty CSS of graph . Py ( )
Updated build tools and sdk
Update aboutlibraries
Remove unused code
Ignore Update ' modules / apps / collaboration / document - library / .
Fix Boost install script
Includes the NOTICE file in the index
Improve movies grid activity as well
Ignore Update ' modules / apps / collaboration / wiki / .
Updated v1 . 1 . 0
Fix ' heap ' reference ' by mistake .
Ignore Update ' modules / apps / foundation / portal - scripting / .
Added intellij resources / folder to .
Removed android - android - 1 . 5 . 2 .
Updated ChangeLog
Removed the README file for HDFS - 3405 .
Upgrade delve version
Removed dup shebang .
SONAR - 4636 Bind handling of branding resources to a later phase of the build
Prepare version 29 .
Add IntelliJ files to gitignore
Fixed a bug in svm . Cpp
Created tech - debt entries for all components and laboratory components .
Fix pom . Xml
Ignored rrd directory that someone keeps creating for me
Update win64 natives
Fix typo in AbstractTestQueries
Remove h2o - scala from all packaging / so that it can be able to remove some code
Follow change in parent .
LPS - 69878 Set the new column to null
Update joda - tools to 0 . 8 . 1 in order of java 2 . 2
Bump engine . Io - client
Upgraded the POM version to match the current trunk version
Update sparc natives
Removed bottom padding in com . Mongodb . CommandResult . GetServerUsed
Ignore Update ' modules / apps / foundation / plugins - admin / .
Update changelog
Update library version
Add additional key for fullscreen on iOS7
Removed unused config from Support Library
Removed unused imports
Removed any remains of list appearance
Ignore Update ' modules / apps / collaboration / wiki / .
Fixed bug in previous commit .
Replace image for layout practice 5 1 . 2
Updated project . Yml to give bug in the URL
Adding placeholders for the fullscreen button
Revert " added line at end of list to pass "
Fix copy & paste error in isKeyguardLocked ( )
Remove unused imports
Added back gtest . Zip
Removed test file
Ignore Update ' modules / apps / collaboration / blogs / .
Ignore Update ' modules / apps / web - experience / site - navigation / .
Decrease lengthin some lines
Add exit codes to externs for CanvasRenderingContext2D .
Ignore Update ' modules / apps / foundation / portal - search / .
Updated ChangeLog
Upgraded the POM version to match the current trunk version
Revert " Fixed space ? "
Bump eclipse plugin version to Android 2 . 2
Remove lint line from travis .
Prepare repository for the next development iteration
Ignore Update ' modules / apps / foundation / portal - security / .
Ignore Update ' modules / apps / forms - and - workflow / polls / .
Remove local testing file
LPS - 64531 don ' t do this .
Fix copy / paste error on non - J2CL code
Updated changelog
LPS - 63462 update jar
Ignore Update ' modules / apps / foundation / contacts / .
Add config for Travis CI
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fixing transitive - ness of provided
Updated icons for struct and enum
Ignore Update ' modules / apps / marketplace / .
Add StoreMeta which is an empty components for the medium dpi version .
Ignore Update ' modules / apps / collaboration / flags / .
Revert " set zombies after they are be used
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Restored SailGraph ' s Log4j config file .
Bumped version number to 1 . 4 . 0
Resize splash icon
Removed not - needed file
Prepare next dev iteration
Update linux bullet binary ( 32bit )
Bumped version
Updated ognl to 3 . 1 . 2
Remove " allowBackup " from Manifest
Setting version to 1 . 0 . 135
Added small screenshot
Added lkraz to contributors .
Remove unused return statement in ExecutorServiceProxy .
Updated library version to avoid latest 1 . 3 . 1
Added translation using Weblate ( Breton )
Move index for src / java to README .
Remove import from non - existent file
Remove blank line
Added Joachim Baumann to the contributors
Remove a commented line at the end of the file
Removed issue labels from the issues ' summary that were in the " Release 2 . 1 . 0 " help page .
Updating Alloy to e79a782 ; LPS - 13554
Add cassandra - 2 . 3 . 0 .
Response . SetStatus now accepts arbitrary IStatus - derived instances
Fix an unintentional change in method signature ( IDEADEV - 9042 )
Fix InputType determination of WebTextView ( DO NOT MERGE )
Added SQL Console module to jOOQ - Copy authors . Txt
GRAILS - 6290 removed debug . Js
Add extra android support package to travis config
Adds sdp parameter indicating the annex compatibility when g729 is enabled .
Ignore Update ' modules / apps / web - experience / staging / .
Regenerate portal - client .
Remove useless TODO
LPS - 54745 ignore jar
Update libwebp
Adding missing Cydia Substrate library
Added preview image .
Bump up okhttp version
Revert committed tests
Added a readme for instructions on our project
Removed obsolete comment in test template
Remove applicationId from ' dependencies ' repo in POM .
Add missing migration file
Make an internal class package private ( cherry - pick to master to unblock all )
Allow unnecessaryCasts diagnostic to be suppressed .
Delete device - 2016 - 04 - 160244 .
Remove 888
Add dirname so that OTP can be fully as others
Corrected link to create changes docs link in iOS usr / share / red5 / share .
Removed unused art file
Don ' t publish versions on parallel
Check extra exception on shutdown ( ) method ( 0 )
Updated Japanese translation
Removing @ Override flag from compareTo method , since it isn ' t in the superclass .
Ignore Update ' modules / apps / web - experience / product - navigation / .
Added debug printing content of all incoming packets
Added target to .
Fixed a small typo in worldedit . Conf
Ignore NetBean ' s config file
Add a newline for the noun ' build '
Fixed copy / paste error when history methods ( IDEADEV - 6618 )
Remove warning that doesn ' t like it on windows .
Changed URL to www . Robovm . Com in README . Md .
LPS - 50400 Move AsyncBrokerTest to portal - impl , no change
Fix typo
Prepare release checkstyle - 7 . 3
Rename 2 . 6 to 1 . 2
Updated gif
Fixed typo in CHANGELOG . Md
Ignore Update ' modules / apps / foundation / users - admin / .
Removed redundant jar file
Revert properties , 0 , preparing forgot the executor method
Don ' t reference the enclosing type name when it ' s not read ( IDEA - 90953 )
Added files via upload
Updating Alloy to e79a782 ; LPS - 13554
LPS - 45983 Add a line break since it does not always initialized
Checking only test files
Removed unused files .
Remove Car audio class .
DO NOT MERGE - Ringtone bugfixes ( round 1 )
Setting default name for multi - project
Removed debug comment from messages . Js
Add missing default config ( # 2 )
LPS - 65012 Move export - import - service resources to the correct dir
Remove text placeholder in widget titles , closes # 1498
Set BP 3 . 0 . 2 - SNAPSHOT .
Upgrade Shadow plugin .
Ignore Update ' modules / apps / foundation / portal - lock / .
Add metric for managed profile to support list
GRAILS - 5691 - remove unused code that was accidentally rename because it is used
Ignore Update ' modules / apps / collaboration / mentions / .
Bump next version to 2 . 3 . 3
Revert version for release
Ignore Update ' modules / apps / web - experience / journal / .
Reset the build
Ignore Update ' modules / apps / collaboration / message - boards / .
Ignore Update ' modules / apps / collaboration / document - library / .
Updated parent version .
Add an ensureOpen check to Publication . HasBeenConnected ( ) .
Updated AVS proprietary to 2 . 8 . 7
Fix wrong expired drop false
Updated changelog .
Fix build . Gradle with JDK 1 . 6 .
LPS - 12927 Retry safe building logic on reflection invoking failure
Update readme to 0 . 6 . 2
Ignore Update ' modules / apps / collaboration / message - boards / .
Add image for Android listitem
Ignore Update ' modules / apps / collaboration / blogs / .
Ignore Update ' modules / apps / foundation / portal - template / .
Reduce the size of the systray configure icon to 16x16 .
Fix icon .
Move widget preview drawables to drawable - hdpi .
Fix README
Added files via upload
Ignore Update ' modules / apps / collaboration / document - library / .
Add old semicolon in graylog2 . Sh
Setting version to 1 . 0 . 92 - SNAPSHOT
Updated maven - client - plugin to 2 . 7 . 1 .
Ignore Update ' modules / apps / web - experience / site / .
Add another new functionality at the end of the code
Remove openjdk8 from the Travis config
Remove unused setter from HttpConfiguration .
Added a redirect to the new location
LPS - 63462 update jar
Fixed max stacksize on Potions .
Add HADOOP - 9417
Remove unused imports in AnimatorSet .
Update readme . Md .
Add new training trick on mini logo
GRAILS - 10448 - fix failing tests
Don ' t reference the enclosing type instance when it ' s not used ( memory optimisation )
Remove rogue println in test fixture
Added ptr - demo - 0 . 5 . 4 .
Upgrade Ant to 1 . 9 . 6
Remove accidentally added android submodule file
Delete demo2 . Gif
LPS - 53447 let the Group cleanup everything when trying to null
Ignore Update ' modules / apps / collaboration / announcements / .
Smack 4 . 1 . 0 - alpha7 - SNAPSHOT
Ignore Update ' modules / apps / web - experience / asset / .
Ignore Update ' modules / apps / sync / .
Revert " disable 3041579 stream for the init script
We don ' t need Ivy 7 in tests . Xml
Ignore example ' s ' bin ' on H2O - api / README .
Update linux - x86 - 64 natives
Removed unused resources .
Removed unnecessary import
Add LGPL desgination to hunspell
Remove old version number from example - api - http
Ignore Update ' modules / apps / foundation / frontend - css / .
Ignore Update ' modules / apps / foundation / portal - search / .
Revert I3fdda2588a7c612d7c9cfb4f25d9aedd1d609162 which open two functions
Removing dangling directory
Updated sample project to version 0 . 6 . 2 - thrift
Update contributor list , add yaphet , bjlindeqiang , dingjun , Dollyn , feilaoda
ZEPPELIN - 500 - Fix leak of output in Firefox
Fix sync stuff in README . 0 . 3 release
Fixing GLIBC 2 . 4 problem on Debian system .
Add missing RCTConvert import
Update internal framework to multi - gpu support .
Upgraded maven - release - plugin to version 2 . 1 .
Added logo
Add missing dependecy on core - web . Jar .
Add config for Travis CI
Remove the OnItemClick listener when the fragment is destroyed
Provide a reverseEach method for arrays
Fixed bug with saving view loading method call
Add image for simplecursoradapter
Ignore Update ' modules / apps / foundation / portal - template / .
Upgrade version library to 1 . 1 . 0
Removes exception when trying to make it when running it
Updated changelog
Removed unused imports in BufferUtils
Updated BP libs
Revert " Changed power request to activation energy . "
LPS - 56015 We only want the regular parameters , see getParameterValues and other methods in the class .
Delete kk
Ignore Update ' modules / apps / foundation / portal - cache / .
Upgraded netty to 4 . 0 . 20
Ignore Update ' modules / apps / collaboration / blogs / .
Fixed javadoc error
Don ' t run performance tests for parallel
Ignore target directory
Fix crash when using non - create a assert key when running it one is populated
Don ' t parallelize the Gradle tests .
Revert " force monospace font in table window ( IDEADEV - 6618 )
Removed the pdf file so that it does not be part of a recipe
Remove android - 22 from buildscript
Disable RenderThread
Use the latest version of Android Tools
Ignore Update ' modules / apps / collaboration / blogs / .
Removed unused image .
Add STORM - 818 to changelog
Updating astyanax version to 2 . 0 from 2 . 0 - beta
Revert " Caching dependencies to speed up PR builds "
Bump the version .
Ignore Update ' modules / apps / web - experience / export - import / .
Publish next devlopment version .
Fix target package name so tests run .
Learned some new structs from Blizzard ' s Hearthstone
Removing unused enum value in ` BuildRuleSuccess . Property `
GRAILS - 5691 - remove some code that was accidentally left in a memory name
Added methods on broker to integrate Zookeeper based broker .
Add StoreMeta which is an file for the medium dpi version .
Add additional clirr config
Remove unused variable
Revert " added newline at end of file "
Updated changelog
Set correct permissions on the script .
Added missing anchor for docs .
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fix memory leak
Fix a SurfaceFlinger . Shutdown ( ) from creating a cache object .
Commented out a failing line
Remove unused imports from graylog2 . Sh
Removed tag roboguice - 2 . 0 . 1
Prepare release HikariCP - 1 . 3 . 5
Add gradle . Properties and example build
Added a Composite Configuration Diagram to use in the Wiki .
Fixed bug in ByteBufferSend that lead to incorrect complete ( ) method
Ignore Update ' modules / apps / foundation / roles / .
Removed android - support - v4 . Jar .
Adding IntelliJ generated files to .
Update lib / bin / 21 . 1 . 2
Add image for multi task visualization
Improve MongoDB script
Removed the necessary demo .
Add missing semicolon in dialogs . Xml
Delete screenshot_one .
Move vector drawables to proper drawable directory
Remove mongo . Jar and bson . Jar on clean .
Fix link to reflect release 3 . 1 . 0 - alpha7
Ignore local . Properties
Added baseName for uberjar task
Added VIM swp files to gitignore .
Updated changelog
Ignore Update ' modules / apps / foundation / osgi / .
Fix typo in NativeComponentsAndroid . Md
Revert " Bumps commons - pool2 version to latest "
Revert version to 1 . 6
Fixed a bug where the view is blocked by the
Remove redundant dependency .
Added changes entry for and baf36c4
Add cdma_rmnet4 to list of kept - all .
Add Ken to the AUTHORS file .
Fix test data name .
Update FastAdapter to latest v1 . 5 . 3
Updated Gains / Lift screenshots
Changed dependencies back to SNAPSHOT versions after tagging
Ignore Update ' modules / apps / collaboration / invitation / .
Setting version to 1 . 0 . 113 - SNAPSHOT
MinecraftForge / FML @ 0b84b6aa297bdf6ab9f010e340f286442cb242dc Expose the same color for 37284 .
LPS - 57626 Migrate icon
Adding bin to gitignore
Add gradle . Properties to .
Use the latest lib snapshot
Ignore Update ' modules / apps / foundation / frontend - theme / .
Fix l . NewRouteIsCalculated ( updateRoute , true )
Ignore Update ' modules / apps / collaboration / image - uploader / .
Removing appinfo . Jar .
Don ' t include grails - core in POM
Updated Studio with last version
Tweak gitignore to ignore 0 . 8 . 5
Remove unnecessary prop
Rename CREDITS to CREDITS . Md
Add # 3762 to CHANGES . Txt for CASSANDRA - 11051
Added tests .
Ignore Update ' modules / apps / web - experience / layout / .
Remove completed todo
Add AppRegistry to imports
Removed bad import from the rules
Remove unknown app module
Ignore Update ' modules / apps / collaboration / document - library / .
Align Wrapper for View ( PY - 7161
Updated studio with Security + Backup UI
Update todo
Remove spurious ' var '
Update emitter version
Updated changelog
Added another semicolon in docs .
Revert " Make null default on any async instead of leaking it
Bumped 4 . 7 . 0 release notes with Hadoop 7 . 1 .
Removed redundant jar file
Ignore Update ' modules / apps / web - experience / export - import / .
Updated release version
Add missing image resource
Ignore Update ' modules / apps / collaboration / comment / .
Removing the important files from the project file
Bump version to 0 . 9 . 2
Ooops . . . Forgot a conflict with .
Fork a new test JVM every 10
Removed @ Nullable from AppCompatActivity # getData ( )
Use both JDK7 and JDK8 in Travis
Updated version in new build in release
Moved AndroidSDK . Java back into place as it uses test
Modified ' var ' type in ' backspace ' settings ( OC - 5012 )
Changed filter icon
LPS - 54552 avoid duplication of breadcrumb now that it is a portlet
Moved glm pyunit to NOPASS due to intermittently failing more often than desired .
Ignore Update ' modules / apps / foundation / portal / .
Ignore Update ' modules / apps / web - experience / staging / .
Push version to 191 and v9 . 2 .
Now closes ReadableByteChannel after it has been read .
Add STORM - 1473 to Changelog
Add example image to README . Md .
Removed old readme from support . Xml
Bump up zookeeper version to 0 . 4 . 3
LPS - 25788 top links can not show the SF break
Fixed a typo in commonutil .
Eliminate borders from tables in markdown . Css
Fix a slight problem when you compile for the first time and have no ooolocales . Properties
Set last_subscription_check after check
Ignore Update ' modules / apps / web - experience / staging / .
Rolled back bootstrap version
Ignore target directory created by running sample ha - ops bash scripts
Commented maven push for travis
Ignore Update ' modules / apps / collaboration / mentions / .
Prepare for next development iteration
Update readme
Fixed the bug in the theme in the end of the file
Ignore Update ' modules / apps / web - experience / asset / .
Updated jetbrains . Dic
Typo fix a bad date
Added missing early_stopping arg in action bar list ( closes # 1498 )
Removed unnecessary return statement in LineageFileOutStream
Fixed a typo in the configuration ( # 57 )
Fix bug in HTTP2 settings parsing
Don ' t force refresh if data is taken from cache
Removed obsolete openjdk7 from travis config
Add image for multi - runner library
Fixed a bug in ScanSettings constructor
Updated license header
Copy the XML descriptors .
Consolidate javax . Servlet jars
Changed dependencies back to SNAPSHOT versions after tagging
Added Travis CI configuration .
Ignore Update ' modules / apps / foundation / contacts / .
Configuration not needed any more .
Fix problem with installing the build .
Ignore Update ' modules / apps / foundation / portal - configuration / .
Ignore Update ' modules / apps / web - experience / export - import / .
Bump the package name for the site test .
Prepare version 0 . 6 . 1
Removed unnecessary return statement in LineageFileOutStream
Add good icon for free app
Updated version number
Move file to correct folder
Fixed a bug in commonutil .
Don ' t filter help files on messages ( # 57 )
Added empty line
Add icons for Android listitem
Added note to www . Robovm . Gz ( # 60 )
Updated version
Remove duplicate encoding entry from build . Gradle .
Fix gradle build
Add image for simplecursoradapter
Fix build issue
Revert " Change the scope "
Add image for multi - runner library
Add ptr - index - 0 . 4 . 2 .
Missing warning ( ) to not append file with an blank line
Add gitignore file
Updated changelog
Now create a local window . . .
Update apk
Ignore Update ' modules / apps / foundation / portal - configuration / .
Setting version to 1 . 0 . 14 - SNAPSHOT
Remove unused import from AnimatorSet .
Ignore Update ' modules / apps / foundation / frontend - theme / .
Removed unused art .
Ignore Update ' modules / apps / foundation / portal - instances / .
Add " Passivate " not " encodeAsForTags " in " add " option ( PY - 7609 )
Updated ChangeLog
Changed a typo from SHNAPSHOT to SNAPSHOT = )
GRAILS - 11151 remove StatementCache from jdbcInterceptors property in default DataSource properties
Remove sudo added test from travis build
Disable PY - 6643 ( PY - 11499 ) .
Update the menu in the preview of the video
Bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6
Added STORM - 10054 to the CHANGELOG .
Add image so a new dpi package
Added rendered to correct location
Revert " remove newline , that it doesn ' t delete it
Update travis config
Bump version from 1 . 7 . 8 - > 1 . 7 . 9
Ignore Update ' modules / apps / web - experience / trash / .
Add readme for sample app
SONAR - 5736 The calling HelpshiftHelper . Shutdown method method method method method method method method method method method method method method method method change
Add Demo . Apk
Fix up the makefiles and some samples .
Add svm_print_interface
Disable memory size to 0 . Mongodb . 1 for present .
Added missing migration file
Prepare release HdrHistogram - 1 . 0 . 9
Ignore Update ' modules / apps / forms - and - workflow / calendar / .
Don ' t force refresh if data is taken from cache
Bump up version number .
Remove unused import
Allow state loss on fragment change
Rename ActivityCompat23 . Java to ActivityCompatApi23 . Java
Bump version to 0 . 2 . 1 . BUILD - SNAPSHOT
Fixing syncDoc task to avoid up - to - date message only because target directory already exists
Update internal framework to API 24 ( Nougat Final Preview )
Updated changelog .
Ignore Update ' modules / apps / foundation / portal - template / .
Set superclass of org . Mongodb . BulkWriteException to com . Mongodb . MongoException
Add lint caching to travis config
Kill CheckOutputThread on stoptrace ( PY - 12782 )
Updated ChangeLog
Ignore sync - api 1 . 0 . 0 prep next
GRAILS - 11151 remove StatementCache from jdbcInterceptors property in README
Updated version
Disable PY - 11673 Error when building by default
Add gbm . Properties .
Do not encode sendRedirect URLs
Ignore Update ' modules / apps / web - experience / layout / .
Removed accidentally committed image
Ignore Update ' modules / apps / foundation / portal - scheduler / .
Removed release notes that was accidentally committed .
Delete README
Push version to 15 . 0 . 6 , 15008 .
Context stop topic ( IDEADEV - 22220 )
Moved HasXPath into correct directory .
Ignore Update ' modules / apps / web - experience / rss / .
Added image for multi task visualization
Remove warning ( don ' t run it )
Set gradle version to 2 . 2 . 1 for compatibility with Nebula NetflixOSS
Bump common for 4 . 2 . 2 ref
Ignore Update ' modules / apps / collaboration / wiki / .
Ignore Update ' modules / apps / web - experience / asset / .
Fixed a typo in ` loop '
Ignore Update ' modules / apps / sync / .
Incremented the version code of the sample project for GPlay upload .
Add a documentation for the visualization project
Ignore bin / * .
LPS - 57534 Should not use full path , but CI machines have a broken PATH setup , need QA to fix it .
Change default encoding to UTF - 8 & so that something isn ' t run via 30 "
Updated 0 . 4 . 0 - SNAPSHOT to 0 . 7 . 0 - SNAPSHOT
Fix build failure
Fix Travis yml .
Fixed a subtle bug in ParticleSystem . Reset ( ) .
Add # 4494 to CHANGES . Txt
Upgrade version name to 0 . 2 . 3
Added android docs notice to " Demo . "
Added CNAME support for gh - pages
Add Callum Stott to .
Force AST Injected property check with staticCheckerVisitor
Add exit codes for spec .
Removed old readme from support . Xml
Replace list
Updated build . Gradle to org . 4 . 1 .
Updated version
Ignore Update ' modules / apps / web - experience / journal / .
ZEPPELIN - 815 don ' t create a sub - arg twice
Upgraded guava to 16 . 0 . 1
