Delete ic_launcher .
Updated FML
Ignore target , because that is generated code
ignore Update ' modules / apps / collaboration / blogs / .
Updating Alloy to 65b0e38 ; LPS - 29614
specify source encoding
Updated changelog
Add stacktrace for travis .
Fix incorrect solaris / x86 native library
update changelog
Change launchMode of Accounts activity
Delete demo2 . gif
Push version to 11244 .
fixing Junit dep scope to test
ignore Update ' modules / apps / foundation / portal - remote / .
um , this was overwriting all other plugins .
Always invalidate TextView on checkForRelayout
Added STORM - 1272 to Changelog
Auto commit test 2
Reset build identifier to next milestone snapshot
Fix NPE when provider returns null cursor .
Make ideavim compatible with InteliiJ IDEA 10 . 0 . 2
Remove temporary test
Updated support libs to 23 . 3 . 0 .
Pull script for window
Remove empty line .
Fix checkstyle
Create README . md
Revert " Make sure .
ignore Update ' modules / apps / marketplace / .
Upgrade gradle to match upstream .
Fix checkstyle violation - extra import .
Fix single test
Add default constructor to Proguard rules
Rename method
update libwebp
Update build branches
update adbiFilters
Fix data driven testing example in documentation
ignore Update ' modules / apps / web - experience / journal / .
Set source level to 1 . 7 for javadocAll if possible
ignore Update ' modules / apps / collaboration / flags / .
LPS - 30240 Move IntraBandPortalCacheManagerTest from portal - service to portal - impl , because the dependence to MemoryPortalCacheManager
upgraded netty to 4 . 0 . 31
Prepare next development version .
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4
Create README . md
moved pyunit to NOPASS .
Adding an empty line to test the import script
updated jline
Add art assets
Added a gitignore
add NOTICE file
add conf / tachyon - env .
updated ChangeLog
IDEA - 77239 Cannot checkout project from github
Thymeleaf support words
fix this $ 0 groovyc problem
Add finish ( ) after timeout of Reqeust Arc operations .
ignore Update ' modules / apps / foundation / contacts / .
fix test data
Removed extraneous comments
fixed PY - 3637 test runner progress in django
Removed image , never used .
Move file to correct dir
Add versions to fbobjc .
don ' t include grails - core in POM
Changed defaults when creating new room .
Remove TBD from fields and properties section
added getCollection ( Class ) to interface
add free marker and junit in supplementaryLibs
Create README . md
Bump SpongeCommon ref
ignore Update ' modules / apps / collaboration / message - boards / .
HHH - 7578 Sybase does not support " unique not null "
added id to textview
ignore Update ' modules / apps / marketplace / .
remove useless println
rename class to match file
Help id corrected .
We don ' t need libopencore_author and libcutils in libmedia_jni
Updated Gains / Lift screenshots with new images from Nidhi
Thymeleaf support words
update changes . txt
proofreading EDU
Removed another version from the pom
don ' t return null network .
Don ' t show suggestions
update changelog
Fix Copyright Year
adding influencer , influencers
bumped up gradle to 2 . 4
ignore Update ' modules / apps / foundation / map / .
Updating samples
fixed clirr config
add source and target compatibility to 1 . 6
Upgrade os - maven - plugin to fix the build issue
Adding missing Notifications icon
Remove unused notification icons .
ignore local tmp dir
fixed version
add table of contents in python / README
The / green command should now only affect dirt on the top layer .
Added tests to index
Add missing piece to the build . gradle .
Add version back into compile notes
Appease the checkstyle overlords .
remove component ' s events when dealloc is called . "
Fix broken test name that prevents test from running .
removing bitdeli - badge
Create test
LPS - 68014 update jar
ignore Update ' modules / apps / collaboration / microblogs / .
Fixed SAML SSO
Fix focus issues with dialpad in the call dialog .
fixing missing types in capture method
updated crate / elasticsearch so the license headers are correct in the upstream
switch off unsupported sparse extensions for our hg version ( 2 . 6 . 2 )
add STORM - 1503 to changelog
update changelog
Fix check style
Upgraded maven javadoc plugin to 2 . 9 in order to fix javadoc generation
Added the manual to the build .
Updated wrapper version .
ignore Update ' modules / apps / foundation / portal - search / .
Updated todo
ignore Update ' modules / apps / web - experience / asset / .
Add permission model - - Adding a newline at the end of FsPermission . java
Updated Travis CI for newest dependencies
update emitter version
moving to latest release of jain sip
Normalize line endings
Remove redundant modifier
ignore Update ' modules / apps / collaboration / notifications / .
build number 114
removed old NOTICE file
Move test to NOPASS
updated studio
ignore Update ' modules / apps / foundation / web - proxy / .
bump version
Added STORM - 765 to Changelog
update Readme .
add function with zero arguments
Add eclipse plugin .
update cacheword to get build fixes
updated version
Fix RTL layout in Recent Apps , landscape mode
Do not use unreleased checkstyle rules
follow / unfollow API
Updated Vanilla dependency to 1 . 3 . 0 - SNAPSHOT .
do not lock files
optimize build release script
Fixing GLIBC 2 . 4 problem on Debian system .
add RippleBackground
Add missing JSON highlighting to example .
ignore Update ' modules / apps / foundation / frontend - js / .
improve TextInput docs
avoid conflict with prev PR
add HBase testing directories to gitignore
Remove unnneeded .
ignore Update ' modules / apps / foundation / frontend - taglib / .
testing push mails
Revert " bump version for development "
Don ' t allow onBackPressed to be called while AstridActivity is finishing .
ignore Update ' modules / apps / web - experience / asset / .
Correct a type annotation in w3c_indexeddb .
Ignore IntelliJ output directory .
update README . md
ignore Update ' modules / apps / collaboration / document - library / .
update to latest android support libraries v23 . 2 . 1
Remove unused function arg
Set min api to 9
Updated version number to 0 . 23 . 0 - SNAPSHOT
Added javadoc
bump version
Provide a reverseEach method for arrays
Reverts removal of @ JsonIgnore on Event . type field
Add a new contributor
added the Gremreaper logo .
ignore Update ' modules / apps / foundation / portal / .
ignore Update ' modules / apps / screens / .
Switch the visibility of LazilyInitializedInfo . clone to protected since it ' s only used by JSDocInfo .
update to classworlds 1 . 1 - alpha - 1
update readme
Push version to 190 .
ignore Update ' modules / apps / forms - and - workflow / polls / .
Revert " Enable OpenCORE on master - part 1 "
Update the alias in the server side trust store to match the name used for the certificate .
updated studio
ignore Update ' modules / apps / foundation / frontend - js / .
ignore Update ' modules / apps / foundation / frontend - taglib / .
ignore Update ' modules / apps / foundation / roles / .
Updated mockito to 1 . 8 . 0
Fix NPE on isValid for an expired session when activity check is enabled .
removed System . exit ( 0 ) from RunTests
update readme
Add logging for unknown state .
remove language " fr "
ignore Update ' modules / apps / web - experience / export - import / .
Update Android build tools ( # 908 )
added scripts to create heron - tools self extracting binary
Fixed closing socket in debuger .
update sparc natives
Fixed asciidoc issue
Switch basic auth back on in web - secure
Rename Histogram to DHistogram in an effort to avoid a class name collision
Added curContext . blendFunc to fake - dom .
proofreading EDU
add and initialize README . md
updated version
Compiled w / jdk 1 . 4 . 2
ignore Update ' modules / apps / collaboration / wiki / .
Increment of invalid packets counter needs to be concurrent because it is used by both sender and receiver threads .
updating changelog
Added tag 1 . 0 - RC1 for changeset 4daa5ed3ef0e
updated version of jikes
ignore translator - web 1 . 0 . 2 prep next
added latest jar
changed the inner class to static
Updated ic_sysbar menu asset
ignore Update ' modules / apps / foundation / portal - configuration / .
Move the version to a separate file
ignore class files in root ( which are generated by " gradle test " )
Set bg and fg colour in site . css
Delete fair - scheduler - allocation . xml for YARN - 1300
remove underline on focused link
bump version to 1 . 2 . 4
Use the latest version of Gradle
LPS - 55531 Move FileSystemStoreRootDirException to portal - service
bumped version
add bin / and gen / to ignore list
Expose FloatingActionsMenu . isExpanded ( ) state
prohibit " Schafmittel "
adding logo
The CI build no longer runs * all * compatiblity tests .
Prevents unnecessary exception from GA failure .
Upgrade version .
Fixed test
Removed a System . out
Ignore OSX and IDE files
Removing support library vector drawables as 23 . 1 doesn ' t support it yet
Fixed version in the notes
Delete help button from postfix completion configurable
Removing println from OperationMerge
Delete helloworld . meta
Vertical drag supported overriding clampViewPositionVertical method .
reset utterance counter upon stop ( )
default focused control is OK button
Make uploadMavenCentral task , that encompasses other tasks
Updated changelog
Prepare version 23 - beta3 .
ignore Update ' modules / apps / foundation / portal / .
updated es module
added STORM - 1053 to Changelog
Bumped version
Disable one of the ` ExternalJavacIntegrationTest ` test cases .
ignore files
add provider properties action
Saving Blacklist and Hold for Moderation lists when dismissing dialog
Updated changelog
ignore Update ' modules / apps / web - experience / iframe / .
Bump the version
prepare for next development iteration
save storage format version after successful cleanup
add getter for GenericVertex max index
Nexus S now reports the proper frame - rate
update README . md
updated screenshot
Set beta_features to True .
Add makefile
prepare release HikariCP - 1 . 3 . 5
Solves script can now pick up env var JAVA_HOME
added intellij specific file to .
bump version
Removed last trace of Wildfire . . . . .
Deploy the upgrade info as an artifact .
change default markdown rendering to not use hard wrap
add PaDeviceInfo_getNameBytes method .
Fixed VM memory leak in AudioSystem JNI interface
Regenerate WSDL
ignore Update ' modules / apps / foundation / web - proxy / .
Bumping project configuration requirement to Android 2 . 2
set version for release
Added explicit HystrixPlugins . reset ( ) to HystrixTimerThread init of each test
Added STORM - 1561 ot Changelog
prevent thread leaks due to deallocator prestarting threads
ignore Update ' modules / apps / static / osgi / .
ignore Update ' modules / apps / collaboration / blogs / .
ignore Update ' modules / apps / web - experience / export - import / .
Added gitignore .
Prepare next release v1 . 0 . 2 - SNAPSHOT
Updated readme
Fix start - mac .
Remove build . sh debugging flag .
update linux - ppc64 native
add words
adding IDE related files to .
build linux / i386 against older glibc ( 2 . 3 . 4 ) for compatibility
do not lock files
Fixed the problem with maven publication .
Added STORM - 787 to changelog
added titan and captheorem image for documentation .
Missing CHANGES . txt for YARN - 2503 .
remove unused import
restored projectName property to support backwards compatibility with plugins etc .
Enlarge default size for the main window .
ignore Update ' modules / apps / web - experience / asset / .
Ignoring TDB files .
Fix cqlsh DESCRIBE column order
Removed DS_Store files
IDEA - 126585 " Evaluate Code Fragment " dialog uses some strange proportional font in editor
don ' t compress jars
Remove the superfluous ProGuard rule for the database package
add overlay for cpp subproject
Fixing phpunit invocation
Removed debug logging added with r1061929 .
Bump the version to 2 . 0
documented changes so far
LPS - 47461 Add entry - action style
ignore Update ' modules / apps / collaboration / recent - documents / .
Updated doc for 1 . 8 . 0
Add Ken to the AUTHORS file .
adding branch in .
Adds ' More ' custom action icon for Android Wear devices
Make sure background drawables are correct when View is attached
start drag of text selection on initial press
setting version to 1 . 0 . 135 - SNAPSHOT
Removing wiki repo submodule
Bump readme version
Fixed bug in proguard . cfg
ignore Update ' modules / apps / collaboration / mentions / .
ignore Update ' modules / apps / web - experience / portlet - configuration / .
ignore Update ' modules / apps / collaboration / ratings / .
do not run tests in parallel
Update the ptbtokenizer test to reflect the non - americanization
removed extraneous whitespace from pull request
ignore Update ' modules / apps / foundation / petra / .
Fix broken build
changed image transparency
Move H2OApp into a package
update FML for gradle changes
Add Eclipse ' s bin / folder to .
Updating Alloy to f506b55 ; LPS - 17157
Fixed a bug where the notifications could overlap when reset
Removed a System . out
Updating Alloy to 07c34ac ; LPS - 29771
Updated RecyclerView support lib to V22
setting version to 1 . 0 . 145
Updated TCK .
update w32 native
Remove redundant version number from application . properties ( grails plugin )
ignore Update ' modules / apps / foundation / portal - template / .
allow private constraints to be retrieved as a read only property
Added thirty minute per test time limit , to avoid stalled tests
update deskshare applet
Remove unused variable
ignore Update ' modules / apps / web - experience / journal / .
Fixed a bug with the init script to make it work in IE .
Fixed a naming issue
Adding whack to messenger to allow for cleaner dom implementation of basic xmpp handling .
add lint abort to demo ' s gralde build script , ps for travis - ci
Add product flavor to reduce build time on debugging
install database - migration plugin by default
Using jetty - test - helper version 2 . 7 .
Should fix black laser beams .
added a missing def
If no security filter is added then display all resources
updated launcher icon to match green / white of other msging apps
Updating Alloy to f506b55 ; LPS - 17157
Upgraded wrapper
fixed tag state identification problem
ignore Update ' modules / apps / collaboration / invitation / .
ignore Update ' modules / apps / web - experience / site - navigation / .
Disable the JDK 6 and 7 builds on this branch - - no point loading up
Bump common ref .
don ' t index unsaved files ( ie , no context )
Updated readme
Added folder for the visualization project .
add Compression . NONE
update demo
ignore Update ' modules / apps / sync / .
ignore Update ' modules / apps / collaboration / wiki / .
Using 1 . 1 . 0 of gradle plugin
add more margin to bottom .
ignore Update ' modules / apps / foundation / portal - scheduler / .
Added gitignore .
ignore Update ' modules / apps / marketplace / .
Update stack diagram .
Add branch name " master " to version . properties
LPS - 66316 ( WEB ) Move css file
Added link to contribute page
ignore Update ' modules / apps / foundation / portal - search / .
Removed margin from ' add button ' .
ignore Update ' modules / apps / adaptive - media / .
Updated github page logo
don ' t tweak left margin for ssh button panel
ignore Update ' modules / apps / foundation / frontend - editor / .
Bump jxmpp to 0 . 5 . 0 - alpha7
Add ABS as dependency to library ( fix # 559 )
add STORM - 555 to changelog
Prepare library for release 2 . 1 . 3
Added gitignore .
Removed doc / shared submodule
Fix - - filter documentation
ignoring target directory created by running sample ha - ops bash scripts
Update shiped ForgeGradle for 1 . 7
Hiding DrawerLayout does not fire correct accessibility event .
fixing the name of the sort icon for hdpi
ignored dependency - reduced - pom .
updated server icon
ignore Update ' modules / apps / foundation / my - account / .
Fix OSGI version
setting version to 1 . 0 . 128
missing import
missing import
ignore Update ' modules / apps / foundation / monitoring / .
Fix task leak in coordinator
add google classic style loadmore
update Bootstrap ' s entry in the NOTICE file
adding ommitted file
Fix log version string .
Set NODE_ENV and use node - env - inline plugin
Revert sound change ( # 63 )
ignore Update ' modules / apps / forms - and - workflow / calendar / .
Updated changelog
Add logging of Bintray user for CI
Fix changelog by adding a new empty section
Implement PrestoConnection . getTransactionIsolation
upgraded some JAR files in the project
Add CHANGELOG . md
update changelog for 1 . 1 . 1
Add travis - ci configuration
prepare release curator - x - zkclient - bridge - 3 . 0 . 0
Fix missing line after import codenarc
Add files via upload
Add a statically linked , 32 - bits x86 protoc ( v2 . 5 . 0 ) for Linux .
added few known transitive verbs .
Prepare next development version .
Fixed deserialization problem in DatePicker .
KT - 1036 JetFile - > PsiJavaFile cast problem - one more test for changed diagnostic behaviour
logging stuff 1 .
updated version
fixed asm jar version
add new subproject to pom file
Removed reference
Add sample preview
use 500 as max output lines on all platforms
replaced print with logging
update README . md
Upgrade gradle plugin to 2 . 2 . 0
ignore Update ' modules / apps / marketplace / .
setting version to 1 . 0 . 77 - SNAPSHOT
added icon to reset magnification in desktop sharing
Simplifying the default welcome presentation
Added STORM - 1270 and STORM - 1274 to Changelog
ignore Update ' modules / apps / web - experience / layout / .
Using the latest buildtools version here too
Smack 4 . 0 . 2 - SNAPSHOT
Updated BP wo last snapshot
Add image for a notification view
Adding more temp files to gitignore
setting version to 1 . 0 . 132 - SNAPSHOT
Change Sorbian ISO 639 - 2 from wen to hsb
Fix unbounded expansion of cumulative buffer in SslHandler
ignore Update ' modules / apps / collaboration / notifications / .
ignore Update ' modules / apps / collaboration / bookmarks / .
optimize to_maven script
Bump up RC version in curr . release
try new about format
gets intermittent glm assertion error
ignore Update ' modules / apps / foundation / frontend - theme / .
shut up linter
experimenting the OSGi stuff , parent 7 - SNAPSHOT deployed on Nexus
Fix AppleBundle # getBuildSteps ( ) so it returns a non - null value .
removing appinfo . jar
alternately patched avro jar
fix ( driver ) make Find . Hint a static class
I don ' t really see a justification for doing a blocking write on close .
Add image for multi task visualization
setting version to 1 . 0 . 7 - SNAPSHOT
Updated changelog
Declare orientdb - core dependency to be of jar type
Updated changelog
Remove unnecessary spaces from docs / manual / dynamicform .
Fixed typo in .
add docs to keep up to date
Fix sync tests failure .
removed apk
ignore Update ' modules / apps / foundation / configuration - admin / .
don ' t compress jars
Bluez doesn ' t handle disconnect while connecting well .
fixed PY - 6543 Django manage . py commands not working
ignore Update ' modules / apps / foundation / petra / .
add YARN - 4367 to 2 . 8 . 0 .
Don ' t re - throw exception in onThrowable
Temporarily disables the MSN test suite so that we could have a new build .
The emojicon size was not consistently taking effect when it was set after the text was set .
Do not include svg - s in the default resource pack
optimize release builder
LPS - 12050 PortletClassLoaderUtil should release reference to PortletClassLoader after PortalClassLoaderServletContextListener context destory
Only run compile / unit tests in Travis
update macosx bullet natives
Added zero - arity body to comp function returning identity fn
ignore Update ' modules / apps / collaboration / bookmarks / .
ignore Update ' modules / apps / foundation / portal - store / .
fixed reference to ActorSerializer
ignore Update ' modules / apps / collaboration / document - library / .
ignore Update ' modules / apps / foundation / portal - template / .
Added zero - arity body to comp function returning identity fn
ignore Update ' modules / apps / foundation / frontend - theme / .
Built new snapshot
improved handling for Droid Incredible 2
LPS - 52093 moves icon
add reply . writeNoException ( ) for quick response
ignore Update ' modules / apps / foundation / frontend - css / .
ignore Update ' modules / apps / forms - and - workflow / polls / .
Prepare next release v0 . 90 . 2 - SNAPSHOT
Create zmnhnd . xml
LPS - 2900 - Firefox ( and other browsers ) will only show the scrollbar when needed
Add Lucene version in plugin . properties file
Use truth snapshot until truth > . 24 is released
Bump readme version
updated ehcache dependency to 1 . 1
Prepare next development stage
add image for transition drawable
Fix uninitialized variables in Caches . cpp
setting version to 1 . 0 . 126
Download apk directly from here
touched changed log so Travis CI tries again .
Include a call to ` ulimit - a ` when building in Travis CI
update README . md
ignore Update ' modules / apps / sync / .
ignore Update ' modules / apps / foundation / frontend - theme / .
Set self . camera to nil when stopping session
ignore Update ' modules / apps / web - experience / journal / .
LPS - 67914 Do not commit private . lar
Added Artur to the contributor list
ordering tests
Make gradlew executable on linux
ignore Update ' modules / apps / forms - and - workflow / polls / .
ignore Update ' modules / apps / foundation / plugins - admin / .
ignore Update ' modules / apps / foundation / configuration - admin / .
Set node size to 10 in NodePencil .
JAL - 35 Add image notes to non - proprietary licenses
Updated irc - api library to rev . 194 .
ignore Update ' modules / apps / web - experience / asset / .
Fix nit in pom . xml
catch Throwable on startup rather than Exception
ignore Update ' modules / apps / marketplace / .
ignore Update ' modules / apps / web - experience / trash / .
Set isInEditMode ( ) to true # 9
Removed android - support - v4 . jar .
ignore Update ' modules / apps / collaboration / directory / .
Ignore outstanding delayed shutdown on restart
bump deb version
LPS - 45983 Add a line break since one depends on the other
Add postgresql in the allow_failures block from travis config ( see # 382 )
Updating release version to 0 . 96 in build . properties
ignore Update ' modules / apps / collaboration / notifications / .
remove fiel
Taking away test file
fixed travis build problem
Remove unused file
Deprecating ExternalResources .
ignore Update ' modules / apps / web - experience / export - import / .
upgraded junit
Add a redirect for / index . html on the site .
Don ' t build aggregated source jar .
Add ICU as a java library for docs .
ignore Update ' modules / apps / foundation / portal - security / .
Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode .
Bump version to 3 . 0 . 0 - beta . 1
Remove duplicated definition of alarm_active .
Updated readme
ignore Update ' modules / apps / foundation / frontend - js / .
ignore Update ' modules / apps / collaboration / wiki / .
Revert " Revert " LPS - 54998 SF "
add icon
Updated changelog
Bump Idea compiler process heap to 1 . 5GB
Force ' marke all as read ' in the overflow menu .
ignore Update ' modules / apps / forms - and - workflow / calendar / .
setting version to 1 . 0 . 148 - SNAPSHOT
ignore Update ' modules / apps / collaboration / message - boards / .
Updating gradle tools version
update video library to gstreamer - java 1 . 6 and jna 3 . 5 . 2
Fix the bug on Libsvm 3 . 14 that not free the memory allocated for sv_indices .
ignore Update ' modules / apps / web - experience / site - navigation / .
ignore Update ' modules / apps / collaboration / item - selector / .
upgraded netty to 4 . 0 . 35
Adjust maven assembly so that the tarballs are not released to our artifactory on release .
Make gradlew executable on linux
Add maven central repo to readme
add exec header . sh
updated AUTHORS . md to include Vingles
Add maven central repo to readme
LPS - 4808 - Migrating Browser Selectors / extensions to Alloy
Updated FAQ
ignore translator - web 1 . 0 . 0 prep next
prepare release HikariCP - 1 . 3 . 5
updated example image .
Revert " Revert " Bump major version to 2 . 23 "
Delete obsolete icon
Add a libbase static depedency for aapt2 .
Added gitignore .
adding another exception test
Upgrade gradle plugin to 2 . 2 . 0
Ignore OSX and IDE files
Uses a Thread pool for StunClientTransaction in order to improve performance .
Updated readme
updated credits
Added lib dir in cassandra - 0 . 7
ignore Update ' modules / apps / foundation / configuration - admin / .
ignore Update ' modules / apps / web - experience / journal / .
Push build .
Updated wrapper version .
Add maven central repo to readme
Remove " Set up library later " from dialog
ignore pom . xml . versionsBackup
FIX Dashboard always display a scroll in IE7 ( cherry picked from
Eradicate whitelisting
fixed key type .
Remove spurious @ Override .
add IRC notifications to travis
Built new snapshot
ignore Update ' modules / apps / foundation / contacts / .
adressing review comment for # TACHYON - 1243
Fixed bug in dumper ( compile - server ) .
Git hygiene
ignore Update ' modules / apps / collaboration / item - selector / .
ignore Update ' modules / apps / web - experience / layout / .
prepare release acra - 4 . 5 . 0RC3
Updated hector link in README . txt to match Readme . markdown
fixed typo in config file .
Delete fair - scheduler - allocation . xml for YARN - 1300
fixed IDEA build configuration
improved logger
add cloud - azure module
Make gradlew executable on linux
Added an empty / res / .
update changelog
LPS - 10193 Cast group_ .
follow / unfollow API
Fix errors found by the new check .
ignore Update ' modules / apps / forms - and - workflow / calendar / .
Remove fflush from hdr_percentile_print .
Delete Thumbs . db
ignore Update ' modules / apps / forms - and - workflow / calendar / .
ignore intelliJ files
ignore Update ' modules / apps / collaboration / bookmarks / .
Make uploadMavenCentral task , that encompasses other tasks
Removed leftover name field
Renamed README to README . md
Fix typo in log message .
ignore Update ' modules / apps / web - experience / journal / .
Added MANIFEST . in needed for building PyPI package .
build make buildlog include tests run and fail stacktraces
immediately update todo tree ( IDEADEV - 20186 )
Updated README . md
Add 111
update classpath for javadocing
Indicate temporary status of YouTrack in README .
Added Makefile for R .
Added " elastics " client for javascript
Updated readme
ignore Update ' modules / apps / foundation / portal - security / .
Replace local copy of TimerMixin with module from npm .
Added STORM - 1408 to Changelog
Adding codecov support to travis
Updated changelog
Converted png to ico
add getRegion to PolygonSprite
Updated version in README
update Readme .
add API reference docs filtering for level 20
add a few more tests to pyunit smoke test list
Push version to 13 - beta6 , 11249 .
make full message view whitespace - aware so we can do cool ascii - art
ignore Update ' modules / apps / collaboration / blogs / .
Remove ' performanceTest ' entries from .
Create webapp / llap directory for MiniLlapCluster
save watches per configuration type - fixed tests
ignore Update ' modules / apps / web - experience / journal / .
omitting rbx - 19mode from travis build for now , because hoe is acting up .
DO NOT MERGE ANYWHERE Update support library version to 24 . 1 . 0
setting version to 1 . 0 . 104
Flip EMERGENCY_ASSISTANCE_ENABLED to true
Fixed TextInput . blur ( )
upgraded json path to 2 . 0 . 0
Renamed rnc file .
include tests in package - plugin
Remove extra traling space
ignore configured dir
update coverage to jdk 9 compatible asm
promote InconsistentArrays lint check to error
Added STORM - 500 to Changelog .
ignore registry - api 1 . 0 . 1 prep next
Updated upgrading section
Remove post tag in circle file to attempt build fix
added TODO
Make gradlew executable on linux
Don ' t update TextureView ' s surface if the Layer doesn ' t exist
Prepare next release v0 . 87 . 2 - SNAPSHOT
Updated readme
fixed wrong model name
ignore Update ' modules / apps / foundation / hello - world / .
update changes . txt
comment out snapshot plugin for release
SONAR - 3429 In rule descriptions , " < p > " should have vertical spacing
Update android build tools
mention 5950 in NEWS
removing assembly
Updated changelog
ignore Update ' modules / apps / foundation / frontend - js / .
Remove another unused method .
update to latest android build tools
Remove failed test to troubleshoot
add jdk8 to build matrix
Releasing OrientDB 2 . 1 - rc6
Reduce the amount of logging from the Javadoc plugin .
ignore idea ' s .
Ignore OSX and IDE files
Fix latest plugin version
Added Makefile for R .
Fixed import error
update to latest android gradle build tools 2 . 0 . 0
Upgrade ZkClient to 0 . 8
Updated changelog
Added makeGLMModel call to python .
changed a typo from SHNAPSHOT to SNAPSHOT = )
Updated changelog
ignore Update ' modules / apps / collaboration / item - selector / .
update to latest support libraries v23 . 3 . 0
minimal json update version to 0 . 9 . 2
Revert " LPS - 66282 Increase app server startup timeout to 15 minutes to match ant "
Upgrade Support Library to 24 . 1 . 1
add osm module to parent pom
catch more exceptions during tearDown ( )
Fix fileHasAnnotations for Repo
remove spurious character
updated CHANGES . txt
Remove temporary file npm . tar . gz from Git
Add missing specialized implementation for Counted / count on StringSeq .
Ensure only a single scroller animation callback per frame .
update latin names
Update build tools to 21 . 0 . 2 .
Remove unneeded method .
Remove a debug line
Add lintOptions in build . gradle
upgraded to recent classworlds release
add 32 - bit linux version of launch4j
adding TODO for system overview diagram
Fix master build
forgotten jars
Fixed test
Remove unused file
ignore Update ' modules / apps / foundation / portal - template / .
ignore files
Fix issue with state reset
modify mute / unmute buttons and icons
make sure we only sign when uploadArchives is run
Ignore patterns
Set isInEditMode ( ) to true # 9
Grails Controller tests generator modified
add heap dump on OOM , see # 304
Removed a redundant call to setDefaultButton
update libwebp
ignore Update ' modules / apps / marketplace / .
Remove outdated ( and wholly unnecessary in this case ) README for wordcount examples
Updating Alloy to f506b55 ; LPS - 17157
Strict compile warnings
Use the main WorldEdit version for Sponge
Add self as contributor
Replace screenshot with a new one
ignore Update ' modules / apps / web - experience / xsl - content / .
Added akka application packaging cache to the ignored files .
fix the misleading model_key name
override canNavigateToSource for the future compatibility
add iris test file
Add debug to version name
ignore Update ' modules / apps / foundation / frontend - js / .
Add sudo false to use container - based infrastructure .
ignore Update ' modules / apps / collaboration / document - library / .
updated my e - mail address
Fix double counting of written characters .
Fix uninitialized variables in Caches . cpp
Updated refs
set openpgp - api - lib to a version that actually works
ignore Update ' modules / apps / foundation / portal - security / .
ignore Update ' modules / apps / web - experience / export - import / .
Updated copyright .
LPS - 65521 Ignore SF for now
Ignore mac hidden files for ant auto - complete
Adds Gson and GsonConverter for Retrofit
Added Example apk
add weex . jks wee . txt
updating examples for rev 0099
LPS - 59594 Fix run format - source checks outside the portal
add favicon
LPS - 66860 prep next , use latest
Explicitly specify jspc version
Use new Alluxio logo
setting version to 1 . 0 . 116
LPS - 42723 Remove blank line
Updated changelog .
Should have child graphs .
add function graphic
Bumping commit of submodule
Run the tests in parallel .
added date stamp
Prepare next development version .
Fix flexible rails , Closes # 944
Add redis to .
Removed Thread . dumpStack ( ) calls used for debugging .
ignore Update ' modules / apps / foundation / portal - settings / .
FileList implements IArrayLike < ! File >
gradle should output the stacktrace for test failures
prepare for next development iteration
build make buildlog include tests run and fail stacktraces
add function with zero arguments
Revert " travis build check "
Fixed readme file
Ignore editor backup files
unbreak accessiblewebview
ignore " bin " directory ( created by Eclipse )
Added STORM - 1190 to Changelog
Make gradlew executable on linux
include outbound socket exceptions at debug level
Improve environments .
Added copyright year entry to configuration file
Added lintVitalRelease as suggested by @ DimaKoz
prepare for next development iteration
Adds Retrofit library
LPS - 68970 rename file
README . md support English
ignore target
Add a 192x192 xxxhdpi icon ( scaled down from 512x512 )
Don ' t upload codecov results if jacoco wasn ' t run , as it generates an email warning now
Added a gitignore
Updated the help jar
ignore Update ' modules / apps / foundation / hello - world / .
LPS - 27200 Jetty needs JNDI
update version of build tools
Use the new Android 2 . 0 - style SDK value for this field so it compiles
ignore Update ' modules / apps / collaboration / mentions / .
Updating Alloy to f506b55 ; LPS - 17157
Ignore editor backup files
add new module to platformImplementationModules
ignore Update ' modules / apps / foundation / my - account / .
ignore Update ' modules / apps / ip - geocoder / .
Removed old Javadocs .
Build scripts moved packaging
LPS - 27654 - Adding Translation in Web Content in Control Panel on IE8 Breaks
ignore Update ' modules / apps / collaboration / announcements / .
Add sample apk
Started new demo .
bump to 1 . 7 . 6 and minor CHANGELOG cleanup
fixed typo in comment
Fix reboot loop due to NPE .
Adding IntelliJ files to ignore
Fixed small error in README
do not run tests in parallel
use minSdk 11 for Sample
add PaDeviceInfo_getNameBytes method .
Upgraded slf4j - api from 1 . 6 . 1 to 1 . 7 . 2
add image for listview and custom listitem
update FML for gradle changes
comment out snapshot plugin for release
ignore Update ' modules / apps / web - experience / layout / .
Set default encoding to UTF - 8 ( fixes # 192 )
Fix descriptor leak after accepting connections
Made empty constructor for ModMetadata public
Remove unused icon .
Fixed isDrawing .
Changed Target SDK to 21 ( Lollipop )
Restored formatting interfaces to provide same functionality as v0 . 95 .
Fix ref to lucene . apache . org
ignore Update ' modules / apps / foundation / contacts / .
set IDEA JDK from build script
prepare release checkstyle - 6 . 13
Don ' t run performance tests in parallel .
Adding myself to Travis notifications
ignore Update ' modules / apps / collaboration / document - library / .
LPS - 33648 - Remove the constraining width from AutoComplete suggestions popup
Drop unused lab drawable .
Updated changelog
update applet zip
Added an object file and a elf file to the test data
remove empty duplicate AbstractEdge
Build ' client ' target with - Wno - sign - compare .
FileList implements IArrayLike < ! File >
LPS - 57173 Wake all thread waiting on the manager
help ID ( PY - 4108 )
ignore Update ' modules / apps / collaboration / directory / .
LPS - 61001 Move java file
ignore Update ' modules / apps / collaboration / quick - note / .
Fixes an issue which could cause CPU starvation while receiving from MultiplexingDatagramSocket .
ignore Update ' modules / apps / sync / .
Build tarball only
Fix build errors with m2e
Include message history in stacktraces from error handler , making it easier to know where the problem was .
fire file statuses changed event after adding ignored files ( IDEADEV - 16670 )
updated changelog
Updated README
Remove LOAD_OS_APP message from standard context hub messages
add constant for rstudio user identity display
wake - up sleeping reader when stop is called
optimize p . redraw ( )
Added IDEA files to the .
ignore Update ' modules / apps / collaboration / document - library / .
Add intellj project files to .
Skip auth setup if AllowAllAuthenticator is used
ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fixed a subtle bug I happened to introduce last night .
remove patch verb , not supported by HttpUrlConnection
Remove text capitalization in widget titles , closes # 1498
fix the build
adding fonts and new buttons
fixing line endings for .
updated CHANGES . txt for Breton .
Adds * .
Ignore target directories
Fix wrong file name
ignore Update ' modules / apps / foundation / frontend - theme / .
fixing a memory leak when creating a new node and not adding it to the tree .
Ignore VIM swp files .
add jcenter to repositories to get actionbarsherlock . aar
ignore Update ' modules / apps / foundation / portal - settings / .
Use Android Gradle Plug - in v2 . 2 . 0 - alpha6
Bump SpongeCommon ref
Fixing an issue with that damn bundle plugin again .
when building the simulator on linux , link ( only ) with libdl , as opposed to also making libdl a build target .
Rebuilds libAEGetURLEventHandlerAgent . jnilib for Mac OS X 10 . 4 compatibility .
prepare for next development iteration
ignore Update ' modules / apps / web - experience / product - navigation / .
Fixed IndexOutOfBoundsException in EpisodesFragment
Fixed colspan .
Make Bazel compile ( a previous change added a graph - > jsr305 dependency that was not reflected in the BUILD file )
Upgrade gradle
Fix NPE on isValid for an expired session when activity check is enabled .
ignore Update ' modules / apps / collaboration / announcements / .
updated sbt idea plugin to 1 . 5 . 2
Travis does not support a JDK named ' openjdk8 '
ignore Update ' modules / apps / foundation / users - admin / .
Fix potential NPE in WebView
added new config files to gitignore
ignore Update ' modules / apps / foundation / login / .
ignore Update ' modules / apps / foundation / users - admin / .
upload demo gifs
Updated README
LPS - 10836 remove local address after do local method for Unitcast situation
Remove unused file
Starting a new 1 . 0 Release
Push version to 13 . 1 , 11256 .
Updated forms . AsmCodeGenerator for custom BorderFactory client property
+ x for wait_for_emulator
Fixing transitive - ness of provided
prepare release acra - 4 . 6 . 0
Ignore IDEA project / workspace files
save watches per configuration type - fixed tests
Removed Key Value Server from SVN repository .
cleaning up 1 . 8 . 6 warnings
LPS - 43729 - Blogs subscribe links not contained in portlet container
Updated CHANGELOG . txt .
update readme
ignore bin directory
Use Gradle Android 0 . 6 .
Add missing test resource ( # 2 )
ignore top level dsl - support dir
Updated refs
update osx / darwin native
Update gradle build tools
Added STORM - 1168 to Changelog
Removed an accidental line break to retain the standard code formatting .
ignore Update ' modules / apps / collaboration / ratings / .
LPS - 65017 Move resource - actions
Changed break extension to have 2 buttons for breaking on request and / or response
LPS - 57004 Batch tests should print gc logs
ignore Update ' modules / apps / foundation / monitoring / .
updated ChangeLog
Refactored quartz plugin .
setting version to 1 . 0 . 141 - SNAPSHOT
update cacheword to latest head ( notification fixes )
Only clear the caret when in caret selection mode .
ignore Update ' modules / apps / collaboration / ratings / .
Adds device uid for wmme and dsound devices .
Fix check box alignments
ignore Update ' modules / apps / foundation / portal - store / .
make images shorter
Adds smackx - debug to our smacklib to make debugging easier when necessary
Fixing the build .
Upgrade netflixoss Nebula plugin to 3 . 2 . 2
Refactored item_avenger to item_character
Make Tachyon - Perf a subproject of Tachyon
inherit meta from parent dir
Don ' t automatically show the batch buttons when entering multiselect mode
Make text in table wrappable
delete old file
Fix focus issues with dialpad in the call dialog .
LPS - 51081 Move stuff out
Allows use of IPv6 addresses without brackets ( Resolves
Updated readme
Bump SpongeCommon ref
moved wait_for_emulator to android examples
update CHANGES
Also release Android sources to npm
Make gradlew executable on linux
Commented the missing function viewUpdate ( ) and added a navigator . notification . alert ( " Ready " ) ;
Updating Alloy to 65b0e38 ; LPS - 29614
added mcumings to contributor
ignore files
Bump " demo " to 1 . 1
explicitly declaring the Locale of JavaDoc task as en_US
Updated libs .
Updating Tomcat ' s copy of BCEL as far as r1748500 ( more to come )
Added gitignore .
Fix release notes .
Add missing villager sounds .
Updating the script to build with
LPS - 55100 Ignore lib for versions . xml
Add COCOA_TREE to list of possible tree types .
Push build .
bumped version from 0 . 3 - SNAPSHOT to 0 . 4 - SNAPSHOT
upload demo gifs
Bump SpongeCommon ref
updated crate / elasticsearch so the license headers are correct in the upstream
LRQA - 26247 prep next , use latest
Changing the MSI installers banner
ignore Update ' modules / apps / web - experience / export - import / .
Disable Example until new plugins are pushed
add getCount method to BytesInputStream ( @ MysteryMachine )
optimize p . redraw ( )
proofreading EDU
Add isClosed in DruidDataSource
bumped parent version from 2 - SNAPSHOT to 2
ignore Update ' modules / apps / web - experience / trash / .
LPS - 67552 Remove empty file
ignore Update ' modules / apps / web - experience / rss / .
Add appcompat v7 support library .
Add missing LOCAL_MIN_SDK_VERSION for Support Library demos
Removed a System . out
cm changes broke this
Bumped version to 1 . 5 . 0 .
Delete default README
Fixed SAML SSO
Updating Alloy to 65b0e38 ; LPS - 29614
Updated copyright .
Updated changelog .
Use the Cache for ~ / .
update FML for gradle changes
include tests in package - plugin
missing test for KT - 451 incorrect character liternals assertion error
Add sources . jar as part of the build artifacts .
don ' t build consoleio on win64
LPS - 40933 Puts device preview on top of dockbar and other elements
use latest build gradle tools version
updated Studio
Ignore folder that contains h2o . jar in the R package .
updating version to 1 . 0 . 1
Make APNS . java final
Deleted some unused resources
Updated changelog
Added comment .
added new configChang handling for certdisplay
set IDEA JDK from build script
Isolate the manual tests .
LPS - 36595 Do not display Manage Site Membership in Control Panel when the Site membership policy doesn ' t allow manual membership
Add the Servlet 3 . 0 xsd ' s
add scenario name to test stub
ignore Update ' modules / apps / foundation / portal - lock / .
ignore Update ' modules / apps / marketplace / .
add STORM - 790 to changelog
remove repeat annotation
Reset languageMode to languageIn at the beginning of processNewScript ( )
Fixed classpath reference in buildscript dependencies
ignore chat - web 1 . 0 . 2 prep next
Corrected Javadoc on MapReduceOutput
restore forkEvery = 1 . . . still troubleshooting build issues
Invalidate structure when adapter is changed
do not return invalid files
Added a line , just to see if DC manages to monitor changes again and build groovy as it was the case before the move . . .
LPS - 53413 Set 20 plugin groups
update multiwords . txt
Always invalidate TextView on checkForRelayout
Removed unnecessary import .
undo previous trivial change , still testing svn
French tagger now calls dontTagLowercaseWithUppercase ( ) .
Remove fflush from hdr_percentile_print .
updated hbase jar
Prepare version 20 . 1 . 0 .
Removed unused incompilable input file
Use latest release plugin .
replace the openjdk6 to oraclejdk8
ignore Update ' modules / apps / web - experience / staging / .
moved runit to NOPASS .
FredrichO - fixed spacing on the bottom of the number of columns in the media gallery settings layout .
Added nmsblock classes for MCPC 1 . 6 . x .
Reverted build tools version to fix CircleCI
ignore Update ' modules / apps / collaboration / message - boards / .
LPS - 8736 - Allow configuration popup styling to be targeted specifically
Bump version code
Fix leak of stackTrace in java / lang / Throwable .
Fix build .
fixed IDEA build configuration
update sbt 0 . 13 . 11 - > 0 . 13 . 12
Added log and release to cvsignore
Updated sample APK .
cleared cache in travis
Return the record state locked
updating the version number
Create Jar artifact with test code
Ignore IDEA ' s ` .
added id to textview
Updated version before the release
Setting release version to 4 . 0 . 0 .
Increase CircleCI timeout to 30 min
Adding Read icon , updating Dashboard / Reload icons
Publish ` gradle - process - services ` module
Move Benchmark release to 1 . 3
exclude groovy - all - tests jar during assembly
ignore Update ' modules / apps / web - experience / asset / .
Add configuration changes to Notification Settings
Build fix ( take 2 )
update morfologik - stemming to 1 . 5 . 3
upgrade randomized testing to 2 . 0 . 12
Add ` repositories { mavenCentral ( ) } ` to Gradle instructions for completeness
PY - 1065 Reformat and auto - import do not respect space - after - comma preference in multiline imports
add offset
modify mute / unmute buttons and icons
Delete unused strings resource file
Fix doc link for optimize documentation
Updated changelog
ignore Update ' modules / apps / web - experience / asset / .
updated version
Remove trailing line
Modified url for issue tracking to directly show tickets for the component .
ignore Update ' modules / apps / foundation / portal - lock / .
Moving PCA golden test to NOPASS until I figure out the source of the numerical inaccuracies .
Added failing test for JSON output
remove unused files .
LPS - 61001 add image_uploader to build process
add words
The / green command should now only affect dirt on the top layer .
Added translation using Weblate ( Breton )
Fix back popping the back stack too much .
Handle logging levels via log4j . xml
Set LOCAL_MIN_SDK_VERSION .
Updated changelog
prepare release 0 . 17 . 2
update Android - Iconics to v1 . 0 . 1
Add org . sonarqube .
LPS - 37519 hide only control panel link icons
ignore Update ' modules / apps / foundation / users - admin / .
Add ignores for idea and eclipse project settings
add " perflib " from tools - base module to build
moving logo to wiki
Bump version number again
described changes to French Grammar rules in CHANGES . txt
Added Changelog
Add issue template .
ignore Update ' modules / apps / foundation / expando / .
Modify install_fbthrift .
ignore files
Modify Makefile
Fixed a minor typo at the top ( Cloudera CHD3 - > Cloudera CDH3 )
ignore Update ' modules / apps / marketplace / .
Changed a + = of a null string back to the appropriate = sign .
Updated README version
update buildToolsVersion
ignore Update ' modules / apps / web - experience / product - navigation / .
Added junit version .
prepare release HikariCP - 1 . 3 . 5
added few known transitive verbs .
ignore Update ' modules / apps / web - experience / staging / .
Update build branches
Fixed typo
Added missing graph . shutdown ( ) to newly added test case
Add flags needed to switch Jack to 1 . 8 for CTS targets
LPS - 42308 Set visible does not always work in Liferay Pagination
Zeppelin Server doesn ' t catch all exceptions when launching interpreter . sh
update win32 - x86 native
delete old jar
ignore Update ' modules / apps / web - experience / export - import / .
Add screenshots
build linux / i386 against older glibc ( 2 . 3 . 4 ) for compatibility
simplify code
added linux binary
ignore Update ' modules / apps / foundation / portal - cache / .
LPS - 54421 update sdk
added known aliast for monostate pattern
change the default release scope to be patch
Fix mCoveredFadeColor setter
ignore Update ' modules / apps / foundation / portal - store / .
Bump gradle to 2 . 4
ignore Update ' modules / apps / foundation / portal - settings / .
need store refresh status thread to be daemon
LPS - 15720 Add terminated to bad column names list
prepare for next development iteration
Remove sorting on post formats to fix # 284 .
ignore Update ' modules / apps / collaboration / wiki / .
Create README . md
Set isInEditMode ( ) to true # 9
Push version to 14 . 0 . 2 , 11265 .
update applet zip
if null , check version .
remove unused files .
Make every language have its own preview page by default ( no need to specify useSharedPreview ( ) for each )
fixed the busy sound as it was rendering quite poorly with portaudio
Remove ES Client . close ( ) .
Get me out the stupid readme file .
add function with zero arguments
ignore Update ' modules / apps / foundation / web - proxy / .
Ignore list created
Turn debug on for test diagnosis
LPS - 18560 Source formatting missed the break
I had named these with RF instead of matching all the existing * _rf_ * .
update natives
Added files via upload
Added get point method to Line3D . java
Rename file extension
Updated changelog for 0 . 8 . 3
Make gradlew executable on linux
update changelog
Create README . md
fix bug upload demo
Make ViewHolder less visible , static .
ignore Update ' modules / apps / foundation / frontend - taglib / .
remove silly throws decl
CUpdated reference for v83
adding word " LibreOffice "
ignore Update ' modules / apps / web - experience / site / .
added deprecated annotation to deprecated methods .
ignore Update ' modules / apps / foundation / frontend - js / .
Add moon point
LPS - 27654 - Adding Translation in Web Content in Control Panel on IE8 Breaks
ignore Update ' modules / apps / foundation / frontend - js / .
Fix issues with app crash
DO NOT MERGE Take fake bold font property into account .
Make log4j an optional dependency
Adding myself to Travis notifications
setting version to 1 . 0 . 9 - SNAPSHOT
Updated the sample APK
Skip a test that does not apply to JRuby .
push new builder top on texture
Completely reverted change on log4j dependency .
Testing visiblity of a commit message
Add Eclipse files to .
Include message history in stacktraces from error handler , making it easier to know where the problem was .
Fixed TextInput . blur ( )
Added log and release to cvsignore
Added serialVersionUID to MongoInterruptedException
starting 0 . 6 . 1 - SNAPSHOT
Create readme . md
Added reference to distribution .
ignore Update ' modules / apps / foundation / frontend - theme / .
Ignore temp files
Updated travis
avoid fallthrough in ONMOUSEDOWN
Fix AppleBundle # getBuildSteps ( ) so it returns a non - null value .
ignore Update ' modules / apps / foundation / portal - remote / .
Fix BufferedTokenStream . reset ( ) putting the stream in an invalid state when called before lazyInit
Make argument of NullType constructor nullable
Add source encoding to the maven compiler plugin .
ignore Update ' modules / apps / collaboration / item - selector / .
fixed typo in travis . yml
update to latest android gradle build tools 2 . 0 . 0
ignore Update ' modules / apps / web - experience / product - navigation / .
updated version
ignore Update ' modules / apps / foundation / portal - search / .
add function with zero arguments
Disable JS tests when enabling the profile dbTests
Fix missing return value in android_location_GpsLocationProvider_init
Reduce the amount of logging from the Javadoc plugin .
change wl12xx hotspot ssid to spike
ignore Update ' modules / apps / collaboration / message - boards / .
updated CHANGES
Fix nullptr exception .
add incorrect compounds
LPS - 66848 Add missing Gitignore
Have the comparison script handle app failure gracefully
Fixed outdated graddle wrapped from rebase .
Added STORM - 848 to changelog
Remove a spurious symlink
Upgrade netty - build to 11
update to latest android gradle build tools 2 . 0 . 0
Update travis config
set IDEA JDK from build script
Removed un - used p . paused ( ) .
added intellij specific file to .
updating history
ignore Update ' modules / apps / collaboration / blogs / .
Remove newline in TicTacToe example
help ID ( PY - 4110 )
add date
Changed packaging to jar since there are problems with bundle ( classes being in other
Add ' Server ' keyword to title
knock version back to 1 . 6
build script fix
delete test file
Have a bottom actionbar in the Search activity to be consistent .
ignore Update ' modules / apps / web - experience / rss / .
Log type of unexpected quorum packet in observer loop
update sample app
ignore Update ' modules / apps / collaboration / document - library / .
Add Foundation import to the native IntegralToString header .
Fixed accidentely removed call to " java " from bin / robovm .
updated studio
ignore Update ' modules / apps / foundation / contacts / .
Fix changelog by adding a new empty section
Fixing small memory leak when evaluating xpath queries .
Missing key
update linux amd64 natives
Updated gitignore ?
Make notest .
Updated the OrangeExtensins . jar library ( compiled with java 1 . 5 ) .
Removed unnecessary return statement
add codestyle jar file
updated change branch image
Make method private
LPS - 54970 removed unnecessary return
Updated notification icon for Android 2 .
ignore Update ' modules / apps / foundation / frontend - taglib / .
force foreground of execution line to be white
Updated change list
Updating Alloy to 2 . 0 . x c6d25c7
Upgrade Ant to 1 . 9 . 6
Make convertToTranslucent a public method in Activity
Remove unused assignment .
don ' t hardcode IP address for http tunneling
ignore Update ' modules / apps / foundation / portal - store / .
Added Google to license .
Updated README
Downgrade jdk version .
rename jsoup
upgraded http client to 4 . 5 . 2
bump deb version
Make an internal class package private ( cherry - pick to master to unblock all )
Add image for gravity
Added translation using Weblate ( Persian )
LPS - 54434 update jar
remove extra unneeded elements
ignore Update ' modules / apps / collaboration / bookmarks / .
Reverted build tools version to fix CircleCI
Rename migration to avoid timestamp conflict
Fix extra text appearing after ellipsis
Don ' t wrap inline code blocks .
LPS - 54811 Export the proper datasource in order to get the proper transaction management within the new OSGi modules
Set oss parent to 9
Add relative link to contributing file .
Fix indirect misuse of $ ( my - dir ) .
Bump common ref
LPS - 46809 Add a line break since we ' re about to manipulate the var
updated the screenshot
Fix # 205
Removes the TODO to upload the library to bintray / jcenter
ignore Update ' modules / apps / foundation / frontend - editor / .
Removed unused file
ignore Update ' modules / apps / foundation / users - admin / .
increased text size
add sample apk
Added STORM - 1074 to the CHANGELOG .
ignore Update ' modules / apps / foundation / xstream / .
moving RestSpecAndBasicUnitTest to test / unit / voldemort / server / rest
wipe change notes from plugin . xml
Add 0 . 138 release notes
Fixed SAML SSO
Appease the checkstyle overlords .
added helper method for builder implementations
Remove AppState from Known Issues page
Added " elastics " client for javascript
Have RCTBridge . loading return RCTBatchedBridge . loading
cat health api didn ' t disable headers
Fixed Travis
ignore Update ' modules / apps / sync / .
Upgrade jsr305 2 . 0 . 3 to 3 . 0 . 0
Updating Alloy to 612185b ; LPS - 36444
ignore Update ' modules / apps / marketplace / .
ignore Update ' modules / apps / web - experience / staging / .
Updating build tools to 23 . 0 . 1
HHH - 7578 Sybase does not support " unique not null "
Added intellij generated files
Don ' t run performance tests in parallel .
Reduce default stack size for CASSANDRA - 1256
Updating junit version to 4 . 11 - using FixMethodOrder for method ordering
Aligned pom . xml with the other components .
Adds settings icon
Updates the merge calls button .
Eradicate whitelisting
Add case for Decimal128 to BsonBinaryReader # skipValue
Fix isUsbMassStorageConnected ( ) will always return true
ignore Update ' modules / apps / foundation / portal - settings / .
Upgrading the Guava version
updated to tz version 2006d
Added banner file for README . md
Updating Alloy - updated async ajax patch on YUI
Delete README
ignore Update ' modules / apps / web - experience / rss / .
Marking 9 . 3 . 8 as clirr comparison
LPS - 52032 released 1 . 0 . 2 , so prep for 1 . 0 . 3 snapshot
add jcenter to repositories to get actionbarsherlock . aar
Fix double checked locking concurrency issue .
Make argument of NullType constructor nullable
Updated travis
Ignore target directory
Updated changelog
Updating Alloy to f506b55 ; LPS - 17157
LPS - 25788 top links are broken in IE7
update travis to the new build tools
Updated changelog
updated banner to show 0 . 63 - Beta
Add demo gif
setting version to 1 . 0 . 12
ignore Update ' modules / apps / foundation / login / .
Added STORM - 1279 to Changelog
Added STORM - 449 to Changelog
replace Future < T > with T in EJB implementation
bump version
Updating all components to use version 3 of the parent pom .
ignore Update ' modules / apps / collaboration / wiki / .
Added STORM - 1104 to Changelog
added idea ignore config
adding OSSMETADATA for NetflixOSS tracking
updated label to 0 . 81 - beta - 2
Updates build tools and compile version
Fixed a bug where the notifications could overlap when reset
allow testing element icons ( author section removed )
Add DroidSansArmenian font file
ignore Update ' modules / apps / web - experience / staging / .
Added onSequenceStep ( ) ( # 103 )
Add app store screenshots
Bump up revision number .
Changed name for me
ignore Update ' modules / apps / foundation / portal / .
Added screenshot
Only CI build the master branch
Only build the master branch with Travis .
don ' t index unsaved files ( ie , no context )
Ignore IntelliJ IDEA files
ignore Update ' modules / apps / collaboration / message - boards / .
Add ESC mapping for Pixel C keyboard
Cleaning unused files .
update buildnumber - maven - plugin to 1 . 3
add missing test
gets intermittent glm assertion error
reset version for development
added tmp to ignored dirs
ignore Update ' modules / apps / foundation / frontend - js / .
add overlay for cpp subproject
Remove unnecessary code from the test
rename UsersController # delete to destroy # NO_ISSUE
Ignore Sublime Project Files
add image for listview and custom listitem
Don ' t trace debugger internals in Python 3 .
rename unit - tests execution to default - test
ignore * ~ from hg
ignore Update ' modules / apps / foundation / my - account / .
updated animation
remove todo
Set OTR session in ChatView . onBind .
Modify changelog
Fix - Add travis - ci support
Remove semicolon
ignore Update ' modules / apps / sync / .
Bump readme version
Add clover license
Fix copy & paste error in isKeyguardLocked ( )
Upgrade JUnit to 4 . 12
ignore Update ' modules / apps / forms - and - workflow / calendar / .
updated crate / elasticsearch so the license headers are correct in the upstream
ignore Update ' modules / apps / collaboration / bookmarks / .
Removed unneeded ant call in build ( )
set version for release
ignore Update ' modules / apps / web - experience / export - import / .
Removed number to avoid problems
Updated upload document icon
ignore Update ' modules / apps / collaboration / ratings / .
ignore Update ' modules / apps / web - experience / layout / .
Bumping commit of submodule
ignore Update ' modules / apps / collaboration / mentions / .
Remove vim command
Mitigates deadlocks related to synchronization source identifier ( SSRC ) - related information lookup .
add STORM - 1848 to changelog
Fix typo .
Fixed a layout issue with the empty view in list comments
fix the build
add devtools api
ignore Update ' modules / apps / web - experience / asset / .
update com . android . tools . build to 0 . 4 .
Have the final setVisibility cause a requestLayout .
add jamm - 0 . 2 . 5 .
Add battery capacity property
update Bootstrap ' s entry in the NOTICE file
ignore Update ' modules / apps / sync / .
ignore Update ' modules / apps / web - experience / asset / .
Completely reverted change on log4j dependency .
Move Recents task to back when hiding view .
ignore Update ' modules / apps / collaboration / bookmarks / .
setting version to 1 . 0 . 11 - SNAPSHOT
Push version to 235 .
Instruction3rmi should use Format3rmi , not Format3rms
add jamm - 0 . 2 . 5 .
updated codegen dependency
ignore Update ' modules / apps / foundation / portal - security / .
update bundled JRE to 6u39 , refs OF - 612
update build . gradle
update TODO
ignore Update ' modules / apps / collaboration / blogs / .
Add mongodb service for travis config
Remove fixed pipeline technique from lighting shader
add # 3794 to NEWS
ignore Update ' modules / apps / foundation / frontend - css / .
Websockets now need this method .
Increasing uninterrupted sleep quantum in SQLiteDatabase to increase transaction size .
Ignore vim ' s temporary files
add globus
Use new lib
bump version
Speed up Travis by running on non - sudo containers
Speed up consistent hash ring
Moving third - party STUN implementation from Openfire main project to plugin .
Removed a redundant call to setDefaultButton
ignore Update ' modules / apps / foundation / portal - search / .
Added demo gif
Fix trivial equals implementation
Fix JavaDoc .
LPS - 34188 Add missing list close tag in the export layouts form
ignore Update ' modules / apps / sync / .
ignore Update ' modules / apps / web - experience / site / .
ignore Update ' modules / apps / web - experience / portlet - configuration / .
Added " elastics " client for javascript
Updated GBM and GLM booklets on github
ignore Update ' modules / apps / foundation / portal - remote / .
setting version to 1 . 0 . 113
Made CuboidRegion ( world , . . . ) constructor clamp to world .
added constructor that takes the parent class loader
Added files via upload
fixed javadoc for zipalign path getter
HIVE - 2550 Provide jira_base_url for improved arc commit workflow
corrected a typo from @ Maxwell1987
ignore Update ' modules / apps / collaboration / blogs / .
Added STORM - 849 to Changelog
updated studio
Replace registerForEvent ( ) with equivalent call that makes registerForEvent ( ) unused .
Updated changelog
ignore Update ' modules / apps / collaboration / directory / .
ignore Update ' modules / apps / forms - and - workflow / calendar / .
Updated changelog
ignore Update ' modules / apps / marketplace / .
modified a bit of test data
Shrink notification area to contents
ignore Update ' modules / apps / foundation / frontend - theme / .
Added Gradle installation lines
Removed android - support - v4 . jar .
remove overridden function implementation .
ignore Update ' modules / apps / collaboration / blogs / .
Fix Java unmappable character warning on Windows .
added faunus diagram .
added titan + rexster image
updated plan to remove existing functionality
Fix the fix in r1530423
Try a different travis config
Updated changelog
Deprecated com . mongodb . MongoServerSelectionException class
added missing sigar libraries
Updated FAQ
ignore Update ' modules / apps / collaboration / wiki / .
ignore Update ' modules / apps / foundation / portal - remote / .
ignore Update ' modules / apps / forms - and - workflow / calendar / .
LPS - 54165 your changes reminded me of a bug that the SN migration team added
ignore Update ' modules / apps / collaboration / bookmarks / .
Add project default gradle . properties , to avoid build failures from missing properties
fixed the busy sound as it was rendering quite poorly with portaudio
Added description to project
Reactivated the rxjava - core tests
changed versioncode number
Add a a trailing comma .
Log exception if it prevented to start the Git process
removed OBE comment
add STORM - 1848 to changelog
Add image for backstack visualization
Fix a ViewPager bug repopulating after a data set change that removed
fix conflicting native library error message
handle empty preview appearance correctly .
ignore Update ' modules / apps / web - experience / nested - portlets / .
Accessibility events fired from AdapterView underpopulated .
Add missing method
Bump version code
Try and handle " death on startup " a bit cleaner
Added idea output directory to .
LRQA - 24374 Add a new ' portal . release ' property to mark all portal tests to be ran in the release job
Included string . h to use memset in stress . cpp
proofreading EDU
Remove a spurious symlink
FIX application zip should contain a top level dir
Remove redundant fileTree dependency
Delete duplicate application . properties
ignore Update ' modules / apps / foundation / portal / .
Updated Changelog for STORM - 315
Added support for using a transaction to perform batch tasks .
Set mSeekNotificationSent as false for RTSP seeking .
ignore Update ' modules / apps / foundation / map / .
ignore Update ' modules / apps / forms - and - workflow / calendar / .
Reload results immediately after the sort has changed
ignore Update ' modules / apps / foundation / portal - search / .
Updated changelog
Excel import sometimes drops last row of data .
Updated changelog
Added link to contribute page
Prepare for next dev iteration
Remove test I opted to host elsewhere
Added ` Groovy ` solutions for chapter 5
ignore Update ' modules / apps / screens / .
Make gradlew executable on linux
update idea version
Added OC Jelly Bean workaround app as a visible module in the project
ignore Update ' modules / apps / foundation / configuration - admin / .
Fix data driven testing example in documentation
Fix Preview initialization .
remove key lookup for account screen ( not a good place )
Smack 4 . 1 . 3 - SNAPSHOT
Add NEAR QueryOperator
updated version to 3 . 0 . 0 for pending release
optimize png
rename IntelliLang configurable to " Language Injection "
Increased max number of items rendered from 3 to 5 .
Suspend must freeze the time
ignore Update ' modules / apps / foundation / portal - settings / .
Fixed SAML SSO
cm changes broke this
fixed compilation error
add Alireza as contributor
ignore Update ' modules / apps / collaboration / item - selector / .
Removed PMetadata from opengl
ignore Update ' modules / apps / foundation / frontend - taglib / .
adding words suggested by users
Add flow directive to index . android . js
Reverted pom to r2 since our build server can ' t handle r3
add support for chunk setup options in data chunks
ignore build . xml , its generated by .
Fix build
ignore Update ' modules / apps / foundation / portal - instances / .
Updated Changelog for STORM - 315
Added checkstyle to core and cache module
upgraded guava to 14 . 0
Ignore Jetbrains IDEA files in git
Added STORM - 1418 to Changelog
Prepare next version ( 0 . 3 )
reset current scheme panel after import if current scheme was updated
Add build status icon
Added support for using a transaction to perform batch tasks .
ignore Update ' modules / apps / collaboration / flags / .
added few known transitive verbs .
Hopefully fix the build .
Added debug printing content of all incoming packets
Deploying more artifacts .
Download apk file directly from here
include tests in package - plugin
Delete build . gradle
ignore Update ' modules / apps / web - experience / asset / .
Check for APK tamper in HomeActivity . onResume ( ) , fix # 309
Make an internal class package private ( cherry - pick to master to unblock all )
Add image for multipane layout
Upgrade AudioPlayer to v1 . 0 . 8
add directoryMappingChanged ( ) callback
replace non - portable use of echo - n with printf
Fix exception in wrapped documents
Use 0 . 6 of the gradle plugin .
Delete obsolete import
finished collection / list separation
Added security dependency on webapp . mod
Make gradlew executable on linux
Fix missing break in Icon class
Added NOTICE file
Add Clover instrumentation .
fixed a small bug
Updated changelog
Committed new mountains . zip file
Updated version in docs to use 1 . 5 . 0
Remove vim command
Bump readme version
Readded clean goal for coveralls as it seems to be required by the official doc .
Add isClosed in DruidDataSource
update demo
ignore Update ' modules / apps / collaboration / blogs / .
Do not process grammars following an error during parsing ( fixes # 507 )
Allow access to the type " ComponentVillage "
Always call handleException rather than cb
remove freemarker . jar and junit . jar
ignore Update ' modules / apps / foundation / portal - security / .
Recommend jcenter repo .
Fix type warnings
missing import
Fix checkstyle issues
ignore Update ' modules / apps / foundation / expando / .
Removed tag roboguice - 1 . 1 . 1
add spreay dependency to core subproject
add STORM - 1499 to CHANGELOG . md
setting version to 1 . 0 . 9 - SNAPSHOT
update aerosolve version
Added STORM - 1396 to Changelog
Added STORM - 1127 to Changelog
Fixed data type in setStreamVersion
Added the mysql connector jar to .
Updating release version to 0 . 96 in build . properties
Updated changelog
ignore Update ' modules / apps / foundation / login / .
Prevent receiver leak in TrustAgentWrapper
Fix Preview initialization .
update aboutlibraries
added keystore to gitignore
Nexus S now reports the proper frame - rate
Add Mike to the AUTHORS file .
adding android - framework . jar fixes # 34
add badge
updated wiki snapshot
Push version to 12 - beta2 , 210 .
Ignore docs . tar in GIT
Add Eclipse specific project files to ignore .
Add definition file for Travis CI
Removing TimeUnit from api and replace with Duration
renamed class to fix capitalization issue
Added test for
Fixed case of SideBitFlag
pass env ' s CFLAGS through to sub - builds
update screenshot
bump version
Updated changelog
added gradle buildfile to create downloadable artifacts , and push them out to neo4j . org
Fixing the build .
updated changelog
ignore Update ' modules / apps / collaboration / blogs / .
Updated Studio with last version
updating history .
Changed dependencies to milestone versions in preparation of tagging
upgraded guava to 17 . 0
Fix typo in beans { } example
ignore Update ' modules / apps / forms - and - workflow / polls / .
Added Commander / SourceSafe to the list of checked plugins
Update the version to . 96
reduce logging , use ' quiet '
Removed JDK7 and OpenJDK
add wget to yum dependencies
update CHANGES
Set project version to 6 . 1 for release .
ignore Update ' modules / apps / foundation / hello - soy / .
Push version to 12 . 4 , 244 .
Adding maxmemory setting for javadoc generation
ignore Update ' modules / apps / foundation / portal - instances / .
Fixes default config settings .
Updated changelog
Added Travis
Only show warnings and errors from maven - javadoc - plugin
ignore mac finder droppings
Prepare next dev iteration
Updated changelog
debug dor darcula nad retina
Fixed camel - test dependency scope .
Upgrade gradle plugin to 2 . 2 . 0
Rename file extension
Updated unit test for CacheConfig class .
include ' < cxxabi . h > ' ( needed for non - OS X platforms )
Fix test that was not cleaning meta class registry after test
Fixed test for changes to ' model ' report output .
Add comment .
Improved CSS to only add space for breadcrumbs below the * first * title on each page .
prepared for next development iteration
add progress cycle
ignore Update ' modules / apps / foundation / hello - world / .
Remove unused field .
Updating Alloy to 61d4f94 ; LPS - 31537
Remove deprecated constant
Added Eclipse support .
Fix apicheck break .
Fix linux capture preview .
set VERSION . txt
Exclude log4j in kafka dependency as well
Fixed test data
ignore Update ' modules / apps / collaboration / notifications / .
ignore Update ' modules / apps / foundation / portal - lock / .
adding exception
ignore Update ' modules / apps / foundation / roles / .
ignore Update ' modules / apps / web - experience / journal / .
Bumped version to 0 . 35
turn off active by default on tests ( # 1843 )
add changes note about changed launch scripts
update sample app
prepare release swagger - project - 1 . 01
Added Studio with Graph Refactoring
Fix 64 bit long pointer size for media scanning
Add definition file for Travis CI
repackaging guava
Fix indent for unordered lists as well
testing build notify
Push version to 15 . 0 . 6 , 15008 .
prepare release checkstyle - 6 . 11
Fix release notes
Don ' t run the lazybones tests in the joint Groovy build .
add changelog entry for # 1646
Added getter for FloatTextureData . buffer
Fix travis building .
fix build error
ignore Update ' modules / apps / web - experience / export - import / .
Delete build . gradle
Revert " Bumping gradle to hopefully fix buffer overflow on Travis "
Remove warning that should rarely matter
ignore Update ' modules / apps / collaboration / blogs / .
Removed DoubleCheckedLocking from checkstyle . xml .
ignore maven target folder and eclipse project files ( .
Closes completely the master password dialog when finished instead of just hiding it .
remove spurious import
Fix extra text appearing after ellipsis
Remove LOAD_OS_APP message from standard context hub messages
Remove image sample
acknowledge bashisms
updated controller template
LPS - 22149 - This will lockup the browser
LPS - 65920 ( WEB ) Move css files
ignore Update ' modules / apps / collaboration / flags / .
Don ' t include original exception class name in CQL message
Added upload dir to gitignore
ignore Update ' modules / apps / web - experience / site / .
Recommend jcenter repo .
fixed ignore
Fix release notes
ignore Update ' modules / apps / collaboration / flags / .
Fix bug introduced in Change I856118d8 .
accept " screenshot "
Add a default xlarge wallpaper .
Fixed IndexOutOfBoundsException in EpisodesFragment
remove typo
patch the gitignore by hand .
Give a useful error message when the neo4j shell script gets no command
update play version to non - RC
LPS - 66848 Add missing Gitignore
Add missing closing parenthesis in configuration example
Add optional tags to frameworks / base ext .
fixed # 32
ignore Update ' modules / apps / foundation / frontend - css / .
Use the latest version of Android Tools
Fixed SAML SSO
Updated build configuration to version 3 . 2 . 0 - SNAPSHOT
make full message view whitespace - aware so we can do cool ascii - art
Remove executable bit .
ignore Update ' modules / apps / collaboration / blogs / .
Fixed the name of the bintray task in the travis file .
LPS - 26209 Remove the row id when closing the row
removed package statement as we ' ve stuff in groovy .
Use the latest lib snapshot
Add maven central repo to readme
ignore Update ' modules / apps / marketplace / .
Add image of selecting node on tree view
updated version number
ignore Update ' modules / apps / web - experience / journal / .
Updated schema version to 3 . 2
Bump SpongeCommon ref
Excluded a couple of tests from java 9 test suite .
try jdk8 on travis CI with a revised timeout ( 30 mins this time )
git ignore gradle . properties
Updated changelog
Add lib / html / sax / push_parser .
Push version to 14 - beta1 , 11258 .
ignore Update ' modules / apps / collaboration / document - library / .
ignore Update ' modules / apps / foundation / frontend - js / .
Remove unused import .
More missing " public "
Fix the build
Don ' t invalidate the options menu from the message list as we open a
Reinstate view example for screenshot tests
add a disconnect from ANativeWindow
ignore * .
Delete img
Bump SpongeCommon ref .
Updating the script to build with
Have a bottom actionbar in the Search activity to be consistent .
STORM - 751 Move javadoc aggregate to site phase .
DGM . println ( Object ) and friends do a Writer . close ( ) if the object is a writer .
Use the Cache for ~ / .
Add WaveTable symbol to w3c_audio .
Change version back .
updated the CHANGELOG
Added self to Travis notification list
Removed spurious break .
updated ChangeLog
Updating Alloy to f506b55 ; LPS - 17157
change result type to long ( copy & paste error )
ignore Update ' modules / apps / web - experience / rss / .
add xml - psi into core - analysis . jar ( required by java )
ignore Update ' modules / apps / collaboration / image - uploader / .
Make GBM weight test NOPASS again .
Set memory for compiler as otherwise it sometimes fails here
Make SwitchPreference switch more Material
Fix i18n - unsafe API in AaptStep
ignore Update ' modules / apps / web - experience / layout / .
Set activity state correctly when ending activity .
ignore Update ' modules / apps / foundation / portal - security / .
Flow should ignore website .
ignore Update ' modules / apps / collaboration / announcements / .
Revert " disable parallel execution of web tests with coverage "
knock version back to 1 . 6
ignore Update ' modules / apps / collaboration / document - library / .
update equalsverifier to 2 . 1 . 4 ( # 3410 )
Upgraded parent version .
Upgrade Anonymous Usage Statistics to version 1 . 1 . 0
ignore Update ' modules / apps / collaboration / document - library / .
updated version number to 1 . 01
Updated README
Add Screenshot for documenting repo branch in gfx
Fix quotes
ignore Update ' modules / apps / web - experience / layout / .
Fix test resource number .
ignore Update ' modules / apps / collaboration / document - library / .
Add gitignore to github repo .
update readme for new version
Redraw search autocomplete dropdown after config change .
LPS - 25605 Fix jspc
Don ' t show strange exceptions on shutdown ( PY - 5417 ) .
added appveyor build definition
remove check for Java 6 or above before applying bintray . gradle
Add art assets
Fix layout
Ignore api key file
Add quasar - core .
Fix an serializable bug .
Added Studio with Graph Refactoring
LPS - 47753 - Documents and Media Icon view overlaps border and document name
typo , removed sys accidently a couple days back
Revert " Change the scope "
added oupls images for documentation .
update readme
Fixing transitive - ness of provided
remove the final modifier to ensure it will compile again
updating version . txt
update demo
Removed " travis_wait "
Remove unused import
Upgrade JUnit to 4 . 12
Remove old unused test resources
Change the 0_fully signal icon to the new style
ignore Update ' modules / apps / foundation / login / .
ignore Update ' modules / apps / foundation / portal - configuration / .
Upgrade JUnit to 4 . 8 . 2
Remove unreachable code
LPS - 50400 Move AsyncBrokerTest to portal - impl , no change
ignore Update ' modules / apps / collaboration / document - library / .
update linux - x86 natives
add antlr - 3 . 1 . 3 ( should have been in r761805
Bumped minSdkVersion
Forgot to include an import
Added STORM - 848 to changelog
Fix Java unmappable character warning on Windows .
ignore Update ' modules / apps / foundation / portal - template / .
ignore Update ' modules / apps / collaboration / invitation / .
add Asturian
add csiro . au as TLD since is not listed on Mozilla PSL
missing force refresh icon
Fix bug that meant test always hung until the background process count reached zero .
Removed another version from the pom
Set plugin prefix
Add different resolutions for ic_action_watched .
Fix AppleBundle # getBuildSteps ( ) so it returns a non - null value .
Added Christopher Deckers as author
ignore Update ' modules / apps / collaboration / wiki / .
Remove log4j . properties from test - jar .
Ignored SDK directory
Bug 289540 added javadoc into distro
Bump the version
ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fix WTF when creating a lazily initialized connection
upgraded netty to 4 . 0 . 33
Modify Makefile
We don ' t need libopencore_author and libcutils in libmedia_jni
Added gitignore .
Remove useless .
adding junit in preparation from testing
Fix documentation for Method . is_static
ignore Update ' modules / apps / foundation / petra / .
Fix filename typo
Adding constant to PokeGO
Indexer don ' t use the value specified with - m
Add option to export weights and biases to REST API / Flow .
ignore Update ' modules / apps / foundation / portal - configuration / .
Fixed a crash in TelephonyManager while calling getDeviceID ( )
removed unused variable
upgraded netty to 4 . 0 . 6
update aboutlibraries
LPS - 63528 Duplicate util package , unify under service layer
removed empty line .
ignore Update ' modules / apps / web - experience / journal / .
setting version to 1 . 0 . 78
LPS - 46809 Add a line break since we ' re about to manipulate the var
Added local . build . properties to the build so the user can have properties that are not in a file handled by Subversion .
Fix reading sleep policy
Pull oy for release
Missed file during previous commit .
ignore Update ' modules / apps / foundation / web - proxy / .
Remove unused import alluxio . util . OSUtils to pass checkstyle
rename for letter case
eliminate signed / unsigned comparison warning
revert change preventing NULL SSID in a WifiConfiguration
Remove unnecessary initialization
Bump SpongeCommon ref
Revert " use fakeroot "
Remove unknown app module
Added STORM - 1279 to Changelog
ignore Update ' modules / apps / foundation / monitoring / .
ignore Update ' modules / apps / web - experience / asset / .
Adding riak module
include InterruptedException into mock1 . 7
Added back gtest . zip
ignore Update ' modules / apps / collaboration / mentions / .
LPS - 40933 Puts device preview on top of dockbar and other elements
Fixed a bug in bbb - conf
added e - mail address
removing assembly
convert bytes to hex for BytesType . getString ( )
Updated README version
Fix build - remove obsolete import of Animatable
LPS - 65521 Ignore SF for now
Removed " terrain . png "
IDEA - 146469 IDEA with bundled JDK on OS X has incorrect Info . plist settings that prevent dynamic switching between graphics cards
Fix data driven testing example in documentation
ignore Update ' modules / apps / collaboration / image - uploader / .
another test bites the dust
LPS - 62718 add build . xml
ignore Update ' modules / apps / foundation / frontend - theme / .
bump to version 5 . 4 - rc - 2
Fixed wrong android version name in README . md
ignore Update ' modules / apps / foundation / plugins - admin / .
update tests to android - 19
add console appender to quickstart - web
adding rootbeer1_paper . pdf ( HPCC - 2012 conference paper )
prepare for next development iteration
In JSF tag attributes must generally be deferred value expressions , but IDEA does not flag as error immediate evaluation expressions .
Don ' t leak scanners when fetching suggestions from HBase .
set maximum height for mention menu ;
Added STORM - 1476 to CHANGELOG . md
Removed Key Value Server from SVN repository .
add TODO for BIP
ignore Update ' modules / apps / collaboration / ratings / .
remove ugly focus highlight border
Updated the CHANGELOG
ignore Update ' modules / apps / web - experience / trash / .
ignore Update ' modules / apps / forms - and - workflow / calendar / .
ignore Update ' modules / apps / foundation / frontend - js / .
Added missing break in case
Move BeanDeclaration to correct package
Add 1 . 3 apk and qrcode
add logo
set correct version
Update stack diagram image
Ignored all dependency - reduced - pom . xml .
may as well make this by default
Move the wcursor increment after the assert
Hide enum constructor further .
Updated changelog
remove fiel
make project name distinct from src / grails / build .
Fix sourceDirectory , restoring compiled serializers to guava - gwt jar .
Adding top level .
ignore Update ' modules / apps / collaboration / bookmarks / .
Updated comment .
Add lint config
Added STORM - 449 to Changelog
Updated readme
Modifies prefab to reflect new BreatherComponent name
Fix progress dialogs to top of browser window
Prepare next development version .
Added render distance hook
setting version to 1 . 0 . 100 - SNAPSHOT
setting version to 1 . 0 . 98
LPS - 54533 moves icon
Ignore OSX and IDE files
ignore Update ' modules / apps / web - experience / product - navigation / .
Added STORM - 797 to Changelog
ignore Update ' modules / apps / sync / .
Actually close the comment
ignore Update ' modules / apps / foundation / portal - search / .
moved pyunit to large because it uses bigdata
LPS - 19211 Missed build . properties
for IDEA - level ignored folders - keep / show in viewer only folder
ignore Update ' modules / apps / web - experience / layout / .
Remove log4j . properties from test - jar .
add demo gif
Updated README with recent new Extensions .
Remove Gradle wrapper files from .
updated ChangeLog
Removed unnecessary indirect call in NioSocketChannel . isConnected ( )
Added folder for the visualization project .
bump version for move to Apache incubator
change version num and year for the release of libsvm 3 . 15
Forgot to include images in last commit
Updated github page logo
add " retarget " to english
Adding missing Notifications icon
Add intellij files / folder to .
Delete demo . apk
change uploadArchives to uploadPublished for signing condition
ignore Update ' modules / apps / foundation / frontend - js / .
Deploy snapshots of 1 . 1 branch with Travis CI
Updated changelog
Updated version in README .
Removed unused import
Remove webpage after dismissing the view .
Removed stupid typo that I accidentally committed .
ignore Update ' modules / apps / collaboration / blogs / .
update druid console version ( # 3189 )
ignore Update ' modules / apps / collaboration / wiki / .
removed blankline
Added settings to .
fixed wrong import .
updated version
Ignore temporary generated site .
Fix spelling mistake .
Remove fall through for KEYCODE_VOICE_ASSIST
fix mac build issue
LPS - 51912 remove redundant ` continue ` keyword
Remove TBD from fields and properties section
Add checkstyle plugin to lifecycle mapping exception to get things work without warnings on Kepler .
Increment gradle build tools
prepare for next development iteration
add flipviewpager
ignore Update ' modules / apps / collaboration / notifications / .
updated changelog
Making sure that there is no notification when focus changes from something to nothing .
enable unit test on jdk6 and 7 , and use mvn clean package instead of mvn test - B
missing bracket
ignore Update ' modules / apps / web - experience / asset / .
Adds Retrofit library
Breaks the loop
LRQA - 29149 prep next , use latest
ignore Update ' modules / apps / collaboration / announcements / .
fixed IDEA build configuration
update assertj to test scope
Updating Alloy to 65b0e38 ; LPS - 29614
drop jdk6 from build matrix , we require java 7
Make MetricsRegistry # getMetrics ( ) return an unmodifiable map
Setting default name for multi - project
LPS - 62787 Add missing build . xml
ignore Update ' modules / apps / foundation / portal - remote / .
Removed un - used p . paused ( ) .
help topics for VCS configurables ( IDEADEV - 33672 )
Adding top level .
Added support for using a transaction to perform batch tasks .
Fix power provider
ignore Update ' modules / apps / web - experience / layout / .
Add file to images
Call WebView # freeMemory before collecting memory information
Added relative path to the parent POM so that the user won ' t need to
Prepare next release v0 . 88 . 2 - SNAPSHOT
adding gitignore file
prepare release HikariCP - 1 . 3 . 5
Fix license header .
GRAILS - 5691 - remove some code that was accidentally left in the last commit
Updating Alloy to f506b55 ; LPS - 17157
add seaborn to requirements . txt
add gitignore
Use two threads on TravisCI
Use the latest lib snapshot
Added intellij files to .
Update gradle . properties file with a new VERSION_NAME and VERSION_CODE for the next development iteration
remove empty file
Fix generic method signature
build tools 21 . 1 . 2
ignore Update ' modules / apps / web - experience / journal / .
set javadocs to use UTF - 8
remove the unused manifest file
ignore Update ' modules / apps / collaboration / ratings / .
Updated readme
Fix broken test .
upgraded commons - lang 2 . 1
ignore Update ' modules / apps / foundation / portal - security / .
Fix variable visibility issue
Added translation using Weblate ( Uzbek )
Updated changelog
Added diffutils library
Return this instead of null in TimeoutStream # resume
ignore Update ' modules / apps / marketplace / .
To run test
Bump the default max of the connection pool to 8 .
Adds dialog image
Upgrade parent pom version .
reset version for development
ignore Update ' modules / apps / foundation / portal - security / .
Updated gitignore
Updated changelog
Push version to 11 , 206 .
ignore Update ' modules / apps / web - experience / portlet - configuration / .
Fixed a compilation error ( returning from a void method ) .
Upgrade maven version to 1 . 0 . 4
update internal framework to API 19
removed unused texture
Updated changelog
Use both JDK7 and JDK8 in Travis
Missing mavenCentral ( ) repository
ignore Update ' modules / apps / web - experience / site / .
Update expected user guide sample output
Add travis - ci configuration .
Updating Alloy to f506b55 ; LPS - 17157
Remove Java 7 from Travis build .
ignore Update ' modules / apps / collaboration / microblogs / .
Delete PACKAGES . gz
Bumped version to 0 . 8 . 7 - SNAPSHOT .
Prepare version 22 . 0 . 0 - beta3 .
start next dev cycle ( 2 . 0 . 2 - SNAPSHOT )
Add some gitignores
Include ` private - cli ` on npm export
Remove unused import in BufferUtils
Updated usage of the fest - assert - core jar
Add GCMParameterSpec to preloaded - classes
LPS - 19601 No feedback to the user when signing in using Facebook
setting version to 1 . 0 . 151 - SNAPSHOT
Added translation using Weblate ( Kabyle )
removed empty line .
Add an empty README . md to the project
Fix landscape layout of LockScreen on devices with a keyboard
don ' t show misleading help message
Added Fenwick Tree ( Binary Indexed Tree ) to the Readme
setting version to 1 . 0 . 126 - SNAPSHOT
Added Example apk
Remove memory limit due to OOME
Add missing JSON highlighting to example .
ignore Update ' modules / apps / sync / .
added new plugins codes
Fix lint
Add oraclejdk8 to the build matrix for Guava on Travis CI .
prepare for next development iteration
Updated version
Granular navigation uses mContentDescription instead of getCpontentDescription ( ) s
Setting build group and version
Missed required - type - id for a junit
update changelog
updated csproj file
Fix mCoveredFadeColor setter
Avoids automatic boxing and unboxing in the handling of audio levels .
Modifies prefab to reflect new BreatherComponent name
proofreading EDU
add release notes
updated ChangeLog
change pyunit to PASS PUBDEV - 2199
Removed unused method
fixed typo in first line of bbb - conf
ignore Update ' modules / apps / web - experience / site / .
prepare release HdrHistogram - 1 . 0 . 9
Add screenshot
Run the tests in parallel .
add multithreaded example
Added tag 0 . 0 . 7 . 2 for changeset 5de91e5a0e95
Add lint config
don ' t over - validate email address .
Avoid splitting overloaded methods
Added tmp / to .
Remove Y
Normalize line endings
Remove spurious @ Override .
missing icon
ignore Update ' modules / apps / foundation / petra / .
missing return in svg ' s getCoords
ignore Update ' modules / apps / foundation / expando / .
Ignore temporary generated site .
bumped parent - pom - > 7 - rc
ignore Update ' modules / apps / foundation / portal - settings / .
Completely reverted change on log4j dependency .
Set minSdkVersion + targetSdkVersion via build . gradle
Bump SpongeCommon ref
Reformatted and updated POS documentation
ignore Update ' modules / apps / foundation / petra / .
Add support for ALTER TABLE MODIFY in CUBRID
Added volley . jar to the project
Fixed a code typo
ignore Update ' modules / apps / collaboration / wiki / .
LPS - 67839 Create project build . gradle
Changed Target SDK to 21 ( Lollipop )
Remove android - 22 from buildscript
Added STORM - 1476 to CHANGELOG . md
ignore Update ' modules / apps / web - experience / layout / .
Source formatter had trailing blank line
Updated TCK .
Moved log4j . properties to test folder to avoid including it in jar
Speed up Travis by running on non - sudo containers
Added STORM - 1449 to Chagelog
Added makeGLMModel call to python .
Added IPC manager ( support info )
Push API version to 1 . 1 . 0 , enable snapshot .
Restored @ since javadoc tag of Convertible
add close method to EchoedRow
Add maven central repo to readme
remove duplicate image
Add DSLContext . fetchFromCSV ( boolean ) to allow for fetching header - less CSV data
ignore Update ' modules / apps / collaboration / mentions / .
printing all threads stack trace , is making the console out put very large and not giving much info
and update CHANGES . txt for CASSANDRA - 11051
Fix JAR count after adding task - cache - http .
Don ' t run the int tests concurrently at all ( for now ) .
fix the push - tags target
add libs / to gitignore and remove old dependency directories
Enabled fast scrolling for season and episode lists .
ignore Update ' modules / apps / foundation / license - manager / .
make sure Maven prints the complete stacktrace to the command line in case of test failures
IDEA - 117674 please rebuild and commit runnerw . exe
Adding a ' .
remove unused logger
Add missing closing parenthesis in configuration example
Add 9 - inch screenshots
Ignore IDEA project files
ignore Update ' modules / apps / web - experience / site / .
Fixed issue where unread messages wouldn ' t alert properly .
Add Travis - CI support
upgrade the wrappered gradle to 0 . 9 - rc - 3
ignore Update ' modules / apps / web - experience / asset / .
Download apk directly from here
Renaming FrameDebugExtension to FrameCaptureExtension to better reflect usage
Fix ci link
Remove files from obolete and unused figures
ignore Update ' modules / apps / sync / .
Updated changelog
ignore Update ' modules / apps / marketplace / .
Added STORM - 893 to Changelog
tell travis to build free version
Remove javadoc option that fails with java 7
Remove a debug line
Add portlet properties
Updated changelog
removing OSX file
ignore Update ' modules / apps / forms - and - workflow / polls / .
ignore Update ' modules / apps / web - experience / staging / .
Added STORM - 2018 to Changelog
Updated structdb
shut up linter
Updated version
Avoids automatic boxing and unboxing in the handling of audio levels .
ignore Update ' modules / apps / foundation / frontend - js / .
Resized header
increased the default permgen
Only CI build the master branch
ignore Update ' modules / apps / web - experience / asset / .
ignore Update ' modules / apps / foundation / portal - instances / .
Updating Alloy to 61d4f94 ; LPS - 31537
Fixed focus javascript error .
ignore Update ' modules / apps / web - experience / journal / .
Make gradlew executable on linux
LPS - 43918 Add SuppressWarnig
Adding couchbase module
reenable daylight saving test , now that we use joda - time 2
Fixed the camel - scala compile error
Add quasar - core .
Test can take more than 10 minutes , use travis_wait command to allow them take up to 20 minutes .
Prepare library for development
Remove local testing file
ignore Update ' modules / apps / web - experience / portlet - configuration / .
remove TBD from " Optionality " section
Avoid early returns
Fix typo for setting selection drawable
ignore Update ' modules / apps / web - experience / journal / .
add maven support
Fix preloaded classes for the emulator .
ignore Update ' modules / apps / web - experience / staging / .
Remove stray ' - ' after splitting of increment and decrement methods
Add tab localization
ignore Update ' modules / apps / web - experience / staging / .
updated images for checkboxes and pagertabstrip
Updated comment .
remove unused import statement
Simplifying the default welcome presentation
Remove Android examples from release
Added debug level pool statistics logging
add intellij * .
added CDI / Weld to list of support DI containers
Fix osmo login issue
renamed bouncy castle library and upgraded it to rev141 and jdk1 . 5
Disable mocking " promise " in Jest tests
update osx / darwin native
updating readme
Bump version to 3 . 0 . 2
ignore Update ' modules / apps / foundation / portal - instances / .
Fixed formatting of data structure test code
ignore Update ' modules / apps / foundation / portal - remote / .
adding words suggested by users
Actually fix dupe drop
Automatically sign artifacts when releasing .
Fix returning wrong field
temporarily disable 1 . 3 rule for idea_rt
Changed target file name
LPS - 54970 removed unnecessary return
LPS - 10836 remove local address after do local method for Unitcast situation
Added Recognizer . removeErrorListeners ( ) to Recognizer . py
update applet to fix some exceptions
Add CHANGELOG . md
the dist and docs target now work with the github repo
Add adapter for 1 . 10 .
always add snapshot repo as long as we are using Groovy 2 . 0 snapshot
Added WebGLUnsignedByteArray to jslint .
Updating Alloy to f506b55 ; LPS - 17157
Move BikePark * to correct location .
Increment version by Travis CI build 145
Add READ SD CARD permission
Upgrade gradle - plugin
Add maven central repo to readme
Fix test failures for CASSANDRA - 5175
Updated version in README
ignore pom . xml . versionsBackup
setting version to 1 . 0 . 111 - SNAPSHOT
add sbt cached resolution to build "
upgraded slf4j to 1 . 7 . 16
rebuild test instrumenter with target java 1 . 5
ignore Update ' modules / apps / forms - and - workflow / calendar / .
update doc
add empty header placeholder
add irc icon 64x64
Animate movies grid view .
Relax flow jest - cli regex
ignore Update ' modules / apps / foundation / web - proxy / .
Added a gitignore
Push version to 15018 .
tweak readme
Updating Alloy to f506b55 ; LPS - 17157
Adds DestroyRoom class .
ignore Update ' modules / apps / foundation / portal / .
Bump versionCode to 85 .
trying out shippable
Removing openjdk8 from the Travis config as this isn ' t supported
tried new submodule url
updating changelog
initial git ignore file
build number 9
Adds more code on dispatching audio level events .
Remove title , gets set dynamically
Configuration not needed any more .
Adds stream capture and render via CoreAudio for MacOSX .
Added the shutdown command to the service provider
Add getter method for line length field .
Input Whitespace ( is used in many UTs ) now compilable
shiftreduce parser in corenlp requires pos
Add version 2 . 3 . 4 to upgrade from versions
Use less intrusive watched icon .
Fix POM
Updated gitignore
adding word " LibreOffice "
dispatch up event to fix fling
ignore Update ' modules / apps / marketplace / .
Make ViewHolder less visible and static .
prepare for next development iteration
Updated changelog
Updated changelog
add STORM - 1079 to CHANGELOG . md
ignore Update ' modules / apps / collaboration / directory / .
Added tag 0 . 2 for changeset aa491af82d9a
Invalidate ActionMode content rect on scroll .
Add missing travis ci components
disable AMQP by default in graylog2 . conf example # NO_ISSUE
add screenshots
Revert test
ignore Update ' modules / apps / foundation / frontend - js / .
Updates
ignore portal - profile 1 . 0 . 3 prep next
make the common library
improved favicon
build make buildlog include tests run and fail stacktraces
Fixed pom . xml tag
Add lintOptions in build . gradle
remove repeat lefover . . .
add / bin - test - lib to .
added code generation of the use of tuples , lists and maps
Reseting a project . properties file
ignore Update ' modules / apps / foundation / frontend - theme / .
add zuk image
Upgrade asset pipeline to 3 . 2 . 0
Revert " updated dependency "
LPS - 65012 Move export - import - service resources to the correct dir
Git hygiene
Ignore eclipse files
updated screenshot
LPS - 55548 Add property to field type settings definition
update FML for gradle changes
Reverts removal of @ JsonIgnore on Event . type field
Finish removal of pages submodule
Added * jar and out into ignore list .
Add getBytes to InputStream , URL and File ( patch thanks to jeremi Joslin )
change the gitignore
Updated changelog
adding this in so its there for easy building
Removed unused return type in ExecutorServiceProxy .
add help topic ( IDEADEV - 24855 )
Change put command .
ignore classes directory
prepare for next development iteration
update Readme .
fix more apostrophes
Updating Alloy to 65b0e38 ; LPS - 29614
ignore * ~ from hg
Remove another unused method .
Push version to 11250 .
fixed possible problem with closed DB
Fixed MySQL datetime test case
ignore Update ' modules / apps / sync / .
Updated Studio UI
removed wrong doc
Add a LOG_TAG for android . graphics . Graphics JNI .
Remove travis configuration file
Updated changelog
Ignore the local eap repo .
Added logo
fix usages may break code if conflicts were ignored
ignore Update ' modules / apps / foundation / portal - search / .
adding comment about compiler argument
add words suggested by users
ignore Update ' modules / apps / foundation / license - manager / .
ignore Update ' modules / apps / foundation / portal - security / .
Remove old InetAddress DNS cache from preloaded - classes .
Added integration test outputs to .
Updated Slovak translation
add new line at the end of file in the pom . xml
Removed " terrain . png "
added few known transitive verbs .
ignore Update ' modules / apps / foundation / frontend - css / .
Add Spring
update README
ignore Update ' modules / apps / foundation / portal - security / .
Update delve version
changing demo runit statuses
LRQA - 16038 Fix value of property to get correct team name to testray
add * ~ to .
Made names consistent in configuration examples
Built new snapshot
Update to latest getglue - java snapshot , now supports checkin comments .
Fix the glyph for U + 3A34 in DroidSansFallbackFull . ttf .
Set beta_features to True .
skip tests in compiling alluxio for hadoop
Commits the binary for the JNI Speex encoder , decoder and resampler on Mac OS X and thus enables them .
ignore Update ' modules / apps / foundation / frontend - css / .
Updated readme
ignore Update ' modules / apps / collaboration / wiki / .
Add STORM - 1427 to Changelog
update gradle wrapper
Bump pegasus to 1 . 9 . 5
Aligned pom . xml with the other components .
Adds the .
LPS - 69997 Add taglib mapping
add all jdk
update gradle
add h2o_hosts
Fix build after checkThread fix merge to master
Set memory limit for CircleCI
Add maven central repo to readme
add function with zero arguments
remove old screenshots they are not representativ anymore
Display improvements
Bump common ref .
ignore Update ' modules / apps / web - experience / journal / .
fixed android backend . . .
ignore Update ' modules / apps / marketplace / .
ignore Update ' modules / apps / web - experience / asset / .
ignore Update ' modules / apps / web - experience / staging / .
Adding empty script to " pack . sh " GhostDriver ( a reminder . . . )
Upload 1 . 3 . 0 version .
ignore Update ' modules / apps / web - experience / staging / .
Added ignores for Eclipse files
Simplified shell launcher and fixed white space handling
Upgrade retrofit2 to beta4
ignore Update ' modules / apps / collaboration / wiki / .
Set log level to trace for package action . support . broadcast in the RecoveryPercolatorTests # testSinglePercolator_recovery test .
ignore Update ' modules / apps / forms - and - workflow / polls / .
add STORM - 1126 to changelog
Fix uninitialized rect structure for retrieving rect cropping information from decoder
add new hdpi and xxhdpi resources for penandink icon
Adding mavenLocal ( ) for local resolution
include ' < cxxabi . h > ' ( needed for non - OS X platforms )
prepare for next development iteration
Changed background color of external player to transparent
lower gig requirements to 1 , test works fine .
Changed wrong id .
Started work on the ICQ / AIM protocol provider implementation
ignore Update ' modules / apps / web - experience / export - import / .
we could be leaking file descriptors here
LPS - 47461 Add entry - action style
Updating Alloy to 65b0e38 ; LPS - 29614
ignore Update ' modules / apps / foundation / license - manager / .
ignore Update ' modules / apps / foundation / portal / .
make auto focus for all consoles with history
adding lang3 jars
fixed a bug in the - - salt function
Fix # 2739
Added ' metaclass ' to default Python dictionary ( PY - 13357 )
Adds a jitsi - defaults .
ignore Update ' modules / apps / marketplace / .
Added makeGLMModel call to python .
Do not commit target directory
remove PIDFILE at stop time
Tried new gititgnore file
ignore Update ' modules / apps / collaboration / blogs / .
Move the wcursor increment after the assert
added Kasper to list of developers
Upgraded parent version .
ignore Update ' modules / apps / foundation / portal - security / .
ignore Update ' modules / apps / foundation / users - admin / .
Add DSLContext . fetchFromCSV ( boolean ) to allow for fetching header - less CSV data
Removed tag roboguice - 2 . 0 - RC2b
Preparing for release X . Y . Z
add support for chunk setup options in data chunks
emit didFocus after routeStack reset
remove fiel
Added new files to libRSSupport
added rendered version of logo
update linux - arm natives
Fixed a bug
Updated CHANGES
Fix OSGI version
Fix data driven testing example in documentation
Rebuild static openssl libraries from NDK r9c
can ' t access static field from nested closures
Bumped JadConfig to version 0 . 3 , fixes SERVER - 59
Add STORM - 244 to Changelog .
Bump readme version
Remove executable bit .
Don ' t link librt on Mac
LPS - 32257 Removed conflicting nekohtml classes
Updated README version
update travis . yml
Add maven central repo to readme
ignore Update ' modules / apps / foundation / portal - scripting / .
HHH - 9717 - Build script improvements - applied new standalone XJC and AnimalSniffer plugins
Add - lpam when linking pam_google_authenticator module to fix undefined symbol problem
Fixed issue where ChunkPriderEvent . InitNoiseField used the wrong sizeY value .
prepare release 0 . 16 . 0
Create README . md
update version number for doc stamp
Push version to 14 - beta4 , 11261 .
fixed wrong import .
Upgrade Aalto - xml to 1 . 0
Restored upload of distribution
Bump version to 1 . 1 . 0
removed onion routing from readme
rename file so its title has a space in it
Allow the support library to work directly on Gingerbread .
bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6
Take fake bold font property into account .
disable partial nashorn support while merging in recent bug fixes
Upgraded surefire maven plugin to 2 . 6
LPS - 57159 Migrate icon
LPS - 39388 Remove weird comment
Delete obsolete import
ignore Update ' modules / apps / web - experience / export - import / .
Updating Alloy to c3a133e ; LPS - 30635
Add support for interceptorsgd
add style images
Remove unused setter from HttpConfiguration .
Ignore bin and gen
LPS - 67552 Remove empty file
ignore Update ' modules / apps / foundation / portal - template / .
ignore Update ' modules / apps / web - experience / layout / .
Added GIF
Fixed default focused element for credentials dialog opening ( password is focused if username is disabled )
STORM - 751 Move javadoc aggregate to site phase .
Delete fair - scheduler - allocation . xml for YARN - 1300
update com . android . tools . build to 0 . 4 .
run travis ci whit ' gradlew check '
ignore Update ' modules / apps / marketplace / .
added Steve as a contributor
LPS - 50400 Move AsyncBrokerTest to portal - impl , no change
Updated changelog
set IntelliJ IDEA languageLevel to 1 . 6 for Grails 2 . 4 .
Add an " all " target to compile everything and run test cases , pmd , findbugs etc
Fix footer in FireFox
ignore Update ' modules / apps / foundation / server / .
ApplicationStarterBase can process external command line
Travis CI does not provide oraclejdk6
Reverted accidental DataSourceStatus enum change
Remove ' displayName ' prop from ' PickerExample ' component
add grailsCentral ( ) repo to sample application so dependency resolve
Fix typo
include " ruby / util .
Fixed typo in doc
ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fix CircleCI configuration
Overload Methods Declaration Order Check compilable UT input
Modified url for issue tracking to directly show tickets for the component .
update dict
Added the PR number for the snapshot interface in the changelog
update todo
Fixed pom . xml issue with distributed sub - project
build new pre release b4
Bump common and forge build dependency .
fix bug
Remove redundant call to createSdpOffer ( )
Fixes # 167 by replacing the undefined ' mavenUser ' and ' mavenPassword ' with placeholders
updated version
Updated README
ignore Update ' modules / apps / web - experience / site / .
Fix memory leak ( also delete the best model ) .
ignore Update ' modules / apps / web - experience / site - navigation / .
disable uploadArchives for streaming and hadoop 1 . 0
Add back validate into BootstrapModal globals
restore grails . factories file
add function with zero arguments
removed unused annotations from java . g
ignore Update ' modules / apps / web - experience / export - import / .
Saving Blacklist and Hold for Moderation lists when dismissing dialog
Ignore eclipse files
Replace refresh with cluster . health check
fixed BackgroundAttribute bug .
ignore Update ' modules / apps / collaboration / message - boards / .
Bump up assertj version
update gradle version
make note of # 4452 and # 4452
Updated lib .
Delete dangling comment about long - dead code .
Removed android - support - v4 . jar .
LPS - 40679 Fix SF
Remove redundant fileTree dependency
Set VERSION to 5 . 3 . 0 - dev ( via coho )
ignore logs
add STORM - 1008 to CHANGELOG . md
added Richard to the team - welcome aboard !
ignore Update ' modules / apps / collaboration / wiki / .
updating to Gremlin 0 . 8
Upgraded maven - javadoc - plugin from 2 . 7 to 2 . 9
Fix indent
Ignore bin and gen
Added a property to avoid the exception stack trace when running the console
Updated copyright date in LICENSE .
Intellij doesn ' t like trailing newlines ; removed from neo4j . xml .
fixed big refresh image for tablets
LPS - 65225 update hash
Moved AstBrowserProperties from src / main to src / resources .
Prepared version 1 . 8 . 0
Add caching of Maven artifacts to Travis CI build
made the mistake of opening anything in finder
Added STORM - 1204 to Changelog
temporarily disable 1 . 3 rule for idea_rt
make dummy change and assert CC is updating correctly
Added failing test for JSON output
ignore Update ' modules / apps / foundation / frontend - theme / .
update applet jar with changes to minimize connect timeout
Bump common ref for inventory changes .
ignore Update ' modules / apps / foundation / portal - security / .
remove change from another PR to avoid confusion
ignore Update ' modules / apps / foundation / petra / .
Added CNAME for github docs to accept project - voldemort .
try a little more heap memory for tests in Bamboo
Fixed cancel button in landscape account activity
Use new sanitizer option .
CORE - 1506 updateSQL generates invalid SQL for oracle
Bump up revision number .
add new similarity word2vec test
finished collection / list separation
Fix UIExplorer drawer list
Fix a bug in ControllerActivityCounter
ignore Update ' modules / apps / collaboration / document - library / .
Removed leftover name field
Updated changelog
Updated changelog
Remove random "
bumped parent versions from 2 - SNAPSHOT to 2
Ignore IDEA directory
Make gradlew executable on linux
Change Chunk < T > to be a static inner class
Renamed maven assembly to jmxtrans - all . jar .
removed left space from chat view balloon
Bumping the version code again .
use the latest platform - tools on travis
Updated reference to library after adding support to set user agent
ignore Update ' modules / apps / collaboration / bookmarks / .
LRQA - 16067 Add list of product names into test . properties
LPS - 46537 Add plugins SDK
rename " Console Folding " to " Console "
try screen refresh
ignore Update ' modules / apps / sync / .
remove unused property
added id to textview
ignore Update ' modules / apps / foundation / frontend - css / .
Upgrade parent pom version .
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
git ignore eclipse stuff
Add lineDashOffset to externs for CanvasRenderingContext2D .
ignore Update ' modules / apps / collaboration / document - library / .
enable EGL_IMG_context_priority for the omap4 platform
ignore Update ' modules / apps / collaboration / blogs / .
add tags for wakelock and other API names
JETTY - 1308 327109 ( re ) fixed AJP handling of empty packets
Replicate text and sounds settings for managed profile .
Fixed travis build tools version
Updated changelog
ignore Update ' modules / apps / foundation / login / .
Upgrade gecko to 1 . 1 . 3
ignore Update ' modules / apps / collaboration / comment / .
fixed test data for docStub intention
Remove oraclejdk7 from travis .
Updated library reference
ensure key provider returns unique key for each item
Changed id to CLI friendly format .
Updated IntelliJ version
Fix an unintentional change in method signature and avoid an API change .
Ignore reports directory .
update readme
Marking 9 . 3 . 8 as clirr comparison
Simplifying the default welcome presentation
Ignore the gradle - app .
Added a protected method to retrieve the indent printer for reuse in subclasses of MarkupBuilder
Fix translation numbering
Updated changelog
Add missing closing parenthesis in configuration example
Add a Javadoc pointer from DiscreteDomain to DiscreteDomains .
Hide gh - pages
use oracle ' s official jdk
Fixed method layout in ActivityApp
update applet to fix some exceptions
Bump SpongeCommon ref
add Eclipse support
Add @ since comment for method Part . getSubmittedFileName ( ) that was added in Servlet 3 . 1 .
Updated app_konference - 10 . 04 - 32 .
updated CHANGES
Push version to 12 - beta2 , 210 .
Use the Cache for ~ / .
configured functional tests to run with forked jvm per - test , possibly hiding a memory leak problem with tests
adding vvikas
cm changes broke this
add A tag ' s cursor css
add todo
Added STORM - 827 to Changelog
Remove test I opted to host elsewhere
Fixed lost text in notifications for failed uploads
modify docker
Make Option extend HTMLOptionElement instead of Element
Updated Vietnamese translation
Remove redundant constructor .
comment out snapshot plugin for release
use a container and caches
Don ' t appy recording marks twice to audio
Added Studio with Graph Refactoring
Correct a typo
Add scope = test to hsqldb ( fixes # 330 )
added support for GvTags
Fix previous fix .
handle new nack packet in timeline
Remove test for troubleshooting
improve banner
ignore Update ' modules / apps / foundation / frontend - theme / .
ignore Update ' modules / apps / collaboration / blogs / .
Ignore Eclipse files
updated sdk
ignore Update ' modules / apps / web - experience / staging / .
ignore Update ' modules / apps / forms - and - workflow / calendar / .
Fix typo in angular - 1 . 5 externs
ignore Update ' modules / apps / collaboration / document - library / .
Add text editor temporary files to .
ignore Update ' modules / apps / collaboration / microblogs / .
Added support - annotations
Added STORM - 1837 to Changelog
update latin names
Prepare release 3 . 0 . 5
logging stuff 1 .
Prevent random crashes on SGX architecture
add ConnectionState interceptor ,
Fix crash when doing conferencing over Wi - Fi
ignore Update ' modules / apps / forms - and - workflow / calendar / .
LPS - 63528 ( WEB ) Move icon files
Don ' t fetch all indexer errors to get total count
fixing build
Added STORM - 132 to Changelog
remove component ' s events when dealloc is called . "
ignore Update ' modules / apps / web - experience / site / .
update sunos - x86 * natives
Bump common ref .
setting version to 1 . 0 . 118
ignore Update ' modules / apps / foundation / frontend - taglib / .
added few known transitive verbs .
ignore Update ' modules / apps / web - experience / journal / .
add STORM - 1937 to CHANGELOG
Corrected typo in year in license
Don ' t capitalize headings .
ignore Update ' modules / apps / marketplace / .
tries a rescue of my git repository after a network loss
LPS - 65749 prep next , use latest
Push version to 16 - beta4 , 15013 .
Added jme3 - lwjgl3 / build / to the gitignore file . . . .
remove submodule jni / NDKBitmap
Remove a problematic empty update optimization .
ignore Update ' modules / apps / foundation / portal - security / .
use more subtle shade for inline toolbar button text
Add art assets
added mysql - python
Fix descriptor leak after accepting connections
Upgraded maven - compiler - plugin version .
Updated logos with new ones - part of # 630 rebranding
ignore Update ' modules / apps / foundation / frontend - theme / .
LPS - 61440 remove dynamicImport
Removed rogue text from build file .
ignore intellij project / workspace files
Fix changelog by adding a new empty section
Add fast color matrix
Updated EnOcean lib to work with more EEP .
fixed 5 millisecond delay on recompiled .
updated version
Ignore IntelliJ metadata
add sitetools
ignore Update ' modules / apps / static / osgi / .
Fix recent regression in DrawableContainer .
bump socket . io for tests
ignore Update ' modules / apps / web - experience / nested - portlets / .
Updated changelog
Uses a Thread pool for StunClientTransaction in order to improve performance .
Increment gradle build tools
rename example guide
Removed application tag from library , unnecessary
LEP - 5045 Bug - Allow guest to see attached images
Upgrade Apache Commons Collections to v3 . 2 . 2
ignore Update ' modules / apps / web - experience / site / .
Recommend jcenter repo .
updated JettyWebfilterTest . java to JettyWebFilterTest . java
cleanup remove unused file
Ignore IntelliJ IDEA files
Added message .
Add a task that resolves all configurations .
Fixed some help missing links .
Porting fix to allow for a forward / include to call getAttributeNames on the Request in a sandbox
Updating Alloy to f506b55 ; LPS - 17157
ignore Update ' modules / apps / foundation / login / .
update com . android . tools . build to 0 . 4 .
Remove hardcoded version of commons - cli
Updated README
Fix up Settings dependencies when Enabled is off , fix # 208
Add PBAP service start .
Use higher z - index for modal backdrop
ignore Update ' modules / apps / foundation / frontend - editor / .
added changes for 1 . 2 RC3
fixed test data
add STORM - 1646 to CHANGELOG
Include shrink - index .
Bumped version to 1 . 6
LRQA - 12823 - Add test property to use Solr in Poshi
fixed PY - 2608 Test runner does not draw test hierarchy
setting version to 1 . 0 . 103
Remove unnecessary permission from gallery app
update linux - ppc64 native
add context accessor for subclasses
Moving third - party STUN implementation from Openfire main project to plugin .
add analysis - icu module
ignore grails - plugin - domain - class / bin
try diagonal NR shader of same density
Not using any more
add apply eclipse to enable cleanEclipse eclipse targets
Updated changelog
Fix potential segfault in RS watchdog .
upgraded netty to 4 . 0 . 7
ignore Update ' modules / apps / collaboration / ratings / .
Changed CommandLineRunner to public , as I believe that was the intention according to
Adding icon for attic and modified firstfloor icon to exclude the attic .
Updating Alloy to f506b55 ; LPS - 17157
Add a white background layer .
Includes the NOTICE file in the release
update jars
placed the completed ( ) call under the right braces
adding windows builds of new native dlls
updated CHANGES
FIX Dashboard always display a scroll in IE7 ( cherry picked from
Added debug assertions
ignore Update ' modules / apps / foundation / portal - template / .
Suppressed deprecation warning in the group test
Updated changelog
ignore Update ' modules / apps / web - experience / site / .
Remove spurious density - specific default wallpaper .
Prepare next development version .
ignore Update ' modules / apps / foundation / portal - search / .
Refactored quartz plugin .
Added new files to libRSSupport
add STORM - 1674 to changelog
Bump maven lib version to 1 . 0 . 1 .
Removed unnecessary file
Adds a new invite dialog icon .
Added more height to the shadow drawable , so it can be scaled properly to lower dpi screens .
Avoid NPE when trying to do access logging on cookies for an unmapped request .
Smack 4 . 1 . 0 - beta3 - SNAPSHOT
updating gitignore
Remove an unnecessary empty line
Add travis config
reduce staggering in help display
ignore Update ' modules / apps / collaboration / announcements / .
Add CHANGELOG . md
add jdk
remove unused config
Removing Java 6 from the travis build config since 7 + is needed for findbugs 3 . 0 .
GROOVY - 816 - import breaks example
Fix changelog by adding a new empty section
invoke later to show error message
implementing before on node set
add HADOOP - 9417 to CHANGES . txt
removing appinfo . jar
Allow change in whether to shuffle training data after checkpoint restart .
ignore Update ' modules / apps / foundation / portal - store / .
Create menu_nl .
Delete fair - scheduler - allocation . xml for YARN - 1300
Fixing deprecated gradle property
Added Travis
Added Travis
Modify changelog
Added multichat operation set definition and Gibberish protocol implementation .
Fix plugin id name
Added files via upload
removing appinfo . jar
remove old screenshots they are not representativ anymore
setting version to 1 . 0 . 151 - SNAPSHOT
