Updated changelog 
update changelog for STORM - 513 
ignore Update ' modules / apps / foundation / portal / . 
add icon for <UNK> 
LRQA - <UNK> Add test property to test . properties 
add <UNK> <UNK> 
update sample . ts 
update engine version 
Updated linux . tgz 
<UNK> <UNK> <UNK> 
Updated changelog 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / iframe / . 
update readme 
Updated version to 7 . 1 . 1 
<UNK> version to 4 . 0 . 4 
update <UNK> to version 0 . 5 . 0 
fixed test data 
Add logo 
Add antlr4 / antlr4 . 
remove unused import 
Fix <UNK> index 
setting version to 1 . 0 . 133 - SNAPSHOT 
ignore Update ' modules / apps / foundation / roles / . 
remove circle . yml 
Add <UNK> - generator to 1 . 0 . launcher to <UNK> . 
Add a Coffee comment . 
ignore Update ' modules / apps / foundation / petra / . 
LRQA - <UNK> <UNK> type jdk jdk jdk 
update applicationLifeCycles uml 
Add Protocol - Overview . 
Make <UNK> to NOPASS 
fixed <UNK> test 
update gitignore 
ignore Update ' modules / apps / foundation / portal - cache / . 
add index for components to <UNK> 
update changelog 
Remove <UNK> . ttf 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / foundation / contacts / . 
updated version to 1 . 4 
update engine version 
Fix <UNK> <UNK> <UNK> 
Prepare version 18 . 0 . 1 . 
Add Sets release version 
update travis 
removed <UNK> from BigBlueButton BigBlueButton 
update wiki 
Updated <UNK> <UNK> icon . 
Fix <UNK> <UNK> <UNK> 
updated HdrHistogram jar 
Add settings for spring - web - reactive 
add SWIFT_OPTIMIZATION_LEVEL = SWIFT_OPTIMIZATION_LEVEL to ActorSDK 
Fix <UNK> <UNK> <UNK> 
add STORM - 816 to changelog 
update support to latest version 
ignore Update ' modules / apps / collaboration / document - library / . 
Updating up version 
update sonatype - upload - release - release 
add migration for <UNK> 
Updated Readme 
Use <UNK> <UNK> 
Add newbie newbie to PImage height 
<UNK> <UNK> . max_map_count to match . 
Add <UNK> . removeErrorListener ( ) to Recognizer <UNK> 
Fix <UNK> 
add OSGI - INF to build . properties 
setting version to 3 . 0 . 1 - SNAPSHOT 
update library version 
Add CHANGELOG . md 
add <UNK> . gif 
ignore Update ' modules / apps / foundation / contacts / . 
<UNK> <UNK> <UNK> 
update NEWS 
Add Completed Completed to CassandraDaemon service 
update realtime version 
Add new apk 
add mode 
added gitignore 
added proprietary image of proprietary 
update linux - x86 natives 
Add 2b587d24e73f24c049700ffa1f645ccea2a31c93 - 1 . 6 
Fix <UNK> <UNK> <UNK> . 
add STORM - 166 to changelog 
<UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / login / . 
Add inputType inputType to <UNK> 
LPS - <UNK> Remove unnecessary line 
update version to Dev Build 
Fix typo in <UNK> . 
Updated version to 7 . 1 . 3 
update gitignore 
ignore Update ' modules / apps / web - experience / asset / . 
add STORM - 2081 to CHANGELOG 
Fix build 
ignore Update ' modules / apps / web - experience / export - import / . 
<UNK> <UNK> . jnilib <UNK> <UNK> . 
updated editorconfig jar 
Fix process pom 
update maven to version 3 . 1 . 1 
fix <UNK> <UNK> 
update changelog for 2 . 14 . 1 . 
Add gen . xml 
Remove <UNK> <UNK> from ContextObservingClassEventService 
ignore Update ' modules / apps / foundation / portal - scripting / . 
Remove unused <UNK> 
add TODO 
update todo 
<UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
Add travis config 
Bump common ref . 
Add reviewboardrc reviewboardrc 
ignore Update ' modules / apps / web - experience / trash / . 
Add travis . yml 
added libsqlcipher_android so <UNK> <UNK> 
add allowHeavyFilters ( ) to <UNK> 
ignore Update ' modules / apps / foundation / login / . 
update travis to play version 
<UNK> <UNK> . 
Updated auto parent parent version . 
<UNK> - packages script 
update gradle plugin version 
add <UNK> . md 
Add missing test data 
add STORM - 1872 to changelog 
update nexus nexus plugin 
ignore Update ' modules / apps / collaboration / wiki / . 
Added <UNK> <UNK> 
bump to version 1 . 8 . 3 
fix <UNK> <UNK> 
Delete tablet . 
update TODO 
ignore Update ' modules / apps / foundation / portal - search / . 
update libwebp 
LPS - <UNK> Add missing gradle . gradle for <UNK> 
MinecraftForge / FML @ c2b919d339e5f63271cfb67a77235c21c5c3b80e <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
<UNK> <UNK> 
ignore Update ' modules / apps / collaboration / comment / . 
update topology . java ( ) 
LPS - <UNK> Add missing Override 
add CHANGES . txt for 2 . 1 . 15 
Make <UNK> executable 
Modify connect connect 
<UNK> version to 0 . 2 - SNAPSHOT 
updated EditDistanceJoiner jar 
add <UNK> 
ignore Update ' modules / apps / collaboration / message - boards / . 
Setting default name for multi - project 
bump version to 0 . 5 . 5 - SNAPSHOT 
Fix <UNK> <UNK> 
update to latest android 2 . 0 . 4 
ignore Update ' modules / apps / web - experience / layout / . 
<UNK> . gradle 
<UNK> <UNK> . getType . Type to Type isScheduled . SCHEDULED . Type . 
ignore Update ' modules / apps / web - experience / trash / . 
<UNK> <UNK> to " " " <UNK> " 
Fix <UNK> <UNK> 
Updating Alloy to rev . <UNK> 
<UNK> <UNK> 
updated version to 0 . 2 . 2 
Updated CHANGES . 1 
Fix typo 
Travis Travis 
<UNK> <UNK> 
Ignore <UNK> files 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
<UNK> the <UNK> to <UNK> <UNK> . 
changed <UNK> to cobertura 
remove cases 
Updated changelog 
<UNK> <UNK> to <UNK> 
ignore Update ' modules / apps / foundation / portal / . 
Updated changelog 
Delete bolts . jar 
LPS - <UNK> Ignore SF for now 
update Manifest . txt 
Fixed <UNK> <UNK> 
fixed <UNK> <UNK> ( PY - <UNK> ) 
remove deeplearning4j - cli from pom . xml 
Add a @ SideOnly annotation . 
fixed test data 
updated demo 
ignore Update ' modules / apps / web - experience / application - list / . 
Add missing test data 
setting version to 1 . 0 . 62 
Revert " <UNK> to Travis the build . 5 
add mac mac 
<UNK> <UNK> <UNK> <UNK> 
update changelog 
ignore Update ' modules / apps / collaboration / directory / . 
add permission 
added gitignore 
Delete aapt / aapt and aapt <UNK> 
remove unused import 
Fix <UNK> <UNK> <UNK> 
Add 8eac6f6140e16e89a98bf00163dba2cfb414523d 1 . 1 . 1 to . 
ignore Update ' modules / apps / web - experience / journal / . 
add STORM - 548 to changelog 
add STORM - 567 to changelog 
Added STORM - 414 to changelog 
Add <UNK> - 4 . 0 - beta2 . 
Add occasionally AndroidIncompatible to LineBufferTest LineBufferTest 
<UNK> <UNK> . instantiateClass 
add idea files 
ignore Update ' modules / apps / collaboration / wiki / . 
<UNK> <UNK> <UNK> 
<UNK> - wrapper wrapper wrapper 
add missing import 
update gradle - wrapper . jar 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
remove ' include ' from ServerMain . cpp 
Delete jaxen - 1 . 1 . 1 . 
gitignore txt 
bump version to 1 . 2 . 0 
Updated crash 
Add 76f63d1e55a2ef792a27057acc214dcf0d2326b7 0 . 3 
Make <UNK> executable 
<UNK> - <UNK> - run - run <UNK> <UNK> <UNK> <UNK> 
Use the latest snapshot 
update reactor to v1 . 6 . 0 
Added relativePath - pom to the parent build . 
add icon for <UNK> 
Add isVisible isVisible ( ) method to BaseObject3D . 
update android 21 to API version 
update README 
LPS - <UNK> moves icon 
Prepare next release v1 . 91 . 1 - SNAPSHOT 
add words 
<UNK> <UNK> 
<UNK> <UNK> <UNK> 
Add xhdpi launcher icon . 
Fix <UNK> <UNK> 
<UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - css / . 
Updated Readme 
Prepare version 25 - beta1 . 
Fix typo 
fix broken test 
<UNK> <UNK> . reloadGraphs 
ignore Update ' modules / apps / foundation / portal - template / . 
ignore Update ' modules / apps / foundation / portal - search / . 
ignore Update ' modules / apps / collaboration / wiki / . 
ignore Update ' modules / apps / foundation / roles / . 
<UNK> <UNK> 
LPS - <UNK> Remove unused jar 
update readme 
add <UNK> 
Add support for <UNK> 
Revert " Update plugins to . " 
LPS - <UNK> - <UNK> <UNK> <UNK> in ftl ftl . 0 
Fix <UNK> <UNK> <UNK> . 
Added icon to chat icon 
Add missing buffer to Geometry3D <UNK> . 
Fix LOCAL_JNI_SHARED_LIBRARIES tests . 
<UNK> <UNK> <UNK> <UNK> ( <UNK> ) 
update <UNK> to version version 
Fix <UNK> . version of spark spark to include the version of the spark file 
update samples 
Make <UNK> <UNK> <UNK> <UNK> . 
Add missing test 
add png for logo 
<UNK> <UNK> ' s <UNK> 
added jar for commons - io - 1 . 2 . jar 
Add 2009 2009 to PlannedExtensions doc 
Remove <UNK> from <UNK> . 
<UNK> <UNK> ( ) ( IDEADEV - <UNK> ) 
LPS - <UNK> update sdk 
JAL - 35 Add image notes to non - proprietary licenses 
Fix <UNK> <UNK> <UNK> 
Add jira . codehaus . org / browse - - browse browse browse 
ignore blogs - demo 1 . 0 . 1 prep next 
ignore Update ' modules / apps / foundation / users - admin / . 
Remove an blank <UNK> <UNK> 
Add gitignore 
<UNK> the <UNK> <UNK> <UNK> to <UNK> . 
add <UNK> to gitignore 
Remove <UNK> . home 
add <UNK> 
Remove <UNK> <UNK> 
Move test to the test 
Delete MultiDimRay2 . jar 
add favicon 
Fix <UNK> <UNK> <UNK> 
fixed <UNK> <UNK> 
Fix dependency of h2 - boot - actuator - actuator - actuator 
Added missing <UNK> for <UNK> . 
update <UNK> to patch 
Updated changelog 
ignore Update ' modules / apps / marketplace / . 
optimize import 
update gitignore 
Bump up version . 
Updated <UNK> jar 
add STORM - 1191 to changelog 
fixed <UNK> <UNK> ( PY - <UNK> ) 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Add <UNK> to <UNK> 
Updated WinLauncher64 exe 
update changelog 
ignore Update ' modules / apps / collaboration / microblogs / . 
Updated version for release - hbase 
Fix <UNK> <UNK> . 
Fix typo in Contributing - Tachyon - Tachyon - Tachyon - Tachyon . 
Add <UNK> margin 
update 0 . 4 - SNAPSHOT 
Updated <UNK> <UNK> icon . 
Remove sdk - sdk - mac_86 
Updating Alloy to rev . <UNK> 
Push version to 16 - beta2 . 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
update maven - dependency - plugin to 2 . 8 
updated <UNK> icon 
update <UNK> to 21 . <UNK> . 2 
ignore Update ' modules / apps / web - experience / asset / . 
Remove unnecessary line 
Ignore Eclipse files 
Set directoryIncluded / bin to mapping 
add mode 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
add STORM - 1393 to changelog 
update mac natives 
update junit to @ version 
add STORM - 1206 to CHANGELOG 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Move <UNK> to <UNK> . 
ignore Update ' modules / apps / web - experience / staging / . 
Fix <UNK> <UNK> 
Updated LICENSE 
update README 
<UNK> <UNK> 
Remove unused import 
Add xml to the pom . xml 
Remove unnecessary ycsb - binding from pom . xml 
update Gemfile . 
Add DukeChoice lm lm 
<UNK> UltimateAndroidGradle plugin 
LRQA - <UNK> Add new property to testray . properties 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Remove unused files 
<UNK> <UNK> 
update version to 8 . 
<UNK> DBUILD_TESTS git 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Add gh - 50 from changes 
ignore Update ' modules / apps / screens / . 
Updated openpgp to latest openpgp 
Updated runnerw exe 
Add minSdkVersion to AndroidManifest 
add STORM - 1344 to CHANGELOG 
<UNK> alluxio - fuse - fuse . 
update reference to 10 . 2 . 0 
Updated changelog 
LRQA - <UNK> Add new property property to testray shield 
Fix <UNK> <UNK> 
Delete keystore . jks 
add WEB . md 
remove unused - cpd - plugin . 
ignore Update ' modules / apps / foundation / hello - world / . 
Remove 111 portal portal portal ext <UNK> 
LPS - <UNK> add gitignore 
update README 
add <UNK> image 
add gitignore 
add annotations - specific to SomeClassFactory . md 
Add <UNK> to <UNK> 
Add <UNK> to gitignore 
Add isScreenOn <UNK> to LocalPowerManager <UNK> of <UNK> . 
Remove basedir javadoc <UNK> 
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> 
Updated <UNK> to latest <UNK> 
ignore Update ' modules / apps / collaboration / item - selector / . 
LPS - <UNK> <UNK> - <UNK> is not do the UTF properties 
Fix install install install 
update travis 
add STORM - 1464 to changelog 
Add <UNK> <UNK> 
Fixed <UNK> <UNK> 
Add stg stg stg to editorconfig <UNK> 
Fix <UNK> <UNK> 
add css for css 
Added SQLDialect <UNK> to SQLDialect confusion 
<UNK> travis 
LPS - <UNK> Add uuid_ AssetTag to 75 - 6 . 2 . 0 
bump version for storm - hdfs 
Fix <UNK> tests 
Updated <UNK> <UNK> to <UNK> <UNK> . 
ignore Update ' modules / apps / collaboration / wiki / . 
Fix <UNK> <UNK> <UNK> 
update gitignore 
Updated parent version . 
<UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - theme / . 
added <UNK> <UNK> 
update <UNK> to version 3 . 2 . 3 
update gitignore 
add master to travis 
update travis 
update gitignore 
add gen to gitignore 
ignore Update ' modules / apps / screens / . 
Delete 9gag_v1 . 1 . png 
Remove unused file 
Fixed <UNK> <UNK> 
update README 
Add faq task to docs 
Added BCV image 
<UNK> <UNK> <UNK> <UNK> 
add <UNK> . gif 
add icon for <UNK> 
Add <UNK> to the list of the root <UNK> 
add CHANGES . txt 
Add missing billing for billing 
Add cobertura . skip to the pom 
Fix <UNK> ( ) . 
Expose the <UNK> of the BasicBSONObject BasicBSONObject 
Add <UNK> <UNK> <UNK> 
update wiki 
remove extra line 
<UNK> <UNK> in FnMethod 
update toc . textile 
<UNK> to mavenrc mavenrc mavenrc mavenrc sudo 
ignore Update ' modules / apps / foundation / portal / . 
LPS - <UNK> moves icon 
<UNK> <UNK> <UNK> <UNK> 
LPS - <UNK> Add classes to classes with classes 
Make <UNK> executable 
ignore Update ' modules / apps / web - experience / site - navigation / . 
add README . md 
<UNK> <UNK> . testEnums ( ) 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
<UNK> <UNK> . 
Updated README 
<UNK> <UNK> . cpp to TEXTURE_2D target . 
Updated changelog 
Add gh - 46 Fixed 
Remove <UNK> from phrases phrases <UNK> 
LRQA - <UNK> <UNK> log4j . rootLogger to <UNK> the stdout 
add <UNK> . zip 
Updated testng 
ignore Update ' modules / apps / collaboration / document - library / . 
added <UNK> <UNK> <UNK> 
Updates the <UNK> <UNK> <UNK> . 
added <UNK> . png to the icon_IntelliJIDEA 
Add notification notification to travis 
fix test data 
ignore Update ' modules / apps / foundation / frontend - js / . 
ignore Update ' modules / apps / foundation / login / . 
update NOTICE 
Use inject javax . inject . 
ignore Update ' modules / apps / foundation / portal - settings / . 
update gitignore 
Updating Alloy to rev . <UNK> 
<UNK> <UNK> . 
remove unused import 
Ignore DS_Store 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
add demo2 . gif 
Add missing @ test to the test 
<UNK> <UNK> <UNK> <UNK> 
LPS - <UNK> update version 
ignore Update ' modules / apps / marketplace / . 
ignore Update ' modules / apps / foundation / roles / . 
Add missing <UNK> to ZygoteInit <UNK> <UNK> 
ignore Update ' modules / apps / sync / . 
<UNK> <UNK> to 0x00040000 <UNK> 
Move the v11 v11 v11 to the same <UNK> . 
Add test - results to build . xml 
update application . properties to 1 . 2 . 3 
Ignore derby . log 
LPS - <UNK> moves icon 
update applet zip 
Replace image for <UNK> 
ignore Update ' modules / apps / foundation / frontend - js / . 
add jar 
<UNK> <UNK> . 
update release 0 . 56 . rst 
Fix <UNK> <UNK> 
update screenshot 
add STORM - 1253 to CHANGELOG 
ignore Update ' modules / apps / collaboration / message - boards / . 
ignore Update ' modules / apps / collaboration / wiki / . 
update changelog 
update readme 
Add xxhdpi xxhdpi icon 
Remove unused gradle . properties 
Bumping rest - client submodule 
ignore Update ' modules / apps / foundation / frontend - js / . 
update help . help 
update ZeroClipboard 
LPS - <UNK> prep next , use latest 
update javadoc 
<UNK> <UNK> 
<UNK> - logging test logging 
<UNK> <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> . 
Use oraclejdk8 <UNK> <UNK> 
Fixed <UNK> <UNK> 
add STORM - 611 to CHANGELOG 
Add a LabelField LabelField . 
remove unused imports 
<UNK> <UNK> to <UNK> 
update readme 
update gremlin version to 0 . 8 
ignore Update ' modules / apps / web - experience / asset / . 
Bump up version 
ignore Update ' modules / apps / collaboration / blogs / . 
add missing <UNK> to css 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> . makeInvalid ( ) in gui . cpp 
LPS - <UNK> <UNK> <UNK> <UNK> - <UNK> , fixes the <UNK> - xuggler . 
Added platform icon to platform - resources . 
LPS - <UNK> - Missing language key 
ignore Update ' modules / apps / collaboration / notifications / . 
Fix <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
update travis config 
Add <UNK> to formatting 
Prepare next development 
Fix apply plugin for framework 
Built the latest snapshot 
ignore Update ' modules / apps / collaboration / comment / . 
Fix typo 
Fix <UNK> <UNK> <UNK> 
added missing jar 
update android 18 to android - 18 
add bin 
update version to 0 . 4 . 0 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
add ' Erball ' to prohibit . txt 
Fix <UNK> <UNK> <UNK> 
add SuperFinalize 
Updated sample APK . 
update to latest version 
Updated changelog 
Updated Readme 
junit junit junit 
Fix <UNK> <UNK> 
Remove unused <UNK> <UNK> 
update <UNK> to latest version 
<UNK> <UNK> . getType ( ) return <UNK> 
add nb xml for nb 
updated CHANGES 
ignore Update ' modules / apps / collaboration / directory / . 
Use the <UNK> of the travis <UNK> 
update docs 
<UNK> <UNK> to <UNK> 
Fix <UNK> <UNK> 
Fix typo in project . xml 
ignore Update ' modules / apps / foundation / hello - velocity / . 
update pom . xml 
updated ChangeLog 
<UNK> - packages script 
Fix <UNK> <UNK> <UNK> 
Fixed <UNK> <UNK> 
update <UNK> to com . tbruyelle . rxpermissions 
Make <UNK> executable 
Add <UNK> . so for libvudroid - v8a . 
update bbb - conf 
update gradle plugin version 
Updating up version . 
update codenarc script 
Fix <UNK> <UNK> 
Updated <UNK> version 
rmarkdown rmarkdown rmarkdown rmarkdown 
Add webkitVisibilityState for <UNK> <UNK> 
Add rmnet_usb0 rmnet_usb0 to network_interface manager . 
Add ic_github . png 
Remove unused <UNK> 
<UNK> <UNK> to 9042 
Add missing <UNK> to AudioAttributes <UNK> 
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
updated version 
<UNK> <UNK> <UNK> 
Remove unused method 
<UNK> experts itself second 
add grails project to build . gradle 
<UNK> <UNK> to <UNK> 
update Dockerfile 
ignore Update ' modules / apps / collaboration / flags / . 
add <UNK> icon 
add STORM - 757 to changelog 
<UNK> - debug <UNK> 
<UNK> - setup - setup - setup script 
Fix typo 
Updated changelog 
Fix <UNK> <UNK> 
Add cache between cache to travis 
Push version to 12 - beta6 . 
update to latest 0 . 3 
update CHANGES 
update xsoup version 
Fix <UNK> <UNK> 
update v v v v v v v gradlew 
Updated ReleaseNotes 
Updated library reference 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
add TODO 
SONAR - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Remove unused files 
update changelog 
Prepare next development iteration 
update gitignore 
Move ResponseToMetricConverter . java to ResponseToMetricConverter . 
updated ShowHideSideBars 
update openssl 
updated version 
update version to 2 . 0 - BETA 
add mode 
Updated README 
add NOTICE 
ignore Update ' modules / apps / foundation / portal - search / . 
<UNK> <UNK> . 
<UNK> the <UNK> <UNK> . 
update readme 
<UNK> <UNK> <UNK> 
Fix build . 
Fixed <UNK> <UNK> 
<UNK> <UNK> . zip 
update to latest support libraries 
Fix config 
Update doc commit pointer 
updated chunk_vert to reflect <UNK> <UNK> 
HHH - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
update linux - i386 native 
LPS - <UNK> <UNK> <UNK> osgi <UNK> 
Change <UNK> to 22 
Fix <UNK> <UNK> 
Fix <UNK> <UNK> . 
Prepare version 29 - beta2 . 
<UNK> gitignore 
update README 
update gitignore 
update CHANGES . txt for 1 . 9 release 
Add <UNK> <UNK> <UNK> 
<UNK> version 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
<UNK> <UNK> 
<UNK> <UNK> to <UNK> 
add STORM - 468 to changelog 
<UNK> <UNK> . R 
update gitignore 
Use <UNK> to <UNK> 
update Mongolastic asciidoc 
update README . asciidoc 
<UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
LPS - <UNK> Add a new <UNK> <UNK> 
<UNK> <UNK> 
add STORM - 762 to changelog 
Fix <UNK> <UNK> . 
<UNK> <UNK> . kl 
updated ChangeLog 
Remove unnecessary call 
Added toString ( ) method . 
add superscript for <UNK> <UNK> <UNK> 
updated changelog 
Fix <UNK> <UNK> 
Fix <UNK> <UNK> 
Remove unused dependency 
Fix coverage 
LRQA - <UNK> Add new property for <UNK> . acceptance . quarantine to testray . properties 
update travis . yml 
fix failing test 
Updated <UNK> <UNK> to <UNK> <UNK> . 
ignore Update ' modules / apps / collaboration / item - selector / . 
<UNK> the build 
Fix <UNK> <UNK> <UNK> 
update version to 5 . 0 . 2 
update uaparser 
Updating Alloy to rev . <UNK> 
ignore Update ' modules / apps / foundation / frontend - theme / . 
update demo 
<UNK> <UNK> to <UNK> <UNK> . 
Fix LinkProperties <UNK> <UNK> . 
remove unused reference 
ignore Update ' modules / apps / collaboration / wiki / . 
add panda2 3 
Fix <UNK> 
fix <UNK> <UNK> 
add <UNK> . GIF 
set <UNK> to cleanLocalMavenRepos 
Remove <UNK> . mk from <UNK> . 
add <UNK> translation 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / foundation / petra / . 
update changelog 
<UNK> - P travis 
Fix <UNK> <UNK> line . 
add group to the group 
Updating Alloy to rev . <UNK> 
Updated <UNK> 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Updated <UNK> . 
Fix <UNK> <UNK> <UNK> 
update removed 
add README . md 
update travis config 
<UNK> to 4 . 0 . 3 - SNAPSHOT 
update travis 
ignore Update ' modules / apps / web - experience / product - navigation / . 
updated <UNK> 
Remove <UNK> - 0 . 2 . 0 . jar from freeboxos - 0 . 2 . 0 . 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - js / . 
add buildPlugin for <UNK> 
Prepare next development version . 
add mode 
Updating Alloy to rev . <UNK> 
ignore Update ' modules / apps / web - experience / export - import / . 
Remove unnecessary <UNK> 
Updated svnkit jar 
ignore Update ' modules / apps / marketplace / . 
bump to version 3 . 0 - rc - 1 
<UNK> <UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> . 
update buckconfig 
Add missing readme 
update art 
Add Travis config 
Fix crash when <UNK> <UNK> <UNK> <UNK> . 
Updated parent version . 
Remove unused <UNK> . 
Add travis . yml 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
update gitignore 
Fix memory leak in pom . xml 
Fix <UNK> <UNK> <UNK> . 
Fix <UNK> <UNK> <UNK> 
Updated <UNK> jar 
ignore Update ' modules / apps / foundation / portal - configuration / . 
Added setId ( ) method to SugarRecord <UNK> 
Updating parent version . 
update to latest android 0 . 3 . 1 
Bump common ref . 
update wildfire_i18n_en 
update to latest android version 
ignore Update ' modules / apps / web - experience / journal / . 
add max_hint_window_in_ms . txt for add - 1459 
update travis config 
Revert " LPS - <UNK> - Updated test test " 
Add LICENSE for <UNK> 
<UNK> <UNK> <UNK> <UNK> in CompileTask <UNK> . 
<UNK> <UNK> <UNK> 
remove unused TODO 
update javax . xml to 3 . 0 . 1 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
ignore Update ' modules / apps / foundation / portal - security / . 
Remove unused <UNK> <UNK> 
<UNK> the <UNK> of the <UNK> <UNK> <UNK> . 
update coverage 
Updated <UNK> 
update commons - pool2 to 2 . 3 
Add svn <UNK> 
LPS - <UNK> Add missing property 
Fix AppleNativeIntegrationTestUtils test . 
Add version of <UNK> <UNK> <UNK> 
add STORM - 1416 to CHANGELOG 
<UNK> - oj junit core - stubs bouncycastle 
Fix <UNK> test 
update acl . 0 
bump version 
Fix <UNK> <UNK> . 
Fix all <UNK> <UNK> 
LPS - <UNK> Remove unused jar 
Add <UNK> Kingsbury 
Built the latest snapshot 
Bump up version . 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / petra / . 
Fix config 
ignore Update ' modules / apps / foundation / portal - cache / . 
Prepare version 1 . 0 . 9 - SNAPSHOT 
Remove import 
Add <UNK> . png to xhdpi . 
Add image for cherries cherries 
updated bbb_banner bbb_banner image 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - js / . 
Fixes the <UNK> of the MetaContactListSource of the MetaContactListSource <UNK> , <UNK> , <UNK> , <UNK> , <UNK> , <UNK> , <UNK> , <UNK> , <UNK> , <UNK> , <UNK> . 
add STORM - 1395 to changelog 
<UNK> <UNK> <UNK> jar 
ignore Update ' modules / apps / web - experience / site / . 
ignore Update ' modules / apps / web - experience / site / . 
Add screenshots 
add groovy - ant dependency to groovy - ant 
Updated changelog 
add words for <UNK> 
<UNK> background background 
Add <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / web - proxy / . 
add README . md 
Remove unnecessary file 
fixed typo 
Updated version number 
tachyon_version tachyon_version for <UNK> 
update README 
Remove unused method 
update <UNK> to 1 . 3 . 1 
add <UNK> 
ignore Update ' modules / apps / collaboration / message - boards / . 
Add <UNK> <UNK> 
update gitignore 
Delete gradle - wrapper . 
<UNK> <UNK> 
Updating netty to 4 . 0 . 23 
Add <UNK> . npm 
LPS - <UNK> Fix <UNK> 
update to latest 1 . 8 . 0 - beta - 1 
ignore Update ' modules / apps / foundation / frontend - theme / . 
add <UNK> to <UNK> 
<UNK> <UNK> . 
LPS - <UNK> Remove unused file 
Fixed typo 
ignore Update ' modules / apps / collaboration / bookmarks / . 
update release - release - plugin to 1 . 2 . 0 
updated ChangeLog 
<UNK> the <UNK> of the <UNK> <UNK> <UNK> . 
update version 
Updated keystore 
Remove unused file 
Updated sample image . 
Remove @ SystemApi link from PhoneAccount PhoneAccount . 
ignore Update ' modules / apps / web - experience / asset / . 
add <UNK> 
Make <UNK> executable 
Remove <UNK> . 
ignore calevent - importer 1 . 0 . 4 prep next 
add \ files 
<UNK> <UNK> . kl 
update win32 natives 
update android jar 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
add jdk8 to travis 
Remove unused test 
fixed <UNK> <UNK> 
update sunos natives 
Fix <UNK> - class - docs . 
setting version to 1 . 0 . 105 
Add jar for junit 
update itext jar 
Add import to Restore de . 
ignore Update ' modules / apps / foundation / portal - scripting / . 
updated <UNK> icon 
fixed test data 
Fix <UNK> selector 
Fix <UNK> 
Updated CHANGES 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
LRQA - <UNK> Add a new component to the test 
SimplePool SimplePool 1000 <UNK> in SimplePool <UNK> 
Make <UNK> executable 
add test 
ignore Update ' modules / apps / collaboration / directory / . 
ignore Update ' modules / apps / foundation / petra / . 
<UNK> the <UNK> of the refine svn <UNK> . 
ignore Update ' modules / apps / collaboration / wiki / . 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
<UNK> plugin to JAVA JAVA - Des . path . 
Updated joscar jar to latest version 
Set <UNK> to - - <UNK> 
removed roles from advanced recipe 
Updating Alloy to rev . <UNK> 
Updated parent version . 
<UNK> <UNK> <UNK> <UNK> . 
<UNK> <UNK> <UNK> <UNK> 
add STORM - 1590 to changelog 
Smack 4 . 0 . 5 - SNAPSHOT 
Bump up version 
Updating Alloy to rev . <UNK> 
Remove @ Override from MySiteFragment MySiteFragment 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - css / . 
Fix typo in pom . xml 
Fix <UNK> 
Fix <UNK> 
add STORM - 1835 to changelog 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / marketplace / . 
Fix <UNK> <UNK> 
<UNK> <UNK> 
updated upload_files . cm 
Remove comment 
Delete IMG00001 . GIF 
<UNK> <UNK> to <UNK> <UNK> . 
add <UNK> 
update orientdb - etl to 2 . 1 . 0 
<UNK> <UNK> <UNK> 
update bytebuffer - collections to 0 . 2 . 1 
Updated <UNK> 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / bookmarks / . 
Updated version 
Fix typo 
<UNK> <UNK> <UNK> <UNK> . 
ignore Update ' modules / apps / foundation / server / . 
Re <UNK> - based travis 
<UNK> <UNK> . process ( ) 
bumped version to 1 . 0c 
Remove application application android application from AndroidManifest . xml 
update DrawHelper . java 
Bump common ref . 
ignore Update ' modules / apps / web - experience / layout / . 
test <UNK> 
Bumping rest - client submodule 
Fix <UNK> <UNK> . 
ignore Update ' modules / apps / collaboration / message - boards / . 
update README 
ignore Update ' modules / apps / foundation / frontend - css / . 
<UNK> Makefile 
bump pegasus to 1 . 8 . 2 
Fix <UNK> <UNK> 
Make outputStreamOutputBuffer <UNK> 
update <UNK> 
add README . md 
<UNK> <UNK> 
<UNK> <UNK> 
Fix toLowerCase splits <UNK> in processing . 
update to latest android 0 . 1 . 1 
add ic_list_library_calibre icon 
Add missing check_deskshare check_deskshare for config 
Remove <UNK> - classes 
add arsenal . md 
fixed broken <UNK> <UNK> ( PY - <UNK> ) 
Set manager manager manager to true 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / journal / . 
Remove versionNameSuffix versionNameSuffix beta beta 
ignore Update ' modules / apps / web - experience / asset / . 
Add <UNK> - armv6hf . 8 to libjSSC - armv6hf - armv6hf . 
Add back 1 . 5 
Add screenshot 
updated librobovm llvm 
<UNK> <UNK> <UNK> 
add mode 
Updated Readme 
Add image for preference <UNK> 
made mySelected protected 
updated to latest 2 . 0 . 1 - final 
<UNK> the version of the version 
Fix typo 
Remove mms - common - <UNK> 
update gitignore 
add joinAlarm to joinAlarm <UNK> 
Fixed typo 
bump pegasus to 6 . 0 . 14 
Fix jar error 
Modify submodules 
updated README 
Remove <UNK> 
Fix <UNK> <UNK> . 
<UNK> the <UNK> 
ignore Update ' modules / apps / foundation / hello - soy / . 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
update buildToolsVersion to 22 . 0 . 1 
ignore Update ' modules / apps / collaboration / message - boards / . 
ignore Update ' modules / apps / web - experience / layout / . 
LPS - <UNK> <UNK> <UNK> <UNK> 
update README . markdown 
updated <UNK> 
Remove build . dependsOn webpack from zipkin - ui 
Bumping rest - client submodule 
ignore Update ' modules / apps / foundation / portal / . 
Remove unnecessary <UNK> 
ignore Update ' modules / apps / foundation / portal - settings / . 
update readme 
Add <UNK> <UNK> libraries 
ignore Update ' modules / apps / web - experience / export - import / . 
update native natives 
LPS - <UNK> update sdk 
update encog - core to 3 . 2 . 0 
Fix <UNK> <UNK> 
Updated version for release - hbase 
ignore Update ' modules / apps / foundation / expando / . 
Push version to 13 - beta2 , 242 - 242 . 
GenericXmlBikeRentalDataSource Missing <UNK> <UNK> 
<UNK> <UNK> 
ignore Update ' modules / apps / web - experience / product - navigation / . 
<UNK> icon 
Updated <UNK> <UNK> to <UNK> <UNK> . 
Fix <UNK> <UNK> 
<UNK> <UNK> . onDestroy ( ) in MainService 
Fix <UNK> <UNK> 
add README 
add <UNK> to the 20 
Fix thrift repositories 
Updated favicon 
add STORM - 1478 to changelog 
<UNK> <UNK> 
<UNK> <UNK> to 0 . <UNK> 
<UNK> <UNK> . 
help topic ( IDEADEV - <UNK> ) 
update changelog 
update LICENSE 
<UNK> <UNK> 
Updated changelog 
Fixed test 
LPS - <UNK> moves icon 
Add files via upload 
add STORM - 412 to CHANGELOG 
made <UNK> ' s <UNK> 
add STORM - 1481 to changelog 
ignore Update ' modules / apps / web - experience / journal / . 
revised <UNK> icon 
SONAR - <UNK> <UNK> - viewer line line of code for code 
update header gif 
<UNK> Makefile 
Fix XMLHttpRequestBase <UNK> <UNK> 
<UNK> <UNK> <UNK> 
Updated <UNK> <UNK> asset . 
Fix build 
Fix <UNK> <UNK> 
Add <UNK> <UNK> 
update test . xml 
Remove unused double double double 
update Process 
update HazelcastStabilizer 
ignore Update ' modules / apps / foundation / portal - security / . 
Updating Alloy to rev . <UNK> 
update gitignore 
ignore portal - profile 1 . 0 . 0 prep next 
add <UNK> to the build . 
<UNK> proguard 
Fix broken create <UNK> 
update proguardVersion to 5 . 1 
Add <UNK> notification 
Make <UNK> executable 
bump version to 0 . 6 . 1 
ignore Update ' modules / apps / foundation / portal - configuration / . 
Add <UNK> to InAppPurchaseManager <UNK> 
LPS - <UNK> Add getUserId ( ) to UserScreenNameException <UNK> 
setting version to 1 . 0 . 89 - SNAPSHOT 
<UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
Add <UNK> <UNK> to <UNK> . 
fixed <UNK> <UNK> 
LPS - <UNK> - Remove alloy alloy - 0 . 1a . zip 
add * . 
<UNK> test 
add License . md 
Added 2fb52c5eaa097f1d9ee5bf13a45feb3f7779f9ed - 2 . 0 - ignoreme6 0000000000000000000000000000000000000000 
added test to TODO 
update plexus - component - metadata to 1 . 6 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> 
Remove unused Disposer 
update app version 
Bump versions to 1 . 2 . M02 . 
Add <UNK> mapreduce jar 
add learnMore image 
Add missing <UNK> . h to DrmSupportInfo DrmSupportInfo of DrmSupportInfo . h 
<UNK> <UNK> 
ignore Update ' modules / apps / collaboration / directory / . 
update settings 
Add Example ( ) to Example . asciidoc 
added missing jar 
MinecraftForge / FML @ 852710962a9b6d7c8e2ca188c715eebb2da44c2a <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
update to latest android 0 . 1 . 2 
fix a typo in OngoingStubbing . java 
<UNK> <UNK> <UNK> <UNK> 
LPS - <UNK> Add @ Override 
<UNK> <UNK> . 
update windows natives 
Fix <UNK> <UNK> <UNK> 
Add oraclejdk8 oraclejdk8 for travis 
refs 
ignore Update ' modules / apps / web - experience / site / . 
Updated structdb 
ignore Update ' modules / apps / web - experience / product - navigation / . 
ignore Update ' modules / apps / foundation / portal - configuration / . 
Push version to 11247 . 
<UNK> <UNK> to be test 
updated CHANGES . txt for release 
Remove unused image . 
add * . 
update pom 
Updated gradle wrapper to version 2 . 7 
<UNK> <UNK> to <UNK> 
add circle . yml 
Add <UNK> . 
add liquibase - core liquibase 
Add categorical_encoding <UNK> to DeepWaterV3 <UNK> . 
Updated version for curator - x - bridge . 
ignore Update ' modules / apps / foundation / hello - soy / . 
Bump common ref . 
Fix typo 
add css for 10px sans - serif 
Add screenshots 
Add missing <UNK> to positionLimit <UNK> . 
<UNK> reference of <UNK> 
ignore Update ' modules / apps / web - experience / journal / . 
<UNK> license 
Add missing @ Override annotation 
update support - v4 to fix <UNK> <UNK> 
LPS - <UNK> update sdk 
Fix <UNK> <UNK> <UNK> . 
Fix <UNK> <UNK> <UNK> 
update demo 
setting version to 1 . 0 . 115 - SNAPSHOT 
add NOTICE . txt to release release 
<UNK> gitignore 
Move ModelParameterSchema ModelParameterSchema ModelParameterSchemaV2 to h2o 
Updated version to 6 . 16 . 2 - SNAPSHOT 
Use jsp - api - jsp 
Add notificationq analytics property for killbill - server . 
Add / bin / bin to gitignore 
Add missing import . 
Updated library reference 
Push build . yml 
add index for <UNK> . 
Fixed typo 
update txtfilereader . md 
Updated CHANGELOG 
<UNK> <UNK> <UNK> 
update app version 
added h2o - sources . 
ignore Update ' modules / apps / screens / . 
Bump up version . 
<UNK> <UNK> . start ( ) 
<UNK> <UNK> . setTitleBarGravity ( ) . 
update gitignore 
<UNK> version to 0 . 2 . 0 
Prepare next release v1 . 87 . 4 - SNAPSHOT 
add pom . xml 
update buildToolsVersion to latest version 
Fix <UNK> <UNK> 
Fix typo 
Updated junit 4 . 5 . jar with <UNK> <UNK> . 
Fix <UNK> <UNK> . 
add local . properties 
Added Base class to ActionResponse requests for ActionResponse requests . 
Updated <UNK> to <UNK> <UNK> <UNK> 
updated splash 
LPS - <UNK> prep next , use latest 
add a TODO 
update README 
Updated version for release - hbase 
update version to 0 . 8 . 9 
LPS - <UNK> Remove <UNK> <UNK> 
added ISchemableSpout interface for <UNK> . 
fixed <UNK> <UNK> 
update Reflections version 
ignore Update ' modules / apps / web - experience / layout / . 
Fix ldaptive - unboundid - support dependency 
Updated README 
Fix typo 
Fix <UNK> <UNK> asset . 
<UNK> <UNK> . 
LPS - <UNK> update sdk 
Add <UNK> to <UNK> 
ignore Update ' modules / apps / collaboration / flags / . 
Add Xmx512m - Xmx512m - Xmx512m dependency for <UNK> . 
Fix test 
<UNK> <UNK> <UNK> 
Add <UNK> . neo4j . jmx . 
Bump version number 
ignore Update ' modules / apps / collaboration / wiki / . 
ignore Update ' modules / apps / foundation / login / . 
<UNK> <UNK> 
update version 
Added getAssociatedObject ( ) method to BaseAdapterHelper <UNK> . 
<UNK> <UNK> . 
ignore Update ' modules / apps / foundation / contacts / . 
ignore Update ' modules / apps / collaboration / image - uploader / . 
update location module 
Fix <UNK> <UNK> <UNK> 
Add y - y to travis 
update minSdkVersion to 8 
Added Logo Logo Logo 
ignore Update ' modules / apps / collaboration / announcements / . 
ignore Update ' modules / apps / foundation / portal / . 
ignore Update ' modules / apps / sync / . 
add jcenter ( ) to build . gradle 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / foundation / portal - security / . 
Add serialization Used serialization 
ignore Update ' modules / apps / web - experience / asset / . 
Fix <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Added relative - pom to the parent build . 
Updated CHANGES 
add <UNK> 
bump to next dev iteration 
Updated changelog 
add <UNK> <UNK> pdf 
update gitignore 
ignore Update ' modules / apps / collaboration / blogs / . 
Updated <UNK> 
update gdx jar 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / wiki / . 
Add missing hive_logo . 
ignore Update ' modules / apps / web - experience / staging / . 
Add link for <UNK> 
update NEWS 
Revert " Add screenshot to gitignore " 
Add Tom Morris to README 
add format 
LPS - <UNK> Add missing @ Transactional 
Move <UNK> to GCloudSessionDataStore - gcloud - manager . 
ignore Update ' modules / apps / foundation / portal - search / . 
ignore Update ' modules / apps / web - experience / application - list / . 
add txt for <UNK> 
ignore Update ' modules / apps / web - experience / iframe / . 
Updated ExecutionMemberSelector index 
Remove unused call 
Fix NPE in JavaWriter JavaWriter 
update <UNK> to version 0 . 3 . 10 
Remove <UNK> from control 
updated page_white_get page_white_get icon 
<UNK> <UNK> <UNK> <UNK> 
init PACKAGE @ init - init for debian - init 
ignore Update ' modules / apps / collaboration / image - uploader / . 
Remove import 
remove administrator README 
Updated changelog 
ignore Update ' modules / apps / web - experience / asset / . 
<UNK> version 
Ignore <UNK> 
<UNK> dependencies 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / nested - portlets / . 
add changelog 
Fix <UNK> <UNK> <UNK> 
<UNK> user user to ArtifactoryUser user 
<UNK> <UNK> . url ( ) in Request ( ) 
update changelog 
Remove unused <UNK> 
ignore Update ' modules / apps / collaboration / bookmarks / . 
<UNK> <UNK> to <UNK> <UNK> . 
Add SortedHashMapTest . java to pom . xml 
<UNK> <UNK> . 
Fix typo 
setting version to 1 . 0 . 154 - SNAPSHOT 
update dnsjava to 2 . 1 . 6 
Updated README 
update 
add README 
<UNK> classid <UNK> 
add README 
Fix <UNK> <UNK> . 
update project . properties to <UNK> 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
add OS X stuff to . 
ignore Update ' modules / apps / collaboration / item - selector / . 
<UNK> jps <UNK> 
update changelog for STORM - 461 
add todo 
Fix <UNK> right right 
Remove unused import 
update engine version 
add moment - timezone - bootstrap 
Updated changelog 
<UNK> <UNK> <UNK> 
Remove the stop <UNK> - stop - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Updated screenshots 
ignore Update ' modules / apps / foundation / users - admin / . 
Revert " Revert " Updated " to the latest library " 
Fix <UNK> <UNK> . 
add user - transaction module 
LPS - <UNK> moves icon 
LPS - <UNK> <UNK> <UNK> . properties ( ) 
add <UNK> image of 2x 
<UNK> the <UNK> <UNK> in EditPost . 
help topic ( PY - <UNK> ) 
updated <UNK> images . 
updated ChangeLog 
<UNK> <UNK> <UNK> in MessageListFragment <UNK> 
update location module 
LPS - <UNK> prep next , use latest 
<UNK> , <UNK> <UNK> 
Fix <UNK> <UNK> . 
Bump version to 1 . 1 . 0 - SNAPSHOT . 
<UNK> <UNK> 
Remove unnecessary line 
Add tests for <UNK> 
ignore Update ' modules / apps / collaboration / microblogs / . 
Remove resolution 
Identity Identity Identity CombinedTransform in Identity Identity 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
updated Warning image 
Add <UNK> to <UNK> 
Prepare version 23 - beta4 . 
bump version to 1 . 0 . 1 
update gradle to version 2 . 1 . 2 
update deny . txt 
Updated <UNK> <UNK> to <UNK> <UNK> . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Remove <UNK> . 
Updated <UNK> libs 
Add <UNK> . 
update sample sample 
Add osgi plugin to osgi - javanica 
Updating Alloy to <UNK> ; LPS - <UNK> 
updated <UNK> icon 
update readme version 
Add <UNK> operation <UNK> ( <UNK> ) 
ignore Update ' modules / apps / foundation / server / . 
Add demo gif 
ignore Update ' modules / apps / web - experience / iframe / . 
Add unbind ( ) to GLib <UNK> 
added <UNK> event 
<UNK> javadoc 
update gradle to version 0 . 8 . 
Move ipython_dataprep_output_fixed python txt to python . txt 
Fix newline for test . 
add VERSION_1_7 VERSION_1_7 sourceCompatibility sourceCompatibility <UNK> 
<UNK> <UNK> 
Push version to 15 . 0 . 4 . 
set back 8 
ignore Update ' modules / apps / web - experience / asset / . 
add locales . enabled to hook_6_2_0 hook_6_2_0 
ignore Update ' modules / apps / collaboration / flags / . 
Fix <UNK> <UNK> 
Fix dependency 
update README 
Updated changelog 
made getPreviousBlock protected 
Add travis config 
LPS - <UNK> Ignore SF for now 
LPS - <UNK> rebuild jgroups . jar to jgroups jgroups <UNK> 
LPS - <UNK> update jar 
ignore Update ' modules / apps / web - experience / journal / . 
add STORM - 764 to changelog 
Updated <UNK> <UNK> to <UNK> 
ignore Update ' modules / apps / foundation / portal - settings / . 
update CHANGES . txt 
<UNK> <UNK> - graphs fieldGraphs fieldGraphs fieldGraphs . valueSeq ( ) 
Replace image for practice_3_sample practice <UNK> 
set ANDROID_BUILD_MIN_SDK_VERSION to 9 
update maven to 2 . 2 . 1 
Fix <UNK> <UNK> <UNK> 
<UNK> runtime junit 
Updated changelog 
Updated structdb 
Fix test 
update test 
update wordpresslibraries wordpresslibraries to 1 . 1 . 1 
add . markdown to <UNK> 
Fix RCTModuleData <UNK> <UNK> 
bump version to 1 . 3 . 0 - alpha . 
Fix typo 
LPS - <UNK> Move js js files 
update ActorSerializer ActorSerializer to version ActorSerializer 
Add placeholder for <UNK> 
<UNK> <UNK> 
Updated <UNK> 
LPS - <UNK> moves icon 
ignore Update ' modules / apps / foundation / contacts / . 
update README . md 
added validation module 
Updated jediterm - pty - 2 . 0 . jar to jediterm jediterm <UNK> of <UNK> . 
add unanimously to <UNK> 
<UNK> needs more tests . 
Fix <UNK> 
ignore Update ' modules / apps / foundation / portal / . 
Make the <UNK> of the Iterator Iterator . 
LRQA - <UNK> prep next , use latest 
Delete pickerdemo . gif 
<UNK> <UNK> system system system 
update maven - dependency - plugin to 2 . 10 
Make mSceneInitialized protected for RajawaliRenderer <UNK> 
<UNK> <UNK> <UNK> 
Fix <UNK> 
Fix <UNK> <UNK> 
Built the latest snapshot 
Remove redundant prerequisites prerequisites 
update readme 
Fix test 
Fix typo in pom . xml 
updated todo 
update tachyon . xml 
Remove unused <UNK> 
<UNK> <UNK> to <UNK> 
<UNK> <UNK> <UNK> 
update android . jar 
update maps version 
Make the <UNK> of the <UNK> method . 
<UNK> <UNK> . 
ignore Update ' modules / apps / web - experience / staging / . 
add README . md 
<UNK> <UNK> 
Make withoutSource static . 
ignore Update ' modules / apps / collaboration / document - library / . 
<UNK> import 
Add image for preference sample 
<UNK> test 
ignore Update ' modules / apps / foundation / portal - lock / . 
Remove intellij intellij <UNK> from . 
Add ycsb - users . 
Move <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / asset / . 
setting version to 1 . 0 . 139 - SNAPSHOT 
<UNK> <UNK> . 
set <UNK> to RS_R_VERSIONS_PATH 
bump version to 0 . 7 . 1 - SNAPSHOT 
<UNK> <UNK> . jar 
update maps version 
add commons / build to gitignore 
LRQA - <UNK> - Add missing images 
<UNK> travis 
<UNK> <UNK> <UNK> <UNK> <UNK> 
add StreamingGZIPInputStream class 
Updating Alloy to rev . <UNK> 
fixed broken test 
Fix <UNK> <UNK> . 
updated version 
update gitignore 
add gitignore 
update gitignore 
ignore Update ' modules / apps / foundation / map / . 
LPS - <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / contacts / . 
ignore Update ' modules / apps / web - experience / asset / . 
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
<UNK> apt - get update 
ignore Update ' modules / apps / web - experience / layout / . 
<UNK> <UNK> - copy <UNK> 
Fix <UNK> <UNK> 
add README 
Updated icon to <UNK> 
Add travis config 
ignore Update ' modules / apps / collaboration / message - boards / . 
Bump common ref . 
update jackson jar to latest <UNK> version 
update gradle plugin 
Add ShadowViewMeasureSpec . class to Robolectric Robolectric <UNK> 
Updated example image . 
Add <UNK> <UNK> natives . 
Add NSNumber import for NSNumber + JavaNumber 
Fix <UNK> <UNK> <UNK> 
Updated <UNK> icon 
add SGML . txt 
ignore Update ' modules / apps / foundation / portal / . 
<UNK> PApplet XML 
Fix <UNK> <UNK> <UNK> 
add gradle jar 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Add play <UNK> to travis . 9 
Updating Alloy to <UNK> ; LPS - <UNK> 
<UNK> <UNK> 
Fix <UNK> <UNK> 
update english 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Add screenshots 
<UNK> <UNK> 
updated TODO 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Add <UNK> to checkstyle . 
<UNK> <UNK> 
ignore Update ' modules / apps / collaboration / document - library / . 
MinecraftForge / FML @ ac994e178a3533aa3c2ad8359aef9e5852c27a72 <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
updated RELEASE - NOTES - the 361 - the limits at integer 
DO NOT MERGE - <UNK> <UNK> <UNK> <UNK> 
gitignore 
Add Enabling more <UNK> to travis 
ignore Update ' modules / apps / web - experience / site / . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
add debug image 
ignore Update ' modules / apps / foundation / users - admin / . 
fixed <UNK> parent parent parent parent parent parent parent parent parent parent parent 
Add a - query - lang - lang . 
Updated <UNK> 
updated art 
<UNK> the <UNK> <UNK> 
Fix <UNK> <UNK> 
Fix <UNK> 
Fixed package name 
Fix <UNK> <UNK> . 
Fix <UNK> <UNK> <UNK> 
Fix <UNK> test 
Add missing apply for Support Library 
Preparing " <UNK> " <UNK> " 
ignore Update ' modules / apps / foundation / roles / . 
update changelog 
Fixed a bug in ResolveExpressionHandler <UNK> 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Updating copyright to reflect recent <UNK> 
update gradle to version 2 . 2 . 0 
Fix bug with <UNK> <UNK> <UNK> . 
Remove <UNK> test 
add local . properties to gitignore 
update multiwords . txt 
Delete logo - footer . 
Updated library reference 
ignore Update ' modules / apps / foundation / roles / . 
Add gradle gradle for <UNK> 
ignore Update ' modules / apps / web - experience / site / . 
ignore Update ' modules / apps / foundation / petra / . 
updated DMG_background 
update README 
add metrics - httpasyncclient module 
<UNK> <UNK> to <UNK> 
added lint file 
Updated changelog 
Fix typo 
update server1 . yaml 
ignore Update ' modules / apps / collaboration / blogs / . 
update NEWS 
setting version to 1 . 0 . 62 - SNAPSHOT 
Add invalidateMaster <UNK> to Broker <UNK> of <UNK> 
<UNK> <UNK> <UNK> <UNK> 
Add travis config 
bower bower bower install install 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - editor / . 
update travis config 
updated app_konference . so for <UNK> 
Add accountChangeButton . jpg 
fixed <UNK> <UNK> 
Fix <UNK> <UNK> 
Add jslayoutjs jslayoutjs to the jslayoutjs . 
<UNK> <UNK> to <UNK> 
ignore Update ' modules / apps / collaboration / flags / . 
<UNK> <UNK> . 
ignore Update ' modules / apps / foundation / portal - configuration / . 
<UNK> <UNK> to saveOnRunAction 
Add missing break 
ignore Update ' modules / apps / web - experience / product - navigation / . 
add STORM - 1715 to changelog 
update maps version 
<UNK> created animation 
Move <UNK> to be <UNK> 
Fix <UNK> <UNK> <UNK> 
update gitignore 
Remove unused - example 
update toc . textile 
add reference for <UNK> notes 
<UNK> <UNK> <UNK> <UNK> 
Push version to 237 . 
Fix test 
update camQualityPicture . xml 
update README . md 
add Emacs backup files to gitignore 
Bump version number 
Add ' intellij ' to BUCK 
update maven - javadoc - plugin to fix build 
update gitignore 
Updated <UNK> 
Testing the build 
ignore Update ' modules / apps / foundation / portal - cache / . 
Add <UNK> . mp4 
Add <UNK> <UNK> <UNK> to <UNK> 
update NEWS 
add lang - python module 
Remove build files 
add active_directory active_directory active_directory 
<UNK> <UNK> to hosts <UNK> 
Updated changelog 
Fix <UNK> <UNK> . 
bump version for release - server 
Remove unused <UNK> 
ignore Update ' modules / apps / collaboration / recent - documents / . 
<UNK> <UNK> to 5 
Remove unnecessary call 
<UNK> <UNK> . zip 
Fix <UNK> <UNK> 
<UNK> . styl border with border 
Updated changelog 
add vcs to the build . gradle 
Delete tehuti - 0 . 4 . jar from lib 
removed ser . ser and they ' s not used in the <UNK> 
<UNK> FnExpr FnExpr 
Remove @ Override annotation from AbstractTFS . java 
Fixed <UNK> list 
Add modules for <UNK> 
add task to the javadoc 
update location module 
update PosixChildProcess . cpp 
added 49 . listen . 49 . 49 . 49 to manager . py 
update NOTICE 
Add travis config 
Fix <UNK> <UNK> <UNK> . 
updated 2 . 0 . 4 
Add gradle jar 
Prepare library for release 
Add <UNK> . signingConfigs . release to build . gradle 
<UNK> - packages script 
update travis config 
updated javac2 . jar 
Add <UNK> icon 
setting version to 1 . 0 . 140 - SNAPSHOT 
Move <UNK> to correct <UNK> 
Fix <UNK> <UNK> 
Fix <UNK> test 
Fix bug 
Move <UNK> to correct <UNK> 
<UNK> <UNK> 
Make <UNK> executable 
Add <UNK> 
Move BikeParkUpdater BikeParkUpdater BikeParkUpdater to BikeParkUpdater <UNK> 
<UNK> <UNK> <UNK> <UNK> 
update doxia - module - markdown to 1 . 5 
Fix test 
Add netty to netty 
Remove debugging from Makefile 
updated ChangeLog 
update gitignore 
update jersey - server to 1 . 3 
ignore Update ' modules / apps / foundation / petra / . 
<UNK> <UNK> and <UNK> <UNK> 
Add unistd . h struct struct to libmpg123 index . 
Updated changelog 
LPS - <UNK> Add portlet . expiration . time . com . portlet . portlet . portlet . portlet to the portal . properties 
update gitignore 
Add sample - release apk 
Updated SemaphoreConfiguration . index 
Fix <UNK> . metrics . register <UNK> 
<UNK> <UNK> <UNK> 
<UNK> <UNK> to 7 
add STORM - 1467 to changelog 
add jetty - jaas to pom 
ignore Update ' modules / apps / web - experience / site / . 
Bump common ref . 
switched build 
updated CHANGES 
LPS - <UNK> moves icon 
Add travis . yml 
bump to latest 0 . 10 . 0 - rc . 2 
add STORM - 1254 to changelog 
Add <UNK> to SurfaceTexture of <UNK> 
Fix <UNK> <UNK> 
<UNK> <UNK> 
update <UNK> 
Updated 08 - 2015 - 08 - 08 - 08 - 08 - 08 . 
Remove irc - api - 1 . 0 - sources . jar . 
Fix <UNK> <UNK> <UNK> . 
Add missing import 
Add release notes 
update README 
<UNK> <UNK> ' s <UNK> 
Remove Vendor_0a5c_Product_8502 Vendor_0a5c_Product_8502 kl . 
ignore Update ' modules / apps / foundation / frontend - editor / . 
<UNK> <UNK> 
add mode 
update to version 3 . 1 . 0 
Fix <UNK> <UNK> 
Fix <UNK> 
Add travis config 
add check for check to check 
Remove <UNK> 
Fix <UNK> <UNK> 
Remove openjdk6 from travis 
update README . txt 
gitignore 
Fix <UNK> 
LPS - <UNK> Fix portlet <UNK> 
<UNK> <UNK> . Hashtable ( ) in ThreadWithAttributes 
Fix lint <UNK> 
Updated library reference 
Fix <UNK> 
Remove unused TODO 
<UNK> <UNK> println 
Make throws <UNK> to <UNK> 
update android jar 
Fix <UNK> <UNK> . 
<UNK> <UNK> . zip 
<UNK> NoClassDefFoundError priority 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - scheduler / . 
ignore Update ' modules / apps / web - experience / journal / . 
Fix <UNK> <UNK> 
update README 
LRQA - <UNK> Move the <UNK> to portal - test 
Fix delete test 
update change 
Add transform transform transform 
update readme 
ignore Update ' modules / apps / web - experience / layout / . 
Remove extra <UNK> 
update android jar 
LPS - <UNK> <UNK> packageinfo File File 
Updated changelog 
Fix <UNK> <UNK> <UNK> . 
Updating netty to 4 . 1 . 1 
ignore Update ' modules / apps / foundation / xstream / . 
ignore Update ' modules / apps / foundation / portal - template / . 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
add README . md 
Make junit scope scope to test 
update travis 
Add <UNK> <UNK> jar 
Fix dependency 
Make <UNK> <UNK> <UNK> . 
<UNK> the <UNK> of the <UNK> <UNK> <UNK> . 
ignore Update ' modules / apps / foundation / portal - search / . 
update docs 
Fix <UNK> <UNK> 
<UNK> <UNK> - <UNK> 
Remove @ SuppressWarnings from EasyPredictModelWrapperTest test . 
Set <UNK> version to 1 . 0 . 0 . 
<UNK> now group a group 
ignore Update ' modules / apps / collaboration / message - boards / . 
Remove debug <UNK> . 
<UNK> shutdown shutdown shutdown . 
Add tinkerpop . tinkerpop . gremlin . HadoopGremlinPlugin to ext plugins 
update <UNK> to 2 . 9 . 3 
Fix <UNK> . sh 
Remove disconf - web - web 
Add includeTestSourceDirectory <UNK> to the list of the <UNK> 
Add task for <UNK> . 
Fix <UNK> <UNK> <UNK> ( ) . 
<UNK> height of <UNK> 
Add recyclerview jar 
Remove comment 
ignore Update ' modules / apps / foundation / portal - settings / . 
<UNK> <UNK> 
update version to 1 . 0 - SNAPSHOT 
Fix <UNK> <UNK> <UNK> . 
LPS - <UNK> Move ModelAdapterUtil java files 
Fixed test data 
<UNK> <UNK> <UNK> 
Updated <UNK> to latest version 
MinecraftForge / FML @ 4981aa3421262c3c1c4705468fe202df8198b9f0 <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
added sample image . 
Fix <UNK> <UNK> 
<UNK> <UNK> - lssl - lcrypto - lcrypto to lib 
add charset issue for ReleaseNotes server 
Fixed the build 
update gitignore 
Fix Ignore error 
Remove allowBackup allowBackup allowBackup from AndroidManifest 
Remove unused <UNK> from MessagesController . rb 
update gitignore 
Fix <UNK> exception 
<UNK> <UNK> to <UNK> <UNK> . 
ignore Update ' modules / apps / foundation / users - admin / . 
update screenshot 
Bump common ref . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
<UNK> - plugin <UNK> 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / sync / . 
update <UNK> . zip 
<UNK> <UNK> 
<UNK> the <UNK> of the <UNK> <UNK> <UNK> . 
Add <UNK> <UNK> images 
update gradle - wrapper . jar 
add STORM - 126 to changelog 
Fix <UNK> <UNK> . 
<UNK> ' s <UNK> 
bumped parent version . 
ignore Update ' modules / apps / web - experience / staging / . 
updated jnsapi jar 
ignore Update ' modules / apps / collaboration / image - uploader / . 
ignore Update ' modules / apps / collaboration / announcements / . 
<UNK> <UNK> <UNK> <UNK> 
Smack 4 . 1 . 6 - SNAPSHOT 
import import 
Fix typo 
add buildnum . txt 
changed <UNK> to bootstrap 
<UNK> <UNK> and <UNK> 
Fix typo 
update LICENSE 
<UNK> <UNK> <UNK> <UNK> 
Add twine requirements to requirements 
update VERSION to 1 . 5 . 1 
Remove extra line 
update version to 0 . 8 . 10 - SNAPSHOT 
ignore Update ' modules / apps / foundation / portal / . 
<UNK> the JNI <UNK> library . 
ignore Update ' modules / apps / collaboration / recent - documents / . 
Fix mDeletePlayer <UNK> <UNK> in <UNK> 
Fix <UNK> <UNK> 
Updated list with the flow <UNK> 
ignore Update ' modules / apps / collaboration / notifications / . 
<UNK> <UNK> in ByteBufferList <UNK> 
update <UNK> to 1 . 10 . 16 
Add <UNK> to Makefile 
update screenshot 
Fix <UNK> <UNK> <UNK> 
Add <UNK> <UNK> for <UNK> 
Remove right right right right right right right 
ignore Update ' modules / apps / foundation / frontend - js / . 
ignore Update ' modules / apps / foundation / portal - security / . 
Make <UNK> executable 
Add <UNK> . dll for Windows 32 - bit . 
Remove <UNK> from <UNK> 
update bullet natives 
fixed test data 
Updated gradle wrapper to version 1 . 10 . 
ignore Update ' modules / apps / marketplace / . 
add shippable . yml 
Fix build 
Updating Alloy to rev . <UNK> 
Bump version number 
<UNK> hostname . local 
LRQA - <UNK> Remove unused import 
Add relativePath - parent relativePath to pom . xml 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Fix <UNK> <UNK> <UNK> 
Add missing import . 
Add <UNK> <UNK> 
LPS - <UNK> Add description to the description of the user 
<UNK> <UNK> 
Move LiveDatabaseTest test to LiveDatabaseTest test 
Removed junit jar from lib 
Updated changelog 
ignore Update ' modules / apps / web - experience / iframe / . 
LPS - <UNK> Add missing key 
Updated TODO 
add jOOQ - test - utils 
update <UNK> to 0 . 9 - rc - 1 
add platform - tools to travis 
<UNK> <UNK> <UNK> <UNK> 
upgraded to latest <UNK> <UNK> 1 . 1 . 9 
LPS - <UNK> Add settings file 
Add FIREBIRD <UNK> to <UNK> 
<UNK> the <UNK> of the <UNK> - 64 <UNK> . 
Make testNoClassNameDuplication ( ) method 
Fix typo 
add image for <UNK> drawable 
bump to version 2 . 2b2 
<UNK> test 
Fix UserManager <UNK> . 
ignore Update ' modules / apps / marketplace / . 
Add LaunchDaemons root for osx <UNK> 
Make getDefiningClassLoader public 
Fix broken README 
update sysv CNAME <UNK> to <UNK> 
ignore Update ' modules / apps / collaboration / microblogs / . 
update hsqldb 
Setting default name for settings 
ignore Update ' modules / apps / foundation / petra / . 
Fix <UNK> <UNK> 
update dexguard 
Fix sample 
Update NOTICE 
Updated changelog 
ignore Update ' modules / apps / collaboration / document - library / . 
Add Format <UNK> to Format instantiation of <UNK> . 
ignore Update ' modules / apps / foundation / license - manager / . 
add mode 
updated <UNK> <UNK> 
update parent pom 
<UNK> <UNK> <UNK> <UNK> in Compiler <UNK> . 
Fix <UNK> 
Fix <UNK> 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> . java ( ) 
add gradle . properties to gitignore 
<UNK> <UNK> <UNK> 
Remove classLoader classLoader grailsApp . 
Fix typo 
<UNK> <UNK> <UNK> <UNK> 
LPS - <UNK> prep next , use latest 
Prepare next development version . 
updated screenshot 
Remove unused <UNK> 
update <UNK> to version action . 
update server - metrics to 0 . 2 . 2 
Add jar for yui 2 . 4 . 8 
Updated <UNK> to latest version 
ignore Update ' modules / apps / foundation / login / . 
Fixed <UNK> <UNK> 
update gitignore 
Remove module module 
Fix <UNK> <UNK> . 
Remove <UNK> . 
LPS - <UNK> Move icon 
Removed jetty - overlay - deployer from pom . xml 
add STORM - 2092 to changelog 
LRQA - <UNK> prep next , use latest 
Add javadoc to the javadoc 
add KUnitTest test for <UNK> 
ignore Update ' modules / apps / foundation / portal - configuration / . 
update gitignore 
<UNK> <UNK> to configured 
Add IndicesRequestCache IndicesRequestCache to ClusterSettings <UNK> . 
Fix <UNK> <UNK> 
Add href target for target <UNK> 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> 
Updated sonatype parent version 
<UNK> <UNK> for externalProcessingUse externalProcessingUse 
Added jar for <UNK> 
update version to 1 . 2 . 7 - dev 
<UNK> <UNK> ' s <UNK> 
update k9 to 0 . 3 
ignore Update ' modules / apps / foundation / frontend - css / . 
Make <UNK> <UNK> <UNK> <UNK> . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> of <UNK> 
<UNK> <UNK> . getLoadBefore getLoadBefore return getLoadBefore getLoadBefore getLoadBefore getLoadBefore getLoadBefore getLoadBefore getLoadBefore softDepend loadBefore getLoadBefore softDepend softDepend softDepend getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad getLoad ) . 
setting version to 1 . 0 . 136 
<UNK> <UNK> <UNK> <UNK> in <UNK> . 
ignore Update ' modules / apps / web - experience / site / . 
updated <UNK> to <UNK> 
update user_manual . md 
Updated changelog 
added IAtomicReference . util . concurrent . atomic . AtomicReference to 01_5_Whats_new_3 java . 2 . md 
Replace <UNK> 
set <UNK> to grailsApp 
Make blueprints blueprints - test scope 
update cache module 
add project files to . 
Change compileSdkVersion 17 to compileSdkVersion 17 . 
Make <UNK> <UNK> to NOPASS 
Move samples to samples 
Add <UNK> <UNK> for <UNK> 
Add vagrant . pyc deploy to . 
<UNK> <UNK> disableContextMenu disableContextMenu disableContextMenu disableContextMenu disableContextMenu 
ignore Update ' modules / apps / collaboration / document - library / . 
update to latest release snapshot 
Delete sc_01 . 
updated ChangeLog 
<UNK> the build . 
<UNK> bigbluebutton . nginx . bigbluebutton . 
update jackson - jaxrs to 1 . 9 . 7 
Fix <UNK> <UNK> 
update <UNK> . zip 
Fix typo 
update sample flexibledivider 
Add tests for R tracking 
update parent - 8 to UTF - 8 
Fix <UNK> 
Fix <UNK> <UNK> <UNK> 
<UNK> minidns minidns <UNK> <UNK> 
Remove dependency from guice dependency . 
remove svg - web - svg from pom . xml 
update to latest android v1 . 1 . 0 
setting version to 1 . 0 . 69 - SNAPSHOT 
Added aapt differ aapt 
Use jdk8 to <UNK> 
ignore Update ' modules / apps / web - experience / layout / . 
Fix <UNK> <UNK> 
add <UNK> version 
Updated changelog 
Updated changelog 
Add link for <UNK> 
update debug . sh 
Remove unused import 
Add <UNK> for travis 
MinecraftForge / FML @ e1529845384f4935b7c11d4d36d25db51c0b9a31 <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
Fixed <UNK> <UNK> 
Fix <UNK> <UNK> 
Remove <UNK> 
ignore Update ' modules / apps / collaboration / wiki / . 
Make Builder private private to Builder 
Push version to 15 . 0 . 3 . 
add build / build to . 
add validation - api dependency 
update gitignore 
ignore Update ' modules / apps / web - experience / export - import / . 
Add <UNK> 0 . 0 . 7 . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Make <UNK> executable 
ignore Update ' modules / apps / web - experience / trash / . 
updated <UNK> icon 
<UNK> <UNK> <UNK> 
Fix build 
Fix <UNK> <UNK> 
Remove unused <UNK> 
Fix <UNK> 
ignore Update ' modules / apps / collaboration / blogs / . 
update CHANGES 
update <UNK> natives 
LPS - <UNK> moves icon 
<UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
Updating to version 3 . 1 . 0 
updated layout 
Fix coordinator <UNK> <UNK> . 
update ivy version 
ignore Update ' modules / apps / foundation / expando / . 
ignore Update ' modules / apps / web - experience / export - import / . 
Fix bottom 
update changelog 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> 
update sc logo 
ignore Update ' modules / apps / web - experience / iframe / . 
Add jcenter ( ) to repositories . 
Fix 4 . 
Updated _misc <UNK> <UNK> 
bump version 
Updated <UNK> <UNK> to <UNK> <UNK> . 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - lock / . 
LPS - <UNK> ( WEB ) Move chat chat chat chat chat INF 
ignore Update ' modules / apps / web - experience / asset / . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> 
Add missing <UNK> 
Add * - dashboard - web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web
Fix <UNK> <UNK> <UNK> 
update changelog 
<UNK> <UNK> <UNK> 
<UNK> <UNK> 
Make <UNK> executable 
Remove 51 tmlog1 
Updated <UNK> libs 
Added 8675fbdee81afa7723bcc43023a15d932ca845b7 0b1 2 . 2 
<UNK> travis 
add deploy . bat 
Add container to travis 
update gradle to 1 . 0 . 1 
ignore Update ' modules / apps / sync / . 
add <UNK> - v4 . 0 . zip to docs 
<UNK> <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - js / . 
setting version to 1 . 0 . 123 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
<UNK> the <UNK> <UNK> icon . 
gitignore 
add CHANGES entry 
update 
Updated <UNK> wallpaper 
ignore Update ' modules / apps / collaboration / document - library / . 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
remove unused method 
set version 
ignore Update ' modules / apps / web - experience / journal / . 
Add 333 - upgrade 
bump alpha - 5 
<UNK> <UNK> 
Fix <UNK> form 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> 
update linux natives 
LRQA - <UNK> <UNK> port port for setproxy . properties 
Fix <UNK> <UNK> 
bump pegasus to 1 . 9 . 18 
add " TODO " 
ignore Update ' modules / apps / foundation / portal - instances / . 
add push_buxs . bat 
add reference to antlr4 
bumped parent version . 
update changelog 
<UNK> <UNK> <UNK> 
update parent pom to 9 . 0 
add mode 
Remove debug <UNK> 
Updating compile to 1 . squareup 
Add <UNK> translation 
update http request 
Fix <UNK> <UNK> . 
fixed test 
Add travis config 
Fix <UNK> <UNK> 
update AndroidManifest . xml 
prohibit Busenbrenner Busenbrenner NS . 0 . 0 - <UNK> 
remove gant_groovy1 jar 
<UNK> client 
add <UNK> . 
Updated <UNK> description 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - settings / . 
remove unused ChangeLogParserListener . 
Move tests to fix <UNK> 
Remove scala <UNK> 
update release script 
ignore Update ' modules / apps / collaboration / message - boards / . 
update <UNK> to gephi gephi <UNK> 
Add notice to <UNK> 
Fix <UNK> <UNK> 
Add <UNK> . properties 
Updating Alloy to rev . <UNK> 
fixed <UNK> <UNK> <UNK> 
add image for VerbalExpressions 
update changelog 
update README 
Delete app / version 
<UNK> license image 
Removed junit jar from lib 
Updated api . services . png to reflect the new version 
Remove bazel bazel tools - tools bazel bazel bazel 
Fix <UNK> <UNK> 
Delete bg . jpg 
update project . xml 
ignore Update ' modules / apps / collaboration / bookmarks / . 
Reduce <UNK> <UNK> 
setting version to 1 . 0 . 68 
update gitignore 
<UNK> the <UNK> of the <UNK> <UNK> <UNK> . 
Add <UNK> to the checkstyle 
ignore Update ' modules / apps / foundation / frontend - theme / . 
ignore Update ' modules / apps / collaboration / notifications / . 
<UNK> travis to <UNK> 
Fix typo 
ignore Update ' modules / apps / web - experience / layout / . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
update changelog 
Delete BrowserLauncher2 . jar 
Updated <UNK> 
update CHANGELOG 
setting version to 1 . 0 . 73 
ignore Update ' modules / apps / foundation / frontend - css / . 
Remove unused storm file 
added image for <UNK> - dead - concert2 . 
<UNK> <UNK> <UNK> <UNK> 
Remove registerForRemoteNotifications registerForRemoteNotifications registerForRemoteNotifications 
add Dart Dart to AWSCloudFormation 
add @ Deprecated annotation 
add missing project 
Add elasticsearch indexer 
Add travis config 
Add <UNK> to <UNK> . 
Fix <UNK> <UNK> <UNK> 
update gif 
Fix createDefaultUsers createDefaultUsers createDefaultUsers . 
Add break to Extractor <UNK> 
ignore Update ' modules / apps / foundation / portal - search / . 
Make <UNK> executable 
Fix <UNK> <UNK> 
add <UNK> icon 
ignore Update ' modules / apps / marketplace / . 
LRQA - <UNK> Fix typo 
ignore dictionary - web 1 . 0 . 2 prep next 
update <UNK> 
Travis Travis 
update project 
add TODO 
Add <UNK> . 
LRQA - <UNK> - Add missing images 
Fixed typo 
Fix broken test 
added clover license 
Bumping 191 191 191 . 
update win32 natives 
update version to 2 . 1 - SNAPSHOT 
Updated changelog 
<UNK> <UNK> <UNK> <UNK> 
Add image for preference 
prepare for next development iteration 
Fix <UNK> <UNK> <UNK> 
Add <UNK> to FileContentProvider <UNK> ( ) 
Fix typo 
Add GL_PATCHES <UNK> to GL4 <UNK> <UNK> 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / sync / . 
Remove pomPropertiesFile pomPropertiesFile pomPropertiesFile from <UNK> 
bump version 
ignore Update ' modules / apps / screens / . 
updated gant 
Add cd build for Makefile 
Add <UNK> root for <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
Updating parent version . 
Prepare library for development 
Fix test 
updated version 
Delete hazelcast - 2 . 1 . 2 . 
Add fullBackupContent fullBackupContent fullBackupContent to rxlifecycle - sample . 
Remove unused <UNK> 
MinecraftForge / FML @ 5d6dc5dce37e488188d6fc468c16e8a6183a3610 <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
Add image for preference <UNK> 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / microblogs / . 
Fix <UNK> <UNK> <UNK> . 
update linux - ppc64le natives 
ignore Update ' modules / apps / web - experience / export - import / . 
ignore Update ' modules / apps / collaboration / image - uploader / . 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / flags / . 
Fix <UNK> <UNK> 
Fix <UNK> 
Updated changelog 
bump to version 1 . 9 . 22 
update 1 . 1 . 0 release 
<UNK> the <UNK> of the graphhopper . 
ignore Update ' modules / apps / web - experience / staging / . 
Add null for <UNK> 
<UNK> . gif 
Add <UNK> 0 . 0 . 7 . 3 for changeset <UNK> 
<UNK> <UNK> ' s <UNK> ' s place 
add STORM - 1482 to CHANGELOG 
LPS - <UNK> add aui . tld to gitignore 
add WARN . xml to log4j . xml 
Remove gradle from build . gradle 
Make scope to test scope 
updated CHANGES 
updated <UNK> to <UNK> <UNK> . 
Updated pdf 
Fix <UNK> <UNK> <UNK> 
Add isms <UNK> to <UNK> 
<UNK> <UNK> <UNK> <UNK> 
Delete ic_launcher web 
LPS - <UNK> - Remove empty file 
updated version 
Set comboBoxDp <UNK> to 1 
Remove unnecessary <UNK> from settings . gradle 
Add <UNK> . maldini 
Smack 4 . 1 . 0 - rc3 
Add <UNK> to <UNK> 
Fix heap <UNK> - > - plugin . 
ignore Update ' modules / apps / foundation / configuration - admin / . 
ignore Update ' modules / apps / foundation / plugins - admin / . 
Updated changelog 
update <UNK> to v1 . 0 . 2 
Remove unused image 
added gradle . properties file 
ignore Update ' modules / apps / foundation / frontend - js / . 
LPS - <UNK> Add a property 
add STORM - 274 to CHANGELOG 
Add parcour @ @ @ gmail to travis 
Updated submodules 
update gitignore 
ignore Update ' modules / apps / foundation / portal - search / . 
ignore Update ' modules / apps / web - experience / layout / . 
update CONTRIBUTORS 
update gitignore 
Set <UNK> to compile 
update build 
ignore Update ' modules / apps / foundation / frontend - editor / . 
Remove unused fontawesome fontawesome 
Fix <UNK> <UNK> 
setting version to 1 . 0 . 72 - SNAPSHOT 
Updated changelog 
ignore Update ' modules / apps / web - experience / export - import / . 
update fileContent + + to gitCommit + . 
Fix the <UNK> <UNK> . 
<UNK> <UNK> <UNK> <UNK> 
Ignore files 
Fix <UNK> 
<UNK> <UNK> 
updated gant 
Add build - tools - 19 . 1 . 0 
ignore Update ' modules / apps / foundation / roles / . 
add 8eb5ae9da46fd4fa6af17df1632c97dd0e385f82 - ee - ee 
<UNK> <UNK> - wait - interval sms sms 
update druid version 
Update travis config 
ignore Update ' modules / apps / foundation / frontend - js / . 
Add missing import 
ignore Update ' modules / apps / collaboration / bookmarks / . 
<UNK> resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp resp ) 
add mode 
add several . txt 
Fix <UNK> <UNK> 
Updated changelog 
update xercesImpl version 
updated changelog 
SONAR - <UNK> Add missing title 
Make getAccountManager AccountManager public . 
Remove unused method 
ignore Update ' modules / apps / foundation / portal - search / . 
proguard interface 
ignore Update ' modules / apps / collaboration / document - library / . 
LRQA - <UNK> Add <UNK> <UNK> icon 
ignore Update ' modules / apps / static / osgi / . 
update wiki 
Push <UNK> . 
ignore Update ' modules / apps / collaboration / microblogs / . 
Add <UNK> to the list of the root <UNK> 
Fix <UNK> <UNK> 
Add fileoverview externs for angular Material . 
<UNK> <UNK> - type to 1 . rules . 0 
ignore Update ' modules / apps / foundation / map / . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> 
Add <UNK> . png to xhdpi . 
Updated jediterm - pty - 2 . 1 . jar to jediterm terminal <UNK> . 
ignore Update ' modules / apps / foundation / portal - scheduler / . 
Add <UNK> to <UNK> 
Updated <UNK> icon 
ignore Update ' modules / apps / foundation / hello - world / . 
update version to 3 . 0 . 4 
Remove System . out . println from Editor . 
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
ignore Update ' modules / apps / foundation / contacts / . 
add log4j jar 
Add <UNK> 
Updating Alloy to rev . <UNK> 
Remove <UNK> <UNK> <UNK> <UNK> 
Updated <UNK> 
bump to latest r10 - SNAPSHOT 
Remove unused <UNK> . 
Fix <UNK> <UNK> <UNK> . 
Remove unused @ SafeVarargs list 
Delete yuicompressor - 2 . 4 . 8pre jar 
add * . 
Updated <UNK> . txt 
Adds 1 . 1 . 1 release . 
Add Trevor John to pairs <UNK> . 
Fix <UNK> <UNK> 
<UNK> <UNK> to junit 
Remove unused image 
Use git <UNK> git 
Add ConnectionService hide to ConnectionService <UNK> . 
add Boat . java to Boat Boat for <UNK> . 
Fix <UNK> Success Success Success in <UNK> 
Fix NotificationOptions Notification <UNK> . 
<UNK> <UNK> . 
add STORM - 807 to CHANGELOG 
ignore Update ' modules / apps / foundation / login / . 
Add @ Override annotation to TestCommand . 
update <UNK> to 5 . 0 . 0 
update blurringview version 
update git 
add out / out to . 
ignore Update ' modules / apps / web - experience / export - import / . 
ignore Update ' modules / apps / collaboration / microblogs / . 
Updated CHANGES 
Fix <UNK> . yml 
ignore Update ' modules / apps / collaboration / wiki / . 
Fix NotificationOptions Notification <UNK> . 
ignore Update ' modules / apps / collaboration / blogs / . 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> 
checkstyle the checkstyle 
Change maxThreads 0 . 0 to 100 . 
updated CHANGES 
LRQA - <UNK> Add property property to test . properties 
<UNK> <UNK> 
update version to 1 . 0 . 21 - SNAPSHOT 
Added <UNK> jar 
Updating Alloy to rev . <UNK> 
update iconics - core to 1 . 5 . 1 
Updated <UNK> 
Fixed broken test 
Delete DeepLearningRVignetteDemo . zip 
ignore Update ' modules / apps / foundation / frontend - js / . 
Remove unnecessary file 
add package . html 
updated header 
update classes natives 
LRQA - <UNK> Move <UNK> to portal - web 
add linksource . additionalparam . additionalparam maven - 1 . additionalparam to project . properties 
Compile to include minSdkVersion and <UNK> 
remove unused @ Override 
updated to latest 0 . 5 - RC2 
LRQA - <UNK> Add property to test . properties 
Add <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / export - import / . 
add tests for build 
<UNK> <UNK> . groovy ( ) 
ignore Update ' modules / apps / foundation / frontend - js / . 
update reference for <UNK> 
Add gitignore 
update changelog 
hgignore nbproject . el 
<UNK> <UNK> . trackEventForSelfHostedAndWPCom ( ) instead of WPMobileStatsUtil WPMobileStatsUtil 
<UNK> <UNK> <UNK> 
update ant jar 
Bump common ref . 
add buffer for buffer code 
ignore Update ' modules / apps / web - experience / journal / . 
ignore Update ' modules / apps / foundation / frontend - editor / . 
ignore Update ' modules / apps / collaboration / wiki / . 
Added translation using Weblate ( <UNK> ) 
ignore Update ' modules / apps / foundation / portal - store / . 
Add stats stats stats to the stats . 
update build script 
added <UNK> image of the landscape_rtl 
update gif 
update <UNK> 
LPS - <UNK> <UNK> alloy <UNK> jar , Alloy Alloy jar 
Make 0755 FileUtils FileUtils . 
MinecraftForge / FML @ 741e172ffe163f0dd3018e1474af46ef0696396a <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
add jacoco_build . sh 
Updated <UNK> jar 
<UNK> travis 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / document - library / . 
added class diagram for factory pattern 
Updating Alloy to rev . <UNK> 
ignore Update ' modules / apps / foundation / portal - remote / . 
ignore Update ' modules / apps / foundation / portal - search / . 
update build 
ignore Update ' modules / apps / collaboration / microblogs / . 
Add 0755 fileMode fileMode to tachyon <UNK> 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Fix <UNK> <UNK> . 
<UNK> debug debug . 
Fix width width 
Updated changelog 
Add ES_INCLUDE ES_INCLUDE to <UNK> . 
Add <UNK> operation <UNK> ( <UNK> ) 
Bump common ref . 
ignore Update ' modules / apps / foundation / frontend - css / . 
Prepare version 19 - beta3 . 
<UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
Remove <UNK> <UNK> 
Updated gif 
Remove <UNK> from ParticleSystem . pde 
add STORM - 1268 to CHANGELOG 
updated LeonidsLib jar 
ignore Update ' modules / apps / collaboration / directory / . 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - security / . 
Fix <UNK> <UNK> <UNK> 
Remove unused <UNK> <UNK> 
add TODO for TODO 
add readerwriter - injection to jaxrs 
bump version to 1 . 0 . 0 - beta . 2 . 
updated studio with <UNK> 
Add circle . yml 
<UNK> - PreducedMemory travis 
<UNK> <UNK> <UNK> 
update <UNK> to android - 19 
Remove parallel <UNK> dependency 
Adds <UNK> . dll for Windows . 
update dependency to guava guava 
add twitter - search module 
Add <UNK> translation 
Remove unnecessary file 
add missing test 
Fix <UNK> <UNK> <UNK> 
Fixed <UNK> <UNK> <UNK> 
update maven - compiler - plugin to 3 . 0 
LPS - <UNK> Add <UNK> to packageinfo 
ignore Update ' modules / apps / foundation / petra / . 
Delete notify_chatsecure . 
ignore Update ' modules / apps / marketplace / . 
<UNK> - launcher - launcher - launcher <UNK> python python 
add ' deliverability ' to spelling 
Add travis - ci . 
add tempFile . txt 
Move scala version to 3 . 1 . 0 
<UNK> quotes 
<UNK> <UNK> 
<UNK> the version of the dsel 
<UNK> - java - test - sizefile - sizefile - sizefile - sizefile - sizefile - sizefile - sizefile - sizefile - sizefile . 
Use the latest previousVersion <UNK> version of the pom . 
ignore Update ' modules / apps / foundation / portal - search / . 
Bump common ref . 
add SOURCE . txt for 3479 - 3479 
add tachyon . master for <UNK> 
update maven maven to 2 . 0 . 6 
update readme 
Remove unused import 
ignore Update ' modules / apps / foundation / configuration - admin / . 
ignore Update ' modules / apps / collaboration / bookmarks / . 
set version for development 
<UNK> <UNK> . Color 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> shutdown shutdown . 
LPS - <UNK> Copy new jars 
<UNK> <UNK> 
Add <UNK> jar for truth 0 . 6 
ignore Update ' modules / apps / web - experience / staging / . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Prepare version 22 . 0 . 0 - beta5 . 
ignore Update ' modules / apps / foundation / contacts / . 
<UNK> the <UNK> 
Remove unused print 
Updated <UNK> 
Remove unused LogBufferDescriptor 
ignore Update ' modules / apps / foundation / portal - remote / . 
ignore Update ' modules / apps / collaboration / bookmarks / . 
LPS - <UNK> Remove empty file 
add <UNK> 
Modify otr4j 
add bug for bug to CONTRIBUTORS 
Remove lp lp lp . 
Fix <UNK> <UNK> . 
Updated changelog 
update gitignore 
<UNK> <UNK> <UNK> <UNK> 
Use <UNK> Android 22 . 
update aboutlibraries to latest android 5 . 0 . 5 
Remove println 
ignore Update ' modules / apps / collaboration / document - library / . 
<UNK> Files 
Remove unused leveloffset ql 2 . 5 
<UNK> the <UNK> of the threadProc timerSet timerSet timerReset timerReset <UNK> . 
ignore Update ' modules / apps / collaboration / wiki / . 
Updated hbase_datastore jar 
Add a echo list to helios list 
ignore Update ' modules / apps / foundation / portal - scripting / . 
add MANIFEST . MF to . 
Remove unused jar 
updated ChangeLog 
remove unused demo file 
update <UNK> to 0 . 10 . 69 
Add " node " to buildSuccess import 
Fix typo 
Push version to 28 . 
update gitignore 
<UNK> the <UNK> of the change 
add mode 
Upgrade <UNK> to 1 . 3 . GA 
gitignore gitignore 
update <UNK> natives 
Fix <UNK> <UNK> 
Fix <UNK> <UNK> 
Updated parent version . 
LPS - <UNK> <UNK> VARCHAR add groupKey to the same <UNK> 
y xml - y - apis sudo 
update engine version 
update camel - parent to 2 . 15 - SNAPSHOT 
update sunos natives 
<UNK> <UNK> <UNK> <UNK> in NIOConnection <UNK> 
ignore Update ' modules / apps / foundation / plugins - admin / . 
Updated CHANGELOG 
update kotlin reflect version 
<UNK> <UNK> . zip 
<UNK> the build . 
Add @ Override annotation 
<UNK> <UNK> to 1 
ignore Update ' modules / apps / collaboration / wiki / . 
update mac developers 
Replace image for practice_1_sample practice <UNK> 
Updated dslv to latest head 
Add <UNK> <UNK> 
Fix typo 
Fix <UNK> <UNK> 
<UNK> <UNK> 
Add <UNK> jar 
Delete GROUPS GROUPS 
ignore Update ' modules / apps / collaboration / blogs / . 
ignore Update ' modules / apps / web - experience / site - navigation / . 
Updated library reference 
Fix <UNK> const . 
ignore Update ' modules / apps / foundation / portal - search / . 
updated ChangeLog 
update camel - parent to 2 . 8 - SNAPSHOT 
add license 
update project . properties 
<UNK> travis to <UNK> 
Prepare for next development iteration 
ignore Update ' modules / apps / foundation / portal - security / . 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Remove unused files 
LPS - <UNK> <UNK> <UNK> / rss <UNK> 
Remove unused newline 
Updated changelog 
LPS - <UNK> update jar 
ignore Update ' modules / apps / foundation / contacts / . 
Add travis . yml 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Fixing transitive - ness of provided 
Updated <UNK> icons 
ignore Update ' modules / apps / marketplace / . 
add <UNK> icon 
ignore Update ' modules / apps / collaboration / flags / . 
Fix orientation orientation orientation 
Make <UNK> <UNK> <UNK> <UNK> . 
update LICENSE 
Updating up version 
update nodes 
Remove unused <UNK> 
Prepare next dev iteration 
update windows natives 
update version to 2 . 0 . 11 - beta 
update ognl version 
Remove unnecessary application android application 
setting version to 1 . 0 . 119 
added <UNK> image 
update AUTHORS 
Fix <UNK> <UNK> 
update to latest android 1 . 1 . 5 
Added translation using Weblate ( <UNK> ) 
update LICENSE 
remove unused import 
Fix <UNK> <UNK> 
Added Joachim Baumann to the pom 
Add list of <UNK> . py 
Updated <UNK> jar 
Updating Alloy to rev . <UNK> 
update version number 
<UNK> <UNK> <UNK> <UNK> in KeyguardPINView <UNK> 
<UNK> <UNK> . 
Fix <UNK> <UNK> <UNK> . 
add <UNK> for <UNK> 
Remove unnecessary lines 
Add extra google google m2repository 
Updated <UNK> to <UNK> 
ignore Update ' modules / apps / web - experience / staging / . 
Regenerate - <UNK> - <UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> 
LPS - <UNK> update css 
update libwebp 
added <UNK> <UNK> 
Add image for <UNK> 
update support to 23 . 1 . 1 
Fix install - boost - boost - boost 
add README . md 
add , vcs - api - api " 
Fix repo 
Add xhdpi icon for xhdpi 
Fix <UNK> <UNK> 
<UNK> - native React React React lib 
Delete change branch 
Add JARs directory 
<UNK> <UNK> . post ( ) 
<UNK> <UNK> to ExampleConfiguration <UNK> 
<UNK> <UNK> 
Fix web - web . js 
Fix <UNK> <UNK> . 
Updated changelog 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / product - navigation / . 
<UNK> the <UNK> <UNK> <UNK> to <UNK> . 
update gitignore 
<UNK> <UNK> . sh 
update gitignore 
<UNK> Eurasian Eurasian <UNK> 
<UNK> <UNK> . 
<UNK> <UNK> <UNK> 
Fix 4160 4160 <UNK> in how_to_deploy . md 
LRQA - <UNK> Move the <UNK> to portal - test - internal 
SONAR - <UNK> Fix <UNK> 
update version to 7 . 3 
Updated FML 
Updated gif 
Updated changelog 
ignore Update ' modules / apps / foundation / users - admin / . 
Delete protobuf / protobuf - java - 2 . 2 . 0 . 
<UNK> <UNK> ' s <UNK> 
Fix <UNK> <UNK> <UNK> 
Add screenshots 
Updating Alloy to rev . <UNK> 
LPS - <UNK> <UNK> display display 
<UNK> flow 
Remove unused steam steam 
Add <UNK> + layout_alignBottom 
Updated <UNK> icon 
Setting default name for multi - project 
Remove unused import 
travis 
LPS - <UNK> Move dependencies 
Fix <UNK> bottom 
Fix <UNK> <UNK> <UNK> <UNK> . 
update <UNK> to 4 . 2 . 3 
ignore Update ' modules / apps / foundation / portal - lock / . 
Add <UNK> Access for <UNK> Access access . 
Remove unused <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / mentions / . 
<UNK> version number 
Updated changelog 
ignore Update ' modules / apps / web - experience / journal / . 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / message - boards / . 
ignore Update ' modules / apps / collaboration / document - library / . 
Updated parent version . 
Remove <UNK> <UNK> <UNK> 
Updated <UNK> to 2 . 8 . 8 
Add gif for success static 
Updated changelog 
Add missing mLeft to <UNK> . 
LPS - <UNK> Fix <UNK> 
update README 
ignore Update ' modules / apps / collaboration / message - boards / . 
Add image for preference 
ignore Update ' modules / apps / collaboration / blogs / . 
ignore Update ' modules / apps / foundation / portal - template / . 
Updates the <UNK> background icon . 
Fix <UNK> <UNK> <UNK> 
Move <UNK> to correct <UNK> 
Fix typo in README 
Add demo . gif 
ignore Update ' modules / apps / collaboration / document - library / . 
Updated bin 
setting version to 1 . 0 . 107 - SNAPSHOT 
update abs . version to 4 . 2 . 0 
ignore Update ' modules / apps / web - experience / site / . 
Fix file_root - <UNK> file_root file_root fileroot - <UNK> 
<UNK> <UNK> 
Fix broken test 
add <UNK> for <UNK> 
Updated fastjson jar to latest <UNK> version 
Remove unused import . 
update hadoop - HDFS - 7285 - 7285 - 7285 - 7285 
<UNK> now now <UNK> the <UNK> 
Add Banner Banner <UNK> 
Fix <UNK> <UNK> <UNK> . 
<UNK> <UNK> <UNK> 
Add missing @ Override annotation 
Remove println 
add changelog 
Updating <UNK> to 1 . 9 . 7 
remove <UNK> 
Delete color_demo . gif 
LPS - <UNK> Remove unused <UNK> 
ignore Update ' modules / apps / collaboration / announcements / . 
Smack 4 . 1 . 0 - alpha6 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / sync / . 
<UNK> <UNK> to 14 
Bumping rest - client submodule 
Add lava type to cliff_walking_1 <UNK> . 
update linux - x86 natives 
Remove <UNK> <UNK> 
optimize imports 
<UNK> Makefile 
Fix dependency for tightdb - java - core 
ignore Update ' modules / apps / foundation / frontend - css / . 
ignore Update ' modules / apps / foundation / portal - search / . 
Fix <UNK> <UNK> <UNK> 
Delete js . jar 
Remove local . properties 
update README 
Remove unused margin 
Updated README 
update linux natives 
Fix <UNK> <UNK> 
updated ymsg_support jar 
update maven - release - plugin to 2 . 1 
Updated logo 
update pom 
Add travis config 
Fix <UNK> . 
Added Mike Dillon to the pom 
Fix <UNK> <UNK> 
Add jd_reverse_express . png 
ignore Update ' modules / apps / foundation / portal - template / . 
update 1 . 0 . 0 release 
Updated import 
updated changelog 
remove @ Override annotation 
Updated <UNK> libs 
Fix <UNK> <UNK> 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
remove sample_missions kk <UNK> 
ignore Update ' modules / apps / foundation / portal - cache / . 
upgraded netty to 4 . 0 . 17 
ignore Update ' modules / apps / collaboration / blogs / . 
Removed <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
Add target to the samples 
Fix <UNK> <UNK> <UNK> 
Fix build script 
<UNK> <UNK> 
Remove swp refine 
update travis config 
Use <UNK> <UNK> <UNK> to <UNK> 
update app version 
ignore Update ' modules / apps / collaboration / blogs / . 
Remove unused <UNK> <UNK> icon . 
add STORM - 1233 to CHANGELOG 
<UNK> version to 3 . 0 . 0 - SNAPSHOT 
update travis script 
bumped version to 1 . 0d 
ignore Update ' modules / apps / web - experience / export - import / . 
Remove <UNK> from <UNK> 
Fix targetPackage tests 
Updated structdb 
Fix <UNK> <UNK> <UNK> 
fixed <UNK> <UNK> 
<UNK> <UNK> 
Add <UNK> <UNK> icon 
Upgrade <UNK> to 2 . 3 
Fix <UNK> <UNK> <UNK> 
update features 
Updated changelog 
Make <UNK> executable 
<UNK> <UNK> . color ( currentStrokeColor p . color ) 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
<UNK> <UNK> . mRenderer mRenderer mRenderer mRenderer NULL mRenderer mRenderer NULL . 
<UNK> <UNK> . 
<UNK> the <UNK> test . 
<UNK> <UNK> <UNK> <UNK> 
Added b2429ac28ab5cde6dd99f2543e250b34a898794e - 2 . 0 - ignoreme 0000000000000000000000000000000000000000 
Prepare next development iteration 
<UNK> <UNK> 
add changelog 
Added getAuthenticationDetailsSource <UNK> to AbstractProcessingFilter - 310 - 310 
ignore Update ' modules / apps / foundation / roles / . 
removed support - support - v4 version 
update gitignore 
update ideaVersion . sh 
Add image for preference sample 
Fix <UNK> script 
Remove unused Roboto Roboto <UNK> 
<UNK> <UNK> in ContextImpl <UNK> 
Delete spark . rar 
Move example to example 
Remove unnecessary parallel - execute 
update changelog 
add . 
update demo . gradle 
update gitignore 
Updated changelog 
ignore Update ' modules / apps / foundation / osgi / . 
Fix <UNK> <UNK> 
update commons - collections to 3 . 2 . 2 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> to <UNK> 
Remove unnecessary call . 
updated CHANGES 
Add link for README 
Add Mike AUTHORS for AUTHORS 
Fixed test 
update crash 
updated test 
update neo4j - kernel - SNAPSHOT to SNAPSHOT 
ignore Update ' modules / apps / collaboration / invitation / . 
setting version to 1 . 0 . 110 - SNAPSHOT 
Pull ColorPicker of ColorPicker <UNK> 
LPS - <UNK> moves icon 
Add checkstyle for checkstyle files 
Remove libs / libs from . 
Built the latest snapshot 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / image - uploader / . 
Remove unused icons 
Remove commons - io - class dependency 
updated studio 
add demo apk 
remove unnecessary prop 
Rename LICENSE 
update CHANGES 
add <UNK> 
ignore Update ' modules / apps / web - experience / layout / . 
update TODO 
Add <UNK> to <UNK> 
<UNK> <UNK> to <UNK> 
Fix library 
ignore Update ' modules / apps / collaboration / document - library / . 
Fix NPE in <UNK> . 
updated studio with <UNK> 
update TODO 
Fix http2 http2 http2 
update emitter version 
Updated changelog 
add Graylog . conf 
<UNK> <UNK> <UNK> <UNK> 
LRQA - <UNK> Add new testray testray component to testray . properties 
Remove jar 
ignore Update ' modules / apps / web - experience / export - import / . 
updated to latest release <UNK> 
add icon for <UNK> 
ignore Update ' modules / apps / collaboration / comment / . 
added HdrHistogram - 2 . 1 . 6 
set version 
update gitignore 
<UNK> <UNK> . 
Fix <UNK> <UNK> 
Add <UNK> to travis 
Fix <UNK> <UNK> <UNK> 
Move <UNK> to the same class 
add 005 to <UNK> 
<UNK> <UNK> <UNK> 
LPS - <UNK> - Remove unnecessary line 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal / . 
ignore Update ' modules / apps / web - experience / staging / . 
Push version to 9 . 1 . 
Now closes the <UNK> <UNK> . 
add STORM - 1196 to changelog 
update README 
Delete opengl . jar 
update <UNK> to 1 . 2 . 5 
LPS - <UNK> - <UNK> text <UNK> text in <UNK> 
Add 2 . txt to docs for embedded examples 
remove unused <UNK> 
<UNK> <UNK> to forkmode <UNK> 
Fix stream <UNK> 
ignore Update ' modules / apps / web - experience / staging / . 
update transfuse version 
Add <UNK> . 
Fix <UNK> script 
ignore Update ' modules / apps / collaboration / mentions / . 
Upgrade to latest project parent parent . 
update to latest android android android android android android 1 . 1 . 0 
Add monitor monitor to sqllogictest import 
ignore Update ' modules / apps / web - experience / asset / . 
update jetbrains . dic 
add _collections to <UNK> 
Make pkg pkg pkg size for <UNK> 
Remove reference from ResolutionStrategy 
<UNK> failing test 
<UNK> <UNK> <UNK> <UNK> 
add missing @ NotNull 
Add <UNK> notification 
Add readMoreTextViewExpanded readMoreTextViewExpanded screenshots 
Fix <UNK> <UNK> 
update server version 
Add test - * . 
Remove <UNK> <UNK> 
update usage to 2 . 0 . 0 - SNAPSHOT 
Add travis config 
ignore Update ' modules / apps / foundation / contacts / . 
Fix <UNK> <UNK> 
<UNK> <UNK> and <UNK> 
ignore Update ' modules / apps / foundation / portal - configuration / . 
ignore Update ' modules / apps / web - experience / export - import / . 
Fix <UNK> <UNK> . 
update README . md 
remove unused <UNK> 
add <UNK> icon 
updated to latest 1 . 0 - RC1 - SNAPSHOT 
Move ZLAndroidMainWindowUtil android geometerplus to correct folder 
remove unused <UNK> <UNK> 
fixed push push <UNK> 
Remove unnecessary line 
Add screenshots 
updated todo 
updated version 
update mongo - compat - driver to 2 . 11 . 0 
update <UNK> to 15 
Add art_toolbar . png 
add coverage to <UNK> 
Make initWebSocket initWebSocket public 
Add <UNK> font ttf 
Add changelog for 0 . 9 . 9 
Add stdint . h > to ColorConverter ColorConverter . 
added gitignore 
Updated changelog 
Add debug <UNK> to login 
update demo 
ignore Update ' modules / apps / foundation / portal - configuration / . 
setting version to 1 . 0 . 134 - SNAPSHOT 
add there for debug stream 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Delete ic_launcher . 
ignore Update ' modules / apps / foundation / portal - instances / . 
fix the <UNK> . 
updated ChangeLog 
<UNK> version to 1 . 1 - rc - 1 
remove pooled pooled true from DataSource - app 
<UNK> - tests 
add hg4idea hg4idea to <UNK> 
<UNK> <UNK> <UNK> 
update cqlsh 3 . 1 . 5 
add STORM - 898 to changelog 
Add <UNK> <UNK> 
Add cwac_camera_profile_motorola_xt910_rtanz . xml to cwac_camera_profile_motorola_xt910_rtanz camera <UNK> for <UNK> - - <UNK> 
LPS - <UNK> Add new new <UNK> to the list of the selection 
update travis config 
bump to version 1 . 8 . 25 
ignore Update ' modules / apps / web - experience / trash / . 
Add README . md 
Add getChangeLogParameters changeLogParameters ( ) to Liquibase - getChangeLogParameters 
updated MaterialDesignIconGeneratorPlugin jar 
Fix <UNK> for Support13Demos apk . 
Added svm_print_interface ( ) to <UNK> . 
<UNK> <UNK> . 
add circle . yml 
update version to 1 . 0 . 8 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
<UNK> <UNK> 
Bump up version . 
<UNK> <UNK> . kt world 
<UNK> <UNK> <UNK> 
<UNK> Example <UNK> . 
update to latest release snapshot 
outputs syncDoc inputs to outputs syncDoc <UNK> - <UNK> 
update internal framework to API 19 
Updated changelog 
ignore Update ' modules / apps / foundation / portal - template / . 
add TODO 
update travis config 
Fix <UNK> <UNK> 
updated ChangeLog 
ignore sync - api 1 . 0 . 1 prep next 
remove unused stopTableEditing 
updated version 
<UNK> <UNK> 
update typed . txt 
<UNK> <UNK> ( ) in <UNK> ( ) 
ignore Update ' modules / apps / web - experience / layout / . 
Remove unused planner . 
ignore Update ' modules / apps / foundation / portal - scheduler / . 
bbb - record - record - record <UNK> 
Remove executable 
Push version to 15 . 0 . 2 . 
updateChangesContent shelf shelf - <UNK> 
Move start . bat to start . sh 
ignore Update ' modules / apps / web - experience / rss / . 
Add image for preference 
update dependencies 
Use the latest 2 . 2 . 1 version of the <UNK> version number . 
Bump common ref . 
ignore Update ' modules / apps / collaboration / wiki / . 
ignore Update ' modules / apps / web - experience / asset / . 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / sync / . 
Updated apk 
Add image for readme 
update gitignore 
Fix <UNK> <UNK> 
<UNK> <UNK> and <UNK> 
update <UNK> to 0 . 8 . 2 - RC1 
<UNK> <UNK> 
Updated travis config 
<UNK> <UNK> memory of memory of memory leak . 
update CHANGES 
Set version 0 . 4 . 7 
Updated README 
add invoker . properties 
Add Corey Downing to pairs 
Fixed broken test 
add cardview - v7 to BUCK BUCK r_android_library 12 
Modify MF example MF <UNK> . launcher 
set version for release 
added io plugin for build 
Bump up version . 
add gitignore 
Fix <UNK> - shrinkwrap . json . json to match the npm - shrinkwrap . 
Updating to <UNK> 15 . 
