Delete ic_launcher . 
Updated FML to fix <UNK> <UNK> 
Ignore <UNK> files 
ignore Update ' modules / apps / collaboration / blogs / . 
Updating Alloy to rev . <UNK> 
Set properties for the pom 
Updated changelog 
travis test 
update <UNK> natives 
update changelog 
<UNK> <UNK> to singleTop 
Delete demo2 . gif 
Push version to 11243 . 
Add scope for gson scope 
ignore Update ' modules / apps / foundation / portal - remote / . 
Fix <UNK> <UNK> . 
Fix <UNK> <UNK> 
add STORM - 1248 to changelog 
update Wiki . txt 
update to latest release snapshot 
Add d for AsyncQueryHandler toString 
update javac to 1 . 5 
Fix <UNK> <UNK> 30 30 
update to latest support libraries 
add pull . sh 
Fix <UNK> <UNK> <UNK> . 
Make ApplicationMasterPrivateAccess static to static 
add readme 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / marketplace / . 
update gradle to 2 . 2 . 2 
Fix <UNK> <UNK> 
<UNK> <UNK> <UNK> 
Fix <UNK> . DefaultBehavior . 
<UNK> <UNK> to <UNK> 
update libdatabase_sqlcipher jar 
Fix Basic Basic Basic 
Remove <UNK> <UNK> 
Fix typo in CommunicationIOS . 
ignore Update ' modules / apps / web - experience / journal / . 
Fix <UNK> . options ( ) 
ignore Update ' modules / apps / collaboration / flags / . 
LPS - <UNK> Move test to the test 
upgraded netty to 4 . 0 . 30 
Prepare next development version . 
update gradle - wrapper . jar 
add <UNK> . md 
Make <UNK> <UNK> <UNK> <UNK> . 
Fix <UNK> 
revert jar to <UNK> 
Add gif for zoom sample 
Add gitignore 
add NOTICE . txt 
Remove conf from . 
updated ChangeLog 
remove unused <UNK> 
update jetbrains . dic 
<UNK> <UNK> ( ) 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / contacts / . 
fixed test data 
Fixed <UNK> <UNK> 
<UNK> <UNK> 
Delete mconftec . png 
Move <UNK> to src / main / java / java / java / java / java / java / java / java / java / java / java / java / java / java / java / java / java / java / java / java / java /
Fix UIExplorerIntegrationTests / <UNK> in IntegrationTests . 
add grails - resources to grails - scripts 
Fix typo in muc - server - form - form - form . 
Remove TBD TBD <UNK> from core - object . 
Remove TODO 
Add jar for the <UNK> 
add README 
Bump common ref . 
ignore Update ' modules / apps / collaboration / message - boards / . 
HHH - <UNK> <UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / marketplace / . 
<UNK> <UNK> <UNK> 
Make LogASTTransformTest class 
<UNK> <UNK> to <UNK> 
Fix <UNK> <UNK> <UNK> 
updated <UNK> images 
update jetbrains . dic 
update CHANGES 
updated <UNK> course 
Add maven - maven plugin 
Remove TODO 
Fix <UNK> <UNK> <UNK> 
update changelog 
update README 
update filter 
Fix task wrapper . 
ignore Update ' modules / apps / foundation / map / . 
update samples 
Use the <UNK> <UNK> version of the <UNK> . 
update deskshare - 0 - 0 . 9 . 
bump version of os - maven - plugin to 1 . 2 . 3 . 
Add <UNK> operation icons . 
Remove unused image . 
update gitignore 
<UNK> version 1 . 1 . 4 
add README / Contents / Contents / Contents 
<UNK> <UNK> . getResourcePath + request 
index <UNK> 
add <UNK> ( ) to the build . gradle 
update to latest android widget plugin 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> 
Fix <UNK> test 
Add Bitdeli image 
add test 
LPS - <UNK> update jar 
ignore Update ' modules / apps / collaboration / microblogs / . 
Updated library reference 
<UNK> <UNK> when <UNK> is <UNK> . 
updated index 
update es / upstream to fix <UNK> tests 
Fixed test data 
add STORM - 1176 to changelog 
update changelog 
Remove import 
Fix typo in apache - camel - converters - converters 
Added server module to the build . 
update wrapper version 
ignore Update ' modules / apps / foundation / portal - search / . 
update push notifications 
ignore Update ' modules / apps / web - experience / asset / . 
Remove newline 
update travis config 
update server - metrics to 0 . 2 . 5 
Updated <UNK> to <UNK> <UNK> <UNK> . 
text text to text <UNK> 
Fix <UNK> - core 
ignore Update ' modules / apps / collaboration / notifications / . 
add 146 SNAPSHOT to the build . 
Remove <UNK> . 
<UNK> <UNK> <UNK> <UNK> 
updated studio 
ignore Update ' modules / apps / foundation / web - proxy / . 
bump version to 0 . 8 . 0 - SNAPSHOT 
add STORM - 563 to CHANGELOG 
update README . md 
remove unused <UNK> 
Remove apply plugin from perf . gradle 
update AndroidEmojiInput 
updated version 
Fix <UNK> <UNK> <UNK> 
Fix build 
add * . 
update sandbox to use 2 . 0 - SNAPSHOT 
<UNK> the <UNK> <UNK> 
Remove DIR lein compile <UNK> 
update linux natives 
update library to <UNK> 
Fix typo 
ignore Update ' modules / apps / foundation / frontend - js / . 
Fix <UNK> <UNK> 
remove unused variable 
update gitignore 
Remove unused - server 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
updated README TXT 
update version to 1 . 2 . 0 - usergroups - SNAPSHOT 
Fixed <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / asset / . 
Fix @ @ Array . 
gitignore 
update README . md 
ignore Update ' modules / apps / collaboration / document - library / . 
update to latest support libraries v23 . 3 . 0 
Use the <UNK> of the endShape closeShape 
update library version 
update version to 0 . 21 . 0 - rc2 - SNAPSHOT 
Add lucene - version to docs 
Updated changelog 
update Denis . xml 
Make customer__resolvedKey private <UNK> 
update contributors 
added gremlin gremlivich image . 
ignore Update ' modules / apps / foundation / portal / . 
ignore Update ' modules / apps / screens / . 
Add a @ deprecated annotation to the JSDocInfo . 
update classworlds version 
update to latest android 2 . 0 . 4 
Push version to 185 - beta4 . 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Fix <UNK> <UNK> 
<UNK> - <UNK> - <UNK> <UNK> <UNK> tests 
updated studio 
ignore Update ' modules / apps / foundation / frontend - js / . 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
ignore Update ' modules / apps / foundation / roles / . 
Updated wildfly pom 
Fix <UNK> <UNK> 
added exit for 0 . exit 
update README 
<UNK> <UNK> <UNK> <UNK> 
Fixed typo . 
ignore Update ' modules / apps / web - experience / export - import / . 
update build tools to 24 . 0 . 3 
Fix <UNK> <UNK> <UNK> to conf 
Fix <UNK> <UNK> . 
update sunos natives 
update delete delete 
Fixed <UNK> cache . 
changed <UNK> to correct <UNK> 
<UNK> <UNK> - dom 
updated <UNK> course 
Added licenses for <UNK> 
Updated to version 1406000 " 1406000 package 
updated ant - antlr . 
LPS - <UNK> prep next , use latest 
Remove <UNK> <UNK> . 
Updated changelog 
Add ca3fe55c28a6aa6ca662d78cf5d3662a9e9d70ce 0 . 4 to . 
update jikes 
ignore translator - web 1 . 0 . 3 prep next 
update sugar jar 
Make ClientProxyFuture private private 
Updated <UNK> <UNK> asset . 
ignore Update ' modules / apps / foundation / portal - configuration / . 
set version to 1 . 9 . 0 
Ignore class files 
<UNK> <UNK> <UNK> <UNK> 
LPS - <UNK> - Remove empty file 
<UNK> focus <UNK> 
update version to 1 . 2 
update gradle plugin 
LPS - <UNK> Move ModuleFrameworkImpl to src - impl 
updated version 
add target 
Fix <UNK> <UNK> <UNK> 
prohibit prohibit <UNK> " 
Add logo . 
<UNK> <UNK> tests 
<UNK> <UNK> to <UNK> 
LPS - <UNK> Remove new property 
Fixed test data 
Remove println 
Fix <UNK> <UNK> 
Fix vectorDrawables - <UNK> 
update notes to reflect release 
<UNK> <UNK> 
Fix <UNK> <UNK> 
Add Singleton class for Singleton class 
<UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
fixed <UNK> <UNK> ( PY - <UNK> ) 
Make uploadMavenCentral task , that encompasses other tasks 
Updated changelog 
Prepare version 23 - beta2 . 
ignore Update ' modules / apps / foundation / portal / . 
update es / upstream to fix <UNK> tests 
add STORM - 993 to changelog 
Add missing module for artifact 
Add junit to MoreFilesIntegrationTest MoreFilesIntegrationTest <UNK> 
update gitignore 
add <UNK> 
Fix <UNK> <UNK> <UNK> 
Updated changelog 
ignore Update ' modules / apps / web - experience / iframe / . 
Updating to version 2 . 9 . 0 
bump to version 1 . 0 . 9 
fix <UNK> <UNK> 
<UNK> <UNK> <UNK> 
Fix <UNK> <UNK> for <UNK> . 
update to latest android v1 . 0 . 0 
updated screenshot 
<UNK> <UNK> 
update Dockerfile 
Prepare next development iteration 
<UNK> <UNK> . sh 
add atlassian - ide . 
bump version to 0 . 8 . 0 - SNAPSHOT 
Updated logo 
pre - integration module for package - integration phase 
fix Process Process <UNK> " 
Add <UNK> <UNK> natives . 
Add NULL NULL to convertAudioPortConfigFromNative <UNK> 
Regenerate - <UNK> - <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / web - proxy / . 
update framework to android - 12 
update VERSION . txt 
<UNK> <UNK> <UNK> 
add STORM - 1592 to changelog 
update es / upstream to fix <UNK> tests 
ignore Update ' modules / apps / static / osgi / . 
ignore Update ' modules / apps / collaboration / blogs / . 
ignore Update ' modules / apps / web - experience / export - import / . 
<UNK> <UNK> to refdocs 
Prepare next release v1 . 85 . 2 - SNAPSHOT 
Add image for raw master 
<UNK> . sh 
<UNK> - dependent - build - build - build - build - build - build 
update linux - ppc64 natives 
add <UNK> - adjoint to spelling . txt 
add project files 
update linux natives 
Added large_record_larger test 
update javarepl projectVersion to projectVersion projectVersion . 
add STORM - 789 to changelog 
added <UNK> <UNK> <UNK> 
updated CHANGES . txt for <UNK> release 
Remove unused import 
<UNK> <UNK> <UNK> 
Fix <UNK> for <UNK> 
ignore Update ' modules / apps / web - experience / asset / . 
gitignore 
Updated FML 
Remove <UNK> <UNK> 
doSetText text <UNK> ( ) in <UNK> ( ) 
updated gant 
Fix <UNK> <UNK> . 
update CMakeLists . hpp list 
update travis 
Fix <UNK> <UNK> 
bump to version 2 . 0b6 
<UNK> <UNK> 
LPS - <UNK> - <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / recent - documents / . 
Update <UNK> - tools - 21 . 1 . 
Add Matija AUTHORS for AUTHORS 
Add pinot . 
Add missing image 
Fix <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
setting version to 1 . 0 . 134 
LPS - <UNK> Remove unused submodule 
update to latest android 0 . 1 . 1 
update dexguard - project . 
ignore Update ' modules / apps / collaboration / mentions / . 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
ignore Update ' modules / apps / collaboration / ratings / . 
Remove CLI <UNK> from pom . xml 
<UNK> - <UNK> <UNK> <UNK> 
<UNK> <UNK> 
ignore Update ' modules / apps / foundation / petra / . 
Fix typo 
updated sewerage sewerage images 
Move <UNK> to correct location 
MinecraftForge / FML @ 0d810c01fab99ac491c2277097a4198518fe6c75 <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
add . 
Updating Alloy to rev . <UNK> 
Fix <UNK> <UNK> 
Remove debug <UNK> 
Updating Alloy to <UNK> ; LPS - <UNK> 
update play version 
setting version to 1 . 0 . 146 - SNAPSHOT 
Updated <UNK> 
update native 
update app . properties to 0 . 6 - groovy - 1 . 7 - SNAPSHOT 
ignore Update ' modules / apps / foundation / portal - template / . 
<UNK> <UNK> <UNK> <UNK> 
Fix typo 
update applet with <UNK> <UNK> 
<UNK> <UNK> . onDestroyBubble ( ) . 
ignore Update ' modules / apps / web - experience / journal / . 
fixed <UNK> <UNK> 
<UNK> <UNK> 
Add <UNK> jar 
add testCoverageEnabled true to proguard 
<UNK> <UNK> and <UNK> 
add database - migration to BuildConfig 
update jetty - test - helper to 2 . 9 
Fix <UNK> <UNK> <UNK> 
Reduce the <UNK> of the test 
Updated DecisionTreeTrainer the DecisionTreeTrainer all to <UNK> 
updated <UNK> icon 
Updating Alloy to rev . <UNK> 
Upgraded Wrapper 
fixed <UNK> ( ) 
ignore Update ' modules / apps / collaboration / invitation / . 
ignore Update ' modules / apps / web - experience / site - navigation / . 
Reduce <UNK> to oraclejdk8 jdk - <UNK> 
update submodule to latest branch 
fix <UNK> - <UNK> - <UNK> 
Updated image 
Add folder for the visualization . 
<UNK> <UNK> 
update demo 
ignore Update ' modules / apps / sync / . 
ignore Update ' modules / apps / collaboration / wiki / . 
update releaseCompile to latest version 
Fix typo 
ignore Update ' modules / apps / foundation / portal - scheduler / . 
Add gitignore 
ignore Update ' modules / apps / marketplace / . 
updated screenshot_overview 
update version 
LPS - <UNK> ( WEB ) Move js files 
Updated README 
ignore Update ' modules / apps / foundation / portal - search / . 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / adaptive - media / . 
Updated logo 
add margin to <UNK> 
ignore Update ' modules / apps / foundation / frontend - editor / . 
upgraded to <UNK> . 4 . 2 
Use library <UNK> 
add STORM - 555 to CHANGELOG 
<UNK> version 0 . 4 . 54 
Add gitignore 
updated wiki 
Fix typo . 
add gitignore 
update ForgeGradle version 
Fix DrawerLayout <UNK> <UNK> <UNK> . 
Fix <UNK> <UNK> <UNK> image . 
gitignore gitignore 
add <UNK> 
ignore Update ' modules / apps / foundation / my - account / . 
Add jersey - Package to pom . xml 
setting version to 1 . 0 . 128 - SNAPSHOT 
add import 
Fix import 
ignore Update ' modules / apps / foundation / monitoring / . 
Fix <UNK> <UNK> 
update gitignore 
Add jQuery License to NOTICE 
Add AndroidManifest . xml 
<UNK> <UNK> to 0 . 0 . 0 
Fix <UNK> <UNK> 
<UNK> <UNK> . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Updated changelog 
Fix <UNK> <UNK> 
updated CHANGELOG . textile 
Fix <UNK> <UNK> 
Removed unused <UNK> jar 
Add CHANGELOG . md 
updated ChangeLog 
<UNK> travis 
Updated version for curator - x - bridge . 
Add missing import 
add missing icon 
Updated protoc 
update release release 
Prepare next development version . 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> . 
removed <UNK> <UNK> jar 
updated version 
update asm version 
added beatrix module 
<UNK> reference 
Added image1 image1 image1 
don ' t <UNK> <UNK> <UNK> 
Fixed <UNK> <UNK> 
update README to latest version 
update gradle plugin to 2 . 1 . 0 
ignore Update ' modules / apps / marketplace / . 
setting version to 1 . 0 . 77 
Add <UNK> image 
Updated default ppt <UNK> to <UNK> 
add STORM - 1269 to changelog 
ignore Update ' modules / apps / web - experience / layout / . 
update resourcePrefix . gradle to include <UNK> 
Smack 4 . 0 . 3 - SNAPSHOT 
Updated <UNK> libs 
update image for instructions 
Remove <UNK> from gitignore 
setting version to 1 . 0 . 132 
Move <UNK> to ja 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / notifications / . 
ignore Update ' modules / apps / collaboration / bookmarks / . 
Replace to_maven . sh 
update <UNK> to 0 . 90 . RC4 
<UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Fix <UNK> 
Updated version number to 5 . 6 . 3 - SNAPSHOT 
Remove unused <UNK> <UNK> 
Remove ApplicationInfo ApplicationInfo <UNK> 
update hbase_datastore jar 
Make Builder public to static 
Fix NPE 
Add image for preference sample 
setting version to 1 . 0 . 127 
update changelog 
updated orientdb - core - pom 
Updated changelog 
Fix the <UNK> . md 
Use travis - Pintegration - Pintegration 
add <UNK> performance fixes 
Fix SyncStorageEngine <UNK> 
Delete DemoApp . apk 
ignore Update ' modules / apps / foundation / configuration - admin / . 
<UNK> jps <UNK> 
Fix BluetoothDeviceProfileState <UNK> <UNK> 
fixed <UNK> <UNK> ( PY - <UNK> ) 
ignore Update ' modules / apps / foundation / petra / . 
CHANGES CHANGES . txt for FairScheduler Ozawa . 
<UNK> unexpected error . 
Add GibberishProtocolProviderServiceLick GibberishProtocolProviderServiceLick to the testing 
Fix <UNK> <UNK> 
Fix typo 
<UNK> - <UNK> , <UNK> make_binary_release - Ppyspark <UNK> 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
<UNK> travis 
update macosx bullet natives 
<UNK> <UNK> to prn 
ignore Update ' modules / apps / collaboration / bookmarks / . 
ignore Update ' modules / apps / foundation / portal - store / . 
Fixed package name 
ignore Update ' modules / apps / collaboration / document - library / . 
ignore Update ' modules / apps / foundation / portal - template / . 
<UNK> <UNK> - map are <UNK> - map 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Built the latest snapshot 
<UNK> <UNK> 5 . 
LPS - <UNK> moves icon 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - css / . 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Prepare next release v1 . 90 . 1 - SNAPSHOT 
Add <UNK> <UNK> for binding 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Add <UNK> . version file 
updated truth version 
update to latest 2 . 0 . 0 
update project - plugins sdocbook 
update <UNK> version 
Add image for preference sample 
Fix <UNK> <UNK> . 
setting version to 1 . 0 . 127 - SNAPSHOT 
Download apk directly from here 
Updated CHANGELOG . textile . 
Use new container 
update README 
ignore Update ' modules / apps / sync / . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / journal / . 
LPS - <UNK> Remove <UNK> . lar 
Added Artur Biesiadowski to the project 
<UNK> <UNK> <UNK> <UNK> 
Make <UNK> executable 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
ignore Update ' modules / apps / foundation / plugins - admin / . 
ignore Update ' modules / apps / foundation / configuration - admin / . 
Fix <UNK> <UNK> . 
JAL - 35 Add image notes to non - proprietary licenses 
Updated irc - api - api - 1 . 0 . 2 to irc - api . 
ignore Update ' modules / apps / web - experience / asset / . 
Remove <UNK> <UNK> 
add <UNK> to StorageServiceMBean service 
ignore Update ' modules / apps / marketplace / . 
ignore Update ' modules / apps / web - experience / trash / . 
Remove unused reference 
removed support - support - v4 version 
ignore Update ' modules / apps / collaboration / directory / . 
Fix <UNK> <UNK> <UNK> 
bump deb version 
LPS - <UNK> Fix <UNK> 
update travis to latest version 
update curr . properties 
ignore Update ' modules / apps / collaboration / notifications / . 
removed unused <UNK> <UNK> 
LPS - <UNK> Remove unused file 
<UNK> <UNK> 
remove <UNK> 
Make XMMapFSDirectory public 
ignore Update ' modules / apps / web - experience / export - import / . 
Fix dependency for junit - dep 
<UNK> <UNK> . configure ( ) . 
Fix typo in attach pom . xml 
Add framework to the framework <UNK> 
ignore Update ' modules / apps / foundation / portal - security / . 
<UNK> <UNK> . kl 
Updating to <UNK> 2 . 1 . 0 - RC 
<UNK> <UNK> 
Updated README 
ignore Update ' modules / apps / foundation / frontend - js / . 
ignore Update ' modules / apps / collaboration / wiki / . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
add icon for <UNK> 
Updated changelog 
add FrameworkDetectionExcludesConfiguration . append ( ) for idea <UNK> 
Fixed the bug in menu 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
setting version to 1 . 0 . 147 
ignore Update ' modules / apps / collaboration / message - boards / . 
set findbugs findbugs for sqlbrite 
update jsminim jar 
Add <UNK> to svm 
ignore Update ' modules / apps / web - experience / site - navigation / . 
ignore Update ' modules / apps / collaboration / item - selector / . 
Updating netty to 4 . 0 . 34 
Fix typo 
Make <UNK> executable 
update README 
<UNK> - execheader . sh . trampoline - jar 
update AUTHORS . md 
add prolificinteractive . md 
LPS - <UNK> Remove unused jquery 
Updated readme 
ignore translator - web 1 . 0 . 1 prep next 
Prepare next development version . 
updated example image . 
update to latest release <UNK> 
Delete ic_launcher_gibberbot . 
Add libpng libpng to the tools <UNK> . 
Add gitignore 
Remove unused test 
update gradle plugin to 2 . 2 . 1 
add IDE files 
<UNK> the <UNK> <UNK> <UNK> to <UNK> . 
Updated README 
update minecraftforge_credits 
Added README 
ignore Update ' modules / apps / foundation / configuration - admin / . 
ignore Update ' modules / apps / web - experience / journal / . 
Add dummy a new dummy 
update wrapper version 
Add Java compile task for Java specifies its <UNK> 
<UNK> <UNK> <UNK> 
gitignore log 
Fix <UNK> <UNK> <UNK> 
add requirements 
<UNK> <UNK> to <UNK> <UNK> 
Fix <UNK> <UNK> . 
Add irc notifications to travis 
Built the latest snapshot 
ignore Update ' modules / apps / foundation / contacts / . 
Add missing <UNK> to the <UNK> 
missing import 
Ignore nbactions nbactions . 
ignore Update ' modules / apps / collaboration / item - selector / . 
ignore Update ' modules / apps / web - experience / layout / . 
Prepare next development iteration 
update Readme 
Add <UNK> error 
LPS - <UNK> - Remove empty file 
Fix systemProperties systemProperties systemProperties 
update VERSION . txt 
add cloud - aws module 
Make <UNK> executable 
add mode 
update changelog for STORM - 549 . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> 
add jitsi - local . 
<UNK> <UNK> . java ( ) 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Fix <UNK> <UNK> 
removed unused test 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
ignore classpath files . 
ignore Update ' modules / apps / collaboration / bookmarks / . 
Make uploadMavenCentral task , that encompasses other tasks 
remove unused SuppressWarnings . 
update README . md 
Fix <UNK> <UNK> type . 
ignore Update ' modules / apps / web - experience / journal / . 
add README . markdown 
Remove redundant <UNK> 
made getParentElement public 
Fix <UNK> . 
Add CCCC - upgrade to readme 
<UNK> javadoc 
add GNU to README 
add README 
Add ColdFusion for <UNK> <UNK> 
Updated README 
ignore Update ' modules / apps / foundation / portal - security / . 
Remove <UNK> <UNK> from RecyclerViewBackedScrollView . android . js 
add STORM - 1414 to CHANGELOG 
Add codecov to travis 
Updated changelog 
update favicon 
Add Repeat Repeat to Texture <UNK> . 
update to latest android 2 . 0 . 2 
update to latest android 0 . 1 . 1 
add <UNK> to the 20 
Updated Python_examples CMakeLists to fix <UNK> <UNK> 
Push version to 13 - beta5 , 11248 - 11248 . 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / blogs / . 
Add build folder to . 
add mode 
paused paused ( ) in <UNK> 
ignore Update ' modules / apps / web - experience / journal / . 
update travis config 
update ext . gradle to 28 . extraVersion 
setting version to 1 . 0 . 105 - SNAPSHOT 
Add allow_non_emergency_calls_in_ecm_bool allow_non_emergency_calls_in_ecm_bool allow_non_emergency_calls_in_ecm_bool to CarrierConfigManager CarrierConfigManager . 
<UNK> <UNK> . 
update <UNK> to 1 . 2 . 0 
update spring gif 
Remove unused compilationFailures <UNK> 
Fix typo 
ignore configured - test - suite - uber / configured 
update coverage 
update lint 
Added STORM - 501 to changelog 
ignore registry - api 1 . 0 . 0 prep next 
Updated README 
update circle . sh 
Make ArgumentMatcherTest public to <UNK> 
Make <UNK> executable 
Fix <UNK> <UNK> <UNK> 
Prepare next release v1 . 87 . 3 - SNAPSHOT 
Fix <UNK> 
update README 
ignore Update ' modules / apps / foundation / hello - world / . 
update changelog 
Add missing properties for presto - main 
SONAR - <UNK> add code for code 
update gradle build tools 
update todo 
Add javadoc . skip javadoc to the javadoc file . 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - js / . 
Remove unused <UNK> <UNK> 
update gradle plugin version 
Fix <UNK> test 
<UNK> <UNK> 
update to latest 2 . 1 - rc6 
Remove <UNK> from the config 
Ignore reports 
Ignore the libs of the Eclipse system system system system system system system system system system system system . 
update README . md 
Remove unused package file 
Fix import 
update gradle plugin 
update <UNK> to 1 . 4 . 0 - RC4 
Updated changelog 
Fixed a bug in the launcher . 
to 1 . 1 - rc - 1 
Updated changelog 
ignore Update ' modules / apps / collaboration / item - selector / . 
update support to 23 . 4 . 0 
update minimal - json to 0 . 9 . 2 
bump version 
update to latest android 24 . 0 . 2 
add opentripplanner - analyst module 
<UNK> <UNK> <UNK> 
Fixed <UNK> <UNK> history 
<UNK> <UNK> 
add CHANGES . txt 
add npm logs 
Fix <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
Remove <UNK> . xml 
Update build tools to 21 . 0 . 1 . 
<UNK> <UNK> 
<UNK> <UNK> <UNK> 
Fix proguard <UNK> 
update maven - statcvs - plugin to 2 . 7 
updated <UNK> - macosx and windres - macosx and windres - macosx . 
add TODO for Neo4j overview diagram 
Remove <UNK> <UNK> from <UNK> 
add <UNK> jar 
<UNK> <UNK> 
LPS - <UNK> Remove unused file 
ignore Update ' modules / apps / foundation / portal - template / . 
add target target to gitignore 
Fix <UNK> <UNK> 
Add <UNK> <UNK> 
Fix check error 
parallel faunus parallel parallel 
Remove unnecessary call 
add <UNK> to the groovy 
<UNK> the <UNK> of the graphhopper . 
remove unused setBackground 
update libwebp 
ignore Update ' modules / apps / marketplace / . 
<UNK> <UNK> to <UNK> 
Updating Alloy to rev . <UNK> 
add UTF - 8 to the build . 
<UNK> the <UNK> 
update CONTRIBUTORS 
update art 
ignore Update ' modules / apps / web - experience / xsl - content / . 
<UNK> . yml 
Add <UNK> to <UNK> 
<UNK> <UNK> . 
Add missing <UNK> . txt 
Remove <UNK> 
ignore Update ' modules / apps / foundation / frontend - js / . 
<UNK> <UNK> 
ignore Update ' modules / apps / collaboration / document - library / . 
Remove email from closure - compiler . pom . 
Fix <UNK> <UNK> 
Fix <UNK> <UNK> . 
Added <UNK> image 
updated openpgp to latest - keychain 
ignore Update ' modules / apps / foundation / portal - security / . 
ignore Update ' modules / apps / web - experience / export - import / . 
Updated COPYRIGHT . txt 
LPS - <UNK> Add new <UNK> 
update 1400M . ini 
Add <UNK> - 1 . 7 . 0 to okhttp - 1 . 7 . 0 
add example 
Added missing test file 
update examples . zip 
add org - gradle - gradle 
add screenshots for lt omegat_small 
LPS - <UNK> prep next , use latest 
Updating maven version to 2 . 0 . 8 
Updated logo 
setting version to 1 . 0 . 116 - SNAPSHOT 
LPS - <UNK> Remove unnecessary line 
Updated changelog 
Updated README 
add <UNK> <UNK> 
Bumping rest - client submodule 
Here debug a debug a debug a CI a CI a CI a CI a CI 
add note to revisions 3 . 0a4 ( REV 0231 0231 2014 ) 
Prepare next development version . 
Fix <UNK> the provided 
<UNK> <UNK> 
Fix <UNK> test 
ignore Update ' modules / apps / foundation / portal - settings / . 
Add a @ implements < IArrayLike < IArrayLike < string to browser . 
add jps - sources to jps <UNK> of <UNK> 
update version to 7 . 4 
<UNK> - <UNK> - <UNK> - accuracy test jar 
Fix <UNK> <UNK> 
update travis config 
updated README 
Add . . 
Remove unused <UNK> 
Remove newline 
add STORM - 1145 to changelog 
Make <UNK> executable 
<UNK> <UNK> . debug ( ) 
Use <UNK> 
<UNK> <UNK> to <UNK> 
<UNK> travis 
Updated version to 7 . 1 . 2 
Add protobuf jar 
Updated <UNK> <UNK> 
update README 
add otp . jar 
Add hdpi icon 
Use the <UNK> of the travis 
Add gitignore 
Updated <UNK> jar 
ignore Update ' modules / apps / foundation / hello - world / . 
Fix <UNK> <UNK> 
update sample version 
update android . properties to <UNK> 
ignore Update ' modules / apps / collaboration / mentions / . 
Updating Alloy to rev . <UNK> 
Ignore gradle files 
<UNK> <UNK> 
ignore Update ' modules / apps / foundation / my - account / . 
ignore Update ' modules / apps / ip - geocoder / . 
update javadoc . sh 
Remove <UNK> 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / announcements / . 
Add apk 
Add break to MainActivity MainActivity 
Add disklrucache disklrucache to the gradle . 
Fixed typo 
Fix <UNK> clear clear . 
add <UNK> to gitignore 
Updated README 
Use <UNK> <UNK> 
Fix <UNK> <UNK> 
Add <UNK> <UNK> natives . 
update slf4j - api to 1 . 7 . 6 
Add image for <UNK> and <UNK> 
MinecraftForge / FML @ 7eb36a1481aea9f68fa46bc199195769b27d904b <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
Add <UNK> to <UNK> . 
ignore Update ' modules / apps / web - experience / layout / . 
add UTF . build . sourceEncoding to pom 
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
<UNK> <UNK> <UNK> <UNK> 
Remove unused image 
Remove unnecessary line . 
update android 14 to API 
updated RELEASE - NOTES . 
add distribution to README 
ignore Update ' modules / apps / foundation / contacts / . 
<UNK> <UNK> <UNK> 
update version to 6 . 13 
Add certain only to <UNK> performance <UNK> 
Add <UNK> to the travis 
ignore Update ' modules / apps / collaboration / document - library / . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Remove notification . mp3 
Updated changelog 
update applet zip 
Add <UNK> . png 
LPS - <UNK> Remove unused file 
Remove <UNK> - sign - compare - compare - compare - compare . 
Add @ noalias noalias to externs . 
<UNK> <UNK> 
help topic ( PY - <UNK> ) 
ignore Update ' modules / apps / collaboration / directory / . 
LPS - <UNK> Move icon 
ignore Update ' modules / apps / collaboration / quick - note / . 
<UNK> the <UNK> <UNK> <UNK> to <UNK> . 
ignore Update ' modules / apps / sync / . 
Fix typo . 
Remove maven . version from pom . xml 
Fix <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> 
Updated changelog 
update Changes 
updated svm 
update <UNK> 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> . RIGHT p p . RIGHT 
update gitignore 
ignore Update ' modules / apps / collaboration / document - library / . 
gitignore gitignore 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
<UNK> <UNK> . 
DO NOT MERGE - <UNK> " <UNK> " <UNK> " 
Fix <UNK> <UNK> 
<UNK> <UNK> . xml 
<UNK> <UNK> . app 
line line 
updated CHANGES . txt 
Add * . 
Add a gitignore 
Move VectorEnabledTintResources VectorEnabledTintResources VectorEnabledTintResources VectorEnabledTintResources <UNK> to the same <UNK> . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
<UNK> <UNK> . 
add . 
Remove mavenLocal mavenLocal mavenLocal 
ignore Update ' modules / apps / foundation / portal - settings / . 
update gradle plugin version 
Bump common ref . 
<UNK> bundle to org . neo4j . management < org . namespace to <UNK> with <UNK> <UNK> . 
<UNK> <UNK> 
updated quaqua jar 
Updated version 
ignore Update ' modules / apps / web - experience / product - navigation / . 
remove unused call 
fixed <UNK> <UNK> <UNK> ( ) 
add blaze_exit_code to <UNK> 
Updated gradle wrapper to version 2 . 2 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / announcements / . 
Remove unused <UNK> <UNK> 
update travis 
ignore Update ' modules / apps / foundation / users - admin / . 
Fix <UNK> <UNK> <UNK> 
add deploy . 
ignore Update ' modules / apps / foundation / login / . 
ignore Update ' modules / apps / foundation / users - admin / . 
add demo . gif 
Fix README 
LPS - <UNK> Remove unused <UNK> 
Delete jsshellhelper . pyc 
add 0 . 10 . 1 to CHANGELOG 
Push version to 13 . 1 . 1 . 
updated asm4 jar 
Fix <UNK> - R . 
Fixing transitive - ness of provided 
Prepare release v1 . 6 . 1 
add dist to gitignore 
Make MockConfiguration public 
Remove step - builder from pom . xml 
<UNK> <UNK> 
LPS - <UNK> - <UNK> <UNK> - admin - admin - admin to portlet 
Updated changelog for release integration 
Updated README 
Ignore sublime . 
update gradle to 2 . 1 . 0 
<UNK> test 
add version to gitignore 
Added <UNK> image 
update darwin jar 
update gradle plugin version 
add STORM - 1170 to changelog 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / ratings / . 
LPS - <UNK> Move default default action 
Add <UNK> . ico 
LRQA - <UNK> Add set - sybase - charset to build - test . 
ignore Update ' modules / apps / foundation / monitoring / . 
updated ChangeLog 
Remove gant gant SNAPSHOT 
setting version to 1 . 0 . 141 
update cacheword to latest head 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / ratings / . 
Fixes the Windows binaries of the PortAudio <UNK> . 
Add <UNK> margin 
ignore Update ' modules / apps / foundation / portal - store / . 
Replace <UNK> <UNK> 
Add <UNK> . jar for <UNK> . 
Fix <UNK> <UNK> to optional 
update <UNK> to version 3 . 1 . 2 
Move videoplayer_activity layout to videoplayer_activity <UNK> . 
add hexagonal 
update WORKSPACE 
<UNK> <UNK> <UNK> <UNK> 
add break to css 
removed <UNK> - 3 . 4 . 5 . 
Fixes the <UNK> of the login bar when <UNK> is not <UNK> . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Updated <UNK> <UNK> to <UNK> <UNK> . 
update readme 
Bump common ref . 
Move <UNK> . lua to the test 
update CHANGES 
add npm - shrinkwrap . 
Make <UNK> executable 
Remove <UNK> . h import 
Updating Alloy to rev . <UNK> 
Add intrications to readme 
add TextPosition . aidl . api to TextPosition domain domain 
update demo 
Fix <UNK> <UNK> 
Updated jediterm jar 
Fix <UNK> <UNK> <UNK> 
add hgignore for <UNK> . 
updated release notes 
Fix <UNK> <UNK> 
update travis config 
update jar 
Make Evaluator protected 
Push <UNK> . 
Updated Note to 0 . 4 
add <UNK> gif 
Bump common ref . 
update es / upstream to fix <UNK> tests 
LRQA - <UNK> prep next , use latest 
<UNK> <UNK> . exe 
ignore Update ' modules / apps / web - experience / export - import / . 
remove restli - guice - bridge - bridge dependency 
<UNK> <UNK> preventing <UNK> . 
<UNK> <UNK> to 60 
updated <UNK> course 
Added close method for JSONSerializer <UNK> 
bumped parent version . 
ignore Update ' modules / apps / web - experience / trash / . 
LPS - <UNK> Remove <UNK> file 
ignore Update ' modules / apps / web - experience / rss / . 
<UNK> - <UNK> <UNK> library 
Fix the <UNK> for the samples . 
Remove println 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> version 
Remove unused README 
Updated library reference 
Updating Alloy to rev . <UNK> 
Updated COPYRIGHT . txt 
Updated changelog 
<UNK> cache 
MinecraftForge / FML @ 4a753227adb805d29f3bf245c3f8427193c35544 <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
Remove grailsAppName projectName <UNK> from _GrailsTest . groovy . classpath 
Updated <UNK> 
Fix <UNK> 
remove unnecessary str 
LPS - <UNK> Remove <UNK> <UNK> 
update gradle to version 2 . 0 . 0 
updated studio 
update gitignore 
<UNK> version 1 . 1 . 0 
Remove unnecessary assert 
Delete ic_action_import_export . 
Updated changelog 
<UNK> <UNK> . onActivityCreated ( ) 
Remove theme theme 
Fix <UNK> <UNK> <UNK> 
Fix build . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Update NOTICE 
Add missing @ Ignore for <UNK> 
ignore Update ' modules / apps / foundation / portal - lock / . 
ignore Update ' modules / apps / marketplace / . 
add STORM - 596 to changelog 
<UNK> <UNK> test 
Add <UNK> . 
update README to latest version 
ignore chat - web 1 . 0 . 1 prep next 
<UNK> collection <UNK> 
Reduce <UNK> test 
<UNK> <UNK> <UNK> <UNK> 
remove <UNK> <UNK> 
fix the build 
Fix test 
update multiwords . txt 
Fix <UNK> <UNK> <UNK> 
Remove unused import 
Fix <UNK> <UNK> 
<UNK> <UNK> 
<UNK> default to path 
update sqlite jar 
Prepare version 20 . 1 . 0 - beta2 . 
removed unused <UNK> 
update maven - release - plugin to 2 . 5 . 1 
<UNK> travis 
ignore Update ' modules / apps / web - experience / staging / . 
<UNK> <UNK> <UNK> <UNK> 
background background background background background 
Add <UNK> <UNK> images 
update to latest android android <UNK> 
ignore Update ' modules / apps / collaboration / message - boards / . 
LPS - <UNK> Add a boundingBox portlet for boundingBox - image - gallery - gallery - gallery - gallery - gallery 
Bump version number 
Fix <UNK> <UNK> <UNK> . 
Fix <UNK> <UNK> <UNK> 
add - maxsockets 3 . properties to the Jenkins list 
update sbt to 0 . 13 . 8 
update release notes 
Delete sample file 
update sample 
Fix <UNK> <UNK> 
update to latest v1 . 3 . 0 
Add javadoc to the javadoc build . 
add . 
<UNK> <UNK> to 80 80 80 80 80 80 80 60 <UNK> 
Updated version to 1 . 8 . 6 - SNAPSHOT 
Updated version to 4 . 0 . 0 . 
<UNK> <UNK> 
<UNK> <UNK> image . 
Fix <UNK> <UNK> 
<UNK> - reducer reducer reducer . asciidoc 
<UNK> - <UNK> - tests - all groovy - tests module 
ignore Update ' modules / apps / web - experience / asset / . 
Add configChanges android configChanges to AndroidManifest . xml 
<UNK> <UNK> . chromeLinuxTest check . 
add Larger dictionaries were to CHANGES . txt 
update junit4 - maven - plugin to 2 . 0 . 14 
Add mavenCentral ( <UNK> ) 
<UNK> <UNK> . 
<UNK> <UNK> 
add <UNK> images 
<UNK> <UNK> to <UNK> 
add release notes to docs 
Updated changelog 
ignore Update ' modules / apps / web - experience / asset / . 
update version to 84 = 84 
Remove newline 
Update trac trac to https 
ignore Update ' modules / apps / foundation / portal - lock / . 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> 
Remove unused files 
LPS - <UNK> Add build . xml 
add modality modalities 
<UNK> <UNK> . giveBack ( ) 
Added translation using Weblate ( <UNK> ) 
Remove <UNK> <UNK> 
MatrixVectorView has index error 
Add missing LOCAL_JNI_SHARED_LIBRARIES . 
Updated changelog 
<UNK> events <UNK> 
update iconics to latest version 
Fix <UNK> <UNK> 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / users - admin / . 
Add idea . properties 
removed lint - cli module 
Delete Logo . 
Bump version number 
update CHANGES . txt 
add changelog 
add against against Early 
ignore Update ' modules / apps / foundation / expando / . 
Modify submodules 
add * . 
<UNK> Makefile 
updated README 
ignore Update ' modules / apps / marketplace / . 
<UNK> <UNK> . parse ( ) in ImapStore . 
Updated <UNK> version . 
update to latest android 23 tools libraries 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Add guice dependency to pom . xml 
Prepare next development iteration 
add Substitute Substitute to <UNK> 
ignore Update ' modules / apps / web - experience / staging / . 
add sources for travis 
Remove unused <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> 
Add LOCAL_JAVA_LANGUAGE_VERSION 1 . 8 to <UNK> . 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
update win32 natives 
Delete xUtils - 2 . 5 . 5 . 
ignore Update ' modules / apps / web - experience / export - import / . 
Add art 
update examples 
Fix <UNK> 
add <UNK> windows 
ignore Update ' modules / apps / foundation / portal - cache / . 
Updated <UNK> to 2 . 8 . 2 
update README 
<UNK> scope to patch 
Remove unused variable 
ignore Update ' modules / apps / foundation / portal - store / . 
Updated gradle wrapper to 2 . 10 . 1 
ignore Update ' modules / apps / foundation / portal - settings / . 
fixed <UNK> <UNK> <UNK> ( IDEADEV - <UNK> ) 
LPS - <UNK> Add character to the character 
<UNK> <UNK> version 
Make img to <UNK> . 
ignore Update ' modules / apps / collaboration / wiki / . 
add README . md 
<UNK> <UNK> . RxCheckedTextView . 
Push version to 14 . 0 . 1 . 
update applet zip 
<UNK> <UNK> 
Remove unused files 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> . 
update close 
Add script to test 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / foundation / web - proxy / . 
add ISSUE_TEMPLATE . md 
Remove unused <UNK> <UNK> 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Move <UNK> to <UNK> 
update win32 - x86 natives 
updated demo2 
Remove unused <UNK> 
add README . rdoc 
update changelog 
Make <UNK> executable 
Updated changelog 
add readme 
update demo 
Remove import from Constants . 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Make <UNK> . init ( ) IOException IOException IOException IOException IOException IOException IOException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException TTransportException . 
update reference for <UNK> 
updated manual 
ignore Update ' modules / apps / web - experience / site / . 
Add @ Deprecated annotation 
ignore Update ' modules / apps / foundation / frontend - js / . 
update Roadmap 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - js / . 
Fix <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
Fix - driver - jdbc - jdbc - jdbc - jdbc - jdbc 
Add myself for jdk8 
setting version to 1 . 0 . 9 
Updated sample APK . 
<UNK> test 
updated <UNK> icon 
Add log4j - log4j scope to log4j . 
Push <UNK> . 
Fix <UNK> <UNK> 
Fix <UNK> <UNK> 
Add <UNK> to RCTTextViewManager 
add communicator - communicator sip 
<UNK> <UNK> ( ) in DBTCPConnector 
bump version to 0 . 6 . 1 - SNAPSHOT 
add Protocol 
Add note to README 
ignore Update ' modules / apps / foundation / frontend - theme / . 
JodaTime cvsignore tzdata . 
add master for <UNK> 
<UNK> <UNK> <UNK> 
Fix AppleBundle <UNK> <UNK> in AppleBundle . 
ignore Update ' modules / apps / foundation / portal - remote / . 
Add Lexer <UNK> to Lexer <UNK> <UNK> 
Set formal_target_type <UNK> to formal_target_type 
<UNK> <UNK> for encoding 
ignore Update ' modules / apps / collaboration / item - selector / . 
<UNK> <UNK> 
update gradle to version 2 . 0 . 0 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Updated SwaggerSpec version 
ignore Update ' modules / apps / foundation / portal - search / . 
<UNK> <UNK> <UNK> 
Add org . jooq . ScalaGenerator . ScalaGenerator name to jOOQ - scala 
Remove <UNK> <UNK> <UNK> 
Fix typo 
Fix <UNK> <UNK> . 
ignore Update ' modules / apps / collaboration / message - boards / . 
update CHANGES 
<UNK> <UNK> <UNK> 
prohibit prohibit Verfassungsschuss " N N " " 
LPS - <UNK> Add missing dynamic option 
Add <UNK> to run_comparison print_stats . 
Updated gradle wrapper to version 2 . 11 
Updated changelog for STORM - 864 . 
Remove jar 
update netty version . 
update gradle to version 2 . 0 . 0 
add openjdk7 to travis 
<UNK> <UNK> 
<UNK> <UNK> ' s <UNK> 
add atlassian xml 
<UNK> <UNK> 
ignore Update ' modules / apps / collaboration / blogs / . 
<UNK> <UNK> <UNK> <UNK> 
help topic ( PY - <UNK> ) 
<UNK> <UNK> 
Fix typo 
update README 
Set <UNK> version 
Remove redundant dependency 
LRQA - <UNK> Add test . txt 
Remove launchMode launchMode launchMode 
ignore Update ' modules / apps / web - experience / rss / . 
Updated CHANGES 
update example 
ignore Update ' modules / apps / collaboration / document - library / . 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> to Xmx2g Xmx2g <UNK> 
updated studio 
ignore Update ' modules / apps / foundation / contacts / . 
update CHANGELOG 
<UNK> <UNK> . 
LPS - <UNK> - <UNK> <UNK> <UNK> counters counters counters counters counters counters <UNK> permissions 
update linux - x86 natives 
update gitignore 
Make <UNK> . 
updated OrangeExtensions jar 
Remove unnecessary @ Override annotation 
Add jar for <UNK> 
Updated <UNK> image . 
Fix <UNK> <UNK> 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Updated <UNK> icons 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Add CUSTOM_DEBUG_KEYSTORE_PATH to <UNK> <UNK> 
updated CHANGES 
Updating Alloy to 2 . 0 . x <UNK> 
update to latest support <UNK> 6 . 1 . 22 
SystemApi TranslucentConversionListener 
Fix test 
Updated <UNK> <UNK> to <UNK> 
ignore Update ' modules / apps / foundation / portal - store / . 
update LICENSE 
Fix typo 
Set <UNK> version to VERSION_1_7 . 
Move library_jsoup_strings library_jsoup_strings library_jsoup_strings library_jsoup_strings library_jsoup_strings <UNK> 
update <UNK> to 4 . 5 . 1 
bump version 
Fix <UNK> <UNK> 
Add image for <UNK> 
Added translation using Weblate ( <UNK> ) 
LPS - <UNK> update jar 
Add finalName - geocoder finalName 
ignore Update ' modules / apps / collaboration / bookmarks / . 
update <UNK> to 2 . 1 . 2 
Move V20160908172551__multiple_refunds_254 . sql to V20160908172551__multiple_refunds_254 . sql 
Fix <UNK> <UNK> 
Add missing <UNK> to the reset 
LPS - <UNK> Remove unnecessary jdbc org . springframework . jdbc . LazyConnectionDataSourceProxy . jdbc . LazyConnectionDataSourceProxy . jdbc . LazyConnectionDataSourceProxy . jdbc . LazyConnectionDataSourceProxy . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc . jdbc .
update parent - parent to 2 . 0 . 5 
add missing image 
<UNK> the <UNK> of the samples 
Bump common ref . 
LPS - <UNK> Fix <UNK> 
Updated <UNK> 
Updated README 
update NEWS 
ignore Update ' modules / apps / foundation / frontend - editor / . 
remove unused ZLTextView . 
ignore Update ' modules / apps / foundation / users - admin / . 
<UNK> <UNK> 
Add apk for sample 
add STORM - 566 to changelog 
ignore Update ' modules / apps / foundation / xstream / . 
Fix <UNK> <UNK> <UNK> 
add missing 1 . 2 
update release - 0 . 142 . rst 
Updated library reference 
<UNK> <UNK> . 
<UNK> <UNK> 
update <UNK> versions 
Add <UNK> Storehaus client 
Fix <UNK> <UNK> 
Fix cat test 
<UNK> jdk to oraclejdk8 jdk 
ignore Update ' modules / apps / sync / . 
update code 
Updating Alloy to 2 . 0 . x <UNK> 
ignore Update ' modules / apps / marketplace / . 
ignore Update ' modules / apps / web - experience / staging / . 
Updating the version number to 22 . 0 . 1 
HHH - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
add * target to gitignore 
Reduce <UNK> to startParameter with <UNK> 
<UNK> - metawiki - metawiki . sh . JDBCImporter . JDBCImporter to mysql - metawiki . 
update compile - testing to 0 . 2 
Fix camel - saxon JMS 
Add <UNK> . gz 
Updates the <UNK> background icon . 
Remove unused <UNK> . py 
Make size to <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - settings / . 
update guava to latest version 
update <UNK> 
Add filedownload_sample_description . png 
Updating Alloy - rev . <UNK> 
Modify bbb - demo / README2 / README2 / README2 / README2 / README2 / README2 / README2 / README2 / README2 / README2 / README2 / README2 / README2 / README2 /
ignore Update ' modules / apps / web - experience / rss / . 
Fix <UNK> <UNK> 
Updated version 
Use the latest <UNK> jcenter jcenter . 
Fix <UNK> <UNK> . 
<UNK> <UNK> . default_expression ( ) 
<UNK> - - eval db for travis 
Ignore sdk / dist 
Updated changelog 
Updating Alloy to rev . <UNK> 
LPS - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> <UNK> - container 
update travis to support <UNK> release 
Updated changelog 
updated bigbluebutton logo 
update screens 
setting version to 1 . 0 . 12 - SNAPSHOT 
ignore Update ' modules / apps / foundation / login / . 
add STORM - 515 to changelog 
add STORM - 464 to changelog 
add <UNK> 
bump version to 0 . 8 . 1 - SNAPSHOT 
add relativePath - parent relativePath to pom . xml 
ignore Update ' modules / apps / collaboration / wiki / . 
add STORM - 1087 to changelog 
Ignore * . 
active OSSMETADATA 
update <UNK> 
update version to 23 . 0 . 1 
Fix <UNK> <UNK> <UNK> 
add noinspection 
Add <UNK> <UNK> for <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / staging / . 
Fix typo 
Add screens screens 
<UNK> <UNK> version . 
Fix typo 
ignore Update ' modules / apps / foundation / portal / . 
Added <UNK> <UNK> 
Travis - based master 
<UNK> Travis to <UNK> 
<UNK> <UNK> <UNK> 
Fix <UNK> <UNK> . 
ignore Update ' modules / apps / collaboration / message - boards / . 
Fix <UNK> <UNK> 
Add Unsaved . 
update scalastyle - maven - plugin to 0 . 5 . 0 
add missing <UNK> to PythonAllTestsSuite 
<UNK> <UNK> <UNK> <UNK> 
add 286185 . txt for JSON 
gitignore 
ignore Update ' modules / apps / foundation / frontend - js / . 
add CMakeOverlay . txt to CMakeLists CMakeLists . txt of CMakeLists . 
fixed test data 
<UNK> <UNK> to all <UNK> 
Ignore Macs DS_Store files 
add image for instructions of <UNK> 
Fix <UNK> <UNK> 
Fix typo 
hgignore webrev webrev 
ignore Update ' modules / apps / foundation / my - account / . 
Updated gif 
update todo 
remove unnecessary <UNK> 
Updated changelog 
Add Travis config 
Fix <UNK> <UNK> . 
ignore Update ' modules / apps / sync / . 
update to latest release version 
added clover license 
<UNK> <UNK> . isCloseable ( ) 
update junit to 4 . 12 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
update es / upstream to fix <UNK> tests 
ignore Update ' modules / apps / collaboration / bookmarks / . 
<UNK> <UNK> . sh 
set version 
ignore Update ' modules / apps / web - experience / export - import / . 
Fix the <UNK> <UNK> to com . soundcloud . 
updated <UNK> image 
ignore Update ' modules / apps / collaboration / ratings / . 
ignore Update ' modules / apps / web - experience / layout / . 
Bumping rest - client submodule 
ignore Update ' modules / apps / collaboration / mentions / . 
<UNK> <UNK> <UNK> 
<UNK> the <UNK> <UNK> <UNK> to <UNK> . 
add STORM - 1862 to changelog 
<UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
Add ifndef _GNU_SOURCE to mt_adaptor _GNU_SOURCE <UNK> 
<UNK> <UNK> 
ignore Update ' modules / apps / web - experience / asset / . 
update gradle to version 1 . 2 . 3 
Fix <UNK> crash 
add <UNK> 
Add BASE_ETHERNET <UNK> to Protocol <UNK> <UNK> 
update NOTICE 
ignore Update ' modules / apps / sync / . 
ignore Update ' modules / apps / web - experience / asset / . 
Fix commons - collections scope 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / bookmarks / . 
setting version to 1 . 0 . 11 
Push version to 229 . 
<UNK> <UNK> . getFormat ( ) return Format return 
Add <UNK> jar 
updated codegen . xml 
ignore Update ' modules / apps / foundation / portal - security / . 
update <UNK> natives 
Add <UNK> to the build . 
add <UNK> 
ignore Update ' modules / apps / collaboration / blogs / . 
Add <UNK> 
Fix <UNK> <UNK> 
updated NEWS 
ignore Update ' modules / apps / foundation / frontend - css / . 
<UNK> <UNK> 
<UNK> <UNK> <UNK> 
Ignore files 
Add <UNK> <UNK> 
Built the latest snapshot 
bump version to 0 . 8 . 1 - wip3 - SNAPSHOT 
remove netty 
Remove ligradle ligradle ligradle ligradle file 
update jstun jar 
remove unused layout 
ignore Update ' modules / apps / foundation / portal - search / . 
add demo gif 
Fix <UNK> <UNK> 
Remove true 
LPS - <UNK> Remove unnecessary li 
ignore Update ' modules / apps / sync / . 
ignore Update ' modules / apps / web - experience / site / . 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
add Pes for <UNK> 
add gephi07beta . icns 
ignore Update ' modules / apps / foundation / portal - remote / . 
setting version to 1 . 0 . 114 - SNAPSHOT 
<UNK> the <UNK> world world 
Add ClassLoader loader to GroovyClassLoader loader method 
Add screenshots 
<UNK> AndroidSdk public 
Add <UNK> to arcconfig . 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / blogs / . 
add STORM_803 
added studio 
Fix <UNK> <UNK> 
Updated changelog 
ignore Update ' modules / apps / collaboration / directory / . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Updated changelog 
ignore Update ' modules / apps / marketplace / . 
<UNK> <UNK> - <UNK> 
Remove unused <UNK> 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Updated readme 
removed support - support - v4 version 
Fix typo 
ignore Update ' modules / apps / collaboration / blogs / . 
Fix <UNK> <UNK> 
added <UNK> - character . 
added <UNK> logo for <UNK> . 
update plan 
Fix <UNK> <UNK> 
Use <UNK> 
Updated changelog 
<UNK> <UNK> 
updated CHANGES 
Updated README 
ignore Update ' modules / apps / collaboration / wiki / . 
ignore Update ' modules / apps / foundation / portal - remote / . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
LPS - <UNK> Set default build to <UNK> 
ignore Update ' modules / apps / collaboration / bookmarks / . 
add Place . properties 
<UNK> <UNK> . wav to zrtpAlert sounds . 
add description to hazelcast pom 
Remove unnecessary dependency 
Updated <UNK> 
Remove <UNK> from AbstractGenruleStep . java 
<UNK> <UNK> <UNK> in <UNK> 
Move <UNK> to correct <UNK> 
add STORM - 1851 to changelog 
Add image for architecture 
Fix <UNK> <UNK> 
<UNK> <UNK> . interrupt ( ) . 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / nested - portlets / . 
<UNK> <UNK> <UNK> <UNK> 
Add <UNK> to Scenario line . 
set test 
<UNK> <UNK> . 1 . cpw . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> .
gitignore 
LRQA - <UNK> Add new property for ' portal . context ' <UNK> ' 
add stdint for stdint Node 
updated <UNK> course 
Delete gradle - open - 0 . 8 . jar from plugins 
Fix <UNK> <UNK> 
<UNK> the <UNK> <UNK> 
Remove unused . 
ignore Update ' modules / apps / foundation / portal / . 
update changelog 
Make graph Graph public 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / map / . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Fix <UNK> search 
ignore Update ' modules / apps / foundation / portal - search / . 
Updated changelog 
<UNK> verb TODO 
Updated changelog 
add Reference to go 
Prepare next dev iteration 
Fix <UNK> <UNK> 
update Groovy submodule 
ignore Update ' modules / apps / screens / . 
Make <UNK> executable 
update bash to 141 141 <UNK> 
update settings 
ignore Update ' modules / apps / foundation / configuration - admin / . 
Fix typo 
<UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> 
Smack 4 . 1 . 4 - SNAPSHOT 
update version 
updated to latest release <UNK> 
update messageHistory icon 
<UNK> <UNK> <UNK> 
DO NOT MERGE - <UNK> <UNK> <UNK> 
fixed broken <UNK> 
ignore Update ' modules / apps / foundation / portal - settings / . 
Updated library reference 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> 
update contributors 
ignore Update ' modules / apps / collaboration / item - selector / . 
Remove unused SuppressWarnings annotation 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
add words to <UNK> 
Updated README 
update maps version 
<UNK> <UNK> <UNK> 
<UNK> proguard 
Add abc_search_view_preferred_height <UNK> to <UNK> 
ignore Update ' modules / apps / foundation / portal - instances / . 
update changelog 
Updated runnerw 
Updating guava to 20 . 0 
update gitignore 
add STORM - 1415 to changelog 
SNAPSHOT to fix build 
<UNK> <UNK> <UNK> <UNK> 
update CONTRIBUTING 
<UNK> <UNK> 
ignore Update ' modules / apps / collaboration / flags / . 
Add FX2D LITERAL2 to keywords keywords <UNK> 
<UNK> <UNK> . 
<UNK> the <UNK> <UNK> <UNK> to <UNK> . 
<UNK> the <UNK> test 
update apk 
Fix <UNK> <UNK> 
Remove unused <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / asset / . 
<UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
Add image for preference 
remove <UNK> 
fixed <UNK> <UNK> <UNK> ( IDEADEV - <UNK> ) 
<UNK> cassandra cassandra cassandra 
Fix <UNK> <UNK> 
update gradle build tools 
Remove unused import . 
add DONE . txt 
update jsp 
Make <UNK> executable 
Fix <UNK> loop 
update NOTICE 
keystore for . 
Fix a bug in TextAnnotationPatternsInterface / surface / surface ( ) 
Updated changelog 
update <UNK> 
update index version 
fixed <UNK> <UNK> <UNK> 
update to latest release version 
cobertura coveralls 
Make endSubTable TableQuery public 
update demo 
ignore Update ' modules / apps / collaboration / blogs / . 
<UNK> <UNK> 
Add aqw aqw to the fml_at . 
<UNK> <UNK> <UNK> <UNK> 
Remove <UNK> 
ignore Update ' modules / apps / foundation / portal - security / . 
Fix typo in README 
Fix <UNK> <UNK> . 
import import 
Remove unused variable 
ignore Update ' modules / apps / foundation / expando / . 
Add 4aeb7d83a31671d6785f0f533823b8da2e5d09f1 - 1 . 1 . 2 to . 
update Releasing after <UNK> after <UNK> after <UNK> 
add STORM - 1463 to changelog 
setting version to 1 . 0 . 133 
update version number 
add STORM - 706 to changelog 
add STORM - 1180 to changelog 
<UNK> <UNK> 
update gitignore 
update curr . properties to 0 . 54 
Updated changelog 
ignore Update ' modules / apps / foundation / login / . 
Fix <UNK> <UNK> <UNK> 
Updated @ ServiceProvider @ service version 
update materialdrawer 3 . 0 . 7 
update gitignore 
Remove <UNK> from surfaceflinger Android <UNK> . 
update AUTHORS 
Add <UNK> <UNK> 
Added badge 
update wiki 
Push version to 211 - beta3 . 
updated gitignore 
Added dependency - reduced - pom . xml to . 
add plugin . yml 
Add missing import 
Move <UNK> to correct class 
Remove unused <UNK> 
update EdgeDirectionDefault . java 
Add <UNK> to the C string . 
update screenshots 
set GRAYLOG2_VERSION_TIMESTAMP . 9 to GRAYLOG2_VERSION_TIMESTAMP GRAYLOG2_VERSION_TIMESTAMP GRAYLOG2_VERSION_TIMESTAMP GRAYLOG2_VERSION_TIMESTAMP 
Updated changelog 
update gitignore 
Fix <UNK> <UNK> 
Updated changelog 
ignore Update ' modules / apps / collaboration / blogs / . 
updated studio 
updated History . txt 
update neo4j - kernel - SNAPSHOT to SNAPSHOT 
Updating to version 19 . 0 
Fix jms log 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
<UNK> <UNK> <UNK> 
update version to 0 . 97 - SNAPSHOT 
update travis config 
Revert " Revert " updated openjdk7 " 
yum yum dependencies 
updated CHANGES 
Set snapshot version to 6 . 0 . 2 - SNAPSHOT . 
ignore Update ' modules / apps / foundation / hello - soy / . 
Push version to 13 - beta1 , 241 - 241 . 
Add 1024m to the new Library <UNK> 
ignore Update ' modules / apps / foundation / portal - instances / . 
<UNK> <UNK> 
Updated changelog 
add AndroidSdkNotConfiguredException . java . android . android . util to android android src 
Fix typo 
Add DS_Store to gitignore 
Prepare next dev iteration 
Updated changelog 
add <UNK> icons 
Fix camel - disruptor scope 
update gradle plugin 
add README . txt 
<UNK> <UNK> ( ) 
Add egl_cache EGL egl_cache to the core . 
Fix test 
Fixed <UNK> 
Remove blank line 
<UNK> <UNK> - width 3em 3em 3em <UNK> . 
<UNK> version to 1 . 1 . 16 - SNAPSHOT 
update art 
ignore Update ' modules / apps / foundation / hello - world / . 
Add missing @ Override annotation 
Updating Alloy to <UNK> ; LPS - <UNK> 
Added todo 
add Note . md 
Fix enableWriteAheadLogging . xml <UNK> 
Add <UNK> <UNK> natives . 
add VERSION . txt for 288055 exchange 
Add slf4j - log4j12 to the pom . xml 
fixed test data 
ignore Update ' modules / apps / collaboration / notifications / . 
ignore Update ' modules / apps / foundation / portal - lock / . 
add use use <UNK> 
ignore Update ' modules / apps / foundation / roles / . 
ignore Update ' modules / apps / web - experience / journal / . 
<UNK> number of build . number 
Added testresources testresources testresources to profile 
updated CHANGES 
update sample version 
update dropwizard pom 
updated studio with <UNK> 
Fix NULL extractAlbumArt <UNK> - <UNK> 
add wallet 
added clover . license 
<UNK> - list list with list of <UNK> 
Remove unnecessary library 
Push version to 16 - beta1 . 
prepare for next development iteration 
update <UNK> 
Remove test . dependsOn prepareTestResources from the task 
update changelog 
Add init to <UNK> . 
<UNK> <UNK> 
update gradle version 
ignore Update ' modules / apps / web - experience / export - import / . 
<UNK> Makefile 
Use the latest 2 . 9 - bin version of the gradle 2 . 9 . 
<UNK> unless unless cross_compile unless unless tasks . 
ignore Update ' modules / apps / collaboration / blogs / . 
Remove MissingSwitchDefault MissingSwitchDefault MissingSwitchDefault 
add Ignore Eclipse settings to gitignore 
Add parent parent parent parent parent parent parent parent . 
remove unused import 
Fix <UNK> <UNK> . 
updated svm 
Delete Demo . png 
<UNK> now now uses a <UNK> <UNK> 
<UNK> <UNK> . groovy 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
- <UNK> ( <UNK> ) Move js files 
ignore Update ' modules / apps / collaboration / flags / . 
Fix <UNK> <UNK> 
add project project to gitignore 
ignore Update ' modules / apps / web - experience / site / . 
Fix <UNK> 
gitignore 
update RELEASENOTES 
ignore Update ' modules / apps / collaboration / flags / . 
Fix <UNK> <UNK> <UNK> 
add " iPhone " to ignore <UNK> 
Add <UNK> translation 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> 
add classpath for <UNK> 
Fix <UNK> - seedrandom BSD BSD 
Add <UNK> to travis 
LPS - <UNK> Add missing <UNK> to gitignore 
Add database database to jdbi <UNK> 
<UNK> - <UNK> - junit for junit 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - css / . 
update to latest android 21 tools 
Updated library reference 
Updating to version 3 . 1 . 0 
<UNK> <UNK> padding 
Make <UNK> executable 
ignore Update ' modules / apps / collaboration / blogs / . 
<UNK> publishToMavenLocal info 
LPS - <UNK> Fix <UNK> <UNK> 
Remove package package 
Built the latest snapshot 
update README 
ignore Update ' modules / apps / marketplace / . 
Add image for preference 
<UNK> <UNK> 
ignore Update ' modules / apps / web - experience / journal / . 
Fix <UNK> version 
Bump common ref . 
Add ' JavaCompilationAgainstDependenciesIntegrationTest ' to java9 <UNK> 
try jdk8 
update gitignore 
Updated changelog 
update Manifest . txt 
Push version to 14 - beta2 . 
ignore Update ' modules / apps / collaboration / document - library / . 
ignore Update ' modules / apps / foundation / frontend - js / . 
Remove unused import . 
add fun public to core . kt 
Fix <UNK> <UNK> <UNK> 
Make FooterViewHolder MessageList class . 
Remove <UNK> from ExceptionsManager . js 
<UNK> <UNK> . cpp ( ) 
add * . 
<UNK> . rb 
Bump common ref . 
<UNK> <UNK> to bin 
<UNK> the <UNK> <UNK> to singleTop singleTop <UNK> 
Fix typo 
Reduce the <UNK> of the <UNK> method . 
add directories for travis 
Add simple ( function ) to angular . 
update android 8 version to android . 
Updated CHANGELOG 
<UNK> Travis to test 
Fix <UNK> <UNK> 
updated ChangeLog 
Updating Alloy to rev . <UNK> 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / rss / . 
Remove xdebugger vcs - tests from scripts 
ignore Update ' modules / apps / collaboration / image - uploader / . 
Make <UNK> <UNK> <UNK> <UNK> . 
Fix typo 
Fix <UNK> <UNK> <UNK> 
Add a serial serial 
ignore Update ' modules / apps / web - experience / layout / . 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - security / . 
Add Ignore Website to flowconfig . 
ignore Update ' modules / apps / collaboration / announcements / . 
Remove parallel parallel parallel from web 
Use <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / document - library / . 
update hsqldb to 2 . 3 . 3 
Updated parent version . 
update ant to 1 . 10 . 0 
ignore Update ' modules / apps / collaboration / document - library / . 
update version to 1 . 1 
update README 
Add screenshot 
Fix quotes 
ignore Update ' modules / apps / web - experience / layout / . 
Add selectableItemBackground selectableItemBackground to selectableItemBackground test 
ignore Update ' modules / apps / collaboration / document - library / . 
add Changes for <UNK> 
update to latest release 
Fix SearchDialog <UNK> <UNK> 
LPS - <UNK> Fix <UNK> 
<UNK> <UNK> . 
<UNK> ebextensions update to <UNK> . 
<UNK> overrides overrides gradle . gradle 
Add gif 
<UNK> <UNK> <UNK> 
Add useProjectArtifact useProjectArtifact to bundle . xml 
add mode 
<UNK> <UNK> 
updated studio 
LPS - <UNK> - Add background - color for css 
Fix <UNK> <UNK> 
Make initWebSocket initWebSocket public 
updated mdialog 
Updated readme 
Fixing transitive - ness of provided 
<UNK> <UNK> to ArithmeticShell <UNK> 
set version 
update demo 
<UNK> Travis 
Remove unused import . 
add groovy - ant dependency to groovy - ant 
<UNK> - <UNK> - multiline - multiline . xml . xml to backup test folder 
Updated <UNK> <UNK> icon . 
ignore Update ' modules / apps / foundation / login / . 
ignore Update ' modules / apps / foundation / portal - configuration / . 
update junit to 4 . 8 . 2 
Fix <UNK> <UNK> . 
LRQA - <UNK> Move <UNK> to portal - impl 
ignore Update ' modules / apps / collaboration / document - library / . 
update linux - x86 natives 
add <UNK> jar 
<UNK> AndroidManifest . xml 
<UNK> H2OServerError exceptions 
update changelog 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - template / . 
ignore Update ' modules / apps / collaboration / invitation / . 
add Esperanto to text 
Fix <UNK> <UNK> <UNK> . 
Delete actions 
Fix <UNK> <UNK> 
Use the latest release plugin 
Fix - <UNK> - <UNK> <UNK> test test 
Add mdpi launcher icon . 
<UNK> <UNK> . setReflectively ( ) instead of getResolver builder 
update history 
ignore Update ' modules / apps / collaboration / wiki / . 
Add JAVADOC_STYLE JAVADOC_STYLE JAVADOC_STYLE to the pom . xml 
update ActorSDK 
set version 
bump to version 5 . 0 . 17 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Fix <UNK> <UNK> 
Updating netty to 4 . 0 . 32 
<UNK> Makefile 
Add liblog liblog to <UNK> <UNK> . 
Add gitignore 
Remove DS_Store 
Add missing jar 
Fix build 
ignore Update ' modules / apps / foundation / petra / . 
<UNK> test 
add SplitFailedException . mongodb . hadoop . 
remove unused comment 
<UNK> <UNK> and DeepWaterV3 channels channels <UNK> . 
ignore Update ' modules / apps / foundation / portal - configuration / . 
Fix <UNK> <UNK> <UNK> . 
<UNK> <UNK> . getRankings ( ) in TotalRankingsBolt . java 
upgraded netty to 4 . 0 . 9 
update octicons 
LPS - <UNK> Move PrivateMessagingUserNotificationHandler java java files 
<UNK> jar 
ignore Update ' modules / apps / web - experience / journal / . 
setting version to 1 . 0 . 78 - SNAPSHOT 
LPS - <UNK> Add missing @ Override 
add generated module 
Fix WifiController <UNK> <UNK> <UNK> 
Remove <UNK> - - - <UNK> from pom . xml 
Remove compileStatic compileStatic from site . 
ignore Update ' modules / apps / foundation / web - proxy / . 
Remove unused import 
update txtfiereader . md 
<UNK> <UNK> <UNK> 
Fix build 
<UNK> <UNK> to mBaseDir <UNK> 
Bump common ref . 
Fix <UNK> script 
update settings 
add STORM - 1679 to changelog 
ignore Update ' modules / apps / foundation / monitoring / . 
ignore Update ' modules / apps / web - experience / asset / . 
add oracle module 
updated <UNK> to <UNK> 
Add <UNK> <UNK> for docs 
ignore Update ' modules / apps / collaboration / mentions / . 
LPS - <UNK> <UNK> - to <UNK> ( tablet phone ) 
Updated bbb - conf to <UNK> 
update emailmap . properties 
update docs 
Fix <UNK> <UNK> 
Updated <UNK> version . 
update test 
LPS - <UNK> Ignore SF for now 
Remove the FML from the forge 
Fix <UNK> 
<UNK> <UNK> <UNK> <UNK> <UNK> . 
ignore Update ' modules / apps / collaboration / image - uploader / . 
<UNK> <UNK> 
LPS - <UNK> Add build . xml for <UNK> . xml 
ignore Update ' modules / apps / foundation / frontend - theme / . 
bump to version 3 . 0 - rc - 2 
Remove unnecessary <UNK> 
ignore Update ' modules / apps / foundation / plugins - admin / . 
update android . properties to <UNK> 
Fix <UNK> <UNK> 
Add <UNK> <UNK> <UNK> 
Updated version to 6 . 17 
add JspVersion 
Remove println 
Fix <UNK> <UNK> 
add STORM - 1436 to changelog 
remove okhttp - hpacktests - okhttp 
Added a TODO 
ignore Update ' modules / apps / collaboration / ratings / . 
Remove println 
Fix <UNK> upgrade 
ignore Update ' modules / apps / web - experience / trash / . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
ignore Update ' modules / apps / foundation / frontend - js / . 
Remove unused method 
LPS - <UNK> moves icon 
update apk 
Added files via upload 
Set snapshot to 0 . 6 . 4 
updated architecture_en architecture_en image 
Fix <UNK> <UNK> 
bump version 
<UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> 
Updated changelog 
Delete card . io . 0 . aar 
Fix typo 
Remove unused sourceDirectory sourceDirectory test 
add README 
ignore Update ' modules / apps / collaboration / bookmarks / . 
<UNK> comment 
Add lighting down to ProcessingApplet down here 
Added STORM - 443 to changelog 
Updated README 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> 
Prepare next development version . 
Add missing @ Override annotation 
setting version to 1 . 0 . 99 
setting version to 1 . 0 . 99 - SNAPSHOT 
LPS - <UNK> moves icon 
Add <UNK> to hive <UNK> ( ) 
ignore Update ' modules / apps / web - experience / product - navigation / . 
add STORM - 704 to CHANGELOG 
ignore Update ' modules / apps / sync / . 
Remove unnecessary line 
ignore Update ' modules / apps / foundation / portal - search / . 
<UNK> <UNK> <UNK> <UNK> 
LPS - <UNK> Add OAuthRequest * opensocial 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / layout / . 
Fix typo 
add <UNK> 
update readme 
Revert " gitignore " 
updated ChangeLog 
Fix <UNK> <UNK> 
add folder for the visualization 
updated upload_files . cm 
<UNK> <UNK> to 315 
Add <UNK> <UNK> images 
Updated logo 
update english . dic 
Add xhdpi icons for hdpi and mdpi 
add IntelliJ IDEA to gitignore 
Updated apk 
<UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - js / . 
update travis config 
Updated changelog 
Updated to latest android 0 . 6 . 4 
Make <UNK> <UNK> <UNK> to <UNK> 
Fix <UNK> <UNK> . 
Added testConfiguration ( ) to InMemoryGraphTest test 
ignore Update ' modules / apps / collaboration / blogs / . 
update druid - console to 0 . 0 . 2 
ignore Update ' modules / apps / collaboration / wiki / . 
updated changes 
update gitignore 
Remove unused import 
updated version 
gitignore 
update releaseChecklist . md 
Fix <UNK> <UNK> <UNK> 
remove unused <UNK> 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
<UNK> - <UNK> - <UNK> <UNK> <UNK> 
Add APIGenerator . class to pom . xml 
update gradle plugin 
Prepare next development 
update lib to 0 . 1 . 1 
ignore Update ' modules / apps / collaboration / notifications / . 
Updated changelog 
Add <UNK> to <UNK> 
<UNK> <UNK> 
<UNK> <UNK> 
ignore Update ' modules / apps / web - experience / asset / . 
Add <UNK> jar 
<UNK> loop 
LRQA - <UNK> prep next , use latest 
ignore Update ' modules / apps / collaboration / announcements / . 
Use <UNK> <UNK> 
LPS - <UNK> Add compile scope to compile 
Updating Alloy to rev . <UNK> 
Use <UNK> <UNK> 
Make <UNK> to abstract 
Setting default name for multi - project 
LPS - <UNK> Add new build . xml 
ignore Update ' modules / apps / foundation / portal - remote / . 
<UNK> function <UNK> . mouseOut ( ) 
fixed <UNK> history 
add README 
Fixed <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / layout / . 
add scalability image 
Remove @ Override from ReliabilityTestActivity tests . 
Added relativePath - pom to the parent build . 
Prepare next release v1 . 88 . 3 - SNAPSHOT 
<UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> . 
Prepare next development iteration 
Fix build . 
add AbstractJavaClass test 
Updating Alloy to rev . <UNK> 
update README 
Add gitignore 
<UNK> <UNK> 
Built the latest snapshot 
add h2o . 
update 1 . 6 . 
remove unused <UNK> 
Fix <UNK> <UNK> 
Update travis config 
ignore Update ' modules / apps / web - experience / journal / . 
Replace project configuration 
Remove unused MANIFEST MF 
ignore Update ' modules / apps / collaboration / ratings / . 
Add lovejjfg . 
Remove println 
Updated sootclasses jar 
ignore Update ' modules / apps / foundation / portal - security / . 
Make Flusher static to <UNK> 
Added translation using Weblate ( <UNK> ) 
Updated changelog 
add jar 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / marketplace / . 
Updated list 
remove unused @ URL 
added image for <UNK> 
Updated parent version . 
set version 
ignore Update ' modules / apps / foundation / portal - security / . 
Fix RefBase Destroyer <UNK> 
Updated changelog 
Push version to 207 " 11 . 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
Fix test 
bump to version 1 . 0 . 6 
update internal framework to API 19 
Remove unused icon 
Updated changelog 
<UNK> travis 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / site / . 
Add build to <UNK> 
Add travis config 
Updating Alloy to rev . <UNK> 
Add openjdk7 openjdk7 to travis 
ignore Update ' modules / apps / collaboration / microblogs / . 
Delete libbulletjme64 . so 
bump version to 0 . 8 . 7 
Prepare version 22 . 0 . 0 - beta2 . 
Set SNAPSHOT to 2 . 0 . 1 
Add opengl - lwjgl . 
Add lib to package . json 
Remove import 
Add <UNK> test for <UNK> 
Use DefaultHostnameVerifier classes <UNK> 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
setting version to 1 . 0 . 150 
Added translation using Weblate ( <UNK> ) 
<UNK> <UNK> <UNK> 
add mode 
Fix <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> 
Updated README 
setting version to 1 . 0 . 125 
add example 
<UNK> <UNK> 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / sync / . 
Add <UNK> to <UNK> 
Remove reference 
Add oraclejdk8 to the travis matrix 
bump version to 2 . 1 . 1 
update version 
Fix <UNK> <UNK> <UNK> 
update javarepl javarepl to <UNK> 
Add BAD BAD to TypeMap <UNK> . 
update changelog 
<UNK> <UNK> . zip 
Fix <UNK> <UNK> <UNK> 
<UNK> the <UNK> of the <UNK> <UNK> <UNK> . 
Fix <UNK> <UNK> <UNK> 
updated <UNK> course 
add changelog 
updated ChangeLog 
Fix <UNK> <UNK> <UNK> 
Fix <UNK> 
fixed bbb - conf 
ignore Update ' modules / apps / web - experience / site / . 
update version 
update README 
Remove maxParallelForks maxParallelForks maxParallelForks from javaModule test . 
Remove <UNK> <UNK> 
Add 6743b6bb8a38b17fe13ca54edec6727f76cd8ad3 0 . 0 . 7 . 1 for changeset <UNK> 
Fix <UNK> <UNK> . 
Remove unused validates_uniqueness_of email 
Make <UNK> . setup ( ) instead of PlainSaslServerTest void throws Exception 
update gitignore 
Remove Modify 
gitattributes gitattributes . 
Add @ Override annotation 
add <UNK> icon 
ignore Update ' modules / apps / foundation / petra / . 
fixed <UNK> 
ignore Update ' modules / apps / foundation / expando / . 
<UNK> <UNK> 
bumped parent - pom - > 7 - rc5 
ignore Update ' modules / apps / foundation / portal - settings / . 
Add log4j - log4j scope to log4j . 
Add defaultConfig 11 to build . gradle 
Bump common ref . 
update <UNK> 
ignore Update ' modules / apps / foundation / petra / . 
Fix <UNK> <UNK> 
Add jar for commons - lang - 2 . 6 . jar 
Fix <UNK> <UNK> . 
ignore Update ' modules / apps / collaboration / wiki / . 
LPS - <UNK> add build . gradle 
update default - ui to 4 . 2 . 2 
update travis config 
add STORM - 1524 to CHANGELOG 
ignore Update ' modules / apps / web - experience / layout / . 
LPS - <UNK> Fix <UNK> 
Updated <UNK> 
Fix <UNK> <UNK> 
update travis 
add STORM - 1458 to changelog 
<UNK> the <UNK> <UNK> <UNK> 
Add <UNK> to <UNK> 
update version to 1 . 1 . 0 
Add a param tag 
remove unused <UNK> 
Updated RELEASE_NOTES . md 
Fix <UNK> <UNK> icon 
Add missing @ Deprecated annotation 
ignore Update ' modules / apps / collaboration / mentions / . 
Removed unused <UNK> 
Updated CHANGES . txt 
Fix build 
Add test to test 
Fix typo 
update gitignore 
Add <UNK> to <UNK> 
ignore Update ' modules / apps / foundation / license - manager / . 
Add default <UNK> for maven - surefire 
Updated runnerw exe 
add gitattributes <UNK> for <UNK> 
updated log4j . rootLogger to <UNK> 
add configuration to index 
updated <UNK> - screenshots . 
add <UNK> to gitignore 
ignore Update ' modules / apps / web - experience / site / . 
Fixed <UNK> <UNK> 
<UNK> the <UNK> . 
update gradle wrapper 
ignore Update ' modules / apps / web - experience / asset / . 
Download apk directly from here 
Move test to <UNK> . 
update pom 
Remove unused windows <UNK> 
ignore Update ' modules / apps / sync / . 
Updated changelog 
ignore Update ' modules / apps / marketplace / . 
add STORM - 1095 to changelog 
update travis config 
Add <UNK> to the execution 
Add a comment 
LPS - <UNK> Add missing properties 
Updated changelog 
Delete XposedBridgeApi - 36 . 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
ignore Update ' modules / apps / web - experience / staging / . 
add STORM - 2098 to changelog 
<UNK> <UNK> . 
Fix <UNK> 
Updated version to 2 . 0 . 76 - beta 
<UNK> the <UNK> of the <UNK> <UNK> <UNK> . 
ignore Update ' modules / apps / foundation / frontend - js / . 
updated waves waves <UNK> 
<UNK> <UNK> - Xmx256M 
Fix diff header 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / foundation / portal - instances / . 
Updating Alloy to <UNK> ; LPS - <UNK> 
Fix typo in user - edit - form - form - form 
ignore Update ' modules / apps / web - experience / journal / . 
Make <UNK> executable 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
add redis < redis 
make the <UNK> of the throws <UNK> 
Fix camel - jetty9 pom 
add mode 
remove gradlew test 
Prepare library for development 
Remove unused files 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
Remove TBD <UNK> from semantics - semantics . 
LPS - <UNK> Remove unused failonerror 
<UNK> <UNK> . updateUi ( ) 
ignore Update ' modules / apps / web - experience / journal / . 
Remove apply plugin 
Use <UNK> - classes 
ignore Update ' modules / apps / web - experience / staging / . 
Fix <UNK> <UNK> 
<UNK> <UNK> 
ignore Update ' modules / apps / web - experience / staging / . 
Updated <UNK> images 
update to latest android 2 . 4 . 4 
Fix import 
Updated default ppt <UNK> to <UNK> 
Remove examples - exam from pom . xml 
comment " <UNK> <UNK> " 
update gitignore 
update README 
Fix <UNK> <UNK> 
add <UNK> . jar 
update README . json to README . md 
update darwin jar 
Move readme . MD to the camel - weather - weather 
bump pegasus to 5 . 0 . 18 
ignore Update ' modules / apps / foundation / portal - instances / . 
Remove reference 
ignore Update ' modules / apps / foundation / portal - remote / . 
Add se se K 
<UNK> <UNK> . initVanillaEntries ( ) return initVanillaEntries initVanillaEntries 
Fix typo 
<UNK> <UNK> <UNK> <UNK> 
add junit - rt to classVersions 1 . 3 
Add minimizeJar minimizeJar to the pom . 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
LPS - <UNK> Fix <UNK> 
<UNK> <UNK> . py ( ) . 
update applet 
add README . md 
update gitignore 
Add <UNK> <UNK> for <UNK> <UNK> . 
Remove netty 
<UNK> <UNK> to <UNK> 
Updating Alloy to rev . <UNK> 
Move KmlBikeParkDataSource . java to KmlBikeParkDataSource . 
<UNK> version . 
Fix DumpRenderTree permission for AndroidManifest . 
update version 
<UNK> <UNK> 
Fix <UNK> <UNK> parent parent parent parent . 
update to latest android 2 . 0 . 3 
add . 
setting version to 1 . 0 . 110 
Add withCachedResolution for <UNK> 
Updating the version to 1 . 7 . 18 
update testDiscoveryInstrumenter jar 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
update LICENSE 
Remove unused <UNK> . 
Add <UNK> <UNK> for <UNK> 
Fix <UNK> <UNK> <UNK> <UNK> 
<UNK> . js 
ignore Update ' modules / apps / foundation / web - proxy / . 
Add gitignore 
Push version to 15009 . 
Updated CHANGES 
Updating Alloy to rev . <UNK> 
<UNK> <UNK> . 
ignore Update ' modules / apps / foundation / portal / . 
update <UNK> 
fixed typo 
build <UNK> 
update git to latest 0 . 0 . 0 
Updated changelog 
add <UNK> 
update test 
Fixes <UNK> <UNK> <UNK> in CertificateVerificationActivator <UNK> mode . 
<UNK> <UNK> to <UNK> <UNK> 
Add gnu - bin to the assembly of the assembly 
Fix <UNK> <UNK> <UNK> . 
Add <UNK> . neo4j . jmx . 
Make type to <UNK> . 
Fix typo 
<UNK> <UNK> . size ( ) return index2Item index . 
Add 2 . 3 . 5 to the qa 
Add <UNK> <UNK> icon . 
Fix build 
update gitignore 
add Handelkette 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / marketplace / . 
<UNK> <UNK> <UNK> <UNK> <UNK> 
update version 
Updated changelog 
Updated changelog 
add STORM - 1108 to changelog 
ignore Update ' modules / apps / collaboration / directory / . 
Add 4713eec717a35774e6d34ac0819982d2bc34bdc5 0 . 0 . 7 to . 
Remove debug <UNK> 
update travis config 
update graylog2 . conf 
Updated screenshots 
Remove unused file 
ignore Update ' modules / apps / foundation / frontend - js / . 
<UNK> <UNK> <UNK> 
ignore portal - profile 1 . 0 . 4 prep next 
<UNK> LOCAL_MODULE_TAGS LOCAL_MODULE_TAGS LOCAL_MODULE_TAGS . 
update favicon 
<UNK> <UNK> ' s <UNK> - reference ' 
Fix <UNK> 
add abortOnError false to proguardFiles build 
Make the <UNK> of the testRescorerMadeScoresWorse <UNK> 
update gitignore 
updated TODO 
update target to android - 17 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Add screenshots 
Updated 1 . 0 . 11 to 1 . 0 . 12 
update uribeacon 
LPS - <UNK> ( WEB ) Move export import 
add clover . license 
add settings files to . 
updated image2 
LPS - <UNK> Add MustOwnLock extends to FileEntryLockException <UNK> 
MinecraftForge / FML @ b9f4b02cb0b041594656f05de70225df702a8ddd <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> . 
Remove unused found 
Remove unused test 
gitignore <UNK> 
add @ author 
add local . properties to gitignore 
Updated changelog 
Add jar for commons - io - 2 . 2 . jar 
Remove newline 
fixed <UNK> <UNK> 
update license 
update gitignore 
update version to 1 . 5 - SNAPSHOT 
update to latest android 0 . 1 . 0 
Fix help task 
Updating Alloy to rev . <UNK> 
Ignore TAGS TAGS TAGS 
<UNK> <UNK> scope to not_deleted 
Push version to 11251 . 
fixed <UNK> <UNK> 
reset test 
ignore Update ' modules / apps / sync / . 
Updated server jks <UNK> <UNK> 
add profile for release 
Add JNIHelp JNIHelp for android_print_pdf_PdfDocument JNIHelp 
<UNK> <UNK> to True 
Updated changelog 
add m2 . 
added servant diagram diagram 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - search / . 
Fix <UNK> <UNK> 
add words 
ignore Update ' modules / apps / foundation / license - manager / . 
ignore Update ' modules / apps / foundation / portal - security / . 
add Maven repositories 
Ignore <UNK> files 
Updated changelog 
<UNK> <UNK> to <UNK> 
Delete Screenshot_2016 - 04 - 10 - 34 . 
<UNK> <UNK> to <UNK> 
ignore Update ' modules / apps / foundation / frontend - css / . 
add spring module 
update readme to latest - loader 
ignore Update ' modules / apps / foundation / portal - security / . 
Set sources to sources 
<UNK> <UNK> <UNK> <UNK> 
Missing key 
log <UNK> 
<UNK> <UNK> to 10000 <UNK> 
Built the latest snapshot 
Updated <UNK> natives 
Replace DroidSansMono DroidSansMono DroidSansMono <UNK> <UNK> <UNK> 
<UNK> <UNK> ' s <UNK> 
Fix <UNK> Alluxio . 
Add <UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - css / . 
Updated README 
ignore Update ' modules / apps / collaboration / wiki / . 
add STORM - 1424 to CHANGELOG 
Updated gradle wrapper to version 2 . 1 . 
update <UNK> version 
Fix camel - zipkin pom 
update gitignore 
LPS - <UNK> add tld - taglib . properties to taglib - contributor - contributor 
add test for test 
update gradle plugin 
<UNK> <UNK> to <UNK> 
Fix NPE 
<UNK> <UNK> 
Updated Readme 
Fix <UNK> <UNK> 
Delete json2viewFlow . jpg 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Bump common ref . 
ignore Update ' modules / apps / web - experience / journal / . 
update gdx jar 
ignore Update ' modules / apps / marketplace / . 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / web - experience / staging / . 
Add OWNERS OWNERS 
Upload 1 . 4 . 0 version . 
ignore Update ' modules / apps / web - experience / staging / . 
update gitignore 
Fix <UNK> - local . 
update <UNK> to 1 . 4 - beta1 
ignore Update ' modules / apps / collaboration / wiki / . 
Add missing @ Test annotation 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
add STORM - 1340 to changelog 
Add freeing port for <UNK> . 
Add mdpi icons for hdpi 
add mavenLocal ( ) to the build . gradle 
remove TestThat tests 
Changed version to 1 . 2 - SNAPSHOT . 
Fix <UNK> <UNK> <UNK> 
<UNK> default <UNK> to 2 . <UNK> ( ) 
fixed typo in PydevConsoleCommunication PydevConsoleCommunication 
Add <UNK> <UNK> <UNK> jar 
ignore Update ' modules / apps / web - experience / export - import / . 
<UNK> <UNK> <UNK> <UNK> 
LPS - <UNK> - <UNK> <UNK> <UNK> <UNK> 
Updating Alloy to rev . <UNK> 
ignore Update ' modules / apps / foundation / license - manager / . 
ignore Update ' modules / apps / foundation / portal / . 
<UNK> <UNK> <UNK> <UNK> 
Add <UNK> - lang3 sources 
update bbb - conf to BBBAPPSHOME <UNK> 
Fix <UNK> 
<UNK> <UNK> of <UNK> <UNK> <UNK> 
<UNK> test 
ignore Update ' modules / apps / marketplace / . 
Fixed a bug in the launcher . 
update AUTHORS 
<UNK> travis script 
add target for <UNK> 
ignore Update ' modules / apps / collaboration / blogs / . 
Make IZAddress IZAddress <UNK> . 
update project . xml 
Updated parent version . 
ignore Update ' modules / apps / foundation / portal - security / . 
ignore Update ' modules / apps / foundation / users - admin / . 
<UNK> <UNK> . getIndex ( ) 
Added 31cecbb00328430a15845699e4469fa414ccbf53 - 2 . 0 - ignoreme2 0000000000000000000000000000000000000000 
Updated CHANGES . txt 
remove LOG_ERROR error 
Fix <UNK> <UNK> <UNK> 
Remove <UNK> <UNK> 
Add rsApiContext <UNK> to <UNK> . 
Add <UNK> logo 
update linux - arm natives 
<UNK> - vendored - diff - diff - diff - diff / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web / web /
Updated changelog 
Add Export - Package to querydsl pom 
Fix <UNK> <UNK> 
update <UNK> natives 
<UNK> test 
update npn . xml 
update changelog 
update to latest release version 
Make <UNK> executable 
Remove unused ldl LOCAL_C_INCLUDES openssl dependency 
LPS - <UNK> update bnd 
Updated <UNK> version . 
<UNK> test 
update README 
ignore Update ' modules / apps / foundation / portal - scripting / . 
HHH - <UNK> - <UNK> - <UNK> build - hibernate - hibernate - hibernate - hibernate - hibernate - hibernate - hibernate - hibernate - hibernate - plugin 
<UNK> to README 
Fix <UNK> <UNK> 
updated CHANGES 
add README . md 
update to latest android 3 . 1 
Push version to 14 - beta3 . 
remove unused import 
update dsl jar 
add jdbc < module to pom 
Change minSdkVersion to 10 . <UNK> 
update readme 
to <UNK> image 
Make ScriptIntrinsicYuvToRGBThunker class <UNK> 
update cqlsh 3 . 1 . 6 
Fix <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> 
update maven - surefire - plugin to 2 . 8 
LPS - <UNK> Move icon 
LPS - <UNK> Remove unused <UNK> 
Remove unused import 
ignore Update ' modules / apps / web - experience / export - import / . 
Updating Alloy to <UNK> ; LPS - <UNK> 
Remove unused comment 
added titan_configuration <UNK> image 
Remove unused <UNK> <UNK> ( ) from RequestLogConfiguration . 
add 0 . 1 . 4 release 
LPS - <UNK> Remove <UNK> file 
ignore Update ' modules / apps / foundation / portal - template / . 
ignore Update ' modules / apps / web - experience / layout / . 
Updated README 
<UNK> <UNK> <UNK> 
Fix typo 
LPS - <UNK> - Remove empty file 
update gradle version 
removed <UNK> from demo . script 
ignore Update ' modules / apps / marketplace / . 
added Steve Goetze to the project 
LRQA - <UNK> Move <UNK> to portal - service 
Add a new <UNK> badge 
Remove unnecessary <UNK> - <UNK> from gradle . gradle 
update Oracle 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / foundation / server / . 
<UNK> <UNK> 
<UNK> <UNK> 
Fix <UNK> <UNK> <UNK> . 
Fix <UNK> 
Change Recipe def to Recipe . 
Updated Readme 
<UNK> <UNK> . 
Fix <UNK> 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
<UNK> - <UNK> - <UNK> test test 
Fixed broken test 
Update trac trac to https 
update ignatov 
Updated changelog 
update TODO 
Fix junit dependency in grails - grails - support - support 
<UNK> 4 . 0 . 0 release 
Fix <UNK> <UNK> 
<UNK> <UNK> to fill_parent fill_parent <UNK> 
Fix <UNK> <UNK> . 
Add missing beforeDeployment to the library 
updated version 
Fix <UNK> 
ignore Update ' modules / apps / web - experience / site / . 
<UNK> <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / site - navigation / . 
update HdrHistogram 
Add a jshint - W107 * / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / /
add factories factories grails WebDataBindingTraitInjector 
Make Entities public 
update janitor . properties 
ignore Update ' modules / apps / web - experience / export - import / . 
Remove extra line 
add <UNK> to gitignore 
add the <UNK> setup to test 
Remove unused comment 
ignore Update ' modules / apps / collaboration / message - boards / . 
Fix <UNK> <UNK> 
update gradle to 2 . 0 . 0 
Updated todo 
<UNK> <UNK> . jar 
Remove comment 
removed support - support - v4 version 
LPS - <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> 
Fix library 
update package version 
Ignore files 
add STORM - 1000 to changelog 
Added Richard Monson - Haefel to project . xml 
ignore Update ' modules / apps / collaboration / wiki / . 
update gremlin version 
update maven - resources - plugin to 2 . 6 
Fix <UNK> <UNK> <UNK> 
add bugsense_api_key . txt 
<UNK> <UNK> 
update LICENSE 
Remove unused <UNK> from compiler . xml 
updated <UNK> icon 
add pull 
Move <UNK> to the same location 
<UNK> 1 . 8 . 1 
add directories to travis 
Ignore DS_Store <UNK> 
add STORM - 1215 to CHANGELOG 
add util lib to classVersions conf 
add CHANGELOG 
add Predicate . antlr . v4 to Predicate Predicate v4 of Predicate v4 
ignore Update ' modules / apps / foundation / frontend - theme / . 
update applet jar 
Pull MenuComponent of MenuComponent <UNK> 
ignore Update ' modules / apps / foundation / portal - security / . 
<UNK> <UNK> . exit ( ) in ValidateConf . java . ValidateConf ( ) 
ignore Update ' modules / apps / foundation / petra / . 
update CNAME 
<UNK> <UNK> to 640m 
Fix <UNK> <UNK> <UNK> 
Add new <UNK> for Support Library . 
Remove <UNK> <UNK> 
Bump up version . 
add <UNK> 
update readme 
Fix UIExplorer UIExplorer UIExplorer UIExplorer <UNK> 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / collaboration / document - library / . 
Added missing @ Override annotation 
Updated changelog 
Updated changelog 
Updated readme 
Updating parent version . 
update gitignore 
Make <UNK> executable 
<UNK> <UNK> to 8192 <UNK> 
Add gnu to the new test 
Fix <UNK> <UNK> 
Change minSdkVersion to 14 
add tools tools to travis 
Updated library reference 
ignore Update ' modules / apps / collaboration / bookmarks / . 
Add SINCE 0 . 7 . 0 to gitblit gitblit of <UNK> 
add LIFERAY zip 
add @ Deprecated to LanguageConsoleImpl console 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / sync / . 
turn off disable <UNK> for registry 
Fix <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - css / . 
Updated parent version . 
Fix <UNK> <UNK> <UNK> 
update gitignore 
Add HTMLCanvasElement HTMLCanvasElement function to HTMLCanvasElement HTMLCanvasElement <UNK> . 
ignore Update ' modules / apps / collaboration / document - library / . 
<UNK> the <UNK> of the simulator simulator clock_gettime <UNK> . 
ignore Update ' modules / apps / collaboration / blogs / . 
<UNK> <UNK> ' s <UNK> . 
<UNK> for jetty . 2 . 2 
Fix <UNK> <UNK> 
update travis config 
Updated changelog 
ignore Update ' modules / apps / foundation / login / . 
update gecko version 
ignore Update ' modules / apps / collaboration / comment / . 
fixed test data 
add osx to travis 
Updated library reference 
<UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
update ideaIU . properties 
Fix <UNK> <UNK> <UNK> 
Remove <UNK> from NSObject + user 
update README 
update comparisonVersion - websocket comparisonVersion 
Updated default ppt <UNK> to <UNK> 
add gitignore for gitignore 
<UNK> <UNK> 
Updated README . md 
Updated changelog 
<UNK> <UNK> of the top <UNK> 
Fix <UNK> <UNK> <UNK> 
update gitignore 
Add script to <UNK> 
Fixed <UNK> <UNK> 
update applet 
Bump common ref . 
update archivesBaseName . gradle to jedis jedis . 
Fix typo . 
updated app_konference - 10 . 04 - 32 . 
updated CHANGES 
Push version to 212 - beta4 . 
add travis config 
Fix build 
update CONTRIBUTORS 
<UNK> <UNK> <UNK> <UNK> 
Fix - <UNK> 
add missing @ Deprecated annotation 
add STORM - 808 to changelog 
<UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> . 
Fix thrift thrift . 
Fix <UNK> . 
Updated changelog 
Fix <UNK> <UNK> <UNK> . 
Fix broken <UNK> <UNK> 
Reduce <UNK> 
<UNK> <UNK> <UNK> 
updated studio with <UNK> 
Fix typo 
Fix postgresql dependency in spring - boot - devtools - devtools 
Add <UNK> <UNK> jar 
update gridworks to <UNK> 
Add missing <UNK> <UNK> <UNK> 
Fix <UNK> test 
update banner 
ignore Update ' modules / apps / foundation / frontend - theme / . 
ignore Update ' modules / apps / collaboration / blogs / . 
Ignore bin - output 
update travis config 
ignore Update ' modules / apps / web - experience / staging / . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Fix <UNK> <UNK> . 
ignore Update ' modules / apps / collaboration / document - library / . 
add * . 
ignore Update ' modules / apps / collaboration / microblogs / . 
update appcompat v7 
add STORM - 1723 to CHANGELOG 
Remove <UNK> <UNK> 
Updating version to 3 . 5 . 0 - SNAPSHOT 
Updated reportng - dep - 1 . 4 . jar . 
Fix <UNK> <UNK> <UNK> . 
remove pooled pooled true from DataSource - app 
Add ConnectionService hide to ConnectionService <UNK> . 
LPS - <UNK> Add missing @ Deprecated 
LPS - <UNK> moves icon 
Fix <UNK> <UNK> 
Updated travis play to play <UNK> version 
add STORM - 401 to changelog 
<UNK> , <UNK> <UNK> 
ignore Update ' modules / apps / web - experience / site / . 
update freebsd natives 
Bump common ref . 
setting version to 1 . 0 . 119 - SNAPSHOT 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
<UNK> - view - view . frames . frames TODO 
ignore Update ' modules / apps / web - experience / journal / . 
add STORM - 1755 to CHANGELOG 
update copyright 
<UNK> <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / marketplace / . 
Remove <UNK> . jar from <UNK> 
LPS - <UNK> prep next , use latest 
Prepare version 16 - beta3 . 
update gitignore 
Updated NativeBitmapFactory to latest version 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - security / . 
<UNK> <UNK> 
Add art 
Add sphinx sphinx to py - py 
Fix <UNK> <UNK> 
add maven - plugin - plugin to maven - android - plugin 
updated <UNK> <UNK> image . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
LPS - <UNK> Add new <UNK> Package 
Add alwaysRun for <UNK> 
Add plugins / logs to . 
updated version for release 
Fix <UNK> <UNK> . 
Updated <UNK> to <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> 
updated version 
add robolectric settings to gitignore 
Remove <UNK> - config from settings . gradle 
ignore Update ' modules / apps / static / osgi / . 
Fix <UNK> <UNK> <UNK> 
update socket . io to test 
ignore Update ' modules / apps / web - experience / nested - portlets / . 
Updated changelog 
<UNK> the <UNK> <UNK> <UNK> to <UNK> . 
update gradle plugin version 
update README 
Fix typo 
LPS - <UNK> <UNK> <UNK> 
update commons - collections to 3 . 2 . 2 
ignore Update ' modules / apps / web - experience / site / . 
add image for greenaddress github 
update test 
Delete server . bks 
update gitignore 
Fix <UNK> <UNK> ( PY - <UNK> ) 
Reduce the CI_NAME <UNK> for the jacocoReport jacocoReport . 
updated high <UNK> to <UNK> <UNK> . 
Remove <UNK> <UNK> <UNK> 
Updating Alloy to rev . <UNK> 
ignore Update ' modules / apps / foundation / login / . 
update to latest android build tools 
Remove version of jython - standalone dependency 
Updated README 
<UNK> <UNK> <UNK> <UNK> 
<UNK> <UNK> <UNK> <UNK> 
Fix <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / frontend - editor / . 
update VERSION . txt 
fixed test data 
add STORM - 2039 to changelog 
Replace status . asciidoc to fix the status <UNK> 
Set <UNK> version 
LRQA - <UNK> Add new property for skip deploy 
Fix <UNK> <UNK> for <UNK> 
setting version to 1 . 0 . 104 - SNAPSHOT 
Fix <UNK> permission . 
update linux - ppc64 natives 
fixed <UNK> <UNK> 
update commons commons commons jexl_2 
add analysis - phonetic module 
Ignore bin - plugin - async / bin / bin / bin / bin / bin / bin / bin / bin / bin / bin / bin / bin / bin / bin / bin 
Fix <UNK> <UNK> icon 
Delete QuantcastAndroidSdk . jar 
Add idea plugin for <UNK> 
Updated changelog 
Remove unused <UNK> . 
Updating netty to 4 . 0 . 8 
ignore Update ' modules / apps / collaboration / ratings / . 
Make ControlFlowGraph public to <UNK> 
updated energy energy icon 
Updating Alloy to rev . <UNK> 
updated icon 
Add LICENSES . txt to server server . 
update examples 
<UNK> <UNK> <UNK> <UNK> 
update cudaruntime_x86 dll 
update changelog 
Fix <UNK> <UNK> 
fixed <UNK> <UNK> <UNK> 
ignore Update ' modules / apps / foundation / portal - template / . 
Add deprecation deprecation 
Updated changelog 
ignore Update ' modules / apps / web - experience / site / . 
Remove unused image 
Prepare next development version . 
ignore Update ' modules / apps / foundation / portal - search / . 
Add missing jar for <UNK> 
Remove stale <UNK> from <UNK> . 
update changelog 
Bump version to 3 . 14 . 1 . 
Fix <UNK> <UNK> 
Updates the <UNK> background icon . 
Updated <UNK> icon . 
Fix <UNK> <UNK> 
Smack 4 . 1 . 0 - beta1 
add lib to gitignore 
Remove unnecessary line 
Add travis config 
add <UNK> to <UNK> 
ignore Update ' modules / apps / collaboration / announcements / . 
Add <UNK> . 0 
add jdk jdk to travis 
add missing secret to secret <UNK> 
<UNK> <UNK> 
Remove import 
Remove require require rubygems 
<UNK> <UNK> <UNK> 
Add <UNK> . attribute_type to attribute_decl attribute_decl of attribute_decl <UNK> 
updated CHANGES . txt for HADOOP - 12526 . 
Delete appinfo . jar 
Fix <UNK> <UNK> <UNK> . 
ignore Update ' modules / apps / foundation / portal - store / . 
Add <UNK> . lang 
LPS - <UNK> - Remove empty file 
Add xhdpi xxhdpi <UNK> 
travis 
add 10_basic 10_basic test 
Updated changelog 
Remove unused <UNK> . 
Remove some task from <UNK> 
Added preview image 
Remove ApplicationInfo ApplicationInfo <UNK> 
Remove <UNK> . 
setting version to 1 . 0 . 151 
