fix for <UNK> <UNK>
fix <UNK>
Added . addConstructor . addConstructor . bluetooth . bluetooth . bluetooth . bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . Bluetooth . bluetooth . bluetooth . bluetooth . bluetooth . bluetooth . bluetooth . bluetooth . bluetooth . bluetooth . bluetooth . bluetooth . bluetooth .
Updating to PGPlugin base class , cf [ Issue # 44 ]( https :// github . com / phonegap / phonegap - plugins / issues / 44 )
<UNK> : fix PGSocialShare - 8 - js
Updated version to 4 . 1 . 7 . RELEASE
Upgrade to Spring Boot 5 . 0 . 5 . RELEASE
add registry daemon
[# <UNK> ] <UNK> : updated test fixture
[# <UNK> , # <UNK> ] <UNK> : updated test fixture
fix travis build
Added <UNK> entry
[# <UNK> ] IfReturnReturnSimplificationInspector . point : IfReturnReturnSimplificationInspector . problem
<UNK> : added <UNK>
Translated using Weblate ( Catalan ) Currently translated at 62 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Upper Sorbian ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Kabyle ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Added travis CI
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Esperanto ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 99 . 8 % ( <UNK> of 2094 strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Japanese ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( 1738 of 1738 strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Taiwan )) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 99 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Slovenian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Basque ) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 62 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Lithuanian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Finnish ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Lithuanian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( 1595 of 1595 strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( French ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Simplified )) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Czech ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Committed translation ( eu )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 %
fix <UNK>
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of 641 strings )
Translated using Weblate ( Russian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of 641 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix <UNK> <UNK>
Translated using Weblate ( Hebrew ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add feature_articles feature_articles feature_articles feature_articles <UNK> # <UNK> )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hungarian ) Currently translated at 99 . 8 % ( <UNK> of 3376 strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Greek ) Currently translated at 52 . 8 % ( <UNK> of 3102 strings )
Translated using Weblate ( Upper Sorbian ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Updated Android translation
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Committed translation ( mr mr <UNK> )
Translated using Weblate ( Czech ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( 991 of 991 strings )
Translated using Weblate ( <UNK> ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Catalan ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
fix error in <UNK>
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 43 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Hebrew ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add <UNK> to MultiTouchSupport MultiTouchSupport MultiTouchSupport <UNK>
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Taiwan )) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hungarian ) Currently translated at 100 . 0 % ( 1660 of 1660 strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( 1595 of 1595 strings )
Fixed <UNK> <UNK>
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 76 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Basque ) Currently translated at 61 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 991 of 991 strings )
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( 1595 of 1595 strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of 641 strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 44 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Taiwan )) Currently translated at 100 . 0 % ( 1595 of 1595 strings )
fix settings
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Removed unused import
Translated using Weblate ( Turkish ) Currently translated at 9 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
DataExtractionOSM DataExtractionOSM line in net . render . xml
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Bulgarian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Japanese ) Currently translated at 43 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Greek ) Currently translated at 52 . 8 % ( <UNK> of 2536 strings )
Translated using Weblate ( Polish ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hebrew ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 47 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hebrew ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Upper Sorbian ) Currently translated at 43 . 1 % ( <UNK> of 2331 strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( sr sr Argentina )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 2331 of 2331 strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( 2357 of 2357 strings )
Translated using Weblate ( Lithuanian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( <UNK> ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Hungarian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
<UNK> <UNK>
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( latin )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Serbian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hungarian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
<UNK> <UNK> <UNK>
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 47 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Basque ) Currently translated at 52 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 43 . 1 % ( <UNK> of 3102 strings )
Committed translation ( es )
Translated using Weblate ( Greek ) Currently translated at 52 . 8 % ( <UNK> of 2536 strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Chinese ( Taiwan )) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of 641 strings )
<UNK> <UNK> icon
Translated using Weblate ( Esperanto ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
added <UNK> for <UNK>
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( 2000 of 2000 strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 43 . 1 % ( <UNK> of 3102 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovenian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
[ maven - release - plugin ] prepare release lanterna - 2 . 0 . 2
[ maven - release - plugin ] prepare release lanterna - 2 . 1 . 6
addAction addAction addAction action action
<UNK> the component is buffered - buffered to be <UNK>
<UNK> <UNK> to <UNK>
[ Java ] Update version to rc1
<UNK> the <UNK> <UNK>
README
fix CandleStickChart CandleStickChart CandleStickChart CandleStickChart CandleStickChart <UNK>
add readme
Removed unnecessary manifest
Upgrade gradle to 3 . 3
<UNK> : fix <UNK> . txt <UNK> <UNK>
[ <UNK> - <UNK> ] Fixed <UNK> <UNK> in JavaScriptException <UNK>
Made <UNK> <UNK> to be <UNK>
Added the paths to the . tools file
Fixed a typo in I18N locale
Added javadoc to AsyncProxy Deprecated
<UNK> : <UNK> <UNK> to put <UNK> <UNK>
<UNK> : fix <UNK>
added missing javadoc to complete javadoc
added DelayStrategy delayStrategy delayStrategy DelayStrategy fields
[ pom ] Update maven - jar - plugin to 2 . 6
Release 1 . 3 . 0 - beta0 - SNAPSHOT
remove unused import
fix javadoc comment
Updated clas . 02
added janino janino dependency to logback
added missing break to DBUtil break
remove getContext getContext getContext getContext getContext <UNK> is already <UNK>
<UNK> the logback test
add Chetan Mehrotra Mehrotra Uttar CLAs CLAs <UNK> )
fix test
fix stop <UNK>
Added appcompat appcompat appcompat v7 v7 v7 <UNK> , it can be used
updated to v0 . 4 . 2
Fixed <UNK> <UNK> in <UNK>
<UNK> : <UNK> <UNK>
formatting
rename demo to the demo
Removed a rm1 rm1 rm1 tests
Fixed a bug in WordPruningBreadthFirstSearchManager <UNK>
Fixed a bug in LexTreeLinguist LexTreeLinguist <UNK>
Fixed typo in <UNK>
[ <UNK> - <UNK> ] <UNK> the <UNK> of the <UNK>
Added doc to doc . html
Removed unnecessary <UNK> from LogMath TODO
Fixed a bug in SimpleFrontEnd context
Added a System . out . println to Live println
<UNK> the parallel directory in the parallel directory
Added README
[ <UNK> - <UNK> ] Remove file in DiscCache file
<UNK> - context : Add missing - core to spring - core
Updated Changelog for a a 1 . 12 . txt
trying to fix travis CI
Added new Started Started to 1 . 6 . txt
Updated changelog
Added link to README
update gitignore
remove unused manifest
README
Opening up v0 . 2 . 4 for development
<UNK> : Move <UNK> to model
<UNK> : Add todo
Added <UNK> to the <UNK>
Moved classes . txt
removed obsolete TODO
Updating to bom version 1 . 15 . 69 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
Updating to bom version 1 . 16 . 186 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
jvm the <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
add test
add ResultSetMapper ResultSetMapper interface
Updated gitignore
<UNK> the starter grpc grpc grpc grpc starter <UNK> in the <UNK>
Fixed a bug in ZContext 1 . 5 . 5
fix test case
Added sync_flowchart sync_flowchart sync_flowchart sync_flowchart . png
Travis : travis travis - yml
add build ignore
Updated . gitignore
Incrementing snapshot version to 1 . 1 . 0 - SNAPSHOT
fix <UNK>
fix <UNK> <UNK>
<UNK> <UNK> <UNK> <UNK> <UNK>
remove tmp gitignore
<UNK> the visibility of the <UNK>
fix missing @ Key . management_index . management_index . management_index . management_index . management_index . apache
<UNK> : make test <UNK>
Bumped version
fix <UNK> <UNK> on <UNK>
add missing <UNK>
fix <UNK>
fixed test case
Incrementing snapshot version to 1 . 0 . 1 - SNAPSHOT
added TODO
Removed unnecessary CassandraRunnerTest exclude from utils
<UNK> the default max to 0
update
fix <UNK> <UNK>
update sdks
add log
<UNK> test
<UNK> the <UNK> Donald email
added <UNK>
[ pom ] Add jstl - api to jstl jstl - api
Removed <UNK> test
scribe scribe scribe scribe # <UNK> )
bump 1 . 16 . 20_pre17
release 1 . 16 . 22
bump pre
release 1 . 16 . 24
Added build . sh for build . sh
[ Gradle Release Plugin ] - pre tag commit : ' 5 . 6 . 9 '
<UNK> 1 . 13 . 3
bump 1 . 16 . 20_pre5
fix apk in apk
Upgrade to Vaadin 8 . 0 . 5 Closes gh - <UNK>
Upgrade Spring Cloud to Spring Cloud 1 . 1 . 0 . RC1
Upgrade Spring Spring Cloud version to 1 . 0 . 0 . RELEASE
Upgrade to Spring Boot 1 . 0 . 0 . RC1
Upgrade to Apache Camel 2 . 19 . 0 Closes gh - <UNK>
svn changeset : <UNK> / svn branch : trunk
Eclipse 4 . 6
Added project project
Added a <UNK> for <UNK>
Updates the <UNK> libraries ( <UNK> on opus - <UNK> )
Updates jicoco
Updates libjitsi
update libjitsi
Updates the <UNK> library ( <UNK> on jitsi <UNK> )
Updates libjitsi
Updates libjitsi
fix : <UNK> <UNK> <UNK> <UNK>
Updates libjitsi
Updates libjitsi
Updates jabber . jar ( built on jitsi <UNK> )
add travis CI
lintOptions lintOptions build
add <UNK> to <UNK>
Added missing string
<UNK>
added voiceimeutils jar
Fixed layout in the layout
<UNK> <UNK>
added null check to DictionarySQLiteConnection word
Added gen / bin / gitignore
fix : <UNK> <UNK>
<UNK> : make volatile private
add a info to the <UNK>
session session
MVStore volatile
remove duplicate database in Session
fix : add <UNK> when <UNK> is <UNK>
Added 788 788 788 788 788 log . md
add <UNK> <UNK> to circle
Update 11 TouchEvent . md
Added synchronized to CurlMesh bitmap texture it is not it in the <UNK>
<UNK> : <UNK> <UNK>
Updated README . md
git - svn - id : https :// only . mawhrin
add screenshots
[ maven - release - plugin ] prepare release mango - 1 . 0
[ maven - release - plugin ] prepare release mango - 1 . 3 . 2
[ maven - release - plugin ] prepare release mango - 1 . 2 . 3
[ maven - release - plugin ] prepare release mango - 1 . 4 . 0
[ maven - release - plugin ] prepare release mango - 1 . 2 . 7
remove test
[ maven - release - plugin ] prepare release mango - 1 . 3 . 5
fix lombok lombok lombok lombok Parcelable Parcelable # <UNK> )
Updated README . md
Travis : travis travis - yml
add link to README
Fixed typo in example
Added <UNK> to the <UNK>
remove unused import
Fixed <UNK> <UNK> <UNK>
Added android arsenal arsenal badge
Fixed bug in AddonRedPower2 temporary recipe recipe recipe recipe recipe <UNK> <UNK>
Updated changelog to include changelog
<UNK> . gradle : fix config . minecraft_version . txt
fix Localizations Localizations <UNK>
added log for <UNK>
<UNK> - testnet - testnet - testnet - <UNK> : Fix :// <UNK> . <UNK> . com / wiki / <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> = issues / <UNK>
fix <UNK>
added missing <UNK>
fix <UNK>
Added link to travis build
rename project name
removed TestHelpers TestHelpers dependency
add config repo
add config repo
add config repo
<UNK> the <UNK>
Removed activity activity
Updated maven - javadoc - plugin to 2 . 9 . 1
fix test case
Removing unused import
<UNK> : fix test case
Removing unused import
Fixed <UNK>
Added build / build / build to . gitignore
added missing v to Youku Youku Youku Youku <UNK>
// readme
Added a <UNK> to the <UNK>
update README
updated jar
fix log
add a missing task to the file
remove unused import
fix form executor
warn <UNK>
fix <UNK>
remove unused import
remove <UNK>
remove unused import
remove dependency
fix bindAll bindAll bindAll bindAll bindAll bindAll bindAll bindAll <UNK> <UNK>
bump version
removed })) })) })) System . updateRequest
Upgrade to 0 . 18 . 0
trace <UNK>
logfetch up logfetch
bump version
<UNK> imports
<UNK> <UNK>
Updates the <UNK> image
Updates the <UNK> icon
jar
<UNK> the <UNK> ()
Removed a <UNK> cancel to the <UNK> <UNK>
Fixed resources in resources
Updated the Growl Growl Growl Growl Growl framework to the resources
Removed debugging
Adds a <UNK> to the <UNK> <UNK>
Updated resources
Updates ice4j . jar to <UNK>
Added a <UNK> chat status to the list of the chat window
Updates libjitsi . jar to <UNK>
Updates libjitsi . jar to <UNK>
Updates libjitsi . jar to <UNK>
<UNK> the <UNK> <UNK>
SuppressWarnings FileManager SuppressWarnings . openURL - no - no - no - no - no - no - no - no - no - no - no - no - no - no - no - no - no - no - no - no - no choice choice choice choice choice <UNK> <UNK> <UNK>
pom : update pom
Updates ice4j . jar to <UNK>
<UNK> the <UNK> to the <UNK>
Fixes a NullPointerException in icq ContactIcqImpl ContactIcqImpl ContactIcqImpl <UNK> <UNK>
<UNK> <UNK>
<UNK> the <UNK> <UNK> to the <UNK>
<UNK> the size of the yahoo yahoo yahoo yahoo yahoo <UNK>
<UNK> the chat window to the list
Updates ice4j . jar to <UNK>
Fixed <UNK> <UNK> in chat room
fix debian debian name
<UNK> : <UNK> <UNK> to audioLevelsReceived CallPeerSipImpl <UNK>
<UNK> the SIP call to the <UNK>
Updated debian version to resources
Added a check for the <UNK> <UNK> <UNK>
fix resources in resources
Fixes a bug in run run
Fixed resources in resources
Changes version to 2 . 9
add badge
add getNextId getNextId ()
[ maven - release - plugin ] prepare release docx4j - 3 . 2 . 1
fix NPE in StyleUtil isEmpty
[ pom ] Update slf4j - api to 1 . 7 . 10
README
Added note to the README
sample sample
fix sample sample title
<UNK> : fix typo in readme
fix handlebars handlebars package
add module to pom . xml
Signed - off - by : Jeeeyul < jeeeyul @ gmail . com >
Signed - off - by : Jeeeyul < jeeeyul @ gmail . com >
Added bin to gitignore
<UNK> : add travis - ci build
Bumped version to 0 . 9 . 4
Updated Syncthing to v0 . 14 . 40
Fixed <UNK> <UNK> <UNK>
Bumped version to 0 . 7 . 11
Fixed <UNK> margin in <UNK>
Bumped version to 0 . 7 . 5 - beta2
Updated syncthing to v0 . 14 . 13
<UNK> : fix <UNK> <UNK>
Updated servlet - api - api to 3 . 0 . 1
fix typo in README
<UNK> : Move the test file
[ Gradle Release Plugin ] - new tag commit : ' 2 . 1 . 2 - SNAPSHOT '
// for the <UNK>
add image
Updated travis build version
Updated gradle version
<UNK> the <UNK> to the <UNK>
NOTES : add release notes
Added a i debian from the build file
<UNK> the <UNK> if a <UNK> is null
Added travis status status status
<UNK> the test in the test
temporary ignore until <UNK> how
remove log from <UNK>
fix test
<UNK> import
<UNK> padding
fix <UNK>
remove cfpLoadingBarProvider cfpLoadingBarProvider cfpLoadingBarProvider cfpLoadingBarProvider <UNK>
Added icon
fix tags on tags
fix config
super rejectedExecution super super
Added s s s s to the templates
Fixed <UNK> <UNK> <UNK>
Added application development to README . asciidoc
Upgrade android - screenshot - paparazzo to 1 . 9
[ pom ] Update maven - plugin - testing to 2 . 1
ignoring test
fix bug in <UNK>
remove animal - sniffer - maven - plugin from 1 . 11 to 1 . 11
fix parameter of <UNK>
fix test
updated skin version
added further test to more more more <UNK>
added missing Maven Android to maven - <UNK>
exclude helpmojo helpmojo plugin
[ pom ] Remove maven - dependency - tree to the maven - dependency
<UNK> version to 0 . 9
// <UNK>
<UNK> <UNK>
Deleted unused file
remove log
<UNK> <UNK> to URL
add <UNK> to <UNK>
fix getWorkingPatchApkChecksum getWorkingPatchApkChecksum getWorkingPatchApkChecksum getWorkingPatchApkChecksum getWorkingPatchApkChecksum Context Context Context <UNK> )
update README
fix test case
gh - svn - id : http :// protostuff . googlecode . com / svn / trunk @ <UNK> 3b38d51a - 9144 - 11de - 8ad7 - 8b2c2f1e2016
//
Updated README
Added <UNK>
fix <UNK> <UNK>
remove finish finish
<UNK> file
travis : remove Java 6 . 6
<UNK> : don ' t try to null
bump version
bump version
<UNK>
Added unused icon
added check for <UNK>
Added test for test
add 3 . 5 . 5 to the jms title
Added missing <UNK> to SOAP Mock <UNK>
<UNK> <UNK>
added @ keystoreTable @ keystoreTable @ <UNK>
added getter for isUseRegEx useRegEx useRegEx <UNK>
Updated RELEASENOTES error
debug : debug debug debug
fixed <UNK>
added check for <UNK> input input ."); for <UNK> input ."); for <UNK>
[ ci ] <UNK>
fixed <UNK> algorithm algorithm PKCSObjectIdentifiers pkcs_12PbeIds <UNK>
rename to correct <UNK>
readme
update log
Fixed issue with <UNK> <UNK>
Updated version number
Fixed issue with <UNK> <UNK>
Fixed issue with <UNK> <UNK> when <UNK> is not found
Fixed a bug in visibleBoundsContains parent
Updated version
Fixed issue with <UNK> <UNK> in iOS
trying to fix travis CI
Added Default
Fixed a bug in InfiniteContainer container
Fixed regression in the <UNK>
Updated version number
Updated version
Fixed issue with <UNK> <UNK>
Added a getColumnCount getColumnCount getColumnCount row to cursor
Fixed a bug in InfiniteContainer container
fixed a bug in hide
fixed issue with <UNK> <UNK>
Fixed regression in JavaFXLoader JavaFXLoader commit in <UNK>
Added a <UNK> to the <UNK> <UNK>
log4j log4j . properties
<UNK> : fix unused <UNK>
add missing method to app
add getter
fix for <UNK>
fix along along along along dimension dimension dimension <UNK>
fix : <UNK> <UNK> <UNK>
debug cuda false
fix <UNK> <UNK>
add log to the <UNK>
<UNK> the <UNK> <UNK> to location the location
<UNK> : fix test
[ pom ] Remove slf4j - simple - jdk14 - jdk14 - jdk14 to slf4j - jdk14 - jdk14 - jdk14 - <UNK> : <UNK> : <UNK> . <UNK>
Added comment
<UNK> the toto toto txt
Fixed NPE in null
fixed svn :// github . com / svn / trunk / <UNK>
Updated gif
Added <UNK>
[ Gradle Release Plugin ] - pre tag commit : ' 0 . 1 . 12 '
[ <UNK> - <UNK> ] fix NPE in <UNK>
removed suro suro elasticsearch elasticsearch elasticsearch - <UNK> from 0 . 90 . 12
fix typo in sink_using_kafkaV2 sink_using_kafkaV2 small <UNK> <UNK>
[ Gradle Release Plugin ] - new version commit : ' 0 . 1 . 15 - SNAPSHOT '
[ <UNK> - <UNK> ] remove <UNK> <UNK> <UNK> <UNK> <UNK>
Updated README . md
Removed TODO
add apk
Added access via COUNT_UPDATER SuppressWarnings SuppressWarnings SuppressWarnings }) <UNK> / <UNK> / lettuce / <UNK> - <UNK> / <UNK> / <UNK>
gitignore
Updated README to point to 1 . 1 . 5
pom pom
[ maven - release - plugin ] prepare release apns - 0 . 1 . 6
<UNK> : Fix <UNK> <UNK>
Fixing a bug in DeploymentServiceImpl formMap formMap formMap <UNK> <UNK>
Removed unused code
fix bug in RestResponseFactory isAssignableFrom - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> -
Added dbclean sql sql
Added javadoc for Dimitris Daniel Daniel Daniel can <UNK> <UNK> ' t <UNK> <UNK>
Updated pl pl commit to version 2 . 2 . 2
[ pom ] Update tomcat8 to 7 . 0 . 90
[ pom ] Update tomcat8 to 8 . 0 . 41
xstream xstream xstream xstream 1 . 4 . 9
[ pom ] Update tomcat8 to 9 . 0 . 2
[ pom ] Update tomcat9 to 9 . 0 . 0 . M21
[ pom ] Update tomcat8 to 8 . 5 . 20
add apk
add apk
add <UNK>
add screenshot
fix <UNK> <UNK>
add new apk
Fixed <UNK> saved saved null pull
Fixed typo in MetricsResource writer
Fixed a bug in stmt ourResource <UNK>
Adding a CHANGELOG for the CHANGELOG
add a testSimpleInsert test
Added apk
bump build version
add dialog
fix null pointer
python python ipython install notebook install
fix item of <UNK>
added eclipse classpath
fix <UNK> <UNK>
Updated Gradle version
seldon python 1 . 4 . 1
seldon python 1 . 3 . 3
README
added <UNK> to end of <UNK>
<UNK> the <UNK>
<UNK> <UNK>
Updated sqlcipher sqlcipher sqlcipher sqlcipher <UNK> <UNK> <UNK>
Updated sqlcipher sqlcipher sqlcipher sqlcipher <UNK> <UNK> <UNK>
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare release ormlite - android - 4 . 45
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare release ormlite - android - 4 . 46
logger the logger
<UNK> the content content
<UNK> : Increase <UNK>
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 2 . 26 '
[ Gradle Release Plugin ] - new version commit : ' 1 . 1 . 56 - SNAPSHOT '
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 1 . 50 '
[ Gradle Release Plugin ] - new version commit : ' 1 . 2 . 15 - SNAPSHOT '
<UNK> : <UNK> loaded
updated before / after
README
<UNK> <UNK>
<UNK> : Fix <UNK> <UNK> in <UNK>
javadoc : Corrected javadoc
Added commons - lang - 14 to doap_lang - lang - 14
fix travis build
[ travis ] Remove 10 . 1 . 0 . Final to travis . 0 . 0 . Final
<UNK> : <UNK> jdk
Upgrade to ES 0 . 10 . 0
gh - <UNK> - Fixed typo in accumulo @ store
<UNK> Copyright Copyright 2016 2016
fix typo in accumulo test
<UNK> the accumulo store store
rest rest rest rest to rest
gh - 471 - updated travis script
gh - <UNK> - fixed typo in accumulo io
gh - <UNK> - optimiseSchema store . optimiseSchema . optimiseSchema . optimiseSchema . optimiseSchema . optimiseSchema . optimiseSchema (); to use the optimiseSchema optimiseSchema optimiseSchema optimiseSchema <UNK> <UNK>
ignore the nbproject / nbproject / gitignore
Removed ant logging
Try to fix travis CI
fix import
[ maven - release - plugin ] copy for tag lenskit - 0 . 1
<UNK> the warn
fix plugin - info - info
remove unused import
<UNK> guide for wiki
log log
release ' 0 . 24 . 0 '
Fixed incorrect <UNK> in CHANGELOG . md
release ' 0 . 10 . 0 '
add mavenCentral mavenCentral mavenCentral mavenCentral <UNK>
release ' 0 . 87 . 3 '
Upgrade to Spring 3 . 2 . 14 . RELEASE
[ pom ] Update mybatis to 3 . 0 . 5
Upgrade to Spring 4 . 2 . 2 . RELEASE
Upgrade to bitcoinj 0 . 7 . 3
add <UNK> test
remove test - context dependency
fix test
javamelody javamelody core - core to 1 . 65 . 0
complments tests unitaires
javadoc
update swing plugin
<UNK> -> author
Added a comment to the <UNK> <UNK> <UNK>
<UNK> <UNK>
add missing <UNK>
<UNK> <UNK> <UNK> <UNK> to localhost the <UNK> <UNK>
Fixed <UNK> utils
<UNK> git ignore
updated ChangeLog
Moved zlibrary . util . util . util . util . util . util . util . util . util . util . util . util . ZLAndroidMainWindowUtil . ZLAndroidMainWindowUtil . ZLAndroidMainWindowUtil . ZLAndroidMainWindowUtil . ZLAndroidMainWindowUtil
updated ChangeLog
updated ChangeLog
updated TODO
TODO
rename assets to match location
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
Updated changelog
updated TODO
updated ChangeLog
updated ChangeLog
updated sort to android
updated ChangeLog
updated ChangeLog
updated ChangeLog
remove unused import
remove unused line
updated TODO
<UNK> : fix NPE in onInterceptTouchEvent action
Updated CMakeLists Wall Wall Wall Wall Wall Wall <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Removed unused assert
Added close () to close ()
Fixed <UNK> <UNK> in MainActivity
[ maven - release - plugin ] prepare release sql2o - 1 . 1 . 0
<UNK>
Added missing KVDocument name to kvdocument kvdocument KVDocument KVDocument <UNK> <UNK> can be <UNK>
[ <UNK> - <UNK> ] <UNK> the <UNK> debug when a <UNK> <UNK>
<UNK> <UNK> to StringBuilder <UNK> <UNK>
fix group
Updated binaries
Updated binaries
Updated binaries
Edited wiki page ReleaseNotes through web user interface
Edited wiki page Downloads through web user interface
Edited wiki page AutoGenerateAttributes through web user interface
Edited wiki page About through web user interface
Removed a <UNK> settings
<UNK> <UNK>
[ BZ - <UNK> ] <UNK> release <UNK> release to release
<UNK> : fix <UNK> . contains ()
add dexlib2 jar
Updated classpath
fixed NPE in AST null
<UNK> : <UNK> Windows , added Windows , case
fixed a bug in Debug Debug Debug <UNK> <UNK>
add myself
Updated CHANGES . txt
[ maven - release - plugin ] prepare release msgpack - 0 . 6 . 5
[ maven - release - plugin ] prepare release msgpack - 0 . 6 . 6
modified CHANGES . txt
Added log for <UNK>
prepare for depth depth depth depth depth <UNK>
remove unused import
[ Gradle Release Plugin ] - new version commit : ' 1 . 4 . 8 - SNAPSHOT '
Removed unnecessary jar
<UNK> version
fix : key key
Upgrade gradle wrapper
<UNK> <UNK>
update logs
update docs
added configure lintOptions lintOptions lintOptions lintOptions lintOptions lintOptions <UNK> <UNK>
fix crash in chat chat
Fixed layout in layout
fix crash in chat chat
<UNK> the <UNK> to the <UNK>
Upgrade to gradle 4 . 9
Added link to the list
<UNK> gradle . gradle
<UNK> the jar
<UNK> jar
Updated build tools
remove unused proguardFiles proguardFiles proguardFiles proguardFiles it ' :// github . com / WhisperSystems / TextSecure / issues / <UNK>
<UNK> <UNK> . odt . odt . odt .
<UNK> armeabi armeabi armeabi armeabi <UNK> )
<UNK> cleanBuild cleanBuild cleanBuild delete
updated screenshot
update travis
<UNK>
added javadoc
Updated pom . xml to 11 - parent
[ maven - release - plugin ] prepare for next development iteration
prepare for 2 . 9 . 6
fix test
Added missing Inamura Inamura to CONTRIBUTORS CONTRIBUTORS - 10 - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK>
Upgraded <UNK> to 3 . 5 . 1
<UNK> trusty trusty trusty trusty trusty <UNK>
Added <UNK> to ProjectRole pRole <UNK>
configandusage snapshot . md
fixed test
Added <UNK> . png
Added known known known doc
fix <UNK> <UNK>
update README
Fixed <UNK> <UNK> in <UNK>
Updated changelog
Bumped version to 4 . 0 . 0 - b1
add note to changelog
Fixed Xbox <UNK> <UNK>
Updated changelog
Updated changelog
Fixed <UNK> <UNK> <UNK> <UNK>
Updated changelog
Updated changelog
<UNK> : fix TH TH TH TH TH Panasonic <UNK>
Updated changelog
Updated changelog
<UNK> the visibility of the <UNK>
Updated changelog
Updated changelog
Bumped version to 3 . 0 . 0 - a3
Adds ext ext ext ext ids to ext - header
README : add API documentation
Fixed bug in spi spi spi <UNK> <UNK>
Added test
target post - build - build - build
fix for Handler Handler - <UNK> - <UNK>
add <UNK> to hide <UNK>
fix />--> />--> />--> />--> notifications
changelog Former - commit - id : <UNK>
<UNK> : <UNK> <UNK> <UNK>
fixed listView listView listView listView listView listView <UNK>
<UNK>
changelog Former - commit - id : <UNK>
<UNK> : <UNK> <UNK> <UNK>
progress_bar layout
changelog Former - commit - id : <UNK>
fix for animation Former - commit - id : <UNK>
<UNK> Former - commit - id : <UNK>
changelog Former - commit - id : <UNK>
changelog
fix <UNK> <UNK>
<UNK> : <UNK> -> contains <UNK>
update README
<UNK> upload
Removed unused line
Adding Steven Siahetiong Siahetiong Siahetiong Siahetiong github . com
<UNK> <UNK> 11
Updated exposed build tools
//
fix <UNK> <UNK>
push version
add javadoc
jmx
Using 1 . 6 . 1
update gradle
<UNK> the <UNK> in mongodb mongodb mongodb by default to <UNK>
Making abstract public public
Updated documentation to basics minimal sprite 2D - <UNK> : <UNK> : <UNK> / <UNK> @ <UNK> . com >
fix <UNK> <UNK>
<UNK> the optional optional for the <UNK> <UNK>
fix : newest newest newest newest <UNK>
Added debug . keystore to . gitignore
add repo
logo
Updated launcher icon
[ artifactory - release ] Next development version 3 . 2 . 0 . BUILD - SNAPSHOT
[ artifactory - release ] Next development version
[ artifactory - release ] Next development version 3 . 1 . 0 . BUILD - SNAPSHOT
<UNK> <UNK> . reportSubscriptionSet () is null
[ artifactory - release ] Release version 3 . 1 . 6 . RELEASE
[ artifactory - release ] Release version 3 . 1 . 0 . M1
img
Upgrade to <UNK> 1 . 2 . 5
gradle : Update android build plugin
[ maven - release - plugin ] prepare release avaje - ebeanorm - 6 . 16 . 4
[ maven - release - plugin ] prepare release avaje - ebeanorm - 4 . 5 . 3
[ maven - release - plugin ] prepare release avaje - ebeanorm - 4 . 1 . 5
[ maven - release - plugin ] prepare release avaje - ebeanorm - 4 . 5 . 5
update gitignore
<UNK> : Fix <UNK> <UNK>
<UNK> mapping . txt
debug apk
add Readme
javadoc
<UNK> : fix byte byte getSegmentList byte getSegmentList byte ) ' t be byte
<UNK> <UNK>
Updated documentation to http Old Documentations Documentations Documentations <UNK> )
Added missing Jenkins for robobinding Jenkins
working on version to 0 . 8 . 14
<UNK> 2 . 1 . 0 - SNAPSHOT
docker README
docker README
<UNK> : add a missing NetworkSpec abstract
// <UNK>
<UNK> building a requires version
Added port to the <UNK>
fix EA EA EA 6 . 1
module to fix <UNK> quickstarts quickstarts <UNK>
pom : fix CompareTest CompareTest CompareTest CompareTest CompareTest unit
readme
Updated docs to match the <UNK> version
add gateway gateway gateway gateway gateway gateway <UNK> )
dependencies on archetype
Removed an unnecessary Ignore to SelfUpdateTest test
Removing the profile to the profile
[ <UNK> - <UNK> ] fix for <UNK>
[ fabric - <UNK> ] insight insight dependency in fabric - pom
[ FABRIC - <UNK> ] <UNK> examples in fabric - itests - demo
[ jboss - fuse - 6 . 1 . x 070 ] Updating perfectus - build number to new build
[ pom ] Remove fabric8 - vertx - vertx - vertx to fabric8
[ jboss - fuse - 6 . 1 . x 113 ] Updating perfectus - build number to new build
[ activemq - <UNK> ] <UNK> activemq activemq activemq activemq activemq <UNK> <UNK> <UNK> is <UNK>
fixed a bug in SeleniumTests return
upgrade to kubernetes - assertions 2 . 0 . 17
[ pom ] Remove profile from release
[ jboss - fuse - 6 . 1 . x 171 ] Updating perfectus - build number to new build
<UNK> the process test to the project
Moved openshift . sh to start . sh
[ jboss - fuse - 6 . 1 . x 139 ] Updating perfectus - build number to new build
[ Java ] Add missing activemq activemq version to 5 . 12 . 1
<UNK> the default revision for the <UNK>
Added a comment to the <UNK>
docs
rename processManager . md
<UNK> the c24io test test
add image
update plugin
<UNK> : fix get_realpath get_realpath get_realpath get_realpath get_realpath <UNK>
travis : add travis behavior
fix test
<UNK> <UNK> to setJob <UNK> <UNK>
<UNK> test
<UNK> the <UNK>
add <UNK>
update README
fix <UNK>
fix coll coll coll coll coll coll coll coll coll isEmpty coll CommonHelper CommonHelper )
[ <UNK> ] <UNK> : fix mDelegated mDelegated mDelegated mDelegated <UNK> to <UNK>
add config repo
update gradle
Added <UNK> icons
sample - 1 . 3 . 3 [ ci skip ]
fix travis build
fix name in userprofile name
Added a tag to the image
travis : use travis build
fix links in links
Added image to the travis build
minor , add elasticsearch cache
fix gradle build
runtime - core : Fix typo in DbmsMetadataHandler tables metadata
runtime - core : Fix typo in runtime - parent - sql
runtime - config : Add missing HasEnabled HasEnabled HasEnabled PrimaryKeyColumn <UNK> <UNK>
Removed BooleanExpressionComplexity BooleanExpressionComplexity BooleanExpressionComplexity BooleanExpressionComplexity BooleanExpressionComplexity BooleanExpressionComplexity <UNK> )
[ PATCH <UNK> / 153 ] <UNK> : <UNK> import
<UNK> : add a null e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e
Added <UNK> . hbase . tar
fix Shi contributors
Added the logger to the log4j . properties
removed mysql - connector dep from jdbc - pom
<UNK> : fix <UNK> dictionary
fix deploy . sh
minor , fix test test
[ maven - release - plugin ] prepare for next development iteration
Translated using Weblate ( Serbian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Romanian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( <UNK> ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add circle file
fix <UNK>
v2 . 29 . 1
Translated using Weblate ( Japanese ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( Chinese ( Simplified )) Currently translated at 100 . 0 % ( 151 of 151 strings )
add index . html
Translated using Weblate ( Japanese ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Fixed issue with <UNK> <UNK> on <UNK>
Fixed <UNK> <UNK> in <UNK>
Updated version number
Fixed issue with <UNK> <UNK> on <UNK>
Added svnhook svnhook svnhook svn changeset : <UNK> / svn branch : 6 . 0
Added <UNK> test
Added commons - io dependency to 1 . 3 . 1
[ maven - release - plugin ] prepare for next development iteration
fix Dorg Dorg Dorg Dorg Dorg Dorg Dorg Dorg <UNK>
[ maven - release - plugin ] prepare release pushy - 0 . 6 . 1
[ maven - release - plugin ] prepare for next development iteration
Added example_4 example_4 example_4 . png
Bumped version to 0 . 4 . 0
Removed example example
Removed <UNK> <UNK> <UNK>
update pom
Updated pom version to 0 . 2 - SNAPSHOT
TODO
added missing scoring scoring scoring scoring scoring <UNK> can be done
<UNK> upgrade
Utils Utils warn
<UNK> <UNK> <UNK> if <UNK> is null
Updated <UNK> . properties
Removed unused font font
Added mapping mapping
Fixed <UNK> <UNK>
Added <UNK> <UNK> to the <UNK>
<UNK> <UNK> <UNK>
Updated <UNK> Version
Updated to latest version
Updated README
Updated gitignore
fix <UNK>
removed <UNK> from <UNK>
bump to 6 . 12 . 29
updated copyright to 2016 Lukasz
Added a <UNK> file to the <UNK>
Added problem
Added problem
//
remove apk
remove Gradle Gradle
updated 2 . jpg
Updated to next development version : 1 . 1 . 1 - SNAPSHOT
build
Upgrade to buildToolsVersion 19 19 . 1 . 0
travis : update travis tools version
Updated gitignore
Fixed typo in CHANGELOG
<UNK> travis build
update README
Fixed <UNK> version in version of <UNK>
[ BZ - <UNK> ] avoid <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
[ RESTEASY - <UNK> ] <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Fixed build build
spec to fix spec in spec
remove compileJar compileJar compileJar compileJar Jars Jars Jars <UNK> , it does not be <UNK>
Updating to bom version 1 . 15 . 39 - SNAPSHOT
Updating to bom version 1 . 14 . 87 at 2017 - 10 - <UNK> : 52 : 39 . <UNK>
Updating to bom version 1 . 14 . 96 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
[ queue ] Add missing component
removed unused checkWritePositionHeaderNumber checkWritePositionHeaderNumber checkWritePositionHeaderNumber assert is already already already already already already already already <UNK>
<UNK> - threads : Move dependency
Updating to bom version 1 . 15 . 26 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
Updating to bom version 1 . 14 . 82 - SNAPSHOT
Updated lang to 6 . 7 . 6
remove test
<UNK> <UNK>
Updated travis build tools
add apk
fix height size in <UNK>
Updated version number
[ Java ] Fix <UNK> <UNK> in <UNK>
<UNK> the gradle branch
test : Move MethodValuesSerializer test
[ CALCITE - <UNK> ] Add cstring cstring cstring cstring cstring <UNK>
[ Java ] Update version to 1 . 5 . 4
[ Java ] Upgrade to Mockito 1 . 10 . 19
[ Java ] Upgrade to Mockito 2 . 2 . 19
Updated to Spring <UNK> 3 . 0 . 2
<UNK> <UNK> to indent indent indent - <UNK> , not not be used in the <UNK>
Removed unnecessary description
removed logging
fixed python % version
fix eclipse eclipse local local local local local
python python python image
fix typo in <UNK>
Removed unused import
add img
fix NPE when <UNK> is not found
rename commit
add ... to README
Removed maven - gradle - plugin from configure
[ Gradle Release Plugin ] - new version commit : ' 1 . 56 . 48 - SNAPSHOT '
[ maven - release - plugin ] prepare release astyanax - 1 . 0 . 1 - SNAPSHOT
Added idea plugin to build
<UNK> the <UNK> instruction instruction the <UNK> instruction instruction instruction <UNK>
Added a <UNK> to the <UNK> <UNK>
Added maven - surefire - plugin to the <UNK> plugin
add <UNK> to Plugin
Update the latest version
<UNK> : Fix an bug in grpc grpc ByteBuf <UNK> <UNK> <UNK>
Update the project version to 0 . 70 . 0 - SNAPSHOT
added <UNK>
<UNK> . xml : <UNK> targetSdkVersion targetSdkVersion 18 <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
NOTICE
Removed debug statement
jacoco tests
working on Selenide 3 . 2
working on Selenide 3 . 7
upgrade to info gradle . 1 . 10
<UNK> : add trusty trusty trusty to trusty trusty <UNK>
<UNK> gitlab . 9 . 1 for 8 . 9 . 1
Removed unused import
[ maven - release - plugin ] prepare release javafaker - 0 . 5
[ maven - release - plugin ] prepare release javafaker - 0 . 4
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare release javafaker - 0 . 15
Updated pom to 0 . 7 . 0 - incubating - SNAPSHOT
Upgrade to pentaho - aggdesigner - algorithm 5 . 1 . 5 - jhyde
[ CALCITE - <UNK> ] Fix <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Updated version
fix test
remove println
[ Gradle Release Plugin ] - new version commit : ' 10 . 0 . 0 - M5 '
Upgrade to <UNK> 6 . 2 . 1
add missing Exception for Exception
fix test
add git central
<UNK> the <UNK> of the <UNK>
wrapper
bump <UNK> version
added isDeprecated isDeprecated ()
<UNK> the <UNK> - scm - scm to groovy
<UNK> test case
Removed unused import
Removed unused import
[ Java ]: <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Fixed <UNK> <UNK>
added <UNK> origin origin . <UNK>
Removed debug statement
Fixed NPE in Invoker TODO
added toString () to expr toString
remove NOTICE from NOTICE
Updated since version
add <UNK> status
<UNK> the <UNK> of the feed
Upgrade to <UNK> 1 . 5
<UNK> the sqlitejdbc v056 jar
<UNK> : fix <UNK> when <UNK> is null
Fixed <UNK> <UNK>
updated start jar
Fixed <UNK> <UNK>
add docker . compose . yml
<UNK> out the travis script
trying to fix out out . out . println
Removing a mockserver from the pipeline - v - a build script
Updated README . md
add . editorconfig editorconfig utf - 8
[ <UNK> - <UNK> ] avoid <UNK> <UNK> in <UNK>
[ maven - release - plugin ] prepare for next development iteration
Removed <UNK> from <UNK>
Upgrade to android gradle build
fix : fix okdownload test okdownload okdownload <UNK> <UNK> is not <UNK>
Update the gen coregraphics gen
<UNK> : add GIT_TAG GIT_TAG b45b5347a6e80ebc346195e6432167586d59b97b b45b5347a6e80ebc346195e6432167586d59b97b b45b5347a6e80ebc346195e6432167586d59b97b <UNK> . <UNK> . com / <UNK> / <UNK> - <UNK>
fixed javadoc
Updated version to 1 . 7 . 1 - SNAPSHOT
Fixed test test
yaml yaml
fix typo in ThingManager ThingManager () (# <UNK> ) Signed - off - by : <UNK> <UNK> < <UNK> @ <UNK> . de >
fix getThing test
Moved test to test
<UNK> : add <UNK> SmartHome Karaf Karaf Karaf <UNK> )
[ Java ]: Removed model . AutoUpdateGenericBindingConfigProvider . java . item
fix typo in model . runtime Signed - off - by : Kai Kreuzer < kai @ openhab . org >
added missing myself
<UNK> : Fix <UNK>
[ maven - release - plugin ] prepare release v0 . 4 . 12
[ maven - release - plugin ] prepare release v0 . 2 . 12
recycler recycler view
update README
updated okhttp 3 . 7 . 0
Updated README . md
Updated jabref_tr . properties Translated the most recent entries to Turkish
added gen translation
Added missing suite to imports
Added splash splash splash 0beta 0beta - <UNK> - 0beta
v2 . 5 . 8
Upgrade to Spring Boot SR3 1 . 5 . 6
bump version number
<UNK> : fix <UNK> <UNK>
<UNK> <UNK>
travis - dev : Update Java version to pip python version
Upgrade to Gradle 4 . 5
<UNK> . status : project . status
added missing <UNK> to <UNK>
[ maven - release - plugin ] prepare release unirest - java - 1 . 4 . 0
[ README ] Update junit to 4 . 12
[ maven - release - plugin ] prepare for next development iteration
Added travis build
[# <UNK> ] <UNK> : updated test fixture
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare for next development iteration
Added a files
docker maxwell
v0 . 10 . 0 - RC4
add inter service
add a test
fix for <UNK>
upgrade open - replicator
upgrade open - replicator
<UNK> swp . swp
upgrade jar
[ RESTEASY - <UNK> ] <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
build . gradle : <UNK> . addReleaseBranchPattern . addReleaseBranchPattern . <UNK>
requestCount stats stats stats stats requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount requestCount <UNK> # <UNK>
<UNK> <UNK> to be <UNK> (# <UNK> ) Change - Id : <UNK>
<UNK> svn changeset : <UNK> / svn branch : 6 . 7
<UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
<UNK> to 5 . 3 . 0 - trunk_custom_build
Fixed typo in <UNK> Change - Id : <UNK>
Fixed bug in VSlider VSlider style (# <UNK> ) Change - Id : <UNK>
Added a connector to <UNK> (# <UNK> ) Change - Id : <UNK>
added hot hot replace to <UNK>
datefield datefield datefield - svn - by : protostuff . googlecode . com / svn / trunk @ <UNK> 1731708e - d1f7 - 11de - a1df - 87ee4daaac7b
added requestRepaint requestRepaint requestRepaint requestRepaint requestRepaint <UNK> svn changeset : <UNK> / svn branch : 6 . 7
Fixed typo in javadoc svn changeset : <UNK> / svn branch : trunk
Added " optimization " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " "
<UNK> : fix typo in URL
<UNK> git - svn - id : https :// tests . googlecode . com / svn / trunk @ <UNK> 1731708e - d1f7 - 11de - a1df - 87ee4daaac7b
Upped VERSION svn changeset : <UNK> / svn branch : 6 . 5
Fixed NPE in Slot orderedlayout caption (# <UNK> ) Change - Id : <UNK>
Upped VERSION svn changeset : <UNK> / svn branch : 6 . 6
<UNK> 5 . 2 . 0rc7
Fixed a bug in setPushConnection pushConnection pushConnection <UNK> Change - Id : <UNK>
Fixed a bug in <UNK>
Removed init - build to init
Updated release notes
Added Brakes Brakes Brakes Brakes syntax to <UNK>
Updated maven - resources - plugin to 2 . 6
Removed println svn changeset : <UNK> / svn branch : 6 . 0
fixed NPE in IndexedContainer null svn changeset : <UNK> / svn branch : trunk
Moved <UNK> to <UNK> svn changeset : <UNK> / svn branch : 6 . 7
svn changeset : <UNK> / svn branch : trunk
<UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
Added a comment to the <UNK> <UNK> <UNK> (# <UNK> ) Change - Id : <UNK>
<UNK> <UNK> margins margins layout svn changeset : <UNK> / svn branch : trunk
Added removeComponent removeComponent removeComponent removeComponent removeComponent svn changeset changeset t t t t t trunk
Fixed bug in <UNK> Change - Id : <UNK>
<UNK> <UNK> if <UNK> is not found svn changeset : <UNK> / svn branch : trunk
Fixed a bug in IUriFragmentUtility <UNK> svn changeset : <UNK> / svn branch : trunk
Added schema central badge
DisallowKeywordValidator . validate : <UNK> : Remove comment
AtomicNodePathProvider . AtomicNodePathProvider . <UNK> : AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider . AtomicNodePathProvider
<UNK> annoyingly annoyingly annoyingly above option
<UNK> native . sqlitejdbc . sqlitejdbc . dll
fix <UNK> logging
[ <UNK> - <UNK> ] <UNK> Programming Programming Programming Programming Endpoint <UNK> <UNK>
Reviewed comments
Reviewed comments
Updated asciidoctorj - pdf - 15 to 1 . 5 . 0 - alpha . alpha . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 . 15 .
upgrade hibernate - jpa - 2 . 0 - api to 2 . 1 - api
fix : <UNK> <UNK>
remove guava
fix : drl drl drl drl drl drl drl drl drl drl drl drl drl drl drl drl . optaplanner
add gitignore
[ Java ] Remove comment
Added travis - ci build file
Added test test to pom
[ maven - release - plugin ] prepare release v2 . 1 . 14
remove <UNK> from dispose
<UNK> <UNK> - parent - with version to 7 . 0 . 0 - SNAPSHOT
[ BZ - <UNK> ] fix <UNK> <UNK> when <UNK> <UNK> in the <UNK>
add sisu - guice - cipher dependency to kie . xml
[ DROOLS - <UNK> ] remove println in <UNK> . out
move test to test
fix ReadMeDrools ReadMeDrools docs
[ DROOLS - <UNK> ] avoid <UNK> <UNK> in <UNK>
[ BZ - <UNK> ] <UNK> <UNK> <UNK> to be <UNK> <UNK>
[ BZ - <UNK> ] turn imports
[ DROOLS - <UNK> ] avoid <UNK> <UNK> when <UNK> <UNK> in <UNK>
Removing unused import
[ DROOLS - <UNK> ] remove System . out . println to System . out
update README
fix codes codes codes codes codes codes codes <UNK> # <UNK>
Added Compiling Compiling Compiling running README
added json . json
update readme
readme
Updated README
Removed <UNK> from init
Added tempFile dfsdfdsfdasfdsfdsfdasfsdfdf dfsdfdsfdasfdsfdsfdasfsdfdf dfsdfdsfdasfdsfdsfdasfsdfdf dfsdfdsfdasfdsfdsfdasfsdfdf dfsdfdsfdasfdsfdsfdasfsdfdf
<UNK> : fix <UNK> pom
Updated gradle_plugin release tools
Added run . sh
Bumped version to 0 . 6 . 0
update jabbarc
Added android badge
Added Screenshots sample screen
<UNK> <UNK>
debug . xml : Add missing entry for processing . copyAttributes
<UNK> : Fix <UNK> address when <UNK> <UNK>
[ Gradle Release Plugin ] - new version commit : ' 2 . 4 - SNAPSHOT '
add <UNK> to index index
jacoco
[ Gradle Release Plugin ] - new version commit : ' 2 . 4 - SNAPSHOT '
[ Gradle Release Plugin ] - new version commit : ' 2 . 4 - SNAPSHOT '
<UNK> : <UNK> <UNK> <UNK> <UNK>
add fastlane fastlane fastlane fastlane fastlane fastlane <UNK> <UNK>
<UNK> version
intellij intellij . xml
Added method to the <UNK>
add <UNK>
fix typo in plugin script
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Azerbaijani ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Taiwan )) Currently translated at 100 . 0 % ( 1595 of 1595 strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add German item
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Taiwan )) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Slovenian ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( 3424 of 3168 strings )
Fixed typo in <UNK>
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hebrew ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate
fix null pointer
Translated using Weblate ( Catalan ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Azerbaijani ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( 3424 of 3168 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Serbian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Lithuanian ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix <UNK> <UNK>
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 76 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Czech ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Basque ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Greek ) Currently translated at 52 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Turkish ) Currently translated at 10 . 9 % ( <UNK> of <UNK> strings )
Committed translation ( hi hi <UNK> )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Turkish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Lithuanian ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( <UNK> ) Currently translated at 100 . 0 % ( 991 of 991 strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add <UNK> - core - core - jar . 0b4 . jar
Committed translation ( mr mr <UNK> )
Translated using Weblate ( Catalan ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( 2331 of 2331 strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 %
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Fixed <UNK> icon
Removed unused import
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Turkish ) Currently translated at 10 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovenian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add missing <UNK>
Translated using Weblate ( Lithuanian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( 1847 of 1847 strings )
Translated using Weblate ( French ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( 3424 of 3168 strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Icelandic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( 1847 of 1847 strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 62 . 1 % ( <UNK> of <UNK> strings )
<UNK> : fix an NPE in StreamBasedTerminal StreamBasedTerminal null
remove unused import
<UNK> the stopScreen flush ( boolean )
[ maven - release - plugin ] prepare release lanterna - 2 . 1 . 8
Updated README . markdown
//
upgrade README
<UNK> : <UNK> <UNK> <UNK>
Removed font size
Updated samples . AbstractFormatExampleConstants_fr . properties to match the <UNK> <UNK>
<UNK> : fix an locale in I18N selection
<UNK> : fix <UNK> . java ()
Updated README . txt
[ <UNK> - <UNK> ] Fixed NPE in GWTRunner GWTRunner <UNK>
added integration . xml to integration . xml
<UNK> <UNK>
Removed unused model
Fixed <UNK> <UNK> |$ |$ |$ |$ <UNK> <UNK> |$ |$ <UNK> <UNK> |$ |$ <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Added problem case
Moved green green green tests svn changeset : <UNK> / svn
<UNK> : Fix <UNK> <UNK>
Updated <UNK> . fst
remove @ Override
added <UNK> to ZipBreakException <UNK> <UNK>
Updated gradle tools version to 26 . 0 . 1
Releasing v0 . 1 . 18
exclude travis travis
Removed unused import
gitignore
Opening up v0 . 2 . 10 for development
Updating to bom version 1 . 14 . 68 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
Fixed ChronicleMapBuilder ChronicleMapBuilder <UNK> in ChronicleMapBuilder sample
Fixed a typo in ChronicleMap the comment
<UNK> : add <UNK> to TCPSocketReplication3VoidValueTest test
Fixed a bug in the <UNK>
Added a <UNK> method to the <UNK>
Fixed issue with <UNK> <UNK>
fix <UNK>
fixed <UNK> <UNK>
Updating CHANGELOG for 1 . 0 . 2 release
<UNK> the package
TODO
Removed <UNK> from <UNK>
removing unused test
<UNK> Member memberData memberData memberData memberData memberData <UNK> <UNK> ()
pre build
build . sh : build . sh
remove log log
release 1 . 16 . 7
bump pre
Upgrade to Spring Cloud 1 . 0 . 2 Closes gh - <UNK>
gh - 471 - <UNK> travis
Updates libjitsi . jar ( built on
Updates libjitsi
<UNK> - keyring - keyring - keyring - keyring - keyring - svn :// osmand . googlecode . com / svn / trunk @ <UNK> <UNK> - <UNK> - <UNK> - <UNK> - <UNK>
Added libjnsctp libjnsctp libusrsctp libusrsctp libusrsctp libusrsctp libusrsctp . <UNK>
update gitignore
commands
fix test
add changelog
add missing <UNK>
Update 5 PieChart . md
Added NewApi NewApi SuppressLint NewApi NewApi context
Updated hgignore hgignore target
Updated lombok lombok plugin to 0 . 9 . 6
add README
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK>
fixed <UNK> tx
updated jar
<UNK> <UNK>
<UNK> : fix <UNK> <UNK> when <UNK> is not <UNK>
Added <UNK> to IRefreshView IRefreshView <UNK> <UNK>
add missing <UNK>
remove unused import
remove ( ignore )
add missing import
<UNK> the Deleting expired Deleting uploader uploader uploader uploader <UNK> uploader uploader <UNK>
add log to log
fix <UNK>
<UNK> <UNK>
bump version
set default <UNK>
path to add action action
<UNK> the <UNK> in the <UNK>
<UNK> : <UNK> <UNK> to Throwable panel
Updates libjitsi . jar to <UNK>
<UNK> the <UNK> in the chat room
Added a <UNK> to the lastIndexOf lastIndexOf className lastIndexOf lastIndexOf lastIndexOf lastIndexOf lastIndexOf lastIndexOf lastIndexOf lastIndexOf lastIndexOf lastIndexOf lastIndexOf . e )
Fixed typo in currently <UNK>
Updates libjitsi . jar to <UNK>
<UNK> the size of the account window
Updates ice4j . jar to <UNK>
Updates libjitsi . jar to <UNK>
Updates the <UNK> 7zS 7zS to the <UNK> <UNK>
javadoc
Updates smack . jar to <UNK>
Fixes a typo in the <UNK>
<UNK> the <UNK> in the ldap ldap ldap is <UNK>
jabber the chat room room room room
remove unnecessary bundle
fixed <UNK> <UNK>
Updates gibberish icon
gitignore
<UNK> for <UNK>
add getThemePart getThemePart ()
Moved 2ed 2ed 2ed 2ed 2ed 2ed <UNK> )
Updated readme
Updated syncthing to v0 . 14 . 13
Bumped version to 0 . 7 . 17
Updated description
Bumped version to 0 . 8 . 8
Updated syncthing to v0 . 14 . 13
Updated Syncthing to v0 . 14 . 40
Bumped version to 0 . 8 . 6
Updated jackson version
<UNK> <UNK> . nls . <UNK>
added link to the copy of the yaml2jmxtrans doc
fixed test
v1 changelog
updated skin version
<UNK> <UNK> default
[ pom ] Add release since it is currently manually manually copying
<UNK> the libs in the <UNK>
added toString () to <UNK>
[ pom ] Add jetty dependency
fix context uriEncodedClientUserDetailsService uriEncodedClientUserDetailsService uriEncodedClientUserDetailsService ref
<UNK> <UNK> to introspect verifying verifying verifying verifying verifying <UNK> <UNK> <UNK> <UNK>
Adds . springBeans springBeans . springBeans to connect
added <UNK> to private_key_jwt private_key_jwt <UNK>
<UNK> callerinfo height
add lealone lealone sqlshell bin
Added images
Added cheat cheat cheat cheat cheat cheat cheat google google - google - <UNK> - plugin - by -
bump version
Updated build tools
fix NPE in <UNK>
Removed unused <UNK> method
Added a missing <UNK> for javadoc
remove unused import
interface
Added a method to the <UNK> getCurrentStackTrace getCurrentStackTrace getCurrentStackTrace getCurrentStackTrace <UNK> <UNK>
Fixed issue with <UNK> <UNK> on iOS
Added a method to the <UNK>
Updated nokia theme to <UNK>
Updated version
Updated version
Fixed issue with <UNK> <UNK>
<UNK> the <UNK> to the <UNK>
Fixed issue in Oauth2 <UNK>
Fixed a bug in <UNK>
Fixed a bug in prefix
Fixed issue with UIBuilder Resources Resources Resources Resources Resources Resources Resources Resources Resources Resources Resources Resources Resources ]
fix <UNK> <UNK>
fix <UNK> <UNK>
Added ignition ignition ignition ignition core - core
remove support support
add apk
add tools to pom . xml
<UNK> : Fix <UNK> test
<UNK> the <UNK>
Removed unused import
Edited release notes
Removed <UNK> from <UNK>
Added todo
<UNK> : <UNK> <UNK> <UNK> is null
[ Gradle Release Plugin ] - new version commit : ' 0 . 1 . 4 - SNAPSHOT '
Moved example to java
Added stresstest logs for <UNK>
Removed unused test
fixed test case
Removed unused dependency
added junit dependency
Updated <UNK> . properties
Removed unused import
fix tasks /{ tasks
Upgrade to postgresql postgresql postgresql jre7 jre7 jre7 jre7 <UNK> , gh - <UNK>
ignore release
[ pom ] Update jmockit 1 . 26
[ pom ] Update tomcat8 to 8 . 0 . 53
[ pom ] Update tomcat8 to 9 . 0 . 6
Updated build version
Added <UNK> for ]] ]] uname
update README
add note about valued valued column
remove unused import
Updated README
mysql
remove GOOGLE_SQL_INSTANCE spark Makefile Makefile Makefile <UNK> <UNK>
vw install - local - vw / install . sh to fix <UNK> <UNK>
Updated seldon - parent - client to version 1 . 4 . 4
add <UNK>
Fixed <UNK> <UNK>
Added selected linear selected color
[ Gradle Release Plugin ] - new version commit : ' 1 . 2 . 7 - SNAPSHOT '
fixed config
<UNK>
DistinctSpliterator . characteristics : DistinctSpliterator . characteristics () <UNK> <UNK> <UNK> <UNK> : DistinctSpliterator . <UNK> () <UNK> : DistinctSpliterator . javax () <UNK> : DistinctSpliterator . javax () <UNK> <UNK> <UNK> <UNK> <UNK> : <UNK> : <UNK> : <UNK> : <UNK> : <UNK>
gh - <UNK> - added javadoc to the <UNK>
Initialise update <UNK>
updated store version
Added gradle - build . build . gradle
fix true on BufferedRestClient BufferedRestClient
upgrade to Spark 1 . 6 . 2
manifest for elasticsearch elasticsearch elasticsearch elasticsearch elasticsearch elasticsearch <UNK> in the <UNK>
[ pom ] Update maven - surefire - plugin to 2 . 14 . 1
[ pom ] Update jacoco - maven - plugin to 0 . 6 . 4 . 201312101107
gitignore
upgrade support
rename Apache License License License License <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Removed group from build
<UNK> the travis build
<UNK> the <UNK> test
[ pom ] Update derby </ 10 to 10 . 14 . 1 . 0
fix <UNK> <UNK>
<UNK> : add proguard version
complments tests unitaires
javadoc
update collector - parent - server to 1 . 6 . 0
extra travis build
Fixed <UNK> <UNK>
Updated the <UNK> library to the <UNK> <UNK>
Added translation
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
Added filter script
updated ChangeLog
updated ChangeLog
<UNK> : fix NPE when <UNK> is null
[ maven - release - plugin ] prepare release sql2o - 1 . 0 . 1
<UNK> <UNK> "?" relation relation relation relation relation already <UNK> "?" already relation "?" already <UNK> already <UNK> already <UNK>
fix travis snapshot
<UNK> the <UNK> script in the <UNK> script
Edited wiki page FrontPage2 through web user interface
<UNK> <UNK> to paddleG null - <UNK>
updated jar
<UNK> : fix bug in FastHierarchy FastHierarchy - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> = <UNK>
fixed <UNK> wrong wrong
add <UNK> . pdf
<UNK>
<UNK> the param to setTimeout param
fix NPE in RealmRecyclerViewAdapter null
Added travis build status
Added lintOptions lintOptions lintOptions lintOptions a <UNK>
// the razerdp razerdp razerdp razerdp <UNK>
Removed unused import
add Scans Barcodes description
<UNK> : fix null pointer on <UNK>
<UNK> <UNK> - app - app - app - app - app - app - app - app - app - app - app - app - app - app - app - <UNK> - <UNK> - app - app - app - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - plugin - plugin - plugin - plugin - plugin
Added arch arch arch arch arch arch arch <UNK>
example example
[ maven - release - plugin ] prepare for next development iteration
add travis CI
<UNK> . txt : test_maps test_thread_map . cpp . cpp
apk
updated jar
icon
[ BZ - <UNK> ] <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK>
Added codegen_login codegen_login codegen_login codegen_login . png
upgrade gradle build tools to 2 . 1 . 0
Updated changelog
Fixed <UNK> <UNK> <UNK> in <UNK>
Updated changelog
Updated changelog
<UNK> Panasonic TV Panasonic TV Panasonic
<UNK> : fix TH TH TH TH TH Panasonic <UNK>
todo
Removed unused setUpDrawer setUpDrawer
<UNK> the <UNK> Former - commit - id : <UNK>
Fixed <UNK> margin in <UNK>
<UNK> <UNK> <UNK>
Upgrade <UNK> - jar to 1 . 7 . 2
Added image
fix for <UNK> when <UNK> is not <UNK> Former - commit - id : <UNK>
fix for <UNK>
changelog Former - commit - id : <UNK>
changelog
fix enabled gradle
add maxSdkVersion 25 25
README
push version
style : add hover
Added Images Images Images Images Images Images Images svn svn 100 100 , 0 / <UNK> / <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK>
remove unused import
[ artifactory - release ] Release version 3 . 0 . 0 . RC2
[ artifactory - release ] Release version 3 . 0 . 0 . RELEASE
added Ignore to FluxPublishOnTest test
fix test
1 yml : Remove 1 . 6
[ maven - release - plugin ] prepare release avaje - ebeanorm - 4 . 7 . 2
[ maven - release - plugin ] prepare release avaje - ebeanorm - 3 . 2 . 3
[ maven - release - plugin ] prepare release avaje - ebeanorm - 4 . 5 . 6
findbugs : fix findbugs . google . client . client . client . client . client . client . client
compileSdkVersion compileSdkVersion 25 25
<UNK> : fix <UNK> . getIdentifier . <UNK> () is called
Updated version to 2 . 4 . 2
Fixed typo in DockerClient <UNK>
<UNK> : fix an bug in config
add README
Added screens
[ jboss - fuse - 6 . 1 . x 075 ] Updating perfectus - build number to new build
add . idea to . gitignore
Using arquillian scope - weld - embedded - 1 . 1 . 0 to <UNK> - 1 . 0 . 0
Upgraded to ES 0007 0007 0007 0007 <UNK>
<UNK>
[ jboss - fuse - 6 . 1 . x 119 ] Updating perfectus - build number to new build
fix git origin push origin push
[ Java ] Use <UNK> to workflows maven - <UNK>
[ <UNK> - <UNK> ] <UNK> <UNK> <UNK> <UNK> <UNK>
[ BZ - <UNK> ] <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK>
[ FABRIC - 671 - 671 - Ignore - FABRIC - ExampleCamelProfileTest - ExampleCamelProfileTest - FABRIC - FABRIC - ExampleCamelProfileTest basic
Added dataImage docker . dataImage to version 0 . 9 . 10
gitignore
[ maven - release - plugin ] prepare for next development iteration
javadoc : add comment about linearly linearly linearly <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
update README
fix README
add missing Ninux Ninux map
fix gradle build
Fixed a typo in InetSocketAddressHelper @ parse
fix <UNK> <UNK>
minor , fix cache
<UNK>
<UNK> the <UNK> pending <UNK>
added 1024 SPLIT_SIZE 1024 1024 1024 1024 <UNK> ) :// :// github . com / <UNK> / <UNK> / issues / <UNK>
add timeout to README
<UNK> : fix <UNK> . run ()
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
release
Translated using Weblate ( Romanian ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( Russian ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( <UNK> ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Turkish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Fixed issue with <UNK> <UNK>
Translated using Weblate ( Chinese ( Simplified )) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( Japanese ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Updated gradle version
Updated gradle version
Updated CONTRIBUTING . md
add screenshot
Added a comment to the <UNK>
add imgs show
Added a opacity opacity opacity connection to the connection
fix : null . java . <UNK>
whack whack whack - svn - id : https :// build . googlecode . com / svn / trunk @ <UNK> 3b38d51a - 9144 - 11de - a1df - 87ee4daaac7b
Fixed a bug where an <UNK> <UNK>
update lang
Answers Euler Euler Euler Euler . com / <UNK> / Answers / <UNK> / <UNK>
// README
added mysqlSQL30 Mysql Mysql mysqlSQL30 mysqlSQL30 Mysql picked by by :// github . com / <UNK> / <UNK> - <UNK> -
fix syntheticcontrol algorithm algorithm algorithm fuzzykmeans fuzzykmeans <UNK>
add screenshot
Added a <UNK> to the <UNK> <UNK>
Added travis - ci config file
Add a Bitdeli badge to README
added missing test
Added a Deprecated to WrappedExcerpt WrappedExcerpt Bytes Bytes Bytes Bytes Bytes Bytes <UNK> <UNK> . g
Updating to bom version 1 . 14 . 116 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
Updated to version 2 . 1 - SNAPSHOT
updated to the latest version of the version
Fixed <UNK> <UNK> when <UNK> is not being <UNK>
fix comment in comment
[ Java ] Upgrade to Mockito 2 . 7 . 22
[ Java ] Upgrade to Mockito 2 . 22 . 0
[ Java ] Upgrade to Mockito 2 . 5 . 5
[ Java ] Upgrade to Mockito 2 . 6 . 8
[ Java ] Upgrade to Mockito 2 . 2 . 26
added javadoc
Added missing <UNK> to the <UNK>
Fixed typo in PrimitiveValue IllegalArgumentException
fix Exception of Exception of ExecuteEclim ExecuteEclim ExecuteEclim Exception
fix TagList_title TagList_title TagList_title TagList_title <UNK>
<UNK> the classpath
Fixed <UNK> <UNK>
<UNK> the <UNK> to 1 . 0 . 0 . BUILD - SNAPSHOT
<UNK> : <UNK> <UNK> . status
<UNK> <UNK> <UNK>
release Selenide 4 . 2
Fixed typo in <UNK>
[ maven - release - plugin ] prepare release javafaker - 0 . 14
[ maven - release - plugin ] prepare for next development iteration
[ pom ] Update cobertura - maven - plugin to 2 . 7
[ CALCITE - <UNK> ] <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK> <UNK> = <UNK>
Fixed NPE in <UNK>
fix test test
<UNK> example
fix Grant McConnaughey McConnaughey McConnaughey McConnaughey McConnaughey McConnaughey McConnaughey # <UNK> )
Fixed NPE in AsmClassGenerator collection
Removed build . bash
<UNK> . jar : version to version version of version . xml
Removed unused import
Fixed issue with <UNK> <UNK> in GrblController <UNK>
[ maven - release - plugin ] prepare release mockserver - 2 . 5
docker - compose : Add new mockserver mockserver to docker - compose
[ maven - release - plugin ] prepare release mockserver - 2 . 5
Added okdownload okdownload okdownload okdownload okdownload okdownload runtime works
updated screenshot
Fixed <UNK> <UNK>
upgrade to play - services - 7 . 5 . 0
Updated README . md
fix typo in <UNK> Signed - off - by : <UNK> <UNK> < <UNK> @ <UNK> . de >
fix build build
[ maven - release - plugin ] prepare release v0 . 1 . 10
updated jar
added missing crowdinUpload apiKey apiKey apiKey apiKey apiKey <UNK>
Fixed <UNK> <UNK>
[ Java ]: Add Xlint Xlint Xlint Xlint Xlint Xlint Xlint <UNK>
Removed unused <UNK>
<UNK> out the <UNK>
[ Gradle Release Plugin ] - pre tag commit : ' 0 . 22 '
update wiki
[ maven - release - plugin ] prepare release unirest - java - 1 . 4 . 4
remove unused import
Updated travis
Added link to default <UNK> svn changeset : <UNK> / svn branch : trunk
<UNK> <UNK> to IFilterSelect TODO svn changeset : <UNK> / svn branch : trunk
<UNK> new version
<UNK> : Change <UNK> Change - Id : <UNK>
Added a Deprecated to the Deprecated
Upped VERSION svn changeset : <UNK> / svn branch : 6 . 5
Fixed <UNK> tabs in <UNK> . tabsheet
Added a comment to the <UNK> (# <UNK> ) Change - Id : <UNK>
Fixed a bug in <UNK> svn changeset : <UNK> / svn branch : trunk
Modified tabsheet height to height in <UNK> svn changeset : <UNK> / svn branch : trunk
<UNK> : <UNK> <UNK> <UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
add archetype versions to numbers
ValidatorFactory : <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> is <UNK>
gh - <UNK> - added hg scm to scm
add Linux
<UNK> class
<UNK> the default max to 1 , so it are set
fix typo in Programming groups
add From . txt for resources
<UNK> : fix <UNK> test
add link to jenkins - kieci - rhcloud . com
make SolutionDescriptor SolutionDescriptor SolutionDescriptor Serializable Serializable <UNK>
[ maven - release - plugin ] prepare for next development iteration
remove duplicate kie - maven - plugin from drools - pmml - plugin
runExamples . bat : Prevent the terminal window to disappear before the user has seen the user message
<UNK> the setName test to Scenario test
[ kie - <UNK> ] add resource . apache to kie . ci
Added a permission to the permission
added json . json
gitignore
<UNK> version to 0 . 5
upgrade min . css
add <UNK> index index
Added description about Google Play Play Play Play Play Play Play Play Play Play Play
<UNK> : Move <UNK>
fix test
Removed <UNK> <UNK>
add README
gif
remove gitignore
add deprecated Deprecated to plugin
fix <UNK> <UNK>
<UNK> : fix a bug when <UNK> is <UNK>
//
Removed unused import
fix example
AutoloadingIssuesInspector index : <UNK> . add " index " " " " " " " " " " "); "); "); "); "); "); <UNK> )
Translated using Weblate ( French ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Turkish ) Currently translated at 0 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of 641 strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Azerbaijani ) Currently translated at 98 . 9 % ( <UNK> of 2331 strings )
Translated using Weblate ( Arabic ) Currently translated at 0 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( 2357 of 2357 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( 2331 of 2331 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
added <UNK> <UNK> to <UNK>
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Greek ) Currently translated at 52 . 1 % ( <UNK> of 3102 strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( <UNK> ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( <UNK> ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 99 . 9 % ( <UNK> of 3458 strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hebrew ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Japanese ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix layout in layout
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hungarian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 99 . 9 % ( <UNK> of 3458 strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 2000 of 2000 strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( pl )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Azerbaijani ) Currently translated at 98 . 9 % ( <UNK> of 2331 strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 2095 of 2095 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( lt )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Bulgarian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Persian ) Currently translated at 43 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( 1848 of 1848 strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( bg )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
use_high_res_maps use_high_res_maps use_high_res_maps use_high_res_maps use_high_res_maps <UNK> <UNK>
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate
fix for <UNK> <UNK>
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Belarusian ( latin )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( lt )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Taiwan )) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Lithuanian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 99 . 9 % ( <UNK> of <UNK> strings )
Committed translation ( pt )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Fixed <UNK> be <UNK>
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Azerbaijani ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 1628 of 1595 strings )
Translated using Weblate ( Greek ) Currently translated at 52 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of 641 strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix NPE in AdvancedEditPoiFragment category
Added translation using Weblate ( Korean )
[ maven - release - plugin ] prepare release lanterna - 2 . 1 . 1
[ maven - release - plugin ] prepare release lanterna - 3 . 0 . 0 - alpha6
<UNK> the <UNK> is null
Made the <UNK> <UNK> to be <UNK>
Removed a Thread Thread to the JUnitShell Thread
Added a comment to the <UNK>
removed unused fail
fixed NPE in TeeHttpServletResponse writer
fix cleanup
updated to v0 . 4 . 4
Updated CHANGELOG
<UNK> the unique unique unique unique necessarily not not state
Fixed 40 40 40
Removed <UNK> - files to audiotool doc
<UNK> the ngram package in the ngram ngram package
Fixed a bug in SimpleFrontEnd SimpleFrontEnd sphinxProperties sphinxProperties <UNK> <UNK>
Removed an <UNK> method
Added a method to the SphinxProperties SphinxProperties SphinxProperties SphinxProperties SphinxProperties SphinxProperties Decoder Decoder can can throw an javadocs
Opening up v0 . 2 . 11 for development
Fixed NPE in <UNK>
Releasing v0 . 2 . 1
Opening up v0 . 1 . 19 for development
<UNK> tests
<UNK> : <UNK> <UNK> test
Added alignment to ReplicatedChronicleMap entry
add install - Host - install
update gitignore
<UNK> setup
fix <UNK> error
remove unused dependency
<UNK> picture to images
Updating CHANGELOG for 1 . 0 . 2 release
update
Updating CHANGELOG for 1 . 0 . 1 release
added comment for 6 arguments die ORG ORG <UNK> - <UNK> - <UNK> / issues / <UNK>
fix incorrect <UNK>
Added travis CI to travis
Updating to spring - cloud - contract 1 . 2 . 1 . RELEASE
Upgrade to Spring Cloud 0 . 2 . 3 Closes gh - <UNK>
Upgrade to Spring Cloud 2 . 0 . 0 . RELEASE
Upgrade to Spring Cloud 5 . 21 . 0 Closes gh - <UNK>
Upgrade to Spring Boot 1 . 4 . 5 . RELEASE
Upgrade to Spring Cloud 1 . 1 . 1 . RELEASE
<UNK> travis build
Added libusrsctp libusrsctp libusrsctp libusrsctp libusrsctp libusrsctp . <UNK>
Updates jar to <UNK>
Updates libjitsi
[ maven - release - plugin ] prepare release libjitsi - api - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub - stub -
<UNK> : <UNK> <UNK> Jingle RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager RawUdpTransportManager ))
add missing <UNK>
<UNK> : make private constructor
<UNK> <UNK> this
fix for <UNK>
Changes
<UNK> the <UNK>
changelog
fix <UNK>
javadoc
fix TODO
Upgrade to postgresql postgresql 9 . 4 . 1209 . jre6 . jre6
fix : <UNK> <UNK>
fix : <UNK> <UNK> <UNK>
apk
[ maven - release - plugin ] prepare release mango - 1 . 3 . 1
[ maven - release - plugin ] prepare release mango - 1 . 12
fix typo in README
add new guide_credentials guide_credentials guide_credentials guide
Updated launcher icon
<UNK> : <UNK> <UNK> icon
Added a missing setBlockBounds setBlockBounds setBlockBounds setBlockBounds setBlockBounds setBlockBounds 0 . 0F . com / <UNK> - 0 / 0 / 0 / 0 . 9375F
<UNK> <UNK> to 11
config
Release 0 . 0 . 5 - SNAPSHOT
git ignore
Updated md
upgrade storm dependencies
Upgrade build tools
Added screenshot_0 screenshot_0 screenshot_0 screenshot_0 screenshot_0 .
Added SD SD SD SD SD SD <UNK>
Updated README . md
bump version
<UNK> date
fix s3Files s3Files isEmpty isEmpty s3Files data
//
remove <UNK> so it ' s not <UNK>
<UNK> the <UNK> . getProperty . <UNK> . separator . line . line . separator . separator . separator . separator . separator . separator . separator . separator . separator . separator . separator . separator . separator . separator
Added Proxy Proxy Proxy Proxy sipaccregwizz sipaccregwizz . <UNK>
<UNK> the theme theme
<UNK> version to IS_NIGHTLY_BUILD IS_NIGHTLY_BUILD VersionImpl true
Updated JainSipApi1 jar library
Updates ice4j . jar to <UNK>
Updates libjitsi . jar to <UNK>
Fixed <UNK> chat button on chat window
Updates the <UNK> image
Updates ice4j . jar to <UNK>
fix ScLo logging in ScLo logging
Updates ice4j . jar to <UNK>
Updates libgrowl4j . dylib . dylib . dylib . <UNK> .
<UNK> <UNK>
fixed a NPE in MediaControl null
<UNK> the <UNK> button on the chat window
Updates libjitsi . jar to <UNK>
<UNK> <UNK> from chat <UNK>
Added a order to the <UNK> <UNK>
getVal getVal getVal getVal getVal / <UNK> / docx4j / <UNK> - <UNK>
rename docx4j
Added gitignore
Signed - off - by : Jeeeyul < jeeeyul @ gmail . com >
fix <UNK>
<UNK> : Only 300 300 abandonedtimeout 300
<UNK> : fix <UNK> from <UNK>
travis : fix travis build
Added idea files to gitignore
Updated README
fix for <UNK>
<UNK>
fix saveOrUpdate 1 session
log log
[ pom ] Update lombok </ 1 . 12 . 2
<UNK> 4 . 1 . 0 - SNAPSHOT
<UNK> if null
add . DS_Store to . gitignore
<UNK>
<UNK> <UNK>
added missing <UNK> to <UNK>
Updated the properties lib
<UNK> the showing <UNK>
added missing InvalidKeyException InvalidKeyException key
fix <UNK>
Fixed issue with iOS themes
Added a <UNK> to the <UNK>
fixed issue with <UNK> <UNK>
Fixed issue with <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
removed TODO to the <UNK>
Updated gitignore
fixed nokia themes
Updated version
Updated nokia theme to <UNK>
fix : <UNK> <UNK>
pom . xml : add <UNK> . xml
add a log
fix NPE in dataset
fix <UNK> test
<UNK> : fix <UNK> <UNK>
fix tabs
Edited release notes
Added TODO
Added TODO
[ Gradle Release Plugin ] - new version commit : ' 0 . 1 . 18 - SNAPSHOT '
Added OSSMETADATA osslifecycle osslifecycle archived to ignore
[ Gradle Release Plugin ] - new version commit : ' 0 . 1 . 11 - SNAPSHOT '
Updated README
bump 1 . 0 . 0
added missing <UNK> to ProcessDefinition <UNK>
fix DbSqlSessionFactory DbSqlSessionFactory DbSqlSessionFactory register
<UNK> version of travis
<UNK> <UNK> lock log
<UNK> : fix edge module
fix : <UNK> executor executor
<UNK> cycle - webapp - cycle - cycle
upgrade commons - beanutils to 1 . 8 . 3
remove unused import
[ CALCITE - <UNK> ] Update classes . properties to classes . properties
[ pom ] Update tomcat8 to 8 . 0 . 52
[ pom ] Remove jspc - compiler - tomcat7 to jspc jspc - compiler - tomcat8
[ pom ] Update maven - compiler - plugin to 3 . 6 . 0
[ pom ] Update dependency - check - maven to 1 . 4 . 1
Fixed a bug in clear
header
<UNK> <UNK> <UNK> <UNK> <UNK>
updated version
Updated the tablesaw tablesaw tablesaw tablesaw jar to tablesaw tablesaw jar
<UNK> travis build
Fixed initial_setup memcached memcached memcached dbcp dbcp <UNK>
gitignore
Added CircleCI circleci circleci circleci circleci circleci <UNK> )
Added . gitattributes behavior to . gitattributes
update NLPIR - ICTCLAS - ICTCLAS - <UNK>
<UNK> the visibility of the <UNK>
Removed <UNK> TODO
Updated version to 3 . 3 - SNAPSHOT
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 1 . 51 '
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 2 . 21 '
add myself to README
added a test for the <UNK> <UNK>
dependency to fix version of servlet - api
gh - <UNK> - Fixed bug in operation
gh - 471 - updated travis script
<UNK> / <UNK> / / / moxie / xml / xml / <UNK>
<UNK> the <UNK> in the <UNK>
upgrade to ES 1 . 0 . 0 . Beta2
update docs
<UNK> test
Updated gitignore
add apollo request README
fix <UNK> <UNK>
Added maven - site - plugin to maven
fixed <UNK> ( <UNK> )
<UNK> version
added comment
[ pom ] Update mybatis to 3 . 0 . 4
Upgrade to Spring 4 . 2 . 3 . RELEASE
<UNK> <UNK>
<UNK> <UNK> <UNK>
Updated README . md
updated ChangeLog
fixed incorrect <UNK>
remove unused import
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated TODO
<UNK>
<UNK> : fix <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
<UNK> <UNK> <UNK>
Updated pom version
<UNK> the Linux Linux to Linux
add <UNK> - files
fix gradle gradle
[ feature ] Remove comment
[ maven - release - plugin ] prepare release sql2o - 1 . 0 . 2
[ maven - release - plugin ] prepare release sql2o - 1 . 0 - beta2
Updated version number to 0 . 40
remove unused import
db : Update version to 3 . 4 . 4 - byteafix
Added a info to the <UNK> <UNK>
Removed unused import
Removed oraclejdk7 from travis
Edited wiki page Benchmark through web user interface
Edited wiki page DeduplicationStrategies through web user interface
<UNK> : <UNK> <UNK>
Added jar to the jar
<UNK> <UNK>
fixed <UNK> <UNK>
add baksmali 1 . 3 . 2
Statement unnecessarily nested within null clause
Updated plugin to eclipse / index . html
[ pom ] Add maven - surefire - plugin to <UNK>
Added a toString toString ( StringBuilder StringBuilder StringBuilder <UNK> )
add archived archived type to wfe_type type
Updated sura_names item
Updated to the <UNK> version
update readme
Fixed crash in chat chat
Upgrade to 4 . 2 . 1 - SNAPSHOT
[ readme ] <UNK>
<UNK> <UNK>
fix typo in README
Preparing release
[ pom ] Update RoaringBitmapParent 0 . 6 . 61
[ 0 . 7 . 1 ] upped version
<UNK>
upgrade version number
Updated pom . xml to 3 . xml
[ maven - release - plugin ] prepare release jackson - core - 2 . 0 . 2
Updated release
fixed typo in comment
Updated copyright to 2 . 0
Updated README . md
springside springside jar
fix <UNK> sqlite clean sqlite clean
Fixed <UNK> <UNK>
Updated changelog
Updated changelog
Fixed <UNK> <UNK>
<UNK> CHANGELOG
fix : <UNK> . net . net to maven - <UNK> - plugin
Updated changelog
Added screenshot
updated res
hide scrolling when <UNK> is clicked Former - commit - id : <UNK>
changelog
Fixed margin in sw600dp header
todo
todo
todo
<UNK> : fix <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Fixed <UNK> <UNK>
<UNK> travis build
Removed Daniel Daniel Daniel Daniel <UNK>
add CHANGELOG to CHANGELOG . md
add <UNK> download
fix <UNK> <UNK>
fix crash when <UNK> is not found
add a only add rCH speakers would native would native file
update README
bump version
fix <UNK> height in compliance
showOwnership showOwnership showOwnership put <UNK> to <UNK>
fix : <UNK> launchMode launchMode launchMode launchMode <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
<UNK> <UNK>
Added <UNK>
[ artifactory - release ] Next development version
[ artifactory - release ] Next development version 3 . 1 . 9 . BUILD - SNAPSHOT
<UNK> <UNK>
[ Gradle Release Plugin ] - new version commit : ' 3 . 0 . 0 . BUILD . BUILD '
[ artifactory - release ] Next development version
[ maven - release - plugin ] prepare release avaje - ebeanorm - 4 . 1 . 2
Added build - cache - cache to . gitignore
sleep if the reload is <UNK>
Updated launcher icon
Added myself to pom . xml
<UNK> : Fix <UNK> . Long ()
Added description for the <UNK> . md file
[ jboss - fuse - 6 . 1 . x 096 ] Updating perfectus - build number to new build
[ FABRIC - <UNK> ] fix <UNK> <UNK> in <UNK>
[ <UNK> - <UNK> ] <UNK> <UNK> <UNK> D D <UNK>
<UNK> the Import specified of the Import specified version
<UNK> : don ' t fabric8 fabric8 plugin
[ pom ] Add OBR OBR default by <UNK>
[ jboss - fuse - 6 . 1 . x 094 ] Updating perfectus - build number to new build
Upgrade to <UNK> v0 . 5 . 3
<UNK> <UNK> <UNK>
README
Added image
Upgrade to spring - oxm - oxm 1 . 0 . 4
remove unused import
Updated gitignore
//
make the DOMMetadataResolver DOMMetadataResolver idpMetadataProvider private
remove <UNK> from OidcClient client_secret client_secret client_secret <UNK>
gradle : update version
response response response content
runtime - core : Add <UNK> to <UNK>
enums - enums - <UNK> : Fix typo in EnumGeneratorUtil constants
runtime - application : Fix typo in application . class
Added a missing pingpong pingpong pingpong pingpong pingpong pingpong pingpong pingpong pingpong pingpong pingpong twitter twitter BUILD - <UNK> - <UNK> - <UNK>
[ PATCH <UNK> / 153 ] <UNK> : bug - fix <UNK> RB_ID = <UNK> ( sapling split of <UNK> )
remove <UNK> scope
minor , fix <UNK> trace when <UNK> <UNK>
minor , fix minor in adhocquery adhocquery <UNK>
[ RESTEASY - <UNK> ] curator curator - recipes - recipes - recipes - recipes - recipes - by :// core . googlecode . com / repos / FBReaderJ / trunk @ <UNK> - <UNK> - <UNK> - <UNK> - <UNK>
remove <UNK>
Translated using Weblate ( Romanian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix <UNK>
<UNK> : Remove <UNK> content
Added <UNK> icon
Added <UNK> - jetty - plugin to 10 . xml
Fixed Delivery History History History History error
<UNK> the test
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare for next development iteration
imgs show gif
Updated repo lib
[ maven - release - plugin ] prepare release guacamole - common - 0 . 4 . 0
fix test
Updated pom
<UNK> : fix start start start
Added tar to the spec
Added missing key for <UNK>
bump to 6 . 12 . 18
[ maven - release - plugin ] prepare for next development iteration
<UNK>
add screenshot
add 2016 . md
Upgrade to VERSION_CODE 1 . 0 . 1 - SNAPSHOT
Fixed hipchat notify notify notify notify hipchat hipchat hipchat
remove license
add screenshot
sample : Fix <UNK>
<UNK> <UNK> <UNK> <UNK>
Updating to bom version 1 . 14 . 125 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
<UNK> : documentation ( cherry - off - <UNK> )
Updating to bom version 1 . 13 . 44 at 2017 - 10 - <UNK> : 08 : 39 . <UNK>
Updating to bom version 1 . 15 . 32 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
updated README
fix error in client (...) workspace
fix <UNK> buffer
log : Log log
<UNK> eclimdoc eclimdoc 1200px 1200px 1200px # <UNK> , via # <UNK> )
[ gradle - <UNK> ] <UNK> properties <UNK>
[ maven - release - plugin ] prepare release astyanax - 1 . 0 . 2 - SNAPSHOT
<UNK> : Only Navigation Navigation Navigation must ' t thread
fix build build
update docs
Update the project version to 0 . 64 . 1 - SNAPSHOT
fix checkstyle checkstyle
<UNK> on Selenide options
<UNK> '**/ '**/ AlertText AlertText <UNK>
Added missing Report Report Test to Jenkinsfile Report Report <UNK> - <UNK>
Added a missing import
javadoc
[ maven - release - plugin ] prepare release gitlab - plugin - 1 . 0 . 5
Added isTriggerOnAcceptedMergeRequest isTriggerOnAcceptedMergeRequest () to GitLabPushTrigger triggerOnAcceptedMergeRequest <UNK>
[ maven - release - plugin ] prepare for next development iteration
fix test
[ maven - release - plugin ] prepare for next development iteration
[ RESTEASY - <UNK> ] <UNK> PageReadStatus 0 . 5 . 5 . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK>
Added hide for <UNK>
add device device 145648 145648 145648 . 2016
Upgrade docker - client - 3 . 1 . 4 to 3 . 1 . 4
added <UNK> to test
removed <UNK> from <UNK>
<UNK> : add a log to the PackageHelper opening file
<UNK> 1 . 0 - beta - 8
<UNK> icon moved to <UNK>
fix layout
demo gif
Fixed a bug in model
[ maven - release - plugin ] prepare release mockserver - 2 . 5
[ mockserver - <UNK> ] Remove junit - dep to junit
Removing MockServerDHC json . json
[ maven - release - plugin ] prepare release mockserver - 2 . 7
rename home - home - home - home -
<UNK> : Fix an bug in MTLBuffer getContents . getContents ()
update README
apk
Updated version number
Added iOS layout for layout (# <UNK> ) Signed - off - by : <UNK> <UNK> < <UNK> @ <UNK> . de >
Added deprecated deprecated to ActiveItem deprecated (# <UNK> ) Signed - off - by : <UNK> <UNK> < <UNK> @ <UNK> . de >
Added dependencies to designer feature (# <UNK> ) Signed - off - by : <UNK> <UNK> < <UNK> @ gmail . com >
[ N - 0 ] refactor class
gh - <UNK> - fixed typo in README
removed unused import
add <UNK>
gitignore
add screenshot
Added link to the reference
trust trust trust - <UNK> - proxy - imaps - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> = issues
handling to add handling to TODO
added note to TODO
Removed unused import
<UNK> : fix 9922 upload builds_jabref_org upload
Updated Danish translation
<UNK> the <UNK> of the <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Fixed <UNK> <UNK>
remove task printProject printProject << << << <UNK>
[ <UNK> - <UNK> ] <UNK> <UNK> <UNK> when <UNK> <UNK> <UNK>
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare release unirest - java - 1 . 3 . 20
[ maven - release - plugin ] prepare for next development iteration
<UNK> gradle version
fix typo in <UNK>
docs : add maxwell to docs
upgrade open - replicator
upgrade open - replicator
wrapper
Fixed NPE in <UNK> () (# <UNK> ) svn changeset : <UNK> / svn branch : 6 . 7
Added image svn changeset : <UNK> / svn branch : trunk
Added <UNK> theme to <UNK> <UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
Added path to build
Added a test to <UNK>
Removed unused module svn changeset : <UNK> / svn branch : 6 . 7
Added javadoc svn changeset : <UNK> / svn branch : 6 . 3
package : svn changeset : <UNK> / svn branch : trunk
Fixed bug when <UNK> is being found svn changeset : <UNK> / svn branch : 6 . 7
<UNK> <UNK> to the sbt
<UNK> Spring <UNK> 2 . 1 . 2 - SNAPSHOT
Moved tsp tsp tsp tsp tsp tsp <UNK> )
fix resources in resources
fix typo in resources
fix : NPE when <UNK> row when <UNK> is not found
drools - svg - svg . svg
add missing 5 . 4 . 0 . Beta2 to 5 . 4 . 0
fix typo in <UNK>
[ maven - release - plugin ] prepare release v2 . 6
[ maven - release - plugin ] prepare release v2 . 1 . 7
[ maven - release - plugin ] prepare for next development iteration
[ BZ - <UNK> ] add <UNK> to drools - model
[ BZ - <UNK> ] <UNK> <UNK> <UNK> for <UNK>
Changed <UNK> to 209 209 209 50
Fixed bug in CountryService Country Country Country <UNK> <UNK>
<UNK> version to 0 . 2
Changed rest rest to rest
<UNK> the <UNK> for the <UNK>
Updated README
apk
Updated readme
<UNK> the positions positions positions positions positions as <UNK>
Fixed NPE in <UNK>
<UNK> test
[ Gradle Release Plugin ] - new version commit : ' 2 . 0 - SNAPSHOT '
<UNK> : fix <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
upgrade version number
StrlenInEmptyStringCheckContextInspection # <UNK> : StrlenInEmptyStringCheckContextInspection . getDisplayName () " <UNK> " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " "
Upgrade to 2 . 0 . 7
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 62 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( bs bs <UNK> )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Fixed issue with <UNK> <UNK>
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( 1595 of 1595 strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate
Translated using Weblate ( Slovenian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix <UNK> <UNK>
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Added missing translation for <UNK>
add missing ttsRequests 0 . 5 . 5
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( de )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 99 . 9 % ( <UNK> of 3458 strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( 1595 of 1595 strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( <UNK> ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Fixed issue with <UNK> <UNK>
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
[ maven - release - plugin ] prepare release lanterna - 3 . 0 . 0 - rc1
[ maven - release - plugin ] prepare for next development iteration
JSON sample - cells - cells - cells - id - o - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id
<UNK> the visibility of the <UNK>
Made tests to tests
Removed import to Result Result Result Result <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Adds changelog for release
<UNK> : Fix out test
[ ci ] <UNK>
1 1 . 0 . 1
added comment for <UNK>
Bumped version
fix test
prepare for notes
Added Maven >= Maven version
Upgrade to Spring Cloud 2 . 0 . 5 Closes gh - <UNK>
<UNK> : fix import
Updates libjitsi . jar ( built on
added <UNK> method to LineEndMotion <UNK> <UNK>
missing import
fix : <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Upgrade to Gradle 2 . 2
add log
add test
added missing import
added missing <UNK>
TransactionViewModel getSignature <UNK>
Updated README
<UNK> : fix test case
remove Slaves Slaves
fix NPE when <UNK> is not <UNK>
fix deploy deploy
fix blazar blazar blazar blazar blazar blazar blazar blazar blazar <UNK>
add missing url
fix curator curator curator curator curator curator curator curator curator curator curator <UNK> )
remove del del resolve
<UNK> : <UNK> location to location
Added a comment about the license service
Updates libjitsi . jar to <UNK>
Updates libjitsi . jar to <UNK>
Removed unused import
Updates libjitsi . jar to <UNK>
<UNK> the chat window to the <UNK>
Updates libjitsi . jar to <UNK>
fix typo in portaudio ifeq - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> = <UNK>
Updates libjitsi . jar to <UNK>
Added a change change to the list of the account
Upgrade to Gradle 2 . 6
fixed <UNK> <UNK>
Bumped version to 0 . 9 . 10
Bumped version to 0 . 7 . 8
Removed mips mips . . versionCode versionCode 1 versionCode versionCode 1 versionCode versionCode 1 versionCode versionCode 1 )
<UNK> the test test
<UNK> <UNK>
Added note about multi - file
[ pom ] Update ttorrent ttorrent ttorrent 1 . 1 . 3
Upgrade to liquibase - core 3 . 0 . 7
ignore nb - configuration . xml
Added N ( API )
add a missing chunkMetaData <UNK> to the <UNK>
PS PS PS PS date in cheat <UNK>
bump version
add <UNK> to README
Added <UNK>
[ project ] Update hermes 1 . 14
Changed COPYRIGHT - 2014 to 2004 2004
removed obsolete TODO
Updated <UNK> icon
fixed nokia themes
Disabling build build for travis
remove unused import
pom . xml : add missing include " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " "
<UNK> : Remove comment message
Updated README
README
[ Gradle Release Plugin ] - new version commit : ' 0 . 1 . 9 - SNAPSHOT '
<UNK> : fix NPE in <UNK>
fixed NPE in ExecutionImpl PvmException transition transition <UNK> is null
Added <UNK> . jpg
fix travis - ci build
add mapping
added bottom bottom to attrs attrs - <UNK> <UNK>
[ maven - release - plugin ] prepare for next development iteration
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 1 . 48 - SNAPSHOT '
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 1 . 49 '
Removing <UNK>
updated before / after
added a testConstructable testConstructable testConstructable test to EnumUtilsTest test
remove Next ' Next ' to userguide Lang version
[ RESTEASY - <UNK> ] remove <UNK> <UNK>
add Travis badge
Fixed noPermission noPermission noPermission noPermission noPermission noPermission <UNK>
removed <UNK>
<UNK> the sql_ spark spark spark spark
sonar sonar . forceAuthentication . forceAuthentication . forceAuthentication . forceAuthentication
<UNK> 10
<UNK> <UNK> . md
updated ChangeLog
updated ChangeLog
added <UNK> to XMLSerializer XMLSerializer book
Fixed a bug where <UNK> <UNK> <UNK> <UNK> <UNK>
[ <UNK> ] <UNK> : bug - fix close close
add image
Removed unused import
Removed unused MvccMetainfoRepository getOwner getOwner MvccMetainfoRepository MvccMetainfoRepository <UNK> can be <UNK>
Edited wiki page Downloads through web user interface
added java_cup jar
fixed bits bits false
[ maven - release - plugin ] prepare release msgpack - 0 . 6 . 9
Fixed <UNK> . monitor . monitor . monitor . schema . schema . monitor . monitor . monitor . schema
Fixed fitXY <UNK> in <UNK>
Updated README
fix crash in preference_editor preference_editor
removed unused incremental call
fix : <UNK> . serializedSizeInBytes () <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Updated h2database to 1 . 4 . 187
Upgrade to gson 2 . 7
Fixed <UNK> <UNK>
Updated changelog
Updated PS3 PS3 renderer renderer
changelog
CurrentPlaceDetailsOnMap Select Maps Maps API
update README
fix 0 . 4 . 4 . 0 . QuestsMapFragment . QuestsMapFragment . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram . tangram .
remove scm connection
update README
[ artifactory - release ] Next development version 3 . 0 . 6 . BUILD - SNAPSHOT
<UNK> on postgresql postgresql <UNK>
fix manifest
[ maven - release - plugin ] prepare release avaje - ebeanorm - 6 . 10 . 2
[ maven - release - plugin ] prepare release avaje - ebeanorm - 6 . 17 . 1
<UNK> to 2 . 11 . 1 - SNAPSHOT
updated to 4 . 17 . 5
Added isCodeReview isCodeReview isCodeReview isCodeReview isCodeReview codeReview codeReview codeReview null . com / fabric8 / fabric8 / issues / <UNK>
[ jboss - fuse - 6 . 1 . x 174 ] Updating perfectus - build number to new build
Removed unused scala . scala . scala . scala . scala . scala
fix typo in example
add javadoc
[ FABRIC - 641 ] Ignore CreateChildContainerTest CreateChildContainerTest CreateChildContainerTest CreateChildContainerTest CreateChildContainerTest <UNK>
[ artifactory - release ] Next development version
add spring - core dep
Fixed <UNK> <UNK>
restart : svn changeset : <UNK> / svn branch : trunk
added javadoc
minor , fix DEFAULT csv csv csv csv csv csv csv csv <UNK>
git ignore
<UNK> the <UNK> testing for <UNK>
add repositories to build
Translated using Weblate ( Serbian ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( Romanian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Romanian ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( Romanian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add screenshots
Updated benchmark version
Added slf4j - simple dependency to doc
pom
Added problem
add travis CI
Updated CONTRIBUTING test
Fixed <UNK> <UNK>
Updating to bom version 1 . 14 . 118 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
<UNK> : <UNK> spin yield yield yield yield yield yield # 47 )
Fixed OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit OfflineSubreddit )
Fixed zoom zoom
Updated launcher icon
Removed unused TextView TextView badgeCounter <UNK> <UNK> <UNK> <UNK>
Updated README . md
Fixed a bug where <UNK> <UNK> is not used
fix double html when <UNK> is not <UNK>
README : add _overview _overview _overview emacs emacs client
gif
Added bin bin to gitignore
release selenide 1 . 5
Travis : <UNK> chrome chrome
release selenide 2 . 25
renamed SeenideFieldDecoratorTest test
Added gitignore
upgrade to gradle 0 . 12
made init config
Added gradlew gradlew
Updated armv6hf jar
release release
<UNK> out quick_build clean is <UNK>
Added gitlab ci file
Made the method of the method of the method to the <UNK>
Updated README . md
[ maven - release - plugin ] prepare release v0 . 4 . 13
Added CHANGELOG for Remove dependency
<UNK> marker filter
Updated About
bump version to 3 . 0 . 12
[ maven - release - plugin ] prepare for next development iteration
fix maxwell
Incremented development version number to 6 . 3 . 2 . svn changeset : <UNK> / svn branch : 6 . 3
Fixed typo in <UNK> svn changeset : <UNK> / svn branch : trunk
<UNK> the <UNK> uuid uuid uuid uuid uuid
Upped VERSION svn changeset : <UNK> / svn branch : 6 . 5
Removed unnecessary System overview cluster overview cluster
fix <UNK>
docs : <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
test test
<UNK> : fix <UNK> benchmark
[ maven - release - plugin ] prepare release v2 . 8
[ BZ - <UNK> ] make KieModule KieModule <UNK> <UNK> is <UNK>
<UNK> Former - commit - id : <UNK>
upgrade min . css
added missing JsonPropertyOrder JsonPropertyOrder JsonPropertyOrder jackson
[ gradle - <UNK> ] Add <UNK> to <UNK>
Bumped version to 0 . 7 . 0
[ Gradle Release Plugin ] - new version commit : ' 2 . 0 - SNAPSHOT '
Fixed detekt detekt <UNK> <UNK>
<UNK> the documentation in the <UNK>
<UNK> : fix <UNK> title
Fixed a bug in CaptureActivity CaptureActivity <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Added projectFiles projectFiles README file
Updated <UNK> plugin to <UNK>
[ Java ]: Fixed bug when <UNK> away when <UNK> is not <UNK>
javadoc
test test
fix typo in Dockerfile
<UNK> : add FROM FROM java - jre FROM tomcat . jre . 0
remove unused import
ReturnTypeCanBeDeclaredInspector method to fix <UNK> <UNK>
[# <UNK> ] <UNK> : bug - fix <UNK>
strings : add parameter to Simplify parameter
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 2331 of 2331 strings )
Translated using Weblate ( Czech ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix <UNK>
Translated using Weblate ( Polish ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( <UNK> ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hebrew ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Upper Sorbian ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Added vist vist hldningsprofil N )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 43 . 1 % ( <UNK> of 3102 strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
<UNK> collect_legacy_libs . sh
Translated using Weblate ( Basque ) Currently translated at 52 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Azerbaijani ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( 2095 of 2095 strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 47 . 8 % ( <UNK> of <UNK> strings )
<UNK> <UNK> icon
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of 641 strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Hebrew ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
<UNK> <UNK>
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Hungarian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Azerbaijani ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovenian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add missing playAndArriveAtDestination playAndArriveAtDestination
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
60 the SUBSCRIPTION_HOLDING_TIME_MSEC test
Translated using Weblate ( Hungarian ) Currently translated at 99 . 9 % ( <UNK> of 3376 strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Latvian ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( 2357 of 2357 strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Upper Sorbian ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 100 . 0 % ( 2094 of 2094 strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of 1630 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix <UNK>
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Basque ) Currently translated at 52 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( 1738 of 1738 strings )
Translated using Weblate ( Upper Sorbian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Greek ) Currently translated at 52 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Basque ) Currently translated at 52 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix <UNK> <UNK>
Translated using Weblate ( Chinese ( Simplified )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Greek ) Currently translated at 52 . 8 % ( <UNK> of 2536 strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
[ maven - release - plugin ] prepare for next development iteration
Renaming the visibility of the DefaultLaidOutComponent DefaultLaidOutComponent DefaultLaidOutComponent DefaultLaidOutComponent LaidOutComponent LaidOutComponent LaidOutComponent LaidOutComponent LaidOutComponent LaidOutComponent lanterna of lanterna strings )
upgrade to 1 . 0 . 1
Updated gif
rename the mobilewebapp place
add a showing for <UNK> <UNK>
sample debug apk
removed unused import
<UNK> the CountingFilter CountingFilter CountingFilter CountingFilter CountingFilter CountingFilter CountingFilter <UNK> is <UNK>
javadoc
<UNK> qrcodes qrcodes qrcodes qrcodes qrcodes qrcodes qrcodes )
Updated README
Fixed a bug in language <UNK>
Fixed <UNK> <UNK> <UNK>
<UNK> <UNK> import
Removed a <UNK> () to the Microphone synchronized
Removed a test file
Removed unused comment
Fixed a typo in BatchModeRecognizer to the comment
[ maven - release - plugin ] prepare release zt - zip - 1 . 2
<UNK> : <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
copyright year
Fixed <UNK> <UNK>
unused import
add <UNK>
update README
Added missing import
Added <UNK> to ZMQ zmq zmq zmq SocketBase SocketBase <UNK> ' t <UNK> . SocketBase
AUTHORS Yarwood Yarwood Yarwood 48 : <UNK> / <UNK> / AUTHORS / detail / <UNK>
<UNK> <UNK> to set_flags set_flags set_flags <UNK>
Upgrade to gradle 1 . 3
fix <UNK> TODO
update sdks
Removed <UNK> <UNK>
Updated README
fix <UNK> <UNK>
fix test case
added stack - most - most editorconfig EditorConfig file
add 2 . 0 . 1 . 1 . 1 . 1 . 1 .
bump 1 . 16 . 11
bump 1 . 16 . 20_pre12
bump to 1 . 3 . 4
pre build
<UNK> : add get *", indices *", *", *", *", <UNK>
[ Gradle - release ] Next development version 1 . 0 . 2 . RELEASE
Updated changelog
Updates libjitsi
Updates libjitsi . jar ( built on
mvn : Updates ice4j
<UNK> : <UNK> <UNK> : <UNK> : <UNK> / + / org / org / org / org . org . jitsi / jitsi / jitsi
Travis : <UNK> <UNK>
Added gplus gplus gplus - <UNK> - <UNK> - <UNK>
fix : Fix typo in Profiler <UNK>
fix <UNK> <UNK>
fix test
scroll png
<UNK> : <UNK> <UNK> to parameter if it is not <UNK>
Fixed issue with <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
[ maven - release - plugin ] prepare release mango - 1 . 2 . 1
[ maven - release - plugin ] prepare release mango - 1 . 5 . 3
Fixed typo in example
fixed <UNK> update
Updated README . adoc
Added install this to fonts demo
gitignore
Added a README . txt
Updated the app file
<UNK> the <UNK>
Updated readme
Added atlassian - ide - plugin - xml to gitignore
<UNK> : fix <UNK> <UNK> when <UNK> is not <UNK>
apk
<UNK> : Fix <UNK> from <UNK>
<UNK> : fix <UNK> <UNK>
Added <UNK> and <UNK> <UNK>
Added spring gitignore
fix <UNK> <UNK>
added missing INVALID_REQUEST_NOOP INVALID_REQUEST_NOOP INVALID_REQUEST_NOOP INVALID_REQUEST_NOOP INVALID_REQUEST_NOOP <UNK>
fix <UNK>
added missing historyPurgingConfiguration isDeleteTaskHistoryBytesInsteadOfEntireRow isDeleteTaskHistoryBytesInsteadOfEntireRow old <UNK>
<UNK>
fix missing ... <UNK>
Fixed <UNK> <UNK> <UNK>
fix tailer tailer tailer tailer data
fix task id
<UNK> : added NightlyBuildID NightlyBuildID . java to version . java . java
<UNK> jmf jmf jmf jmf jmf <UNK> , <UNK> )
<UNK> <UNK> <UNK>
<UNK> the <UNK> window on the chat window
<UNK> the <UNK> <UNK> to the <UNK>
<UNK> the jar
Updates libjitsi . jar to <UNK>
Added a swing . swing . common . common . common . common . common . common . common . common
Added sdp jar
Updates ice4j . jar to <UNK>
<UNK> the <UNK> libraries for the <UNK> <UNK>
Updates libjitsi . jar to <UNK>
Adds a <UNK> for the <UNK> <UNK> <UNK>
<UNK> the <UNK> to the <UNK>
removed unused import
Added library gradle gradle
Signed - off - by : Jeeeyul < jeeeyul @ gmail . com >
Removed unused TODO
Bumped version to 0 . 7 . 7
Bumped version to 0 . 7 . 2
CHANGES CHANGES . txt
javadoc
Upgrade to gradle 2 . 4
<UNK> : fix an bug in Walker handling
<UNK> the test to the <UNK>
slf4j : Add slf4j - simple dependency to slf4j
container container
Updated pom to 1 . 5 . 1
fixed stack error in <UNK>
Upgrade to takari - lifecycle - plugin 1 . 10 . 1
trying to fix travis travis
removed unused private
travis : update travis build
added <UNK> - connect - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common - common -
Removed debug git - svn - id : http :// protostuff . googlecode . com / svn / trunk @ <UNK> 3b38d51a - 9144 - 11de - 8ad7 - 8b2c2f1e2016
Updated protostuff - 1 . 1 . jar to git - 1 . 1 . jar
fix callerinfo callerinfo callerinfo callerinfo callerinfo callerinfo <UNK>
Removed unused import
<UNK> <UNK>
fixed NPE in <UNK>
<UNK> the <UNK> <UNK>
Fixed bug in <UNK>
fixed <UNK>
<UNK>
[ pom ] Add full . name to project . name
<UNK> the <UNK> in the motan filter
Updated version number
Fixed issue with <UNK> <UNK>
Updated version number
Fixed issue with <UNK> <UNK> on android <UNK>
fixed a bug in android <UNK>
Fixed issue with <UNK> <UNK>
Updated nokia theme to <UNK>
Fixed issue with <UNK> <UNK>
<UNK> the <UNK> to the <UNK>
Fixed a bug in layouts
Updated version
Updated version
fixed a <UNK> play play
Updated version
* release version v1 . 6 . 0
fix <UNK> memory
fix <UNK> <UNK>
Added ignition ignition - core to ignition ignition core to ignition <UNK>
fix <UNK>
Added a missing method to tab
add link to the README
Updated to jetty version of jetty
[ maven - release - plugin ] prepare release apns - 0 . 1
Upgrade maven - javadoc - plugin from 2 . 7 to 2 . 9
fix jdbcType jdbcType jdbcType jdbcType jdbcType jdbcType jdbcType jdbcType jdbcType jdbcType jdbcType jdbcType mapping )
[ pom ] Update tomcat9 to 9 . 0 . 0 . M4
[ pom ] Update checkstyle to 7 . 6 . 1
[ pom ] Update sonar - maven - plugin to 3 . 3 . 0 . 603
[ ci ] Add javadoc
Added developer . See . org . org / wiki to web . xml
[ ci ] <UNK>
<UNK> : fix <UNK> stream
seldon python 1 . 4 . 2
seldon - cli - added import
<UNK> the minIdle minIdle minIdle minIdle Integer to 5
seldon - cli - cli <UNK> . cli
Added screenshots
Adds changelog for 1 . 0 . 25
add doc
Added AUTHORS AUTHORS AUTHORS and build scripts
<UNK> the <UNK> to the <UNK>
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 2 . 10 '
Removed gradle gradle
[ Gradle Release Plugin ] - new version commit : ' 1 . 2 . 20 - SNAPSHOT '
snapshots up snapshots
Setting the name to the . name file
add debug debug
<UNK> : fix <UNK> . config_default_ui_icon_size_dp . <UNK>
<UNK> : Fix <UNK> 2
Updated version number
[ RESTEASY - <UNK> ] Add missing Ignore
[# <UNK> ] AbstractStreamEx . identity . util : AbstractStreamEx . util
[ maven - release - plugin ] prepare for next development iteration
deploy deploy
fix snapshots in reference
[ artifactory - release ] Release version 2 . 1 . 0 . Beta2
notes for fact <<< the fact . it
<UNK> <UNK> the all all all all all all all all
release ' 0 . 84 . 0 '
Upgrade to Spring Boot 2 . 0 . 1 . RELEASE
[ pom ] Update ognl </ 3 . 1 . 7
add <UNK> to pom . xml
[ pom ] Remove spring - batch - infrastructure to spring - batch - infrastructure
removed maven - release - plugin
Added missing out of <UNK> ("# Bitcoins Bitcoins Bitcoins <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
fix NPE in BlockListFragment null
remove unused line
add messages to HtmlCoreReport displayed displayed displayed <UNK> <UNK> <UNK> <UNK> <UNK>
Removed unused export
Upgrade to jdeb 0 . 11
Added robots robots robots robots format
Added a green green green green green green green green <UNK>
imports
Added missing pattern
updated ChangeLog
Added betayota ics ics ics ics ics and git - svn - id : https :// protostuff . googlecode . com / svn / trunk @ <UNK> 3b38d51a - 9144 - 11de - 8ad7 - 8b2c2f1e2016
add missing myInfos myInfos
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated ChangeLog
updated TODO
upgrade gradle build tools to 2 . 1 . 2
[ Gradle Release Plugin ] - pre version commit : ' 1 . 0 . 0 '
<UNK> : add extensions
[ maven - release - plugin ] prepare release sql2o - 1 . 2 . 1
<UNK> : fix level level
<UNK> : <UNK> -> toString ()
add instructions
fix <UNK> on <UNK>
renaming <UNK> to <UNK>
beta1
fix crash on <UNK>
add <UNK> app
Preparing release
fix typo in colantonio test
[ 0 . 5 . 4 ] upped version
add preference
Remove unused imports
allowBackup
build . gradle
gradle : upgrade android build plugin
<UNK> safeCssText safeCssText safeCssText safeCssText safeCssText <UNK> <UNK> )
Removed <UNK> from the <UNK> directory
exclude avoid Travis failures
[ maven - release - plugin ] prepare release jackson - core - 2 . 0 . 0 - RC1
upgrade jackson - parent to 2 . 7 . 0 - rc1
added comment
Seq : add javadoc
Release 0 . 9 . 12 - SNAPSHOT
Added codegen_create_build_step4 codegen_create_build_step4 codegen_create_build_step4 codegen_create_build_step4 . png
<UNK> <UNK>
Updated changelog
<UNK> the <UNK> <UNK>
Fixed javadoc comment
Upgrade to latest automatic version
Updated changelog
Removed unused import
Upgrade to latest automatic version
broker / subscriptions : <UNK> formatter used
Upgrade to <UNK> - v4 - support
fix issue with <UNK> <UNK>
changelog Former - commit - id : <UNK>
changelog Former - commit - id : <UNK>
Remove dependency
changelog
todo
Updated readme
Updated admin . include
<UNK> : fix GLOBAL mode GLOBAL VARIABLES VARIABLES VARIABLES VARIABLES LIKE <UNK>
Updated README . md
Remove <UNK> . yml
apk
fix Play Play <UNK>
fix outlet outlet outlet section
fix <UNK>
add apk
[ artifactory - release ] Release version 3 . 0 . 1 . RELEASE
[ artifactory - release ] Next development version 3 . 0 . 0 . BUILD - SNAPSHOT
added gitignore
Using <UNK> GemFire GemFire GemFire GemFire GemFire GemFire <UNK> <UNK>
Upgrade gradle build tools
[ maven - release - plugin ] prepare release avaje - ebeanorm - 6 . 4 . 1
[ maven - release - plugin ] prepare release avaje - ebeanorm - 7 . 4 . 1
[ maven - release - plugin ] prepare release avaje - ebeanorm - 6 . 12 . 2
[ maven - release - plugin ] prepare release avaje - ebeanorm - 6 . 2 . 2
Upgrade library - version to 2 . 7 . 0b1
Upgraded to new <UNK>
Added a comment that that <UNK> fabric8 found
[ jboss - fuse - 6 . 1 . x 036 ] Updating perfectus - build number to new build
Updated repo
[ FABRIC - 521 - 521 - Ignore . itests - 521 - smoke - smoke - FABRIC : https :// FABRIC . googlecode . com / browse / phonegap - plugins / issues / 44 - 9144 - 11de - 8ad7 - 8b2c2f1e2016
Updated h2database . xml
Upgraded to new <UNK>
[ FABRIC - <UNK> ] feature fabric - maven - proxy to the manifest
Added registry registry registry
[ mq - <UNK> ] fix for <UNK>
[ FABRIC - <UNK> ] <UNK> <UNK> <UNK> when <UNK> <UNK>
[ jboss - fuse - 6 . 1 . x 067 ] Updating perfectus - build number to new build
Added a build . properties file to the cache
Added a cache to the travis build
parameterName parameterName parameterName parameterName parameterName : <UNK> : http :// : . . . com
fix test
javadoc
sample - 1 . 0 . 3 [ ci skip ]
fix AAA BaseUserRole end of the end of the <UNK>
fix activated activated activated activated activated activated activated activated <UNK> <UNK>
fixed DAO DAO DAO DAO DAO DAO <UNK>
renamed <UNK> to conf
Updated Dockerfile
[ parent - join ] add runtime . join
runtime - <UNK> : Fix <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
runtime - compute : Fix <UNK>
remove 1 . insertionSort . md
added close open open files to JarBuilder moveFile moveFile moveFile moveFile <UNK> <UNK> ' t <UNK>
<UNK> : fix <UNK> on <UNK>
fix channel session
DEFAULT DEFAULT DEFAULT datatype datatype DEFAULT DEFAULT Signed , ]( https :// 100 . com / repos / FBReaderJ / trunk @ <UNK> 6a642e6f - d1f7 - 11de - a1df - 87ee4daaac7b
minor , fix minor in AggregationGroup AggregationGroup
ThisBuild hadoopRelease hadoopRelease <UNK> - plugin from seq <UNK>
build - example : Move package - example - example to build
<UNK> the pigtutorial pigtutorial pigtutorial . jar
update README
add listitem listitem listitem layout
Translated using Weblate ( Estonian ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
v2 . 30 . 0
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( Ukrainian ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Chinese ( Simplified )) Currently translated at 100 . 0 % ( 170 of 170 strings )
Updated manifest
<UNK> iw item
Updated gradle version
Added svnhook svnhook svn changeset : <UNK> / svn branch : 6 . 0
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
[ benchmark ] Add benchmark benchmark to benchmark
<UNK> : <UNK> 2 . 1 . 3
Added <UNK> to the <UNK>
fix incorrect log
<UNK> the <UNK> <UNK>
updated jar
fix <UNK>
<UNK> <UNK>
Fixed problem with <UNK> <UNK>
Added p048 hs hs hs hs - off - by : Cai < kai < openhab @ 163 . com >
add hibernate hibernate hibernate hibernate hibernate hibernate <UNK> # <UNK>
Updated to next development version : 1 . 3 . 0 - rc1 - SNAPSHOT
<UNK> the build every every every every every every every every every every
update gradle
<UNK> emulator
updated version to versionCode scoops 1 . 0 . 0
git ignore
Updated test to 1 . 2 . 2
Updating to bom version 1 . 14 . 89 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
added missing @ Ignore (" fails on test , 407 issues
Updating to bom version 1 . 14 . 97 at 2017 - 10 - <UNK> : 36 : 39 . <UNK>
Fixed issue with <UNK> <UNK>
Fixed issue with <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
add missing link
[ Java ] Fix typo in <UNK>
fix typo in sbe error
README
[ Java ] Upgrade to Mockito 2 . 7 . 9
fixed : <UNK> <UNK> <UNK>
fix <UNK> <UNK>
Bumped version to 1 . 4 . 9
vcs vcs E117 vcs vcs type is not <UNK>
added <UNK> test
<UNK> <UNK>
add README . md
add travis - ci build
Updated gitignore to latest version
README
<UNK> 8 . 8 . 5
fix test
fix result in readme
Fixed NPE in <UNK>
[ Java ]: <UNK> <UNK> to classes
added javac javac name to build
<UNK> : <UNK> <UNK>
Added getter for <UNK>
<UNK> <UNK>
releasing version number
remove spurious System . out . println
fix ruby mockserver mockserver
Added mock mock mock mock mock
Added working directories to gitignore
Removing travis_build . sh
Removed test script
bump version
Add a dependencies to the dependencies
fixed <UNK> <UNK>
remove <UNK>
[ maven - release - plugin ] prepare release v0 . 1 . 11
remove sample module
<UNK> the feature_sets legomena legomena legomena legomena legomena <UNK> in the <UNK> . xml
<UNK> <UNK> <UNK>
Removed <UNK> <UNK>
Updated build script
<UNK> tcc path to tcc tcc tcc admin - admin - admin
[ maven - release - plugin ] prepare for next development iteration
removing travis linux linux
[ maven - release - plugin ] prepare for next development iteration
fix : <UNK> . getAvailableConcurrentCalls . getAvailableConcurrentCalls . <UNK> . <UNK> . <UNK> . <UNK> . <UNK> . <UNK>
v0 . 11 . 0 - PRE2
upgrade open - replicator
fixed <UNK> <UNK>
replicator jar
Fixed bug in <UNK> # <UNK> svn changeset : <UNK> / svn branch : 6 . 7
<UNK> the theme - compiler - compiler - compiler - compiler - compiler
Fixed bug in checkbox <UNK> (# <UNK> ) Change - Id : <UNK>
Removed functions functions functions functions functions <UNK> <UNK> <UNK> <UNK>
<UNK> : fix <UNK> 100 100 <UNK> svn changeset : <UNK> / svn branch : trunk
Added icon to the <UNK> theme
Added a missing license to the VPasswordFieldPaintable VPasswordFieldPaintable svn changeset : <UNK> / svn branch : 6 . 7
fixed NPE in IExpandLayout expandedWidget expandedWidget svn changeset : <UNK> / svn branch : trunk
Fixed NPE in root <UNK> (# <UNK> ) svn changeset : <UNK> / svn branch : 6 . 7
Fixed <UNK> <UNK> width to <UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
Fixed a bug in VOrderedLayout VOrderedLayout <UNK> <UNK> svn changeset : <UNK> / svn branch : 6 . 7
<UNK> : <UNK> <UNK> <UNK>
add TODO
[ maven - release - plugin ] prepare release v2 . 1 . 9
[ maven - release - plugin ] prepare release v2 . 7
[ maven - release - plugin ] prepare release v2 . 6
[ maven - release - plugin ] prepare for next development iteration
[ BZ - <UNK> ] add missing org . kie . scanner . optional to drools - compiler - compiler osgi
[ <UNK> - <UNK> ] fix kmodule packages in kmodule kmodule - plugin - by : <UNK> < kmodule - openhab . org
gitignore
remove Repository Repository wide wide wide wide wide wide <UNK> )
rename test
[ <UNK> - <UNK> ] fix import in <UNK>
Updated README
<UNK> vPROJECT_VERSION vPROJECT_VERSION via countries
add ]() ]() ]() ]() ]() following <UNK>
Add a few <UNK> test
Fixed <UNK> <UNK> <UNK>
<UNK> : fix <UNK> <UNK>
<UNK>
add codecov
Fixed <UNK> session when <UNK> <UNK>
Added description to ZipFile ZipFile . zip
Upgrade to Spring Boot 0 . 1 . 1 . RELEASE
Translated using Weblate ( Turkish ) Currently translated at 0 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Portuguese ( Brazil )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( hy )
Translated using Weblate ( Icelandic ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
fix <UNK> <UNK>
Translated using Weblate ( Bulgarian ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hungarian ) Currently translated at 99 . 9 % ( <UNK> of 2594 strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Committed translation ( es )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 98 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Catalan ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Upper Sorbian ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Slovak ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Bulgarian ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Greek ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( American )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
addCityToPreloadedList addCityToPreloadedList <UNK> <UNK>
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
add <UNK> . strings
Translated using Weblate ( Belarusian ( latin )) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix notifyFilesToUpdateChanged notifyFilesToUpdateChanged notifyFilesToUpdateChanged notifyFilesToUpdateChanged onPostExecute onPostExecute <UNK> <UNK>
Translated using Weblate ( Catalan ) Currently translated at 62 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Norwegian Bokml ) Currently translated at 100 . 0 % ( 1975 of 1975 strings )
Translated using Weblate ( Swedish ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 100 . 0 % ( 1628 of 1628 strings )
Translated using Weblate ( French ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
[# <UNK> ] DefaultTableRenderer DefaultTableRenderer <UNK> in the <UNK> <UNK>
<UNK> the pdf
Opening up v0 . 2 . 7 for development
README
add javadoc
remove unused import
uuid uuid uuid uuid uuid - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK>
fix typo in comment
Incrementing snapshot version to 1 . 0 . 2 - SNAPSHOT
<UNK> <UNK>
Upgrade to Apache Camel 2 . 18 . 2 Closes gh - <UNK>
Updated pom . xml to 1 . 6
<UNK> the <UNK> schema script
<UNK>
Updates libjitsi
fix : <UNK> <UNK> <UNK> to <UNK>
Upgrade to <UNK> 1 . 6 . 0
<UNK> version
fix test
apk
Updated version number
fix example example
<UNK> if textConfirm textConfirm <UNK> is null
<UNK> the <UNK> version of the build
added null null
Removed <UNK>
added <UNK> check to <UNK>
update config
styles <UNK> to asset asset styles
Renamed logger to BaseTrainable logger
added missing setCommand setCommand setCommand null
install the false to false
remove unused import
fix wrapper
Added java java java java to build
<UNK> the <UNK> <UNK> to the <UNK>
Updates libjitsi . jar to <UNK>
Fixed <UNK> icon
<UNK> - universe - svn :// :// :// protostuff . googlecode . com / svn / trunk @ <UNK> 3b38d51a - 9144 - 11de - 8ad7 - 8b2c2f1e2016
Removed <UNK> from picking system
Updates libjitsi . jar to <UNK>
Added missing <UNK> to the list of the list of the list
<UNK> the SIP <UNK> to the <UNK>
<UNK> the <UNK> libraries for the <UNK> <UNK>
log : Log log message
Removed unused private method
<UNK> : fix <UNK>
Fixed spelling in javadoc
<UNK> <UNK> <UNK>
Removed a <UNK> <UNK>
<UNK> <UNK>
fixed test
Added protostuff - runtime - Issue - Issue
Added package . bat to package
gh - <UNK> - updated travis tools
<UNK> <UNK>
add <UNK> to <UNK>
exclude maven - surefire - plugin plugin to 2 . 18
update core module
beta3 : <UNK> 1 . 0 . 0 - beta3
<UNK> <UNK>
Edited release notes
Upgrade to netty 3 . 2 . 4 . Final
apk
[ pom ] Update slf4j - api to 1 . 7 . 2
<UNK> : add MavenWrapperDownloader MavenWrapperDownloader >**/* MavenWrapperDownloader MavenWrapperDownloader <UNK> - <UNK>
Fixed NPE in cassandra null
bump build version
added <UNK>
update NLPIR - ICTCLAS - ICTCLAS - <UNK>
fix example example
[ pom ] Add X - Xdoclint - Xdoclint - Xdoclint - Xdoclint - by : http :// pom . googlecode . com / repos / FBReaderJ / trunk @ <UNK> 3b38d51a - 9144 - 11de - 8ad7 - 8b2c2f1e2016
// readme
remove pty4j dependency
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 1 . 56 '
pom . xml : 0 . 3 . 1 development started
fix example example
<UNK> : fix NewlineAtEndOfFile module in checkstyle
[ pom ] Update false to false
gh - <UNK> - added shaded artifactSet uk to accumulo accumulo accumulo jackson
gh - <UNK> - graph example
gh - <UNK> - Updated Builder connextTimeout connextTimeout timeout to timeout
fix up namedViewRegion namedViewRegion namedViewRegion namedViewRegion cache
fix license license
<UNK>
[ artifactory - release ] Release version 1 . 3 . 0 . M2
fix download file
[ maven - release - plugin ] copy for tag release - 0 . 3 . 1
fix secring . secretKeyRingFile
Upgrade to Spring <UNK> 3 . 0 . 5 . RELEASE
<UNK> unsigned unsigned char char NSString NSString <UNK>
<UNK> the <UNK> at the payloadOffset . length
Fixed <UNK> <UNK>
fix typo in model
imports
[ maven - release - plugin ] prepare release HdrHistogram - 1 . 0 . 9
Updated pom version
Added check for null <UNK>
Removed unused constraint
propertyName propertyName propertyName propertyName propertyName - <UNK> - pages - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> - <UNK> manifest
<UNK> the Field Field Field not fieldRef not <UNK>
<UNK> : make VirtualCalls VirtualCalls VirtualCalls class
modified CHANGES . txt
add a <UNK> to the serverAndUI Dockerfile
fix crash in <UNK>
Added <UNK> activity
fix scripted dependency in scripted scripted release
update otr4j
<UNK> the <UNK> at the <UNK>
update README
Updated CHANGELOG
Updated changelog
Added travis - ci config file
fix layout
added Other Other Other Other Other for github . com
todo
fix <UNK> str str row
fix link in README
add README
upgrade gradle build tools to 2 . 1 . 2
Removed 1 . 0 . 0 . RELEASE to 1 . 0 . 0
[ DROOLS - <UNK> ] <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
add Samples README
<UNK> 2 . 2 . 0 - SNAPSHOT
Updated gitignore
[ FABRIC - <UNK> ] <UNK> DataStoreManager <UNK> <UNK> to caching the <UNK>
[ jboss - fuse - 6 . 1 . x 172 ] Updating perfectus - build number to new build
[ FABRIC - <UNK> ] icon grafana icon
[ jboss - fuse - 6 . 1 . x 074 ] Updating perfectus - build number to new build
Added osc log file
profile
travis : remove Java environment
codegen . java : common . java ()
Updated README to 5 . 1 . 41
add default to the RangeKeyDistributionReducer cube
Added travis - ci config file
<UNK> <UNK> GraphService GraphService GraphService GraphService <UNK> )
Add a missing kylin instance to the kylin . 7 . 6
add README . md
Translated using Weblate ( Japanese ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Added banner
Translated using Weblate ( Dutch ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 % ( 0 of 0 strings ) Created new translation
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Made TextUtils TextUtils TextUtils import
Added travis CI
Upgrade to netty 4 . 0 . 18
[ README ] <UNK>
updated TODO
fix for NPE in <UNK>
fix null pointer
<UNK> : Fix typo in postinstall postinstall MESSENGER_HOME <UNK> <UNK> <UNK>
Added daocloud image
BlockPumpkin BlockPumpkin meta
add new demo demo
Made defConcern WriteConcern WriteConcern WriteConcern <UNK> ' s <UNK> '
fix doFirst doFirst doFirst doFirst release
Updated README . cn
add 2016 . md
<UNK> : fix travis build
[ <UNK> ] Fix the <UNK> <UNK> in the <UNK>
Fixed <UNK> <UNK>
Fixed a typo in GobblinAWSClusterLauncher instance
Added delete race to test
add a alert readability alert of alert docs
[ Gradle Release Plugin ] - pre tag commit : ' 1 . 56 . 44 '
Added android arsenal badge
fix test test
Updated maven plugin to 0 . 3
<UNK> <UNK>
add <UNK> for <UNK>
Updated gitignore
add <UNK> to the own core
[ project ] Remove dependency
Removed unused Bundle Bundle Bundle Bundle <UNK> can be <UNK>
Removed <UNK> from <UNK>
Updated bin to Xmx2g Xmx2g Xmx2g Xmx2g Xmx2g <UNK> <UNK> <UNK> doesn ' t <UNK> <UNK>
fix config
add _Tray Notification_ library
updated jar
Fixed bold bold bold <UNK> <UNK> in <UNK>
Added <UNK> <UNK>
Fixed bug in MassSetFieldAction MassSetFieldAction getFieldNames getFieldNames getFieldNames getFieldNames getFieldNames getFieldNames getFieldNames getFieldNames split of the <UNK> <UNK>
remove unused import
Added <UNK> to HeaderAuthentication ... <UNK>
<UNK> <UNK> <UNK> <UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
gwt version svn changeset : <UNK> / svn branch : 6 . 0
<UNK> svn changeset : <UNK> / svn branch : trunk
Removed obsolete TODO svn changeset : <UNK> / svn branch : trunk
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
plugin maven - release - plugin to maven - plugin
<UNK> the support lib
<UNK> : add trusty trusty trusty trusty trusty trusty trusty <UNK> '
[ BZ - <UNK> ] <UNK> <UNK> <UNK> <UNK> to be <UNK>
[ BZ - <UNK> ] avoid <UNK> <UNK> in <UNK>
[ DROOLS - <UNK> ] remove unnecessary System . out . println
added json . json
<UNK> the <UNK> refid classpath is not <UNK>
Updated README . md
add logo
<UNK> : fix <UNK> <UNK>
fix comment
Added classlib classlib classlib classlib classlib classlib classlib commit from commit
<UNK> : add <UNK> method to <UNK>
Translated using Weblate ( Hebrew ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Dutch ) Currently translated at 43 . 1 % ( <UNK> of 3102 strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hebrew ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 98 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Upper Sorbian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Italian ) Currently translated at 99 . 9 % ( <UNK> of 2594 strings )
Translated using Weblate ( Italian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Korean ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hungarian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Esperanto ) Currently translated at 100 . 0 % ( 1595 of 1595 strings )
Translated using Weblate ( Esperanto ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Hungarian ) Currently translated at 99 . 8 % ( <UNK> of 3376 strings )
Translated using Weblate ( Argentinean Spanish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Russian ) Currently translated at 99 . 8 % ( <UNK> of 641 strings )
Translated using Weblate ( Italian ) Currently translated at 99 . 8 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Arabic ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
remove unused import
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
<UNK> the <UNK> <UNK> to addError addError addError addError <UNK>
added comment
Updated the lesscode version to 0 . 4 . 1
Added large <UNK> to edu edu language
Removed test . props to false
<UNK> : <UNK> <UNK> <UNK>
README
Updating to - type > 3 . 6 . 2
fix typo in item
git - svn - id : https :// goclipse . googlecode . com / svn / trunk @ <UNK> 1731708e - d1f7 - 11de - a1df - 87ee4daaac7b
[ <UNK> ] Remove <UNK> . schema ()
Updates libjitsi @ 1 . 0 - 20160325 . 182640 - 122
Changes in translation
Added . gitignore
Update 6 Bezier . md
Added 4 PathFigureAndLogical . md
[ maven - release - plugin ] prepare release mango - 1 . 3 . 1
added a comment for the <UNK> <UNK>
fix <UNK> example
Removed marker from <UNK>
transaction <UNK>
<UNK> the <UNK>
add config repo
remove object method
ignore
<UNK> : fix <UNK> ()
fix null check
add travis - yml
Added eclipse dependency
[ Java ] Remove unused import
Added pom datumbox jar
Updated README
fix <UNK> "]' search
added missing ServiceIntegrationTests op op op op op op <UNK> <UNK>
exclude tmp folder in runner folder
<UNK> the <UNK> in the chat room room
Updated irc - api - jar to irc irc - api - jar
dispose the dispose window to the account
<UNK> : <UNK> <UNK> to isPinnedToTaskBar ConfigurationUtils <UNK>
<UNK> the <UNK> in the <UNK>
<UNK> : <UNK> private to private
add constant
build : add check
Updated syncthing to v0 . 14 . 13
<UNK> : <UNK> <UNK> to <UNK>
<UNK> : fix <UNK>
Updated copyright - 2000 to 2000 - 20015 - hamcrest - hamcrest : <UNK> : <UNK> : <UNK> . <UNK>
<UNK> : fix IDATA IDATA error in error
add travis CI
don ' t <UNK> setName setName setName <UNK>
[ pom ] Update emma </ 2 . 1 . 5320
Updated maven - release - plugin to 2 . 0 - beta - 9
fix typo git - svn - id : http :// protostuff . googlecode . com / svn / trunk @ <UNK> 3b38d51a - 9144 - 11de - 8ad7 - 8b2c2f1e2016
<UNK> log
updated to groovy 1 . 7 . 5
Added analytics analytics analytics analytics analytics analytics analytics can can be <UNK> in the build
Removed continue for <UNK>
Removed comment
Fixed regression in SilverlightImplementation SilverlightImplementation <UNK>
Made the <UNK> to getScrollable component
settings
Fixed typo in pom . xml
remove CNAME CNAME
[ Java ] Update version to 3 . 0 . Beta1
<UNK> the YzV00YM MZlZV772EMqzliBRP9b1o_rGvg meta
Added level level to logging
add some info
<UNK> the ab ab ab ab ab ab the <UNK> is not <UNK>
Updated pom
Added start all all all all files
Added coveralls plugin
gh - <UNK> - removed println
gh - <UNK> - fixed test
gh - <UNK> - added toString ()
added missing git - <UNK>
[ maven - release - plugin ] copy for tag lenskit - 1 . 2
[ maven - release - plugin ] copy for tag release - 0 . 11
<UNK> : <UNK> <UNK>
Upgrade to mockito - core 2 . 15 . 0
apk
add debug debug
add aspectjweaver aspectjweaver aspectjweaver aspectjweaver you is not you for <UNK>
Added target files to gitignore
<UNK> : add <UNK> to postinst postinst postinst - <UNK>
<UNK>
updated ChangeLog
add screenshot
[ maven - release - plugin ] prepare release HdrHistogram - 1 . 0 . 6
added test
Updated README
<UNK> the <UNK> build
Added log log
<UNK> <UNK> to support <UNK>
Edited wiki page About through web user interface
added toString () to hashCode group
fix for depth depth depth depth <UNK>
[ Gradle Release Plugin ] - new version commit : ' 1 . 4 . 11 - SNAPSHOT '
gradle
lintOptions lintOptions lintOptions lintOptions <UNK>
fix travis build
appveyor appveyor
update README
QQ1Group QQ1Group QQ1Group QQ1Group QQ1Group <UNK> <UNK> ' t <UNK>
<UNK> the <UNK> <UNK>
Added Travis CI to travis CI
fix for <UNK> <UNK>
<UNK> the _parseName _parseName _parseName _parseName int
Added <UNK> UI
Added <UNK> 2018 to LICENSE
Updated google - api - datastore - datastore - datastore - datastore - datastore - datastore : http :// datastore . googlecode . com / svn / trunk @ <UNK> <UNK> - <UNK> - <UNK> - <UNK> - <UNK>
Removed unused test
Updated README
broker / InterceptConnectMessage commit - <UNK> - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id - id -
changelog Former - commit - id : <UNK>
added onStart cancel
updated Other Other Other Other Other commit , id
todo
<UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
Updated version
<UNK>
<UNK> : Fix <UNK> <UNK>
Added a method to mongodb skip <UNK>
<UNK> <UNK> import
fix gdprTaxonomy link in components
fixed test
[ artifactory - release ] Next development version 3 . 1 . 7 . BUILD - SNAPSHOT
[ maven - release - plugin ] prepare release avaje - ebeanorm - 6 . 6 . 1
<UNK> : fix <UNK> ()
add README
[ jboss - fuse - 6 . 1 . x 173 ] Updating perfectus - build number to new build
registry
<UNK> customize customize customize customize customize <UNK>
[ pom ] Use JBoss Community Access Access Access Access <UNK>
Added a markdown for the <UNK> <UNK>
Updated gitignore
<UNK> : fix <UNK> email
runtime - core : Add <UNK> . getDbmsNameMeaning . postgresql . postgresql to PostgreSQL PostgreSQL database in <UNK>
<UNK> <UNK> cube when <UNK> is not <UNK>
update README
<UNK> . 0 . 10
Updated version
Updated gradle version
Bumped version to 1 . 1 . 0
Fixed a bug in setApnsServer port
Added maven - surefire - plugin to 2 . 22 . 0
Upgrade to helios - testing - 0 . 9 . 71
Added <UNK>
demo
fix : <UNK> ( final : <UNK> )
add screenshot
add 2016 . md
<UNK> changelog
Upgrade to gradle plugin
removed unused import
prepare for 4 . 4 . 3
[ Java ] Upgrade to gson 2 . 8 . 0
Fixed <UNK> <UNK> in PrimitiveValue hashCode - <UNK>
Upgraded to <UNK> 1 . 2 . 2
add build gradle
update gitignore
[ Java ]: Upgrade to Agrona 0 . 3 - SNAPSHOT
add img
Update the project version to 0 . 28 . 1 . Final - SNAPSHOT
added getter for Condition ( <UNK> )
working on Selenide 4 . 11
<UNK> : fix test chrome
release Selenide 4 . 10
add missing method to CHANGELOG . 6
[ maven - release - plugin ] prepare for next development iteration
[ maven - release - plugin ] prepare release javafaker - 0 . 4
<UNK> : fix <UNK> on sample
Fixed a bug in ios
[ N - 0 ] refactor <UNK>
Updated notes
Updated Danish translation
<UNK> the test
[ maven - release - plugin ] prepare release unirest - java - 1 . 3 . 2
v0 . 11 . 3
Removed debug message svn changeset : <UNK> / svn branch : trunk
Fixed bug in Table <UNK> svn changeset : <UNK> / svn branch : trunk
<UNK> <UNK> <UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
<UNK> <UNK> to 0 . 9 . 13
<UNK> <UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
<UNK> <UNK> svn changeset : <UNK> / svn branch : trunk
fix : <UNK> <UNK> <UNK> <UNK>
fix typo in <UNK>
expandAllNodes expandAllNodes expandAllNodes expandAllNodes expandAllNodes void expandAllNodes expandAllNodes <UNK> <UNK> <UNK> <UNK>
<UNK> 3 . 0 . 5
[ RESTEASY - <UNK> ] fix package name in KieContainerFromKieRepoExample example
Added serialVersionUID to MVELDialectRuntimeData serialVersionUID
<UNK> the <UNK> of the <UNK>
Added a missing codecInfo codecInfo codecInfo codecInfo omx OMX . g
fix javadoc
<UNK> travis
Updating to PGPlugin base class , cf [ Issue # 44 ]( https :// github . com / phonegap / phonegap - plugins / issues / 44 )
sample sample version
Translated using Weblate ( Persian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
progress <UNK> <UNK>
Translated using Weblate ( Esperanto ) Currently translated at 99 . 8 % ( <UNK> of 2331 strings )
Translated using Weblate ( Chinese ( Traditional )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Latvian ) Currently translated at 98 . 1 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Polish ) Currently translated at 99 . 9 % ( <UNK> of 3458 strings )
Translated using Weblate ( Spanish ( Argentina )) Currently translated at 100 . 0 % ( 3424 of 3424 strings )
Translated using Weblate ( Polish ) Currently translated at 99 . 9 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Sardinian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Chinese ( Simplified )) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
imports
Translated using Weblate ( German ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
fix <UNK>
Translated using Weblate ( Danish ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Translated using Weblate ( Belarusian ) Currently translated at 100 . 0 % ( <UNK> of <UNK> strings )
Fixed <UNK> <UNK>
[ maven - release - plugin ] prepare for next development iteration
<UNK> : fix <UNK> <UNK> when <UNK> is not <UNK>
fix <UNK>
update package
Removed unused code
Incrementing snapshot version to 1 . 0 . 2 - SNAPSHOT
Upgrade to Spring Cloud Camden . SR2
Updates libjitsi
mvn : Updates jicoco
gitignore
fix <UNK>
Update 10 RequestLayout md
Updated project . version
<UNK> : add a cleanup to BaseLiquibaseTask ant <UNK>
Added screenshot001 screenshot001 screenshot001 screenshot001 screenshot001 screenshot001 screenshot001 . x de
remove unused import
remove unused line
remove unused import
<UNK> the <UNK> <UNK> to the <UNK>
Updates the chat room room room room room room room room
<UNK> the <UNK> button when it is <UNK>
[ maven - release - plugin ] prepare release docx4j - 3 . 3 . 7
Removed unused import
Added a comment to the <UNK>
Updated TODO
fix <UNK> log
<UNK> <UNK>
Added screenshot
<UNK> version to 5 . 10 - SNAPSHOT
[ pom ] Update jmockit 1 . 22
Upgrade to Spring Boot 4 . 1 . 2 . RELEASE
fix null pointer
gh - <UNK> - Fixed typo in test
<UNK> the <UNK> to the <UNK>
added full full full full tests
gradle - 2 . 0 . all
removed <UNK> from XMLSerializer book
Upgrade to postgresql 9 . 3 - 1102 - jdbc4
fixed NPE in AbstractHost tag
modified CHANGES . txt
Updated launcher icon
Removed unnecessary TODO
add screenshots
Added [` isEven `](# [` `](# float )
bump pom to 4 . 3 . 0 - SNAPSHOT
add hawtio to docs
[ artifactory - release ] Release version 3 . 0 . 0 . RC1
<UNK> : Fix typo in <UNK>
fix <UNK>
minor , fix /). kylin . md
<UNK> kylin kylin kylin
Translated using Weblate ( Japanese ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Translated using Weblate ( French ) Currently translated at 100 . 0 % ( 170 of 170 strings )
Fixed issue with <UNK> <UNK> <UNK> <UNK> <UNK>
<UNK> <UNK> . pdf
fix test
test : fix typo in test
[ Java ] Upgrade to Mockito 2 . 2 . 16
Updated pydev feature feature to 6 . 4 . 3
Added travis - ci config file
Updated readme
added checks in checks to ElementDisappearsTest ElementDisappearsTest ElementDisappearsTest ElementDisappearsTest are <UNK> for <UNK>
added a test to the test
Made onStart onStart onStart onStart onStart onStart onStart onStart onStart onStart onStart openevent openevent - 412e ]
<UNK> org . reflect . codehaus . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy . groovy .
<UNK> : Fix <UNK> /*< implements implements <UNK> <UNK>
transient transient name in config . Configuration . core
<UNK> : fix setTimeout setTimeout setTimeout null on <UNK> Signed - off - by : <UNK> <UNK> < <UNK> @ <UNK> . de >
[ maven - release - plugin ] prepare release v0 . 2 . 16
<UNK> : fix build . sh
[ BZ - <UNK> ] add <UNK> to <UNK>
[ <UNK> - <UNK> ] fix kmodule packages in kmodule kmodule - plugin - by : <UNK> < kmodule - openhab . org
mysql - binlog - connector to 0 . 13 . 0
fix screen plugin
fix test
